- COPYING
- README.md
- bin/ovn-k8s-cni-overlay.py
- bin/ovn-k8s-overlay.py
- bin/ovn-k8s-watcher.py
- ovn_k8s/common/config.py
- ovn_k8s/common/kubernetes.py
- ovn_k8s/common/util.py
- ovn_k8s/common/variables.py
- ovn_k8s/modes/overlay.py
- ovn_k8s/processor/__init__.py
- ovn_k8s/processor/conn_processor.py
- ovn_k8s/watcher/endpoint_watcher.py
- ovn_k8s/watcher/pod_watcher.py
- ovn_k8s/watcher/service_watcher.py
- ovn_k8s/watcher/watcher.py
- requirements.txt
- setup.cfg
- setup.py
This starts with 3 utilities and a library.
The utilities are:
1. ovn-k8s-watcher.py
This is a daemon that is run in the k8s master node (where
OVN database resides too.). This daemon listens on the
k8s API server for events. It is interested in pod creation
and deletion. It is also interested in creation and destruction
of services and endpoints to setup load balancing and gateway rules.
When a pod gets created, it creates a logical port and asks
OVN to assign a IP address and MAC address. It uses this IP address
and MAC address to annotate the pod object in the API server.
2. ovn-k8s-cni-overlay.py
This is the CNI plugin for the overlay mode and resides
in every host where containers are run. When kubelet
spawns a container, it calls the CNI plugin with a few
env variables set.  Instead …
> Initial commit for Kubernetes integration with OVN.

- ovn_k8s/common/exceptions.py
- ovn_k8s/common/kubernetes.py
- ovn_k8s/modes/overlay.py
- ovn_k8s/watcher/endpoint_watcher.py
Leader election causes a lot of endpoint updates (see kubernetes
issue #23812). This implies that roughly every 2 seconds an endpoint
MODIFIED event is sent for processing, for every endpoint where
leader election is enabled (examples: kube-scheduler or
kube-controller-manager).
This patch leverages the so far unused object cache in the endpoint
watcher, sending the event only when ip changes are detected in the
endpoint data structure. To this aim, the logic for extracting ips
from the endpoint object has been moved from overlay.py into
endpoint_watcher.py
Also, tt is not to be taken for granted that given and endpoint,
there will always be a service with that name. This patch therefore
also adds explicit handling of 404 errors.
This is however a rather minor point as the final result of …
> Avoid continuosly handling events due to leader election annotations

- README.md
Tweak the README to clarify that the "overlay" mode applies to running
on bare metal as well as within VMs.
> readme: Note overlay mode applies to bare metal.

- ovn_k8s/common/util.py
Use the next() function to be compatible with Python 3.
> python3: Use next().

- ovn_k8s/modes/overlay.py
If we delete and re-create the logical port, dynamic addresses change.
So that breaks connectivity. This issue fixes it.
> overlay.py: Don't delete logical switch port before creating it.

- bin/ovn-k8s-overlay
The load-balancer on the external switch does not work when
there is a SNAT rule in the gateway router.
> ovn-k8s-overlay: Use the gateway router for North-South LB.

- README.md
Without a 'default_gw', north-south only works in
the connected subnet.
> README.md: Include default_gw in examples.

- bin/ovn-k8s-overlay
When we add a physical interface for a gateway, we copy
its IP address and MAC address and make it the IP address
and MAC address of the gateway router port in the logical space.
In the physical space, we add that interface as a port of br-int.
Once we do that, we should flush its IP address.
> ovn-k8s-overlay: Flush the IP address of physical interface.

- ovn_k8s/modes/overlay.py
When a logical port is created we write the log as info.
When we delete a logical port, it makese sense to apply
the same standard.
> overlay.py: Change a log statement from dbg to info

- CONTRIBUTING.md
The main rationale is to make the 'Signed-off-by:'
requirement official. The file is copied from
the main OVS repo with some modifications.
> Add a CONTRIBUTING.md file.

- ovn_k8s/modes/overlay.py
- ovn_k8s/watcher/pod_watcher.py
- ovn_k8s/watcher/service_watcher.py
Replace del statement with pop method, in order to avoid watcher
failures due to KeyError when deleting a pod.
There is at least one corner case where a pod is never processed
and therefore never stored in cache, and that would be when the
kube scheduler is down and does not come up before the pod is deleted.
It is worth noting however that the observed failure is not
critical as the watcher is restarted.
> Do not assume pod is always in cache on delete

- README.md
- bin/ovn-k8s-watcher
- ovn_k8s/watcher/watcher.py
We can now ask the watcher to exit with the run-time
command:
ovs-appctl -t ovn-k8s-watcher exit
We can list all the vlog modules:
ovs-appctl -t ovn-k8s-watcher vlog/list
We can run-time change the logging level of a particular module:
ovs-appctl -t ovn-k8s-watcher vlog/set overlay:file:DBG
> ovn-k8s-watcher: Add support for run-time commands.

- ovn_k8s/modes/overlay.py
- ovn_k8s/watcher/pod_watcher.py
- ovn_k8s/watcher/service_watcher.py
Replace del statement with pop method, in order to avoid watcher
failures due to KeyError when deleting a pod.
There is at least one corner case where a pod is never processed
and therefore never stored in cache, and that would be when the
kube scheduler is down and does not come up before the pod is deleted.
It is worth noting however that the observed failure is not
critical as the watcher is restarted.
Fixes: 06a8017bac85 ("Do not assume pod is always in cache on delete")
> Use 'pop' instead of 'del' when removing from cache

- ovn_k8s/watcher/watcher.py
A full traceback could be quite useful for debugging and troubleshooting.
This patch add an additional vlog.exception statement, preserving the
original vlog.warn statement, which has been only slightly changed to
enclose the exception reason in double quotes
> Log traceback when watcher fails

- bin/ovn-k8s-overlay
The latest kubernetes CNI integration [1] changed where the default CNI
configuration files are read from. This updates ovn-k8s-overlay to
generate it's configuration file in this new location.
[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/cni/cni.go#L38
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> ovn-k8s-overlay: Update CNI configuration file path

- ovn_k8s/common/kubernetes.py
- ovn_k8s/modes/overlay.py
- ovn_k8s/watcher/service_watcher.py
- ovn_k8s/watcher/watcher.py
When the watcher dies, it is possible that some
objects in k8s get deleted. When the watcher starts
again, we will miss those events and stale entries
will remain in the OVN database.
With this commit, we do the following steps.
1. Make a connection to k8s API server to get any
events from that time on. But we do not process
any of the events till step 3.
2. We connect to k8s API server and get all the
pod and services objects. We then compare it
with OVN database to sync them.
3. We now start processing new events from K8s API
server.
> Sync K8s objects with OVN objects.

- docs/INSTALL.K8S.md
Based on the bug https://github.com/kubernetes/kubernetes/issues/30681,
we should download CNI plugins from upstream repo for k8s to work.
And we now should also specify the --network-plugin-dir for kubelet.
> INSTALL.K8S.md: Update docs about upstream CNI plugin requirements.

- bin/ovn-k8s-overlay
Because we use tunnels, the MTU of the internal interface
should be low. We set the container network interface to
have a MTU of 1400, so we can do the same here.
> ovn-k8s-overlay: Set the MTU of internal interface lower.

- .gitignore
- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/provisioning/setup-hostnames.sh
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
- vagrant/provisioning/virtualbox.conf.yml
This commit adds a handy Vagrant setup to easily try out OVN integration with
Kubernetes. It allows a user to create a master node and 2 minion nodes, with
OVN configured with the latest upstream master code.
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> Vagrant: Add support to try this with Vagrant

- vagrant/README.md
- vagrant/provisioning/setup-k8s-master.sh
Add some logic to generate yaml files to bringup a simple Apache
pod, as well as both east-west and north-south load balancing
for the pod.
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> vagrant: Update and clarify examples

- vagrant/README.md
- vagrant/provisioning/setup-k8s-master.sh
Add the creation of an nginx pod to show OVN load balancing
between different pods.
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> vagrant: Add nginx pod to show OVN load balancing

- ovn_k8s/modes/overlay.py
Code will try to create a logical port even if the pod name
is not found in pod data. While this is however extremely
unlikely to occurr, if not impossible, this patch simply ensures
the if condition actually tests what we want to test.
The logical_port variable is indeed built from namespace and pod
name and will never be false in a test.
> create_logical_port: return if pod name not specified

- ovn_k8s/modes/overlay.py
The current code uses a string built from namespace and pod
name for verifying whether it's able to delete a logical port.
This string however can never fail a test. The test should check
the pod name. The condition in which a pod name is however empty
or None is extremely unlikely if not impossible.
This patch also contains minor improvements in log statements
in the same routine.
Signed-off-by: Salvatore Orlando salv.orlando@gmail.com
> delete_logical_port: abort if pod name not found

- README.md
commit fc7aeaf1437bdefacec112dbd4164eba9052c0b3
Author: zhou Huijing <zhou.huijing@zte.com.cn>
Date:   Mon Nov 28 03:40:56 2016 +0000
README.md: Set an unique system-id to identify an ovs
Signed-off-by: zhou Huijing <zhou.huijing@zte.com.cn>
diff --git a/README.md b/README.md
index 94b7a14..59af8d3 100644
--- a/README.md
+++ b/README.md
@@ -107,11 +107,14 @@ kernel version of 3.18 for geneve.  There is no stt support in upstream Linux.
You can verify whether you have the support in your kernel by doing a `lsmod |
grep $ENCAP_TYPE`.)
+$SYSTEM_ID is a unique identifier to identify each Open vSwitch in an OVN 
+deployment.If you start Open vSwitch manually, you should set one.
```
ovs-vsctl set Open_vSwitch . external_ids:ovn-remote="tcp:$CENTRAL_IP:6642" \ …
```
> README.md: Set an unique system-id to identify an ovs

- bin/ovn-k8s-cni-overlay
commit e7310ccc442a2639aad6d88af482d117b3051fd0
Author: zhou Huijing <zhou.huijing@zte.com.cn>
Date:   Tue Nov 29 07:01:17 2016 +0000
ovn-k8s-cni-overlay:log print missing a parameter
Signed-off-by: zhou Huijing <zhou.huijing@zte.com.cn>
diff --git a/bin/ovn-k8s-cni-overlay b/bin/ovn-k8s-cni-overlay
index 5562c8d..6b2a375 100755
--- a/bin/ovn-k8s-cni-overlay
+++ b/bin/ovn-k8s-cni-overlay
@@ -133,7 +133,7 @@ def setup_interface(pid, container_id, cni_ifname, mac_address,
return veth_outside
except Exception as e:
- vlog.warn("Failed to setup veth pair for pod" % str(e))
+vlog.warn("Failed to setup veth pair for pod: %s" % str(e))
command = "ip link delete %s" % (veth_outside)
call_popen(shlex.split(command))
raise OVNCNIException(100, "veth setup failure")
> ovn-k8s-cni-overlay:log print missing a parameter

- README.md
- bin/ovn-k8s-overlay
- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/provisioning/setup-minion.sh
This commit adds support for as many gateways as possible.  This needs a feature in OVN that will only be available with OVS 2.7. So we should consider creating a branch in ovn-kubernetes too.
This commit will likely need a rebase depending on the review of #54 as it includes changes from there. Only the last 3 commits in this series are relevant as the first 2 commits are actually part of #54
> Add support for multiple gateways

- ovn_k8s/modes/overlay.py
With multiple gateways, you can add new gateways
after a watcher is started.  It does not look
worthwhile to cache it and change documentation
to say that you should start watcher only after
initializing all gateways.
> overlay: Don't cache gateway IP addresses.

- bin/ovn-k8s-cni-overlay
- requirements.txt
Having to shell out is not nice just like having to worry about privsep.
Using pyroute solves the first problem, even if it does not really solve the latter (But with the current plugin execution model the responsibility of setting the right capabilities are on the kubelet)
Anyway, there are two commits in this PR.
The first is just about leveraging CNI_NETNS for the namespace path
The second introduces pyroute.
> Use pyroute2 in CNI plugin

- bin/ovn-k8s-cni-overlay
This triggers a misleading failure mode when there is an error while
retrieving pod annotations.
> Add missing 'raise' keyword

- ovn_k8s/tests/unit/test_exceptions.py
the base exception class for ovn_k8s was flawed (thanks @shettyg for spotting the issue!)
This PR fixes that and also add a unit tests which is always a decent thing to do.
> OvnK8sException should call constructor's init method

- README.md
- vagrant/provisioning/setup-master.sh
With OVS 2.7, one can no longer connect automatically to
TCP ports of OVN databases. You need to clearly specify
the connection type of either TCP or SSL. This commit
only provides information about TCP connection.  SSL
information is TBA.
> README.md: Update documentation for OVS 2.7.

- README.md
According to my test, i think it should be 'ovn-k8s-gateway-helper', thank you!
Signed-off-by: chentao1596 <chen.tao3@zte.com.cn>
> fix the wrong description of the installing process

- bin/ovn-k8s-cni-overlay
> ovn-k8s-cni-overlay: fix access to unitialized annotations dict.

- bin/ovn-k8s-overlay
When a system reboots, OVS internal device gets re-created. When
this happens, the MAC address needs to remain the same.
Fixes: #88
> ovn-k8s-overlay: Make mac address of internal device permanent.

- requirements.txt
> Add pip requirements to fix TLS validation issues.

- ovn_k8s/modes/overlay.py
> overlay: Maintain a cache for k8s container port name.

- bin/ovn-k8s-gateway-helper
When you share the same NIC for both mgmt and data
traffic, you need to track connections that are
initiated from the pods so that reverse connections
go back to the pods.
> ovn-k8s-gateway-helper: Fix traffic multiplexing.

- ovn_k8s/modes/overlay.py
There is a typo inside the sync_pods function.
When the logical port is created, it will have "external-ids:pod=true",
but inside the sync_pods function it will try to fetch existing logical
ports based on "external_id:pod=true" which will always return nothing
since the logical ports are not created with this tag.
The fix consists in changing the query to retrieve all the logical
ports having "external-ids:pod=true" instead of "external_id:pod=true".
> Fix typo inside sync_pods function

- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
Sometimes when vagrant environment is slow and some commands
fail, it is useful to run the commands manually again. Sometimes
while developement, it is useful to change scripts and re-run them.
In those cases, it is useful to store the passed arguments for reuse.
> vagrant: Store arguments in file.

- bin/ovn-k8s-overlay
Specifying the outport is not mandatory as OVN can figure this
out based on the IP address of the gateway.  But there are
environments like GCE where the default gateway is not in
the same subnet as the VM's IP address. In cases like that,
specifying the outport is useful.
> ovn-k8s-overlay: Specify the outport for the external gateway.

- setup.cfg
Having "/etc/openvswitch" instead of "etc/openvswitch" in setup.cfg
would not place the config file in the expected location.
The fix consists in changing "/etc/openvswitch" to "etc/openvswitch"
in setup.cfg.
Signed-off-by: Alin-Gheorghe Balutoiu <abalutoiu@cloudbasesolutions.com>
> config: Change setup.cfg config file location

- bin/ovn-k8s-overlay
Currently there is no Windows support when running the
minion init script.
This patch adds the posibility to run minion init on Windows
nodes in order to add them as minion nodes to a kubernetes
deployment.
The logic is the same as in Linux case, the difference is that
the Linux specific commands are replaced with their equivalent
powershell commands on Windows.
Signed-off-by: Alin-Gheorghe Balutoiu <abalutoiu@cloudbasesolutions.com>
> ovn-k8s-overlay: Add Windows minion init support

- README.md
- docs/config.md
- ovn_k8s/common/config.py
Relying on pip to place the config in a specific path does
not seem to be reliable.
We will now expect to find the config file in a default path.
The default path is "/etc/openvswitch/ovn_k8s.conf" on Linux
and "C:\etc\ovn_k8s.conf" on Windows.
If the config file is not found there, we are using the default
values which are stored in a dictionary inside config.py.
Signed-off-by: Alin-Gheorghe Balutoiu <abalutoiu@cloudbasesolutions.com>
> config: Cache the config values and fix Windows support

- go-controller/Makefile
- go-controller/hack/build-go.sh
- go-controller/hack/init.sh
- go-controller/hack/lint.sh
- go-controller/hack/verify-gofmt.sh
Two things in the PR:
1. Re-org hack/build-go.sh so that lint tools can re-use the symlink based GOPATH setup
2. hack/lint.sh and hack/verify-gofmt.sh
Ultimately we should run hack/{lint,verify-gofmt}.sh with travis, but it cannot be done right now since travis does not support multiple language installs (doing it manually will slow everything).
> lint and gofmt tools; not yet added to travis

- .travis.yml
- go-controller/hack/lint.sh
This PR enables go lint in travis CI.
> Enable go lint in travis

- vagrant/provisioning/setup-k8s-minion.sh
Kubernetes 1.6 expects a newer CNI.
Also, the --network-plugin-dir does not work with
k8s 1.6.
> vagrant: Update CNI to the latest version.

- go-controller/pkg/factory/factory.go
Without this change, the pod watcher would block and endpoint
watcher would never run.
> go-controller: Create go routines for pod and endpoint watcher.

- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
When a service is deleted, you will endup with a
situation where no endpoints are deleted.
This commit adds a service watcher which will delete all the
endpoints from the load-balancer when a service is directly
deleted.
> go-controller: Watcher to handle service delete events.

- .travis.yml
'make lint' takes up a lot of resources and is very slow.
Currently we are running it twice for each environment.
Avoid it.
> travis: Don't run 'make lint' twice.

- go-controller/pkg/cluster/master.go
@shettyg 
Bug found where hostsubnets would get re-assigned unnecessarily. Fix is to just check the annotation before assigning a new hostsubnet.
> do not override hostsubnet if one already exists for a node

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
Also, ovn-docker package is not needed for kubernetes.
> vagrant: Handle new libopenvswitch package in master.

- go-controller/pkg/cluster/bin/install_ovn.sh
- go-controller/pkg/cluster/bin/ovnkube-setup-master
- go-controller/pkg/cluster/bin/ovnkube-setup-node
Move ovn/ovs installation bits to another util script; ovnkube setup should not install packages, just init them. Currently the setup scripts end up forcing a particular package of OVS on the installation.
Package install should be left to cluster installers e.g. ansible
> Remove package install bits from setup scripts

- go-controller/pkg/cluster/bin/ovnkube-setup-master
Instead, the go-controller should be started with sudo.
@rajatchopra
> go-controller: don't use sudo in master setup script

- go-controller/pkg/ovn/pods.go
> pods.go: Use '--if-exists' while deleting logical port.

- go-controller/Makefile
- go-controller/hack/lint.sh
Currently we are getting gometalinter from master branch.
This gives us new issues everytime something changes in
gometalinter. With this commit, we use gometalinter.v1
> lint: Use gometalinter.v1

- docs/INSTALL.UBUNTU.md
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
Compiling OVS increases time. Also, compiling
everytime can get us bugs from OVS master branch.
So use a released version of OVS instead.
> vagrant: Install OVS with packages.

- vagrant/Vagrantfile
According to https://www.vagrantup.com/docs/providers/configuration.html,
we should be using the "override" method to handle different providers.
> vagrant: Fix vm box override for different provider.

- bin/ovn-k8s-overlay
The function fetch_ovn_nb() is called from all init function.
And we check for the variable args.nb_cert there. This will
give an exception if the same options are not available from
all the places it is called.
> ovn-k8s-overlay: Use certificate options for all init commands.

- vagrant/README.md
- vagrant/provisioning/setup-k8s-master.sh
K8s 1.7.x by default uses etcd 3.x
> vagrant: Update to support k8s 1.7.x

- ovn_k8s/modes/overlay.py
When I try to translate ovn-k8s-cni-overlay from python to go,
I found that I can't unmarshal the ovn annotations which get from the pod information.
Finally ,I found the reason, the ovn annotations in the pod look like follows:
ovn:{'gateway_ip': u'192.168.2.1', 'ip_address': u'192.168.2.3/24', 'mac_address': '0a:00:00:00:00:01'}
Actually it's not a standard json format, so I write some code to make it general, like follows:
ovn:{"gateway_ip": "192.168.2.1", "ip_address": "192.168.2.5/24", "mac_address": "0a:00:00:00:00:03"}
which make it more compatible.
> let ovn annotations which stored in pod comply with standard json format

- vagrant/provisioning/setup-k8s-master.sh
With the changeover to etcd 3.x cluster, it has been
observed that k8s-apiserver takes a longer time to
initialize. If it does not initialize in time, other
daemons that connect to it fail. There is clearly a
better way to script this up, but for the time being
increase the timeout.
> vagrant: Add extra wait times for k8s daemons.

- ovn_k8s/modes/overlay.py
Currently when a service of nodeport is created, we do not
add the clusterIP of that service in the cluster load-balancer.
This commit adds that support.
Fixes: #128
> overlay.py: Add clusterip when nodeport is created.

- README.md
It makes more sense to show the architecture diagram after
the text.
> README: Move overlay architecture to the end.

- go-controller/cmd/ovn-k8s-overlay/app/common.go
In the new golang port:
1. Downgrade a couple of "info" statements.
2. string(int) gives junk value. Use Sprintf instead.
3. don't try to access index greater than string length
> ovn-k8s-overlay: A few small fixes

- go-controller/pkg/ovn/ovn.go
Move the policy init function prior to WatchPods because create pod event callback refers to logicalSwitchCache and an init race can result in null pointer dereference.
@shettyg PTAL. Thanks.
> Fix an init race condition

- go-controller/Makefile
- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/util/kube.go
Bringing the cni plugin executable at par with python version.
- rename ovn-kube-cni-overlay to ovn-k8s-cni-overlay (because config file pkg/config/config.go:CniPlugin parameter should match)
- fix ovn-k8s-cni-overlay logging
- fix ovn-k8s-cni-overlay so that it can talk to an apiserver over ssl (with its own bearer token)
> Fix ovn-k8s-cni-overlay issues

- bin/ovn-k8s-overlay
Kubernetes emits events when pods are created. The event will contain
only lowercase letters of the hostname even though the kubelet is started
with a hostname that contains lowercase and uppercase letters.
When the kubelet is started with a hostname containing lowercase and
uppercase letters, this causes a mismatch between what the watcher
will try to fetch and what kubernetes provides, thus failing to
create the port on the logical switch.
Until the above is changed, switch to a lowercase hostname for
minion-init.
> ovn-k8s-overlay: Change node_name to be always lowercase

- README.md
Windows will not recognize ovn-k8s-overlay as a python script and
it needs to be explicitly run with python.
This commit adds the way in which minion-init should be executed
on Windows.
> README: Add details for minion-init on Windows

- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
Starting any of the watches will now allow for a processExisting function to be passed. This function can be used to match ovn's state to current list of active items and hence do some cleanup.
This PR does not do any cleanup, just provides for a way for the function to be passed.
@pravisankar PTAL, thanks.
> allow for a preprocessing callback for the watchers

- go-controller/cmd/ovn-k8s-overlay/app/common.go
- go-controller/cmd/ovn-k8s-overlay/app/master_init.go
- go-controller/cmd/ovn-k8s-overlay/app/minion_init.go
- go-controller/pkg/util/util.go
Use constants for argument names to turn potential code errors
into compile time errors instead of runtime ones. urfave/cli
returns "" if the argument isn't defined, so mistyping the arg
name in the code could cause unexpected behavior during parsing.
Also unify the common args between master and minion to reduce
code duplication.
> ovn-k8s-overlay: reorganize args parsing

- go-controller/Makefile
- go-controller/pkg/cluster/node.go
Also keep the original name of the executable; no reason to call it
ovn_cni, as CNI doesn't care what it's called, it just runs whatever
its given.
> ovnkube: depend on out-of-band install (make install, RPM¸ deb, etc) for CNI plugin

- go-controller/pkg/util/net.go
@shettyg PTAL
I have tested this. We need this randomization at the very least. Eventually we could use something more deterministic like using IP-address -> MAC.
> fix random to be random enough across multiple initializations

- go-controller/hack/build-go.sh
rpmbuild and rpmlint expect every executable to have a buildid.
golang doesn't add the buildid so add it explicitly.
> Add "buildid" to excutable

- docs/ovn-k8s-overlay.1
- docs/ovn-kube-util.1
- docs/ovnkube.1
First draft of man pages for:
ovn-k8s-overlay
ovn-kube-util
ovnkube
They are based on "help" output from the commands.
This is part of building an RPM for fedora.
> Added man pages for utils

- go-controller/hack/build-go.sh
-a means "force rebuild packages that are already up-to-date", which
makes builds take longer, but worse tries to install things to the
system gopath that it shouldn't touch:
```
hack/build-go.sh cmd/ovnkube/ovnkube.go
WORK=/tmp/go-build173037572
runtime/internal/sys
mkdir -p $WORK/runtime/internal/sys/_obj/
mkdir -p $WORK/runtime/internal/
cd /usr/lib/golang/src/runtime/internal/sys
/usr/lib/golang/pkg/tool/linux_amd64/compile -o $WORK/runtime/internal/sys.a -trimpath $WORK -goversion go1.9.2 -p runtime/internal/sys -std -+ -complete -buildid 1c8a63759c54727d75e76055a9cf70042cbecdee -D _/usr/lib/golang/src/runtime/internal/sys -I $WORK -pack ./arch.go ./arch_amd64.go ./intrinsics.go ./stubs.go ./sys.go ./zgoarch_amd64.go ./zgoos_linux.go ./zversion.go
mkdir -p …
```
> hack: don't pass -a to 'go install'

- go-controller/README.md
Node process does not install the cni binary now. It will be done by make install or whichever way the software is chosen to be installed.
Redo #194, that one got closed accidently by an empty commit. 
/cc @shettyg
> reflect changes to install process

- go-controller/hack/init.sh
The test was to get past a travis problem. This is no longer an
issue.
golang is going to version 1.10 and the test breaks since
testing version < 1.5 will pass
> hack - eliminate golang version test

- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
We can now pass something like
-logfile="/var/log/openvswitch/ovnkube.log" for
logrus to log to.
> ovnkube: Ability to set logfile.

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/util/ovs.go
Currently, the code makes an assumption that the platform
is RHEL or Fedora. This expands the scope to Ubuntu and
also makes sure that the code does not error out on
VMware Photon platform.
The second patch of the series adds ovn-remote, ovn-encap-type 
and ovn-encap-ip for master too.
> go-controller: Handle services in different platforms.

- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/ovs.go
If nodeport is not enabled, we can program the gateway
bridge with static flows to enable all exited traffic
from pods to re-enter. With this, we don't need to run
ovn-k8s-gateway-helper on all the gateways.
> cluster/node: Program the gateway bridge for egress.

- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node.go
One can currently pass -gateway-interface to specify the
physical interface to use for a OVN gateway. With this patch
you can specify -gateway-spare-interface to directly
attach the -gateway-interface to br-int.
> cluster/node: Direct attach of gateway physical interface.

- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
The golang watcher and utilities have come of age.
So we can replace most python utilities with golang
ones.
We still have one python utility -  ovn-k8s-gateway-watcher
that will still be used with this vagrant.
> Vagrant: Use golang watcher and utilities.

- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/management-port.go
Currently, we need to manually add a route to access k8s services
from the node.
This commit lets us access the services from nodes without manual
intervention. This is also useful when you run ingress controllers
and they need to route to service IPs.
> go-controller/cluster: Setup routes for service-cluster-ip-range.

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/ovn.go
Make the factory more of a watcher factory, instead of something that creates the OVN and Cluster controllers itself.  Lets us make the controllers more self-contained and unit-testable in the future.
> go-controller: informer factory refactor and minor cleanups

- .travis.yml
- go-controller/Makefile
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/hack/build-go.sh
- go-controller/hack/init.sh
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_windows.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/util/nicstobridge.go
- go-controller/pkg/util/ovs.go
This patch adds support for doing minion-init on a Windows host.
The following changes were made:
- Add check for master / gateway init on Windows hosts which is
currently not supported
- Update build scripts to compile the Windows version of ovnkube.
The binary will be found in _output/go/windows/ovnkube.exe
- Moved the gatewayInit code in another file and added conditional
compilation. The gatewayInit is making use of "github.com/vishvananda/netlink"
package which does not compile on Windows.
- Implemented configureManagementPort for Windows. Added the equivalent
commands for enabling the interface, setting IP and the rest.
- Added conditional compilation for nicstobridge.go which is used
only in gatewayInit and imports the package "github.com/vishvananda/netlink"
- Added equivalent …
> go-controller: Add Windows support for minion-init

- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/cmd/ovn-k8s-overlay/app/gateway_init.go
- go-controller/cmd/ovn-k8s-overlay/ovn-k8s-overlay.go
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/nicstobridge.go
The project has been renamed from Sirupsen to sirupsen.
The conflicting imports mixing upper- and lower-case of
the package are causing issues.
More details here:
https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276
I encountered this issue while trying to import a package which was using Sirupsen with lowercase.
I got the following error:
```
case-insensitive import collision: "github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/sirupsen/logrus" and "github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/Sirupsen/logrus"
```
> Change Sirupsen to sirupsen

- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
The config is not fetched before using config.LogPath variable.
This makes the CNI plugin to always use the default value of LogPath
regardless of the value given in the config file.
This patch fixes this issue by fetching the config before using
any values from it.
> ovn-k8s-cni-overlay: Fetch the config before using config values

- .travis.yml
The travis tests were ignoring intermediate failures
in golang tests. For e.g., 'make gofmt' failing would
not fail the entire test. This commit takes this
opportunity to retire python checking and to move
exclusively to golang. This also will cause failures
if any intermediate step fails.
> travis: Move exclusively to golang.

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/policy.go
1. policy: Handle "<none>" label selectors.
2. policy: Don't wait forever for a namespace event.
> Network policy fixes

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
When ovnkube watcher starts, sync k8s resources with OVN backend
including pods, policies, and namespaces. If there is any obsolete
resource left on OVN after k8s resource has been deleted, clean up
the stale resource from OVN.
Signed-off-by: Tong Liu <tongl@vmware.com>
> Sync k8s resources with OVN backend when watcher starts

- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
Adds default config path for Windows based on the OVS_SYSCONFDIR
environment variable which is set by the OVS installer.
The if was removed from the CNI config file creation.
Now it is been enabled on Windows as well.
> config: Add default config path and create CNI config on Windows

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
With OVS 2.9 released, we have a conflict with package
installations in vagrant. It installs 2.9 version of
libopenvswitch by default. This makes libopenvswitch version
explicit.
> vagrant: Explicitly set libopenvswitch version.

- go-controller/pkg/config/config.go
We currently fail when certificate bootstrapping fails.
Instead, just log the error. If the certificate in
question is indeed being used, then the utility which
uses it will eventually fail.
> config: Don't fail after certificate bootstrapping fails.

- go-controller/pkg/util/gateway-init.go
When we moved from python gateway-init code to
golang gateway-init code, we missed specifying outport
name for the default route for gateway router. This
becomes a problem when we run in GCE where there are
/32 IP addresses and we need to specify the outport
name.
> gateway-init: Add outport name for default next hop.

- go-controller/Makefile
- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_linux.go
- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_windows.go
- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/pkg/config/config.go
This patch adds CNI plugin support on Windows.
The following changes were made:
- The Makefile was updated to include also the CNI when
doing 'make windows'
- The platform specific code from ovn-k8s-cni-overlay
was moved outside the original file in 'helpers_linux'
and 'helpers_windows' which will only build on linux/windows
Signed-off-by: Alin Balutoiu abalutoiu@cloudbasesolutions.com
> ovn-k8s-cni-overlay: Add Windows CNI support

- go-controller/pkg/ovn/management-port.go
Fix the IP used to create the route for service cluster ip range.
It should be clusterServiceIP and not clusterIP.
This is an issue when the service cluster ip range is outside
the cluster subnet.
> ovnkube: Fix route add for service cluster ip range on Windows

- go-controller/pkg/config/config.go
It so happens that on the master node if SSL configuration is already present,
then running ovnkube on the master will hang at the following command invocation
$ ovn-nbctl set-ssl /etc/openvswitch/ovnnb-privkey.pem \
/etc/openvswitch/ovnnb-cert.pem /etc/openvswitch/cacert.pem
The only way to make ovnkube to proceed at this point is to either perform:
- ovn-nbctl del-ssl
- ovn-nbctl clear nb_global . ssl
The following patch prevents this situation, by deleting the SSL configuration
before we call set-ssl
Reviewed-by: Ram Vepa <rvepa@nvidia.com>
> ovnkube: Prevent ovnkube from hanging if SSL configuration is already present

- go-controller/pkg/config/config.go
The OVN addresses from external_ids will have format
ssl:1.2.3.4:6641 but we need to store them in URL format,
i.e. ssl://1.2.3.4:6641.
This will cause issues when trying to read the OVN
addresses from external_ids which will cause a crash
with error "missing port in address". This happens
if the components try to read the OVN addresses from
external_ids.
This commit fixes the issue by replacing the first
occurence of ':' with '://' when fetching the address
from OVS external_ids.
> config: Fix OVN address when fetching from external_ids

- test/integration/README.md
- test/integration/ansible.cfg
- test/integration/build/openshift.yml
- test/integration/build/ovnkube.yml
- test/integration/golang.yml
- test/integration/hosts
- test/integration/main.yml
- test/integration/openshift-dind-test.yml
- test/integration/system.yml
- test/integration/vars.yml
Testing infrastructure based on openshift. The ansible playbooks intend to be invoked by a ci/cd mechanism (e.g. jenkins). The prereqs require a merged branch of ovn-kubernetes be available at the following location: $GOPATH/github.com/openvswitch/ovn-kubernetes
Manual entry point is main.yml with two tags present: setup, integration. 'setup' sets up the env, and 'integration' runs the DinD (docker in docker) tests. The infrastructure can be expanded upon later.
Next tasks:
1. build a kubernetes end-to-end test infrastructure
2. infrastructure for locally written tests
> ansible based ci/cd testing infrastructure based on openshift on DinD setup

- go-controller/pkg/util/gateway-init.go
We were adding a route to the gateway router with a outport
of a gateway router port. But the gateway router was not yet
created. This resulted in some error messages in ovn-northd.log.
But were harmless as we would eventually create the port.
This commit does the route addition after the router port is
created.
> gateway-init: Add the next hop after router port creation.

- go-controller/Makefile
- go-controller/hack/lint.sh
We seem to be getting travis CI timeouts on the linting, which
does take a while.  Instead of just bumping up the travis timeout,
show some linting progress.
@shettyg @rajatchopra
> build: show lint progress so travis doesn't time out

- README.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/gateway_init.go
If -nodeport is specified while running 'ovnkube -init-node',
then do a watch on kubernetes API server for services.
When a nodePort is created, program the local bridge to
send traffic headed to nodePort to the pods.
Co-authored-by: YaoZengzeng <yaozengzeng@zju.edu.cn>
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>
> gateway_init: golang version of ovn-k8s-gateway-helper.

- vagrant/provisioning/setup-k8s-minion.sh
- vagrant/provisioning/setup-minion.sh
Now that we have the golang gateway helper, use it
in vagrant. This means that we no longer need
pip and the python installation. Also, since
passing -nodeport to '-init-node' now means that
ovnkube will run forever, we need to run it in
background.
> vagrant: Use golang gateway helper.

- README.md
Instead of a duplicate command to run in the background,
ask to run in the background and then look at log files
for errors.
> README.md: Add a note on checking log files.

- vagrant/provisioning/setup-k8s-minion.sh
With -nodeport as an option, we should run ovnkube in
background with a nohup.
> vagrant: Run ovnkube with nohup on minions

- README.md
- go-controller/pkg/util/nicstobridge.go
When we create a gateway, we automatically add the
physical interface as a port of OVS bridge and move
the IP address from physical interface to OVS bridge.
When the machine is rebooted, this will cause OVS
to recreate the bridge - but not move the IP address
resulting in not being able to ssh to the box.
With this, we will add '--delete-transient-ports' to
/etc/default/openvswitch[-switch] so that when OVS
is restarted it will not add the physical interface
to the bridge.
You will have to run ovnkube again for it to be readded
to the bridge.
> nicstobridge: Make nicstobridge transient.

- go-controller/pkg/util/gateway-init.go
Let us say that we are initializing multiple gateway nodes at the same
time. The code in gateway-init.go tries to retrieve the next available gateway
IP by contacting NB. Even though there is code in place to lock NB DB for this
operation, the lock is released too soon. As a result, we end up in a
situation where all the gateway nodes get the same IP address.
Reviewed-by: Ram Vepa <rvepa@nvidia.com>
> ovnkube: race while generating gateway IPs

- go-controller/pkg/cluster/node.go
- go-controller/pkg/util/ovs.go
Let us say that SSL is in use between OVN host and OVN central. So, when
ovn-controller is restarted it expects the SSL client keys to be specified in
/etc/default/ovn-host as below:
OVN_CTL_OPTS="--ovn-controller-ssl-key=/etc/openvswitch/ovncontroller-privkey.pem
--ovn-controller-ssl-cert=/etc/openvswitch/ovncontroller-cert.pem
--ovn-controller-ssl-bootstrap-ca-cert=/etc/openvswitch/ovnsb-cert.pem"
If these keys are not present when ovn-controller is restarted, then
ovn-controller will fail to connect to OVN Southbound DB. During the
invocation of ovnkube on a K8s node we take all the parameters required to
connect to OVN Southbound DB. This patch takes those parameters and adds it to
/etc/default/ovn-host as part of the bring up and avoids one extra manual step
of user populating …
> ovnkube: restart ovn-controller with SSL keys for SouthBound DB

- vagrant/provisioning/setup-minion.sh
Now that ovnkube populates /etc/default/ovn-host, let
ovnkube populate it.
> vagrant: Don't add contents to default file manually.

- go-controller/pkg/cluster/master.go
- vagrant/provisioning/setup-master.sh
On a master node too, we run ovn-controller (because
we create a logical switch and a management port for
master.). This keeps the behavior consistent with
ovnkube when run for nodes.
> cluster/master: restart ovn-controller.

- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
In the case where ovnkube was executed with all the information provided on
the CLI, we only persist k8s-api-server and k8s-api-token as external IDs in
Open_vSwitch table. This results in ovn-k8s-cni-overlay to fail in
InitConfig()  and as a result no networking is configured for the pod.
When SSL is in use, the CNI looks for CA certificate and it cannot find
it. This patch fixes the issue by persisting k8s-ca-certificate in
Open_vSwitch table.
> ovnkube: persist k8s CA certificate file path in Open_vSwitch external_ids column

- go-controller/pkg/ovn/management-port.go
If OVS fails to retrieve the mac address of the k8s interface
created on the host, it will return "[]" instead of "".
This means that the error will not be catched and it will try
to continue which will give misleading error messages. This will
happen when it will try to add the port in OVN.
This patch also fixes some log messages which were not logging
the interface name variable.
> ovn: Fix error catching when fetching the mac address

- go-controller/pkg/util/ovs.go
We check the platform value as specified in the key 'Name'/'NAME'. For RHEL an example os-release file is:
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
```
Perhaps, we should change the key from 'Name' to 'ID', but for now this fix is needed. Tested and verified for RHEL 7.4!
Signed-off-by: Rajat Chopra …
> fix platform string match for RHEL

- go-controller/cmd/ovn-kube-util/app/nics-to-bridge.go
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
- go-controller/pkg/util/nicstobridge.go
This patch adds a subcommand bridges-to-nic to ovn-kube-util to restore back
the NIC interface that was added to OVS bridge as part of gateway
initialization. That is, given breth0 it moves the IP/routes associated with
breth0 to eth0 and then deletes the OVS bridge breth0.
I have renamed arguments to saveIPAddress(), delAddRoute(), and saveRoute()
so that I could reuse those functions to bridges-to-nic.
> ovn-kube-util: provide bridges-to-nic subcommand

- go-controller/cmd/ovn-kube-util/app/nics-to-bridge.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/util/nicstobridge.go
Instead of just bailing out of the given (or autodetected) gateway interface is already an OVS bridge, check if it looks like an already configured nic-to-bridge and try to use it.
@rajatchopra @shettyg @alinbalutoiu
> gateway: try to recover from already-initialized nic-to-bridge

- vagrant/README.md
ovnkube silently fails to start on minions if the minion VM gets
provisioned before the master. Provide the order in which VMs should
be started to avoid surprises.
Signed-off-by: Jakub Sitnicki <jkbs@redhat.com>
> vagrant: Instruct the user to start VMs in a particular order.

- go-controller/pkg/ovn/policy.go
When syncing network policy, it reports "Spurious object" error.
This patch fix the correct way to get network policies.
> Fix a network policy typo

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/policy.go
Put the DeletedFinalStateUnknown handling in one central place.  That
requires knowing the object type so convert the handler add functions
to pass it around.
While we're there, get rid of the internal informer tracking since
the SharedInformerFactory already has an internal map of informers
for each object type.
@shettyg @rajatchopra 
Yeah, this conflicts with https://github.com/openvswitch/ovn-kubernetes/pull/260... but it makes some of the same changes and cleans some stuff up.
> pkg: consolidate informer creation and object deletion handling

- docs/ovnkube.1
- go-controller/README.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
Current, ovn controller only runs on one kube master node with one
central OVN database. In case of failover, all kube nodes data are
gone. This patch recontructs OVN database on a new kube master
node after failover including node's logical switch, management
port etc. The HA mode can be invoked by --ha command arg.
e.g. ovnkube -net-controller -init-master -ha
Signed-off-by: Tong Liu <tongl@vmware.com>
> Add HA support by rebuilding OVN database for cluster nodes

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/util/ovs.go
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
- vagrant/provisioning/setup-minion.sh
Containerized/daemonset ovnkube shouldn't talk to service managers to
start/restart things it depends on.  Those things may even be containers
themselves which are not managed by systemd.
Instead, dependencies on OVS and northd should be handled by whatever
manages the lifecycle of ovnkube, whether that's systemd (via .service
files and Requires:) or Kubernetes (via front-end scripts that wait for
the dependencies to be ready).
For ovn-controller, we have verified that 2.8 and later automatically
pick up new ovn-remote external-ids and SSL certificates pushed to
the OVSDB via 'set-ssl'.  It no longer needs to be restarted or have
certificates persisted in config files, since all that information
is available from the OVSDB.
@alinbalutoiu anything we need to do on Windows to make sure the …
> cluster: don't start OVS, ovn-northd, or ovn-controller services

- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
When ovnkube is being used as a daemon the --pidfile \<path-to-pidfile\>
option creates a file containing the pid.
If ovnkube tries to start and the file exists, the attempt fails.
The file is deleted when ovnkube terminates.
ovn-kubernetes issue: 310 add flag to generate pid file
Signed-off-by: pecameron <pcameron@redhat.com>
> Add ovnkube --pidfile

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/ovs.go
go-controller: Use a timeout for local unix socket calls.
Currently, we are running ovn-nbctl commands in the watcher
to program OVN NB database whenever there are events from
kubernetes. But there is no timeout for these calls. If for
some reason, the command hangs, then our watcher will be
blocked.
With this commit, we will use RunOVNNbctlUnix() function
from util package. The return type is alredy stringified
with spaces and quotes removed. So at some places, I
had to remove the string conversions and trimming spaces
and quotes.
> go-controller: Use a timeout for local unix socket calls.

- vagrant/README.md
kubectl is part of $PATH in master.
> vagrant: Avoid need of absolute path.

- go-controller/pkg/util/gateway-init.go
Running gateway-init multiple times (a valid scenario
with a reboot) would create multiple duplicate NAT entries.
This prevents it.
> gateway-init: Prevent duplicate NAT entries.

- docs/ovnkube.1
- go-controller/README.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/remove-node.go
You can run this on a master node:
ovnkube -remove-node=k8sminion2
Or run this on any other node:
ovnkube -remove-node=k8sminion2 \
-nb-address=$NB_ADDRESS \
-nb-client-privkey /etc/openvswitch/ovncontroller-privkey.pem \
-nb-client-cert /etc/openvswitch/ovncontroller-cert.pem \
-nb-client-cacert /etc/openvswitch/ovnnb-ca.cert
The code does not try to remove the OVS bridge on the node. The
thought process is that:
1. We already have a 'ovn-kube-util bridges-to-nic' option for that.
2. We want to be able to run this command on the master.
3. We can in the future have a node watcher in master that will
call this whenever a node gets deleted.
> ovnkube: Ability to remove node.

- go-controller/pkg/util/kube.go
In a daemonset Kubernetes will provide the apiserver address via
the container environment and will map the token and CAcert into
/var/run/secrets/kubernetes.io/serviceaccount/.
So if neither the kubeconfig nor the apiserver are given via
configuration, try to read the necessary information from the
container environment instead.
@rajatchopra @shettyg @pecameron
> pkg/util: fall back to reading kubeconfig from container environment

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/service.go
Fixes #134 
We do not need to maintain a cache of container port names to integers. Matching the endpoint's ports are created after resolving the port names. To match the correct svcPort to the matching endpointPort, we can just match the servicePortName.
Tested by hand.
> support named ports for services

- docs/INSTALL.UBUNTU.md
The packages from there has a bug with OVS 2.9.x.
I will maintain a repo for OVS/OVN till we have a more
official way of supporting it.
We also don't need python libraries anymore.
> docs: Remove packages.wand.net.nz for debian packages.

- go-controller/pkg/config/config.go
Looks like with OVS 2.9.1, we need to del-ssl before
we set-ssl if there are values in SSL table.
> config: Use del-ssl before set-ssl.

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
We were using packages.wand.net.nz to download deb files for OVS/OVN.
But, with OVS 2.9.x, they have changed the startup scripts
to be different than what we provide in OVS. Their startup
scripts have bugs in them.
So I decided to create a new debian repo for ovn-kubernetes
project - till we have a better solution.  We need this
because OVS 2.9.1 was released last week and it has fixes
that we can take.
OVS 2.9.1 also has raft based clustering for OVSDB databases.
> vagrant: Use a custom debian server.

- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_linux.go
- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_windows.go
- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
This commit removes the Windows specific workarounds and makes it
look more similar to the Linux code.
The endpoint name should not depend on the container details passed
to the CNI (e.g. container ID). This is because kubelet calls
at the moment the CNI for every container within a pod when it should
be called only for the sandbox container.
> ovn-k8s-cni-overlay: Update Windows CNI and remove the workarounds

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
Instead, wait for pod modify event to come with
it set. Without this, even a single pod can
delay the logical port creation pipeline by 30 seconds.
> pods: Avoid loop wait for pod.Spec.NodeName

- docs/ovn-kube-util.1
- go-controller/cmd/ovn-kube-util/app/gateway_init.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/util/gateway-init.go
We currently, always create 2 LBs (one for TCP and one for UDP)
when a gateway router is created, irrespective of whether
nodeport is needed. When the cluster size increases, we are
increasing the number of objects that OVN daemons need to
process unnecessarily.
> gateway-router: Flag to enable nodeport load-balancers.

- contrib/roles/linux/openvswitch/vars/ubuntu.yml
Until now version 2.8 of OVS was used since there was a bug when using
'nodeport'. For more information see:
https://github.com/openvswitch/ovn-kubernetes/issues/272
The issue is now fixed, and this patch bump the version used by the playbooks.
> Bump OVS version used by ansible:

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
Without this, it is hard to figure out where in the code
the error came from.
> cluster: Add a error message.

- README.md
- docs/INSTALL.SSL.md
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
6641 and 6642 is what OVN uses by default. Stick to it.
> docs/vagrant: Use default ports that startup scripts use.

- go-controller/pkg/cluster/master.go
When a k8s node is deleted, we can remove OVN
objects in the central DB associated with that node.
> cluster: Remove OVN objects for a node deletion.

- go-controller/cmd/ovn-k8s-cni-overlay/app/bandwidth.go
- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_linux.go
- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_windows.go
- go-controller/cmd/ovn-k8s-cni-overlay/app/ovs.go
- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/vendor/github.com/vishvananda/netlink/handle_unspecified.go
- go-controller/vendor/github.com/vishvananda/netlink/link.go
- go-controller/vendor/github.com/vishvananda/netlink/link_linux.go
- go-controller/vendor/github.com/vishvananda/netlink/neigh.go
- go-controller/vendor/github.com/vishvananda/netlink/neigh_linux.go
- go-controller/vendor/github.com/vishvananda/netlink/netlink_unspecified.go
- go-controller/vendor/github.com/vishvananda/netlink/rule.go
- go-controller/vendor/github.com/vishvananda/netlink/rule_linux.go
- go-controller/vendor/vendor.json
OVN's QoS needs some clarification, as the manpages state that the QoS table only works with userspace DPDK.  Until that happens (and if true, QoS gets implemented for non-DPDK), implement bandwidth shaping by porting the openshift-sdn code over that handles it directly in OVS.
Not supported on Windows for now; @alinbalutoiu any idea what that would take?
> ovn-k8s-cni-overlay: implement bandwidth shaping outside OVN

- go-controller/pkg/config/cni.go
Use ioutil.TempFile to create a temportary file for the CNI config,
write to it, and move to 10-ovn-kubernetes.conf.
Signed-off-by: Bo Gan <ganb@vmware.com>
> config: Use temporary file and rename to write CNI config atomically

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/util/kube.go
…sn't exist
k8s apiserver's CACert might not need to be specified explicitly.
In some k8s cluster, apiserver's CACert is trusted automatically on the host,
e.g., part of /etc/pki/tls/certs/ca-bundle.crt.
Signed-off-by: Bo Gan <ganb@vmware.com>
> util: default to host CA bundle for k8s CACert

- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/gateway_init.go
- vagrant/provisioning/setup-k8s-master.sh
gateway: Add a localnet gateway.
There are k8s deployments with only master node (as a starting
point). And sometimes they just deploy a DNS pod or some other
pods in the master node. The DNS pod in pod network will go into a
crash loop because it cannot access the k8s daemons' IP in host
network.  Even if we deploy a OVN gateway on master, this won't
help because OVN gateway will have the same IP as the host IP. 
Currently in OVN we create gateways in minions only. We can also
create a gateway in master, but we do need 2 NICs there.
This commit lets OVN handle master-only deployment. This is done
by creating a "localnet OVN gateway" on master. A localnet OVN gateway
is just a regular OVN gateway, but with a local physical interface
connected to it. When ovnkube is run with …
> gateway: Add a localnet gateway.

- contrib/roles/windows/kubernetes/tasks/start_kubelet.yml
By default kubelet logs on STD_ERR and not to the files.
This commit adds a command line argument to instruct kubelet to log
in files rather than STD_ERR.
> Add logging to kubelet on Windows

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
Which means that docker can't be installed, which means that
kubelet can't start, which means not much works.
Replace with keyserver.ubuntu.com which is probably more reliable.
k8s-master: + sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
k8s-master: Executing: /tmp/tmp.fIFMpo6bEb/gpg.1.sh --keyserver
k8s-master: hkp://p80.pool.sks-keyservers.net:80
k8s-master: --recv-keys
k8s-master: 58118E89F3A912897C070ADBF76221572C52609D
k8s-master: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
k8s-master: gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
k8s-master: gpg: no valid OpenPGP data found.
k8s-master: gpg: Total number processed: 0
k8s-master: gpg: keyserver …
> vagrant: p80.pool.sks-keyservers.net appears to be down

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cnishim.go
Or, supposedly if cniserver responds accurately to a 0.2.0 request with a 0.2.0 response, the cnishim will still return a current version result.
@dcbw Can you urgently take a look at this? I somehow get an error on Windows with an older kubelet where the response is expected to be 0.2.0 and the one given by ovn fails to translate properly (no IP addresses).
> cni result should be versioned according to the one asked for

- go-controller/cmd/ovn-kube-util/app/gateway_init.go
- go-controller/cmd/ovn-kube-util/app/nics-to-bridge.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/testing/testing.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/ovs.go
@shettyg @rajatchopra this is the first bit.  An alternate approach is to make *all* exec commands filter through a central file that has a global for the runner, but that makes it a bit harder to manage unit testing.
Follow-on PR will more extensively test pkg/cluster.
> go-controller: use exec interface to run external binaries to help unit-testing

- README.md
- dist/Makefile
- dist/READMEcontainer.md
- dist/ansible/scripts/ovn-setup.sh
- dist/images/Dockerfile
- dist/images/Makefile
- dist/images/ovn-config.sh
- dist/images/ovn-debug.sh
- dist/images/ovn-run.sh
- dist/images/ovn_k8s.conf
- dist/images/ovnkube.sh
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- docs/INSTALL.OPENSHIFT.md
- go-controller/pkg/util/kube.go
Create a container image for ovn, configure and run from openshift
daemonsets.  As of OCP-3.10 openshift is in containers. The network
sdn is also in containers.
See dist/READMEcontainer.md, docs/INSTALL.OPENSHIFT.md for details.
> Containerized ovn openshift/RHEL/centos/fedora

- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_test.go
- go-controller/pkg/ovn/ovn_suite_test.go
- go-controller/pkg/testing/testing.go
- go-controller/pkg/util/ovs.go
Unit tests were developed against pre-cleaned-up Windows management
port commands to ensure cleanups didn't change the command sequence.
@shettyg @rajatchopra @alinbalutoiu
> ovn: unit test management port creation and clean up Windows bits

- go-controller/pkg/ovn/pods.go
Otherwise, we may end up having duplicate addresses.
> pods: Clear dynamic addresses while setting static addresses.

- go-controller/pkg/ovn/management-port.go
Modify all powershell commandlets that operate on the management port
to also include hidden adapters.
This will be useful when we switch to a container feature only model on
Windows.
> windows,go-controller: Include hidden adapters on management port

- Dockerfile.centos
- dist/images/Dockerfile.fedora
- dist/images/Makefile
- dist/images/ovnkube.sh
ovn-kubernetes/Dockerfile.centos
build the binaries in the Dockerfile
docker build -t ovn-kube .
to build the binaries and the image.
dist/images/Makefile builds the binaries and then the
docker build just includes them in the image.
Copy .git/HEAD and .git/refs/heads into image
Display ref and commit in log
> Added top level Dockerfile

- go-controller/pkg/cni/cniserver_linux.go
If for some reason another ovnkube is running and already
bound to the socket, this instance should quit. We need to
remove it and recreate it to (a) ensure this instance
owns it, and (b) that it has the right (root-only) permissions.
@rajatchopra @shettyg @pecameron
> cniserver: fail if cniserver socket cannot be removed

- go-controller/pkg/util/gateway-init.go
If for some reason, the gateway-init is called again
(for e.g because a previous invocation caused a bug),
we need to get the routerIP from database.
> gateway-init: Make code more re-entrant capable

- dist/images/ovnkube.sh
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
Ovn adds the HW nic to the ovn bridge. This works as long as
ovn is running.  When docker is restarted or the ovs daemonset
is deleted the traffic continues to go to the bridge which
results in the loss of all network access. The console can
be used to repair the configuration and restore networking.
This change is a workaround that avoids placing the nic in the
bridge.  A side effect is that iptables are used.
Also, a bind mount can't be deleted in a container.
Changed the go_controller to not try. Deleted files in the
daemonset yaml files.
/var/run needs to be mounted.
ovnkube.sh now displays the git branch and commit number
when available.
> WORKAROUND for network loss problem

- dist/images/ovn_k8s.conf
- dist/images/ovnkube.sh
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- docs/INSTALL.OPENSHIFT.md
- Don't mount /etc/origin (use the k8s-provided secret)
- Fail on missing variables
- Get the nodename from the k8s downward API
> dist/*: small daemonset cleanup

- go-controller/pkg/util/ovs.go
ovnkube can't start until the ovn-ndb is running.
This change goes into a loop waiting until the
daemon is running.
> Wait for "Connection refused" to go away

- go-controller/pkg/cni/cniserver_linux.go
If the parent directory is bind-mounted into the contianer which
ovnkube is running in, then we cannot remove the socket's parent
directory at all. In this case, just attempt to verify that it
already has the right permissions and owner.
Fixes: 3bfc9ce0d8cf4d0b73e15135ba540b653d3d0d44
@shettyg @rajatchopra @pecameron
> cniserver: better handle socket parent directory if bind-mounted

- dist/images/ovnkube.sh
- go-controller/pkg/cni/types.go
In a container /var/run/ovn-kubernetes is created with
permission 0755 (from kubelet). Because of the bind mount
permissions can't be changed. The fix is to create directory
/var/run/ovn-kubernetes with permission 0700 as needed.
> bind mount problem /var/run/ovn-kubernetes

- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/management-port_test.go
commit b054c98d (Remove Hyper-V as a hard dependency)
increased timeouts for utility calls. But the tests
remained using the old values. The tests can be run
with 'make check test'
> tests: Adjust the timeout in utility calls.

- dist/images/ovnkube.sh
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
ovn-kubernetes/dist cleanups
- make ovndb persistent
- include official image name
- note requred compatibility between daemonset and image
- wait for deamons to come up before starting additiona daemons
- ovnkube.sh - add display command to dump logs
-                     add display_env to dump environment variables
-                     add ovn_debug comamnd to gather ovn debug information
> Minor cleanups

- contrib/ovn-kubernetes-cluster.yml
The ansible playbook does not add minion hostnames inside
the /etc/hosts file on the master. As a result, the kubectl exec
command does not work since the master node cannot resolve the
minion hostname to connect to the pod.
This patch fixes this by adding the hostnames of the minion
in the master /etc/hosts file.
Example of kubectl commands working afterwards:
```
root@k8s-master:~# kubectl exec nano-1803 cmd /c dir
Defaulting container name to nano.
Use 'kubectl describe pod/nano-1803 -n default' to see all of the containers in this pod.
Volume in drive C has no label.
Volume Serial Number is 0C99-B7C6
Directory of C:\
04/11/2018  04:53 PM             1,894 License.txt
07/07/2018  03:36 PM    <DIR>          Users
08/21/2018  09:42 AM    <DIR>          var
08/21/2018  09:42 AM    <DIR> …
```
> ansible: Add minion hostnames in master hosts file

- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
With the addition of federated watch handlers, there are unnecessary go routines in the policy flow.
All we do with spinning a new go-routine for watching local peer pods for policy is 'add' the handlers and then wait for network policy to be removed so that we can 'remove' the handlers. We don't need go-routines for that.
This will be immensely helpful when we have 20k namespaces isolated from each other by at least as many NetworkPolicy objects.
This is a rebased version of https://github.com/openvswitch/ovn-kubernetes/pull/311
> remove unnecessary go-routines around policy watches

- docs/config.md
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
OVN DB has a connection table where we currently define the
port number to listen on for the OVN DB servers.  By default,
every 5 seconds or so, OVN DB server sends a inactivity probe
to test whether the client is still connected.  When there
are hundreds of clients, the server may spend a lot of time
maintaining these inactivity probes and as a result consume
a lot of CPU. It does not make sense for the server to do
this job. It should be the client that tries to maintain
the connection. And if the connection is down, the client
should restart it.
So this commit disables the inactivity_probe for the server
by setting it as zero.
For the clients (ovn-controller in our case), we provide the
option for the user to set it. Shorter time would mean that
a lot of inactivity probes could be sent …
> config: Modify inactivity-probe for DB server and client.

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
ExternalIPs are put as load balancer keys on the default gateway. The default gateway is the one which has the port 100.64.1.2 (we used to slap an external id earlier, but not anymore).
ovnkube on the default gateway must be invoked with --nodeport to let the load balancers be installed on the default gateway, or external IPs will be ignored.
To create a service with external IP, see [this](https://github.com/rajatchopra/openshift-examples/blob/master/hello-lb.json) example.
Tested it to the point where load balancer entries are made properly. 
TODO: Test with a configured environment where a packet is sent to the default gw node with the external IP as destination.
@shettyg PTAL. Thanks.
> support for external IPs

- README.daemonset.md
- dist/READMEopenshiftdevpreview.md
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- dist/yaml/sdn-ovs.yaml
There is a useable build of the ovn image in
docker.io/ovnkube/ovn-daemonset:latest
The image is updated as described in README.docker.md
The daemonset yaml files are updated to reference this image.
> Ovn-kube community container image

- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
The windows/linux integration will have daemonsets on
both linux and windows. Label the linux daemonsets to run
only on linux.
> Add os.kubernetes.io='linux' label to daemonsets

- dist/ansible/scripts/ovn-setup.sh
By default, the `host` cmd will search for the A, AAAA, and MX records in order.
This may result problem sometimes. 
Like below:
```
+++ hostname
++ host networking-master.cluster.local
+ host_ip='10.66.144.161
out;
out;'
+ OvnNorth='tcp://10.66.144.161
out;
out;:6641'
+ OvnSouth='tcp://10.66.144.161
out;
out;:6642'
--snip---
+ echo OvnNorth tcp://10.66.144.161 'out;' 'out;:6641'
OvnNorth tcp://10.66.144.161 out; out;:6641
+ echo OvnSouth tcp://10.66.144.161 'out;' 'out;:6642'
OvnSouth tcp://10.66.144.161 out; out;:6642
```
The full output of the `host` cmd is:
```
networking-master.cluster.local has address 10.66.144.161
;; connection timed out; no servers could be reached
;; connection timed out; no servers could be reached
```
So, add `-t A` parameter can fix the issue, and grab the …
> add parameter -t for host cmd to get the correct host_ip

- docs/ovnkube.1
- go-controller/cmd/ovn-kube-util/app/gateway_init.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/cmd/ovnkube/ovnkube_test.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_windows.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_test.go
- go-controller/pkg/util/gateway-init.go
First draft of adding multiple CIDR and configurable hostsubnetlengh in ovn-kubernetes networkwork plugin.
multiple cidrs are passed on the command line with  --cluster-subnet flag in the form
`--cluster-subnet [cidr]-[hostsubnetlength],...`
for example I used the below for testing
`-cluster-subnet "10.132.0.0/26-4,10.133.0.0/26-4"`
the hostsubnetlength refers to the number of ip addresses each node has for the allocation of pods in the above the nodes allocated in the above ranges would have /28 addresses to allocate pods in (I made it small for testing purposes) without this PR the hostsubnetlength was hard-coded to 8 so nodes had /24
> multiple CIDR and configurable hostsubnetlength support 

- dist/yaml/sdn-ovs.yaml
Restrict the number of pthreads ovs-vswitchd creates to reduce the
amount of RSS it uses on hosts with many cores.
This bug was originally reported on openshift-sdn. Since ovn-kube
uses the same daemonset to start ovs, repeat the fix here.
Fixes Bug: 1633892
https://bugzilla.redhat.com/show_bug.cgi?id=1633892
> Fix race in ovs startup

- README.md
- READMEquay.md
This describes using quay.io to automatically build images from your local github/<user>/ovn-kubernetes master branch. The images can be "docker pulled" into nodes in the cluster and be used as your development image.
> Add READMEquay.md

- dist/READMEopenshiftdevpreview.md
- dist/ansible/hosts
- dist/ansible/ovn-playbook.yaml
- dist/ansible/run-playbook
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- dist/yaml/sdn-ovs.yaml
Use ansible to install OVN on top of a 3.11 (no cluster network provisioned) install
On any suitable host, clone ovn-kubernetes
cd dist/yaml
edit ovnkube-master.yaml, ovnkube.yaml, sdn-ovs.yaml for the desired
image name.
cd ../ansible
edit hosts for hostname of master
./run-playbook
> ansible install of OVN on v3.11 cluster to bring up networking

- dist/images/ovnkube.sh
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- dist/yaml/sdn-ovs.yaml
Daemonset version 1 runs all daemons in a single container.
Further there is a daemonset for master and a separate daemonset
that runs on all nodes except master.
Version 2 daemonsets run each daemon in its own container.
The master daemonset runs only master daemons. The node daemonset
runs only node daemons. Both master and node daemonsets run on the
master and only node daemonsets run on the other nodes.
The ovnkube.sh script now supports both version 1 daemonsets
and version 2 daemonsets. The script has additional commands
that display the container logs, container environment variables
and ovn/ovs debug information.
SDN-110 - [ovn] split master and node-level daemonsets
https://jira.coreos.com/browse/SDN-110
> [4.0]Refactor ovnkube.sh and daemonset files

- dist/yaml/ovn-policy.yaml
I checked in kubernetes installed manually and also via kubeadm
and did not see a ClusterRole named "cluster-reader". I am not
sure what its intentions are here. May be it only comes from
openshift?
> ovn-policy: Get rid of ClusterRoleBinding "ovn-cluster-reader".

- dist/images/Dockerfile.ubuntu
We use 18.191.116.101 for installing OVS/OVN for vagrant
in setup-master.sh and setup-minion.sh.
This gives us more control over the exact OVS/OVN version
that we need installed. For e.g., currently upstream Ubuntu
provides OVS 2.9.0. We know that it is buggy and is a old release.
> Dockerfile.ubuntu: Use debian packages from 18.191.116.101.

- go-controller/pkg/cni/helper_windows.go
Currently, kubelet on Windows calls the CNI for every single container
within the same POD. This patch adds an early return in order
to skip calling powershell if the interface is already set up.
This applies only for the subsequent calls and not for the
first CNI call.
Signed-off-by: Alin Balutoiu <alinbalutoiu@gmail.com>
> cniserver: Improve CNI performance on Windows

- go-controller/pkg/util/remove-node.go
I see following two patch ports still present:
- patch port from Join switch to Gateway router
- patch port from Distributed router to Node's logical switch
Fixes Issue #480
> Not all OVN resources cleaned up on deletion of K8s nodes

- contrib/inventory/group_vars/all
- contrib/roles/linux/kubernetes/tasks/deploy_coredns.yml
- contrib/roles/linux/kubernetes/tasks/main.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- contrib/roles/linux/kubernetes/vars/ubuntu.yml
- contrib/roles/windows/kubernetes/tasks/run_minion_init.yml
Internal kubernetes dns is now enabled by the ansible playbooks by default.
Fixes #410
> Ansible dns

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
It's possible to deadlock if two events come in quick succession,
and one of the events triggers a watch handler removal. In one
specific case:
1) NetworkPolicy added -> addNetworkPolicyOld() -> handleLocalPodSelectorOld()
∘ adds pod event handler
2) Pod is deleted from API
∘ Pod informer Lock() grabbed
∘ handleLocalPodSelectorDelFuncOld()
∘ tries to grab np.Lock()
3) NetworkPolicy deleted -> deleteNetworkPolicyOld()
∘ grabs np.Lock()
∘ shutdownHandlers()
∘ RemovePodHandler()
‣ tries to grab Pod informer Lock()
Fix the deadlock by setting a tombstone on handlers so they
are not called after they are "removed", but do the removal
from a separate goroutine that can lock/unlock the informer
independently of any of the actual OVN logic.
@rajatchopra @shettyg @JacobTanenbaum @squeed …
> factory: defer handler removal to a goroutine

- go-controller/hack/test-go.sh
In the test-go.sh the last command is popd which will be the exit
code of the script. This means that even if running the actual tests
will fail, the exit code of the script will always be 0.
This change will also fix travis ci to fail when tests are failing.
Signed-off-by: Alin-Gheorghe Balutoiu <alinbalutoiu@gmail.com>
Example where this can be seen: https://travis-ci.org/openvswitch/ovn-kubernetes/builds/452974514
> Return proper exit code for make check

- dist/images/Dockerfile.ubuntu
Without gawk, we are seeing this error inside of the OVN daemonsets:
{"log":"/root/ovnkube.sh: line 261: gawk: command not found\n","stream":"stderr","time":"2018-11-14T06:34:05.453256293Z"}
> dockerfile: add the missing package gawk to ubuntu dockerfile

- contrib/README.md
- contrib/roles/windows/requirements/tasks/main.yml
- contrib/roles/windows/requirements/vars/windows.yml
This PR adds the Ansible logic `windows/requirements` to disable IPv6 on all the Windows agents.
This fixes https://github.com/openvswitch/ovn-kubernetes/issues/491.
> Disable IPv6 for Windows agents

- contrib/roles/windows/kubernetes/tasks/setup_ovs_docker.yml
Only set the `system-id` if it wasn't set.
> Ansible: Reduce the duplicates of chassis in SB database

- contrib/ovn-kubernetes-cluster.yml
- contrib/roles/windows/kubernetes/tasks/main.yml
- contrib/roles/windows/kubernetes/tasks/run_minion_init.yml
- contrib/roles/windows/kubernetes/tasks/setup_ovs_docker.yml
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_init_windows.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_localnet_windows.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/cluster/helper_linux.go
- go-controller/pkg/cluster/helper_windows.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/nicstobridge_windows.go
This patch separates the Linux specific code from the common
code inside gateway-init file. The code is moved in a helper
file.
Gateway init support is now enabled on Windows.
Signed-off-by: Alin-Gheorghe Balutoiu <alinbalutoiu@gmail.com>
Co-authored-by: Alin Gabriel Serdean <aserdean@ovn.org>
> windows: Add gateway support

- go-controller/pkg/cluster/master.go
currently when starting the ovn kubernetes master in the function
StartClusterMaster() when building a list of already allocated
subnets net.ParseIP() is incorrectly used on a CIDR which returns nil
and causes an empty list to be passed when building subnetAllocator structs
Correcting this behavior by calling net.ParseCIDR on allocated hostsubnets
and check if ranges contain that address to correctly build the list of already
allocated hostsubnets
Corrects Issue: https://github.com/openvswitch/ovn-kubernetes/issues/463
> Fix creation of the subnet allocated map on master startup

- Dockerfile.centos
- dist/images/Dockerfile
Allow container image to be built for multiple archetectures.
This upstreams some changes from the Openshift image
Also, permit build time selection of ovs/dpdk version (as of 2.9.2 dpdk is required.)
> Dockerfile.centos - multi arch changes

- dist/READMEopenshifttechpreview.md
- dist/ansible/ovn-playbook.yaml
- dist/ansible/scripts/ovn-debug
- dist/ansible/scripts/ovn-display
- dist/ansible/scripts/ovn-logs
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube.yaml.j2
Separate containers for northd and the nb and sb databases
Change display target to list pid and log for the container
General cleanups and restructuring:
- daemon output to stdout so oc logs can display it.
- Restart when a daemon fails.
- Add scripts to get logs and ovn debug info from all nodes.
- document changes: READMEopenshifttechpreview.md
SDN-119 The OVN daemonset should be reliable and easy to debug
SDN-110 Split daemonset in to multiple containers
SDN-114 Separate master and node components in to two daemonsets
SDN-221 Write daemonset templates for OVN
SDN-195 Split daemonset in to *even more* containers.
SDN-193 OVN: improve logging and error handling
https://jira.coreos.com/browse/SDN-193
> ovn version 3 ovnkube.sh and daemonsets

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_localnet_windows.go
Let the default gateway still create load balancer for nodeport/external-ip even
if the type is of localnet.
Rebase/fixup of https://github.com/openvswitch/ovn-kubernetes/pull/462
TODO:
@shettyg @rajatchopra
> gateway: enable NodePort for localnet gateway

- go-controller/Makefile
- go-controller/hack/build-go.sh
In order to use tools like delve successfully we need to disable some
compiler optimizations from the go binaries. This commit adds support
for the same.
Since, there are subtle differences in how this optimizations can be
achieved based on the version of the go compiler in use, I did not create
a `debug` target. For example:
Go 1.8.1:
-gcflags 'arg list' ==> use '-N -l'
Go 1.11.2:
-gcflags '[pattern=]arg list'  ==> use 'all="-N -l"'
Instead of a 'debug' Makefile target, the developer needs to invoke
make like below:
$ make GCFLAGS="-N -l"
(if you use, GCFLAGS=all="-N -l", then the dependent packages are also
compiled with these flags)
> add source debug build options

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/master.go
In the OVN topology that is build, the name of the K8s master node's
Logical Switch and the name of the distributed router for the entire
K8s cluster are same. For example: if the hostname of the K8s master
node is k8s-ubuntu-master, then we will have two OVN resources -- one
logical switch and one logical router -- that will be named as
k8s-ubuntu-master.
This causes some issues while displaying the logical flows for the OVN
resources as can be seen below (just an example of one of the issues).
$ sudo ovn-sbctl lflow-list k8s-ubuntu-master
ovn-sbctl: multiple rows in Datapath_Binding match "k8s-ubuntu-master"
To resolve the above problem, one would need to resort to UUID of the
OVN resource.
Fixes ovn-kubernetes issue #484
> Rename the distributed router to ovn_cluster_router

- dist/ansible/ovn-uninstall.yaml
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube.yaml.j2
The ovn northd and the nb and sb database containers now start properly.
Improved logging in northd, ovnsdb and ovnndb.
Cleanup /var/run/openvswitch files and /var/log/openvswitch files during
uninstall.
> OVN start containers properly, improve logs

- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/util.go
There is a known issue with OVS not correctly picking up the
physical network interface MAC address.
Gateway-init will fail on the Windows node when trying to add
the router port with a different MAC than the initial one. This
happens after node reboot.
As a workaround, fetch the MAC address via powershell if
it is not picked up from OVS.
Fixes #516 
Signed-off-by: Alin-Gheorghe Balutoiu <alinbalutoiu@gmail.com>
> windows: Fixes MAC fetching during gateway-init

- contrib/roles/windows/kubernetes/tasks/setup_ovs_hns.yml
The issue mentioned in the comments here was already fixed by pull request https://github.com/openvswitch/ovn-kubernetes/pull/541.
Signed-off-by: Ionut Balutoiu ibalutoiu@cloudbasesolutions.com
> Ansible: Remove OVS windows workaround

- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
Flag prevents kube-controller-manager to start with k8s master ( 1.14+ ) builds as it was removed.
> Ansible: Remove insecure-experimental-approve-all-kubelet-csrs-for-group flag

- contrib/inventory/host_vars/README.md
- contrib/roles/windows/kubernetes/tasks/set_ip_facts.yml
- contrib/roles/windows/kubernetes/vars/windows.yml
The `sdn_preferred_nic_name` config variable is now a global host
specific variable.
This will cover the case when multiple Windows minions will have the
preferred NICs with different names.
Signed-off-by: Ionut Balutoiu ibalutoiu@cloudbasesolutions.com
> Fix sdn_preferred_nic_name for multi-node deployments

- contrib/roles/linux/openvswitch/tasks/build_install_release_ovs.yml
- contrib/roles/linux/openvswitch/tasks/download_install_packages.yml
This is only a small cleanup PR. It removes the common `_` for every item in the `with_items` loop.
Signed-off-by: Ionut Balutoiu ibalutoiu@cloudbasesolutions.com
> Ansible: Small cleanup when at 'with_items' loops

- contrib/inventory/host_vars/README.md
- contrib/ovn-kubernetes-cluster.yml
- contrib/roles/linux/kubernetes/tasks/init_gateway.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- contrib/roles/windows/kubernetes/tasks/run_minion_init.yml
Remove the `init_gateway` flag from the main playbook file and
have it to be used as a host specific configuration option.
This will easily allow users to disable gateway for some
k8s minions, if desirable.
The default value is considered `true` to maintain backwards
compatibility.
> Ansible: Update `init_gateway` boolean flag

- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
Previously, Linux minions didn't have a systemd service
for the ovnkube service when `init_gateway` is disabled.
This is required, otherwise the Ansible task executing
`ovnkube` hangs forever.
> Ansible: Fix Linux minions without gateway flags

- contrib/ovn-kubernetes-cluster.yml
- contrib/roles/linux/validation/tasks/main.yml
This pull request adds a workaround for the stucked `pending` state of the CoreDNS pods when a deployment is initially created.
On top of this, validation tasks for checking `running` CoreDNS pods is added.
> Ansible: Fix the CoreDNS pods and add validation tasks

- contrib/roles/linux/kubernetes/tasks/generate_certs_master.yml
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- contrib/roles/linux/kubernetes/vars/ubuntu.yml
Add variable with the root directory for the Kubernetes certificates, and use
this in the Ansible tasks.
Improve the check for the Kubernetes master certificates existence.
> Ansible: Cleanup the K8s Linux certs setup

- contrib/roles/linux/validation/tasks/main.yml
- contrib/roles/windows/kubernetes/tasks/create_infracontainer.yml
The retry logic when executing shell commands on both Linux and Windows
lacked the comparison for exit code.
> Ansible: Fix retry logic

- contrib/roles/linux/common/tasks/kubectl_client.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
Add common role for setting up the kubectl client tool.
**NOTE**: This pull request must be merged after https://github.com/openvswitch/ovn-kubernetes/pull/568 gets in.
> Ansible: Add common role for kubectl tool

- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_old.go
This PR adds the ability to use both podSelector and NamespaceSelector in a network policy as conforms to kubernetes documentation.
> namespaceSelector and podSelector: A single to/from entry that specifies both namespaceSelector and podSelector selects particular Pods within particular namespaces.
Makes the change in both egress and ingress
> add namespace selector and pod selector functionality to network policy 

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/ovs.go
Instead of generating addresses in the 100.64.1.x range (eg, things connected to the 'join' switch, eg gateway routers) manually with locking, just let OVN dynamically allocate them.
@shettyg @rajatchopra @danwinship
> Allocate gateway router port addresses dynamically

- contrib/roles/linux/validation/tasks/main.yml
* Instead of using Python and a script created on the fly, we use native support for JSONPath from the kubectl CLI tool
* Add task to validate K8s API health for Linux and Windows minions
> Ansible: Add more validation for K8s Minions

- go-controller/cmd/ovnkube/ovnkube.go
Currently, we create pidfile and immediately delete it for the
transient command like `ovnkube remove-node`. This shoudln't
be done. Also, I have refactored the pidfile handling code to
it's own function. This is in preparation for adding subcommands
to ovnkube.
> pidfile handling should be done only for the ovnkube daemons

- dist/images/ovnkube.sh
OVN_LOG_NORTHD can be set to space-separated values, so we need
to enclose it within quotes otherwise the value be interpretted
to be ovn-northd's CLI argument.
> log: enclose ovn-northd log options in quotes

- contrib/roles/linux/common/vars/ubuntu.yml
Bumping the golang version to decrease recompile/relink times.
> [Ansible][contrib] Bump golang version

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovn-setup.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
Added livenessProbe for vswitchd (restarts after OOM gets it)
Made KUBECONFIG and environment variable that can be set in the
daemonset.
Changed gawk to awk.
> Fix minor details

- dist/images/Dockerfile.ubuntu
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
No need for KUBECONFIG file within the POD to access cluster
out-of-band (without using service IP). Use the 'ovn' serviceaccount
token and ca.crt instead. Require user to specify K8S_APISERVER
parameter through ovn-k8s ConfigMap like we had before.
Remove all the /etc/origin/node mountpath since we don't need the
kubeconfig file anymore.
Add `bind9-host` debian package which provides `host' command that was
being used in ovnkube.sh
> daemonset: miscellaneous fixes to get daemonset to work

- dist/images/ovnkube.sh
Provide a way to specify log options to ovn-controller daemon just
like how we do for northd, ovsdb servers, and others.
Provide a way to specify different mode of L3 gateway options. By
default we will use the local host networking like today.
Fix ovn-northd log option issue.
Acked-by: Girish Moodalbail <gmoodalbail@nvidia.com>
> ovnkube: ovn-controller log and ovnkube gateway options support

- go-controller/pkg/util/ovs.go
When OVN commands fail, it is useful to log the actual command that failed.
> When OVN cmd fails - add the actual command to the errorw

- dist/ansible/ovn-playbook.yaml
- dist/templates/ovn-setup.yaml.j2
As of PR 605 - k8s_apiserver is required in the ovn-config configmap
PR 605 didn't set the k8s_apiserver in the config map. This change
fixes that and allows ovn to again work on openshift.
> Add k8s_apiserver to ovn-config configmap

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/nicstobridge.go
The external OVN logical switch that connects the OVN l3gateway router
(and all of the logical ports behind that gateway router) to physical
network should make use of 'localnet' logical port type.
The localnet ports are defined as below in ovn-architecture(7) document
Localnet  ports represent the points of connectivity between
logical switches and the physical network. They  are  implemented as
OVS patch ports between the integration bridge  and  the  separate
Open vSwitch  bridge that underlay physical ports attach to.
and it fits our requirement very well.
They are also essential to support the physical network that is tagged
or VLAN based. From the ovn-nb(5) we have
When port is localnet, tag_request can be set to indicate that the
port represents a  connection  to  a  specific VLAN …
> gateway: use localnet ports on external logical switch

- dist/ansible/ovn-playbook.yaml
- dist/images/ovnkube.sh
This simplifies the install by moving the iptables rules
that open the ovn database ports (6641 and 6642) from the install
to ovnkube.sh
SDN-313 Put iptable rules for ovn db access into image
https://jira.coreos.com/browse/SDN-313
> Move iptable port 664[12] open to ovnkube.sh

- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
ovn-k8s-cni-overlay doesn't need any arguments, so do not set the
Flags for this
> cmd: ovn-k8s-cni-overlay doesn't need any arguments

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/util/gateway-init.go
All the external logical switches that connect L3 gateway to external
network assumes that the underlay is untagged. This may not be the case.
The underlay network could be tagged and therefore we need a way to
specify a VLAN ID.
This commit adds a new argument to ovnkube called --gateway-vlanid. The
default value will be 0, and therefore untagged. If the external network
is tagged, then the packets leaving the POD must be tagged as well and
one should populate this option with the right VLAN tag.
This option is valid only for Shared Gateway Interface and Spare
Gateway Interface.
Fixes #583
> gateway: add access to tagged external network

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/util.go
Currently, we are seeing following errors
2019-03-06T12:30:50.983Z|01361|ovn_northd|WARN|Dropped 23 log messages in last 21950 seconds (most recently, 21950 seconds ago) due to excessive rate
2019-03-06T12:30:50.983Z|01362|ovn_northd|WARN|bad ip address or port for load balancer key None:6642
since we are not handling headless service in Add/Delete Endponts.
Signed-off-by: Yun Zhou yunz@nvidia.com
> ovn/service: handle headless service in Add/Delete Endpoints

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/testing/testing.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/remove-node.go
Node logical switches and their associated connections to the cluster router
are now created in the master on Kube API node add events, and cleaned up
from the master on node delete events.
Fixes: https://github.com/openvswitch/ovn-kubernetes/issues/531
@squeed @danwinship @openvswitch/ovn-kubernetes-team
> cluster/ovn: move node logical switch creation to master

- contrib/roles/linux/kubernetes/tasks/init_gateway.yml
The OVN Gateway Helper service requires the physical
interface name as an argument. On subsequent playbook
runs, it will pass the bridge name instead of the
physical interface name. It should use the variable
physical_interface_name instead of interface_name when
creating the service.
Found by inspection.
Signed-off-by: Alin Balutoiu <alinbalutoiu@gmail.com>
> [Ansible][contrib] Fix ansible gateway interface for subsequent runs

- contrib/ovn-kubernetes-cluster.yml
Ansible will try to manage all of the machines
referenced in a play in parallel by default.
The module lineinfile has conccurency issues
when multiple hosts are delegating to the
same host and the same file. This issue
is tracked upstream in ansible:
https://github.com/ansible/ansible/issues/30413
As a temporary workaround, the hosts file will
be updated by all the nodes one by one instead
of doing it in parallel.
Fixes issue #637
Signed-off-by: Alin Balutoiu <alinbalutoiu@gmail.com>
> [Ansible][contrib] Add workaround for lineinfile concurrency issues

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_test.go
- go-controller/pkg/util/util.go
We have a significant drawback while deploying K8s cluster using OVN-K8s
CNI in Shared gateway interface mode. In this mode,
1. one cannot deploy a POD on the K8s Master node. The PODs requiring
K8s API Server access ends up in CrashLoopBackOff as it cannot reach
K8s API Server through the kubernetes Service IP (10.96.0.1:443).
This happens because 10.96.0.1 is translated to the K8s Master host
IP and this IP cannot be accessed from the OVN logical topology since
this same IP address is used by OVN L3 gateway.
2. an another issue is that a POD on a host cannot access any service
on that host itself. For example: a metrics-server POD on a host H1
that wants to access the stats from kubelet running on that host at
port 10250, will fail
This is because the packets from the POD meant for the …
> PODs on K8s nodes access to host IP when using Shared Gateway Interface

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/util/gateway-init.go
The packets to a POD on a K8s node that is an endpoint for a NodePort
service is forced-SNAT'ed to L3 Gateway's IP address. The intent is to
make the reply packets from the POD to exit out through the same L3
gateway. However, the reply packets from the POD matches a
longest-prefix src-ip based static route on OVN cluster router and gets
forwarded to a different L3 gateway.
The fix is to add /32 specific route for each of the GR router's IP.
Fixes #647
> cluster: src-ip based routes take precedence and breaks NodePort

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/util/gateway-init.go
without setting 'protocol=tcp' for north-south load-balancer, the output
of `onv-ncbtl lb-list` displays 'null' instead of 'tcp'.
> call out the protocol to be TCP for north-south load-balancer

- go-controller/pkg/factory/factory.go
Fixes: https://github.com/openvswitch/ovn-kubernetes/issues/454
@girishmg @shettyg @squeed @pecameron
> factory: move u64 to head of struct for 32-bit atomic requirements

- contrib/roles/linux/common/tasks/k8s_client_certs.yml
- contrib/roles/linux/kubernetes/tasks/generate_certs_master.yml
The `mkdir` and `rm -rf` calls are not necessary from the `k8s_client_certs.yml` `make-certs` bash script:
* The K8s certs directory is previously created via an Ansible task, so the `mkdir -p "$cert_dir"` is useless.
* The `rm -rf` has `"$cert_dir/*"` (enclosed in double quotes), and the file with the exact name `*` is tried to be removed from the `$cert_dir` directory. But it doesn't exist, so this call does nothing:
```
root@k8s-04:/home/ionut# cert_dir="/etc/kubernetes/tls"
root@k8s-04:/home/ionut# ls -l $cert_dir
total 8
-rw-r--r-- 1 root root 1675 Mar 26 16:26 ca-key.pem
-rw-r--r-- 1 root root 1090 Mar 26 16:26 ca.pem
root@k8s-04:/home/ionut# rm -rf "$cert_dir/*"
root@k8s-04:/home/ionut# ls -l $cert_dir
total 8
-rw-r--r-- 1 root root 1675 Mar 26 16:26 ca-key.pem
-rw-r--r-- 1 root …
```
> [Ansible] Small bash script cleanup

- contrib/ovn-kubernetes-cluster.yml
- contrib/roles/linux/kubernetes/tasks/fetch_k8s_binaries.yml
- contrib/roles/linux/kubernetes/tasks/generate_global_vars.yml
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/linux/ovn-kubernetes/tasks/fetch_bins.yml
* The fetch module has a bug which causes it to use memory proportional to the file being transferred. The `synchronize` uses rsync which only has low memory requirements. Fixes #494.
Signed-off-by: Sebastian Geiger <sbastig@gmx.net>
* Move local cache `ansible_tmp_dir` create at the beginning of the main playbook file.
> [Ansible] Replace fetch with synchronize

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovn-setup.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
The idea here is to have 3 sets of PODs:
1. ovnkube-db POD -- runs both OVN NB DB and OVN SB DB. Other PODs will wait
until this POD comes up since it has DBs.  This will be facilitated using
headless service without label selectors -- named ovnkube-db. The endpoint for
this service will be populated by ovnkube.sh once both the DBs are up.
2. ovnkube-master POD -- runs ovn-northd and ovnkube in master mode. This POD
depends on ovnkube-db and becomes aware of the availability of the DB POD by
checking the ovnkube-db Endpoint object (just like how we do it today).
3. ovnkube-node POD – no changes and will have containers like today.
Fixes #648
> framework for providing high availability for OVN DBs

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
This gets us the latest kernel module and makes it easy
to test the latest OVS.
> vagrant: Use dkms kernel module for daemonsets too.

- dist/images/ovnkube.sh
ovnkube-master container sets few fields in OVS DB and this fails if
ovs-servers is not ready by that time. This patch fixes that issue.
Otherwise, we will see panics like this below in ovnkube-master.log.
{"log":"panic: Error setting OVS external ID
'ovn-nb=\"tcp:10.10.0.11:6641\"': exit status 1\n","stream":"stderr",
"time":"2019-04-05T17:14:08.569185599Z"}
> daemonset: wait for ovs to be ready before starting ovnkube-master

- README.md
- dist/images/ovnkube.sh
- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/config/config.go
- vagrant/provisioning/setup-master.sh
`localnet` is a very well known concept in OVN, so br-localnet gives
a wrong idea to someone who is starting new with ovn-kubernetes. So,
br-localnet should be renamed to br-local (it is similar to what
br-local does in OpenStack).
> gateway: br-localnet really should be br-local

- go-controller/pkg/ovn/loadbalancer.go
The current code makes a bad assumption that
GetMap can return a nil value. It instead only
returns a zero length map if no record found.
> loadbalancer: Fix error handling.

- go-controller/pkg/ovn/ovn.go
The address provided is of the form:
"tcp://10.10.0.11:6641,tcp://10.10.0.12:6641,tcp://10.10.0.13:6641".
We are currently not splitting it.
> ovn: Handle multiple addresses correctly.

- dist/images/ovnkube.sh
There is an issue in pid_ready() and pid_health() where in the PID from
the respective daemon's pidfile is not compared for the exact match in
the `ps` output.
This results in pid_health() abnormally terminating a daemon and
causing a container restart or pid_read() will never see the daemon to
be up and waits till it timesout and restarts the process
> daemonset: fix logic error in pid_ready and pid_health

- vagrant/provisioning/setup-master.sh
> vagrant: cleanup hostname mapping to 127.0.0.1

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/util/iptables.go
Per append() documentation if the slice has sufficient capacity, then it
would reslice the 1st argument to accommodate the new elements. This
was causing a logic error in how the iptable rules were getting inserted
at position 1 in a chain.
Also, the rule ordering was incorrect if the chain already had one
rule in it.
> iptables: issues with usage of append() and iptable rules ordering

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_localnet_windows.go
- go-controller/pkg/util/iptables.go
The support for NodePort service is currently broken for local gateway
type. The IPtable rules added by kube-proxy makes the packet enter OVN
through the management port and the return path for these packets will
be lost. Instead, we want the NodePort packets to enter OVN through L3
gateway.
With this fix, we will not need kube-proxy at all for any of the 3
modes of gateway we support.
Fixes #667
Signed-off-by: Yun Zhou yunz@nvidia.com
> add iptable rules to support NodePort service for local gateway type

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/util/ovs.go
Rename OvnAddressForClient -> Address since we only deal with
the NB/SB client now.
Also consolidate OvnDBAuth, OvnAuthConfig, and rawOvnAuthConfig;
there's no reason to have all three of them anymore.
@shettyg @girishmg @squeed @pecameron
> config: clean up now that config only handles the client side

- dist/images/ovnkube.sh
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
Rather than hardcoding the namespace for the `ovnkube-db` service in `ovnkube.sh`, have it put the service in the same namespace as the pods themselves.
(In OpenShift, we want all "system" namespaces to start with "`openshift-`", so when running OVN Kubernetes, we put it in the namespace "`openshift-ovn-kubernetes`".)
cc @dcbw @pecameron
> Allow running in namespaces other than 'ovn-kubernetes'

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/master_test.go
There is a race between the LogicalPort creation for the management
port and the LogicalPort creation for the first pod on that node.
To fix this, for every ovn-node's subnet we need to keep aside the
second address for the management port (that is set Logical_Switch's
exclude_ips to the management port's IP). That way OVN will allocate the
subsequent addresses dynamically for the PODs on that node.
> race between LogicalPort creation of management port and first pod

- README.md
- contrib/roles/linux/kubernetes/tasks/init_gateway.yml
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- contrib/roles/windows/kubernetes/tasks/run_minion_init.yml
- dist/images/ovnkube.sh
- docs/INSTALL.SSL.md
- docs/ha.md
- docs/ovnkube.1
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_test.go
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
The two values do the same thing, and --service-cluster-ip-range wins if present
to maintain backwards compatibility. But there's now config file support for
service-cidr and it now has a default too.
@shettyg @girishmg @pecameron @JacobTanenbaum @danwinship @squeed
> config: add --k8s-service-cidr config option and deprecate --service-cluster-ip-range

- contrib/README.md
- contrib/ovn-kubernetes-cluster.yml
- contrib/roles/linux/docker/vars/ubuntu.yml
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- contrib/roles/linux/openvswitch/tasks/build_install_release_ovs.yml
- contrib/roles/linux/openvswitch/tasks/download_install_packages.yml
- contrib/roles/linux/openvswitch/vars/ubuntu.yml
- contrib/roles/linux/ovn-kubernetes/vars/ubuntu.yml
- contrib/roles/linux/version_check/tasks/main.yml
This PR updates the OVS/OVN versions to 2.10, adds support for Ubuntu 18.04, deprecates support for Ubuntu 14.04.
Unfortunately Ubuntu 18.04 comes with `netplan` builtin. This causes issues when deploying it as a gateway, because the DNS settings are not copied from the physical interface to the OVS bridge. Until support is added, 18.04 minions will be forced with a gateway configuration.
This PR contains the following commits:
-   [ansible] Switch to ovn-org links
-   [contrib] Bump OVS linux version to 2.10
-   [contrib] Add 18.04 to the supported list and deprecate 14.04
-   [contrib] Bump OVS installer to 2.10 on Windows
-   [contrib] Linux add new dependency needed to compile OVS
-   [contrib] Change order when installing debs
-   [contrib] Set init_gateway to false by default on …
> [Contrib] Add Ubuntu 18.04 support

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
When nodeport enabled for the cluster node, there are two load balancers
created for north-south traffic, one handles UDP and another handles
TCP, add the missing clean up code. So there should be corresponding code
in gateway clean up logic.
> load balancer entries are not getting cleaned up on node deletion, this commit fixes it.

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ovn.go
For NodePort enabled endpoints, each node will have VIPs added to the
gateway router load balancers. But if new node add after endpoints
added, there is missed logic to add the VIPs to the new node's
load balancers. This commit fixes this problem.
Fixes #316
> Update LB VIPs for nodeport service on adding new node

- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
`--k8s-service-cidr` is ovnkube specific.
Switch to `service-cluster-ip-range` as per:
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
> [contrib] Fix kube-apiserver service ip argument

- dist/images/ovnkube.sh
- go-controller/README.md
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
Modify ovnkube to use environment variables and service account files to
provide Kubernetes configuration in addition to the command line
options.
The value is set from the command line option, if present, or the
environment variable, if present, or the service account file, where
available.
--k8s-apiserver  K8S_APISERVER
--k8s-kubeconfig K8S_KUBECONFIG
--k8s-cacert K8S_CACERT /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
--k8s-token K8S_TOKEN /var/run/secrets/kubernetes.io/serviceaccount/token
The ovnkube.sh script is changed to no longer pass ovnkube --k8s-apiserver
--k8s-cacert --k8s-token since they are availabe as described above.
Jira: SDN-304
https://jira.coreos.com/browse/SDN-304
> OVN: Stop putting the token on the cmdline

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/gateway-init_test.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/util_suite_test.go
This reverts commit ebe7c729afc4581f8b9e31a288056758f9e8caeb.
Now that OVS 2.11 and 2.10.2 are out we can rely on the IPAM fixes that prevented
PR #503 from being used. Those fixes in upstream OVS are:
branch-2.11/master:
6f5cc61c07f20452955d5278f0771fbd8af1840c
dcad447342ea30d2806d9df063c7cef6a1b0cb1d
branch-2.10:
f01ed924c5f7224d8083a25a7e6b3c3621ba03aa
66b6fff3edae2dc71628997b749a962c80fbec30
@shettyg @girishmg
> [v2] Allocate gateway router port addresses dynamically

- go-controller/pkg/cluster/node.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/factory/factory.go
Rather than distributing the database urls via ConfigMaps, they should be obtained via a Service/Endpoint. As endpoints change, the ovn-kube process can update ovn and openvswitch accordingly
[SDN-295](https://jira.coreos.com/browse/SDN-295)
> node processes should get their connections via a Service

- go-controller/pkg/ovn/policy_common.go
the following usage which is allowed by the K8s API Spec
ingress:
- from:
- ipBlock:
cidr: 192.168.10.0/24
except:
- 192.168.10.4/24
- 192.168.10.7/24
- ipBlock:
cidr: 192.168.1.0/24
except:
- 192.168.1.4/24
- 192.168.1.7/24
should be allowed
> add support for multiple ipBlock fields in a single ingress/egress rule

- dist/images/Dockerfile
Add arm64 support for docker build based on Centos:
1. Add aarch64 support for kubernetes.repo
2. Add/fix the aarch64 suport for dpdk rpm install
3. Add multi-arch support for containernetworking-cni package
The docker build command for aarch64 could be:
docker build --build-arg rpmArch=aarch64 -t some_tag .
The commit would NOT affect the original building work on x86, and had been tested both on x86_64 and aarch64.
Signed-off-by: trevor tao <trevor.tao@arm.com>
> Add arm64 support for daemonset image build

- dist/images/Dockerfile
- dist/images/kubernetes.repo
Let's just use what yum already does with $basearch rather than doing
magic in the Dockerfile.
Fixes: https://github.com/ovn-org/ovn-kubernetes/pull/721
> dist: simplify kubernetes.repo and Dockerfile interaction

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/testing/testing.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/ovs.go
Move all vswitch, MAC retrieval, and IP operations out of the common gateway code in pkg/util. This will allow us to run the local operations only on the nodes but all the logical network operations on the master in the near future.
@girishmg @shettyg @squeed @danwinship @pecameron @rcarrillocruz
> gateway: split local vswitch and OVN operations

- go-controller/pkg/cluster/gateway_init.go
it is possible that the IP interface can have more than one IP address
and we end up picking up the wrong address.
> gateway: pick the first IP address from the interface

- README.md
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- vagrant/provisioning/setup-master.sh
For most current Kubernetes master node, the label value of
"node-role.kubernetes.io/master" is just ""(empty), not "true".
So when using the nodeSelector to choose the master of K8s cluster,
we should use just an empty value "" instead of a "true" value, which
means if there is a label "node-role.kubernetes.io/master" set in the node,
it's the desired master node.
If the value of "true" is used, there may be NO approriate node
that can be found to run the pod when deploying the pod.
Signed-off-by: trevor tao <trevor.tao@arm.com>
> Change the value for selecting the master node

- dist/templates/ovnkube-master.yaml.j2
Now that we don't make the assumption that the OVN DBs and its clients
OVN northd and ovnkube-master are on the same k8s node, remove the
limitation in the ovnkube-master POD yaml that restricts both ovnkube-db
and ovnkube-master to be on the same node.
> yaml: ovnkube-db and ovnkbue-master need not be on the same k8s node

- README.md
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
- vagrant/provisioning/setup-master.sh
daemonset.sh now supports --gateway-options CLI switch using which one
can specify one of the 3 gateway modes that we support. When specified,
the ovnkube-node POD spec will expose an environment variable capturing
the gateway options. The onvkube.sh reads this environment variable and
does the right thing.
> provide a way to specify gateway options for ovnkube-node daemonset

- dist/images/Dockerfile
It seems the containernetwork-cni rpm package had been
removed from the official fedoraproject repo which leads to
an error when building the image.
Now we just remove that package installation since
containernetworking-cni is not needed to build the image.
Do it to the comments of PR727:
https://github.com/ovn-org/ovn-kubernetes/pull/727
Signed-off-by: trevor tao <trevor.tao@arm.com>
> Remove the installation of containernetwork-cni

- README.md
- dist/images/Dockerfile.ubuntu
- docs/INSTALL.UBUNTU.md
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
We maintain a Debian source repository for ease of use to
keep openvswitch/OVN packages. Amazon had a outage yesterday
and a restart of the VM gave it a new IP address.
> Change debian source repository's IP address.

- docs/ovn_k8s.conf.5
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/etc/ovn_k8s.conf
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_localnet_windows.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
Allows their use in the config file, rather than just on the command-line. Girish and I had discussed moving more option processing out of the ovnkube.sh script and into a configmap that would be used as a config file, so that ovnkube.sh is less complicated and config options are easier to change without having to update ovnkube.sh itself.
@girishmg @shettyg @pecameron @danwinship @ovn-org/ovn-kubernetes-committers @JacobTanenbaum @squeed
> config: add gateway options as full config options

- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
on each of the k8s node, based on the gateway mode, we create several
OVS resources namely
-- bridges, like br-int, br-local
-- ports, k8s-`hostname`, br-nexthop, patch ports
These resources are not cleaned up on the deletion of the onvkube-node
pod. This change adds a preStop hook to ovn-node and ovs-daemons
containers in the ovnkube-node POD to perform cleanup.
> cleanup OVS resources on k8s node upon ovnkube-node pod deletion

- README_MANUAL.md
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- dist/files/ovn-kubernetes-master.sh
- dist/images/ovn-debug.sh
- dist/images/ovnkube.sh
- docs/INSTALL.SSL.md
- docs/ha.md
- docs/ovnkube.1
- go-controller/README.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- vagrant/provisioning/setup-master.sh
In this iteration I have just removed the `-net-controller` option. 
In the next iteration, which I am testing, I am going to 
- move some master aspects of cluster.go`OvnClusterController into the ovn.go`Controller and create a single controller called MasterController
- keep the node aspects of cluster.go`OvnClusterController and rename it to NodeController.
So, there will be two controllers -- MasterController (runs in ovnkube-master process) and NodeController (runs in ovnkube-node process).
> remove the -net-controller option

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/healthcheck.go
- go-controller/pkg/kube/healthcheck/healthcheck.go
- go-controller/pkg/kube/healthcheck/healthcheck_test.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/kube.go
- go-controller/pkg/util/util.go
A few fixes to get NodePort and LoadBalancer services fully working.
The first patch fixes an edge case: connecting from a node to a NodePort service on the same node, when using `GatewayModeLocal`. (The bug is pretty specific to the localnet implementation; I don't think any corresponding fix is needed to the other modes.)
The second patch fixes LoadBalancer services that don't have health checks, by treating them the same as NodePort.
The third patch fixes LoadBalancer services *with* health checks, by copying in the kube-proxy service health check code and running health check servers for the services that need them. This code probably should be moved somewhere outside of kubernetes itself so we can vendor it, but for now I just copied it over. The changes from upstream are minimal …
> Fixes for NodePort and LoadBalancer services

- go-controller/hack/test-go.sh
Gets rid of the lines like:
?   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/kube   [no test files]
in the "make check" output.
(The "`grep -v vendor`" in the original version may have been necessary with older versions of `go`, but `go list` knows to skip vendor itself these days.)
> hack: don't try to run "go test" in dirs with no tests

- go-controller/Makefile
- go-controller/pkg/cluster/gateway_localnet_windows.go
It seems that chaining the Windows build commands together (to
take advantage of the export WINDOWS_BUILD) wouldn't properly
exit with failure when one of the commands failed. Fix that.
@girishmg @alinbalutoiu
> windows: fix build after gateway cleanup changes

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/util/gateway-init.go
Turns out we can just rely on the host's iptables/nftables for NAT-ing
outgoing gateway traffic, stop NAT-ing in the OVN node gateway, and
things appear to work fine.
@danwinship @girishmg @shettyg
> gateway/local: stop double-NAT-ing

- dist/images/Dockerfile.fedora
Switch to 'ovn' packages rather than openvswitch (due to the recent
OVS/OVN packaging split).
Clean up outdated comments and unnecessary packages.
Synchronize a bit more with downstream OpenShift ovn-kubernetes
Dockerfile.
@danwinship @pecameron
> images/Dockerfile.fedora: switch to 'ovn' packages and cleanups

- dist/images/ovnkube.sh
For those processes (ovsdb-server, ovs-vswitchd, ovn-northd,
ovsdb-server-nb, ovsdb-server-sb, and ovn-controller) that support
ovs-appctl to control it, use the same utility to check for process
health and readiness.
> use ovs-appctl to check for process readiness and health

- README_MANUAL.md
- contrib/roles/linux/kubernetes/tasks/init_gateway.yml
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
- contrib/roles/windows/kubernetes/tasks/run_minion_init.yml
- dist/files/ovn-kubernetes-master.sh
- dist/files/ovn-kubernetes-node.sh
- dist/images/ovn-debug.sh
- dist/images/ovnkube.sh
- docs/INSTALL.SSL.md
- docs/ha.md
- docs/ovnkube.1
- go-controller/README.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/config/utils_test.go
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
To keep moving towards our future use of the config file (and thus ConfigMaps) instead of CLI options, move the cluster-subnet option into config and rename slightly now that we support multiple cluster CIDRs. Provide backwards compatibility for the old '-cluster-subnets' CLI option.
@danwinship @pecameron @girishmg @shettyg @squeed
> config: add '-cluster-subnets' CLI and 'cluster-subnets' config file options

- docs/ovs_offload.md
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_windows.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/config/cni.go
- go-controller/vendor/github.com/Mellanox/sriovnet/LICENSE
- go-controller/vendor/github.com/Mellanox/sriovnet/README.md
- go-controller/vendor/github.com/Mellanox/sriovnet/file_access.go
- go-controller/vendor/github.com/Mellanox/sriovnet/mofed_ib_helper.go
- go-controller/vendor/github.com/Mellanox/sriovnet/sriovnet.go
- go-controller/vendor/github.com/Mellanox/sriovnet/sriovnet_helper.go
- go-controller/vendor/github.com/Mellanox/sriovnet/sriovnet_switchdev.go
- go-controller/vendor/github.com/satori/go.uuid/LICENSE
- go-controller/vendor/github.com/satori/go.uuid/README.md
- go-controller/vendor/github.com/satori/go.uuid/codec.go
- go-controller/vendor/github.com/satori/go.uuid/generator.go
- go-controller/vendor/github.com/satori/go.uuid/sql.go
- go-controller/vendor/github.com/satori/go.uuid/uuid.go
- go-controller/vendor/vendor.json
The current OVS supported is OVS running in Linux Kernel. Mellanox Accelerated Switching And Packet Processing (ASAP2 ) technology allows OVS offloading by handling OVS data-plane in Mellanox ConnectX-4 Lx onwards NIC hardware (Mellanox Embedded Switch or eSwitch) while maintaining OVS control-plane unmodified. OVS hardware offload is using SR-IOV technology with VF representor host net-device. The VF representor plays the same role as TAP devices in Para-Virtual (PV) setup. A packet sent through the VF representor on the host arrives to the VF, and a packet sent through the VF is received by its representor.
This proposal provide a mechanism to enable OVS hardware offload with OVN Kubernetes. 
More information can be found on Design Proposal for OVS Offload Support for OVN CNI [1]
[1] - …
> ovnkube support for ovs offload

- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
Currently, those two pods have hostPID set to true. So, this means that
they can see all the processes in host process namespace. This is not
good from the security perspective.
Commit 59c345931f9d (use ovs-appctl to check for process readiness and
health) added support to check process readiness and health using
a control socket instead of a PID.
ovnkube-node pod cannot be yet moved to hostPID:false since we open
network namespace (PID in host process namespace) from within the pod
while adding an interface to the pod. so, this pod will be tackled in
a separate commit.
> ovnkube-master and ovnkube-db pods shouldn't have hostPID set to true

- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_test.go
ovn-northd complains with a warning message "Duplicate IP set" when the
IP address set in logical switch's other_config:exclude_ips key is
statically allocated to a logical switch port. To eliminate that
warnings we'd need to remove the exclude_ips configuration in the same
transaction as the creation of the management port.
> remove other-config:exclude_ips key once that IP address is allocated

- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- go-controller/pkg/config/config.go
- go-controller/pkg/util/ovs.go
Every invocation of ovn-nbctl command connects to northbound database
running on a remote server, retrieves a partial copy of the database
that is complete enough to do its work, sends a transaction request to
the server, and receives and processes the server’s reply. In common
interactive use, this is fine, but if the database is large, then the
command takes a long time to complete and yields poor performance.
The solution to this problem is to use golang OVSDB bindings. However,
In the absence of the bindings the next best solution is to use
ovn-ncbtl in the daemon mode.
In a "daemon mode", the user first starts ovn-nbctl running in the
background and afterward uses the daemon to execute operations. The
client needs to use the control socket and set the path to the control
socket in …
> ovn-nbctl daemon mode until we get golang OVSDB bindings

- dist/images/ovnkube.sh
Running "local" gateway mode is not a HACK. It is one of the ways to
achieve North-South traffic (aka traffic external to logical network).
If operators want to run "shared" gateway mode, then it is well
understood that they shouldn't be running ovs-server container in the
ovnkube-node POD. The expectation is that the OVS bridge with
right physical NIC as one of the bridge's port is already created in
the K8s node and that ovs-vswitchd and ovsdb-server processes are
running in the node.
> remove TEMP HACK - WORKAROUND verbiage from ovnkube.sh

- dist/images/Dockerfile.fedora
Without iptable,  ovnkbue.sh cannot start with the following error message.
=============== ovn-node   --init-node
info: Waiting for process_ready ovnkube to come up, waiting 1s ...
panic: failed to initialize iptables: exec: "iptables": executable file not found in $PATH
> add missing iptables package to fedora dockerfile

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
The port security is currently disabled. This means that the packets
with any ip/mac can be received/sent by the pod. A pod can do both MAC
and IP spoofing. However, by enabling port security we can limit the
addresses from which a logical port may send packets and to which it
may receive packets. This can be enabled by setting the
logical_switch_port's port_security column to the port's (MAC, IP)
address.
We cannot enable port security on K8s management logical switch port
since packets meant for local k8s node are forwarded through that port.
So, it receives packets with destination IP address that does not
belong to it.
> enable port security on the pod's logical switch port

- dist/images/.gitignore
- dist/images/Dockerfile
- dist/images/Dockerfile-ovndb-vip.ubuntu
- dist/images/Dockerfile.fedora
- dist/images/Dockerfile.ubuntu
- dist/images/Makefile
- dist/images/ovnkube.sh
Currently this info is parsed from files that are not guarnteed to be there.
For example in the case of git-pack-refs.
> Get git info from git commands

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/util/gateway-cleanup.go
For a given node, we add a logical_static_route to ovn_cluster_router that routes the packets to the local k8s node through the node's management port. Now, when the node is deleted we need to remove that static route from ovn_cluster_router.
> remove logical static route on node deletion

- dist/images/ovnkube.sh
commit 88edc8e2eb ("ovnkube.sh: optionally run as non-root user")
added support to optionally run OVS/OVN daemons as non-root user.
However, it forgot to add support for OVN NB DB daemon
> optionally run OVN NB DB as non-root user if needed

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/ovn/management-port.go
- go-controller/pkg/ovn/management-port_linux.go
- go-controller/pkg/ovn/management-port_linux_test.go
- go-controller/pkg/ovn/management-port_windows.go
- go-controller/pkg/ovn/management-port_windows_test.go
- go-controller/pkg/util/iptables.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/util.go
CRI-O already creates iptables rules for hostport ports, but they don't work because of weird non-symmetric routing into and out of OVN. Forcing packets going into the management port to be masqueraded ends up fixing this.
Is this the right fix? :man_shrugging: 
@dcbw
> gateway_localnet: add a rule to fix hostports

- FAQ.md
- dist/images/Dockerfile
- dist/images/Dockerfile.fedora
- dist/images/Dockerfile.ubuntu
- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
Currently, the CNI configuration and bin directories are not
configurable when using daemonsets. They are hardcoded to
/etc/cni/net.d and /opt/cni/bin respectively. This commit
adds support for using non-default locations using volumes
and volumeMounts field of the pod specification.
Added a FAQ file, and an entry within the FAQ file to capture the
steps required to enable non-default CNI directories.
> [daemonset] enable support for non-default CNI directories

- dist/images/ovnkube.sh
This allows better debugging of startup/dependency issues in onvkube.sh
from the daemonset/deployment YAML of each container, so that we don't
need to build special container images just for debugging.
@girishmg @shettyg @danwinship @pecameron
> ovnkube.sh: add OVNKUBE_SH_VERBOSE for 'set -x' debugging

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/node.go
It doesn't actually need any cluster controller private fields, so
no need to make it part of the cluster controller.
@girishmg @danwinship
> cluster: decouple CleanupClusterNode() from the cluster controller

- dist/images/ovnkube.sh
all of the docker images for ovnkube-node container doesn't have
loopback CNI plugin installed, so there is no point in trying to copy
over this binary as it will result in an error.
furthermore, the `looopback` CNI plugin will need to be installed by
the deployer on each of the kubernetes node as part of the node bring
up. this is one of the requirements of kubernetes. (See Kubernetes
CNI network plugin requirements on kubernetes.io)
> do not copy over loopback CNI plugin from the onvkube-node container

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/config/config.go
Currently we use client/server design to create and configure the pod
interface. The client being the ovn-k8s-cni-overlay and server
being the ovnkube-node container. The ovnkube-node creates and
configures the pod interface. This requires It to be running with
SYS_ADMIN capability and this is undesirable.
To make ovnkube-node to run with least capabilities as possible, the idea
is to create and configure the pod interface in the client itself (i.e., in
ovn-k8s-cni-overlay running on the host). In this approach, the deployer
explicity asks for unpriivelged ovnkube-node using a CLI option. The
server returns to client all the pod interface information (ip, mac, gateway,
MTU, ingresss, egress bandwidth, and so on). The client then creates
and sets up the pod interface.
Signed-off-by: Zhen …
> Add an option for CNI shim to create and configure the pod interface

- go-controller/pkg/cluster/master.go
> break after successully getting a subnet from the allocator

- dist/templates/ovnkube-node.yaml.j2
For Pod with security context runAsNonRoot, ovnkube-node container will
fail with statfs for NonRoot container's namespace with permission denied.
SYS_PTRACE is the ability to skip the seccomp check.
> add SYS_PTRACE capability to ovnkube-node container

- dist/images/ovnkube.sh
This was crashing when the daemonset restarted, because it would try and create endpoints that already exist. Change it to "kubectl apply"
> ovnkube.sh: idempotently set endpoints

- dist/images/ovnkube.sh
We currently have an issue where-in one can access OVN NB and SB DBs
from within the user's PODs. This commit resolves this issue by:
- opening passive connection at port 6641/6442 bound to the node IP
instead of INADDR_ANY
- adds a bunch of iptable rules to OVN-KUBE-OVNDB to drop the packets
from the cluster subnet CIDR
Fixes #624 
>  Bind OVN DB ports to the node IP instead of INADDR_ANY 

- go-controller/pkg/cluster/node.go
- go-controller/pkg/util/ovs.go
Introduce isOVNControllerReady routine and RunOVSAppctl utility function
in order to check if ovn-controller has established a connection to the SB
db and logical flows have been properly installed before proceeding with
ovn-k8s initialization
> cluster: introduce isOVNControllerReady routine

- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/gateway-cleanup.go
We add a default route to ovn_cluster_router that points to a L3
gateway router as the next hop. When the node that hosts the L3 gateway
router is deleted from the cluster, the default route still points to
the same l3 gateway router chassis. We also need to move all the
External IPs related Load Balancer rules to a different default gateway
router.
> update the default route when the next hop node is deleted

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/ovn/management-port_linux.go
- go-controller/pkg/ovn/management-port_linux_test.go
- go-controller/pkg/ovn/management-port_windows.go
- go-controller/pkg/util/iptables.go
Packets entering the OVN pipeline from the host or hostNetwork pods are
now SNAT'ed to management port IP. This is done so that the response
packets come back through the management port IP itself. However, the
rule is now just added to POSTROUTING chain. This fix moves the SNAT
rule to its own chain called OVN-KUBE-SNAT-MGMTPORT and delete the
chain on node deletion.
> Add OVN-KUBE-SNAT-MGMTPORT chain in iptables nat table

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovn-setup.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
the custom MTU value will be captured in ovn-config's new key 'mtu'
along side with svc_cidr and net_cidr keys.
> provide a way to modify the MTU of the default cluster network

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
Right now the master operations are under two different structures
and its receivers. This commit combines all the master operations
under the Controller struct in `ovn` package.
By doing so, all the node operations are under the OvnClusterController
in the `cluster` package.
So, there will be two controllers -- master (runs in ovnkube-master
process) and node (runs in ovnkube-node process).
In the next PR, I will rename `Controller` struct to OvnMasterController
and `OvnClusterController` struct to OvnNodeController.
> move master related receivers in OvnClusterController to Controller

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/endpoints_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/service_test.go
This PR comprises: the testing of the OVN DB re-creation should OVN die during its life-cycle. 
Among other, it increases the `ovn` package's test-covarage from 8 to 25 %. Testing has been abstracted a bit for increased readability. Tests have been added for the resources: `service`, `endpoints` , `pod` and `namespace`. 
These tests are more "integration tests" than any kind of unit-tests, thus the scale of these tests increases. So, please get back to me with any of your modifications on the readability of these tests. 
Please keep in mind that as long as the issue: https://github.com/ovn-org/ovn-kubernetes/issues/743 is not resolved, flaky builds will increase as a result of this PR. 
@dcbw
> Adding test cases for OVN sync

- go-controller/pkg/ovn/ovn.go
The commit ac57d2a213e2 changed the order of nodes and pods handler and
as a result the logical port creation is waiting behind the logical
switch creation. Note that all the watch* functions gets serialized on
the initial addObj() calls in sync*() function.
Fixes: ac57d2a213e2 (move master related receivers in
OvnClusterController to Controller)
> node watcher must be called before the pod watcher

- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
This is a work-around needed as to be able to create clusters using an OVN network plugin on GCP.
The kubelet sets `NodeNetworkUnavailable` on GCP node startup's, see [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L237) which will lead to problems for network plugins. Have a look at a previous discussion here: https://github.com/kubernetes/kubernetes/pull/34398
This PR introduces an overwrite of this condition once OVN starts so that it can proceed with the networking setup.   
@danwinship @dcbw
> Clear kubelet's NodeUnavailable status

- dist/images/daemonset.sh
- dist/templates/ovnkube-monitor.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- dist/yaml/.gitignore
with the prometheus monitoring scaffolding in ovn-kubernetes, we need
to add a way to enable prometheus to discover these endpoints and
scrape data out of it. to enable this we need to define a ServiceMonitor
resource and a corresponding Service resource that points to the
endpoint exposing metrics.
> define prometheus ServiceMonitor and Service resource for OVN components

- dist/images/Dockerfile
Due to the problems met in issue:
https://github.com/ovn-org/ovn-kubernetes/issues/855
We should use ovs 2.11 instead of 2.10 to fix the problem
of ovn-nbctl running in daemon mode.
So the ovs version used in the Dockerfile should be promoted
to 2.11 to build a suitable image for daemonset install.
The DPDK library is also updated to 18.11 to satisfy the requirement
of ovs2.11.
The related changes in Dockerfile for rpmArch of aarch64(arm64)
are also given.
Signed-off-by: Trevor Tao <trevor.tao@arm.com>
> Upgrade ovs version in Dockerfile to 2.11

- dist/templates/ovn-setup.yaml.j2
> remove the unnecessary annotation from the ovn-kubernetes namespace

- dist/templates/ovn-setup.yaml.j2
the serviceaccount user `ovn` has a cluster-admin role today and can
pretty much do anything in the clsuter. we need to fine grain access
control and pod privileges for this user.
to do this:
1. define a PodSecurityPolicy object that captures minimum required
security policies to run our deployments and daemonset.
2. define a ClusterRole object that captures all the resources we are
intersted in and all the actions we need on them. also, this role
should use the PodSecurityPolicy defined in step 1.
3. bind the above role to `ovn` serviceaccount
Note: this commit adds (1) that provides almost any securityContext to
be set (this can be restricted in future commits)
> do not assign cluster-admin role for the `ovn` serviceaccount

- go-controller/pkg/cni/helper_linux.go
Kubelet may keep multiple sandboxes running for a given pod if some are
waiting for garbage collection. We need to make sure that only the
latest sandbox has iface-id set to the container's namespace/name or
ovn-controller may get confused about which OVS port to associate with
the Pod's logical switch port.
@squeed @girishmg @danwinship
> cni/linux: ensure only the latest sandbox has external-ids:iface-id set

- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/util/net.go
Commit 0c0aa45d moved the creation of the management lsp to the master, but the comment and error message createManagementPortGeneric() doesn't reflect this.
Also, util.GetNodeWellKnownAddresses() never returns an error, so let's remove the return value and the error handling from callers.
(Just noticed this while reviewing #767)
> management-port: clean up from move to master

- go-controller/pkg/util/net.go
If dynamic addressing is set up, but there are no addresses assigned, then since commit 11f284c8, you'll see:
```
/usr/bin/ovn-nbctl --db=tcp:10.0.141.40:9641 --timeout=15 get logical_switch_port jtor-GR_ip-10-0-170-219.us-west-2.compute.internal addresses"
stdout: \"[dynamic]\\n\""
stderr: \"\""
failed to localnet gateway: error while waiting for addresses for gateway switch port
```
whereas the error before was:
```
failed to localnet gateway: empty addresses for gateway switch port
```
Restore the previous behavior by recognizing that [dynamic] means that no addresses are assigned.
> Handle static vs dynamic better in GetPortAddresses()

- docs/ovs_offload.md
The connection tracking offload is not merged yet into kernel and ovs
therefore update the doc to reflect that. Once all the patches get
merged we will update the doc with the relevant kernel and ovs versions.
This patch also fix the sriov device plugin json example
Signed-off-by: moshe010 <moshele@mellanox.com>
> Update ovs_offload doc that kernel and ovs are TBD

- go-controller/pkg/cni/bandwidth.go
- go-controller/pkg/cni/helper_linux.go
For egress network bandwidth, we configure ingress_policying_rate,
but, by itself, it might end up allowing less than the rate (e.g.
iperf TCP with a rate of 4Gbps gives < 1Gbps). OVSDB schema has
this to say about ingress_policying_burst:
"
Specifying a larger burst size lets the algorithm be more forgiving,
which is important for protocols like TCP that react severely to
dropped packets. The burst size should be at least the size of the
interface’s MTU. Specifying a value that is numerically at least as
large as 10% of ingress_policing_rate helps TCP come closer to
achieving the full rate
"
Set ingress_policying_burst to 10% of ingress_policying_rate.
Additionally, for a SR-IOV VF we also need to configure its
max_tx_rate using the egress value in Mbps.
Tested by configuring …
> Bandwidth: Actual egress bandwidth might be much lower than configured.

- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/cluster/management-port_linux.go
- go-controller/pkg/cluster/management-port_linux_test.go
- go-controller/pkg/cluster/management-port_windows.go
- go-controller/pkg/cluster/management-port_windows_test.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/util/net.go
GetNodeWellKnownAddresses() returns RotuerIP, ManagementPortIP, and PrefixLen. However, the RouterIP is returned ad RouterIP/PrefixLen whilst ManagementPortIP is returned without PrefixLen.
So, I changed the code to just return IPs. With that the callers can use PrefixLen if they want to construct an IP with mask. This also allowed me to use this Function at one other place in the codebase.
> make use of GetNodeWellKnownAddresses() in createManagementPortGeneric()

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/ovn/ha_master.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/OWNERS
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/metrics.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
- go-controller/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
- go-controller/vendor/vendor.json
This PR adds support for HA for ovnkube-master so that multiple ovnkube-masters can be run.
It is expected that, the HA for OVN DB servers if desired should be managed separately.
> HA for ovnkube-master using leader election

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_old.go
This had been done previously but was removed with commit https://github.com/ovn-org/ovn-kubernetes/commit/f99a10b1a4b9fa6fefb27e60628cc0960921ca5e 
We however still need this specific behaviour in case the OVN DB is completely destroyed, but the cluster and the corresponding kubernetes objects remain intact (possibly during a roll-out from OVN -> OVN HA). If not we'll have a different state between k8s vs. OVN. 
Test cases updated to test for this behaviour.
> Re-create the OVN DB with the k8s pod annotation, should it exists.

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
There is a race condition on namespace deletion where we try to unlock a nil mutex. Put a lock around the mutex map.
> namespace: fix panic

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/helper_linux.go
- go-controller/pkg/util/nicstobridge.go
In shared gateway mode, we share one of the interfaces on the node for
L3 gateway functionality (North-South) traffic. The IP address of this
interface on the host will be used to SNAT the pod traffic reaching out
to external world. Any NodePort traffic hitting the node at the shared
interface IP will be steered into OVN topology through OpenFlow rules.
The shared interface itself can be:
1. a physical interface
2. a OVS bridge interface
3. one of the internal ports of the OVS bridge
We support (1) and (2) today, but not ()3. This commit adds support
for (3).
Fixes #883
> allow OVS internal port to be a shared gateway interface

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/ovn/metrics.go
- go-controller/pkg/ovn/ovn.go
This adds a simple end-to-end test to determine that northd is working correctly. It periodically updates a value in NB_Global options, and exposes that same value, but from SB_Global.
It also adds some basic metrics plumbing.
cc @JacobTanenbaum @dcbw @girishmg
> pkg/cluster: add an end-to-end timestamp and metric

- go-controller/pkg/cluster/node.go
on our cluster, several ovnkube-nodes had a failed restart due to the
fact that `br-int` was not created yet by ovn-controller. the code in
isOVNControllerRead() checks for Openflow rules in br-int. however, it
could be that br-int is not created yet. as a result
`ovs-ofctl dump-flows br-int` fails and the container restarts.
wait for some time for the br-int to be created and then wait for the
flows to be created on br-int
> wait for the ovs integration bridge to be created

- go-controller/pkg/ovn/ovn.go
Clarify the issue that https://github.com/ovn-org/ovn-kubernetes/pull/859
fixed by splitting WatchNodes() out.
@girishmg
> ovn: split out WatchNodes() and add note about why it needs to be first

- dist/templates/ovn-setup.yaml.j2
extensions/v1beta1 is no longer supported in 1.16.
PodSecurityPolicy apiVersion should be policy/v1beta1 and
is back supported to 1.10
> PodSecurityPolicy should be apiVersion: policy/v1beta1

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ha_master.go
- go-controller/pkg/ovn/ovn.go
When all pods for a service VIP are removed, this used to result in the
load balancer for the VIP being removed from OVN.
With this change, we instead leave the VIP configured, but have the
backends in the OVN load balancer empty.
We also enable the controller_event northbound option. Now, with empty
load balancer backends, if OVN receives traffic for a load balancer VIP,
it will raise an empty_lb_backends event in the southbound database.
This patch adds an EventChecker method for the Controller that polls the
southbound database every 5 seconds to find if there are any unhandled
empty_lb_backend events. If there are any, then the event is parsed and
we send an event to kubernetes to request pods.
The use case for this is OpenShift's unidling. OpenShift will
automatically spin up pods if …
> Add unidling support.

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/namespace_test.go
When setting the value of the "addresses" column of an address_set,
each IP address should be quoted.  Otherwise, ovn-nbctl will emit an
error when parsing an IPv6 address like this one:
level=error msg="failed to set address_set, stderr: \"ovn-nbctl: fd01::58e2:7aff:fe00:13: unexpected \\\":\\\" parsing set of strings\\n\" (OVN command '/usr/bin/ovn-nbctl --timeout=15 set address_set a4065017480316135312 addresses=fd01::58e2:7aff:fe00:13' failed: exit status 1)"
> Ensure addresses are quoted for address set

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
While this is useful for the nodes, it doesn't really make sense for the master process to be connecting to ovsdb and setting connection information (ovsdbs or nodes). So, remove that.
> master: don't set connection in ovsdb

- go-controller/pkg/cluster/gateway_localnet.go
This code assumed an IPv4 address.  When the IP address is IPv6, we
must wrap it with square brackets to differentiate the address from
the : that separates the address from the port number.
> Wrap IPv6 address in [] before adding port

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
Enable IGMP Snoop (when supported) and IGMP relay to allow multicast
connectivity across nodes.
Enforce the following network policies for IP multicast traffic:
- a default deny-all network policy is applied to all IP multicast
traffic. This is implemented with two ACLs:
a) one ACL dropping egress multicast traffic from all pods:
this is to protect OVN controller from processing IP multicast
reports from nodes that are not allowed to receive multicast
traffic.
b) one ACL dropping ingress multicast traffic to all pods.
- when multicast is explicitly enabled in the namespace, IP multicast
traffic is forwarded only to pods in the same namespace. This is done
by adding:
a) a port group containing all logical ports associated with the
namespace.
b) one "from-lport" ACL allowing egress …
> Add multicast support.

- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/net.go
I encountered the following error in an ovn-controller log:
019-11-04T14:15:02Z|00025|lflow|WARN|error parsing actions "ct_lb(2600:1f16:d2d:3003:9dbc:39cc:ef6c:6dbb:6443);": Invalid numeric constant.
The root cause is that the IPv6 address was not wrapped in square
brackets when ovn-kubernetes configured the VIPs for a load balancer.
This patch fixes this issue, along with a number of other places where
net.JoinHostPort() needs to be used instead of performing the same
operation manually in a way that works for IPv4 only.
> Fix formatting of IPv6 LB VIPs

- dist/images/Dockerfile
The centos image gets a lot of vulnerabilities warnings at quay.io.
Running yum update cures them all.
> Run yum update in centos Dockerfile

- go-controller/pkg/cni/cnishim.go
> use %v to print a struct info instead of %q

- go-controller/pkg/cluster/node.go
with the current use of dump-flows to check if there are non-zero flows
in br-int, the log file for ovnkube-node is getting polluted with 1000s
of flows. instead use `dump-aggregate` which returns the flow_count to
determine the same
> use ovs-ofctl dump-aggregate instead of dump-flows

- go-controller/pkg/util/kube.go
A quick profiling session showed that decoding json is 50% of the CPU usage of ovnkube-master. There's no need to waste that time; switch to protobuf.
> Allow protobuf in client

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
During node addition the hostSubnet gets posted to node
annotations but that doesn't set the annotation in the
node object being used in the WatchNodes() AddFunc, so
when the management port handling function tries to
parse the annotation it won't get it.
@girishmg  what about this instead of https://github.com/ovn-org/ovn-kubernetes/pull/909 ? Saves us an unecessary API call because we have the hostsubnet already.
> ovn: use hostsubnet from node addition

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/ovn/ha_master.go
This PR cleans up the work done in https://github.com/ovn-org/ovn-kubernetes/pull/881 a bit. Specifically it changes the following:
* It makes sure that when ovnkube-node starts up, that the endpoint is configured properly as to avoid targeting an empty IP or incorrect ovnkube-master. 
* It does a `CreateManagementPort` (which sets up `br-int` in case it does not exist) before doing a `isOVNControllerReady` which dumps all flows on `br-int`. This usually fails for the first run of the container when `br-int` does not exist.
* It makes sure the `ovnkube-db` endpoint only has one master defined. If we have more than one, it's bad. 
* It simplifies the methods of the leader election process
> OVN HA - Cleanup and small fixes

- dist/templates/ovnkube-master.yaml.j2
-- changed run-ovn-northd to ovn-northd
-- changed run-nbctld to nbctl-daemon
the container names for the rest of the OVN/OVS components seem to
be meaningful to me
> rename run-ovn-northd and run-nbctld container names

- go-controller/pkg/ovn/ha_master.go
I don't think we should be running WatchOvnDbEndpoints() if we
aren't managing the DB servers? Endpoints map nil is not directly
related, but is likely why this gets called and panics.
```
E1109 05:52:57.673238       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522 …
```
> HA: fix assignment to nil endpoints annotation map

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
If a failure occurred during a pod Add the error would be logged
but setup would never be retried because the pod would remain
scheduled. Instead, use the 'ovn' annotation as a marker of
whether the pod has been set up or not. Since setting the annotation
should be the last thing we do, we can mostly use this as an
indicator of setup success.
@danwinship @girishmg @squeed
> ovn: retry pod setup in update if it fails during add

- go-controller/pkg/ovn/pods.go
now that podScheduledAndWantsNetwork() ensures that the pod to which
logical_switch_port is being created is not a HostNetwork pod and that
is already scheduled, there is no need to check the same in
addLogicalPort
@dcbw  @danwinship
> remove redundant checks in addLogicalPort()

- go-controller/pkg/ovn/ovn.go
SDN-637 - OVN doesn't work on GCP
https://jira.coreos.com/browse/SDN-637
Bug 1748162
[GCP]Failed to install cluster with OVN network type
https://bugzilla.redhat.com/show_bug.cgi?id=1748162
> gcp - Delete node annotation to permit workers to come up

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
Suggested by Girish.
@danwinship @squeed @girishmg
> pods: only track failed pods for retry-on-Update

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/master.go
Service annotations indicate when the service has been idled, so
only keep the empty LB for those services. Otherwise services with
no endpoints time out rather than have requests rejected as expected.
Fixes failures of the OpenShift/Kubernetes e2e test for:
[sig-network] Services should be rejected when no endpoints exist
@putnopvut @danwinship @knobunc @squeed @girishmg
> unidling: only keep empty LB for service when it has been idled

- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/config/config.go
- go-controller/pkg/ovn/metrics.go
- go-controller/pkg/ovn/pods.go
Add two metrics:
- the delta between pod schedule time and setting the annotations on the control plane
- the time spent on the node waiting for annotations to be set
Make metric names more consistent:
- All master metrics start with ovn_master_
- All node metrics start with ovn_node_
> master, node: add pod operation latency metrics, make metric names consistent

- go-controller/Makefile
- go-controller/hack/build-go.sh
- go-controller/hack/init.sh
- go-controller/hack/test-go.sh
- tell go to use the vendor directory
- Stop creating the fake gopath
- Don't test as root; build test binaries and execute them seperately
> Go mod followups

- go-controller/pkg/cluster/node.go
it is ok to fail while retrieving node's subnet information. we
eventually timeout and error out.
fixes: 59c177d3c326 (Cleaning up error/logging/panic handling in
different places)
@dcbw @alexanderConstantinescu
> fix node restart issue

- go-controller/go.mod
- go-controller/go.sum
- go-controller/pkg/config/config.go
these files with `debug` enabled are running into several GB over few
days, so add support for log rotation for these files
lumberjack seems very popular and works very well with logrus, so use
it to support log rotation
> add support for log rotation for ovnkube.log and ovnkube-master.log

- go-controller/cmd/ovn-kube-util/app/nics-to-bridge.go
- go-controller/pkg/util/ovs.go
While executing ovn-kube-util on a host to bring a NIC under an OVS
bridge, it fails with `ovn-nbctl` command not found. The subcommand
only needs `ovs-vsctl` to run, but expects a whole plethora of utilities
to be present. This commit validates only the required CLI binaries to
be present for ovn-kube-util to succeed.
@dcbw @danwinship  PTAL
> running ovn-kube-util shouldn't require binaries that it doesn't use

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
When handling the scheme:address:port URLs given to OVN for
configuring how to reach OVN services, properly handle IPv6 addresses
by not assuming we can just split on ":" across the whole string.
Also use JoinHostPort to properly join a host and port for both IPv4
and IPv6 cases.
> Fix parsing of IPv6 addresses in ovn URLs

- dist/images/ovnkube.sh
- dist/templates/ovnkube-monitor.yaml.j2
So, we have registered 9409 and 9410 port numbers for ovnkube-master
and ovnkube-node here:
https://github.com/prometheus/prometheus/wiki/Default-port-allocations
Change the current port numbers to use the reserved port numbers.
Furthermore, with the current port numbers -- 9101 and 9102 -- the
node_exporter daemonset is crashing because it uses one of the
above ports.
@dcbw @danwinship @squeed PTAL
> Change the prometheus port numbers to values allocated for ovn-k8s

- go-controller/pkg/ovn/master.go
- go-controller/pkg/util/gateway-init.go
the boolean argument that determined whether a localnet logical switch
port was required or not was required for spare gateway mode. the two
gateway modes we support today will always have localnet logical
switch port, so remove that redundant argument
> remove redundant argument to GatewayInit() from spare gateway mode days

- go-controller/pkg/cni/cni.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
- go-controller/pkg/util/util.go
The pod network info of IP, MAC, Gateway, and Routes are under
'ovn' annotation. We need to move it under 'k8s.ovn.org' namespace.
The new annotation is called 'pod-networks', and it is going to be a
map of 'network_name' to pod's IP information on that network. For
example: ("default" refers to the first OVN interface to the Pod)
{
"default": {
"gateway_ip": "192.168.2.1",
"ip_address": "192.168.2.3/24",
"mac_address": "8a:24:f4:a8:02:04"
}
}
The changes assumes that the master is upgraded first. It continues to
write both the old/new annotation names to facilitate yet-to-be
upgraded ovnkube nodes. In the next release of ovn-kubernetes, we can
remove the code that adds `legacy` annotation.
> Move pod annotation under k8s.ovn.org namespace

- go-controller/pkg/ovn/master_test.go
The current test annotates the node upfront and later checks to see if
the node has correct subnet information. This is not right. We need to
start with no subnet annotation and then later check if the node has
subnet annotation.
> do not annotate test node with subnet information upfront

- go-controller/pkg/cluster/node.go
As with all the other Poll*() functions, don't return an error if
all we want to do is just check again at the next interval.
@danwinship @girishmg @squeed @pecameron
> node: don't return error from isOVNControllerReady() flow check

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/management-port_linux_test.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
The node's subnet information is  under 'ovn_host_subnet' annotation.
We need to move it under 'k8s.ovn.org' namespae.
The new annotation is called 'node-subnets', and it is going to be a
map of 'network_name' to node's subnet allocation from that network.
For example: ("default" refers to the first OVN interface to the Pod)
k8s.ovn.org/node-subnets: {
"default": "192.168.10.0/24"
}
The changes assumes that the master is upgraded first. Since this
annotation is used only in the master the old worker nodes are not
going to be affected by this change. As a result, on master upgarde to
this code we are going to remove the old key and add the new key to
the nodes as part of syncNodes() call.
@dcbw PTAL
> Move node annotation under k8s.ovn.org namespace

- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/util/ovs.go
in the shared gateway mode, we add OpenFlow flows to setup default
connection tracking rules and NodePort rules. as part of cleanup we
need to remove all the OpenFlow rules.
> gateway: remove all the OpenFlow flows from the OVS bridge

- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/gateway-cleanup.go
This should fix the following error seen in an ovnkube-master log:
time="2019-12-03T01:11:33Z" level=error msg="Failed to fetch all routes with IP fd01:0:0:4::2 as nexthop, stderr: \"ovn-nbctl: fd01:0:0:4::2: unexpected \\\":\\\" parsing string\\n\", error: OVN command '/usr/bin/ovn-nbctl --timeout=15 --data=bare --no-heading --columns=_uuid find logical_router_static_route nexthop=fd01:0:0:4::2' failed: exit status 1"
> Quote IPv6 address in ovn-nbctl find command

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/util/net.go
Most error logs as the result of a failed ovn-nbctl / ovs-vsctl / etc
included stdout and stderr, but I got a couple in my logs that didn't.
I've added them here to help with debugging these conditions.
> Add stdout and stderr to more error logs

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_shared_intf.go
We already have ofport obtained in nodePortWatcher() function, however
we obtain it again in syncServices() called from nodePortWatcher(). so,
pass that value into syncServices() instead.
@dcbw @danwinship this is a simple one
> reuse the ofport computed in nodePortWatcher in syncServices as well

- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/windows/kubernetes/tasks/main.yml
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
According to the official kubernetes documentation, the `beta.kubernetes.io / os` tag has been deprecated, and the new version will use` kubernetes.io / os`
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os
@danwinship @squeed @JacobTanenbaum @girishmg @alexanderConstantinescu
> update beta.kubernetes.io/os to kubernetes.io/os

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
GetK8sClusterRouter() returns the OVN distributed router in the K8s
OVN topology. In a 400-node cluster, that function searches through
801 routers to find the distributed cluster router (the one with
external_ids:k8s-cluster-router set to yes). Initially, it was written
for use by clients such as ovnkube-node.
However, after the gateway creation move to master there is no need for
that function since the master already knows the name of the distributed
cluster router since it created it. So, remove that function and
directly use the constant that captures the name of the distributed
router.
> GetK8sClusterRouter() function is expensive when it doesn't need to be

- go-controller/pkg/cluster/node.go
Set log level to debug during node bringup and revert it to the
configured value when bringup is complete.
SDN-734 - [ovn] log kernel interface creation including MTU
https://issues.redhat.com/browse/SDN-734
> Manage log level during node bring up

- go-controller/pkg/cluster/management-port_linux_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/util/net.go
get both dynamic_addresses and addresses values for logical_switch_port
in one call ovn-nbctl call instead of the current two calls.
> get dynamic_addresses and addresses in one go instead of two execs

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_localnet_windows.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
Currently, the node gateway annotations are in map[string]string format.
As in,
annotations:
k8s.ovn.org/node-gateway-iface-id: breno1_sdn-test1
k8s.ovn.org/node-gateway-ip: 10.8.51.51/22
k8s.ovn.org/node-gateway-mac-address: ac:1f:6b:59:97:34
k8s.ovn.org/node-gateway-mode: shared
k8s.ovn.org/node-gateway-next-hop: 10.8.48.1
k8s.ovn.org/node-gateway-vlan-id: "0"
However, in order to support multiple OVN interfaces we would like
those annotations to be map[string]map[string]string. For example:
annotations
k8s.ovn.org/l3-gateway-config: {
"default" : {
"interface-id": "breno1_sdn-test1,
"ip-address": "10.8.51.51/22",
"mac-address": "ac:1f:6b:59:97:34",
"mode": "shared",
"next-hop": "10.8.48.1",
"vlan-id": "0",
}
}
The key "default" above represents the default network attachment to
the pod …
>  move the node gateway annotations to map[string]map[string]string format

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/util/metrics.go
pprof is a useful tool for profiling and finding hot spots. Make it easy to enable.
> cmd: add --metrics-enable-pprof option to serve pprof on metrics port

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
Values in loopback range (127.0.0.0/8) are invalid and cannot be used
for the endpoint.
> Fixes detecting loopback for ovnkube-db endpoint

- dist/templates/ovnkube-monitor.yaml.j2
Though we don't have readiness probes right now, it's a best practice to scrape not-ready endpoints for daemonsets.
> Update metric service to include not-ready endpoints

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/gateway-init.go
OVN Gateway logical resources are now being created on the master. To
create a L3 gateway, we need the node's system ID. We are retrieving
this information in the master by using
`ovn-sbctl find chassis hostname=<nodename>`.
In a large cluster with 100s of kubernetes nodes and busy OVN SB DB,
sometimes we timeout while getting this information.
It is better for each node to pass the system ID through node annotation
along side with other information it currently passes for gateway
creation.
> add node systemID to the list of information passed from node to master

- dist/images/ovnkube.sh
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
- vagrant/provisioning/setup-master.sh
After we migrated the gateway related logical resources creation to
master, the master is now creating LB rules for NodePort services for
all of the nodes irrespective of the fact whether the NodePort feature
is enabled or not on the node.
Each node through l3-gateway-config`node-port-enabled annotation will
specify if the NodePort must be enabled or not. The master acts on this
annotation to create LB rules for specific nodes.
> create NodePort related LB rules only for nodes for which it is enabled

- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/cluster/management-port_linux_test.go
the MAC address for node's management port is randomly chosen. this
address is then added to node's annotation. the master reads the
address and creates a corresponding logical switch port using this
address.
now when node reboots, the mac address of the management port on the
node changes. this changed address is then reflected on node's
annotation and then in the UpdateFunc callback handler for the node
resource, we update the MAC address of the logical switch port.
this is all unnecessary complexity, so better way is to just
persist the initial MAC for the management port in the interface's
MAC column
> persist the mac address associated with the node management port

- dist/images/daemonset.sh
daemonset.sh uses awk $2 with "=" delimiter so it misses the rest of the options if there is a = in it.
For example: daemonset.sh with --gateway-options="--gateway-interface=eth2 --gateway-nexthop=172.17.20.1"
ends up with: ovn_gateway_opts: --gateway-interface
while it should be:
ovn_gateway_opts: --gateway-interface=eth2 --gateway-nexthop=172.17.20.1
Use cut to take all the variable text.
> Fix parsing of gateway-options

- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
the logic behind finding the nexthop for default route for
ovn_cluster_router is very involved. it first finds all the L3 gateways
and then sorts it and picks the first one in the sorted list.
we were doing this everytime a node was added. so, in a 400-node cluster
we were doing the same computation and adding the same duplicate route
again (off course with --may-exist flag) 400 times.
so, i thought of caching the result and re-using the cached nexthop.
then it occured to me that we don't even need default route. we already
had source-ip based routes for every node in the cluster. this route
was never used since it will never get matched (as src-ip based route
will always match and the packets from a node will exit out through its
l3 gateway)
so, i have removed the code to add the default …
> no need to add default route to ovn_cluster_router

- dist/images/ovn-debug.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- go-controller/pkg/cluster/node.go
- go-controller/pkg/util/ovs.go
OVN post split from OVS (post 2.12) has changed the paths for the
runtime directory, log dir and db dir.
The default runtime dir is now - /var/run/ovn
The default log dir is now - /var/log/ovn
And the default db dir is - /etc/ovn
In order to support latest OVN version, this patch checks for the
presence of the file - /usr/bin/ovn-appctl. If this utility is
present, it means the deployment has latest OVN with new dir paths
and uses the new dirs. Else, the old openvswitch dir paths are used.
[Submitting as RFC as I want to get the feedback if this is the right
way to do.]
> Support latest OVN

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
The issue is that br-local was inheriting the lowest MAC from its
port and in this case it was br-nexthop. So, change the order in
which the mac address is fixed for br-local bridge. First, create the
br-local bridge and set other_config:hwaddr with mac_in_use value. Next,
create the br-nexthop interface with fixed mac address.
Fixes: 75f836d91e1e (create br-nexthop OVS internal port with fixed MAC
address)
> set other_config:hwaaddr on br-local before you add br-nexthop

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/gateway-init.go
With 400+ odd nodes, the current GatewayReady() function is not
scaling. The ovn-nbctl calls are timing out. When we have a way to find
out that the data path for the L3Gateway is ready by checking
for OpenFlow rules on the integration bridge we should make use of it.
Adding SNAT rules is the last thing we do while building the logical
topology. So, check for the SNAT rule in table 65 in the integration
bridge
> scale: ascertain gateway readiness by checking OpenFlow rules

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config.go
ovn-kubernetes was already setting ovn-remote-probe-interval.  This
patch follows the same pattern for ovn-openflow-probe-interval, and
does it for the same reasons.
The default value for this option is 5 seconds. On a large cluster,
this can cause excessive CPU consumption in ovn-controller.  If it
takes ovn-controller 5 seconds to do a full state computation, then
you'll see ovn-controller end up in effectively a busy loop, because
it isn't able to keep up with this probe interval.
The openflow probe is even less interesting than the OVSDB
remote probe.  At least the ovsdb connection is to something remote.
The openflow connection is always local, so this is unlikely to be a
problem.  We now set it to 3 minutes by default, just in case, instead
of disabling it completely.
Signed-off-by: …
> ovn-controller: Set ovn-openflow-probe-interval

- go-controller/pkg/factory/factory.go
ovnkube-master.log file, with 290K lines of log messages, had close to
221K lines of '... UPDATE for event handler X' log messages that doesn't
provide any meaningful information. in fact, in that noise we might miss
important log message. so remove these debug messages.
> remove unwanted debug log messages in factory.go

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_common.go
currently, that function gets other-config to ascertain that the
logcial switch is created for a node and continues. later on, we make
an another call to get other-config:subnet. instead, check for
other-config:subnet itself and avoid an unnecessary call.
@dcbw PTAL
> scale: waitForNodeLogicalSwitch() should get other-config:subnet itself

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_old.go
- go-controller/pkg/ovn/policy_old_test.go
This PR fixes a special corner case which can completely block pod creation from ever happening.  
If the following sequence of events happen, pod creation will be blocked: 
1) We begin by deleting the ovn-kubernetes master, upon which a new leader election is made by k8s (the switch between leaders is not instantaneous of course), 
2) If we happen to have a pod deletion in between the time our last leader has died and the new leader is elected and has his informers initialized, then we loose this delete.
3) If the deleted pod is now re-created on a different node, then: since we never received the last delete, we will still have the old pod in the OVN DB with an associated logical port attached to its old node's logical switch and we subsequently fail to create it's new logical port …
> Check pod annotation on syncPod as to handle pod re-sync correctly

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
clearInitialNodeNetworkUnavailableCondition() called from Node
UpdateFunc() is very expensive. In our 600-node cluster, the
updateFunc() is called almost every second. We are spending lot of CPU
cycles in that funciton due to DeepCopy and such. call this function if
the node is part of a cloud provider (Node.Spec.ProviderID is set)
@dcbw @danwinship @alexanderConstantinescu PTAL
> scale: clearInitialNodeNetworkUnavailableCondition() is very expensive

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_shared_intf.go
Say, we share the interface eth0 in the shared gateway mode and that
the ovs-bridge br-eth0 has an additional interface 'vlan100'
br-eth0(LOCAL)  vlan100    patch_port_to_br_int
|        |       |
|        |       |
+-+--------+-------+---+
|       br-eth0        |
+--------+-------------+
|
|
eth0
In the current code, the inbound traffic to vlan100 is always sent to
LOCAL port and therefore services on vlan100 is not reachable. Fix this
by using NORMAL action.
> do normal processing for all inbound packets that are not tracked

- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/cluster/management-port_linux_test.go
- go-controller/pkg/cluster/management-port_windows_test.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/net.go
currently, the MAC address for the logical_router_port on the
distributed_router that connects to node logical_switch is generated
randomly. that by itself is not an issue. however, we depend on this
MAC address on each of the node. each of the ovnkube-node deamon does
routerMAC=`ovn-nbctl lsp-get-addresses stor-node1`
the above call doesn't scale with large number of nodes, and the above
command times out.
instead of creating a random MAC address, use a fixed MAC address that
is formed using the octets of gateway IP address. we already make an
assumption that the 1st IP of the node subnet is the gateway address,
and therefore we can easily derive at the MAC address on the node
without making a ovn-nbctl call.
@dcbw PTAL
> scale: fixed MAC address for the logical router ports

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/endpoints_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_old_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/ovn/service_test.go
- go-controller/pkg/testing/testing.go
Mostly making sure we shut the watcher down more consistently so events don't bleed into subsequent tests.
@girishmg @danwinship
> Factory and testcase cleanups

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
currently, if the ovn specific pod annotation exists, then we read
pod interface info from the annotation and re-create the corresponding
logical switch port. this is all good, however we continue further and
get the pod interface info from OVN logical topology and add the
annotation back. this is not required. so, exit early
@dcbw @danwinship  PTAL
> exit early if ovn specific pod annotations exists

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
--wait=sb doesn't play well with ovn-nbctl in daemon mode. when the
client call to the daemon timeouts with SIGALARM (after 15 seconds) the
daemon itself is stuck and any subsequent ovn-nbctl calls will not
succeed until the 1st call completes. so, we need ot avoid using
--wait=sb when using ovn-nbctl daemon mode. instead fall back to the
retry loop
> avoid using --wait=sb in ovn-nbctl calls when using ovn-nbctl daemon

- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/management-port_linux.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/util/gateway-init.go
I think this PR includes all of the changes needed in a fork to get ovn-kubernetes working with IPv6.  Much of this was reworked from hard-coded IPv6 support to conditional, so it should not change any behavior by default unless configured with IPv6 subnets.
There are a couple of workarounds included here which could use more investigation, but they make things work for now.
> IPv6 single-stack support

- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/util/gateway-init.go
IPv6 mode or not is a deployment time thing and is going to be that way
till the cluster is torn down and brought up in the other mode. So,
figure out the mode in the beginning instead of determining
the mode in every call to UseIPv6().
@russellb @dcbw PTAL
> determine whether we are running in IPv6 mode once at the start time

- dist/images/ovnkube.sh
in ready_to_start_node() we use `ovn-nbctl show` to check if the DB
endpoints are up. however, they are very expensive at scale as can be
seen below
$ ovn-nbctl -vjsonrpc show >/dev/null 2>/tmp/show
$ ll -lh /tmp/show
-rw-r--r-- 1 root root 4.2M Jan 14 15:49 /tmp/show
so, close to 4.2M amount of data is downloaded and if all the
ovnkube-node restart at the same time, then we have data storm.
instead use `ovsdb-client` and the data exchanged is 227 bytes
$ ovsdb-client -vjsonrpc list-dbs $OVN_NB_DB >/dev/null 2>/tmp/list_dbs
$ ll -lh /tmp/list_dbs
-rw-r--r-- 1 root root 227 Jan 14 15:51 /tmp/list_dbs
> scale: use light weight check to ensure OVN DB endpoints are up

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/ovn.go
Add infrastructure for parallel event handlers and make Node events
use it.
@squeed @danwinship @girishmg 
Alternate take on https://github.com/ovn-org/ovn-kubernetes/pull/913 that hashes into a set number of event queues, rather than queue-per-object, per Casey's suggestion in 913.
> factory: parallelize Node events

- go-controller/pkg/util/kube.go
GetNodeIP is used to determine an IP address for the Node to use as
the address other Nodes will use to create Geneve tunnels to this
Node.  It previously filtered out IPv4 addresses, but that breaks an
environment where the Nodes only have IPv6 addresses.
The code will now adjust between expecting an IPv4 or IPv6 address
based on which mode it is in.
> Allow IPv6 Node addresses for geneve tunnels

- go-controller/pkg/util/kube.go
This is a follow-up based on discussion in PR #1013.
Relax the requirements on address type for tunnels and use whatever IP
we can find that should work.  If this behavior doesn't work in some
environment, the encap IP can be configured explicitly instead by
setting the encap-ip configuration option.  This should be safe
default behavior, because it will only use an IP that can be
determined via DNS for the Node.
> Restrict address type requirements for tunneling

- go-controller/pkg/ovn/pods.go
Previously when adding the pod's logical switch port with the --wait=sb option
the wait=sb waited long enough for ovn-northd to perform address assignment
for the pod, so the address was immediately available after the lsp-add.
But without the --wait=sb we try to read the address immediately, fail
because ovn-northd hasn't quite gotten around to assigning it yet, and
then wait a full second before we try again.
Fix that by trying to read the address a couple times using exponential
backoff from 50ms -> 105ms -> 220ms -> 463ms -> 972ms and then polling
every second until quitting after ~32 seconds.
@girishmg @danwinship
> ovn: read pod addresses more quickly

- README.md
- go-controller/go.mod
- go-controller/pkg/config/config_test.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/config/utils_test.go
Previously if not provided, the per host subnet prefix length was set to
24. This presents an issue if the cluster subnet provided by the user is
also 24. This patch adds the following:
- Validations on the value when host subnet length is provided
- When host subnet length is not provided, validation is done to ensure
there are a minimum of number of bits left to subnet out the per-host
subnets
- The new default host subnet length is set to cluster mask + 3 bits
(8 per-host subnet) when possible. Otherwise it is set to the maximum
possible value while still preserving enough room for host
addressing.
> Validates host subnet prefix length and default behavior

- go-controller/pkg/cni/types/types.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/kube.go
One can specify the custom MAC off of the annotation on the POD
spec defined like this below:
```
annotations: v1.multus-cni.io/default-network: | [
{
"namespace": "kube-system",
"name": "ovnkube",
"mac": "aa:bb:cc:dd:ee:ff"
}
]
```
The OVN interface that gets added to the POD will have that MAC instead
of OVN chosen MAC.
Fixes #776
@dcbw @danwinship PTAL. 
BTW, the net-attach-def client here https://github.com/k8snetworkplumbingwg/network-attachment-definition-client doesn't yet support parsing NetworkSelectionElement for MAC, IPs, and default-route. So, I can't use it in this PR
> add support for custom MAC specified in default network-attachment

- dist/templates/ovnkube-node.yaml.j2
i am seeing the following error while applying ovnkube-node.yaml,
error: error parsing ovnkube-node.yaml: error converting YAML to JSON:
yaml: line 231: mapping values are not allowed in this context
the issue is that `tolerations` got indented incorrectly
- name: host-config-openvswitch
hostPath:
path: /etc/origin/openvswitch
tolerations:
- operator: "Exists"
Fixes: 3b6d22cad910 (Make KIND specific yaml rendered)
@trozet FYI
> fix parsing error in onvkube-node.yaml post changes for kind

- .travis.yml
Regexp for conformance test was not matching. Move conformance test to
its own kubetest execution, as it seems as running conformance in
parallel with network policy causes some tests to be flaky.
> Fix kubetest to enable conformance

- dist/images/daemonset.sh
so, we need to use -e CLI option of j2. if we just export the
environment variables, the jinja2 variables inside the template
are not getting replaced. it instead ends up using the default value.
Fixes: 3b6d22cad910 (Make KIND specific yaml rendered)
@trozet FYI again
> j2 utility is being used incorrectly in daemonset.sh

- dist/images/ovnkube.sh
it could be that the IP that the hostname resolves to is not the
intended ip for Geneve VTEP. provide a way for ovnkube.sh to get to
know about the actual encap IP to be used on the node.
the assumption here is that some entity sets up the
external_ids:ovn-encap-ip with the right vtep ip and ovnkube.sh scraps
that info and passes it to onvkube through --encap-ip option.
@danwinship @dcbw PTAL
> a way to specify the encap-ip for a k8s worker node

- .travis.yml
It seems the default 10m timeout is not sufficient for the e2e tests in travis. Not surprising.
@girishmg @trozet @danwinship
> travis: bump timeout for e2e tests

- go-controller/pkg/util/nicstobridge.go
This only necessary when using shared gateways which is never a valid
scenario for OpenShift. Hence it should never be an error but a warning.
This is important because it's currently breaking some tests suchs as:
https://github.com/ovn-org/ovn-kubernetes/pull/1017#issuecomment-579300124
> pkg/util: nicsToBridge failing to config open file is a warning

- dist/images/Dockerfile.fedora
- dist/images/Makefile
> Update Fedora docker image to get ovn/ovs 2.12

- go-controller/pkg/cluster/gateway_init.go
when we delete ovnkube-node, to say fix some issue or it met a panic,
we delete the integration bridge. this inturn deletes all the POD's
ports on the integration bridge. When the ovnkube-node comes back up,
the integration bridge is created but not the ports on it. as a result
all the PODs are disconnected from network.
> do not delete integration bridge as part of ovnkube-node cleanup

- dist/images/Dockerfile
- dist/images/Dockerfile.ubuntu
- dist/images/iptables-scripts/ip6tables
- dist/images/iptables-scripts/ip6tables-restore
- dist/images/iptables-scripts/ip6tables-save
- dist/images/iptables-scripts/iptables
- dist/images/iptables-scripts/iptables-restore
- dist/images/iptables-scripts/iptables-save
- dist/templates/ovnkube-node.yaml.j2
CentOS 8 doesn't have iptables. It instead has nftables. Our code uses
iptables, so we need a way to translate our iptables call into nftables.
On the CentOS host, the ip{6}tables CLI utilties  are symbolic links to
to xtables-nft-multi.
$ file /usr/sbin/iptables
/usr/sbin/iptables: symbolic link to xtables-nft-multi
That particular binary does the right thing. In our case, we don't want
to install iptables in our ovnkube containers. Instead we need to run
the iptable (xtables-nft-multi) utility in the host. This is done
using the iptable-wrapper scripts and some volume mount tricks.
@dcbw @danwinship something that you guys use and that we talked about during the kubecon. We ave started using this internally as our hosts are CentOS 8. PTAL
> fix for iptables issue in CentOS 8

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node_test.go
The configuration was attempting to use the chassis name rather than the
uuid in the Encap table.
> Fixes specifying geneve port

- dist/images/Dockerfile
- dist/images/Dockerfile.ubuntu
- dist/images/iptables-scripts/ip6tables
- dist/images/iptables-scripts/ip6tables-restore
- dist/images/iptables-scripts/ip6tables-save
- dist/images/iptables-scripts/iptables
- dist/images/iptables-scripts/iptables-restore
- dist/images/iptables-scripts/iptables-save
iptables binary is in /sbin on all distro so use that path
Ideally, iptables should be in /usr/sbin. this is true for CentOS, RHEL,
and Fedora. However, ubuntu has this binary in /sbin.
All the distros have this binary (or symbolic link) in /sbin. So use it.
> Iptables followup

- .github/workflow-templates/test.yml
- .github/workflows/test_generated.yml
- contrib/kind.sh
Instead of a mix of 'ovn' and 'kind-ovn' just use 'ovn'. Also fix the node name so that log dumping works and we get artifacts.
> ci: use consistent kind cluster name and fix artifact retrieval

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
In the logical topology we have, the join logical switch connects all
the L3 gateways together on a single L2 broadcast domain. So, with 622
k8s nodes the join logical switch connects 622 L3 gateways and 1
distributed gateway router (ovn_cluster_router). This ends up in
creation of hundreds of thousands of logical flow entries in OVN SB’s
lr_in_arp_resolve table across all of the 623 gateway routers.
These flows add the destination MAC address to the packets bound to
other router ports. Every L3 gateway router has ARP resolve entries in
lr_in_arp_resolve table for 622 other router’s IP address. So, this
results in 622 * 622 entries. Which is 386K entries. Add in IPv6
entries, then it will be 772K entries.
Both ovn-northd and ovsdb-server NB daemon is super busy processing
these flow …
> scale: current logical topology doesn't scale with large cluster

- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
Allow node --nb-address / --sb-address addresses to be obtained by watching endpoints
Signed-off-by: Michael Cambria <mcambria@redhat.com>
> Allow node --nb-address / --sb-address to be learned 

- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/namespace.go
Currently the controller code makes expensive API server calls to
GET objects. This commit changes that to use the informer cache as
the datastore to get objects faster. This will result in performance
benefits esp. at high scale.
> Controller: Use informer cache as object store to get objects

- go-controller/pkg/cni/types/types.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/kube.go
It’s generally expected that the the cluster-wide default network
attachment sets a default route. This default route may be overridden
using the “default-route” key in the Network Attachment Selection
Annotation (see 4.1.2.1.9) on another attachments. In that case, we
should skip adding default route on the OVN interface and instead just
add cluster subnet routes for the OVN interface.
Consider the set of annotations below on a pod:
```
annotations:
v1.multus-cni.io/default-network: ovn-kubernetes
k8s.v1.cni.cncf.io/networks: |
[
{
"name":"sriov-storage-net",
"default-route": ["10.1.32.2"]
}
]
```
The first interface to the pod is provided by ovn-kubernetes and the
second interface is through SRIOV CNI. The default route for that
pod should be through the second interface. So, the routes …
> skip adding default gateway for OVN interface in certain cases

- dist/images/ovnkube.sh
we have code in ovnkube.sh that creates the above folder and it is
not required since all the DB files are going to be either in
/etc/ovn or /etc/openvswitch
>  no need to create /var/lib/openvswitch inside the container

- dist/images/Dockerfile
- dist/images/Dockerfile.fedora
- dist/images/Dockerfile.ubuntu
- dist/images/daemonset.sh
- dist/images/ovndb-raft-functions
- dist/images/ovnkube.sh
- dist/templates/ovn-setup.yaml.j2
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/yaml/.gitignore
This commit implements the clustered database as a statefulsets with
replicas set to 3. The PodManagementPolicy of OrderReady is too
restrictive for how RAFT works, so instead Parallel policy is used.
The existing ovnkube-db service acts as the headless Service for the
statefulset. The pods are scheduled on the nodes with labels
`ovn.org/ovnkube-db=true`.
Implementation notes:
1. ovnkube-db-0, the first pod in the statefulset creates the initial
cluster DB. If an existing standalone DB is present, then it converts it
into the clustered DB.
2. ovnkube-db-1 ... ovnkube-db-{n-1} pods wait until the ovnkube-db-0
has successfully started and then only join the cluster.
3. ovnkube-db-{n-1}, the last pod in the statefulset will ensure that
all of the pods in the statefulet are up and running and …
> Clustered database (aka RAFT) support for OVN DBs

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
Girish identified a race where the initial object Add events that are
sent when a handler is attached to an informer were not properly locked
against incoming events to that informer from the apiserver.
To fix this send the initial Add events while the informer's lock is held.
@girishmg @danwinship @ovn-org/ovn-kubernetes-committers @trozet @alexanderConstantinescu @juanluisvaladas @JacobTanenbaum @pecameron @mccv1r0 @rcarrillocruz
> factory: fix race between queued informer initial add and other events

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/util/kube.go
Previously OVN Kubernetes assumed the node's name in kubernetes was the node's
FQDN, which isn't necessarily true, with this change we read it from the
kubernetes API, which is more reliable.
> pkg/util: make GetNodeIP get the ip address from Kubernetes API

- .github/workflow-templates/test.yml
- .github/workflows/test_generated.yml
It's useful to see successful logs too.
> ci: always export logs

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/node.go
7358508a changed GatewayReady() from using ovn-nbctl to using ovs-ofctl, but checked for an IPv4-specific rule. Fix it to use IPv6 syntax when checking for IPv6 CIDRs.
(I checked the actual CIDR rather than using `config.IPv6Mode` because it was easy, and it means we won't have to revisit this for dual-stack.)
> cluster: Make GatewayReady() IPv6/dual-stack safe

- contrib/kind.sh
kube-proxy is not necessary for OVN.
> Remove kube-proxy in KIND deployment

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
When config is read, the config file is parsed first. After these
settings are loaded, the CLI settings are parsed and override any
settings read from the file. This is fine, except for the CLI settings
may be defaulted, which will just override any specified config file
settings with defaults.
This patch addresses the problem by checking during config override if
the the configuration option has a default specified, and if so, ignores
overriding the current config option.
Additionally, this patch adds real default values for settings.
> Fixes accidental override of file conf settings with defaults

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
add an -ignore-node-labeled flag to the command line to specify a
node label for ovn-kubernetes to ignore. When ignored the node must
have some way to manage the network on its own.
> add the ability for ovn-kubernetes to ignore a node by label

- go-controller/pkg/config/config_test.go
If you have `KUBECONFIG` set in your environment then `make test` will fail
> config: don't let environment affect test results

- go-controller/pkg/ovn/policy.go
when a pod is deleted, its logical_switch_port is deleted and so is the
corresponding entry from logicalPortUUIDCache. In the
handleLocalPodSelectorAddFunc, we fail to get the UUID for the just
deleted pod's logical switch port and we return early from the function
without cleaning up various caches.
Now, say the same pod is added back. All these caches will have stale
data and we fail to add the newly added logical_switch_port to the
port_group.
> network policy's logicalport cache gets out-of-sync on pod deletion

- .github/workflow-templates/test.yml
- .github/workflows/test_generated.yml
This brings down (cached) CI runs from ~35 minutes to ~22 minutes, while also running more e2e tests.
cc @trozet @dcbw
> Add caching for k8s build and shard tests

- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/pkg/config/cni.go
Allow reading the PrevResult on DEL so that we can extract the pod's IP address (if available) at deletion time.
@JacobTanenbaum
> cni: bump supported version to 0.4.0 for PrevResult on delete

- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
With recent changes to OVN to block untracked traffic like ARP, we now
need to explicitly allow it in the default ACLs.
Closes: #1076
> Fixes default Network Policy to allow ARP

- dist/templates/ovnkube-db.yaml.j2
both the NB/SB container runs the iptable rules to open their
respective ports on which it listens for client connections. post
commit 42848736b202 (fix for iptables issue in CentOS 8), we are seeing
errors in the nb/sb db log files that chroot cannot change the directory
to '/host' since we forgot to add volumes and volume mounts in
ovnkube-db.yaml.j2
> fix chroot's cannot change root directory to '/host' error

- go-controller/pkg/util/ovs.go
1.  RunOVNNorthAppCtl() API uses incorrect ctl file
this api uses the incorrect path of ${OVN_RUN_DIR}/ovn-northd.ctl.
however, the control file path for ovn-northd is of the format
${OVN_RUN_DIR}/ovn-northd.<pid>.ctl.
2.  use ovn-appctl when available otherwise use ovs-appctl
this commit fixes small issue introduced by acbe1c59d00f (Support latest
OVN). the current code always uses ovs-appctl even though ovn-appctl
might be available.
@numansiddique @dcbw PTAL
> fix errors in ovn-appctl and ovs-appctl usage

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old_test.go
- go-controller/pkg/ovn/policy_test.go
in the current code, we expand all of the addresses in a namespace and
then perform a set operation against the address_set OVN NB table. this
is very expensive.
consider a namespace with 100 pods and that a new pod is added to that
namespace. Now we walk through all the 101 addresses for the namespace
and set the 101 addresses against address_set OVN NB table instead of
just adding the new address. on pod deletion, we do the same thing as
well.
> use add and remove OVSDB table operations instead of set

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node_test.go
ovn-controller enables conditional monitoring by default for tables in
the Southbound Database it is interested in (e.g., Logical_Flow). This
effectively performs row level filtering for the SB DB tables such that
an ovn-controller would receive only updates about records that refer to
logical datapaths that are local to the chassis.
However, in an ovn-kubernetes cluster, all node logical switches are
connected to the ovn-cluster-router which forces all ovn-controllers to
register for updates about all logical switches.
The conditional monitoring implementation in OVSDB turns out to not
scale so well in such scenarios.
OVN 20.03 supports a new configuration knob (ovn-monitor-all=true) which
instructs ovn-controllers to not use row level filtering of records.
This was introduced by: …
> cluster.go: Disable Southbound DB conditional monitoring.

- README_MANUAL.md
- go-controller/pkg/config/utils.go
- go-controller/pkg/config/utils_test.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/util_test.go
I had a problem in an IPv6 cluster where certain traffic was getting
dropped.  A closer look revealed that duplicate MACs had been
configured in the OVN virtual network topology.  In particular, the
join bridge between the gateway router and distributed cluster router
had the same MAC on both of its ports.
The root cause was this function.  It assumed IPv4.
While working on a fix for this and writing test cases, I discovered
that the function would sometimes also break for IPv4.  It assumed
that the IPv4 address was always in 4-byte form.  Sometimes the IP
type actually has 16 bytes, even when holding an IPv4 address.  The
first fix is to ensure that we're always using the 4-byte
representation when working with the IPv4 address.
The second fix is to make this function aware of IPv6.  We …
> ipv6: Make IPAddrToHWAddr() aware of IPv6

- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- go-controller/cmd/ovn-kube-util/app/readiness-probe.go
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
- go-controller/pkg/util/ovs.go
this PR adds readiness probes for OVN NB/SB, ovn-controller,
ovn-northd, ovs-vswitchd, and ovsdb-server
> add readiness probes for OVN/OVS daemons

- dist/images/Dockerfile.fedora
Includes fixes to regressions that were causing CI to fail before
downgrade.
> Pull new OVN rpm for Fedora

- README_MANUAL.md
- go-controller/pkg/config/utils.go
- go-controller/pkg/config/utils_test.go
This is a follow up after some discussion on PR #1091.  Even with this
limitation in place, we will still end up with some duplicate MACs in
a system.  The duplicates won't be on the same logical switch though,
so it's not harmful.  The cluster subnet doesn't change this
situation.
> Drop IPv6 cluster subnet limitation

- go-controller/pkg/cni/helper_linux.go
ovs 2.12 [1] with hardware offload support ingress ratelimiting therefore
LinkSetVfTxRate is not needed. The patch remove the duplicate configuration
for SR-IOV VF. This kernel patch [2] add the support the mellanox driver.
Closes: #1066
[1] - https://github.com/openvswitch/ovs/commit/e7f6ba220e10c0b560da097185514b6e33e2dc71
[2] - https://www.spinics.net/lists/netdev/msg589937.html
> remove LinkSetVfTxRate from setupSriovInterface

- go-controller/pkg/config/config.go
The klog PR https://github.com/ovn-org/ovn-kubernetes/pull/1047 lacked proper klog flag definitions when writing to a log file. 
This PR adds those. 
I also removed the line `klog.SetOutput(os.Stderr)` because it's not actually needed. Klog writes to `os.Stderr` by default. 
Sorry for any trouble, @girishmg 
/cc @dcbw
> Fix: adding klog specific flags when logging to file

- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
-- added nodeAffinity and podAntiAffinity fields to onvkube-master.yaml to enable multi-master case
-- added terminationMessagePolicy to FallbackToLogsOnError for all the containers
-- removed duplicated readinessProbe for ovs-daemons container
-- removed commented out liveness probe spec in various containers
-- removed unused lifecycle field in various container spec
-- removed fake `healthz` named ports from various containers that was not being used
@dcbw PTAL
> Several fixes to our yaml template files

- .github/workflow-templates/test.yml
- .github/workflows/test_generated.yml
This is now fixed in OVN by:
https://github.com/ovn-org/ovn/commit/1be8ac65bc60c961c542a52f66b29cdad06917ea
> Enable E2E hairpin test for Services

- go-controller/pkg/ovn/ha_master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
- go-controller/pkg/ovn/policy_old_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/ovn/port_cache.go
- go-controller/pkg/testing/testing.go
Instead of having separate UUID and logical switch caches, consolidate them into one cache. We'll also use this later to store pod labels for network policy matching.
@danwinship @girishmg
> Unified port cache

- go-controller/pkg/node/startup-waiter.go
we have two ready functions that check for management port and gateway
readiness. if both of them timeout, then they try to write to an
unbuffered `errors` channel. one of the function will succeed while
the other function gets blocked in
w.errors <- err
the main goroutine gets blocked waiting for both the ready functions to
complete, however one of them cannot complete as it is blocked.
@dcbw PTAL
> deadlock in ovnkube node while waiting on ready functions to complete

- .github/workflow-templates/test.yml
- .github/workflows/test_generated.yml
See https://github.com/actions/checkout/issues/23
We'll often get errors in CI build job reruns like:
```
Resolving deltas: 100% (14917/14917), done.
From https://github.com/ovn-org/ovn-kubernetes
* [new branch]      35d4a96e508311d5f0adda -> origin/35d4a96e508311d5f0adda
* [new branch]      bindings               -> origin/bindings
* [new branch]      branch-0.5             -> origin/branch-0.5
* [new branch]      dcbw-patch-1           -> origin/dcbw-patch-1
* [new branch]      master                 -> origin/master
* [new branch]      rajatchopra-patch-1    -> origin/rajatchopra-patch-1
* [new branch]      revert-440-master-build-ubuntu-docker-image -> origin/revert-440-master-build-ubuntu-docker-image
* [new branch]      revert-890-fix-lint    -> origin/revert-890-fix-lint
* [new …
```
> ci: use checkout@v2 to work around v1 issues on job reruns

- dist/templates/ovnkube-db-raft.yaml.j2
- go-controller/cmd/ovn-kube-util/app/readiness-probe.go
- go-controller/pkg/util/ovs.go
ovsdb-server 2.9 or later introduced a database called _Server. this
database exists in every instance of ovsdb-server process. this database
has a table called Database and the rows in that table captures the
status and configuration of every database ovsdb-server handles
(including _Server database)
for example, in the case of NB ovsdb-server there will be two databases
OVN_Northbound and _Server. the _Server`Database table will have two
rows. one of the columns in the row is called Connected and it is of
boolean type and for cluster database it reprsents whether the server
is in contact with a majority of its cluster.
checking on `connected` to be true is a good readiness probe for both
NB and SB container.
@dcbw @numansiddique @alexanderConstantinescu PTAL
> readiness-probe for OVN NB and SB Raft ovsdb-server

- dist/images/Dockerfile.fedora
2.12.1-1 is now in stable fedora.
> Remove f31 advisory repo

- go-controller/pkg/util/ovs.go
even though the column is defined as `integer` as you can see below
$ ovsdb-client list-columns unix:/var/run/openvswitch/ovnnb_db.sock \
_Server Database |grep index
index     {"key":"integer","min":0}
there are instances where it is returned as [set []] and unmarshalling
fails. remove index for now since we don't need it.
> remove retrieving Index from the _Server database for now

- dist/images/ovndb-raft-functions
because of this silly mistake when the ovnkube-db statefulset is restarted
it was trying to write to the DB  (ovn-nbctl set-connection) without
any quorum and the commands were getting hung.
> the ovn db file is ovn{nb|sb}_db.db and not ovn{nb|sb}.db

- go-controller/cmd/ovn-kube-util/app/readiness-probe.go
- go-controller/pkg/util/ovs.go
the `index` column holds ["set": []] when it is not populated yet and
holds `integer` when it is populated, so we need to use `interface{}`
data type for the structure field that holds its value.
@dcbw @danwinship @trozet PTAL
> handle correct parsing of _Server`Database's index column

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/config/config.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
in preparation for bringing in various prometheus metrics under
following namespaces
- ovnkube_master_
- ovnkube_node_
- ovn_db_
- ovn_db_raft_
- ovn_northd_
- ovn_contorller_
move all the existing metrics and the function behind them under
`metric` package. right now, they are all in various files across
various packages.
@dcbw @danwinship @squeed @trozet PTAL
> group all prometheus metrics and functions under metric package

- dist/images/ovndb-raft-functions
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
add new subcommand to ovn-kube-util called ovn-db-exporter that exports
metrics as relates to OVN DB (clustered db in this commit). since we
cannot instrument the ovsdb-server daemon directly, we are going to
use ovn-kube-util running as a daemon handling http requests on port
'9476' for '/metrics' path.
the ovn-db-exporter is currently running as a 3rd container in the
ovnkube-db pod and exports the following metrics with labels
(OVN_Northbound and OVN_Southbound)
ovn_db_raft_cluster_leader
- a gauge vector metric type that captures whether the current instance
is a leader or not.
ovn_db_raft_jsonrpc_server_sessions
- a gauge vector metric type that captures the number of jsonrpc server
sessions that are currently active on the server.
ovn_db_raft_ovsdb_monitors
- a gauge vector metric …
> add cluster db related metrics using ovn-kube-util as an exporter

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/util/ovs.go
- add metric to record the time taken for the onvkube daemons to come up
added ovnkube_master_ready_duration_seconds and
ovnkube_node_ready_duration_seconds. this is information type metric
since its value doesn't change once the daemons are up and running. we
have found this to be very helpful while bringing up large clusters
to figure out how adding more nodes ot k8s cluster impacts ovn control
plane
- add metric to count number of times we have skipped using nbctl daemon
> add more metrics for ovnkube-master and ovnkube-node daemons

- dist/images/ovndb-raft-functions
- dist/images/ovnkube.sh
Wasted good two hours debugging this. With this check we exit early instead of continuing and ovsdb-server interpreting the empty host ip address incorrectly and screwing up the cluster.
@dcbw PTAL
> exit early from script upon failure to determine ip address of the host

- go-controller/pkg/node/gateway_shared_intf.go
> nodePortWatcher for the shared-gateway mode doesn't handle service update

- go-controller/pkg/config/config.go
- go-controller/pkg/node/node.go
we are not restoring the correct log level after we initially setup
the ovnkube-node daemon to print debug messages at startup time
@dcbw @danwinship   @alexanderConstantinescu PTAL
> ovnkube-node daemon is not logging messages at level=5

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/ovn/ha_master.go
- go-controller/pkg/util/ovs.go
1. added ovnkube_node_integration_bridge_openflow_total metric that exports the number of
OpenFlow flows in the integration bridge
2. added ovnkube_master_ovn_cli_latency_seconds metric that exporst the latency of various OVN commands that runs on the master. Right now, only exports ovn-nbctl and ovn-sbctl calls
3.  miscellaneous fixes to ovnkube-master daemon's duration to ready state metric
- export duration metric in seconds instead of nanoseconds
- measure the duration to ready state in the ha_master.go where we
setup various logical topology on the master and then start watchers.
@danwinship @dcbw @squeed PTAL
> added more metrics and moved the metric collection for ovnkube-master

- go-controller/pkg/util/net.go
`util.GenerateMac` generates pseudo-random MAC addresses but without setting the bit indicating that they are locally-generated rather than being from a formally-assigned block. Fortunately, no one was using it anyway.
@dcbw
> util: remove an unused and erroneous function

- go-controller/hack/lint.sh
We're seeing more CI flakes due to golangci-lint timeouts so bump that for now. For example:
https://pipelines.actions.githubusercontent.com/rx2q6cyVnb1KdY24EzqfkXItIKb3SzT55t8LHdEU6zlqA0chrw/_apis/pipelines/1/runs/410/signedlogcontent/5?urlExpires=2020-03-18T15%3A26%3A18.9706764Z&urlSigningMethod=HMACV1&urlSignature=dVoodq7JRIPc7Y%2BtCoUj%2F44lyyUYkACo0inyIEN89E0%3D
```
+ make install.tools
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b /home/runner/go/bin
golangci/golangci-lint info checking GitHub for latest tag
golangci/golangci-lint info found version: 1.24.0 for v1.24.0/linux/amd64
golangci/golangci-lint info installed /home/runner/go/bin/golangci-lint
+ make lint
level=error msg="Timeout exceeded: try increasing it by passing --timeout …
```
> build: increase lint timeout

- dist/images/Dockerfile.fedora.dev
- dist/images/Makefile
from OVN/OVS master branch.
This Dockerfile builds image that will contain the
OVN-Kubernetes, OVN & OVS binariers built from the
master branch of their respective projects.
User can hack this dockerfile, and change the branch name
to build binary out of any other existing branch of the
projects, as far as OVN and OVS binaries are compatible
to work with each other.
> Added Dockerfile to build OVN-Kubernetes dev image

- dist/templates/ovnkube-db-raft.yaml.j2
> fix the label prefix for ovnkube-db-raft - s/ovn.org/k8s.ovn.org/

- .github/workflow-templates/test.yml.erb
- .github/workflows/test_generated.yml
Cluster name is 'ovn', not 'kind-ovn'. Fixes issues like:
```
2020/03/18 03:57:44 kind.go:377: kind.go:DumpClusterLogs()
2020/03/18 03:57:44 process.go:153: Running: kind export logs /home/runner/go/src/k8s.io/kubernetes/_artifacts --loglevel=debug --name=kind-ovn
time="03:57:44" level=debug msg="Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\\t{{.Label \"io.k8s.sigs.kind.cluster\"}}]"
Error: unknown cluster "kind-ovn"
```
@trozet @as-com
> ci: fix kind cluster name

- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/util/net_linux.go
Instead of passing the address family to LinkNeighAdd() just have
it autodetect the family from the neighor's IP address.
Fixes: 2bfa79bf61d116dee276a0544690c448c2230769
@girishmg @danwinship
> node: fix management port IPv6 neighbor addition

- go-controller/pkg/config/config.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/config/utils_test.go
- go-controller/pkg/ovn/master.go
ovn-kubernetes internally uses 100.64.0.0/16 (for IPv4) and fd98::/64
(for IPv6) for the join network. we need to ensure that the
cluster/service CIDRs don't overlap with these
Fixes #1132
> validate cluster/service CIDRs against reserved IPs

- go-controller/pkg/ovn/master.go
Caused by merging https://github.com/ovn-org/ovn-kubernetes/pull/1154 after https://github.com/ovn-org/ovn-kubernetes/pull/1096 without a rebase.
> ovn: fix up master build failure after merge

- dist/images/ovnkube.sh
with
-klog set to alsologtostderr=true and
-ovnkube.sh also doing `tailf -f /var/log/ovn-kubernetes/<logfile>`
the pod's logfiles were having duplicate log messages
> duplicate log entries in ovnkube daemon's pod logfiles

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/hack/build-go.sh
- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/metrics/ovn.go
1.  ovn_build_info metric captures OVN version and OVS Library version
against which the OVN was build in the constant labels part of the
metric. The metric itself returns a constant value of 1.
2.  ovn_db_raft_build_info metric captures OVN DB version, the Northbound DB
schema and the Southbound DB schema version in the constant labels part
of the metric. The metric itself returns a constant value of 1
3.  ovnkube_master_build_info and ovnkube_node_build_info metrics capture
the commit, branch, build date, and build user information in the
constant labels part of the metric. The metric itself returns a constant
value of 1
> add build_info metric for ovn, OVN DB schema, and ovn-k8s artifacts

- go-controller/hack/test-go.sh
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_windows_test.go
- go-controller/pkg/node/node_test.go
- go-controller/pkg/ovn/endpoints_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_old_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/ovn/service_test.go
- go-controller/pkg/util/util_test.go
In #1071 I tried to fix it so that `make test` didn't depend on `KUBECONFIG` in the environment, but only actually fixed it for `pkg/config/`, not the rest of the tree. This fixes it everywhere.
Also, in #744 I fixed it to not run "go test" in directories with no tests but then in #925 Casey accidentally reverted that. This unreverts it.
> Minor test case fixups

- go-controller/pkg/ovn/allocator/allocator.go
- go-controller/pkg/ovn/allocator/allocator_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/util/gateway-init.go
extends SubnetAllocator to support dual-stack, and updates `pkg/ovn/master.go` for the API change, but doesn't actually make the master handle dual-stack allocations yet
SubnetAllocator has 4 operations (`AddNetworkRange`, `MarkAllocatedNetwork`, `AllocateNetwork`, and `ReleaseNetwork`) but only "allocate" needs to change API to support dual-stack. The new behavior is that if you pass both at least one IPv4 range and at least one IPv6 range to `AddNetworkRange`, then the allocator will be dual-stack, and each allocation will return both an IPv4 subnet and an IPv6 subnet. `AllocateNetwork` becomes `AllocateNetworks` returning an array of either 1 or 2 subnets; in future PRs we'll update the master to handle both networks in the dual-stack case.
@dcbw
> Dual subnet allocation for dual-stack

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
This pull request is to delete the chassis record from the sbdb during sync when the nodes get deleted from the ovnkube-master's perspective.
Signed-off by: Aniket Bhat <anbhat@redhat.com>
> sync: Delete the chassis records during deleteNode from sbdb

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
in the upgrade path, with the rename br-nexthop to ovn-k8s-gw0 changes,
the br-local OVS bridge will have two internal ports -- the old and the
new. both of these ports claim the same logical_port through iface-id
on the chassis and it causes confusion and connectivity issues
> remove legacy br-nexthop internal port, if it exists, before proceeding

- README.md
- dist/images/Makefile
- dist/images/daemonset.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
This patch fixes the following
*.* Removes the hardcoded log levels for ovnkube and ovn.
*.* Exposes logging parametes for ovn (northd, nb db, sb db,
ovn-controller, nbctl) for user to override before generating
deployment yamls.
*.* Updates yaml templates to inject the logging parameters
*.* Updates Dockerfile.fedora.dev file for user's reference
about how to consume these parameters
*.* Adds note in README as well.
> Fixed logging related parameters.

- dist/images/ovnkube.sh
OVN_LOG_NBCTLD env var was not used in ovnkube-master deployment,
so interally in ovnkube.sh it was not mapping to anything, and hence
it was setting to right log file name. Once we injected this env var
through patch (35f27054) it was mapped to log-file and not log-level
and configured --log-file incorrectly.
> Fix nbctld log-file

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_windows.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/node.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/subnet_annotations.go
To support dual stack (#1142) we will need to modify the node-related annotations, as currently neither the `node-subnets`/`node-join-subnets` annotations nor the `l3-gateway-config` annotation supports listing dual-stack IPs/subnets.
As a prelude to that, this abstracts the handling of those annotations into helper utilities in `pkg/util/`. Then to add support for dual-stack we can just change the helper functions/types to use arrays of IPs/CIDRs rather than individual IPs/CIDRs, and the helper functions can then continue to create/parse backward-compatible annotations in single-stack clusters, but use an updated annotation format in dual-stack clusters, and the callers don't need to care.
(The updates to the unit tests got a bit ugly... maybe that should be done differently...)
@dcbw
> Abstract node annotation handling

- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
Deny ACLs for PolicyTypeEgress policies should be applied in direction
"from-lport". Also, make the "find ACL" ovn-nbctl calls more specific by
matching on direction and priority too.
Fixes #1174.
> ovn: Fix default deny ACLs.

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
added following metrics:
ovn_db_raft_cluster_id
ovn_db_raft_cluster_server_id
ovn_db_raft_cluster_server_role
ovn_db_raft_cluster_server_status
ovn_db_raft_cluster_server_vote
ovn_db_raft_cluster_election_timer
ovn_db_raft_cluster_term
ovn_db_raft_cluster_log_index_next
ovn_db_raft_cluster_log_index_start
ovn_db_raft_cluster_log_not_applied
ovn_db_raft_cluster_log_not_committed
ovn_db_raft_cluster_inbound_connections_total
ovn_db_raft_cluster_inbound_connections_error
ovn_db_raft_cluster_outbound_connection_total
ovn_db_raft_cluster_outbound_connection_error
> export ovs-appctl cluster/status output as ovn_db_raft_cluster metrics

- dist/images/Dockerfile
- dist/images/Dockerfile.fedora
- dist/images/Dockerfile.fedora.dev
- dist/images/Dockerfile.ubuntu
- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
From the manpage of `ovsdb-client wait`, we have:
wait [server] database state
Waits for database on server to enter a desired state, which may
be one of:
connected
Waits until a database with the given name has been added
to server.  Then, if database is clustered,  additionally
waits until it has joined and connected to its cluster.
So, instead of checking `pid` associated with the process is present.
The above command looks more appropriate.
> use 'ovsdb-client wait' to check running state of OVN DB servers

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_windows.go
- go-controller/pkg/node/node.go
- go-controller/pkg/node/startup-waiter.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/util/util.go
Note: the logical port name is still going to be k8s-<hostname>, just
that the physical port on every k8s node is going to be ovn-k8s-mp0
see: https://groups.google.com/forum/#!topic/ovn-kubernetes/Q9E5FMXC2GM
@danwinship @dcbw PTAL
> rename k8s-<hostname> management OVS internal port to ovn-k8s-mp0

- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/util/net_linux.go
Link{Addr|Route}Add API was deleting the existing entries and adding
the new entries. During the review it was suggested to split this into
two functions. This commit takes care of it.
It also adds two new APIs Link{Route|Neigh}Exists that will be used
by health check routines in future.
@dcbw PTAL
> refactor Link{Addr|Route}Add API and add Link{Route|Neigh}Exists API

- go-controller/hack/lint.sh
We've had this downstream in OpenShift ovn-kubernetes for a while.
@girishmg
> build: bump lint timeout to 10 mintues

- dist/images/ovndb-raft-functions.sh
while cherry picking the changes from my internal repo to upstream repo
I missed adding the database variable
Fixes: 5e98a62ab047 (use 'ovsdb-client wait' to check the running state
of OVN DB servers)
> define the missing database variable

- go-controller/pkg/cni/cni_suite_test.go
- go-controller/pkg/cni/ovs.go
- go-controller/pkg/cni/ovs_test.go
Completely pointless to return empty values; solves issues like:
time="2019-11-05T10:57:08Z" level=warning msg="failed to clear stale OVS port \"\" iface-id \"e2e-security-context-5442_security-context-2396b1d4-d30b-4259-b2c5-572620d035fd\": failed to run 'ovs-vsctl --timeout=30 remove Interface  external-ids iface-id': exit status 1\n  \"ovs-vsctl: no row \\\"\\\" in table Interface\\n\"\n  \"\""
@girishmg @danwinship @squeed @JacobTanenbaum @alexanderConstantinescu
> cni: don't return empty values from ovsFind()

- go-controller/pkg/util/ovs.go
from OVS FAQ, we have:
All current versions of ovs-ofctl enable only OpenFlow 1.0 by default.
Use the -O option to enable support for later versions of OpenFlow in
ovs-ofctl.
without the -O option the replace-flows command doesn't work
@dcbw any reason why you removed this in your `hybrid-overlay series`?
> add back -O OpenFlow option to replace-flows

- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
Added following changes:
- add support to configure election timer for the clustered DB
we have found that the default value of 1s is not sufficient at scale
and therefore we need a way to modify this value at deploy time
- configure probe interval for {NB|SB} db connections from ovn-northd
- set passive connection and disable inactivity probe for raft reliably
today, if we failed to set passive connection, then we don't re-try
again on the pod restart since it is wrapped under `initialize=true`.
so, we need to re-try on restart if it not set to begin with.
- add support to modify the default TCP ports for RAFT control traffic
> Raft orchestration configuration settings

- go-controller/pkg/cni/cni.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/ovn/allocator/allocator.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/net_linux.go
- go-controller/vendor/k8s.io/utils/net/ipnet.go
- go-controller/vendor/k8s.io/utils/net/net.go
- go-controller/vendor/modules.txt
In a dual-stack world, code needs to decide whether to do IPv4-ish stuff or IPv6-ish stuff based on what sort of addresses it's actually working with, not based on a global switch. So this mostly moves us to that. (There are a few remaining uses of `config.IPv6Mode` which will be dealt with later.)
As part of this, I also switched some code to use `IsIPv6()/IsIPv6String()/IsIPv6CIDR()/IsIPv6CIDRString()` from `k8s.io/utils/net` rather than confusingly fiddling with `ip.To4() == nil` / `!= nil`, etc.
oh, also, the localnet code was previously adding an iptables rule
-t nat -A POSTROUTING -s 169.254.33.2/24 -j MASQUERADE
which is technically invalid; the address should be either `169.254.33.2/32` or `169.254.33.0/24`. iptables interprets it as the latter, but I'm pretty sure we meant the …
> use utilnet.IsIPv6(), drop most uses of config.IPv6Mode

- .github/workflow-templates/test.yml.erb
- .github/workflows/test_generated.yml
This PR removes unnecessary packages (totaling about 10 GB) from the CI environment so we don't run out of disk space during testing and also removes an instance of an unnecessary file copy.
> Free up disk space in CI environment setup

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cniserver_test.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/node/node.go
When profiling the ovnkube-node, the clientset creation showed up as a
bottleneck for cni commands. This PR changes the cmdAdd implementation
to use the clientset passed in from the node process via the server to
the pod request.
Signed-off By: Aniket Bhat <anbhat@redhat.com>
> Node: Optimize CNI to reuse clientset created by ovnkube-node

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/healthcheck.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_windows.go
- go-controller/pkg/node/management-port_windows_test.go
- go-controller/pkg/node/node.go
- go-controller/pkg/util/net_linux.go
Health checks are implemented as go routines and they periodically
checks for
- management port health
- ensure that route entries for cluster CIDR and service CIDR exists
through management port
- ensures that there is MAC/IP arp entry for the node subnet router
IP and its MAC
- iptable SNAT entries exists on the host
- check for any stale OVS Internal ports on br-int
@dcbw PTAL and this PR depends on PR #1183
> add various health checks to ensure proper functioning of ovnkube-node

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/config/utils_test.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_windows.go
- go-controller/pkg/ovn/pods.go
This builds on #1185; the last two commits ("`config: abstract CIDR-overlap-checking`" and "`config: allow multiple service CIDRs`") are new. You can review the PRs separately or review it all here...
The effects of the new commits are:
- `--k8s-service-cidr` and the `service-cidr` config file option are now deprecated in favor of `--k8s-service-cidrs` / `service-cidrs`, which allow a comma-separated list of CIDRs. This is similar to what kube-apiserver does now, and like kube-apiserver we currently require that the "list" is either a single element, or else an IPv4/IPv6 pair (while holding open the possibility that we might allow arbitrary multiple service CIDRs in the future).
- We validate that cluster-subnets and service-cidrs are valid together (ie, both single-stack ipv4, both …
> fix up config for dual-stack, add dual-stack service CIDRs

- .github/workflow-templates/test.yml.erb
- .github/workflows/test_generated.yml
- contrib/kind-ha.yaml
- contrib/kind.sh
This patch adds secondary jobs to execute E2E tests against an HA
cluster using RAFT. 3 nodes are provisioned (to keep resource usage
down) that will act as masters and workers.
> Adds HA deployment option to KIND

- .github/workflow-templates/test.yml.erb
- .github/workflows/test_generated.yml
Logs are named after JOB_NAME so without this distinction logs for
noha/ha were overwriting each other.
> Fix JOB_NAME to include ha/noha

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/healthcheck.go
in the shared gateway mode, we share the host's k8s node ip for SNATing.
we add default set of 'five' flows to steer the nodeport traffic into
the OVN logical topology and to also connection track the l3 gateway
north-south traffic
these flows are very critical and if they are missing for whatever
reason, then that node is not functional. so, we need to add check for
it and take corrective action (for now just kill the ovnkube daemon
so that it restarts with right flows).
@dcbw PTAL
(Note: this commit is based of PR  #1184)
> identify default flows with 0xdeffl05 cookie and add healthcheck for it

- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/ovs_test.go
ovn-nbctl daemon mode by default puts its pidfile and socket
into /var/run/openvswitch which is likely an oversight in the
OVS/OVN split work debuting in OVN 2.12. The code was not looking
in /var/run/openvswitch if ovn-appctl was present, which was supposed
to be the magic way of figuring out whether to use /var/run/openvswitch
or /var/run/ovn.
Instead, first look for an existing OVN_NB_DAEMON environment variable,
which may have been set already per 'man ovn-nbctl' daemon mode
documentation, and return that verbatim to ensure the child ovn-nbctl
process uses it.
Otherwise, look for the pidfile and corresponding socket in both
directories (ovn first, then openvswitch) and pick the first one
that has both.
@trozet @girishmg
> util: fix handling of ovn-nbctl daemon mode paths

- go-controller/hack/lint.sh
- Use verbose print resource usage
- Use vendor folder to avoid having to download deps
Closes #1222
> Fix golang linter timeouts

- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_windows.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/helper_linux.go
- go-controller/pkg/node/helper_windows.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_windows.go
- go-controller/pkg/node/node.go
- go-controller/pkg/ovn/allocator/allocator.go
- go-controller/pkg/ovn/allocator/allocator_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/subnet_annotations.go
- go-controller/pkg/util/util_test.go
In the course of updating a lot of functions that take or return an IP/CIDR to make them able to take/return two IPs/CIDRs for dual stack, I noticed that there are lots of places where we have a `net.IP` or `*net.IPNet`, then convert it to a string to pass to another function, and then that other function immediately reparses it back to struct form (with an error check since it doesn't actually know for sure that the string is valid). Or, we read a value, parse it to make sure it's valid, throw away the parsed form and return the string form to the caller, and then the caller parses it again.
The parsed forms seem to me to be superior to the unparsed ones, since given a `net.IP` or `*net.IPNet`, you are guaranteed to be able to convert it to a valid string without problems, but given a …
> pass MACs, IPs, CIDRs around in parsed form rather than as strings

- test/e2e/e2e_test.go
- test/e2e/go.mod
This PR adds a new e2e test that ensures Internet connectivity is maintained if the ovnkube-master pod is killed. I also fixed the existing ovnkube-node test to handle multiple nodes now that it's a thing in the KIND test suite.
> Add e2e test that kills ovnkube-master; fix ovnkube-node test for multiple nodes

- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
In Ovnkube.sh, currently Node IP's are obtained using DNS.
Instead, Pod spec (status.HOST IP) is used to obtain the Node IP's.
Signed-off-by: Pardhakeswar <ppacha@nvidia.com>
> Obtaining Node IP's from status.Host IP instead of using DNS

- dist/images/ovnkube.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
Currently, ovn_log_northd variable is capturing the loglevel which should capture
the log location. Renaming ovn_log_northd -> ovn_loglevel_northd and similar renaming
is used for other variable names (ovn_log_nb, ovn_log_sb, ovn_log_controller).
Similarly in the YAML files, OVN_LOG_NB and other log level variables(OVN_LOG_SB, OVN_LOG_NBCTLD)
is used for for capturing the loglevel. Renaming them to OVN_LOGLEVEL_NB and others to similar nomenclature.
> Renaming loglevel capture variable names in ovnkube.sh & yaml files

- test/scripts/install-kind.sh
See: https://github.com/ovn-org/ovn-kubernetes/pull/1207#discussion_r404190276
Signed-off-by: Andrew Sun <asun@redhat.com>
> Download kind in CI instead of go getting it

- dist/images/daemonset.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
Run using:
OVN_HYBRID_OVERLAY_ENABLE=true
OVN_HYBRID_OVERLAY_NET_CIDR=<overlay_prefix>
pushd contrib/; ./kind.sh
> Add hybrid-sdn support to KIND

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_windows.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_test.go
- go-controller/pkg/util/util.go
OK, starting to think about dual-stack
The first thing in the source tree alphabetically that needs to be updated is the cniserver/cnishim communication, which currently inlines the pod annotation data.
The pod annotation currently only allows for a single IP per network:
k8s.ovn.org/pod-networks: |
{
"default": {
"ip_address": "192.168.0.5/24",
"mac_address": "0a:58:fd:98:00:01",
"gateway_ip": "192.168.0.1"
}
}
----
EDIT: current version of the patch continues using the above format for single-stack clusters, and replaces `ip_address` and `gateway_ip` with `ip_addresses` and `gateway_ips` arrays only in dual-stack clusters.
original proposal continues below...
----
So options for extending that to dual-stack include:
1. deprecate the existing annotation, add a new one
2. deprecate the …
> update pod annotation and CNI shim communication for dual-stack

- .github/workflows/test.yml
- test/Makefile
- test/scripts/e2e-kind.sh
Instead of "End-To-End Tests (e2e-k..." in the Github show more
of the relevant bits eg "e2e (shard-n,...". Since all the tests
use KIND, and all the tests use OVN, "kind-ovn-" seems less
relevant too.
@as-com @dave-tucker @trozet
> ci: shorter GitHub action job names

- .github/workflows/test.yml
This PR allows the CI test suite to run on branches that aren't master.
Signed-off-by: Andrew Sun <asun@redhat.com>
> Also run CI on non-master branches

- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
error messages in GatewayInit() and GatewayCleanup() functions doesn't
have the gatewayRouter name that makes it diffuclt to know
for which k8s node the functionality has failed.
> Adding gatewayRouter name in error messages.

- README_MANUAL.md
- dist/READMEcontainer.md
- dist/images/ovndb-vip.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- docs/INSTALL.SSL.md
- docs/INSTALL.UBUNTU.md
- docs/debugging.md
- docs/ha.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/ovn/master_test.go
I started this a long time ago when I first started looking at ovn-kubernetes, but wasn't sure what to do about the variable names referencing minions in the vagrant and ansible stuff because I didn't want to break anything but I didn't want to bother testing them either. But now all of those are gone, so all that's left to fix is docs and comments.
> Fix references to "minions" and "master nodes"

- dist/images/daemonset.sh
- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
-- assumes that all the required private keys and corresponding signed
certificates are mounted into the container at /ovn-cert path
-- the private keys and certificates for various OVN components are
named as below
ovncontroller-cert.pem
ovncontroller-privkey.pem
ovnnb-cert.pem
ovnnb-privkey.pem
ovnnorthd-cert.pem
ovnnorthd-privkey.pem
ovnsb-cert.pem
ovnsb-privkey.pem
-- the name of the CA certificate that signed the CSRs is ca-cert.pem
-- disabled by default since there are lot of pre-requisites to get this
thing to work. to enable it, one needs to set the OVN_SSL_ENABLE
environment variable in each of the container
@dcbw @danwinship @trozet @squeed PTAL
> SSL for OVN daemonsets

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/service.go
This is mostly a no-op at this point, but this updates the loadbalancer support to allow passing multiple source IPs, and then it maps all the IPv4 source IPs to all the IPv4 target IPs, and all the IPv6 source IPs to all the IPv6 target IPs.
This PR renames `ovn.getGatewayPhysicalIP` to `ovn.getGatewayPhysicalIPs` and makes it return an array, but at the moment it still only ever returns a single IP. But when it does start returning multiple IPs, the NodePort code will now do the right thing with it (using either or both of the IPv4 and IPv6 node IPs, depending on what endpoint IPs it has available).
(The first commit also does some renaming to IMHO make things clearer. YMMV?)
@dcbw @girishmg 
@trozet since you were just in this code...
> initial dual-stack loadbalancer support

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/testing/parse.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/node_annotations_test.go
- go-controller/pkg/util/pod_annotation_test.go
This adds dual-stack support to the setting and parsing of the l3-gateway-config annotation (but not rippling much beyond that).
Similarly to the pod annotation, I've added new array-valued `ip-addresses` and `next-hops` to replace `ip-address` and `next-hop`, and we set both fields in single-stack clusters but only the new fields in dual-stack clusters; eventually we can migrate to only setting the new fields everywhere.
`node_annotations.go` gets mostly rewritten but the new unit test shows that it's a no-op except where expected.
This also updates one of our external-ids in ovn similarly.
@dcbw
> dual-stack support for l3-gateway-config annotation

- dist/images/daemonset.sh
Currently, sed command is used to generate the ovn-setup.yaml
from ovn-setup.yaml.j2. Instead, j2 tool is used to generate the yaml
file for ovn-setup.yaml.
> daemonset.sh: Using j2 tool to generate ovn-setup.yaml file.

- .github/workflows/test.yml
- contrib/kind.sh
- test/scripts/e2e-cp.sh
- test/scripts/e2e-kind.sh
- test/scripts/install-kind.sh
Put the test name earlier since the GitHub Actions UI only shows
the first 24 characters or so.
Don't use kubetest; don't think we need it since we just use kind.
Retry kubectl commands a couple times when things fail.
@as-com @trozet @dave-tucker
> ci: various cleanups and stop using kubetest

- go-controller/pkg/ovn/master.go
Fixes: 3677530d63fe (ovn: remove gratuitous string/IPNet conversions
around subnet allocation)
@danwinship FYI
> regression: fix nil-pointer reference panic in defer function

- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_windows.go
- go-controller/pkg/node/node.go
If we have multiple hostsubnets, create a dual-stack management port. We don't actually have multiple hostsubnets yet but this at least extends the unit test to exercise the new code.
> dual stack management port creation

- test/e2e/e2e_test.go
I'm noticing some unexpected behavior in the e2e tests that are probably caused by an earlier removal of the delay between creating the pod and doing the rest of the test. Turns out "not pending" might not necessarily mean "running" or "ready."
Signed-off-by: Andrew Sun <asun@redhat.com>
> Wait for pod to start running before deleting things in e2e tests

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/policy.go
I'm not sure if this actually fixes any locking problems, but it at least makes things clearer (and paves the way for storing additional per-namespace info in dual-stack clusters).
The new `FIXME` and `klog.Errorf` in `addNetworkPolicy` are not new problems, they're just problems that were silently ignored before.
@dcbw @girishmg @trozet
> ovn: improve Namespace/NetworkPolicy locking

- dist/templates/ovn-setup.yaml.j2
- go-controller/pkg/config/config.go
the podsecuritypolicy is a cluster-level resource and we were defining
it in ovn-setup.yaml. when PodSecurityPolicy admission controller was
enabled, all the non-ovn-k8s pods were getting tagged with this policy
and that definitely was not the intent when it was initially added
the workflow would be that the cluster-admin would define a policy for
the whole cluster and add 'use' verb for the polices definied for the
'ovn' service account. in short, it should come from the cluster
deployer and not from us
> remove OVN specific podsecuritypolicy resource

- .github/workflows/test.yml
There's a known issue with the GitHub Cache action that it doesn't
always work for pull request re-runs (especially triggered manually
from the Actions UI) for security reasons or something. If that
happens suck it up and rebuild Kube.
https://github.com/actions/cache/issues/208#issuecomment-596664572
https://github.com/actions/cache/issues/107#issuecomment-598188250
@trozet @as-com @dave-tucker
> ci: re-run Kube build if cache failed

- .github/workflows/test.yml
- contrib/kind.sh
When waiting for install to stabilize, the command will sometimes fail:
```
++ grep -v Running
++ kubectl get pod -A -o custom-columns=NAME:metadata.name,STATUS:.status.phase
+ '[' -z 'coredns-6955765f44-fw7lq                     Pending
All pods not available yet on attempt 1:
coredns-6955765f44-mg5pz                     Pending
local-path-provisioner-85445b74d4-vb48p      Pending' ']'
+ '[' 1 -gt 15 ']'
+ echo 'All pods not available yet on attempt 1:'
+ kubectl get pod -A
Error from server: etcdserver: leader changed
make: *** [install-kind] Error 1
make: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/test'
```
> Trivial fix for kind setup wait

- FAQ.md
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db.yaml.j2
instead of opening up the ports that are required for a functional ovn
k8s deployment from within the container's entrypoint script, make it
a requirement to an operator or deployer to open these ports
we have found instances that the current code doesn't work when the host
uses either firewalld (in the case of centos) or ufw (in the case of
ubuntu) or some other host-firewall mechanism.
> iptables: remove all the iptables logic to open up ports that we care

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
Sigh, had used incorrect command to to retrieve OVN_Northbound status.
> trivial: use correct sock for retrieving OVN_Northbound cluster/status

- go-controller/pkg/cni/ovs.go
- go-controller/pkg/cni/ovs_test.go
I am still seeing following error messages in /var/log/messages
Apr 19 16:08:27 sdn-test2 ovs-vsctl[30199]: ovs|00001|vsctl|INFO|Called
as /usr/bin/ovs-vsctl --timeout=30 remove Interface  external-ids
iface-id
Apr 19 16:08:27 sdn-test2 kubelet[35640]: W0419 16:08:27.912489
30181 helper_linux.go:252] failed to clear stale OVS port "" iface-id
"default_web-c22xr": failed to run 'ovs-vsctl --timeout=30 remove
Interface  external-ids iface-id': exit status 1
> fix ovsFind one last time

- go-controller/pkg/util/ovs.go
if we fail to use the ovn-nbctl daemon mode for whatever reason, then
we throw a warning message. if this warning message is missing, then
the command was executed using the ovn-nbctl in daemon mode. so, no need
to log the info that we are using ovn-nbctl daemon mode. this can be
inferred from missing warning message
> remove redundant log message that fills up the onvkube-master log file

- dist/images/Makefile
- dist/images/daemonset.sh
- dist/templates/ovnkube-db-raft.yaml.j2
Currently ovn-kubernetes support configuring election-timer for NB/SB raft cluster,
but it's not explictly exposed in the raft db deployment yaml. This patch
exposes those environment variables and updates daemonset.sh to
take these parameter at build time to generate the raft db yaml with
non-default values for election-timer.
> Expose election-timer for NB/SB raft cluster

- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types.go
this is the flow of handling CNIAdd/CNIDel requests from either kubelet
or multus
```
+--------+      CNIShim                                  CNIServer
|Kubelet/|   +-----------+  /var/run/ovn-kubernetes/  +--------------+
| Multus |   | ovn-k8s-  |   cni/ovn-cni-server.sock  | ovnkube-node |
| exec's |-->|cni-overlay|--------------------------->|  httpServer  |
+--------+   +-----------+          AF_UNIX           +--------------+
(a)            (b)               Socket                    (c)
```
If OVS daemons are running inside the container, then all the namespace
creattion, VETH creation, plugging the interface into the POD, and
creating and adding OVS internal port occurs in the container. This
requires the container to be `privileged`. Everything happens in (c)
In the other mode, …
> fix CNIRequestMetrics that tracks CNI requests (ADD, DEL) duration

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_test.go
Calls ovn-nbctl to add IPv6 addresses to the address_set table require quotes
around the IPv6 addresses.
> ovn-nbctl calls to table address_set need quotes for IPv6

- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_windows_test.go
It's not management port specific so it shouldn't be done there. Plus ovn-controller will create it for us, and we already wait for ovn-controller to create it.  Just let that happen.
@ovn-org/ovn-kubernetes-committers
> node: don't create br-int from management port code

- dist/images/Dockerfile.fedora
Specifically, let's start using the iptables wrapper scripts so we don't have as many problems running upstream "make fedora" images in OpenShift clusters.  Avoids:
```
F0423 16:14:01.771395  207236 ovnkube.go:104] Failed to add NAT rules for localnet gateway (failed to ensure filter/FORWARD: failed to list iptables chains: running [/usr/sbin/iptables -t filter -S --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-147.8.1.el8_1.x86_64
iptables v1.8.3 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
)
```
> dist: harmonize Fedora dockerfile with Ubuntu

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/templates/ovnkube-master.yaml.j2
Currently, the replica value in ovnkube-master.yaml.j2 file is hard-coded to one,
this PR ensures, that the acutal count of master node from kind-ha.yaml is passed
and that the correct value is reflected.
This PR resolves the issue https://github.com/ovn-org/ovn-kubernetes/issues/1265
> fix: removes the hardcoded master node count in ovnkube-master.yaml.j2 file

- .github/workflows/test.yml
Sometimes CI reports:
```
+ git clone --single-branch --branch v1.17.2 https://github.com/kubernetes/kubernetes.git /home/runner/go/src/k8s.io/kubernetes/
fatal: destination path '/home/runner/go/src/k8s.io/kubernetes' already exists and is not an empty directory.
```
We should only get to this step if the cache didn't restore the directory, so we can't really trust it's contents.
> ci: remove an existing $GOPATH/src/k8s.io/kubernetes/

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
Currently, the ovn-remote-probe-interval value is set to a constant value of
100s in the code. If it needs to be changed for varying cluster size and DB type,
needed to change code. So, making this value configurable through ovnkube-node.yaml.j2.
> Making ovn-remote-probe-interval value configurable from YAML file.

- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/util/node_annotations.go
After @Billy99 discovered that we were totally failing to set address_sets correctly on IPv6:
`ovnkube-master-wz8zz.txt:E0421 18:04:59.791761       1 common.go:69] failed to add an address "fd01::4:d802:fff:fe00:93" to address_set "a8947133929095949878", stderr: "ovn-nbctl: fd01::4:d802:fff:fe00:93: unexpected \":\" parsing set of 1 or more strings\n" (OVN command '/usr/bin/ovn-nbctl --timeout=15 add address_set a8947133929095949878 addresses fd01::4:d802:fff:fe00:93' failed: exit status 1)`
I decided to see if there were any other similar problems, and found one, with ACL names on IPv6:
`E0421 17:58:53.417985       1 loadbalancer.go:219] Error while querying ACLs by name: ovn-nbctl: f824f04e-dd70-486d-8f68-f2745fe0fc35-[fd02\:\:347d]\:3000: unexpected "[" parsing set of up to 1 strings` …
> fix an IPv6 problem, and some error messages

- go-controller/.golangci.yml
- go-controller/hack/lint.sh
This commit adds the .golangci.yml file that lists the linters enabled.
This allows for viewing enabled and disabled linters and also allow to add
more linters in the future. This PR addresses https://github.com/ovn-org/ovn-kubernetes/issues/1247
> feat: added the .golangci.yml file that lists the linters enabled

- test/e2e/e2e_test.go
- Creates a macvlan interface in the ovn kind deployment that acts
as an external gw for reachability testing.
- This test is associated with the feature added in #1209 but will 
still succeed without that being merged since the external 
gateway feature is available but not enabled in the current KIND CI.
> Added CI for external gateway feature support

- test/scripts/e2e-kind.sh
A bunch of network policy tests were being skipped which should pass now.
Closes #1190
> Enable more CI tests for k8s e2e

- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/config/cni.go
- go-controller/pkg/config/config.go
- go-controller/pkg/node/node.go
currently it is very hard to debug any issues with cnishim. the error
messages gets captured in the kubelet's log and its hard to just filter
out ovn cni shim specific messages.
this commit adds support to log all of the cni shim specific messages
to configurable log file (by default it is
/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log). the ovnkube-node adds
two fields to 10-ovn-kubernetes.conf file, namely logFile and logLevel
that is passed onto the cni shim either by kubelet or multus. using the
information from os.STDIN, the cnishim setups logging
@ovn-org/ovn-kubernetes-committers
> add logging support to cnishim

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
> trivial: use the right array index in --version output string parsing

- dist/images/ovnkube.sh
> check_health() should be using OVS_RUNDIR for OVS components

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_test.go
Currently passing nil elements to MarshalPodAnnotations will cause "<nil>"
to be added to the json fields where they are not appropriate.
This PR removes one specific example of attempting to pass a nil element
to MarshalPodAnnotations() and makes a validation function that checks if
any element passed to MarshalPodAnnotations() is nil and errors if that is
that case. Unit tests where added to ensure this behavior.
> Remove errors based on passing nil elements to MarshalPodAnnotations()

- dist/images/ovndb-raft-functions.sh
ovn_db_log(Loglevel) option is being set to ovn_log_nb & ovn_log_sb in ovndb-raft-functions.sh
which have been renamed to ovn_loglevel_nb & ovn_loglevel_sb. So, correcting it.
> ovndb-raft-functions.sh:ovndb Loglevel option still set to ovn_log_db

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/healthcheck.go
in shared gaetway mode, we install openflow flows to connection track
all the packets leaving the logical network toward physical network so
that we can steer the reply packets back to the logical network. the
flows related to this logic are added using the `ofport` number of the
patch cable that connects the OVS bridge and integration bridge
it so happens that ovn-controller, when it hits a snag, it can tear
down this patch cable under the foot of ovnkube-node and add it back.
this changes the `ofport` number and all that openflow rules are now
invalid
this commit adds a check to ensure that the `ofport` number didn't
change underneat onvkube-node
> shared-gw: the ofport number can change under your feet

- .github/PULL_REQUEST_TEMPLATE.md
@girishmg @danwinship @trozet @danwinship 
Based on the discussion we had last night I pulled this together.
It's certainly not a substitute for good commit messages - they will persist in the git log after merge and haunt us forever.
What it does do though is make sure that reviewers have all of the necessary context at review time.
> Add A Pull Request Template

- go-controller/hack/test-go.sh
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
Set up a route via the hybrid overlay port IP address through
the management port device to hybrid overlay nodes. Also add
a reply flow to send the traffic back to the management port.
As a bonus, makes services work.
@JacobTanenbaum
> hybrid-overlay: enable host to access hybrid overlay nodes

- go-controller/pkg/ovn/master.go
There was a bug introduced while fixing the chassis deletes where
the node name slice was pre-created with n copies of empty strings.
Instead what is desired is to pre-create the slice of a given
capacity. This commit fixes that issue.
> master: Fix slice creation for syncing nodes

- go-controller/pkg/util/net_linux.go
Fixes to linkneigh utility methods
1. Fixed LinkNeighAdd to add the binding instead of setting it.
2.  Added a helper method for LinkNeighSet
> Fixes to linkneigh utility methods

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/endpoints_test.go
- go-controller/pkg/ovn/service.go
In my ExternalIP PR: https://github.com/ovn-org/ovn-kubernetes/pull/978 I fixed some minor issues related to NodePorts management in the endpoints watcher that we run. @trozet raised the valid point that I should split that to a separate PR, which is this.
PTAL: @trozet / @girishmg / @dcbw
> Small changes + minor fixes to endpoints handler logic

- .github/workflows/test.yml
- contrib/kind.sh
- test/scripts/e2e-kind.sh
This allows us to stop skipping tests with fixes in v1.18 and increases
stability in our CI.
Bumps timeout on pods coming up. Quay.io is now taking longer to
download imags.
> Bump KIND/K8S to v1.18.2

- contrib/kind.sh
Signed-off-by: Sergi Jimenez <tripledes@users.noreply.github.com>
Currently *kind.sh* removes any IPv6 address matching *::1*, this can lead to removing valid ones, e.g 2607:beef:be:beef::1df/128
Running *kind.sh* enabling IPv6 on a node having an IPv6 address matching *::1*, the script will fail, complaining for not finding an IPv6 for the API.
Make sure removing localhost (::1) does not remove valid IPv6 addresses
> kind: don't remove valid IPv6 addresses

- contrib/kind.sh
- contrib/kind.yaml.j2
This PR allows the number of Worker nodes to be configured when running a KIND deployment.
If no additional input is passed to the kind.sh script, the script behaves same as before.
There are two ways to set each variable, and they are equivalent. Either via environmental variable or via CLI parameter. Examples:
$ ./kind.sh -wk 4
$ KIND_NUM_WORKER=4 ./kind.sh
Update KIND deployment to allow configurable number of workers
> Update KIND deployment to allow configurable number of workers.

- .github/actions/retest-action/Dockerfile
- .github/actions/retest-action/action.yml
- .github/actions/retest-action/entrypoint.sh
- .github/workflows/commands.yml
- .github/workflows/test.yml
Fixes #1216 
Before this merges someone with admin on this repo will need to:
1. Create a `ovn-robot` GitHub User and grant them `write` access to this repo.
2. Create a Personal Access Token with `repo` scope and add it as a secret called `REPO_ACCESS_TOKEN` ([docs](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets))
Once it's merged, a comment with `/retest` will attempt to re-run the the CI workflow.
This could fail if, for example, the tests were all green - GH doesn't allow you to re-run in that case.
Or perhaps for other reasons that we'll find out later.
If it was successful, the action will add a :rocket: to the comment.
> Add a GitHub Action To Re-Test PR's

- go-controller/pkg/factory/factory.go
This commit enables creating queued informers for pod events and
increases the number of event queues for handling events to 15.
At scale, the pod informer gets events more rapidly, but the handling
of these events is rather serialized. This will allow for multiple pod
events to be handled in parallel for a given namespace.
Scale tests were ran with this change. At higher node scale (n > 150), the event handlers start contending if the `numEventQueues` is > 25.
> scale: Enable parallel pod creation

- docs/ci.md
- test/Makefile
- test/scripts/e2e-kind.sh
I don't want to run an entire test suite when debugging one test. This will allow us to run a single test by doing:
```
github.com/ovn-org/ovn-kubernetes $ make -C test shard-test WHAT="should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector"
```
Once https://github.com/ovn-org/ovn-kubernetes/pull/1301 we might even have the bot run the one test that failed during our builds.
> Run single k8s test, if specified

- test/scripts/e2e-kind.sh
the following ingressclass test...
"should prevent Ingress creation if more than 1 IngressClass marked as
default"
...that has been failing in CI must be skipped as there is a race
condition in the code. See:
https://github.com/kubernetes/kubernetes/pull/90254
> skip ingressclass test because its buggy

- docs/ci.md
1. the local tests file name was incorrect
2. fixed the KUBECONFIG environment variable's value
> trivial: minor fixes to ci.md document

- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/util/iptables.go
- test/scripts/e2e-kind.sh
the commit will fix the  following errors that we are seeing in the
ovnkube-node log
--------8<-----------------8<-------------
"E0509 07:24:35.366153 195 management-port_linux.go:215] could not set
up iptables rules for management port: running [/usr/sbin/iptables -t
nat -I OVN-KUBE-SNAT-MGMTPORT 1 -o ovn-k8s-mp0 -j SNAT --to-source
10.192.16.2 -m comment --comment OVN SNAT to Management Port --wait]:
exit status 1: iptables: Index of insertion too big."
--------8<-----------------8<-------------
The main issue was that we never created OVN-KUBE-SNAT-MGMTPORT chain, so that was causing the error we are seeing.
Once the k8s cluster is up and running, do the following on the node:
1. …
> create the OVN-KUBE-SNAT-MGMTPORT nat chain if it does not exist

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_shared_intf_linux.go
- go-controller/pkg/node/gateway_shared_intf_windows.go
In the shared gateway mode, the NodePort service is handled by the
OpenFlow flows configured on the OVS bridge in the host. These flows
act only on the packets coming in from outside of the node. If someone
on the node is trying to access the NodePort service, those packets
will not be processed by the OpenFlow flows, so we need to add iptable
rules that DNATs the NodePortIP:NodePort to ClusterServiceIP:Port.
+---------------------------------------+
|                 Node1                 |
|             (10.8.51.51)              |
|                                       |
|                          +----------+ |
|                          |  br-int  | |
|   +--------+             +----+-----+ |
|   |  Node  |             SNAT: NodeIP |
|   |   IP   |                  |       |
| …
> shared-gw: fix access to nodeport services from the node itself

- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/net_test.go
Add "Pods" support for "pkg/ovn/pods.go:getPodAddresses() /
waitForPodAddresses() / pkg/util/net.go:GetPortAddresses() need to handle
multiple IPs".
> dualstack support for GetPortAddresses

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
In preparation for the egressFirewall that would use a namespace wide port_group
generalize the multicast port_group code so that egressFirewall or other objects
could use the namespace wide port_group as opposed to creating another port_group
that contains the same information.
> Make the multicast port_group more general

- .github/workflows/test.yml
- dist/images/ovnkube.sh
- test/e2e/e2e_test.go
- Creates a source and destination pod on two separate worker
nodes and verifies connectivity between the nodes in CI.
- There is a test for the default installation for pods on br-int
and a second test for hybrid-sdn pods on br-ext CI deployments.
> Add inter-node e2e tests

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/ovn/address_set.go
- go-controller/pkg/ovn/address_set_test.go
- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/fake_address_set.go
- go-controller/pkg/ovn/fake_address_set_test.go
- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/util/pod_annotation.go
Put address sets into an object for better encapsulation and cleaner unit tests.
Note that this is based off the port cache code in https://github.com/ovn-org/ovn-kubernetes/pull/1000 so once that merges I'll rebase.
> Address set objects

- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/pkg/ovn/ipallocator/allocator.go
- go-controller/pkg/ovn/ipallocator/allocator/bitmap.go
- go-controller/pkg/ovn/ipallocator/allocator/bitmap_test.go
- go-controller/pkg/ovn/ipallocator/allocator/interfaces.go
- go-controller/pkg/ovn/ipallocator/allocator/utils.go
- go-controller/pkg/ovn/ipallocator/allocator/utils_test.go
- go-controller/pkg/ovn/ipallocator/allocator_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/subnetallocator/allocator.go
- go-controller/pkg/ovn/subnetallocator/allocator_test.go
The first commit in this PR renames the current `pkg/ovn/allocator` package to `pkg/ovn/subnetallocator`. This is to accommodate the new ipallocator package that we are bringing in to this project from the `kubernetes` project.
The second commit in this PR adds a new `pkg/ovn/ipallocator` package that provides support for IPAM. Given a subnet, ipallocator assigns the next available IP address either in a random fashion or contingous fashion. This functionality is required by PR #1365 and PR #1363 . The files underneath ipallocator folder is copied over from kubernetes' pkg/registry/core/service/{allocator, ipallocator} with some simplification.I have removed the snapshot/restore feature from the ipallocator library as we have our own way of persisting the allocated ip information. This …
> ip allocator and subnet allocator changes

- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_test.go
kubelets < 1.16 only set the Pod.Status.PodIP, hence, if
those pods does not have annotations, they will fail to report
an IP.
> add support for old kubelets to GetAllPodIPs

- go-controller/pkg/ovn/loadbalancer.go
Save on some nbctl calls.
Improve efficiency by batching some bulk changes to logical switch ACLs on service changes.
Improve efficiency when handling service creation and deletion.
> master: batch loadbalancer acl updates

- dist/images/Dockerfile.fedora.dev
1. Provide ovn/ovs repo as a argument to override, so user can use their local repo/branches for building image.
2. Copy iptable wrapper scripts (see pr #1290)
3. Create openvswitch group/user for installation, as it's done while installing openvswitch using rpms. RPM installations are standard installation so anybody dealing with ovs images (like openshift cluster network operator) expect it to be running under openvswitch:openvswitch user/group. 
> Patch does following improvement to the dockerfile

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/port_cache.go
- go-controller/pkg/util/net.go
fairly minimal; just pushes the "dual-stack barrier" from one side of the port cache to the other...
(note, if #1372 merges first the test case change here should be updated to match that)
> ovn: add multiple pod IPs to port cache

- go-controller/pkg/ovn/namespace.go
when deleting the namespace port group if you do not reset the portGroupUUID on
the namespaceInfo struct updateNamespacePortGroup() will never create a new namespace
port wide port_group if it is needed again
> clear the portGroupUUID when deleting the namespace port group

- dist/images/ovnkube.sh
the entrypoint script for various ovn k8s containers call
ready_to_start_node() to see if they can continue starting the process
for that container. This function makes a call to ovn-nbctl CLI and this
call fails, timeouts, at scale with 100s of nodes in the cluster.
The call to ovn-nbctl is not required. All we need to check in this
function is to see if ovnkube-db kubernetes service has ovnkube-db
endpoints populated. The logic that populates these endpoints would
have already ensured that the OVN DBs are available at the said
endpoints, so there is no need to check again.
> ovnkube.sh: ready_to_start_node() fails at scale

- dist/images/daemonset.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
Currently ovn-kubernetes supports configuring tcp port, for both the DB
and Raft control plane for both NB/SB DB, however it is not explictly
called out in the yaml files. This patch exposes those environment
variables and updates daemonset.sh to take these parameter at build
time to generate the db yaml with non-default values.
@ovn-org/ovn-kubernetes-committers trivial fix, PTAL. Thanks.
> Expose NB/SB OVN DB TCP db and raft port numbers

- .github/workflows/test.yml
- contrib/kind.sh
Currently the e2e tests in the CI are run only in the local gateway
mode. It would be good to have all tests run in both modes. So a
new flag has been added to the kind.sh script to accept the shared
mode as well.
> CI: Make tests run in both shared and local gateway modes

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn_test.go
The only reason to lock the events array was to ensure that informer
shutdown worked correctly (mostly for unit tests), and that when
a nil event queue was found to stop distributing events to it.
Instead wait for all processEvent() goroutines for each event queue
to terminate before returning from Shutdown(), which handles stopping
event distribution. Just leave the event queues open as there is no
way to safely close now, because the shared informer may still be
delivering events to the factories handler before it notices that
the stop channel has been closed. This isn't a problem though, since
we only ever stop the informer on exit anyway.
@squeed @trozet @abhat 
Fixed a deadlock in handling multiple pod updates.
> factory: remove unecessary locking for enqueueEevent

- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
Don't use direct byte manipulation of the node subnet, otherwise
it's changed for all subsequent uses and that causes the host route
via the management port for the hybrid overlay cluster subnet to
get a .6 address instead of the expected .3.
@trozet @rcarrillocruz @dave-tucker
> hybrid-overlay: fix host route to hybrid overlay subnets

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/pods_test.go
When namespace is updated to remove hybrid annotation, we were not
updating the nsInfo fields so a new pod would get the hybrid gw .3
address route accidentally.
> Fixes resetting hybrid annotation on namespace update

- .github/workflows/test.yml
- docs/ci.md
- test/scripts/e2e-kind.sh
This PR reduces the number of parallel jobs that run in GitHub Actions. We're seeing a combinatorial explosion in the number of jobs that need to be run, and it appears to be causing a backup in the GitHub Actions job queue. This ends up slowing down the test suite due to the overhead of having to install KIND and other dependencies.
> Merge e2e test shards

- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/node/helper_linux.go
- go-controller/pkg/node/helper_windows.go
- go-controller/pkg/node/node.go
- go-controller/pkg/util/net_linux.go
when a pod is deleted make sure to delete any conntrack entries assocaited with
those pods.
https://bugzilla.redhat.com/show_bug.cgi?id=1787434
> explicitly delete conntrack entries for deleted pods

- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/types/types.go
- go-controller/hybrid-overlay/pkg/util/util.go
- go-controller/pkg/kube/annotator.go
- go-controller/pkg/kube/kube.go
Copies External Gateway namespace annotations on to pods, as this is where they are actually consumed. This may enable us to avoid a) waiting for the namespace to be available before processing pod updates, b) having namespace update code calling `addOrUpdatePod` in sequence as it could potentially cause races, lock contention and it's not threaded (neither are pod updates for now but they are likely to be in future).
There are no tests so this will need manual verification that existing behaviour is preserved before merge.
:man_shrugging: 
> hybrid-overlay: Annotate Pods on Ns update

- go-controller/pkg/factory/factory.go
If two updates come in for the same pod in short succession, they will block all other pod updates, since the function that muxes updates will be blocked.
I saw this while running some simple benchmarks.
So, increase the queue size to 10, just to prevent most cases of head-of-line blocking.
> pkg/factory: increase QueuedHandler queue size

- dist/images/ovnkube.sh
The default for hybrid-overlay is disabled, but logic error is causing it
to be enabled on nodes.
> Hybrid-overlay defaults to enabled on nodes

- go-controller/pkg/util/pod_annotation.go
This PR has two commits
1. GetAllPodIPs() was not skipping over the `nil` net.IP address (in one scenario) and was including the nil object in the returned array. There is a fix for this.
2. We were sorting the IPs that were being added to the address_set. I don’t know how efficient this
sort is going to be when we have 1000s of pods in a single namespace. Furthermore, the sorting is lost as new pods gets added to namespace later on, so just removed the sorting
@dcbw FYI
@ovn-org/ovn-kubernetes-committers PTAL. Thanks
> some minor fixes in the AddressSet object code.

- contrib/kind.sh
lot of failures in our CI runs off late has been the failure to install
kind. the script tries to deploy ovnkube-node.yaml using create and it
fails with
~~~~~~~
Error from server: error when creating "ovnkube-node.yaml": etcdserver:\
request timed out
~~~~~~~
and then it tries again up to 10 times to re-deploy but fails every
single time with error as show below
~~~~~~~
+ kubectl create -f ovnkube-node.yaml
Error from server (AlreadyExists): error when creating \
"ovnkube-node.yaml": daemonsets.apps "ovnkube-node" already exists
+ (( retries += 1 ))
info: waiting for 'kubectl create -f ovnkube-node.yaml' to succeed...
+ [[ 2 -gt 10 ]]
~~~~~~~
since we retry use `apply -f`
@ovn-org/ovn-kubernetes-committers PTAL. Thanks
> kind: use kubectl apply and not kubectl create since we retry on failure

- go-controller/pkg/metrics/master.go
- go-controller/pkg/ovn/master.go
the way it is now, the NB_Global table gets updated with this timestamp
from three different places and it gets overwritten by these updates.
we just want the active master node to set this metric value in the OVN
NB table
> run e2e_timestamp metrics updater only on the active master node

- contrib/kind.yaml.j2
etcd suffers with slow disks, because it has to sync data
frequently to offer consistency.
Since we don't need to persist the data, we can use RAM
for storage to have a fast storage.
IMPORTANT: data will not survive reboots.
> run etcd in memory

- go-controller/pkg/factory/factory.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/ovn/ovn.go
This PR adds following two commits:
- capture latency values in starting all the watchers
we add watchers for nodes, pods, namespaces, services, endpoints, and
network policies. almost all of these watches does the following two
things 
- for all of the existing objects in K8s it calls OnAdd() function
- for all of the objects that is present in OVN but not is K8s, that is
stale entries, it removes them from OVN
we don't have observability into how long does each of these task take,
so adding that observability through log messages. there is no point
in creating a prometheus metric for this since it only applies on the
ovnkube-master start
2. add a metric to capture the number of times a resource is being updated
this metric will give insight into how often a UpdateFun for resource,
(pod, …
> add observability into some of the ovnkube-master daemon tasks

- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/hybrid-overlay/pkg/controller/node_windows.go
- go-controller/pkg/node/node.go
This commit removes the Namespace event handler from the Node
controller. Nodes don't need to respond to these events as the
master will update pods with the necessary annotations if a
namespace changes.
> ho: Don't handle Namespace updates on Node

- go-controller/pkg/factory/factory.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/ovn/master.go
Adds following metrics
1. metric to capture whether a given ovnkube-master is leader or not
the leaderelection module provides hooks that gets called when an
instance becomes a leader or looses an election. use those hooks to
capture the appropriate state
2. metric to capture resource update duration histogram
this metric captures the latency of various UpdateFunc handlers
registered for a given resource plotted as a histogram. should be
helpful in knowing what the 95% percentile of various resource updates
are.
@squeed FYI
@ovn-org/ovn-kubernetes-committers PTAl
> ovnkube master leader and resource update histogram metrics

- go-controller/pkg/ovn/pods_test.go
The unit test resets the annotations on the NS then expects a new pod to
be configured with the normal default gw. We need to ensure we wait for
the namespace to be updated before we create the new pod.
Closes: #1413
> make HO unit test wait for namespace update

- go-controller/pkg/ovn/pods_test.go
There's a race between when the namespace is updated and the new pod
that gets created right after. The problem is nsInfo in the ovn-k8s
backend may not be updated (has to wait for lock) by the time the new
pod gets created. A 1 second sleep fixes the issue.
> Add sleep timer to HO test

- test/e2e/e2e_test.go
- this commit verifies the mock external gateway containers exist
before attempting to delete them in AfterEach().
- it also changes the framework err handling to logf instead of failing
the test to cut down on confusion when troubleshooting a test failure.
Can be verified locally with the following or observed in CI actions:
```
./kind.sh -ho
./kind.sh -ho -ha
pushd $GOPATH/src/k8s.io/kubernetes
kubetest --provider=local --deployment=kind --kind-cluster-name=ovn --test
```
Validate gateway containers before cleanup in e2e and change any errors to log only
> Validate container before cleanup in e2e

- dist/images/daemonset.sh
- dist/templates/ovnkube-master.yaml.j2
a change was made to OVN logical topology to include distributed gateway
port to provide access to node local services from hostnetwork pods.
this is needed only for the shared gateway mode. there is a check in
place in master startup code to create these ports for shared gateway
mode alone. however, the default value of the gateway mode is 'shared'
and the yamls generated didn't have a way to change this to 'local'
mode and as a result the topology change was happening for the local
gateway mode too.
Fixes issues #1446
Co-authored-by: Yun Zhou <yunz@nvidia.com>
@trozet PTAL
> expose gateway mode for ovnkube-master process

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/config/cni.go
- go-controller/pkg/config/config.go
Adds log rotation support for ovn-k8s-cni-overlay.log file.
Making (MaxBackups, MaxAge, MaxSize) as a configurable values
through yaml files.
> Adding log rotation parameters as configurable values.

- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/master_test.go
during the code review of edb24e6a7114 (topology changes to enable
Node-Local Services Access in Shared GW Mode) it was decided to use
the prefix of rtos- and stor- for the ports connecting node_local_switch
and the ovn_cluster_router. however, for the switch port we are still
using a different convention.
@trozet FYI-
> trivial: incorrect prefix used for the port connecting switch to router

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_localnet_windows.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_shared_intf_linux.go
- go-controller/pkg/node/gateway_shared_intf_windows.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/node.go
- go-controller/pkg/node/ovn_test.go
- go-controller/pkg/node/port_claim.go
- go-controller/pkg/node/port_claim_test.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/endpoints_test.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
- go-controller/pkg/ovn/service_test.go
- go-controller/pkg/util/iptables.go
- go-controller/pkg/util/kube.go
- go-controller/pkg/util/kube_test.go
Spoiler: _this is a bit of a provocative PR_
Seeing as how the [google group discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/ovn-kubernetes/G8sR1mnpeLo) died out a bit on this topic, I decided to go ahead and implement the solution as to try to move the conversation ahead here in this PR. 
The background to this story is to make `ExternalIP` for services work with ovn-kubernetes. They need to be reachable from any pods in the cluster or any physical node. Today the `ExternalIP` is only reachable from the pods running on the node with the lowest IP in the cluster. This is due to the load balancer item only being attached to that node's logical router. This PR introduces a similar mechanism to what we have for `ClusterIP`, but continues using the …
> ExternalP for ovn-kubernetes  

- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/metrics.go
The coverage/show command against ovn-northd provides metrics that
captures various aspects of ovn-northd's functionality. This commit
is going to capture those values and export it.
In addition to those metrics, the output of "status" command is exported
as well.
Please see below document for more information:
https://docs.google.com/document/d/\
1BAsjLOpAeSyIq2UcyukPK7PgKCqgAKuHcz3962DtoUo/edit?usp=sharing
Co-authored-by: Pardhakeswar Pacha <ppacha@nvidia.com>
@squeed @ovn-org/ovn-kubernetes-committers PTAL
> add metrics for OVN's ovn-northd components

- .github/workflows/docker.yml
Was missing a `run: |` for the build step.
> .github: Fix docker.yml

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/metrics/ovn.go
- go-controller/pkg/util/ovs.go
The coverage/show command against ovn-controller provides metrics that
captures various aspects of ovn-controller's functionality. This commit
is going to capture those values and export it.
In addition to those metrics, the following metrics on each of the
ovn chassis is exported:
-- ovn-openflow-probe-interval
-- ovn-remote-probe-interval
-- ovn-monitor-all
-- ovn-encap-ip
-- ovn-encap-type
-- ovn-remote
-- integration_bridge_openflow_total
-- integration_bridge_patch_ports_total
-- integration_bridge_geneve_ports_total
Please see below document for more information:
https://docs.google.com/document/d/\
1BAsjLOpAeSyIq2UcyukPK7PgKCqgAKuHcz3962DtoUo/edit?usp=sharing
Co-authored-by: Pardhakeswar Pacha <ppacha@nvidia.com>
@squeed FYI …
> add metrics for ovn-controller and ovnkube-node components

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/hybrid-overlay/pkg/util/util.go
not all hybrid network cases will have externalGateway and VTEP IPs.
Correct the functionality of CopyNamespaceAnnotationToPod() to only
copy annotations types.HybridOverlayExternalGw and
types.HybridOverlayVTEP to a pod if they exist on the namespace.
Then the AddPod() can correctly deal with unset values.
> Correct the way that externalGateway and VTEP IP are copied

- go-controller/go.sum
- test/e2e/e2e_test.go
This commit asks our tests to poll for the presence of annotations
on the pods that are created as some signal that the network is,
almost, ready.
The OVN/HO master are responsible for writing these annotations.
The nodes wait on the presence of theses anootations before processing
can continue.
> test: Check network readiness before connection tests

- .github/workflows/test.yml
- go-controller/.gitignore
- go-controller/Makefile
- go-controller/hack/test-go.sh
- test/.gitignore
- test/Makefile
- test/e2e/e2e_suite_test.go
- test/e2e/go.mod
- test/scripts/e2e-cp.sh
- test/scripts/e2e-kind.sh
To help automatic identification of flakes we need to start collecting data from our test runs.
As most suites support Junit output, we can generate this and upload to GitHub as artifacts.
This PR:
- Passes correct arguments to `e2e.test` to generate junit reports
- Adds a reporter to the `e2e_suite_test.go` file to generate junit reports
- Conditionally adds ginkgo arguments to all unit test suites which can produce reports
- Adjust GitHub Actions to archive the reports as artifacts
N/A
Artifacts for this run should include Junit reports.
> Create Junit Reports for all test suites that support it

- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
- go-controller/cmd/ovn-kube-util/app/ovs-exporter.go
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/ovs.go
- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/ovs_unit_test.go
a new container called ovs-exporter that is part of ovnkube-node Pod
exports all the metrics related to OVS. For example:
-- OVS datapath metrics
-- OVS bridge metrics
-- OVS memory metrics
-- OVS hw offload metrics
-- OVS interface metrics
Please see document below for more information:
https://docs.google.com/document/d/\
1BAsjLOpAeSyIq2UcyukPK7PgKCqgAKuHcz3962DtoUo/edit?usp=sharing
Co-authored-by: Pardhakeswar Pacha <ppacha@nvidia.com>
@squeed FYI
This PR depends on #1449  and #1451
> ovs-exporter process to export all OVS related metrics

- go-controller/pkg/config/config_test.go
An url.Parse() error string message changed a bit in go 1.14 (a `"%s"` became a `"%q"`), breaking a test that depended on an exact string match. Fix it to do a substring test instead so it works with either version.
Fixes "make test" on my laptop.
> config: fix unit test under go 1.14

- go-controller/pkg/ovn/address_set.go
- go-controller/pkg/ovn/address_set_test.go
- go-controller/pkg/ovn/fake_address_set_test.go
- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/policy_test.go
1. Now dual stack is supported as first class candidate in Address Set APIs
2. Internally Address set api will always create Ipv4 and Ipv6 address sets for each create.
3. Changes to the policies to support the new API structure and dual stack.
4. Tried to reuse existing address set code as much as possible.
5. Only minimal changes to the tests as required to make the build except a few test cases added to address new Address Set scenarios. More tests will follow in a separate PR.
6. Not addressed ip-blocks in policies yet. Will be done in separate PR.
> Dual stack support for address set and network policies.

- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/policy.go
Dual stack support for IP blocks in network policy
Support dual stack for ip blocks and except blocks in network policies.
Support dual stack for management interface
This PR is dependent on the following PR.  So that should be merged before this. 
https://github.com/ovn-org/ovn-kubernetes/pull/1393
> Dual stack support for IP blocks in network policy

- go-controller/pkg/ovn/fake_address_set_test.go
Currently the output of GetIPv4HashName() and GetIPv6HashName() in the
fakeAddressSet implementation do not mirror the functionality of the
GetIPv4HashName() and GetIPv6HashName() in the OvnAddressSet implementation
of the AddressSet interface. This will cause functions that call GetIPvXHashName()
to behave differently under test then under normal operating conditions.
This patch corrects that and makes the output the same
> Make output of testing functions mirror the real functions

- .github/workflows/cleanup.yml
- .github/workflows/commands.yml
This should stop the cron trigger and issue comment workflows
from running on forks,
> .github: Don't run utility workflows on forks

- test/scripts/install-kind.sh
currently the kind-install.sh assumes that you are using a
standard golang installation and the GOBIN is at GOPATH/bin.
I added some logic in the install to check if a GOBIN is present
and use that allowing a greater number of configurations to use
kind for testing
> change kind-install to support GOBIN environment variable

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
https://github.com/ovn-org/ovn-kubernetes/pull/1427 brought the capability to set the vxlan port on the windows side of a hybrid network. The linux side should have the same capability to avoid UDP port collision 
> for hybrid networks enable setting vxlan port on the linux nodes

- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/subnetallocator/allocator.go
- go-controller/pkg/ovn/subnetallocator/allocator_test.go
The configuration always specifies networks as base CIDR plus `HostSubnetLength`, but the allocator (for historical reasons) required the `HostSubnetLength` to be converted to its inverse, which then requires the caller to unnecessarily take into account whether it's an IPv4 or IPv6 range (which the hybrid overlay code was not doing).
Fix this by just making `SubnetAllocator.AddNetworkRange()` take a `HostSubnetLength` instead, and also make it an int rather than uint32, for ease of use, and then update everything for that.
(So to clarify, this is a dual-stack bugfix in the hybrid overlay code, and just a cleanup everywhere else.)
> Simplify SubnetAllocator ranges, fix hybrid overlay problem

- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/net_linux_unit_test.go
Today the link argument of the LinkRouteExists() function is
ignored. It should be used as a filter for the route existence
check.
Fixes #1471
> use the link argument in the LinkRouteExists() function

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/node_annotations_test.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_test.go
- go-controller/pkg/util/subnet_annotations.go
- go-controller/pkg/util/subnet_annotations_test.go
- go-controller/pkg/util/util.go
After a new Node is created, it will take a while before the
ovn-kubernetes process on that node annotates the node with the
information the master needs. The master should not repeatedly log
"errors" about the annotations not being set, because this is
completely expected.
Also, make ParseNodeManagementPortMACAddress() consistent with all of
the other annotation-parsing methods, and have it return an error when
the annotation is unset. This requires updating one caller, which was
confused anyway because it thought it was checking if the annotation
was removed, but we never remove the annotation after setting it;
really it was only checking if the annotation had not been set yet.
> ovn: don't log spurious warnings/errors on node creation

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
Multicast as a feature is enabled via a config flag that needs to
be passed in. This PR adds support in the start-up scripts for kind
and daemonset files to allow the flag to be passed in.
> Add support for enabling multicast via cli/env variable flag

- go-controller/pkg/ovn/ipallocator/allocator/bitmap.go
- go-controller/pkg/ovn/ipallocator/allocator/bitmap_test.go
- go-controller/pkg/ovn/logical_switch_manager.go
Short-lived pods on a given node may re-use the same IP address in
quick succession, which leads to auditing/logging confusion and race
conditions where a pod delete/add event may not arrive before the new
pod is up and using the same IP.
Instead of using the first free address for a node, switch to
round-robin allocation where all IPs are allocated before any IP
is re-allocated. This doesn't fix the audit/race problems but makes
them less likely until a given node is close to IP exhaustion.
@abhat @danwinship @girishmg
> ovn/allocator: use round-robin IP allocation strategy

- .github/workflows/test.yml
- go-controller/hack/test-go.sh
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/informer/informer_test.go
- go-controller/pkg/ovn/fake_address_set_test.go
- go-controller/pkg/testing/exec.go
Enable the golang race detector for tests and fixes the race conditions detected.
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/1368
Test should pass
> run tests with race detector enabled

- dist/images/Dockerfile.fedora
ovn-20.06.1-0.fc31 and ovn-20.06.1-4.fc31 are failing CI. So force OVN to
run ovn-20.03.0-3.fc31 while root cause is determined.
> Downgrade OVN to ovn-20.03.0-3.fc31

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/net_unit_test.go
Addresses must be a space-separated string sent as a single value.
The slice passed to LSPSetAddress() turns into an OvsSet in which
has special semantics for the second and later elements and causes
OVSDB to insert a newline between the MAC and IPs, leading to
northd complaints that the address is malformed.
@trozet @abhat
> ovn: fix setting addresses on logical switch ports

- .github/workflows/test.yml
The junit xml fails will be needed to improve the reporting, we need to store them so we can reuse it later
> store tests xml artifacts

- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/ovn.go
- go-controller/pkg/metrics/ovs.go
Include srcName and aggregateFrom fields.
srcName will be set if the source of the metric has different name.
aggregateFrom will be populated if a metric is aggregate sum of other metrics
> Extending metricDetails struct

- go-controller/pkg/ovn/master.go
the multicast code all got updated to only work with IPv4 subnets, but we were accidentally still disabling it in dual-stack mode
@dcbw
> Fix IPv6-vs-multicast check

- .github/workflows/test_periodic.yml
- contrib/kind.yaml.j2
- test/scripts/e2e-kind.sh
Set up a periodic job to test dual stack
This does not affect merging, since the job added runes periodically and is only informative
You can see an example of how it runs here
https://github.com/aojea/ovn-kubernetes/actions/runs/184296553
> Dual Stack OVN-Kubernetes job

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/helper_linux.go
- go-controller/pkg/node/helper_windows.go
- go-controller/pkg/util/nicstobridge.go
The current code for detecting the NIC with shared gateway mode assumes
the naming format of the bridge is "br-<nic name>". This is not always
the case an a typical OVS bridge will use the same name for the OVS port
and interface as the brdige. This patch handles that use case.
Additionally, checks for ofport were using "--if-exists" which will not
return an error if the ofport does not exist for that port.
> Fixes shared gateway mode checks

- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_shared_intf_linux.go
Not sure if this is the best fix... if we got rid of all the `ValidatePort` stuff in `getGatewayIPTRules` (which is unnecessary anyway since kube has already validated all of that) then `getGatewayIPTRules` becomes short enough that maybe it would make more sense to just inline it rather than having it run with two separate modes...
cc @alexanderConstantinescu @aojea @dcbw
> node: Fix syncing of local-gateway-mode nodeport services

- .github/workflows/test.yml
- .github/workflows/test_periodic.yml
- contrib/kind.sh
- test/scripts/e2e-cp.sh
- test/scripts/e2e-kind.sh
It runs all the [sig-network] tests in the same job, removing current sharding. We are constrained on number of parallel jobs and the new features we are adding, require new independent jobs.
It allows to run the tests in parallel, right now we run with 4 tests in parallel, running a job in 20 minutes less
> 7 completed jobs  in 40m 56s
vs previously that it took few minutes more than 1 hour.
It build the ovn-kubernetes image only once, and share it using github actions artifacts with the multiple jobs.
> Ci improvements

- .github/workflows/test.yml
- go-controller/pkg/ovn/policy_test.go
Test was failing because the actual command was using ipv6:
||ip6.src == {$a4417939400419858459}
Closes: #1543
> Fixes inconsistent address set tests + Disable test code race detector

- go-controller/pkg/ovn/pods_test.go
Fix a race conditions in one pod testcase.
```
2020-07-27T21:36:57.3433180Z [0mOVN Pod Operations[0m [90mduring execution[0m
2020-07-27T21:36:57.3433620Z   [1mreconciles an existing pod[0m
2020-07-27T21:36:57.3434378Z   [37m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/pods_test.go:182[0m
2020-07-27T21:36:57.4530660Z F0727 21:36:57.452872   11453 exec.go:168] Unexpected command: /fake-bin/ovn-nbctl --timeout=15 --if-exists remove port_group mcastPortGroupDeny ports 8a86f6d8-7972-4253-b0bd-ddbef66e9303 -- add port_group mcastPortGroupDeny ports 8a86f6d8-7972-4253-b0bd-ddbef66e9303
2020-07-27T21:36:57.4531071Z
2020-07-27T21:36:57.4531547Z Executed commands do not match expected commands!
2020-07-27T21:36:57.4532670Z [00]   /fake-bin/ovn-nbctl --timeout=15 --data=bare …
```
> ovn: pod testcase fix

- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-monitor.yaml.j2
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/ovn.go
- go-controller/pkg/metrics/ovn_db.go
- go-controller/pkg/metrics/ovn_northd.go
We have allocated following TCP ports to export metrics from OVN K8s
software components
```
|----------------+----------|
| software       | tcp port |
|----------------+----------|
| ovnkube-master |     9410 |
| ovnkube-node   |     9409 |
| ovn            |     9476 |
| ovs            |     9310 |
|----------------+----------|
```
However, in reality we are exporting metrics for OVN components from
various daemons and at different ports
```
|----------------+------------------------+------|
| OVN component  | Exported By            | Port |
|----------------+------------------------+------|
| OVN North      | ovnkbue-master process | 9410 |
| OVN Controller | ovnkube-node process   | 9409 |
| OVN DB         | ovn-db-exporter POD    | 9476 | …
```
> consolidate exporting of all OVN metrics under one process

- contrib/kind.sh
- docs/kind.md
It workarounds the problem that reboots the host when deleting the KIND cluster directly.
1. Create a cluster
`cd contrib/ ; ./kind.sh` 
2. Delete a cluster
`./kind.sh --delete`
3. The host should not reboot and the cluster should be deleted cleanly
> Fix host reboot after kind delete

- go-controller/pkg/node/gateway_init_linux_test.go
Tests for IPv6 and dual-stack for localnet.
We had tests for IPv4. This PR reuses and refactored  that code to create  tests for IPv6 and dual-stack.
Created a ginkgo Context for localnet tests and have one test each for IPv4, IPv6 ,and dual-stack.
cc: @danwinship
>  IPv6 and dual stack tests for Localnet

- go-controller/pkg/ovn/logical_switch_manager_test.go
- go-controller/pkg/ovn/pods.go
ReleaseIPs should also cause the port addresses on nbdb to get
cleared out in case of error so that the state of a logical port
is in sync between nbdb and ovnkube-master.
> Clear port addresses when releasing IPAM IPs

- go-controller/pkg/ovn/gress_policy.go
Current match logic was breaking dual stack network policies.
The match logic needs parenthesis to aggregate the corresponding
fields matches.
https://github.com/ovn-org/ovn-kubernetes/actions?query=workflow%3Aovn-ci-periodic
> fix network policies for dual stack

- docs/ci.md
- docs/kind.md
Move overlapping documentation on how to install and run KIND(Kubernetes in Docker)
from https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/ci.md to
https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/kind.md
Just to simplify some of the KIND deployment documentation recommended by @Billy99
> Update KIND and CI documentation

- go-controller/pkg/ovn/gress_policy.go
the match string should use parenthesis for the OR logic.
Otherwise, the acls fail in dual-stack mode
This time I ran the tests and are green for the network-policy ones
https://github.com/aojea/ovn-kubernetes/runs/928738628?check_suite_focus=true
> fix dual stack network policy (2)

- go-controller/go.mod
- go-controller/go.sum
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/init_others.go
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/init_windows.go
- go-controller/hybrid-overlay/pkg/windows/service/service.go
- go-controller/vendor/golang.org/x/sys/windows/svc/event.go
- go-controller/vendor/golang.org/x/sys/windows/svc/go12.c
- go-controller/vendor/golang.org/x/sys/windows/svc/go12.go
- go-controller/vendor/golang.org/x/sys/windows/svc/go13.go
- go-controller/vendor/golang.org/x/sys/windows/svc/security.go
- go-controller/vendor/golang.org/x/sys/windows/svc/service.go
- go-controller/vendor/golang.org/x/sys/windows/svc/sys_386.s
- go-controller/vendor/golang.org/x/sys/windows/svc/sys_amd64.s
- go-controller/vendor/golang.org/x/sys/windows/svc/sys_arm.s
- go-controller/vendor/modules.txt
This PR introduces running hybrid overlay as a service on Windows. This is achieved by adding a --windows-service flag to enable running it as a Windows service. This flag is ignored on Linux. This approach is based on kube-proxy and kubelet services.
Signed-off-by: Mansi Kulkarni <mankulka@redhat.com>
Co-authored-by: Aravindh Puthiyaparambil <aravindh@redhat.com>
> hybrid-overlay-node: Windows service enablement

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_shared_intf.go
Originally discussed in #831. We've been carrying a patch in OpenShift that only fixes it for local gateway mode.
Based on discussion in #831 it seems like if we fully masquerade the incoming packets that would do the right thing in shared gateway mode, but how do we do that? iptables doesn't get a chance to run in that case, right?
Fixes #831
> Node: add iptables rules and openflow flows for certain cloud load balancers

- go-controller/pkg/ovn/pods.go
We were missing a continue when we couldn't lock the namespace which
ended up segfaulting during port deletion..
> Fix segfault in exgw route deletion

- go-controller/pkg/ovn/pods.go
Support for dual stack in addRoutesGatewayIP for other default gateway.
Not sure if this is what you expected @dcbw.
cc : @dcbw @danwinship
> Support for dual stack in addRoutesGatewayIP method for other default gateway

- dist/images/ovnkube.sh
- go-controller/pkg/config/config.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/ovn/ovn.go
renamed the egress ip flag to be consistent with other feature flags.
since it is boolean value, the presence/absence of the flag will
determine if the feature needs to be enabled or not
@alexanderConstantinescu @JacobTanenbaum FYI
> consistent naming of the feature flag

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/pkg/informer/informer.go
- go-controller/pkg/informer/informer_test.go
- go-controller/pkg/node/node.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
There was no way to wait until the hybrid overlay informer event handlers
had stopped processing events. Narrow the race window by ensuring that
the informers themselves are done processing events before continuing
to the next test. Otherwise we hit testcase races where an informer for
a previous testcase hasn't finished yet and is accessing data that was
modified by a subsequent testcase's BeforeEach().
See https://github.com/ovn-org/ovn-kubernetes/pull/1512#issuecomment-664414658
@dave-tucker @aojea
> informer: fix testcase races with hybrid overlay event handlers

- .github/workflows/test.yml
- .github/workflows/test_periodic.yml
- contrib/kind.sh
- contrib/kind.yaml.j2
This addresses 2 issues with the CI:
* lack of detail in kubernetes logs to troubleshoot issues
* timing out on test, the average time for an e2e job is around 30 minutes,
but if there are issues it hangs forever and default timeout is 360 minutes.
We can timeout after 1 hour.
> increase kubernetes verbosity on CI and set reasonable timeouts for jobs

- go-controller/hack/test-go.sh
When triggering tests, focus wasn't added as an option to the function triggering those.
Added gingko.focus option to test-go.sh
> Add gingko focus option to test-go.sh

- test/e2e/e2e_test.go
- test/scripts/e2e-cp.sh
Our own e2e tests are failing in the dual-stack CI job because they were only parsing the single-stack form of the node-subnets annotation.
I didn't pull in `util.ParseNodeHostSubnetAnnotation` because (a) nothing else in this file was using any ovn-kubernetes code, and (b) that would require constructing a `Node` object anyway and would end up being overall more complicated than this.
@aojea is there any way to run the dual-stack CI job against this PR?
> fix local e2e for dual-stack
