- .travis.yml
> travis-ci: Add travis-ci config that runs tox.

- ovn_k8s/modes/overlay.py
This patch includes a set of minor and fairly irrelevant changes to
the overlay mode module, namely:
- leverage dict's get default value attribute when possible
- replace if with elif where it makes sense
- use of python list comprehensions to build endpoint list
The latter has also the nice, albeit pointless, advantage of being
a bit faster then the previous routine (around 5%).
> Minor changes to ovn_k8s.nodes.overlay

- .travis.yml
- bin/ovn-k8s-overlay
**DO NOT REVIEW YET**
I have no idea whether this will work or not
> Run flake8 tests on travis CI

- ovn_k8s/modes/overlay.py
- ovn_k8s/watcher/pod_watcher.py
- ovn_k8s/watcher/service_watcher.py
Reverts openvswitch/ovn-kubernetes#20
> Revert "Do not assume pod is always in cache on delete"

- ovn_k8s/common/kubernetes.py
- ovn_k8s/tests/unit/test_kubernetes.py
- requirements.txt
- test-requirements.txt
- tox.ini
They're kind of useful, right?
> First PR for unit tests

- README.md
> Update OVS documentation link.

- README.md
> README.md: Improve documentation around system-id.

- README.md
> README.md: Use proper headline formatting.

- vagrant/provisioning/setup-master.sh
> vagrant: Open up TCP ports correctly.

- ovn_k8s/modes/overlay.py
We can use --wait=sb, to wait for OVN to populate the dynamic
addresses instead of polling for it.
> overlay: Wait for dynamic addresses instead of polling.

- ovn_k8s/modes/overlay.py
> overlay: Warn when unsupported service types get created.

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> vagrant: Mask package versioning information.

- ovn_k8s/common/exceptions.py
- ovn_k8s/common/util.py
- ovn_k8s/watcher/watcher.py
> watcher: Don't show backtrace for API server timeouts.

- docs/debugging.md
> docs: Add information about firewall blocking overlay.

- README.md
> README.md: Provide a link to docs/config.md.

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
> Use logrus acrossing the project

- go-controller/pkg/cluster/master.go
Minor PR that fixes go lint errors that travis pointed out to.
> fix go linter warning messages

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/service.go
Support for NodePort, call for review. Still need to test it completely.
Also TODO: add support for externalIPs.
> Support for NodePort

- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/provisioning/vm_config.conf.yml
I got this to where VMs will start using vagrant-libvirt, but I haven't verified that it's all working properly.  I figured I'd at least share what I have so far.
> vagrant: Support use of vagrant-libvirt.

- vagrant/provisioning/setup-k8s-master.sh
There have been sleep statements in the vagrant and
this commit tries to remove them and start the daemons
more intelligently.
> vagrant: Remove sleep statements.

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/service.go
Network policy integration.
Add support for kubernetes ingress network policy.
> Network policy integration.

- README.md
Signed-off-by: Rostyslav Fridman rostyslav_fridman@epam.com
> Add overlay diagram to README.md

- vagrant/README.md
> vagrant: Add a note about private networks.

- vagrant/README.md
- vagrant/Vagrantfile
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-minion.sh
- vagrant/provisioning/vm_config.conf.yml
> vagrant: Allow bridged networks for north-south connectivity.

- go-controller/cmd/ovn-kube-cni-overlay/ovn-kube-cni-overlay.go
A couple cleanups for the Go overlay including returning a result the runtime can use.  Note that I haven't tested this yet, I'll try to do that soon.  Both if @YaoZengzeng could test it too that would be great.
@shettyg @rajatchopra @YaoZengzeng p
> go-overlay: CNI cleanups

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> vagrant: Upgrade OVS/OVN to 2.8.1

- go-controller/cmd/ovn-k8s-overlay/app/manifests.go
One character fix.
cc @shettyg
> Fix the redhat template

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/service.go
> go-controller: Sync services.

- go-controller/pkg/cluster/master.go
- go-controller/pkg/kube/kube.go
> gofmt: fix up formatting to make travis happy

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
Before this patch, we had support for ingress network
policies when peer is a podselector or namespaceselector.
This adds support egress network policies for the same
peers.
> go-controller: Add egress network policies.

- tasks.md
> update tasks doc with link to community doc

- go-controller/pkg/ovn/policy.go
K8s network policy supports both ingress and egress policy when
peer is from a IPBlock CIDR. The traffic from IPBlock except will
be denied. This patch adds support for this feature.
Signed-off-by: Tong Liu <tongl@vmware.com>
> Add Network Policy IPBlock support

- go-controller/pkg/ovn/policy.go
Currently we wait for pod IP to be set in pod.Status.PodIP.
This only gets set after the pod is created.
This can be slow as pod creation can take time. Since we
can get the IP addresses from OVN annotations, we can setup
firewall much earlier.
> policy: Use IP addresses from OVN annotations.

- go-controller/pkg/cluster/cluster.go
The python code has the ability to bootstrap ssl CA
certificate when it is not present in the file-system.
This commit adds the same feature to golang code.
> cluster: bootstrap CA certificate.

- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> vagrant: Enable SSL certificates for golang utilities.

- go-controller/pkg/util/nicstobridge.go
One could set the IP address of a Linux interface as
172.16.1.2/32 and then give it a default gateway of 172.16.1.1.
This can be done for e.g. by running the following commands.
1. ifconfig eth0 172.16.1.2 netmask 255.255.255.255 broadcast 172.16.1.2
2. route add 172.16.1.1 dev eth0
3. route add default gw 172.16.1.1
The above configuration is what google cloud uses for its VMs.
When the above configuration is used, the current code can fail
because we may attenmpt to do 3. before 2. With this commit,
we do 3. after everything else has been done.
Fixes: #224
> nicstobridge: Handle the case for /32 IP address.

- dist/Makefile
- dist/openvswitch-ovn-kubernetes.spec
WIP
Added new "dist" directory for building rpms
Added spec file and Makefiles
> Create srpm/rpm for ovn-kubernetes

- vagrant/README.md
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
1. kubelet should use kubeconfig.
2. --advertise-address for kube-apiserver.
> vagrant: Few fixes

- go-controller/pkg/factory/factory.go
Discovered while testing on a large cluster of 40 nodes, 3000 pods and 5000 namespaces: we constantly spin over all resources every 10 minutes. This is needlessly aggressive, especially because we do not have a situation where a resync is needed.
> change the resync interval to 12 hours

- go-controller/Makefile
- go-controller/hack/build-go.sh
> minor cosmetic fixes to help with PR ci/cd

- go-controller/pkg/ovn/policy.go
> policy: Add a error message for unexpected delete event.

- go-controller/pkg/ovn/policy.go
We had a race condition (with a TODO item) wherein new
ACLs could be added after we delete all the ACLs when
we delete a policy. This could happen when the call-back
for k8s events come in after we have asked it to close
its thread (or during).
> policy: Don't let new adds when policy is being deleted.

- dist/openvswitch-ovn-kubernetes.spec
- docs/ovn-k8s-overlay.1
- docs/ovn-kube-util.1
- docs/ovn_k8s.conf.5
- docs/ovnkube.1
Major changes:
ovnkube - sort options to same order as --help
ovn_k8s - document the config file.
> Doc changes and improvements

- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
Testing on a large cluster conveys that we should not pound the api server so heavily (or at least so frequently). This PR implements the backoff strategy.
> exponentially back off while retrying on getting pod annotations

- go-controller/pkg/ovn/policy.go
Kubernetes network policy allows multiple ingresses (or
multiple egresses) sections. In each ingress section,
it allows multiple podSelectors (it is not clear why it
supports this, as a single podSelector could have multiple
labels instead).
Our current code had a bug when there are multiple
podSelectors in a single ingress section (or egress section).
This was because we were maintaining separate datastructure
that represented each podSelector and held IP addresses of
the pods selected by that podSelector. Each of this would
then write to the same addressSet in OVN database over-writing
each other.
This commit fixes it by providing a single datastructure for
all podSelectors in a ingress (or egress) section. And each
data structure has a one-one relationship with the addressSet
that …
> policy: Fix bug with multiple podSelectors in a single section.

- README.md
- docs/INSTALL.SSL.md
- docs/INSTALL.UBUNTU.md
> README: Change documentation from python to golang.

- .travis.yml
@shettyg @rajatchopra @alinbalutoiu
> travis: add 'make check' to CI tests

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/service.go
Nothing outside of the ovn package uses them.
@shettyg @rajatchopra @alinbalutoiu
> ovn: privatize some OVN Controller member variables

- dist/Makefile
- dist/files/ovn-kubernetes-master.service
- dist/files/ovn-kubernetes-master.sh
- dist/files/ovn-kubernetes-node.service
- dist/files/ovn-kubernetes-node.sh
- dist/files/ovn-kubernetes.sysconfig
- dist/openvswitch-ovn-kubernetes.spec.snapshot
- docs/ovn_k8s.conf.5
- go-controller/etc/ovn_k8s.conf
This is for v0.2.0
Add packages to control systemd
Since this creates rpms, we need to wait for everything for the next version before this can be completed.
The new version number is mentioned in the spec file.
> rpm build changes

- go-controller/README.md
> go-controller: Windows build steps included in documentation

- go-controller/pkg/util/ovs.go
In rhel/fedora, ovn-controller uses systemd
for startup. The env file there is
/etc/sysconfig/ovn-controller. Also, the variable
name is OVN_CONTROLLER_OPTS.
> util: Use correct environment file in rhel.

- test/integration/openshift-dind-test.yml
- test/integration/system.yml
This should help clear up the CI test failures.
> remove async from ci test setup

- docs/ovn_k8s.conf.5
- go-controller/etc/ovn_k8s.conf
Fix error in ovn_k8s.conf
Fix type on man page for ovn_k8s.conf
> Fix minor problems in rpms

- go-controller/pkg/ovn/policy.go
No functional changes, small LoC win, perhaps a readability win.
@shettyg @rajatchopra
> pkg/ovn: a few cleanups of the ACL code

- docs/debugging.md
The debugging doc was assuming python watcher and scripts.
Change them to reflect ovnkube instead.
> debugging.md: Update for ovnkube.

- go-controller/cmd/ovn-k8s-overlay/ovn-k8s-overlay.go
- go-controller/cmd/ovn-kube-util/ovn-kube-util.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
@pecameron To go with your PR #327 
@dcbw @shettyg ok?
> add a version flag to config so --version shows the latest release number

- dist/openvswitch-ovn-kubernetes.spec
- dist/openvswitch-ovn-kubernetes.spec.snapshot
This spec file change builds  ovn-kubernetes v0.3.0
Signed-off-by: pecameron <pcameron@redhat.com>
> Change spec file for v0.3.0

- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_linux.go
- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_windows.go
- go-controller/cmd/ovn-k8s-cni-overlay/ovn-k8s-cni-overlay.go
- go-controller/cmd/ovn-k8s-overlay/app/gateway_init.go
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/hack/lint.sh
- go-controller/hack/verify-gofmt.sh
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/cni.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- vagrant/provisioning/setup-k8s-master.sh
- vagrant/provisioning/setup-k8s-minion.sh
@shettyg @rajatchopra @alinbalutoiu 
Windows MTU hookup not done, but the value is plumbed through to helper_windows.go.
> Read and use config file in CNI plugin

- go-controller/pkg/ovn/policy.go
Three way deadlock:
1. Network policy delete
Holds np.lock
Issues <-stop that triggers RemovePodHandlers
Waits on stopWg
2. Pod event delivered to policyPeerPodWatch
Holds informer.Lock
Waits on np.Lock to perform Pod event (although np is deleted already, but the check is done after acquiring the np lock)
3. Pod watch handler for the NP in question should be removed from federated handlers.
Gets event on <- stop
Calls RemovePodHandler
Waits on informer.Lock that blocks stopWg.Done
@dcbw @shettyg PTAL
> remove deadlock in network policy delete and pod watch

- go-controller/pkg/ovn/pods.go
> pods: Don't create logical port for hostnetwork pods.

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/service.go
> loadbalancer: Better error handling.

- go-controller/cmd/ovn-k8s-cni-overlay/app/helper_windows.go
This is not the proper way to do it, but it is a good starting point.
Fixes: https://github.com/openvswitch/ovn-kubernetes/issues/335
Tested with kubernetes version `v1.10.0`
> ovn-k8s-cni-overlay: Set MTU for container interface on Windows

- README.md
> README.md: Better compilation instructions.

- go-controller/pkg/ovn/policy.go
Currently, we are applying egress policies before load-balancing
takes place. This means that, we look at the IP addresses of
the packet before load-balancing is done. This is okay, if your
egress policy is to be applied when destination IP is outside
cluster or when the destination IP is a pod's IP.
The bug is when the destination IP is a service IP and after
load-balancing, the IP changes to one of the IPs mentioned in
the egress network policy.
This commit moves the egress network policy to after LB is
done by moving it to egress pipeline of the same switch. This
means that we just need to use "to-lport" in direction.
Also for egress, we don't need to use connection tracker
(allow-related) to allow packets. We can instead use
either "allow" or "drop".
Signed-off-by: Gurucharan Shetty …
> policy: Fix egress policies.

- dist/Makefile
- dist/READMEcontainer.md
- dist/ansible/scripts/ovn-setup.sh
- dist/images/Dockerfile
- dist/images/Dockerfile.fedora
- dist/images/Makefile
- dist/images/ovnkube.sh
- dist/openvswitch-ovn-kubernetes.spec
- dist/openvswitch-ovn-kubernetes.spec.snapshot
- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- dist/yaml/sdn-ovs.yaml
Respond to comments in PR-351
With these changes an image can be built, the cluster provisioned for ovn and ovs/ovn brought up and run.
> Changes to ovn daemonset

- go-controller/pkg/cni/helper_windows.go
Currently, if attaching HNS endpoint to the container fails,
the HNS endpoint does not get deleted. This happens because
the delete function receives the ID of the container instead
of the name of the HNS endpoint.
This also fixes another possible HNS endpoints leak that can
happen if running the ovs command fails.
Fixes issue: #390 
Signed-off-by: Alin Balutoiu <alinbalutoiu@gmail.com>
> cniserver: Fix HNS endpoints leak on Windows

- Dockerfile.centos
> Add hostname rpm to build

- contrib/inventory/group_vars/all
- contrib/roles/linux/kubernetes/tasks/prepare_master.yml
- contrib/roles/linux/kubernetes/tasks/prepare_minion.yml
> Add timeout variable for CLI commands

- dist/READMEopenshiftdevpreview.md
> Instructions for setting up ovn on a OKD-3.11 cluster

- vagrant/README.md
> vagrant: Clarify instructions.

- README.md
I think it makes sense to add this as part of instructions
for master node.
> README.md: Add -gateway-localnet for master node.

- dist/yaml/ovnkube-master.yaml
- dist/yaml/ovnkube.yaml
- dist/yaml/sdn-ovs.yaml
Add beta.kubernetes.io/os: "linux"
(This was ommitted in PR 425)
> Add "linux" selector to sdn-ovs.yaml

- dist/READMEopenshiftdevpreview.md
> Fix errors in dev preview doc

- dist/ansible/scripts/ovn-setup.sh
Wait for cluster and master-api to come up
use /etc/origin/master/master-config.yaml as the source
of the net_cidr and svc_cidr
> ovn-setup.sh changes

- go-controller/pkg/cluster/gateway_init.go
bug: 1626387
https://bugzilla.redhat.com/show_bug.cgi?id=1626387
Jira: SDN-182 Add firewall rule to permit pod to access node
https://jira.coreos.com/browse/SDN-182
> OVN add iptables rule for traffic from pod to external

- dist/ansible/scripts/ovn-setup.sh
jira SDN-203
https://jira.coreos.com/browse/SDN-203
> Changed how to get apiserver

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> Use daemonsets for vagrant.

- go-controller/hack/test-go.sh
- go-controller/pkg/cluster/cluster_suite_test.go
- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/testing/testing.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/iptables.go
@shettyg @squeed @danwinship @rajatchopra
> pkg/cluster: add unit tests and split options into separate Go files

- dist/READMEopenshifttechpreview.md
- dist/ansible/hosts
- dist/ansible/ovn-playbook.yaml
- dist/ansible/ovn-uninstall.yaml
- dist/ansible/run-playbook
- dist/images/Makefile
- dist/images/daemonset.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube.yaml.j2
- dist/yaml/.gitignore
Added an uninstall playbook to remove ovn
./dist/ansible/run-playbook uninstall
Added image variable in dist/ansible/hosts to select the desired image
Moved daemonset.yaml files to template files in dist/templates
Added "daemonsetyaml" target in dist/images/Makefile to expand the
templates into expected daemonset.yaml files in dist/yaml
Also, the image build also generates the daemonset.yaml files from the
template files..
> add ansible uninstall and image config

- contrib/README.md
Updates the ansible README.md file to reflect all the latest
changes.
Signed-off-by: Alin-Gheorghe Balutoiu <alinbalutoiu@gmail.com>
> ansible: Update ansible README.md

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
1. vagrant: Don't need to annotate minions for daemonsets.
2. vagrant: Run 'make daemonsetyaml' for yaml creation
> vagrant: Fixes to handle recent changes.

- dist/ansible/hosts
- dist/ansible/ovn-uninstall.yaml
Make the uninstall more complete
JIRA SDN-237 - make ansible uninstall more complete
https://jira.coreos.com/browse/SDN-237
> OVN ansible uninstall changes

- dist/images/ovn-debug.sh
This commit fixes various minor issues in the ovn-debug.sh and makes it
runnable.
> Make ovn-debug.sh script runnable

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
If you delete a K8s node (run `kubeadm reset -f` and then
`kubectl delete node nodename` on master), then the gatewayCache and
logicalSwitchCache still contains this node. When the node is added back
later, things starts to fail -- pods will get stuck in CreatingContainer
state forever. One can see incorrect gateway_ip set for the pod.
Annotations: ovn={"ip_address":"192.168.2.12/24",
"mac_address":"0a:00:00:00:00:23",
"gateway_ip": "192.168.0.1"}
This is due to the fact that certain steps are skipped because the
cache contains the information from the old allocations.
> Fix cache inconsistency that occurs upon node deletion

- go-controller/pkg/cni/cni.go
- go-controller/pkg/ovn/gateway.go
> govet fixes

- go-controller/pkg/ovn/service.go
Headless ClusterIP services will literally have "None" as the
ClusterIP, and we should ignore those like kube-proxy does.
@danwinship @shettyg @squeed @JacobTanenbaum
> ovn/service: ignore headless ClusterIP services

- contrib/README.md
- contrib/inventory/group_vars/kube-minions-windows
- contrib/ovn-kubernetes-cluster.yml
- contrib/roles/windows/kubernetes/tasks/create_infracontainer.yml
- contrib/roles/windows/version_check/vars/windows.yml
Tested with 2019 LTSC.
[WIP]: https://github.com/openvswitch/ovn-kubernetes/pull/510
> [Ansible] Support Windows server 2019 and 1809

- contrib/README.md
This PR updates and restructures the documentation for the ansible playbooks.
Fixes: https://github.com/openvswitch/ovn-kubernetes/issues/500 
> Update ansible docs

- go-controller/pkg/cluster/cluster.go
The only external-ids that ovn-kubernetes sets in the OVS
database are used by ovn-controller on the node, not the master.
@shettyg @putnopvut what do you think?  The branch starts pods on vagrant for me.
> cluster: don't set external-ids in master codepaths

- contrib/roles/linux/validation/tasks/main.yml
- contrib/roles/windows/kubernetes/tasks/create_infracontainer.yml
- contrib/roles/windows/kubernetes/tasks/main.yml
* Add retries to the CoreDNS validation task and for the task to create the Windows infra-container Docker image
* Disable realtime protection for testing clusters
> Minor fixes and updates

- go-controller/pkg/ovn/loadbalancer.go
> do not make the assumption that OVN DBs are locally available

- OWNERS
> Adding Girish Moodalbail (girishmg) as reviewer

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/gateway-init.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/ovs.go
This reverts commit ee4ad14924ef1d815a0ce1628fe9959f25b40b14, reversing
changes made to 46c6723c433692aed639ccac0cb643231de4f00d.
Fixes #575
> Revert "Merge pull request #503 from dcbw/join-dynamic-addresses"

- tasks.md
Use the new bluejeans link for the community meeting
> Update tasks.md to reflect new meeting location

- dist/images/Dockerfile
- dist/images/kubernetes.repo
> Install the latest kubectl binary in CentOS image

- README.md
- dist/images/ovn-debug.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- docs/INSTALL.SSL.md
- docs/debugging.md
- go-controller/pkg/config/config.go
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> ovnkube.log and ovnkube-master.log shouldn’t be in /var/log/openvswitch

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/util/gateway-init.go
> cluster: move join switch IPAM to 100.64.0.0/16 to support > 253 nodes

- dist/images/ovnkube.sh
> OVN NB, SB, Northd, and ovnkube-master need not wait for OVS daemons

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
This commit cleans up the ovnkube help output by grouping options under various categories:
Generic Options
K8s-Related Options
OVN Northbound DB Options
OVN Southbound DB options
L3 Gateway Options
Currently, the help is one huge output. In the follow up commit, we will introduce subcommands for
ovnkube.
> ovnkube: cleanup help output

- go-controller/pkg/ovn/endpoints.go
> loadbalancer: create OVN LB rules for ClusterIP for UDP protocol

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/service.go
> loadbalancer: do not handle external IP for service type LoadBalancer

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
With the commit 3940547759 [Simplify OVN install] certain changes were
made to ovnkube yam files -- master, node, policy, and so on.
This commit reflects those changes in vagrant so that we can start
using it.
> update vagrant to reflect recent changes to yaml files

- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> vagrant: Use OVS 2.10.x series.

- vagrant/provisioning/setup-master.sh
> vagrant: reflect the new ovnkube-db pods

- dist/images/Dockerfile
- dist/images/Dockerfile.fedora
>  dockerfile: remove copying non-existent binary (ovn-k8s-overlay) 

- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/cni.go
- go-controller/pkg/config/config.go
Signed-off-by: Moshe Levi <moshele@mellanox.com>
> Don't overwrite cni file if exist

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/ovn/management-port_test.go
- go-controller/pkg/testing/testing.go
Adding a wrapper for testing.FakeExec that handles command addition
makes testing simpler by not requiring callers to manage the CommandScript
array themselves, and consolidates command code that creates the
fakeExec itself.
As a bonus: 141 insertions(+), 204 deletions(-)
@shettyg @JacobTanenbaum @girishmg
> testing: simplify FakeExec and fake command generation

- README.md
> README.md: Document dkms dependency.

- dist/images/Dockerfile
Move centos image build to openvswitch 2.10.1
Signed-off-by: root <root@localhost.localdomain>
> On centos use ovs 2.10.1

- dist/images/Dockerfile.fedora
> Build fedora29 image with ovs 2.10.1 and ovn 2.11.0

- README.md
> README.md: Add information for Windows.

- .travis.yml
- test/integration/main.yml
- vagrant/provisioning/setup-master.sh
- vagrant/provisioning/setup-minion.sh
> Bump to Go v1.11.4

- contrib/roles/windows/kubernetes/tasks/run_minion_init.yml
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
- docs/ovnkube.1
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
@girishmg how about this instead of https://github.com/ovn-org/ovn-kubernetes/pull/739 ?
> gateway CLI option cleanup and master NodeportEnable fix

- go-controller/vendor/github.com/golang/groupcache/LICENSE
- go-controller/vendor/github.com/golang/groupcache/lru/lru.go
- go-controller/vendor/k8s.io/client-go/tools/record/OWNERS
- go-controller/vendor/k8s.io/client-go/tools/record/doc.go
- go-controller/vendor/k8s.io/client-go/tools/record/event.go
- go-controller/vendor/k8s.io/client-go/tools/record/events_cache.go
- go-controller/vendor/k8s.io/client-go/tools/record/fake.go
- go-controller/vendor/k8s.io/client-go/tools/record/util/util.go
- go-controller/vendor/vendor.json
The changes that were brought in for Load Balancer services health check was not rebuild after the repo was rebased to K8s 1.14.3. As a result, the repo is broken. I have brought in the missing vendor packages at the right version. This fixes the build.
> vendor: update the packages for the LB services healthcheck

- README.md
> clarify daemonset vs deployment in the README

- .travis.yml
- dist/images/Makefile
@danwinship @shettyg @girishmg
> travis: CI test image builds

- .travis.yml
> travis.yml: Fix syntax.

- go-controller/pkg/ovn/pods_test.go
@danwinship @shettyg @girishmg @pecameron @squeed
> ovn: add testcase for startup pod reconciliation

- go-controller/pkg/cluster/master.go
- go-controller/pkg/cluster/master_test.go
- go-controller/pkg/testing/testing.go
If the node already has the annotation, don't bother setting it again.
@girishmg @danwinship @shettyg
> cluster/master: don't re-set host subnet annotation

- dist/images/ovnkube.sh
> increment retry counter that is currently missing

- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/ovn.go
When a node was added, the master-side NodePort code would block for up to 5 minutes waiting for the gateway load balancers to be created (which would happen only after the "`ovnkube --node`" process was up and running on the new node, which would happen only after the ovn-kubernetes image had been pulled, etc).
Since all event handlers of a given type are run serialized in ovn-kubernetes, blocking in the NodePort Node-added handler would also prevent the primary Node-added handler from running, preventing it from registering any other new nodes.
The net result of this is that if you created multiple new nodes at once, and deployed pods to them which could tolerate NotReady, then on the second and later nodes, those pods would never successfully come up, because the Pod-added handler in …
> master: don't block waiting for gateway load balancer creation

- dist/images/ovnkube.sh
When the shell script sees the OVS_USER_ID parameter, it will run the
various daemons as that user.  The user-info is specified in the standard
user:group notation.
As an implementation detail, using libcap-ng to do the domain transition for
the ovn containers seemed to cause issues, possibly with the capability
bits being retained.  For now, use setpriv as a workaround, but it could be
addressed in the future without impacting users.
Signed-off-by: Aaron Conole <aconole@redhat.com>
> ovnkube.sh: optionally run as non-root user

- OWNERS
> Adding Girish Moodalbail (girishmg) as approver

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/gateway_spare_intf.go
- go-controller/pkg/util/gateway-init.go
This reverts commit 3a69c3d3. Needs some re-work.
> Revert "gateway/local: stop double-NAT-ing"

- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
https://jira.coreos.com/browse/SDN-495
> OVN ovnkube.sh remove version 1,2 support

- go-controller/pkg/cluster/cluster.go
- go-controller/pkg/cluster/node_test.go
- go-controller/pkg/config/config.go
Allow GENEVE port to be set
Add test case
> Allow GENEVE port to be set

- .gitignore
- dist/images/.gitignore
- dist/yaml/.gitignore
> update various .gitignore files with runtime artifacts

- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
I have removed unnecessary volume mounts from these two pods. I had cleaned up the ovnkbue-db POD yaml longtime ago.
@dcbw @shettyg @pecameron PTAL
> cleanup ovnkube-master and ovnkbue-node yaml files

- dist/images/Dockerfile
- dist/images/Dockerfile.fedora
SDN-503 - Dockerfiles: verify that packages are installed
https://jira.coreos.com/browse/SDN-503
> Dockerfiles: verify that packages are installed

- dist/images/ovnkube.sh
> remove the stale ovn-northd control files

- dist/templates/ovnkube-node.yaml.j2
> rename ovn-node container to ovnkube-node for consistent naming

- dist/images/ovnkube.sh
> OVN NB and SB DB should log to their default logfiles

- go-controller/pkg/cluster/gateway_localnet.go
Before this change, code for generating iptables rules for services was
duplicated in `localnetAddService` and `localnetDeleteService`. This
change moves the duplicated code to the separate function
`localnetIptRules`.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> gateway: Generate iptables rules for services in a separate function

- dist/images/ovnkube.sh
The process_ready() function read's the process pid from the pidfile and
ensures that the pid is running. If the pidfile is not present, then it
keeps checking (through wait_for_event code) for the pidfile to show up.
However, there is a possibility that the process crashed and no pidfile
was written. Now, the above logic will keep trying for 400s and give up.
The status of the container will be Running but the process has died
within the first few seconds.
> exit early from the entrypoint script on error

- go-controller/cmd/ovnkube/ovnkube.go
> create the pidfile for ovnkube daemons early in the process startup

- dist/images/ovndb-vip.sh
- dist/images/ovnkube.sh
Fixes: 8ddd5fb1d1bd (ovnkube.sh: idempotently set endpoints)
> remove unnecessary deletion of endpoint before we apply the endpoint

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_windows.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/util.go
> cni/util: allow setting custom routes in pods

- go-controller/pkg/factory/factory.go
The Factory adds a single shared informer handler that dispatches
events to sub-handlers. Shared informers deliver an initial list
of objects to each handler when that handler is attached if the
informer is started (s.started==true). They do this by adding
the initial object list to a queue that the internal listener
representing each handler reads from a goroutine.
This means the initial object list might be delivered to the
factory's shared handler at any point after the creation
of the watch factory, including after subsequent handlers are
attached. This can cause duplicate object additions which
confuses testcases.
To resolve this, prevent the initial object list dispatch
logic by adding the factory's shared handler for each
object type before running that object type's shared …
> factory: add initial event handlers before syncing informer caches

- go-controller/vendor/github.com/coreos/go-iptables/iptables/iptables.go
- go-controller/vendor/vendor.json
govendor fetch https://github.com/coreos/go-iptables@=v0.4.3
> update the vendor for the go-iptables vendor code

- dist/images/Dockerfile
> Use a newer kubectl version for the centos image

- go-controller/pkg/util/util.go
@alexanderConstantinescu @squeed @girishmg @danwinship
> util: validate pod annotation

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_windows.go
- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
- go-controller/pkg/util/util.go
Simplify and consolidate policy code.
@squeed @girishmg @danwinship @alexanderConstantinescu @mccv1r0 @JacobTanenbaum
> policy: simplify and consolidate some code

- go-controller/pkg/config/config.go
- go-controller/pkg/ovn/ha_master.go
1) config.MasterHA.HA* -> config.MasterHA.*
2)
[MasterHA]
ha-*
changes to:
[MasterHA]
*
@girishmg @numansiddique @danwinship
> Reduce redundancy of HA related config option names

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
Hi
This is a bit of a miscellaneous PR. It contains fixes for:
* Panics 
* Logging 
* Errors
which could be refactored as to provide for better error handling.
It also contains some changes for line indentation which looked really awkward.
> Cleaning up error/logging/panic handling in different places

- go-controller/cmd/ovnkube/ovnkube.go
When the configuration file changes, exit. The configuration file is a
mounted configmap (ovnkube-config) so when it changes exit.
SDN-456 - OVN: use config file via ConfigMap rather than environment variables
https://jira.coreos.com/browse/SDN-456
> Notice change in configmap and exit.

- go-controller/pkg/cluster/node.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
This is a PR targetted at:
* being able to target cluster nodes using their DNS name. 
* improving the check on valid IP addresses for endpoint updates. 
@dcbw @squeed @girishmg
> Removing check on hostname and proper update of IP address

- go-controller/pkg/ovn/pods.go
> ovn: log how long addLogicalPort() takes

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cniserver_linux.go
- go-controller/pkg/cni/cniserver_windows.go
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types.go
> cni: actually return error messages on pod ADD failures

- dist/templates/ovnkube-db-vip.yaml.j2
- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
> remove openshift reference in ovnkube pods' labels

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/cluster/gateway_localnet_windows.go
- go-controller/pkg/cluster/gateway_shared_intf.go
- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/cluster/node.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/gateway-init.go
Move node gateway creation to master
Signed-off-by: Michael Cambria <mcambria@redhat.com>
> Move node gateway creation to master

- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/gateway-cleanup.go
A couple random fixes found from trawling through logs of our CI runs and code inspection.
@girishmg @mccv1r0 @danwinship @squeed
> A bunch of random fixes

- go-controller/pkg/cluster/node.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/ha_master.go
@dcbw @danwinship @squeed PTAL
> AddFilteredEndpointsHandler must take label selector like other handlers

- go-controller/Makefile
- go-controller/hack/lint.sh
> build: fix 'make lint' when GOPATH isn't explicitly set

- go-controller/pkg/ovn/master_test.go
the test case was passing config.GatewayModeLocal for the shared
gateway mode instead of config.GatewayModeShared.
> fix test associated with the shared gateway mode

- go-controller/pkg/config/utils.go
- go-controller/pkg/ovn/allocator/allocator.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/ovn.go
Pulls in changes to support multiple subnets and to support IPv6:
https://github.com/openshift/sdn/pull/66
> Sync SubnetAllocator from openshift/sdn

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
Fixes: c3def15ad986 ("Add multicast support.")
> Enable IGMP Querier only if a source IPv4 is available.

- dist/images/ovnkube.sh
> use ahostsv4 database to ensure we get IPv4 address always

- go-controller/pkg/config/config.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
> add a switch to flip on/off multicast support (is disabled by default)

- go-controller/pkg/cni/helper_linux.go
Settling IP addresses is done automatically by the CNI IPAM code.
Since ovn-kubernetes doesn't use that, this is an important step that
still needs to be done.  I observed pods starting and attempting to
use their IPv6 addresses too quickly without it.  We must leave time
for DAD (duplicate address detection) to complete.
I took this a step further and have disabled DAD completely if the
host has IPv6 configured (the right sysctl tunable exists).  I still
left the address settling in place, because it doesn't seem harmful
and maybe there are other reasons to still check this.
> Disable IPv6 DAD and ensure addresses are ready   

- go-controller/pkg/cluster/gateway_init.go
- go-controller/pkg/cluster/management-port.go
- go-controller/pkg/cluster/node.go
sdn-735 [ovn] less confusing gateway and management port wait messages
https://issues.redhat.com/browse/SDN-735
> Reduce logging while waiting for gateway and management port

- dist/images/ovnkube.sh
> Removes duplicate code setting ovn_db_host

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
- go-controller/pkg/ovn/master.go
Fixes #946
@dcbw @shettyg PTAL
> persist the mac address associated with br-nexthop OVS internal port

- go-controller/pkg/cluster/gateway_init_linux_test.go
- go-controller/pkg/cluster/gateway_localnet.go
Creates br-nexthop with the same MTU as br-int.
> pkg/cluster: set br-nexthop mtu

- go-controller/pkg/cluster/management-port.go
With 400+ odd nodes, the current MangementPortReady() function is not
scaling. The ovn-nbctl calls are timing out. When we have a way to find
out that the data path for the management port is ready by checking
for OpenFlow rules on the integration bridge we should make use of it.
> scale: ascertain management port readiness by checking OpenFlow rules

- go-controller/pkg/ovn/master_test.go
the shared gateway tests uses names and logical entities that are local
gateway mode kind, so fix it
> test: shared gateway tests should not use local gateway mode semantics

- go-controller/pkg/ovn/ovn.go
If we failed to create a management switch port on the master, then
we never retry its creation in node's UpdateFunc. So, fix it.
> handle failed management logical_switch_port creation

- go-controller/pkg/ovn/common.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
> ovn: remove 'func (oc *Controller)' from functions that don't need it

- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
Whenever a pod is added/removed from a namespace 'ns', if multicast is
enabled in the namespace, also update the associated Port_Group
mcastPortGroup-<ns> otherwise multicast traffic will not be allowed from
the pod.
Whenever a namespace is created with existing pods, add the pods to the
default multicast deny policy.
Reported-at: https://bugzilla.redhat.com/1772579
Fixes: c3def15ad986 ("Add multicast support.")
> Fix multicast Port_Group update at pod creation/deletion.

- go-controller/pkg/ovn/policy_common.go
> trivial: use GetNodeWellKnownAddresses() to arrive at node mgmt port IP

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_common.go
- go-controller/pkg/ovn/policy_old.go
- go-controller/pkg/ovn/policy_old_test.go
- go-controller/pkg/ovn/policy_test.go
Another random grab bag of cleanups.
@danwinship @girishmg @JacobTanenbaum @pecameron @alexanderConstantinescu @mccv1r0
> Yet more cleanups

- dist/images/daemonset.sh
This is just a quick fix for a bug I discovered while wrangling CI stuff.
> Ensure j2 does not fail to run in daemonset.sh if installed globally

- .github/workflow-templates/test.yml
- .github/workflows/test_generated.yml
> Also run CI for pull requests

- go-controller/pkg/cni/cni.go
- go-controller/pkg/ovn/ovn.go
@danwinship @girishmg @mccv1r0 @alexanderConstantinescu @JacobTanenbaum @pecameron @juanluisvaladas
> CNI logging and timeout fixes, plus node handler locking fix

- contrib/kind.sh
- dist/ansible/hosts
- dist/images/daemonset.sh
- dist/templates/ovnkube-master.yaml.j2
> ci: bump master loglevel to 5

- dist/images/daemonset.sh
Rather than use sed to modify templates, actually render them with
Jinja2.
> J2 render all templates

- go-controller/pkg/cluster/node.go
- go-controller/pkg/cni/cni.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/util/util.go
> Remove the compat annotation code for OvnPodAnnotationLegacyName and OvnHostSubnetLegacy

- dist/images/Dockerfile.fedora
> Downgrade OVN and see if CI passes

- dist/images/ovndb-raft-functions
> use the macros defined to work with pre-split and post-split OVN

- go-controller/pkg/ovn/policy.go
Address sets were being deleted before the port group. The port group
contained an ACL which referenced the address set. This would cause OVN
controller to issue:
2020-02-17T16:31:09.160Z|00032|lflow|WARN|error parsing match "!ct.new
&& ct.est && !ct.rpl && ct_label.blocked == 0 && (ip4.src ==
{$a2376695646506571724, $a6566950664295833471} && outport ==
@a5584531700272134285)": Syntax error at `$a6566950664295833471'
expecting address set name.
With this patch address set is deleted after the associated ACL in the
port group is removed.
See https://github.com/ovn-org/ovn/issues/35
> Fix delete order for network policy

- go-controller/pkg/ovn/policy.go
when we create a network policy for ingress (or egress) that contains
only ipBlock fields and nothing else, we end up creating address_sets.
for example: say we have 3 ingress rules and each rule only captures the
ipBlock and nothing else, we end up creating 3 address_sets (since 3
ingress rules) and they don't have any IP addresses. this also results
in creation of 6 ACL - 3 ACLs for the ipBlock CIDR and 3 ACLs with
empty address_set.
> create address_sets only when required for network policy rules

- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
> miscellaneous cleanups to ovnkube.sh and yaml templates

- dist/images/ovndb-raft-functions
- dist/images/ovnkube.sh
> use ${ovn_kubernetes_namespace} variable instead of 'ovn-kubernetes'

- go-controller/pkg/ovn/policy.go
> build the expected network policies map correctly

- dist/images/ovnkube.sh
we added support for using a non-default ovn_encap_port of 6081.
however, we didn't add support for the same in ovnkube.sh and exporting
the value through environment variable in ovnkube-node container
> support specifying custom ovn_encap_port in ovnkube.sh

- dist/templates/ovnkube-node.yaml.j2
- go-controller/cmd/ovn-kube-util/app/readiness-probe.go
> add readiness probe to ovnkube-node container

- dist/images/ovndb-raft-functions
> [RAFT] add passive connection method with inactivity probe set to 0

- .github/workflow-templates/test.yml.erb
- .github/workflows/test_generated.yml
- contrib/kind.sh
- contrib/kind.yaml
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/policy_common.go
> Add SCTP support for network policy

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/util/net_linux.go
@dcbw @danwinship @russellb PTAL
> convert all the ip-{link|addr|route|neigh} calls to netlink

- go-controller/pkg/ovn/master.go
in syncGatewayLogicalNetwork() we don't handle the case where the
deployer might have disabled the NodePort for the node by updating the
corresponding node annotation.
we handle other l3 gateway related changes except for nodeport change
@dcbw PTAL
> remove tcp/udp load balancers from l3 gateway on disabling NodePort

- .gitignore
> Update gitignore file to avoid tracking GoLand IDE temp files

- dist/images/ovndb-raft-functions
- dist/images/ovnkube.sh
> remove calls to sleep in various functions in ovnkube.sh

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
see: https://groups.google.com/forum/#!topic/ovn-kubernetes/Q9E5FMXC2GM
> rename br-nexthop interface to ovn-k8s-gw0

- .github/workflow-templates/test.yml.erb
- .github/workflows/test_generated.yml
- go-controller/hack/test-go.sh
This is an alternative to #1146 that uses the coveralls github action, in an attempt to get PR gating/comments on coverage.
> build: coverage support (option 2)

- go-controller/pkg/node/management-port.go
Fixes: 4c22af99998f (cluster: use node annotator and startup waiter)
@dcbw FYI
> return err instead of nil

- go-controller/cmd/ovn-kube-util/app/readiness-probe.go
> NIT: fix the error message in the OVN DB readiness probe

- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
This reverts commit 591245645e8313dd458525bb8d2b2c952ff230ce.
@dcbw @danwinship @dceara Fixes Issue #1190
> Revert "ovn: Fix default deny ACLs."

- dist/images/Dockerfile.fedora.dev
- dist/images/Makefile
> Remove hardcoded kernel version

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/ovn.go
> don't pass around stopChan as argument when it's available from receiver

- dist/templates/ovnkube-db-raft.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
> Minor fixes in the template yaml files

- dist/templates/ovnkube-monitor.yaml.j2
@dcbw @danwinship @squeed PTAL
> add prometheus service monitor for the ovnkube-db metrics

- README.md
suggest to remote the master taint
> Fix README - Removed the part that suggest to remove the master taint

- dist/images/daemonset.sh
- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
> apply bash style formatting for better readability and maintainability

- dist/images/ovnkube.sh
- currently the variable is named with _test suffix, as in,
ovn_nbdb_test. change it to ovn_nbdb_conn
- add similar variable for SB DB
- use the above two variables everywhere in the script
> nit: change ovsdb server connection method variable name

- dist/images/ovndb-raft-functions.sh
> ovnkube.sh: Adding iptable rules to open up the OVN NB/SB DB raft ports

- README_MANUAL.md
- dist/images/ovnkube.sh
- docs/INSTALL.OPENSHIFT.md
- docs/INSTALL.SSL.md
- docs/config.md
- docs/ha.md
- docs/ovn_k8s.conf.5
- docs/ovnkube.1
- etc/ovn_k8s.conf
- go-controller/README.md
- go-controller/etc/ovn_k8s.conf
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
And add explicit tests for the old format (tcp://1.2.3.4:6641)
> config: switch tests/docs normal DB address format (eg tcp:1.2.3.4:6641)

- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/util/gateway-init_test.go
- go-controller/pkg/util/subnet_annotations_test.go
This just adds new unit tests...
@dcbw
> some unit tests

- contrib/kind.sh
Ensure pods are all up before we declare install successful
> KIND: Adds check to make sure pods are up

- go-controller/pkg/config/utils.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/util/gateway-cleanup.go
Fixes: 789b004e776c7(Adds SCTP protocol support to services)
@trozet @dcbw PTAL
> gateway: cleanup some sctp related changes

- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_windows.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/gateway-cleanup.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/util.go
Also change returned value variable names to make it clear they aren't IPs, but address/cidrs.
> util: add Hybrid Overlay IP to GetNodeWellKnownAddresses()

- docs/ci.md
> docs: Add documentation for how to build CI tests and run locally.

- go-controller/pkg/ovn/policy.go
Ensure the policy is set correctly with proper locking before we start
the watchers to update the policy attributes.
> Fixes add network policy locking

- README.md
- dist/images/.gitignore
This commit Fix a typo in the README, also add a new binary in the git ignore
and last add a requested package by the ovs to run.
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
> Small nit changes

- contrib/ingress/mandatory.yaml
- contrib/ingress/service-nodeport.yaml
- contrib/kind-ha.yaml
- contrib/kind.sh
- contrib/kind.yaml
Store the yaml files and create ingress according to new KIND docs:
https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
> Cache and fix KIND ingress

- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
> ovnkube.sh: Removing the stderr redirection to /dev/null.

- go-controller/pkg/testing/exec.go
Failing a ginkgo.Expect() from inside the Exec wrapper can result in a panic in some far-flung part of the code, which if it doesn't get caught correctly will result in a useless test failure.
Instead, just check the expectation the old-fashioned way, and if it fails, call klog.Fatal(), which will immediately exit the test with the relevant error message.
@trozet I know this is your favorite failure mode...
cc @dcbw @girishmg
> testing: don't use Expect() from the fake exec wrapper

- dist/images/ovndb-raft-functions.sh
- dist/images/ovnkube.sh
> gracefully terminate ovsdb-server on receiving SIGTERM

- dist/images/ovnkube.sh
> ovnkube.sh : Handling pipe between two commands properly.

- test/scripts/e2e-kind.sh
got annoyed while trying to figure out what Tim changed in #1225 
Feel free to suggest improvements to the echo/sed/tr magic
Also, any info on the "???"s?
cc @dave-tucker @as-com
> test: clarify skipped tests

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
monitoring the OVN DB size is very crucial since it has direct
correlation with the number of logical resources and flows in the
cluster and the effect of the size on ovn-controller since it downloads
this DB
> export the OVN {SB|NB}_DB size as a prometheus metric

- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/hybrid-overlay/pkg/controller/node_windows.go
- go-controller/hybrid-overlay/pkg/types/types.go
- go-controller/hybrid-overlay/pkg/util/util.go
- go-controller/pkg/cni/cni.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/node/node.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/util.go
This allows pods in a namespace with an appropiate notation
to route traffic to an external GW over VXLAN.
> Add external gw feature to hybrid overlay

- .github/workflows/test.yml
Signed-off-by: Andrew Sun <asun@redhat.com>
This should make caching go a little faster and consume less space. See: https://github.com/actions/cache/releases/tag/v2.0.0
> Upgrade cache action to v2

- contrib/README.md
- docs/kind.md
Provided high level README for deploying OVN kubernetes with KIND
> README for KIND deployment

- test/e2e/e2e_test.go
- This commit adds e2e that will create an initial container that
emulates an external gateway and then validates e2e connectivity.
- The e2e framework namespace is then updated with new annotations
and sets up a new container emulating a second gateway which is
then validated for e2e connectivity.
This test can be tested locally by:
$ popd contrib
$ OVN_HYBRID_OVERLAY_ENABLE=true ./kind.sh
From a kubernetes directory run: 
$ kubetest --provider=local --deployment=kind --kind-cluster-name=ovn --test
Add CI that tests updating gateway annotations
> Add CI that tests updating gateway annotations

- test/e2e/e2e_test.go
This batches kubectl calls so that both fields are annotated at the same
time. This will avoid us seeing log lines where one or the other
annotation may be missing in CI.
I also couldn't help myself cleaning up the test code to use const and
var blocks so it makes the tests easier to read.
> test: Set annotations in a single kubectl call

- test/e2e/e2e_test.go
- Increased the retries for getPodAddress() due to a an observed
failure in CI.
This commit is a result of seeing #1385 fail due to  getPodAddress() timing out before the pod IP is retrieved. It adds an additional 15 seconds for pod IP discovery.
By running CI or kubetest locally
Increased the retries for getPodAddress() due to a an observed failure in CI
> Increase the retry timer for CI pod ip discovery in e2e

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- This commit will validate that external gateway annotations
are valid IP addresses (is also v6 compatable) and catch
whitespace chars entered by the user
- Adding whitespace chars or invalid IP addresses (e2e tests to come)
kubectl annotate namespace f5 k8s.ovn.org/hybrid-overlay-external-gw=1234
kubectl annotate namespace f5 k8s.ovn.org/hybrid-overlay-vtep=172.17.0.5\n
> Validate gateway and vtep IP address in hybrid overlay

- go-controller/pkg/util/kube.go
- go-controller/pkg/util/kube_test.go
Adds tests for existing functions defined in pkg/util/kube.go
Code Refactor is not part of scope and any refactor suggestions (if any) will be done in a new PR
> UT: added unit tests for functions in pkg/util/kube.go

- go-controller/pkg/ovn/ovn.go
Say we failed in addNode() for worker node node1. Now, it doesn't get
cached in oc.logicalSwitchCache. We don't try to call addNode() again
on NodeUpdates if addNode() failed in NodeAdd.
With this state for node1, all the pods that gets scheduled on that node
will not proceed since the addLogicalSwitchPort() continues to wait for
the node to appear in logicalSwitchCache. It times out with the error
below
------8<---------8<-----
timed out waiting for logical switch "node1" subnet: timed out waiting\
for the condition
------8<---------8<-----
@ovn-org/ovn-kubernetes-committers PTAL as it is a serious issue. Thanks.
> retry addNode() again in NodeUpdate after it failed in NodeAdd handler

- test/e2e/e2e_test.go
- kind v8 uses a new network bridge named kind rather than the default bridge
kind v8 uses a new docker network which places the CI nodes onto a different
network/subnet then just using default `run` values. This makes the e2e tests
compatible with future kind version bumps.
Can be verified with the following:
```
curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
./kind.sh -ho …
```
> Add support for kind v8 to e2e CI

- go-controller/pkg/informer/informer.go
Just caught this while debugging :)
> informer: Remove debug statements

- go-controller/pkg/util/net_linux.go
forgot to return after an error for conntrack deletion
> fixup of conntrack delete

- .github/workflows/docker.yml
- .github/workflows/test.yml
A couple of CI fixes to help reduce build and queue times:
1. Split the docker image build out to it's own workflow. It should only trigger if the Dockerfile is changed
2. Remove the `free up disk space` step from the build job as we shouldn't need it for a standard go build and it saves 2 mins each run
3. Make e2e tests depend on having a green build job as suggested in #1401 
> ci: Reduce Queue Times Further

- dist/images/ovnkube.sh
> ovnkube.sh : Minor Fix

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
updates to OVN DB raft metrics
1. We already have a metric to track the progress of ovn-northd process,
we update an option in NB_Global table and check for this option in
SB_Global. If the option has been propagated, then ovn-northd is not
stalled. We can extend this furthermore to check if the OVN DB
followers are in-line or behind their leaders. On each of the NB DB
we need to export this timestamp and similarly on each of the SB DB.
2. The ovnkube_db_raft_cluster_leader metric can be inferred from
ovnkube_db_raft_cluster_server_role, so no need for the former
metric.
3. The ovnkube_db_raft_log_entry_index metric is same as
ovnkube_db_raft_cluster_log_index_next, so no need for the former
metric.
@squeed FYI
@ovn-org/ovn-kubernetes-committers  PTAL
> updates to OVN DB raft metrics

- go-controller/hybrid-overlay/pkg/controller/node.go
> hybrid-overlay: fix check of pod object validity

- dist/images/ovnkube.sh
Co-authored-by: Yun Zhou <yunz@nvidia.com>
> gracefully shutdown ovn-northd and ovn-nbctld daemons

- go-controller/pkg/util/net_unit_test.go
- go-controller/pkg/util/ovs_unit_test.go
> unit tests for functions in util/net.go file

- go-controller/pkg/ovn/master_test.go
there were certain test cases in master_test.go that weren't enabled
for shared gateway mode, but we were adding fake commands related to
building shared gateway logical topology by explicitly overwriting
config.Gateway.Mode to config.GatewayModeShared. this causes confusion
and this commit removes that code.
Note: we already have tests to cover those set of commands.
> test shared gateway related logical topology only for shared gw tests

- go-controller/pkg/util/util_unit_test.go
The PR adds unit tests (code  refactor is not the scope for this PR) for most of the functions defined in the following files:
- pkg/util/node_annotations.go [Dropped per review comment that tests are duplicate]
- pkg/util/pod_annotation.go[Dropped per review comment that tests are duplicate]
-pkg/util/subnet_annotations.go[Dropped per review comment that tests are duplicate]
-pkg/util/util.go
This PR is rebased on top of https://github.com/ovn-org/ovn-kubernetes/pull/1371. The files relevant to this particular PR that need review are in the commit https://github.com/ovn-org/ovn-kubernetes/pull/1382/commits/702946ed8f1a99bf98f1670572f8cec7aa75c083?file-filters%5B%5D=
- pkg/util/node_annotations_unit_test.go …
> unit tests added for the util.go file in pkg/util directory

- go-controller/pkg/util/ovs_test.go
> Clean tmp dir after ovs-test

- go-controller/pkg/ovn/pods.go
Don't mark the pod IP as being available until after removing the port
from the switch, or there's a race condition between deleting and
adding pods.
Fixes #1483
> ovn: fix order of operations in logical port deletion

- go-controller/pkg/node/node.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/kube.go
- go-controller/pkg/util/kube_test.go
- go-controller/pkg/util/util.go
Some miscellaneous dual-stack bits.
~Includes a much simpler dual-stack-ification of gateway_localnet.go than #1326~
cc @aojea @gvbalaji
> Misc dual-stack bits

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_localnet_windows.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_shared_intf_linux.go
- go-controller/pkg/node/gateway_shared_intf_windows.go
- go-controller/pkg/node/node.go
- go-controller/pkg/util/iptables.go
Dual-stack setup for both shared and local gateway modes... needed a bunch of rewriting to deal with the externalIP-related changes
@dcbw @gvbalaji @alexanderConstantinescu
> node: dual-stack gateway setup

- go-controller/hybrid-overlay/pkg/controller/master.go
Method handleOverlayPort is changed to handle multiple subnets
> Support for dual stack for hybrid overlay port

- go-controller/pkg/informer/informer_test.go
- go-controller/pkg/ovn/pods_test.go
Some tests depends that an event is processed by the handler, and some times this takes longer than expected failing the test.
We can poll periodically during a small amount of time to avoid this.
Test job pass
> Deflake informer and ovn/pods tests

- go-controller/vendor/modules.txt
when trying to compile using go 1.14.5 received an error that golang vendor
was inconsistent. Run go mod vendor to fix inconsistency
the error is below 
```
+ binbase=ovnkube
+ go build -v -mod vendor -gcflags '' -ldflags '-B 0xca595fc9eb33d9fb12f5f2521317fd04023d0564                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.Commit=a8950c469aca39c8e2926d153d939a459b07d578                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.Branch=goMod                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.BuildUser=jtanenba                 -X github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.BuildDate=2020-07-15' -o /home/jtanenba/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/_output/go/bin/ovnkube ./cmd/ovnkube …
```
> when trying to compile with golang version 1.14.5 errors

- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
> Set MTU for br-ext hybrid overlay bridge

- contrib/kind.sh
- test/scripts/install-kind.sh
kind latest versions contains fixes that will help to
reduce flakiness.
Last stable version uses its own docker network.
This will simplify IPv6 and Dual stack testing too
CI should work :)
> bump kind version

- go-controller/pkg/ovn/pods.go
When pods are assigned IPs and the annotation fails for some reason,
the release was not happening because of incorrect variable scoping.
> Release IPs when pod annotation fails

- .github/workflows/test.yml
** Make sure all your commits include a signature generated with `git commit -s` **
we were reporting only the xml results, that's hard to parse.
Reporting all the tests results in html is much better
> report tests results when job finish

- go-controller/pkg/ovn/ovn.go
Say, we fail to add a logical switch port for a pod that needs OVN
network and gets scheduled on a node. We then fail to annotate the pod
with IP address information. On the cnishim side, it waits for about 2
minutes and timeouts waiting on pod annotation.
There are so many reasons why adding logical port failed. Today, for
that failed pod the only info we see either in pod's description or
pod's events is:
```
Warning  FailedCreatePodSandBox  2m48s (x194 over 88m)  kubelet, node1
(combined from similar events): Failed to create pod sandbox: rpc error:
code = Unknown desc = failed to set up sandbox container
"725605bae050f124c29cbccd603207bcbdf26e097185186a7d4ab0b4b48a8fdc"
network for pod "web": networkPlugin cni failed to set up pod "web"
network: [default/web:ovn-kubernetes]: error …
```
> post an warning event for pod when we fail to add a logical port for it

- go-controller/cmd/ovn-kube-util/app/ovn-db-exporter.go
Included a check for empty output when retrieving e2e_timestamp value
in the ovnE2eTimeStampUpdater().
> Obtaining e2e_timestamp metric value using the unix socket.

- go-controller/pkg/ovn/gress_policy.go
K8s network policy allows to specify the protocol, but if the port
is not specified, it is taken to mean all the ports for that
protocol
"If specified, the port on the given protocol.  This can either be a
numerical or named port on a pod.  If this field is not provided, this
matches all port names and numbers. If present, only traffic on the
specified protocol AND port will be matched.
+optional"
> Port need not be specified for a protocol in a network policy

- dist/images/Dockerfile.fedora
@trozet @Billy99 @numansiddique
> Update to ovn-20.06.1-6.fc31 	

- go-controller/pkg/util/ovs_unit_test.go
Signed-off-by: sheetalsingala <ssingala@redhat.com>
Adds unit tests for RunIP and RunOVSDpctl functions present in util/ovs.go
> Adds unit tests for RunIP and RunOVSDpctl functions present in util/ovs.go

- go-controller/pkg/ovn/ovn.go
EgressFirewall retrieves namespaces from the node Add event, which
is called for all existing nodes at startup. But since WatchNodes()
was started first no namespaces yet exist in the cache and each
namespace request times out.
This is a more general issue than just EgressFirewall; we need to figure out how to make our watcher Add handlers not block on cached things and just do that work from the handler they are waiting on. For example, perhaps we don't need to wait in the EgressFirewall node add handler, but if the namespace doesn't exist in the cache just ignore that and assume the Namespace Add handler will do the required changes.
@JacobTanenbaum @trozet
> master: WatchNamespaces must be started first due to EgressFirewall

- go-controller/pkg/ovn/master.go
During node addition if setting annotations fails because API server
is down, currently we don't have a mechanism to retry. We add the node
to a datastore for failed nodes. But the node will only be retried
in the updateFunc when it truly is updated. Barring any updates, the node
will never get an annotation. This retry will only account for occasional
blips in communication to the API server. Any outage > 1s will result in a
failure annotating the node.
> Add a retry mechanism for setting node annotations

- test/scripts/e2e-cp.sh
Get rid of the dependencies on Kubernetes and allows
to run directly the tests in its own folder.
> e2e control-plane test improvements

- dist/yaml/.gitignore
> Add generated yaml files to .gitignore file

- go-controller/pkg/util/nicstobridge.go
- go-controller/pkg/util/nicstobridge_test.go
- go-controller/pkg/util/ovs_unit_test.go
This PR is about adding unit tests for the functions in the pkg/util/nicstobridge.go file
The files that are relevant to the current PR for review are:
- go-controller/pkg/util/nicstobridge.go (this file was modified to use the netLinkOps interface methods to make UT easy )
- go-controller/pkg/util/nicstobridge_test.go
- go-controller/pkg/util/ovs_unit_test.go (added a struct defintion to make easy mocking/adding string parameters)
Pull this PR into your workspace
Navigate to go-controller/pkg/util directory
execute below commands
go test -coverprofile cp.out
go tool cover -html=cp.out
select file nicstobridge.go from drop down to verify coverage
unit …
> unit tests for the functions in the pkg/util/nicstobridge.go file

- test/scripts/e2e-cp.sh
CI is broken because of this error.
/cc @aojea 
> Fixing EOF error in e2e-cp script

- go-controller/pkg/ovn/loadbalancer.go
The current scheme for naming an ACL includes the IP Address. For IPv6,
the name can exceed the max length of 63 characters.
> ACL Name is limited to 63 chars in ovn-nbctl but exceeded in IPv6

- go-controller/pkg/ovn/egressfirewall.go
We should be able to avoid waiting for namespace lock on the delete and
just go ahead and delete things if the namespace does not exist anymore.
> Remove waitForNamespaceLocked on EgressFW Delete

- go-controller/pkg/informer/informer.go
- go-controller/pkg/informer/informer_test.go
The first delete request on an object with finalizers sets
a value for the metadata.deletionTimestamp field but does not
delete it.
Our informer implementation, on updates, was checking for the
DeletionTimestamp field in the old object instead of the new object,
thus we were processing events for objects that are set for deletion.
After checking the kubernetes code base, I've have observed that
objects can be set for deletion on Add events, and controllers
are filtering on add events too.
We should not process any object that is set for deletion, i.e. that
has the DeletionTimestamp field != nil
> don't process objects set for deletion

- contrib/kind.sh
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/helper_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/net_unit_test.go
- go-controller/pkg/util/nicstobridge.go
Changes to shared gateway mode to support IPv6 Only and Dual-stack. Addresses issue #1141.
> Update shared gateway to support IPv6/Dualstack

- test/e2e/e2e_test.go
- commit adds a test for the non-vxlan external gateway.
- test will setup containers acting as gateways.
- the gateway address is eth0 in the container and
lo0 acts as a remote network the pod will reach
since the feature drains all traffic to the gw.
- the feature requires shared gateway mode and the
test verifies the job infra can support the test,
if it does not the test is skipped.
commit adds an e2e test for the non-vxlan external gateway
Can be verified with the following:
```
curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
curl -Lo ./kind …
```
> Add e2e for non-vxlan external gateway feature

- go-controller/pkg/cni/ovs_unit_test.go
Signed-off-by: sheetalsingala <ssingala@redhat.com>
> Add unit tests for functions in cni/ovs.go

- test/scripts/e2e-kind.sh
This reverts commit 24f2e9e40b5d216e0ece0fc5fed8a7e3507c926b.
> Revert "Skip kube proxy connection reset test"

- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/gress_policy_test.go
- go-controller/pkg/ovn/policy.go
- test/scripts/e2e-kind.sh
our current implementation of Ipblock is incorrect. creating a deny rule for the
except blocks will not allow ips that overlap another IPblock to be allowed.
I changed this so that we only create one rule per ipBlock
so if you have one policy that says
```
- from:
- ipBlock:
cidr: 10.0.0.0/8
except:
- 10.0.1.0/24
```
and another that says
```
- from:
- ipBlock:
cidr: 10.0.0.0/8
```
it will translate two acls that are
```
match=ip4.src == 10.0.0.0/8 && ip4.src !={10.0.1.0/24}
match=ip4.src == 10.0.0.0/8
```
the first rule will not catch a packet from 10.0.1.0 it will
cascade to the second ACL and correctly be allowed. If the except
is not overlapping an additional range it will be denied by the
default deny ACL
This should resolve https://github.com/ovn-org/ovn-kubernetes/issues/845 …
> fix ipBlock except for network policy

- test/scripts/install-kind.sh
pin kind to latest stable release
> bump kind to 0.9.0

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/ovn.go
Change egressfirewall to use logical_router_policies on the
ovn_cluster_router as oppsed to using ACLs on each nodes join
switches.
This changes optimizes the generation of egressfirewall policies
because we only have to create one object and put it in one place
the ovn_cluster_router applies to all namespaces so we only need
to attach the policy there.
because the single router applies to all namespaces the test
"correctly adds an existing egressFirewall to a new node" is no longer needed
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1879908
because of https://github.com/ovn-org/ovn-kubernetes/pull/1692 egress traffic does not route through the nodes join switch and the ovn_cluster_router provides a more efficient way to accomplish …
> make egressfirewall use logical_router_policies

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/util/net_linux.go
Bare metal OCP adds temporary IPs to the primary interface for use with external load-balancing. These should be ignored when determining the primary node IP.
I was going to fix this by implementing #1690 but there's currently a messy tangle of different ways IPs are detected (`util.GetNodePrimaryIP`, `getDefaultIfAddr`, and `getNetworkInterfaceIPAddresses` each do something different and are each only used in one place) and it needs more rethinking than I wanted to do right now, so I just fixed this one method to be better.
> node: ignore "deprecated" IPv6 IPs when determining primary IP

- go-controller/pkg/ovn/gateway_init.go
The previous code assumed that the host network pod backend to a service
would always be in the same subnet as the host accessing the service,
which is not always the case. Additionally, the code used the mask on
the host interface to determine the host subnet, which is not correct
for IPv6. IPv6 addresses may be assigned with /128 prefixes.
Since we really just care about non-pod subnet traffic from mp0 hitting
this policy and going out DGP, we can just inverse the match to match
not on pod subnet.
> Fixes inter node DGP policy for local gw mode

- go-controller/pkg/ovn/egressgw.go
Pods configured with egress gws were unable to reach other pods in other
subnets, via service or otherwise. This is because the lr-policy for
routing traffic to GR was not specific enough. This patch adds criteria
for matching not cluster subnet, so only external traffic is forwarded
to GR.
> Fixes lr-policy for egress gw

- go-controller/pkg/ovn/gateway_init.go
northd may take a short time to create the cluster router datapath
in the southbound. Don't assume it's immediate.
```
E0901 11:21:05.961945       1 master.go:215] Failed to setup master (failed to create a MAC_Binding entry of (169.254.0.1, 0a:58:a9:fe:00:01) for distributed router port rtos-node_local_switch stderr: "ovn-sbctl: datapath=: argument does not end in \"=\" followed by a value.\n", error: OVN command '/usr/bin/ovn-sbctl --private-key=/ovn-cert/tls.key --certificate=/ovn-cert/tls.crt --bootstrap-ca-cert=/ovn-ca/ca-bundle.crt --db=ssl:10.0.0.3:9642,ssl:10.0.0.4:9642,ssl:10.0.0.5:9642 --timeout=15 create mac_binding datapath= ip=169.254.0.1 logical_port=rtos-node_local_switch mac="0a:58:a9:fe:00:01"' failed: exit status 1)
panic: failed to create a MAC_Binding entry of …
```
> master: wait a bit for cluster router datapath to be created

- go-controller/pkg/ovn/pods.go
- test/e2e/e2e_test.go
- test/e2e/go.mod
- test/e2e/utils_test.go
This is to allow a graceful migration from HO
Fixes #1632
> Give preference to routingExternalGWs annotation over hybrid overlay

- go-controller/hack/test-go.sh
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/hybrid-overlay/pkg/controller/master.go
- go-controller/hybrid-overlay/pkg/controller/master_test.go
- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/pkg/informer/informer.go
- go-controller/pkg/node/node.go
- go-controller/pkg/ovn/master.go
This PR fixes the flaky tests in the Hybrid Overlay Master Test Suite.
This required 3 seperate issue to be fixed first.
1. When test cases are compiled, the arguments provided to them via the
testrun function do not get embedded in the binary. Therefore we lose
verbose output, test reporting etc... This commit fixes the test
script so all tests are provided with the correct options and
have uniform output.
2. The `informer` package won't process updates under test conditions when the informers have been started. This is due to a check in to ensure the objects K8s revision number has incremented - that revision number isn't implemented in the fakeClient. Rather than implement this, I added a condition to detect when being run under test and …
> Fix test flakes in Hybrid Overlay Master Test Suite

- .github/workflows/test_periodic.yml
update the periodic job with the new changes on the e2e testing
- new ha configuration
- kubernetes 1.19 version
- new go version
> Update periodic Job

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/gateway.go
- have handled few typos in comments and error messages
- minor changes to getClusterSubnetsExclusion() and  addLogicalRouterPolicyToClusterRouter()
@JacobTanenbaum FYI-
> minor fixes in egress firewall code

- go-controller/pkg/ovn/loadbalancer.go
The generateACLName function was including backslash escapes for the ACL
name for use in OVN commands that have trouble with literal ":". That
was causing a mismatch when services were syncing because the name
actually returned from an OVN command does not include any backslashes
so the names would not match.
> Fix service sync reject ACL name matching

- docs/ovs_offload.md
Update the kernel and ovs version for OVS hardware offload support
> update ovs_offload doc with supported kernel and ovs

- go-controller/pkg/cni/bandwidth_test.go
Signed-off-by: sheetalsingala <ssingala@redhat.com>
Add unit tests for functions in cni/bandwidth.go
> Add unit tests for functions in cni/bandwidth.go

- go-controller/pkg/util/go_ovn_test.go
Fixes incorrect import of mock packages that has broken the build
None
> util: Fix incorrect mock import

- docs/mocks-ut-faq.md
This PR adds documentation that explains how mocks for unit tests are organized and generated.
> Closes #1619: write up to explain mocks organization and generation

- go-controller/pkg/metrics/ovs.go
> Adding metrics for geneve tunnel interface

- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
> Binding the ovn-k8s & ovn & ovs metrics endpoint to the k8s node IP

- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/ovn.go
- test/e2e/e2e_test.go
This patch adds an e2e test with several steps testing the functionality of egress IP for OVN-Kubernetes. 
> Add e2e test for egress IP

- test/e2e/e2e_test.go
- this commit validates pods can reach a network running in a container's looback via an external gateway running on eth0 of the container without any tunnel encap. The traffic will get proxied through an annotated pod in the default namespace. This test requires the infa to have shared gateway mode to be enabled.
- modified the createGenericPod() function to take a namespace as a parameter  since this test introduced the need for creating pods in the default namespace.
Add e2e testing for the pod gateway feature
verify with the following:
``` …
```
> Add e2e for the pod gateway feature

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/endpoints.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/gateway_cleanup.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/loadbalancer.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/util.go
This PR does three things: 
- Commit `Cleanup egress code` cleans up some of the left overs from the last egress IP PR:  https://github.com/ovn-org/ovn-kubernetes/pull/1677 by re-structuring the code and addressing https://github.com/ovn-org/ovn-kubernetes/pull/1484#discussion_r462401005 / https://github.com/ovn-org/ovn-kubernetes/pull/1668#discussion_r507677137 / https://github.com/ovn-org/ovn-kubernetes/pull/1668#discussion_r507678581
- Commit `Unify retrieval of join GR IP addresses` unifies access to the gateway router IPs by using the new method `util.GetNodeGatewayRouterIPs`
- Commit `Move OVN prefix constants to util package` unifies access to the constants across the code base, something seen while writing `Unify retrieval of join GR IP …
> Miscellaneous cleanups and unification 

- go-controller/Makefile
- go-controller/hack/test-go.sh
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/testing/mock_lsp.go
- go-controller/pkg/testing/mock_ovn.go
A month ago we enabled and then quickly after disabled the race detector for PRs, we created the issue: https://github.com/ovn-org/ovn-kubernetes/issues/1550 to track the reinstatement. This PR re-introduces the race detector with two additional prerequisites for that to work.
1. Now that PR https://github.com/ovn-org/ovn-kubernetes/pull/1567 merged and fixed a bunch of races in the master egress IP code, we can simply disable the race detector for the node egress IP tests, due to: https://github.com/ovn-org/ovn-kubernetes/issues/1549 which will probably never be resolved. Egress IP in local gateway mode will probably never be executed anyway, so I think it's fine to disable the race detector for that
2. There are race failures in `pod_test.go` …
> Enable race detector for unit testing 

- go-controller/pkg/node/gateway_shared_intf.go
One can selectively enable NodePort on nodes in K8s cluster. This is
so that OVN control plane can scale well in large cluster. For example:
If you have 1000 node cluster, then you may not want to enable Load
Balancers on all of the 1000 nodes.
We only enable NodePort on few 10s of nodes that form the control plane
services nodes. The rest of the 990 nodes we don’t want it to be a
forwarding or routing entity for these services.
Irrespective of whether NodePort is enabled or not, we still need the
default OpenFlow rules on the host OVS bridge to connection track the
traffic comming in from the OVN logical topology (North-South).
Fixes: 3606ee31259b (Modifies local gateway mode functionality)
@trozet can you PTAL?
> gw: add default connection tracking rules even when NodePort is disabled

- dist/images/Dockerfile
Fix the arm build by changing the dpdk rpm url from arm
None
make centos (on arm)
> Fix arm build

- dist/images/Dockerfile.fedora
All recent builds are broken due to:
```
Complete!
42 files removed
Removing intermediate container e618b9869961
---> 075efe1585e2
Step 5/21 : RUN dnf install -y --enablerepo=updates-testing --best --advisory=FEDORA-2020-6c71d0012d "ovn >= 20.09.0-1" || exit 1
---> Running in 54b6ec212e35
Fedora 32 openh264 (From Cisco) - x86_64        9.4 kB/s | 2.5 kB     00:00    
Fedora Modular 32 - x86_64                      4.0 MB/s | 4.9 MB     00:01    
Fedora Modular 32 - x86_64 - Updates            3.5 MB/s | 3.9 MB     00:01    
Fedora 32 - x86_64 - Test Updates               723 kB/s |  12 MB     00:16    
Fedora 32 - x86_64 - Updates                     21 MB/s |  27 MB     00:01    
Fedora 32 - x86_64                               16 MB/s |  70 MB     00:04    
No security updates for …
```
> Bump Fedora 32 OVN build

- go-controller/pkg/node/gateway_init.go
SIGSEGV like below can be avoided by checking err prior to assignment:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1547955]
goroutine 1 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*OvnNode).initGateway(0xc0006a4900, 0xc000630030, 0x1, 0x1, 0x1b572c0, 0xc00000e900, 0xc00000e920, 0xc0006ba3c0, 0xc0006ba3c0, 0x0)
/root/work/src/github.com/ovn-org/ovn-kubernetes-github/go-controller/pkg/node/gateway_init.go:205 +0x175
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*OvnNode).Start(0xc0006a4900, 0xc0003e23f0, 0x1b53300, 0xc00052c100)
/root/work/src/github.com/ovn-org/ovn-kubernetes-github/go-controller/pkg/node/node.go:219 +0x938
main.runOvnKube(0xc000371880, 0x0, …
```
> fix SIGSEGV when gw init error

- go-controller/pkg/util/ovs_unit_test.go
Signed-off-by: Andre Fredette <afredette@redhat.com>
> Added unit test for RunOVSDBTool()

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
> cni: fix up logging after PR#1830

- go-controller/pkg/node/gateway_shared_intf.go
We already do this in local GW mode, but it was missing in shared GW
mode. For ingress traffic coming into the node that is destined for pod
subnet, it needs to be routed into OVN so that the traffic can make it
to the pods. Note this is only for when we are not using SNAT with
multiple gateways.
1. Launch a kind setup, and disable SNAT multiple gateways (disable-snat-multiple-gws)
2. Create a gateway docker container (docker run --network kind --privileged -it centos /bin/bash)
3. Annotate the namespace with the ip of the docker container created in 2 for exgw
4. Ping from exgw to a pod created in the namespace
> Adds pod subnet flows on shared gw bridge

- go-controller/pkg/factory/factory_test.go
Re-orders test code to make sure handler is added before
the updates are sent. This way we certain that if this test
fails, the missing node update did not get dropped between
spawning the routine that triggers updates and adding the
handler.
> factory: Fix informer inital adds and subsequent updates test

- go-controller/hybrid-overlay/pkg/types/types.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/types/const.go
Fixes some small issues seen with the external GW code while investigating; https://github.com/ovn-org/ovn-kubernetes/issues/1794
> Small fixes for external GW

- dist/images/ovndb-raft-functions.sh
the change addressing the following errors:
1. on init startup, pod-1 and pod-2 suppose to be waiting on a critical section
while pod-0 is initializing, however, it isn't working as expected as
a result pod-0 entering infinite CLB
2. restart on leader causing election timer set to fail with error
"election timer change pending"
3. restart on non-leader node, we may still see code path entering into
initial create section
4. replacement of a node following restart of one of existing 2 nodes would
enter into inifinte CLB
5. if the last OVN DB pod fails before it creates the OVN DB service endpoint,
it restarts without trying again to create the endpoint
with the change we introduce retry on rapid timer set when the previous is in
pending state and remove assumption that pod-0 is always a …
> fixing few raft db startup script issues

- test/scripts/e2e-kind.sh
I forget to follow up on this, we need to run this test too
> enable e2e test UDP Nodeport service

- dist/images/Dockerfile.fedora
> Remove dead rpm advisory for OVN

- go-controller/pkg/ovn/ovn.go
If a pod add fails in ovnkube-master, and there is no subsequent update
event for the pod we never try to add it again and CNI will just
continuously fail. A prime example of this is if a pod is added for a
node, who has not yet registered with ovnkube-master by setting its L3
gateway config.
This patch adds a goroutine which will run and check to see if there are
any pods that need retry who have been sitting for longer than a minute.
If such pods exist, the goroutine will attempt to addLogicalPort for
them.
> Adds reconciliation for hanging pod adds

- go-controller/pkg/util/ovs.go
Minor typo fix in comment to change db to SB while using ovn-sbctl
Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>
> Minor typo fix to change NB db to SB db

- go-controller/pkg/node/gateway.go
Code was accidentally adding instead of deleting.
> Fixes load balancer health checker delete

- go-controller/pkg/ovn/egressgw.go
We need to ensure we only add the proper family routes when exgw
annotations are used.
Fixes #1835
> Check IP family for exgws

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_event.go
- go-controller/pkg/ovn/ovn_event_test.go
move the code to their own file and add unit tests.
Don´t allocate a fixed number of events struct.
> refactor ovn events code

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
> implement egress firewall using join switch acls in shared gateway mode

- go-controller/pkg/ovn/egressgw.go
The ovn_cluster_router policy was being removed for a pod anytime an
exgw was deleted. This is incorrect, because a pod may have more than
one exgw configured. The policy should only be removed for a pod if it
no longer has any exgws configured.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1917605
> Fixes deleting exgw pod

- go-controller/pkg/ovn/address_set/address_set_test.go
- go-controller/pkg/ovn/address_set/fake_address_set.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/egressgw_test.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/endpoints_test.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/logical_switch_manager_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn_suite_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/ovn/service_test.go
- go-controller/pkg/util/util_suite_test.go
**-What this PR does and why is it needed **
this PR referring to #1801.
this PR import the `gomega` and `ginkgo` using the package name instead of using the "." import .
the files changed are the `*_test.go` on the directories`pkg/ovn/*` and `pkg/util/*`.
try to build and run the tests on the directories `pkg/ovn/*` and `pkg/util`.
to check  `pkg/util/*` run from repository root directory:
```
cd go-controller/pkg/util
go test
```
and make sure the test is successfully build.
to check  `pkg/ovn/*` run from repository root directory:
```
cd go-controller/pkg/ovn
go test
```
and make sure the test is successfully build.
fixing #1801 on the directories`pkg/ovn/*` and `pkg/util/*`
> Import ginkgo and gomega using pacagename on `pkg/util` and `pkg/ovn`

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
> add option to enable empty events in KIND

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/healthcheck.go
> Manage and update the gateway OpenFlow rules using flow cache

- contrib/kind.sh
Add OVN/OVS logLevel parameters to the `kind.sh` script
> Add OVN logLevel parameters to `kind.sh`

- test/e2e/e2e.go
the main source of flakiness on e2e test are caused by asynchronous
operations.
Adding fixed timeouts is useless, you'll never now how long can
it takes, and if you overstimate you waste a precious time to run
the test, and also hides race problems in the code.
kubernetes has the wait.PollImmediate functions to check the result
of this asynchronous operations, they give an error if the condition
was not satisfied during the timeout configured.
> deflake e2e test for egressip

- go-controller/pkg/ovn/gateway/gateway.go
> refactor ovn gateway package

- test/e2e/e2e.go
Egress IP e2e tests were flaking because of two reasons:
1. We were not waiting for the egress IP setup to complete
before starting connectivity tests. This is done now by
obeserving the status change, and then performing the
connectivity test
2. When any subsequent test retry happened, we never cleaned
up stale test data from the run in N-1, leading to state
mismatch and flaky failures
Spin-off from https://github.com/ovn-org/ovn-kubernetes/pull/2032#issuecomment-777819636
> EgressIP: cleanup stale e2e test data + wait for setup

- test/e2e/e2e.go
- test/e2e/util.go
We add a new test that creates an externalip service and tries to reach all the endpoints (one for each node) from an external container. The external container goes over all the ips assigned to the node and tries the connectivity through each one of them.
This depends on https://github.com/ovn-org/ovn-kubernetes/pull/1985 and includes its commits.
Only the last commit is related to this change
> E2E tests: test ingress for externalip services

- go-controller/pkg/util/go_ovn.go
use fsnotify watcher to monitor ovndb-client private Key File and Cert
file changes. With goovn client initlized with reconnect flag true,
close the current connection with new TLS cerficate updated,
goovn underly rpc2client will reconnect with new TLS cerficates.
> util goovn TLS connection need to use the latest rotated certificates

- go-controller/hack/test-go.sh
> use '-mod vendor' in all of the `go test` invocations

- go-controller/pkg/ovn/master.go
Logical datapath groups reduce the size of the southbound
database in large clusters. The option is ignored if unsupported
by ovn-northd. ovn-controllers should be upgraded to a version
that supports this option before it is turned on.
@trozet @girishmg @abhat @vpickard
> master: enable logical datapath groups for OVN >= 20.12

- test/e2e/e2e.go
The FDescribeTable was due to local development. We need to remove it or
the only set of tests that are gonna run are these.
> Remove focusing on table

- go-controller/pkg/ovn/controller/services/repair.go
- go-controller/pkg/ovn/gateway/gateway.go
This PR has two commits:
First commit:
```
capture the fact that OVN GR LB is empty as an error object
we need this in several places and we were trying to compare the error
string, and we should avoid it.
```
Second commit:
```
- since we run the repair only once at the beginning, we should clean
up as much as possible and logging error where we can't and still
proceed
- some error messages were printing the entire LB UUID list on failure,
we only need to print only one LB
```
> few fixes to endpointslice controller's repair code

- test/e2e/external_gateways.go
We clone the external gateway namespace annotation tests with a difference: bfd is enabled both on ovn side and on the containers (using a custom container via frr).
We check that ecmp works with two containers, then we remove one container and check that all the traffic reaches the remaining container.
This PR needs to be merged after https://github.com/ovn-org/ovn-kubernetes/pull/2090
> External gateway namespace tests: Cover BFD

- go-controller/pkg/ovn/egressgw.go
With the fix for --may-exist on routes, the route add may still error
due to:
https://bugzilla.redhat.com/show_bug.cgi?id=1916842#c5
Resulting in ovn-k8s:
'ErrorAddingLogicalPort' unable to add src-ip route to GR router,
stderr:"ovn-nbctl: duplicate nexthop for the same ECMP route\n"
> Fixes adding duplicate ECMP routes

- go-controller/pkg/ovn/controller/unidling/unidle.go
The delete handler may receive the service object but it also
can receive cache.DeletedFinalStateUnknown events, and it must
be able to handle them, otherwise it will panic.
> unidling controller must process cache events

- contrib/kind.sh
this PR is a restructuring of the kind.sh script w/o change of behavior
the change can be verified by running the script (following what is defined in `docs/kind.md`)
> kind: script restructuring

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-node.yaml.j2
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/node/node.go
- go-controller/pkg/types/const.go
- test/e2e/e2e.go
This PR adds support to export flows to a collector by using either NetFlow, sFlow or IPFIX, which are the protocols supported by OVS.
1. ./kind.sh
2. kubectl create deployment goflow --image=cloudflare/goflow --replicas=1 -- /bin/sh -c '/goflow -kafka=false -logfmt=json 2>&1'
3. kubectl expose deployment goflow --protocol=UDP --port=2056
4. kubectl -n ovn-kubernetes edit ds ovnkube-node
5. Add "*goflow svc IP*:2056" as value of OVN_NETFLOW_TARGETS
6. kubectl logs -l app=goflow
The logs of GoFlow (which is a flow collector) should show traffic of the kind cluster by using NetFlow. 
Add NetFlow/SFlow/IPFIX support
> Add NetFlow/SFlow/IPFIX support

- go-controller/pkg/testing/exec.go
The current FakeExec implementation does a klog.Fatal, which has the
side effect of panicing and dumping all the goroutines.
Here we record that first non match and we continue returning failing
cmds. With this, we avoid the dump of all the goroutines stacks in case
of failure.
> FakeExec: don't panic when a cmd does not match

- test/e2e/e2e.go
the NetFlow e2e tests changes the environment variable for the
ovnkube-node daemonset and this results in rolling update of the
ovnkube-node pods that involves first terminating all of
the ovnkube-node pods and re-creating them, so wait for those pods to
be ready before proceeding
> wait for ovnkube-node rollout to complete for NetFlow e2e test

- go-controller/pkg/ovn/ovn.go
> avoid nil pointer reference in WatchCRD

- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
ovn-trace command requires specifying ip4 or ip6 accordingly
Closes: SDN-1697
> ovnkube-trace support for IPv6

- go-controller/pkg/ovn/gateway_init.go
This fixes a possible issue where the management port changes for
and existing node. Previously this was never noticed since it's
highly unlikely to happen. If it did happen however we proceeded
to deleting the old setup made, but not creating the new. This
patch fixes that
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
> Sync management port correctly if it changes for an existing node

- go-controller/hack/regenerate_vendor_mocks.sh
> Fix mockery test

- go-controller/pkg/ovn/egressfirewall_dns.go
- test/e2e/e2e.go
Currently when adding EgressFirewalls with 5 or so dnsNames (observed
with 5 dnsNames) it is probable that a deadlock will occur.
thread 1 calls (e *EgressDNS) Add() grabs lock e.lock and calls
signalAdded(dnsName) and continues looping to the next dnsName calling
(e *EgressDNS) Add() grabbing e.lock and trying to write to the channel
thread 2 recieves the signalAdded(dnsName) and is waiting to grab
e.lock in updateEntry for name
thread 1 cannot write to the channel because the channel blocks waiting
for the write and holds e.lock
thread 2 cannot continue with updateEntryForName() because it is wating
for e.lock
Solve this problem by taking the add goroutine out of the long running
update goroutine. By spawning a goroutine for every DNS name the
goroutines can wait until it is there turn …
> fix deadlock in EgressFirewall DNS code

- go-controller/pkg/ovn/policy.go
Profiling indicated a lot of contention on this lock. We should release it before we commit our changes to OVN.
> policy: release LSP lock before adding pods to default-deny portgroups.

- go-controller/pkg/node/node_smartnic_test.go
> Add FakeExec call validation to node smart-nic tests

- go-controller/pkg/ovn/address_set/fake_address_set.go
1) use sync.Mutex rather than RWMutex which has performance issues
2) switch 'destroyed' to an atomic so we don't need to protect access
to it with the mutex
3) add locking to addIP() to solve the following data race:
```
2021-05-12T13:41:21.0637496Z WARNING: DATA RACE
2021-05-12T13:41:21.0637992Z Read at 0x00c000dedc50 by goroutine 580:
2021-05-12T13:41:21.0639638Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/address_set.(*FakeAddressSetFactory).EventuallyExpectEmptyAddressSet.func1()
2021-05-12T13:41:21.0641503Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/address_set/fake_address_set.go:150 +0xe6
2021-05-12T13:41:21.0642269Z   runtime.call16()
2021-05-12T13:41:21.0642863Z       /opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:550 …
```
> ovn: fix some concurrency issues in fakeAddressSet

- go-controller/pkg/ovn/address_set/address_set_suite_test.go
> address_set: fix test suite file name and suite name

- test/e2e/external_gateways.go
We currently validate connectivity with various protocols / ip families
from pod to egress. Here we validate the same path but starting from the
gateway containers that mimic the gw pod.
> Extend gateway tests to validate connectivity from gateway to pod

- go-controller/pkg/cni/ovs.go
We see at scale that this can happen:
1. CNI delete
2. OVN is so busy it takes 30 seconds to remove the old logical port
3. CNI ADD within 30 seconds
4. ovn-controller sees old logical switchport, binds and considers new
pod up, but no traffic works
5. sometime later OVN gets updated, and ovn-controller updates the pod
with the new flows and traffic finally works
To solve this problem we need to have a minimal check to ensure the
right flows are present for the pod before we check if ovn_installed is
true. This change adds back the checks for mac address and of port
number.
> Adds back checking OF flows for CNI

- go-controller/pkg/ovn/loadbalancer/loadbalancer.go
- go-controller/pkg/util/ovs.go
It's possible to batch too many nbctl commands and exceed the OS max
bash args:
failed: fork/exec /usr/bin/ovn-nbctl: argument list too long"
...
Request entity too large: limit is 3145728' (will not retry!)
This patch attempts to detect maximum args allowed on a system, and then
commit existing transactions that would exceed that size using a new
function AddOrCommit.
> Split large nbctl transactions

- go-controller/pkg/ovn/policy.go
When a policy selects many pods, there can be lock contention. This doesn't need to be the case - all the pod creation wants to do is update a hash.
So, instead, take a read lock and use a sync-safe map instead.
> policy: reduce lock contention on policy object

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/ovn.go
batch ovn commands as much as possible for now for egressFirewall. removes the need to block all traffic during upgrades 
> Batch ovn commands for Egress firewall

- test/e2e/e2e.go
Signed-off-by: Omer Ben-Hayun Omer.Ben-Hayun@ibm.com
this PR refactor the e2e test `"recovering from deleting db files while maintain connectivity"` and instead of waiting fixed amount of time (90 seconds) for the pod to restart, it will wait for the pod to finish full restart with `waitForPodToFinishFullRestart`.
the reason for the change is that  its not guaranteed that the deleted db-pod will be up and running by 90s.
I refactored the test `"recovering from deleting db files while maintain connectivity"` , instead of using `time.sleep(90*time.Sceond)` for waiting for the pod restart , I used `waitForPodToFinishFullRestart` as suggested on the comments for #2104.
in order to try it …
> Refactoring e2e test - fixing waiting period when delete db files

- go-controller/pkg/ovn/gress_policy.go
> Minor fix to allocating slice for gress policy

- .github/workflows/docker.yml
specifically calls to the syncMaps LoadAndDelete() causes failure
seen in this PR: https://github.com/ovn-org/ovn-kubernetes/pull/1916
```
Error: pkg/ovn/policy.go:848:26: np.localPods.LoadAndDelete undefined (type sync.Map has no field or method LoadAndDelete)
Error: make[1]: *** [Makefile:34: all] Error 2
make[1]: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller'
Error: make: *** [Makefile:87: ../../go-controller/_output/go/bin/ovnkube] Error 2
make: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/dist/images'
Error: Process completed with exit code 2.
```
**- Description for the …
> bump version of go used for building images is CI testing

- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/ovn.go
Fixes two minor issues:
- Slightly flawed logic for in the egress nodes watcher
- Remove log lines which are spamming ovnkube-master with spurious messages
> Minor egress IP fixes

- go-controller/pkg/ovn/ovn.go
When a node is deleted, there is a grace period before pods will be
evicted from that node. A scenario can occur where we get a node delete
followed by a node add for the same node. During node delete we tear
down the logical switch and all ports associated with that node,
including pod ports. If the above scenario happens, the logical switch
will be restored, but existing pods will not get any new add event, so
we will not recreate any of the logical ports. This will leave the
container without networking and on subsequent restart the pod wil be
stuck in containerCreating status.
This patch addresses the issue by ensuring all pods on a node are wired
after a node add.
> Adds back logical ports for pods during node add

- go-controller/pkg/node/healthcheck_test.go
- go-controller/pkg/ovn/policy_test.go
Not sure how this sneaked in and how it's not been detected this long...
> Fix go-fmt errors

- go-controller/pkg/cni/ovs.go
> avoid printing format specifiers by using Infof

- docs/kind.md
Update the kind.sh --help output and slightly change some of the
wording.
> docs: Improve kind documentation

- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
ovnkube-trace will from now on only install dependencies with pip3 if
these dependencies are not met.
Newer images already come with the required python OpenSSL library
and with ovn-detrace, hence installation of the dependencies with
pip3 is no longer required.
Fixes #2311
> ovnkube-trace: Only install deps with pip3 if deps are not met

- docs/multicast.md
This PR adds documentation on how multicast is implemented in OVN.
closes #2288 
docs: add multicast information
> docs: Add multicast information

- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- test/e2e/e2e.go
This PR implements ECMP for Egress IPs. This is currently not the case for the egress IP setup, which, today, only sends traffic to only one egress node following a non-deterministic OpenFlow ordering. With this PR: traffic will be load balanced between the egress nodes equally following OVN's configured OVS selection ordering (`dp_hash`/`hash`)
**Background:**
Multiple nodes can be specified for an egress IP setup, which per definition makes it an "HA setup" (i.e: if one of your egress nodes goes down, the second will continue serving egress IP intended traffic). You can thus have "egress IP 1" assigned to "node 1" and "egress IP 2" assigned to "node 2", if "node 1" goes down - today - we need to compute a complete re-allocation of the egress …
> ECMP for Egress IP

- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
iproute is not guaranteed to be present in a pod. Simply always
retrieve the required linkIndex from the standard /sys interfaces
which will be present on all Linux pods. This is a refactor of an
earlier commit.
Also, for the ovnkube pod check, remove an else condition which was
never hit because tryJSON was always set to true.
Fixes #2307
> ovnkube-trace: Refactor get linkIndex from /sys interface

- go-controller/pkg/ovn/pods.go
Helps debug latency issues for pod setup.
@trozet
> pods: log when pod setup starts

- .github/workflows/test.yml
Our CI pipeline is overloaded, remove some jobs.
> Remove some CI jobs

- go-controller/pkg/testing/libovsdb/libovsdb.go
- go-controller/pkg/testing/libovsdb/matchers.go
Fixes libovsdb test harness assuming empty strings are named uuids. Also
a bit more thorough detecting duplicate named uuids and duplicate
unexpected matches between actual and expected when attempting to infer
them.
/assing @JacobTanenbaum 
> [libovsdb] fix unnamed uuids in test harness

- contrib/kind.sh
- docs/kind.md
Add dependency check and make sure that required binaries
are installed. Update documentation for kind.sh
Closes #2380
> kind.sh: Add dependency check for required binaries

- test/e2e/e2e.go
- test/e2e/external_gateways.go
- test/e2e/util.go
Use format strings to get the right output string.
> test: fix ExpectNoError() message formatting
