dist/templates/ovnkube-db.yaml.j2, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
ovnkube-node was trying to scrape DB stats and had no mounted volume to
access the NB or SB DB. Additionally, the node was always trying to get
cluster DB stats even when we were not running in HA.
On ovn-k8s master nodes (where db runs) look at the log for ovnkube-node. Without correct paths messages will appear in the log like:
contrib/logs.txt:, err: (OVN command '/usr/bin/ovn-appctl -t /var/run/ovn/ovnnb_db.ctl --timeout=5 cluster/status OVN_Northbound' failed: exit status 1)
contrib/logs.txt:E0805 18:56:15.422051    2212 ovn_db.go:535] OVN command '/usr/bin/ovn-appctl -t /var/run/ovn/ovnnb_db.ctl --timeout=5 cluster/status OVN_Northbound' failed: exit status 1
contrib/logs.txt:E0805 18:56:15.438053    2212 …
=> Fix DB metrics detection for ovnkube-node

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/testing/exec.go
This handles the case where, for whatever reason, the nbdb was deleted out from under us. Since we still have the annotations, we can reconstruct as needed.
/cc @JacobTanenbaum @dcbw
=> hybrid-overlay: reconcile annotation to DB.

.github/workflows/test_periodic.yml
We shouldn't be running the periodic dual-stack CI job (or future periodic jobs) in people's local forks. (And in particular, we shouldn't be sending mail to them about it every day.)
I couldn't find any way to mark the whole file as "`if`" something; it seems like you have to specify it separate for each job...
@aojea @trozet
=> ci: don't run periodic jobs in forks

go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/node/egressip.go, go-controller/pkg/node/egressip_test.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/port_claim.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go
while reviewing #1567 I noticed it was checking for errors while removing handlers and was wondering why it needs to do that, and the answer is that it really doesn't
=> simplify factory error handling

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2
it is impossible to use non-kind cluster virtualization mechanisms and also
there are some ways to improve the current netns access logic, as such
this change provides:
* generic way to configure ovnkube-node --unprivileged-mode
* convert kind to use new configurable rather then specific
* eliminate the need to mount /var/lib/netns
Signed-off-by: Dmitry Yusupov <dyusupov@nvidia.com>
=> provide a way to configure --unprivileged-mode

go-controller/pkg/util/nicstobridge.go, go-controller/pkg/util/nicstobridge_test.go
After PR #1504 was merged, the head is currently broken and `make check` fails.
This is because of mismatch in the API name both in the test and non-test file.
@vjayaramrh not sure what happened here. Can you PTAL?
@ovn-org/ovn-kubernetes-committers FYI
=> s/LinkSetup/LinkSetUp/ in nicstobridge[_test].go

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
This PR adds ability for CNI to wait for openflow flows to be present for the pod, and modifies add_logical_port to annotate the pod before we issue OVN commands. Since most of the time logical port add failures are due to the pod being removed in k8s and we can no longer set the annotation, it ends up leaving OVN config which we have to manually roll back. This PR moves the annotation to before OVN config is done.
=> Fix pod add

go-controller/pkg/ovn/egressip_test.go
This is a spin-off from: https://github.com/ovn-org/ovn-kubernetes/pull/1598#issuecomment-671328286 and comments mentioned on slack: https://coreos.slack.com/archives/GQ0CU2623/p1596750386234500?thread_ts=1596734533.218000&cid=GQ0CU2623
The test `should perform re-assignment of EgressIPs` in `egressip_test.go` sometimes panics as `getEgressIP` (which is used to retrieve that the egress IP status during the asynchronous update)  can return an empty status. This is because `WatchEgressIP` on update resets the status field to an empty status before performing the re-assignment. `deleteEgressIP` and `addEgressIP` both use a mutex to insure correct handling during the delete / add, but during the update there is a small window where the status field …
=> Fix egress IP test panic

go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/config/config.go
The hybrid-overlay-cluster-subnets argument is not required to have a
value for hybrid overlay to work. It is only required when using Windows
nodes that are part of the cluster. It is not required when sending to
3rd party gateways. This patch removes the default subnet value for the
arg.
=> Do not default HO cluster subnets

go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/policy.go
By applying an "allow-related" ACL to every logical switch for mgmt
traffic it causes all traffic between pods to go through conntrack. This
is undesirable, especially when no network policy is being used.
=> Fix default allow mgmt ACL using conntrack

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
When multicast was enabled for a namespace, the allow ACL was trying to
refer the per namespace address set using the wrong name (changed after
commit 414599b7c631). The code now uses nsInfo.addressSet to get the
correct address set name.
Reported-at: https://bugzilla.redhat.com/1843695
CC: @dcbw @abhat
=> Fix multicast allow ACLs after namespace AS name change.

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go
=> Making VLAN ID option to be supported only in shared gateway mode

dist/images/Dockerfile.ubuntu.arm64, dist/images/Makefile, dist/images/push_manifest.sh
Add a ubuntu-based arm64 image building support,
including the Dockerfile and related Makefile changes.
Add multi-arch support for ovn-daemonset-u images for amd64
and arm64 platforms by fat manifest with manifest_tool which
can also be used for other type of images in the future.
Signed-off-by: Trevor Tao <trevor.tao@arm.com>
=> Add arm64 and multi-arch support for ubuntu image

dist/images/Dockerfile.fedora
Picks up force_snat dual-stack fix, ECMP, conntrack optimizations,
and some more.
@trozet @rcarrillocruz @danwinship @alexanderConstantinescu
=> dist: bump OVN to ovn-20.06.1-7.fc31

test/scripts/e2e-kind.sh
This test was already skipped in IPv6 and is now failing for us on IPv4
due to a bug in OVN:
https://bugzilla.redhat.com/show_bug.cgi?id=1870359
=> Skip kube proxy connection reset test

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
Use action flood intead of normal for shared gw bridge
Today we use conntrack to make decisions on how to steer traffic between
the host and OVN on the shared gw bridge (breth0 in KIND cases). This
necessary because we share the same MAC/IP between OVN and the host.
However, some traffic cannot be conntracked (like IPv6 ND) so therefore
it will hit the default rule which currently is NORMAL action.
However, NORMAL action is not sufficient because that will end up
choosing whichever entry is in the FDB, and that is undeterministic
because both ports are sharing the same MAC. This patch changes the
behavior to use FLOOD so that unknown packets are sent to both the host
and OVN.
=> Use flood for shared gw

go-controller/hack/build-go.sh, go-controller/pkg/config/config.go, go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/node.go
This PR improves version information printed by ovn-kubernetes binaries to include useful information such as:
- Version
- Git commit
- Go version
- Build date
- OS/Architecture
This information is usually required in debugging tasks.
To verify it just execute any binary with the -version flag
```
$ _output/go/bin/hybrid-overlay-node -version
Version: 0.3.0
Git commit: 952ef9424870563711a48d0f2f8b4afc787b5641
Git branch: print-version
Go version: go1.14.6
Build date: 2020-08-23
OS/Arch: linux amd64
```
Improve binaries version information.
---
Signed-off-by: Raul Sevilla <rsevilla@redhat.com>
=> Custom VersionPrinter

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_local.go, go-controller/pkg/ovn/egressip_local_test.go, go-controller/pkg/ovn/egressip_shared.go, go-controller/pkg/ovn/egressip_shared_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go
This PR fixes a couple of issues with the egress IP feature that merged yesterday with PR:  https://github.com/ovn-org/ovn-kubernetes/pull/1484. There is no real rush to get this in today and it can wait until next week. I didn't have time to do this yesterday with all the things going on.
Problems solved:
- When deleting the pod's egress setup (upon a pod delete) we were retrieving the IP from the OVN database and subsequently racing with `deleteLogicalPort`, in case we lost: we never cleaned up. I thus changed that to only look at the `pod.Status` instead, this resolves the race condition. Since a pod IP can't change we thus never really need to look in the OVN DB for that. This also simplified the code as I didn't need to pull in …
=> Egress IP fixes

contrib/kind.sh
Moved installation of j2cli via PIP after parsing the arguments.
Parsing command line arguments should be the first statement in the script so that if someone is just providing
the "-h" flag we print out the help  without doing any check. By moving the above statement as mentioned
we have ensured "-h" flag works even if say pip is not installed in the system.
=> Make sure help message is always printed for kind.sh

go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/init_others.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/init_windows.go, go-controller/hybrid-overlay/pkg/windows/service/service.go
This PR introduces a fix for the issue addressed in https://github.com/ovn-org/ovn-kubernetes/issues/1562
As of now, running hybrid-overlay-node as a Windows service relies on os.Exit() to stop the service, this PR 
removes abrupt exit by instead cancelling the context on svc.Stop.
Signed-off-by: mansikulkarni96 <mankulka@redhat.com>
=> Fix abrupt exit of Windows service

go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/policy.go
This reverts commit fd4758701cd61e0f69e21ef5a96ab5d91f704ef0.
We found that this causes problems with network policy ACLs when using
multi-node setups where the network policy ACL only targets a portgroup
of the destination, and in effect only places the ACL there with
allow-related. This causes return traffic destined to another node to be
dropped, because that node does not have any allow-related ACL, and thus
never able to determine via CT if this is reply traffic.
=> Revert "Fix default allow mgmt ACL using conntrack"

go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/testing/mock_chassis.go, go-controller/pkg/testing/mock_ovn.go, go-controller/pkg/testing/mock_stubs.go
This change replaces the ovn-sbctl calls with go-ovn bindings functions
for SB Chassis related OVN SB operations.
=> use go-ovn bindings for Chassis related OVN SB transactions

contrib/kind.sh, contrib/kind.yaml.j2
We were not using the same network configuration in Kubernetes and in OVN.
The defaults were similar but not the same, this configure the same network parameters in both.
xref: https://github.com/kubernetes/kubernetes/issues/94029#issuecomment-675395052
=> use same network configuration in KIND and in OVN

dist/images/Dockerfile.fedora
Won't work until https://bodhi.fedoraproject.org/updates/FEDORA-2020-d2abd8fe6c actually gets pushed to updates-testing but that should be very soon.
=> dist/fedora: require ovn-20.06.2-3.fc31 or later

README.md
The current installation instructions did not include instructions to deploy/create CRDs
fixes "Missing CRD definitions" https://github.com/ovn-org/ovn-kubernetes/issues/1650 
Without instructions added by this fix, user will not deploy CRDs and as result `ovnkube-node` pods will not find the resources definitions 
=> install: add CRD installation instructions to the README file

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
There's a race during pod and delete where a delete will go to ovn-nbctl
and update the NB DB, while an add will read from go-ovn cache. When a
pod is created/deleted fast enough, add_logical_port will not add the
new port (thinking it exists because it is in cache), when really it has
already been deleted. Use bindings to ensure we delete from cache first.
Issue discussed here:
https://github.com/eBay/go-ovn/issues/104
./hack/ginkgo-e2e.sh --provider=skeleton --num-nodes=6 "--ginkgo.focus=Should\srecreate\sevicted\sstatefulset" --report-dir=/home/trozet/e2e --disable-log-dump=true
=> Make pod delete also use go-ovn bindings

dist/images/ovnkube.sh
It may happen that the ovn-controller container restarts (a bug,
fatty fingers, ... )
If this happens, the container init script deletes the ovn-remote
in the external_ids field, causing that it never reconnects until
the ovnkube-node pod is recreated.
This causes that all the pods in that node can not get an interface,
failing with the error:
"failed to configure pod interface: timed out waiting for pod flows
for pod"
Seen in this job 
https://github.com/ovn-org/ovn-kubernetes/runs/1059062544?check_suite_focus=true
caused by
https://bugzilla.redhat.com/show_bug.cgi?id=1871961
It can be easily reproduced in kind, deleting ONLY the ovn-controller container inside the ovnkube-node pod, after that no pod can be scheduled in that node
=> ovn-controller should not delete ovn-remote field

README.md, contrib/kind.sh, dist/images/daemonset.sh, dist/templates/ovnkube-node.yaml.j2, dist/templates/ovs-node.yaml.j2
Quoting from issue #1599, where this was discussed
"In production and serious deployments, the OVS is choice of
software for host networking. So, deployers will not run OVS in
containers."
We should try to test the same scenarios that we run in production,
hence we run openvswitch in its own daemonset instead of running it
in the ovnkube-node pod.
Fixes: #1599 
=> run OVS in its own daemonset

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go
The lr-nat-add would occasionally fail in the gw initialization code
causing the nodes to not come up. The --may-exist semantics work on
the tuple as a whole and if a given row is added again with a different
external IP in case of snat and different logical IP in case of dnat or
dnat_and_snat, the add would fail. So this change makes sure we delete the nat
entry first before trying to add it.
=> Make sure lr-nat-add doesn't fail when adding rows

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/helper_linux_test.go
it turns out that the EUI64 address generated was based on the
default mac address that is created with the veth pair.
However, we set a custom mac address later that does not correspond
to the link-local address associated to the interface, causing that
ovn drops the traffic.
In order to generate a new link-local basde on the provided mac
address, we just need to set it down and up the interface.
=> fix EUI64 link-local address on pod interfaces

test/e2e/e2e_test.go
- this commit adds a host route for the case where the
test infra has snat disabled for return traffic from
the mock container back to the pod sourcing the traffic
- commit adds a host route for mock external gateways in e2e
- This is to fix a failing e2e test in PR #1680 by @trozet 
PR can be verified with the following:
```
curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64"
pushd …
```
=> Add a host route for mock external gateways in e2e

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_local_test.go, go-controller/pkg/ovn/egressip_shared_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
I thought this was going to be a one-liner but it was tricker because apparently the egress IP code now parses `lb_force_snat_ip` to find the gateway IP for a node... I'm not sure that's the right way to find that information, but I didn't change it for now, other than to rewrite it a bit to be more like other dual-stack code.
cc @alexanderConstantinescu
=> Update lb_force_snat_ip code for dual-stack

dist/yaml/.gitignore
The `ovs-daemons` containers were separated into dedicates DaemonSet - `ovs-node`, with generated yaml file.
This PR adds `ovs-node.yaml` into the `dist/yaml/.gitignore` file.   
=> add ovs-node.yaml to .gitignore

dist/templates/ovnkube-db.yaml.j2
When ovnkube-db is deployed without raft support it has mounts of host /var/run/openvswitch/
to /var/run/ovn, and as result the sockets are created in the container local directories
/var/run/openvswitch/, and are not be accessible outside of the containers.
This commit adds mount /var/run/openvswitch/ to /var/run/openvswitch/.
P.S. `ovnkube-db-raft.yaml.j2` has these mounts.
fixes https://github.com/ovn-org/ovn-kubernetes/issues/1669
=> Adds mount /var/run/openvswitch/ -> /var/run/openvswitch/ to ovnkube-db.yaml.j2

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
extracted from #1680 and rewritten a bit; rather than doing a separate LinkSetDown+LinkSetUp, just avoid removing the link-local address in the first place...
=> Fixes losing link local addresses for ipv6

.github/workflows/test.yml, contrib/kind.sh, contrib/kind.yaml.j2, test/scripts/e2e-kind.sh
the sig-network tests in the e2e framework only are not fully exercising
the cluster networking, also they are not stressing the cluster enough to
cover more all the races.
Running the whole conformance + sig-network test, and increasing the
parallelism we can emulate more real workloads.
Also, when running in HA mode, only run OVN in HA to avoid the excessive
resources requirements of a 3 nodes etcd cluster, that is overwhelming for the
current CI resources.
=> run conformance tests in the CI

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/management-port.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/pods.go
Uses a combination of local gateway mode and shared gateway mode. The
topology is identical to shared gateway, however the flow of traffic is
different.
The shared gateway bridge is used only for external network when doing
multiple external gateways (without SNAT). Otherwise, regular N/S
traffic is handled by ovn-k8s-mp0 and the host. For host -> service
traffic the ovn-k8s-gw0 port is used.
The main advantages of this change are:
- No more double SNAT for N/S traffic to a pod
- External gateway will now work with local gw mode
- Moving closer in logical topology to shared gw mode
=> Modifies local gateway mode functionality

contrib/kind.sh
Avoids the copy exiting with code 1 when it tries to copy the
'windows' directory if you ever ran 'make windows'.
```
+ pushd ../dist/images
~/Development/containers/ovn-kubernetes/dist/images ~/Development/containers/ovn-kubernetes/contrib
+ sudo cp -f ../../go-controller/_output/go/bin/hybrid-overlay-node ../../go-controller/_output/go/bin/ovn-k8s-cni-overlay ../../go-controller/_output/go/bin/ovnkube ../../go-controller/_output/go/bin/ovn-kube-util ../../go-controller/_output/go/bin/windows .
cp: -r not specified; omitting directory '../../go-controller/_output/go/bin/windows'
```
@aojea
=> kind.sh: ignore directories when copying executables

dist/images/Dockerfile.ubuntu
Ubuntu 18.04 repository contains old OVS/OVN packages, (2.9.5-0), which are not compatable with current implementation.
With Ubuntu 20.04 `apt-get` installs OVS 2.13 and OVN 20.03
fixes https://github.com/ovn-org/ovn-kubernetes/issues/1695
With Ubuntu 18.04 the ovn-kubernetes image, contains OVN/OVS packages v2.9.5.
and as result there are the following errors:
```
ovn-nbctl: unrecognized option '--inactivity-probe=0'  (from the nb-ovsdb log)
ovn-sbctl: unrecognized option '--inactivity-probe=0   (from the sb-ovsdb log)
/usr/bin/ovn-nbctl: unrecognized option '--pidfile'      (from the nbctl-daemon  log)
```
**- Description for the …
=> Ubdate Ubuntu to 20.04

contrib/kind.sh
we have to untaint the master nodes so we can schedule pods on them, however, the kind
get nodes does not report the nodes in the right order.
This does not an impact HA deployments since we untaint the same number of nodes that we create,
hence the order does not matter.
For noHA deployments it means we only schedule pods in the worker. But our CI is mainly using HA
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>
=> fix a bug on kind deployment

go-controller/pkg/node/gateway_shared_intf_linux.go
We were setting it correctly in the mac_binding table for OVN, but the
mac did not match the address configured on the host. This caused host
destined packets from OVN to be dropped in IPv6.
=> Fix setting ovn-k8s-gw0 mac address for ipv6 single-stack

go-controller/pkg/factory/factory.go, go-controller/pkg/informer/const.go
current resync period was set to 12 hours, instead of having
such large period with the risk of overwhelming ovn with events
every 12 hours, just disable the resync period.
=> disable informers factory resync period

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway.go
Increase the priority of egressfirewall router policies to
ensure that they get processed first. In order to make sure that
no cluster traffic is interrrupted by the egressfirewall rules ensure
that cluster traffic is explicitily excluded from the pattern match
=> increase the priority of egressfirewall router policies

go-controller/pkg/ovn/ovn.go
Egress firewall objects have an assigned status which needs to be
updated by OVN-Kubernetes. The update can however lead to a data race
with the API server object contained in memory in case the update is
not done on a copy. This is something that has been seen when testing PR:
https://github.com/ovn-org/ovn-kubernetes/pull/1640 which enables the
race detector
/cc @aojea @JacobTanenbaum 
=> Make sure to update the copy of egress firewall objects 

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go
When running ovn-kubernetes without `--enable-egress-ip`, ovnkube-master was experiencing errors as we still created the informers (though not starting it). This patch changes that to not instantiate the informer at all should we not be running with `--enable-egress-ip`
/assign @danwinship 
=> Add EgressIP informer only if egress IP is enabled

go-controller/pkg/ovn/ovn.go
If an ovn network pod was updated with exgw annotations, we were
ignoring it because it was not rescheduled and was not a host networked
pod. We should always be updating the exgw for an ovn networked pod
because the pod may be using multus annotations and not rely on being
host networked.
We have no way in our CI/KIND to create a multus host network attachment, so we can trick it and still exercise the same code path:
1. Deploy kind with at least 1 worker node
2. Create a pod in a namespace that will be used for exgw (i.e. create any basic pod in "exgw" namespace)
3. Create another basic pod in default namespace
4. Create an external docker container on the kind network. Add an IP local to that container on lo like …
=> Fixes requiring host-network for exgw pods in update

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/policy.go
There is a race condition, described here
(https://bugzilla.redhat.com/show_bug.cgi?id=1859682)
that results in ACL's and their associated network
entities being orphaned upon the deletion of
a namespace
Specifically, if a namespace is deleted by OVN-K8's
prior to all the Network Policies being handled,
the ACLS, portgroups, address sets, and handlers
become orphaned in `nbdb` beacuse a namespace lock
can never be acquired in `policy.go`'s
`deleteNetworkPolicy()`
This fix ensures that all network entities involving
a namespace's NetworkPolicies are deleted prior to the
namespace's deletion
TODO: I think this is just a quick fix, ultimately
It would be nice to decouple the NetworkPolicy's
dependency on namespaces within OVN maybe by moving the
[`networkPolicies` …
=> Fix Orphaned ACL race condition

dist/images/Dockerfile.fedora
Remove expired fedora advisory
=> Remove expired fedora advisory and testing repo references for FDP build

README.md, contrib/kind.sh, dist/images/.gitignore, dist/images/Dockerfile, dist/images/Dockerfile.fedora, dist/images/Dockerfile.fedora.dev, dist/images/Dockerfile.ubuntu, dist/images/Dockerfile.ubuntu.arm64, dist/images/daemonset.sh, dist/images/ovndb-raft-functions.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-db-raft.yaml.j2, go-controller/Makefile, go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/util/ovs.go
This commit adds support for auditing the raft membership for NB
and SB databases as well as a health-check to recover from a corrupted
cluster.
Following use-cases are supposed to be solved:
- When ovnkube-db pods are restarted in a raft (HA)
mode, they will have a new server id with which they will join the cluster. 
This will cause the members list in the db to have two entries for the same node.
- When any of the existing master nodes is replaced, the cluster will end up
showing the old master's sid in the members list. The replaced node needs to
be evicted. This commit adds support to detect an orphan raft member and kick
it out of the cluster.
- Finally, when any one local instance of the raft db is corrupted, 
today there is no mechanism for the db to recover itself automatically. …
=> Add support for OVN DB Health Check and Raft Membership changes

.github/workflows/test_periodic.yml
Considering the jobs takes about 25 mins to run, in average, we
have limited the CI jobs to timeout after 1 hour.
However, this implies that the test are running in parallel.
=> run periodic tests in parallel

go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/endpoints_test.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go, go-controller/pkg/util/net.go
Previously we were just checking if there as a known ACL which existed
in the cache. If the cache is ever out of sync, we could accidentally
leave stale reject ACLs configured in OVN.
This patch adds checking during service sync for any known stale ACLs
with reject actions belonging to a service. During regular reject ACL
delete a new check is added to see if cache is in an invalid state, and
if so attempt to remove the ACL by querying OVN.
=> Remove reject ACLs regardless of cache

go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/master_test.go
When we delete a node we initiate gateway cleanup which deletes PBR on
ovn_cluster_router. In the current code we list all PBR rules and then
use string submatch to figure out what to delete. Inter node policy was
not including the node name, so it was accidentally deleting PBR rules
for other nodes.
Additionally, the match logic was flawed in the case where there are
node names that overlap. For example, ovn-worker and ovn-worker2. If
ovn-worker node was deleted, it may accidentally match and delete
policies for ovn-worker2.
Both of these issues are addressed by this patch.
Note: in the future we should totally get rid of this and use the go-ovn bindings.
=> Fix ovn_cluster_router policy deletion

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/kube.go
When using hybrid networking hostnetwork pods will cause the error seen below
`E0925 14:57:10.497565 2878 informer.go:254] error syncing 'openshift-kube-apiserver/kube-apiserver-ci-op-3rmk5i8z-0e6bb-v7v6w-master-1': error getting pod details: could not find OVN pod annotation in map[kubectl.kubernetes.io/default-logs-container:kube-apiserver kubernetes.io/config.hash:356a1361733dbc5fb4922e8352293741 kubernetes.io/config.mirror:356a1361733dbc5fb4922e8352293741 kubernetes.io/config.seen:2020-09-25T14:57:10.167982155Z kubernetes.io/config.source:file], requeuing`
It is meaningless becuase the hostnetwork pods do not have an OVN pod annotation and requing the event just causes errrors until
the max retries is reached (at the time of making this patch that is 3)
Signed-off-by: Jacob Tanenbaum …
=> remove requeing of hostnetwork pods causing spurious errors

.github/workflows/test.yml, test/Makefile, test/scripts/install-kind.sh
We were running a dual-stack job periodically to get signal on the dual-stack status.
https://github.com/ovn-org/ovn-kubernetes/actions/runs/281808838
It seems that now is stable enough so we should gate on it to avoid regressions
=> Gate on dual stack job

dist/templates/ovnkube-db-raft.yaml.j2, dist/templates/ovnkube-db.yaml.j2, go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovndbmanager/ovndbmanager.go
In certain use-cases such as master replacement, we have seen
that the configuration of the db/master pods that holds the addresses
of the raft members isn't updated by the time the new master joins the
raft cluster. When this happens the db pods carrying the old address
configuration for nbdb and sbdb would kick the newly joined master out.
This commit addresses this issue by additionally checking existing master
pods' IPs against the server id list for determining whether a given
server id should be booted out of the raft cluster.
=> Consider changed configuration when kicking out raft members

go-controller/pkg/ovndbmanager/ovndbmanager.go
`klog.Fatalf` will generate a stack trace and exit with code 255. we don't want that to be the case when check-cluster errors out.
=> Avoid restarting ovn-dbchecker if the local db check-cluster fails

go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
Ensures that Namespaces are watched before Pods, which prevents pointless 10s sleeps waiting for namespace objects to be found and added to the cache.
To ensure this case still works though, add a testcase that explicitly makes sure pods are retried if the namespace is added after.
=> Fix testcase pod vs. namespace watch ordering

test/e2e/e2e_test.go
- resolves an issue where wait.PollImmediate is polling
an invalid annotation.
- changed to probe for readiness with a valid address
and removed the now redundant get pod address retries.
commit fixes pod readiness polling in an external gateway e2e test
verify with the following:
```
./kind.sh -gm shared -ha
pushd $GOPATH/src/k8s.io/kubernetes
kubetest --provider=local --deployment=kind --kind-cluster-name=ovn --test
```
=> Fix pollimmediate for pod readiness in e2e test

README.md
The note here is anachronistic and irrelevant; you can just specify the node subnet length you want directly in the argument.
(Noticed reviewing @vwalek's #1701)
=> README: use correct modern syntax for cluster subnets arg

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
When writing e2e tests for Egress IP (upcoming PR soon), I realized a mistake made on my part in the assignment procedure, namely: when specifying an egress IP which is a cluster node X's IP address, we might assign it to another node Y in the assignment procedure. This patch thus fixes this by implementing a check and making sure that if the egress IP specified is a cluster node's, that it is also assigned to exactly that node. If that node does not have the egress label, then we do not perform an assignment and notify the user by triggering an event.  
Some of the tests in `egressip_test.go` were explicitly wrong and testing and verifying the complete opposite to what they should have....I obviously should have paid more attention to that and not let it slip by. 
/assign @danwinship …
=> Correct egress IP assignment for egress node IPs

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
when the node is deleted from the k8s cluster, we try to cleanup all the
ovn-k8s related configurations and one such cleanup is to repalce the
OF Flows on the host OVS bridge with a NORMAL action. however, we were
using FLOOD action and this commit fixes that.
@trozet @danwinship @dcbw PTAL
=> On node deletion restore the NORMAL action and not FLOOD action

go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/service.go
Adding an ACL-per-service-per-node switch doesn't scale. OVN team instead
suggested adding the ACL-per-service to a Port Group which all logical
switch ports are members of.
Note that this does now deny multicast traffic across the management port,
but I can't think of a good reason why that should be allowed or even work
today anyway.
Reported-at: https://bugzilla.redhat.com/show_bug.cgi?id=1855408
=> Move service reject ACLs to a cluster port group

dist/yaml/.gitignore, go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/cmd/ovnkube/ovnkube.go, go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/metrics/ovn_northd.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/endpoints_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/service_test.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
This PR takes a step in the direction of cleaning up the code w.r.t all the newly added clientsets from last week. It addresses: https://github.com/ovn-org/ovn-kubernetes/issues/1528 which was a spin-off from the comments given on both https://github.com/ovn-org/ovn-kubernetes/pull/1484 and https://github.com/ovn-org/ovn-kubernetes/pull/1432
In short, it does not do much: simply adds a wrapper around all client sets and allows callers two ways of instantiating the client sets they need, `NewOVNClientset` (for the wrapper containing them all) or `NewKubernetesClientset` (only instantiating the Kubernetes client set, which is useful for hybrid overlay which does not need the others).
/cc @danwinship @trozet 
**- …
=> Cleanup egress* clientset code

go-controller/pkg/ovn/pods.go, go-controller/pkg/util/go_ovn.go, go-controller/pkg/util/go_ovn_test.go
This change fixes potential Pod IPs leakage. The general rule is that
Pod IPs need to be released in case of failure until they are
successfully annotated in the Pod annotation.
=> Pod IPs could be leaked in some cases

go-controller/pkg/ovn/egressip.go
The test `should skip populating egress node data for nodes that have incorrect IP address`
explicitly defines bad IP addresses for nodes as to make sure we don't use such nodes for
egress assignment, however: `addEgressNode` did not take into account that the node in question
might not exist in the map due to the previous condition. The test flakes as the checks it
performs do not change state and thus the Eventually calls might pass faster than the code
path is executed, i.e: it all depends on the CPU
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
=> Fix egress IP test SIGSEGV

go-controller/pkg/node/gateway_init.go
In the original code there was a switch with 2 cases that had the same operation, and it looks like a mistake.
```
switch config.Gateway.Mode {
case config.GatewayModeLocal:
prFn, err = n.initSharedGateway(subnets, gatewayNextHops, gatewayIntf, nodeAnnotator)
case config.GatewayModeShared:
prFn, err = n.initSharedGateway(subnets, gatewayNextHops, gatewayIntf, nodeAnnotator)
```
=> Cleanup a switch with the same operation in 2 cases

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go
There is a race condition when we return that CNI ADD is complete where
a pod that immediately starts and tries to access the network may fail,
because not all OVS flows are present. Specifically we are missing the
check for flows for ls_out_port_security, table 48. Today we only check
for flows in table 9 port security, and table 48 flows may come a few
seconds later.
=> Adds CNI check for table ls_out_port_security flows

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/namespace.go
When an address set is created in the code, there is no guarantee that
the address set is created. Failure in ovn-nbctl can cause no address
set to be created for a namespace nsInfo struct, for example. In this
case other threads will assume there is an address set and this will
cause segfault. This patch adds some protection around calling address
set methods and ensuring the address set is created.
Found in:
https://bugzilla.redhat.com/show_bug.cgi?id=1888827
=> Guard against nil address set usage

go-controller/pkg/ovndbmanager/ovndbmanager.go
The check-cluster tool is not intended to be run online. The
OVN team is looking into providing an alternative for doing live
consistency checks of raft cluster. Meanwhile, this functionality
is causing red-herrings during scale tests. This PR disables the
DB Health checks for now.
=> check-cluster semantics don't support running the tool online

go-controller/pkg/ovn/address_set.go
When a cluster is in single stack configuration and an IP for the
version not configured gets into the cluster and tries to be added
to an address_set ovn_kubernetes will segfault.
instead of segfaulting return an error
=> prevent segfault in addIPs from address_sets

.github/workflows/docker.yml, .github/workflows/test.yml, .github/workflows/test_periodic.yml
set-env is being deprecated due to security issues.
Appending to $GITHUB_PATH or $GITHUB_ENV should provide the same
functionality.
=> .github: Replace usage of set-env

test/e2e/e2e_test.go
- this commit adds some e2e testing for egress firewall tests
- tests include traffic explicitly allowed by the firewall
crd config as well as traffic implicitly denied by the policy
- changed the wait.PollImmediate to look for a pods ip annotation
- commit adds e2e tests for the egress firewall feature
- I used some external sites for the testing. Before I got too deep into more tests I wanted to get consensus on the basics. I will add more scenarios such as:
- more acl protocol combinations 
- testing updates/deletes to the policy
- fixed the `wait.PollImmediate` function to work. Will patch the other tests once this gets reviewed.
This tests only one …
=> Added e2e for egress firewall

dist/images/Dockerfile.fedora, dist/images/Dockerfile.fedora.dev
Add missing python3-openvswitch and pyOpenSSL
This PR adds a missing python3-openvswitch and python3-pyOpenSSL missing
libraries to the Dockerfile in order to be able to run ovn-detrace later on.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>
=> Add missing python3-openvswitch and pyOpenSSL

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/management-port.go
For external IP usage where the IP does not exist on the host, we create
a route to get the packet into OVN where the load balancer will DNAT it.
However after the changes to new local gateway mode this packet needs be
routed to ovn_cluster_router via the mp0 interface.
1. Create a service with an external IP like:
```
[trozet@trozet go-controller]$ cat ~/service.yaml 
apiVersion: v1
kind: Service
metadata:
name: my-service
spec:
selector:
pod-name: server2
ports:
- name: server-80
protocol: TCP
port: 80
targetPort: 80
- name: server-81
port: 81
protocol: TCP
targetPort: 81
externalIPs:
- 80.11.12.10
```
2. Create a pod behind it and start a python simple http server on 80.
3. create another pod outside of the cluster: …
=> Fixes External IP with local gateway mode

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/net.go, go-controller/pkg/util/subnet_annotations.go, go-controller/pkg/util/subnet_annotations_unit_test.go, go-controller/pkg/util/util.go
We used to have single join switch and commit c372 changed to use
per-node join switch to reduce logical flows in the SB's
lr_in_arp_resolve table.
Since then, there are several OVN patches to provide options to change
the default behavior of OVN and reduce the logical flows in the SB.
In particular, the "dynamic_neigh_routers" option can be set to "true"
and the "learn_from_arp_request" option can be set to "false" to avoid
static neighbor flows and diabling neighbor learning from ARP request,
which minimizes the SB logical flows explosion.
With all the patches, we can now revert back to single join switch
implementation. Furture changes will be needed to set those options to
the gateway routers once OVN patches are avaible.
**- What this PR does …
=> scale: revert back to one single join switch

go-controller/pkg/config/utils.go
If you passed dual-stack cluster subnets with the IPv6 subnet first it would mistakenly apply the IPv6 validation rules to the IPv4 subnet too (which was guaranteed to fail).
eg
```
I1028 10:18:51.401400       1 config.go:1283] Parsed config: {... RawClusterSubnets:fd01::/48/64,10.128.0.0/14/23 ...}
F1028 10:18:51.401566       1 ovnkube.go:130] cluster subnet invalid: IPv6 only supports /64 host subnets
```
=> config: fix dual-stack config parsing

go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
- fix typo in OvnSingleJoinSwithTopoVersion constant
- for cleanup look only for `join_<nodeName>` logical swtiches
- don't depend on `error message` has an API since they might change
underneath us
@trozet @cathy-zhou PTAL
=> miscellaneous fixes to the OVN logical topology upgrade logic

test/Makefile, test/scripts/e2e-cp.sh
PR: https://github.com/ovn-org/ovn-kubernetes/pull/1324 introduced
the possibility to run a single e2e tests. However, since then we've
split our own tests into "control-plane" tests, and this possibility
didn't exists for that. This PR introduces the same concept for the
control plane tests.
This will now allow us to run tests as:
```
$ make -C test control-plane WHAT="egress IP"
```
and thus run all egress IP tests only. 
=> Possibility to run single control-plane test

.github/workflows/test_periodic.yml
We had a periodic job to test dual-stack, this job was added with
the intention of getting signal on dual-stack, so we could observe
the results.
After the job was stable, it was promoted to presubmit, so we can
gate on dual-stack.
New dual-stack features are being added upstream, so we should test
against those. In order to do that we modify current dual-stack job
to use master kubernetes.
results here https://github.com/aojea/ovn-kubernetes/runs/1319914695?check_suite_focus=true
=> modify the periodic job to run dual-stack against k8s master

go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/ovn.go, go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/metrics/ovn_northd.go, go-controller/pkg/metrics/ovs.go
OVN Kubernetes metrics:
1. sb_e2e_timestamp should be gauge type to match nb_e2e_timestamp
OVN metrics:
1. swap HasPrefix() arguments that were incorrectly used
2. use /etc/ovn path for the OVN DBs
OVS metrics:
1. fix typo in OVS metric name
=> Fix minor issues with metrics for OVS, OVN, and OVN-kubernetes

go-controller/pkg/informer/handlers.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/management-port.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/node/port_claim.go, go-controller/pkg/node/port_claim_test.go
The current code passes `WatchFactory` everywhere and therefore new callbacks are added to the Service/Endpoint watchers throughout the gateway code.
This PR attempts to refactor the local/shared gateway code such that:
- The watchFactory's AddService/AddEndpoint Handler code is invoked only once
- The gateway code itself is responsible for ensuring all of it's component parts are given a chance to respond to these events.
It's required to make progress on replacing the watchFactory with a workqueue.
This isn't perfect but it's serviceable.
It moves all of the local gateway code back in to one place so it can easily be removed at a later date (if necessary).
All gateway functionality is accessed via the …
=> Refactor Local/Shared Gateway code to simplify watches

go-controller/pkg/metrics/ovn_db.go
The name label used so far in upstream ovn-k breaks openshift which
doesn't add the name=ovnkube-db label on the pods. The ovn-db-pod=true
is a more consistent label to use instead for metrics collection.
=> Use the ovn-db-pod label to identify db pods running on the node

go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/management-port.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/util.go
create a types package to and move constants from util into it.
Beginning to refactor the ovn package and split the resources into there
own packages
In addition make the constants closer in line with the golang style conventions
for initlaisms
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
"Words in names that are initialisms or acronyms (e.g. "URL" or "NATO")
have a consistent case."
=> move const decleration for the ovn_cluster_router to a types package

test/e2e/e2e_test.go
- removed the shared gateway since it is the default
in all e2e infra builds now
- removed the gingko dot import for uniformity
- removed a few misc unused variables
Remove shared gw check in e2e ci and gingko dot import
Verify with the following:
```
./kind.sh -gm shared
pushd $GOPATH/src/k8s.io/kubernetes
kubetest --provider=local --deployment=kind --kind-cluster-name=ovn --test
```
=> Remove shared gw check in e2e ci

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go
We desire the shared gateway bridge to have a NORMAL action behavior
when there is an unknown packet that enters the bridge. This is to
support cases where there may be other ports connected to the shared
bridge. However, NORMAL action will not work for the MAC that is shared
between OVN and the host, due to MAC table swapping when a packet hits
the normal action.
This patch adds a higher priority flow to match on destination packets
the shared MAC, and send the packet to the two possible destinations
(OVN and the host). The lower priority flow after it will allow all
other traffic to be NORMAL switched.
=> Fix shared gateway flood/normal behavior

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go
Fixes #1782
With the code updates to fix problems with orphaned ACLs 
in PR #1665 the code for `localPodDelDefaultDeny` was 
changed in order to be able to clean up related 
resources from both `policy.go` and `namespace.go` 
In order to do so, the `knet.policy` object could no longer
be used in the function call since we didn't have access
to it in `namespace.go` 
Therefore the logic used to determined `PolicyType` was changed
to use only the existing `namespacePolicy` fields egressPolicies and 
ingresPolicies. However it had some issues and the number of egress/ingress
rules weren't enough to tell the `NetworkPolicyType` 
For example, if we had a `NetworkPolicy`
that blocked ALL traffic by default but did not contain any 
ingress/egress rules, the new logic would fail to delete the …
=> Fix default deny port removal issue

go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go
Fix Reject ACLs for NodePort and External IP, and node add
The previous patch for moving Reject ACLs to port group only applies the
ACLs to the port group with management ports, which means the ACL will
only get applied to the node logical switch. For NodePort and External
IP those ACLs need to be on the External switches of the GR where the
load balancer is hosted.
Also, the reject ACLs were not getting created/deleted correctly and
some of the unit tests were missing the expected commands.
During node add, we were still adding reject ACLs directly to switches,
instead of letting them naturally take effect through the mgmt port
being added to the port group.
=> Fix Reject ACLs and improve logging

go-controller/pkg/informer/informer_test.go
We are seeing flakes in informers_test only in CI. Probably a timing
issue with slow VMs in upstream. Using this PR to reproduce and fix
them.
=> Fix race in informers_test

test/e2e/e2e_test.go
- Validates that pods can reach a network running in multiple container's
loopback addresses via two external gateways, running on eth0 of the
container, without any tunnel encapsulation.
- This test defines two external gateways and validates ecmp functionality
to the container loopbacks. The loopbacks are identical on both gateways.
- To verify traffic reaches the gateways, tcpdump is running on the
external gateways and will exit successfully once an ICMP packet is
received from the annotated pod in the k8s cluster.
Add e2e testing for multiple ecmp gateway
Verify with the following:
```
chmod +x …
```
=> Add CI for multiple ecmp external gateways

go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/service.go
Cloud load balancers like Azure and GCP deliver external packets
directly to the hosts without changing the destination IP address.
Therefore we have special iptables rules for handling those packets.
However for traffic sourced from within the cluster (an ovn networked
pod), the current behavior sends the packet out of OVN externally
(either via mp0 in local gw mode, or br-ex in shared gw mode) only to be
circulated back into OVN to be load balanced.
Rather than doing this unnecessary traffic forwarding, make OVN handle
the load balancing directly for the egress pod traffic destined to the
load balancer service.
=> Directly load balance traffic to cloud load balancers

go-controller/hack/test-go.sh
GOMAXPROCS will default to whatever is offered by the host CPU.
As we are running in a container, we should respect whatever
CPU limits are imposed on the container. While we could use
automaxprocs to do this, it is simpler for our test cases
to set GOMAXPROCS to 1.
I hope this will solve a number of timing issues that have recently
plagued our unit tests.
Fixes: #1825 #1780
=> test: Set GOMAXPROCS to 1

go-controller/go.mod, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/gateway/gateway.go, go-controller/pkg/ovn/gateway/gateway_test.go
Isolate the OVN Gateway commands in their own package, decoupling
them from the controller so they can be reused and tested separately.
=> decouple ovn gateway commands from controller

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
This PR adds a temporary functionality for egress IP until both RFEs 
- https://bugzilla.redhat.com/show_bug.cgi?id=1881826 
- https://bugzilla.redhat.com/show_bug.cgi?id=1847570 
are implemented
Essentially we need to be checking if all the egress nodes are up, i.e: that the `.node.status.conditions` does not contain a `NotReady` status or that we cannot reach any of the nodes which are in use for egress assignment. In any of these events we need to re-assign the egress IPs which have previously been assigned to any of these egress nodes. The re-assignment procedure should today be correct, i.e: distributing the load (read: egress IPs) across the nodes available and updating the status of the `EgressIP` object accordingly. We are missing the …
=> Fix egress IP re-assignment for network failing node + minor fixes 

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go
Given a scenario where we have:
1. pod A added
2. pod A deleted
3. kubelet has already started CNI ADD for first event
4. pod A added
5. kubelet starts 2nd sandbox CNI ADD
The current code will remove the original OVS interface for the first
event, however the cmdAdd for the first event will still be running
waiting for flows (up to 20 seconds). Really if hte pod loses its
interface, that cmdAdd iteration is now invalid and we should just
return out immediately with an error.
=> CNI: quit waiting for pod flows for obsoleted ADD

go-controller/pkg/node/gateway_localnet.go
The code was assuming the lb ingress needed to be on a node port
service, which is not required. The lb ingress just needs to DNAT to a
cluster IP service to get to the right place.
Shared gw will be fixed in a separate commit.
=> Fix lb ingress service iptables rules for local gw

go-controller/pkg/ovn/master.go
This was causing:
panic: runtime error: index out of range [1] with length 1
goroutine 222 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).upgradeToSingleSwitchOVNTopology(0xc001817b00, 0xc0018ff730, 0x1993b1f, 0x5c)
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/master.go:155 +0x8a8
=> Fix panic during upgrade

contrib/kind.sh
The kind.sh --delete command can hang because the ovn-kubernetes ns delete will cause a loss of connectivity to the network. This PR adds a sufficient timeout to avoid waiting too long, while also giving enough time for the OVN pods to be torn down. Additionally, allow for automatic cleanup of the previous kind deployment when launching a new one.
=> Improve kind cleanup

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_localnet.go
Code was accidentally doing an add for localPortWatcher when it should
be deleting. Also, the comparison for if a service needs update was
insufficient. Changed it to use the same check as ovnkube-master uses
for services.
Note, a separate commit will be coming to fix shared gw mode.
=> Various service fixes

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/types.go, go-controller/pkg/factory/types.go, go-controller/pkg/node/node.go
Runtimes have no way to cancel an ongoing ADD request. So if a pod is added, then very quickly deleted, our CNI may be uselessly waiting up to 20 seconds for OVS flows that will never appear.
Track sandbox ADD requests in the CNI server and allow them to be canceled by a pod watch in the Node.
@trozet
=> cni: cancel sandbox ADD when the pod is deleted

.github/workflows/test.yml
This will run 3 e2e jobs twice a day on master. It will run
with HA and local gateway across each of ipv4, ipv6 and dual
stack.
With these jobs we can better track the health of CI instead
of only looking at jobs that run on PRs which may or may not
be healthy themselves.
=> Add e2e-periodic workflow

.github/workflows/test.yml
Looks like '* */12 * * *' is what would run ovn-ci every
minute past the 12th hour instead of just every 12
hours. It's not actually running it that fast (probably
getting throttled). '0 */12 * * *' will run the job
every 00:00 and 12:00 which is what I'm looking for.
=> Fix mistake in ovn-ci crontab

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go
Following the changes for shared gw mode from:
https://github.com/ovn-org/ovn-kubernetes/pull/1774
This behavior will allow NORMAL action for all packets not destined to
the shared gw mac, thus allowing an non-ovn port to be attached to the
shared gw bridge and function normally.
=> Changes local gateway flows to NORMAL action

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/types/const.go
Our flows for flooding icmpv6 to both OVN and the host were too generic.
This caused ICMPv6 echo requests to be sent to both, resulting in a
duplicate ack and other issues. This patch changes the flows for icmpv6
to be more specific and target only flooding for Neighbor Advertisements
and Route Advertisements. This will allow OVN to receive only the
packets it needs for peering/discovery, while all other ICMPv6 will go to
the host only.
1. deploy kind (./kind.sh -wk 1 -n4 -i6)
2. docker run --network kind --privileged -it centos /bin/bash
3. In docker container ping -6 <node ipv6 ip> verify no dup replies
4. Add ip6 VIP address to one of the nodes breth0 interfaces
5. Ping the VIP from docker container  and ensure a …
=> Fixes ICMPv6 flooding behavior

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Currently when using a namespaceSelector and podSelector in the same network
policy when changing the labels of the namespace nothing happens.
Correct the operation so that when updating the label removes a
namespace from a network policy the pods are correctly removed.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1752220
=> fix network policy when the namespace label changes

go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/ovs_test.go
Sometimes OVS decides to put quotes around external ids:
https://bugzilla.redhat.com/show_bug.cgi?id=1899746
=> Fixes parsing quotes on OVS iface ID

.github/workflows/test.yml
Use 1.19.4 version in the CI, aslo bump the golang version to the latest
=> bump k8s CI version to 1.19.4

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go
The OVN controller was embedding the Kubernetes clientset
under an Interface, thus other methods couldn't use it.
We add a new field in the controller with the Clientset,
so we don't have to modify the kube.Interface each time
that we need a new functionality, that the Kubernetes
clientset provide us for free.
=> expose Kubernetes clientset in the OVN controller

go-controller/pkg/config/config.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/ovn/egressip_test.go
since the egressIP cli is depended on the existance of the flag if you
default to true egressIP will always been enabled because in the
absence of the `--enable-egress-ip` flag the value will default to true
and when the flag is present it correctly reads as true.
Remove the defaulting true on EnableEgressIP so that egressIP is disabled in the
absense of the `--enable-egress-ip` flag
fixes: https://github.com/ovn-org/ovn-kubernetes/issues/1848
=> egressIP defaulting to true causes the wrong behavior.

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
Some unit test debugging could be made easier by enabling
debug log level. This PR changes the log level in `PrepareTestConfig`
which is used from the tests, as opposed to the `LoggingConfig` object.
This was done as to not impact users of OVN-Kubernetes deploying a
cluster without specifying `--loglevel` and modifying the default setting
The idea came from debugging runs such as: https://github.com/ovn-org/ovn-kubernetes/pull/1815/checks?check_run_id=1381157345 
=> Enable debug logging for unit test runs

go-controller/pkg/util/kube.go
Our client will under high load exceed the default QPS (query per second)
and Burst setting when communicating with the API server, which will cause
the client request to get throttled by the API server. These default
values are currently 5 and 10 respectively. Scalability testing has shown that
25 and 25 are values which lead to reasonable pod ready latency times
under high load.
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
=> Increase QPS and Burst setting

go-controller/hybrid-overlay/pkg/controller/node_windows.go
commit https://github.com/openshift/ovn-kubernetes/commit/99e7c6a14e0a81bcc2ad6724ca693251218b5e00#diff-42fa75bc291c6795ed4125c85836441c2ada0c61d6808773c4bbfeb4d116905bL57 attempted to change the call to the kube.Interface
for the node object to a call to a nodeLister but the cache is not
populated at that point during initialization so the call to the
kube.Interface is required
The SharedInformer Start() is called after NewNode() completes
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1902894
=> have to use the kube interface during windows initialization

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
- this commit adds adress family checks to addGWRoutesForPod(.)
to avoid a condition where mismatched address families could
be provided and result in an ovn-nbctl error
Add address family checks to the external gateway feature
Verify by creating a v4 pod in a namespace with an external gateway of v6
and check the ovnkube-master logs for the error thrown
I will followup in separate PRs for the delete method and another with e2e cases added
=> Add address family checks to the external gateway feature

go-controller/pkg/cni/bandwidth_test.go, go-controller/pkg/cni/helper_linux_test.go, go-controller/pkg/cni/ovs_unit_test.go, go-controller/pkg/kube/kube_test.go, go-controller/pkg/testing/testifymockhelper.go, go-controller/pkg/util/go_ovn_test.go, go-controller/pkg/util/net_linux_unit_test.go, go-controller/pkg/util/net_unit_test.go, go-controller/pkg/util/nicstobridge_test.go, go-controller/pkg/util/node_annotations_unit_test.go, go-controller/pkg/util/ovs_unit_test.go, go-controller/pkg/util/util_unit_test.go
This PR consolidates the mock setup code (repeated in multiple unit tests) run as part of unit test into its own separate struct/function for re-usability/maintainability in the pkg/testing/testifymockhelper.go file. 
- There were multiple structs defined (https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/util/ovs_unit_test.go#L20-L25 https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/util/ovs_unit_test.go#L27-L31 and https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/testing/testifymockhelper.go#L3-L7) across files for modelling the mocks that would have been confusing and unmaintainable. …
=> refactor boilerplate mock object processing code in UT into its own struct/function

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/endpoints_test.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go
Changes Include:
1. Removes assumption that Ingress LB service has to be Node Port.
2. Rather than doing DNAT on our shared gateway bridge to DNAT Ingress VIP -> node port, just configure the Ingress on the OVN gateway load balancer and steer traffic there
3. Fixes bugs in endpoint deletion where we were performing a service delete instead of clearing endpoints on the load balancer and creating reject ACLs for External IP and Node Port types
=> Fix lb ingress shared gw and fixes endpoint deletion

go-controller/pkg/cni/cnishim.go
Implementation of the ADD CNI command in  cnishim.go has the following statements:
```golang
func (p *Plugin) CmdAdd(args *skel.CmdArgs) error {
var err error
startTime := time.Now()
defer func() {
p.postMetrics(startTime, CNIAdd, err)
}()
``` 
but the very next statement shadowed the `err` variables:
```golang
conf, err := config.ReadCNIConfig(args.StdinData)
if err != nil {
return fmt.Errorf("invalid stdin")
}
```  
This PR fixes it.
=> Fix shadowed error variable

test/e2e/e2e_test.go
- commit adds a test that validates ingress traffic sourced
from a mock external gateway running as a container
Adds CI e2e for ingress gateway
Verify with the following:
```
./kind.sh -gm shared
pushd $GOPATH/src/k8s.io/kubernetes
kubetest --provider=local --deployment=kind --kind-cluster-name=ovn --test
```
=> Add CI e2e for ingress gateway

go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go
The ACL was accidentally being configured on the cluster load balancer
instead of the gateway load balancer.
=> Fixes Ingress Load Balancer ACL

go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/util.go
This commit adds support for collecting metrics related to subnet
allocation for the node. In particular, metrics for total number
of v4 and v6 subnets allowed in the cluster and metrics for
number of v4 subnets and v6 subnets allocated to nodes are collected.
=> metrics: Add metrics for total and available subnets for nodes

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, docs/ovnkube.1, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/config/utils.go, go-controller/pkg/config/utils_test.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/types/const.go
This PR adds support for making v4 and v6 join subnets used
by the single join switch to be configurable. This is important
because some users may have the 100.64.0.0/16 or fd98::/64 block
routable in their private network and possibly even assigned for
cluster CIDR or service CIDR.
=> config: Make v4 and v6 join subnets configurable

dist/templates/ovn-setup.yaml.j2, go-controller/pkg/metrics/master.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/acl/acl.go, go-controller/pkg/ovn/acl/acl_test.go, go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/repair_test.go, go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/service_tracker_test.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/controller/services/utils_test.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/kube.go
Endpoint Slices
Kubernetes EndpointSlices is the evolution of the Endpoint object, this doesn't mean that Endpoints are going to be deprecated, but they will not receive any new feature.
As an example, only EndpointSlices will support DualStack endpoints, the new Topology aware features, ...
Since we only need to manage one or other object, and we want to implement the latest Kubernetes features, we need to be able to consume Endpoint Slices without breaking previous deployments. In order to do that, OVN will check the Kubernetes API version, and will use Endpoint or EndpointSlices for Kubernetes versions > 1.19.
Since EndpointSlices can have duplicate multiple objects for the same Service and addresses are not guaranteed to be unique, we need to use a Level based approach for its …
=> Dualstack Services with Endpoint Slices

contrib/kind.yaml.j2
Previously, for HA deployements, we were running a 3 node etcd
cluster. This added a lot of pressure on the system, because
etcd is very IO intensive, so we sacrified our RAM to mount etcd
storage on a tmpfs.
However, this has the problem that if someone is using the script
to run clusters locally, the cluster will be wiped out if the
host reboots, because etct information was stored in ram.
We can run etcd with the local storage because we only use one node.
=> don't run etcd in memory

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go
Make sure that the handlers aren't added to the watchFactory until
after the gateway is fully initialized. This stops us dropping
any events.
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
=> node: Fix gateway start ordering

go-controller/pkg/node/gateway_shared_intf.go
=> shared-gateway: ignore empty Ingress IPs

go-controller/pkg/cni/bandwidth.go, go-controller/pkg/cni/bandwidth_test.go, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/types.go
This Pull Request extends ovn-kuberets to implement the CNI CHECK command, from the [SPEC](https://github.com/containernetworking/cni/blob/master/SPEC.md).
As result of this command, the OVN-kubernetes cni plugin will check that container's networking is as expected. 
- The plugin consults the `prevResult` from the ADD command to determine the expected interfaces and addresses.
- The plugin will return an error if a resource listed in `prevResult` (interface, address or route), but is missing or in an invalid state.
- The plugin validates traffic shaping controls (ingress-bandwidth and egress-bandwidth) and will return error if there is a difference between traffic shaping controls defined in the Pod anotations and real settings.
- If a …
=> Add support to the CNI CHECK command

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go
We still see that at high scale, sometimes high latency will cause CNI
ADD to fail and then retry. During this time a subsequent CNI ADD may
succeed by accidentally checking the flows of the previous CNI
interface. This patch adds a check for the OpenFlow port in the OVS
flows to ensure that the flows we are checking are for the new port.
More context here:
https://bugzilla.redhat.com/show_bug.cgi?id=1885761
Props to @dceara for thinking of this solution
=> Adds OFPort to CNI OVS check

go-controller/hack/lint.sh
there seems to be a regression in golangci-lint where the "--modules-download-mode=vendor"
is not supported. Remove the modules-download-mode until the regression
is fixed
Regression Issue: https://github.com/golangci/golangci-lint/issues/1502
=> fix for the linter

go-controller/pkg/ovn/ovn.go
If there are egressFirewall Policies with dnsName filters on them when
restarting an ovnkube-master container the ovnkube-master pod will
segfault because the EgressFirewall tries to add the rule before the
EgressDNS object is created
fix the order in which the EgressFirewall is started so that the DNS
object is started before the Watcher.
https://bugzilla.redhat.com/show_bug.cgi?id=1909911
=> Fix egressFirewall segfault caused by restarting

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/service.go
Simplifies and Closes #1914
Background: 
This PR fixes the problem found here https://bugzilla.redhat.com/show_bug.cgi?id=1903651
When a POD sends traffic to a service it is loadbalanced(DNAT-ed) and sometimes the same pod is chosen as the backend to the service. To ensure this traffic travels through OVN-K8s rather than the POD2POD network since (srcIP==dstIP), the traffic is SNAT-ed to the VIP of the service's loadbalancer, which results in some packet loss with hairpinned traffic since this is not currently accounted for in the network Policy code
**Temporary solution:** 
In the long term, a feature is being created that will allow for us to specify the loadbalancer's SNAT IP in OVN see -> https://bugzilla.redhat.com/show_bug.cgi?id=1908540.  This will allow us to make a few rules to …
=> [BZ #1903651] Add clusterIP to ingress policy AS for SNAT-ed hairpin Traffic 

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/ovn_db.go
This PR exposes ovn db metrics to prometheus for OVN-Kubernetes deployments by CNO.
This PR modifies StartMetricsServer() in ovnkube.go to take in an additional boolean parameter to expose Ovn db metrics on path=/ovnmetrics on the same mux that exposes Node-exporter metrics.
Co-authored by : Sayandeep Sen sayandes@in.ibm.com
Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>
=> Expose Ovn db metrics  for Prometheus 

.github/workflows/test.yml, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, test/e2e/e2e_suite_test.go, test/e2e/e2e_test.go, test/e2e/go.mod, test/e2e/multicast.go, test/e2e/util.go
Enable MLD Snoop and MLD relay to allow multicast connectivity across
nodes. Extend the IPv4 multicast network policies to make them
applicable to IPv6.
=> Add IPv6 multicast support.

go-controller/hack/test-go.sh
the current code that disables the golang race detector feature for
hybrid-overlay controller package doesn't disable it for all cases and
this commit fixes it
Fixes #1946
@alexanderConstantinescu PTAL at this commit. Thanks. We hit this race all the time in our downstream CI (It is not kind based and is a beefy BM server with multiple CPUs)
=> correctly disable race detector for hybrid-overlay controller package

dist/templates/ovnkube-alerts.yaml.j2
Currently, we have a lot of metrics added in ovn-kubernetes.
so, adding alert rules on above metrics for monitoring aspect.
=> Add ovnkube-alert rules.

go-controller/pkg/ovndbmanager/ovndbmanager.go
In some corner cases, when the DB pods are brought up by the daemonset,
the ovn db file may exist. However, it may be in a state where it does
not have itself as a valid raft node or hasn't joined the existing
raft cluster and is therefore not having valid remote server addresses
in the local instance. Our daemonset code assumes that if the db file
exists, it has the right raft information present so that it can sync
with other db instances and rebuild the db. In the above mentioned
edge-case this doesn't hold true and eventually results in master/db
pods that are continuously crash-looping.
This change relies on the periodic cluster status check to ensure that
the local db is part of the cluster (or is atleast a candidate for
the cluster). If on 10 consecutive retries, the cluster status …
=> db: Handle pruning of unhealthy db files on disk

go-controller/pkg/util/ovs_unit_test.go
Fixes: 0589478720 (refactor boilerplate mock object processing code in
UT into its own struct/function)
@vjayaramrh FYI
=> remove the unused fnCallTimes field in unit test related code

go-controller/pkg/ovn/egressfirewall_test.go
Fixes: f18a027078c2 (implement egress firewall using join switch acls
in shared gateway mode)
@dcbw @trozet @danwinship @aojea FYI
Not sure what happened. The github CI didn't flag this error when I re-ran tests on the PR below this morning :-(
https://github.com/ovn-org/ovn-kubernetes/pull/1958/checks?check_run_id=1714304277
=> fix upstream build failure in make check

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Egress IP assignments can change depending on the health check detection
of routes to egress nodes. Once that re-assignment happens we previously
experienced several minutes of packet loss between the source pods and
any external services they were targeting because no GARP was configured
on the external gateway routers by OVN. This lead to several minutes of
interrupted traffic until the ARP cache expired between client and server
for the egress pods.
I am only configuring GARP on egress-assignable nodes, and removing the
configuration once the egress node is flagged as not usable anymore.
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
=> Configure GARP for egress IP re-assignment

go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/repair_test.go, go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go
The new service controller for endpoint slices has a repair
loop that runs once, during the controller startup process,
so we can delete out of sync data between OVN and Kubernetes,
specially to deal with upgrades and OVN new features.
The repair loop was using the controller service tracker as a
source of true, but this is racy because the service tracker
is updated just after the OVN Load Balancer has been configured,
so it can happen that the Service has an OVN loadbalancer, but
doesn´t exist on the service tracker. As a consequence the repair
loops things that is a stale loadbalancer and deletes it.
The repair loop must use the informer cache as source of true, also
it must run before starting the informers workers, so we avoid any
races.
This repair loop will be needed later, once we …
=> fix service controller repair function race

go-controller/pkg/kube/kube.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressip.go
RetryOnConflict() requires that the update function called returns the
error as is without modifying the error, however we were modifying the
error object. With that modification, RetryOnConflict() will not be
able to determine the "Conflict" error
@dcbw @alexanderConstantinescu @JacobTanenbaum PTAL. Thanks.
=> fix RetryOnConflict() call for egressIP and egressFirewall code

go-controller/pkg/ovn/egressgw_test.go
The kubectl commands were being issued before the fakeExec command was
added, which sometimes could result in the test failing if the code was
executed before the fakeExec was added.
=> Fixes flakes in egress gw unit test

go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
add example on how to use the fake client-go to mock
Kubernetes API calls.
=> unit test example with fake client-go

go-controller/pkg/informer/informer.go, go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/node.go, go-controller/pkg/metrics/workqueue.go
This commit adds the workqueue metrics using the defaults
provided by k8s.io/component-base/metrics.
In order to ensure that labels are propagated correctlty we
use NewNamedRateLimitingQueue.
=> metrics: Add Workqueue Metrics

go-controller/pkg/node/helper_linux.go
support multipath to detect default gateway
We were detecting the default gateway based in the assumption that
the netlink library was populating the de Gw field with it, however,
it turns out that when multipath is enabled that field is empty and
the corresponding information is in the MultiPath field.
Also, in order to obtain the default gateway, we were dumping all
routes filtering by FAMILY_ALL, and iterating on the results to get
the ones we are interested. We can filter directly by the IP Family instead,
to avoid future possibles problems with the FAMILY_ALL interpretion.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1914250
=> detect default gateway

dist/images/.gitignore
ovnkube-trace is now built in go-controllers, and copied to the images
directory, but not included in .gitignore. This fixes that.
Signed-off-by: Stephen Kitt <skitt@redhat.com>
=> images: ignore ovnkube-trace

go-controller/pkg/node/gateway_init.go
a golang interface has two values <type, value>. an interface is nil
if both type and value is nil. so, you cannot directly set the value to
an interface and later check if value was nil by comparing the
interface to nil. this is because if the value is `nil`, then the
interface will still hold the type of the value being set.
with the current code we were hitting SIGSEGV in Service's AddService
handler() where we were doing this:
```
func (g *gateway) AddService(svc *kapi.Service) {
if g.portClaimWatcher != nil {
g.portClaimWatcher.AddService(svc)
}
if g.loadBalancerHealthChecker != nil {
g.loadBalancerHealthChecker.AddService(svc)
}
<Snip>
}
```
even though `portClaimWatcher` was not set we were calling its
AddService function and thereby causing the panic
@dcbw @trozet @danwinship …
=> golang interface holding nil is not always nil since it holds type too

dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go, go-controller/pkg/types/const.go
this feature enables ACL logging for all drop/reject/allow actions
if specified in metadata annotations for Namespace, example:
```
kind: Namespace
apiVersion: v1
metadata:
name: tenantA
annotations:
k8s.ovn.org/acl-logging: '{ "deny": "alert", "allow": "notice" }'
kind: Namespace
apiVersion: v1
metadata:
name: tenantB
annotations:
k8s.ovn.org/acl-logging: '{ "deny": "notice" }'
```
the logging events then can be viewed in OVN controller's log and
will be marked with selected ACL severity level and name set to
a namespace that generates the event.
to make per namespace deny logging configurable as well as to
somewhat make things a bit cleaner, we moved default deny port group
to be part of namespacePolicy. If anything, we expect things to
potentially scale even better, because of reduced …
=> support for ACL logging

go-controller/Makefile, go-controller/hack/test-go.sh
Co-authored-by: Aniket Bhat <anbhat@redhat.com>
This PR adds the ability to run tests (including those requiring sudo such as tests in pkg/node and hybrid-overlay/pkg/controller) inside of a golang 1.15 docker container. Allows for running tests on non-linux systems as well.
Execute `make check` or `make test` on your development system that has docker installed from the ovn-kuberentes/go-controller directory.
=> allows for running all tests inside a container

dist/images/Dockerfile.fedora, dist/images/Dockerfile.fedora.dev, dist/images/Makefile
current version fedora:32 will install older version.
newer version needs to be tested on more periodic basis as per master branch
Signed-off-by: Dmitry Yusupov <dyusupov@nvidia.com>
=> switch to newer fedora:34 so to enable ovn 20.12

go-controller/pkg/ovn/ovn.go
Currently we require that if you specify an external gateway that corresponds
to a multus network, then you must do so as a pod update to add the exgw
annotations. This is due to the fact that multus will not add the network
attachment definition until after OVN CNI runs, and therefore OVN will not be
able to locate the exgw information. The current workflow is this:
1. Create exgw pod (OVN will add pod, multus will add network attachment def)
2. Once created, edit the pod and annotate it with the exgw annotations that
link to a multus network:
k8s.v1.cni.cncf.io/network-status: "[{\"name\":\"blah\",\"interface\":\"net1\",
\"ips\":[\"172.18.0.4\"],\"mac\":\"62:ff:69:f0:83:03\",\"dns\":{}}]"
k8s.ovn.org/routing-namespaces: exgw
k8s.ovn.org/routing-network: blah
However, we should be able …
=>  [fixes BZ #1916872] Handle Multus network-status annotations on pod update

test/e2e/e2e_test.go
the signature for this function is:
(c clientset.Interface, ns, podName string)
but this was passing podName and namespace in the wrong
order. This fixes that.
https://github.com/kubernetes/kubernetes/blob/64c099d67069f85f2b9b78d7d12fd1a92fcc3d75/test/e2e/framework/pod/wait.go#L362-L364
func WaitForPodNotPending(c clientset.Interface, ns, podName string)
error {
return wait.PollImmediate(poll, podStartTimeout,
podNotPending(c, podName, ns))
}
note that this same function was called correctly
in a different place in this file.
=> Swap ns and podName args in WaitForPodNotPending()

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
Each ovnkube-node stores address of the Northbound DB as `external_ids:ovn-nb` in the `Open_vSwitch` table at the local OVSDB. This setting is not used anymore.
=> remove the obsolete setting of NB DB address to OvS

contrib/kind.sh
installing to system dir can fail with permission errors
=> Add --user arg to pip install wheel

go-controller/Makefile, go-controller/hack/lint.sh
This commit allows the linter to be run with podman
as the runtime. It also removes the dependency on
GITHUB_ACTIONS env for checking if the make target is
container runnable.
=> Allow for linter to run with podman as a runtime

test/scripts/e2e-kind.sh
When doing:
```
WHAT="$TEST_NAME" make -C test/ shard-test
```
locally, the E2E tests were not launching and instead raising a failure and refusal to launch the tests with complaints such as:
```
S [SKIPPING] [38.319 seconds]
[sig-network] Networking
/home/aconstan/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:23
Granular Checks: Services
/home/aconstan/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:149
should function for service endpoints using hostNetwork [It]
/home/aconstan/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:490
Requires at least 2 nodes (not …
```
=> Set --num-nodes in e2e-kind.sh

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/gogo/protobuf/proto/text_parser.go, go-controller/vendor/modules.txt
Update gogo/protobuf to v1.3.2 to fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121. The k/k fix is here: https://github.com/kubernetes/kubernetes/pull/98477 
Here are the steps I used:
cd go-controller
go list -m all |grep gogo/protobuf
go get github.com/gogo/protobuf v1.3.2
go mod vendor
Add:
`github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2
`
in the replace section in go.mod, to make sure we only use this version.
go mod tidy
Signed-off-by: vpickard <vpickard@redhat.com>
=> [Fixes BZ #1924535] Update gogo/protobuf to v1.3.2

test/scripts/e2e-kind.sh
Bumping e2e flakes from 3 to 5 to avoid race failures. Skipping host endpoints with a service due to https://bugzilla.redhat.com/show_bug.cgi?id=1927046
=> Fix CI stability

test/scripts/e2e-kind.sh
These are flaking consistently in KIND. We dont really care about these
tests anyway so skip them.
=> Skip AdmissionWebhook confformance tests

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_unit_test.go, go-controller/pkg/testing/mock_acl.go, go-controller/pkg/testing/mock_ovn.go, go-controller/pkg/testing/mock_stubs.go
This PR replaces the usage of `util.RunOVNNbctl()` function with the goovn bindings `ACLAdd` API for creating ACL rules.
Unit tests for the impacted function `addAllowACLFromNode()` has been added
Note1. There are no instances of `acl-del` being invoked in the codebase
Note2. References to `acl-add` in the test code are removed as well per suggestion from @abhat .  
=> refactor: using goovn bindings for adding ACL in addAllowACLFromNode()

dist/images/Dockerfile.fedora, dist/images/Dockerfile.fedora.dev, test/scripts/e2e-kind.sh
F34 is not released and we are hitting issues in CI with rawhide repos. Move back to F33. Skip disruptive tests that bring down api server and do other bad things we dont want to happen during CI.
=> Revert to fedora33 and skip disruptive tests

dist/templates/ovnkube-node.yaml.j2
ovnkube-node Pod has preStop hook defined that cleans up bunch of things
on the k8s node.
-- deletes the patch port between the br-int and physical ovs bridge
-- replaces the OVS bridge flow with a single flow with NORMAL action
-- in some instances, where applicable, it also deletes the physical
ovs bridge.
All of the above cleanup needs to be done on Node deletion. So, remove
the preStop hook for now and determine later on how to use the cleanup
code on node deletion.
@trozet PTAL
=> ovnkube-node Pod restart will break external nw connectivity for pods

test/scripts/e2e-kind.sh
Instead of just skipping Webhook, skip all sig-api-machinery tests as we
are seeing new flakes from tests like:
[Fail] [sig-api-machinery] Aggregator [It] Should be able to support the
1.17 Sample API Server using the current Aggregator [Conformance]
=> Skip all sig-api-machinery tests

go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go
Fixes dualstack reject ACL to work like single stack service/endpoints controllers work. Note, there is an issue where when endpoints are added to a service, and then removed the reject action will no longer worked. This is tracked by https://github.com/ovn-org/ovn-kubernetes/issues/2045 and will be fixed later when we move to reject on load-balancers. For now this makes dual-stack behavior inline with single-stack.
=> Fix reject acl for dualstack

test/e2e/e2e.go, test/e2e/util.go
Add a test that verifies the ingress traffic to nodeport services.
This is heavily inspired by kubernetes networking tests, and done by creating an external container and using the agnhost netexec command to connect to each node's exposed service checking if endpoints on each node can be reached through that.
This depends on https://github.com/ovn-org/ovn-kubernetes/pull/1990 , and includes its commit.
This is because we needed to be able to set the ipfamily of the service as "preferdualstack" in order to validate both ip families.
=> E2E: Add a nodeport connectivity test

go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovndbmanager/ovndbmanager.go
Will periodically release memory back to the OS.
=> Enable DB memory trimming on compaction

contrib/kind.sh, go-controller/pkg/util/nicstobridge.go
remove ovnkube workaround for single-stack ipv4
always enable ipv6 inside kind nodes, docker disables ipv6
globally inside containers by default, but in eth0.
kind enables ipv6 for dual-stack and ipv6 deployments, not for
the ipv4 ones.
ovnkube-node, when trying to copy over the addresses from the
gateway interface, fails because the IPv6 addresses can be
added to the ovs bridge interface, since ipv6 is disabled on it.
=> remove ovnkube workaround for single-stack ipv4

go-controller/pkg/util/kube.go
The detection of the kubernetes version fails in the CI, because the library doesn't parse minors versions that are not only numbers, i.e v1.21.0-alpha.1, that are typically all the clusters that run in the CI.
We really don't need to check the kubernetes version, because the controller can work without dual-stack , it only needs that the cluster has endpoint slices enabled.
=> detect if the cluster has endpoint slices

go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/ovn/egressip_test.go
The hybrid overlay test: `sets up and cleans up a Linux node with a OVN hostsubnet annotation`
was flaking because those tests don't use `NewLooseCompareFakeExec` and it didn't wait for the
add commands to be evaluated before proceeding to the delete part of the test. This patch
does that.
Flake seen here: https://github.com/ovn-org/ovn-kubernetes/pull/2051/checks?check_run_id=1914437125
The egress IP test: `should re-assign EgressIPs and perform proper OVN transactions when pod
is created after node egress label switch` was flaking because the retrieved status might be
empty while the tests are running, in which case we had panics observed during the test
execution. Thus check the status length
Flake seen here: https://github.com/ovn-org/ovn-kubernetes/runs/1919318009?check_suite_focus=tr …
=> De-flake unit test

dist/images/ovnkube.sh, go-controller/hack/build-go.sh, go-controller/pkg/util/kube.go
Currently, on the API Server we don't see the version of K8s client-go
bindings that ovnkube is using. We see this:
user-agent:ovnkube/v0.0.0 (linux/amd64) kubernetes/$Format
With the fix, you will see
user-agent:\
ovn-worker1/ovnkube@d085b888c981 (linux/amd64) kubernetes/v0.20.0
@aojea @dcbw @trozet PTAL
=> capture version of kubernetes client used by ouvnkube in HTTP user-agent

go-controller/pkg/testing/mock_ovn.go
Co-authored by: Sayandeep Sen sayandes@in.ibm.com
Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>
This PR fixes a typo in ExecuteMockCommand() in pkg/testing/mock_ovn.go
=> Fix typo: delete -> update

dist/images/Dockerfile.fedora
Due to a regression in OVN, service hairpinning no longer works, which
means some of our E2E tests are failing.
=> Temporarily downgrade OVN

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
`assignmentRetry` was mistakenly assumed to be thread safe. This is not
the case for the `Range` function. This means that if we have two nodes labelled
as egress nodes concurrently, we will have a subtle data race and possibly
end up deleting the setup done for node 1 by node 2 (since also: the egress
IP setup is not idempotent - we delete then add).
This patch changes it to a proper map with a mutex as to ensure that the
entire iteration over the map during the re-assignment remains thread safe.
It also ensures that we have an ordered assignment of a new / updated egress
IP while a node is added for egress IP assignment.
This issue has been seen here: https://github.com/ovn-org/ovn-kubernetes/pull/2055/checks?check_run_id=1924245680
**- …
=> Change assignmentRetry for egress IP to a proper map + mutex

go-controller/pkg/ovn/policy.go
currently, we don't check if the pod is scheduled or not. we blindly
updated the address_set with the same set of IPs. this causes all of
the OVN chassis to receive updates from the oVN SB and act upon it.
avoid all this unnecessary churn.
@dcbw @trozet @danwinship PTAL
this was causing unnecessary churn in large scale cluster when pods were in this Pending -> Terminating cycle.
=> avoid updating address sets if the pod is not scheduled to a node yet

.github/workflows/test.yml, contrib/kind-dual-stack-conversion.sh, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/subnetallocator/allocator.go, test/scripts/e2e-kind.sh
Fix several issues while converting an OVN IPv4 single stack deployment to dual stack.
It does an scripted conversion from single to dual stack:
- updates kubernetes components to enable the dualstack feature
- updates kubernetes components with secondary cidrs
- updates ovn config with secondary cidrs
- restart ovnkube-master and ovnkube-nodes to pick the new config
To run it just create the single stack cluster with `kind.sh` and once it finish run this new script.
Added 2 presubmit jobs that test the conversion.
=> OVN convert from single to dualstack

README.md, docs/INSTALL.UBUNTU.md
The AWS server (3.19.28.122) that hosted the debian packages is unavailable, references to the server mislead users.
This PR removes these references.
=> Remove obsolete references to 3.19.28.122

test/e2e/e2e.go, test/e2e/go.mod, test/e2e/go.sum, test/e2e/util.go
Extend the current `e2e multiple ecmp external gateway validation` test to cover TCP, UDP, IPV4, IPV6
This will provide more coverage.
This PR is based on https://github.com/ovn-org/ovn-kubernetes/pull/1991, which in turn is based on two more prs.
The commits relevant to this change are only the two last ones (those introducing the `e2e multiple ecmp external gateway validation` test)
=> E2E tests: extend the gw test to cover ipv6 / multiple protocols

dist/images/ovndb-raft-functions.sh
The recent OVS commit e8451e144 updated cluster/status output and the
existing code to get election timer no longer works. This commit fixes
that.
=> need changes to adapt to the new cluster/status output

go-controller/pkg/ovn/policy.go
While debugging on dual-stack KIND setup, ovn-trace
failed due to || and && grouping, with this error
msg:
ovntrace|WARN|reg0[7] == 1 && (outport == @a14390016336330567584 &&
(ip4.src == $a8720055785936351439 && ip4.mcast || ip6.src ==
$a8720057984959607861 && (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))):
parsing expression failed (&& and || must be parenthesized
when used together.)
Signed-off-by: vpickard <vpickard@redhat.com>
=> Fix ACL syntax for dual-stack

dist/images/Dockerfile.fedora
=> Bump OVN to latest from advisory

go-controller/pkg/ovn/address_set/fake_address_set.go
The way the testing function EventuallyExpectEmptyAddressSet() can
fail the first time it is run with the right configuration options
and not do what the developer expects which is retry until timeout
switching the check will make sure that the test function is always
working as intended
=> changed EventuallyExpectEmptyAddressSet() to do what it says

go-controller/pkg/node/node.go
The nodes need to watch the endpoints in order to delete the stale
conntrack entries.
We were using DeepEqual to compare the endpoints structures, however,
this adds a big penalty that is unneccesary since we are going
to compare both the new and old Endpoints object later to obtain
only the new entries.
=> don't compare endpoints on nodes

go-controller/pkg/ovn/ovn.go
Today when we process a node update we don't check if there has
been a change to the node subnet when determining if we should
resync the management port config in the OVN DB. This will lead
to stale data in the OVN DB and networking not fully working on the
affected node(s). This patch does that.
=> Resync node management port on subnet change

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/util/iptables.go, go-controller/pkg/util/net.go
This patch refactors the iptables rules setup for `NodePort` and `ExternalIP` specific services. Mainly it does the following three things:
- It adds an additional filter on the node IP for `NodePort` type services, this fixes #1981 
- Fixes small issues in the iptables setup w.r.t. dual-stack clusters
- Removes the `filter FORWARD` setup for `NodePort` and `ExternalIP` services. That chain is used for routing packets which do not have the node IP as source nor destination IP, essentially just forwarding it to another node. However, for `NodePort` and `ExternalIP` services we just DNAT the packets on the gateway IP / Cluster IP (depending on the mode we're running in). The problem with adding `NodePort` and `ExternalIP` services to filter …
=> Refactor iptables rules for NodePort and ExternalIP services

.github/workflows/test.yml, go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/unidling/ovn_event.go, go-controller/pkg/ovn/controller/unidling/ovn_event_test.go, go-controller/pkg/ovn/controller/unidling/unidle.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, test/e2e/unidling.go
Enable new endpoint slice controller.
Move the unidling controller code to its own package.
Add e2e test.
=> enable new endpoint slice controller (and fix service idling)

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/util/net.go
- Fix the multicast allow policy to not drop IGMP/MLD packets generated by ovn-controller in namespaces with multicast enabled.
- Use a link local IPv6 address (based on router port MAC) for mcast_ip6_src to generate valid MLD queries.
=> Fix multicast querier.

go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/services_controller.go
we don't need RetryOnConflict() in RunOnce() since we are not making
any resource update in the function it calls. so, there is not going
to be any conflict that will be returned
while there also remove RunUntil() since its not currently being used
@aojea @trozet PTAL
=> RetryOnConflict() is meant for resource update and expects unchanged err

contrib/kind.sh, go-controller/pkg/node/gateway_shared_intf_linux.go
We found downstream https://github.com/openshift/ovn-kubernetes/pull/440 that the ipv6 bare metal job was failing. This was because the host -> kapi service was not working. This is because the DGP mac was changed in 380e80f389dad997f9f97c030eb89d8abce4204f for OVN config, but the corresponding change was not made to the OVS interface. Therefore all DGP traffic in ipv6 deployment was getting dropped in the host.
The question then was how was this passing in our upstream CI? This was passing because even though we delete kube-proxy post install, it was leaving behind its iptables rules, which includes DNAT for KAPI service. Thus our CI was falsely passing.
This PR removes those leftover kube-proxy iptables rules, and changes the OVS MAC to match the DGP.
=> Fixes incorrect services in KIND CI and DGP MAC

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/ovn/master.go, go-controller/pkg/testing/mock_chassis_private.go, go-controller/pkg/testing/mock_ovn.go, go-controller/pkg/testing/mock_stubs.go, go-controller/pkg/testing/mocks/github.com/ebay/go-ovn/Client.go, go-controller/vendor/github.com/ebay/go-ovn/chassis_private.go, go-controller/vendor/github.com/ebay/go-ovn/client.go, go-controller/vendor/github.com/ebay/go-ovn/common.go, go-controller/vendor/modules.txt
This PR contains
1)  Update to latest version of go-ovn to support chassis_private table 
-updated to github.com/ebay/go-ovn v0.1.1-0.20210217205951-16f56680e2c0
2) Latest release of OVN have introduced Chassis_Private Table which
contains private information of given chassis. When a node is deleted,
need to delete corresponding chassis record from Chassis_Private Table
along with chassis Table.
3) updated mocks to support new chassis_private table APIs.
=>  Chassis_Private record must be deleted along with Chassis record

go-controller/pkg/ovn/ovn.go
Egress IP is still flaking in CI. I believe the cause of this is due
to not wrapping updating the egress IP status in the retry assignment
executin. On slow servers there can be a conflicting update when the
nodes are labelled and the egress IP is added during our e2e tests.
Wrapping the update part in the mutex execution will enforce that only
one update is done at a time, either when a node is added and the egress
IP is re-assigned, or when the egress IP is added / updated.
Flakes seen here: https://github.com/ovn-org/ovn-kubernetes/pull/2093/checks?check_run_id=2036750987 and here: https://github.com/ovn-org/ovn-kubernetes/pull/2074/checks?check_run_id=2010128791
**- …
=> Fix: egress IP flakes, wrap update in mutex execution

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go
The clean up of OVN Logical Topology and other runtime state that we do
on ovnkube is best effort. in deleteNode() callback we were doing both,
-- continuing on some errors
-- returning on some errors
As it stands today, the cleanup is best effort as it stands today. So,
the code needs to be consistent in what it is doing.
@dcbw @trozet others PTAL
=> node deletion tasks on ovnkube manager node is best effort

docs/network-policy.md
This is a continuation of the work started with #1182 
and also addresses the unresolved comments there
It updates the network policy documentation and adds
some examples
It will also include breaking off the `multicast`
feature documentation into it's own readme
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
=> Update Network Policy Documentation

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_test.go
Rather than issuing a separate ovn_nbctl call for every ip in `AddIPs(ips)`, fold them in to a single command.
=> pkg/ovn/address_set: batch changes

test/e2e/external_gateways.go, test/e2e/images/Dockerfile.frr, test/e2e/util.go
We clone the external gateway tests with a difference: bfd is enabled
both on ovn side and on the containers (using a custom container via frr).
We check that ecmp works with two containers, then we remove one
container and check that all the traffic reaches the remaining
container.
This PR depends and needs to be merged after https://github.com/ovn-org/ovn-kubernetes/pull/2029 and https://github.com/ovn-org/ovn-kubernetes/pull/2077
It's currently consuming a dockerfile image from personal quay repo because I needed an image with FRR (the dockerfile is committed as part of this pr)
=> External gateway pod tests: Cover BFD

go-controller/pkg/factory/factory.go
In the large-scale environment, node status watcher on every k8s node
could be a burden to k8s apiserver. Disable it if ovnkube node not in
hybrid-netwrok mode.
=> factory: Disable node status watcher if node not in hybrid mode

go-controller/pkg/ovn/policy.go
The updateFunc in handlePeerService when a service is updated casts the previous / old objects to kapi.Service (instead of pointers). This may result in a runtime.TypeAssertionError and a crash of kube master.
=> Fix service update for policy type assertion

go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
hybrid-overlay is experiencing an issue where fatal errors are not being
logged when logging to a file using the `logfile` flag. This commit
makes it so that the error is logged properly before the program exits.
hybrid-overlay logs errors properly before exiting due to an error
=> Properly log when hybrid overlay errors out

test/scripts/e2e-kind.sh, test/scripts/install-kind.sh
Just use latest and avoid hardcoding links which will be removed in the
future.
=> Fix dead link for k8s test binaries

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/ovn.go
When adding SNAT per pod with an existing entry, the code will fail and
report an error because with OVN we cannot do lr-nat-del and lr-nat-add
in the same OVSDB transaction. This is because OVSDB evaluates the
lr-nat-add and thinks there will be a conflict because an entry already
exists.
Additionally, during gateway init for a node, this failure may also
occur. In which case the GR will be left with missing config.
To handle this case, split add and delete into separate transactions,
and only del/add if the entry is missing.
=> Fixes errors when adding NAT with existing entry

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/util/ovn.go
- Policy was not working because the inport has to be quoted
- Handle ipv6 addresses with the policy
- Create MAC Binding for DR IP. Without this the traffic is flooded
from OVN cluster router because it cannot learn the the DR MAC.
=> More hybrid overlay fixes

go-controller/hack/build-go.sh
modify CGO build flag for ovn-k8s-cni-overlay binary since its build at the host and it has runtime dependency on some libraries for more details pls. refer to  #2108  
changed CGO_ENABLED env setting to 0 only when building ovn-k82-cni-overlay
bring up ovn KIIND cluster on Fedora 33 where it has glibc33 while ovn CNI expects glibc32 w/o  the fix DNS POD stuck in Starting Container state forever
build ovn-k8s-cni-overlay with CGO_ENABLED=0 while keep it enabled for other binaries
=> modify CGO build flag for ovn-k8s-cni-overlay binary

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
For the default Deny ACL
- name= %Namespace_%NetworkPolicy
- Although the NP to ACL relationship here can be many to one
- This should clarify the most relevant policy most of the time
For each ingress Rule ACL
- name = %NetworkPolicy
- So that we can maintain a relationship between ACLs and Network Policies
For allow ARP ACL
- name = Namespace_ARPallowPolicy
For Multicast ACL's
- name = MulticastAllowEgress
MulticastAllowIngress
DefaultDenyMulticastEgress
DefaultDenyMulticastIngress
DefaultAllowMulticastEgress
DefaultAllowMulticastIngress
=> Change naming conventions for network policy ACL's

go-controller/pkg/ovn/acl/acl.go, go-controller/pkg/ovn/acl/acl_test.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/service_test.go, go-controller/pkg/types/const.go, test/e2e/e2e.go
This PR performs the following major changes for egress firewall:
- Changes egress firewall in local gateway mode to use ACLs on the nodes' logical switch. As supposed to PR: #1901 which applied that on the join switch: we cannot do that in local gateway mode since traffic does not flow through the join switch. The genesis for this change is because previous implementation of egress firewall as logical router policies conflicted with egress IP and rendered the features mutually exclusive if one pod happened to match both.
- It re-works the way egress firewall filters out east <-> west traffic. Previously this was done by using an inequality operator on the match condition. This is however dangerous as it can lead to an excessive amount of …
=> Re-work egress firewall to use ACLs + miscellaneous fixes  

go-controller/pkg/testing/mock_ls.go, go-controller/pkg/testing/mock_stubs.go
Co-authored by : Sayandeep Sen sayandes@in.ibm.com
Signed-off-by: Palani Kodeswaran <palankod@in.ibm.com>
This PR 
- moves Logical Switch mock functions into a separate mock_ls.go file 
- implements Logical Switch functions for the mocks
=> Support go-ovn Logical Switch functions in mock infrastructure

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/types.go, go-controller/pkg/node/node.go, go-controller/pkg/types/const.go
Detect if OVN supports setting the OVS.Interface "ovn-installed"
external id [0] when OVS flows corresponding to a logical flow have
been installed.  If so then change the pod interface readiness check
to wait for the external id to be set by ovn-controller
For backwards compatibility, on older OVN versions, use the legacy
pod readiness checks, i.e., check for specific OVS flows to be
installed.
On upgrade, CNI Server will dynamically switch to new mode after master
upgrade.
[0] ovn-org/ovn@4d3cb42
Co-authored-by: Tim Rozet <trozet@redhat.com>
=> cni: Use new port-up OVN notification mechanism (when possible).

go-controller/cmd/ovnkube/ovnkube.go
ovnkube will no longer restart if it detects a change on the
configuration file. This is risky and can lead in unexpected
restarts of the container causing disruptions or issues that
are hard to track by the cluster admins.
=> don't exit on config changes

go-controller/Makefile, go-controller/hack/test-go.sh
This commit adds support for passing ginkgo focus arguments to
Makefile. In particular, this adds support for GINKGO_FOCUS
environment variable to be honored. Also certain tests that require
sudo were not working correctly with the test-go script. This
commit also fixes the error with running those unit tests.
=> Improvements to unit test scripts

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/ovn/master.go
When the master is terminated instead of just exiting, give leader
election a chance to release the leader lock so another ovnkube
master can grab it while this instance is down.
@trozet @abhat @squeed
=> master: cancel leader election on exit

go-controller/pkg/ovn/acl/acl.go, go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/repair_test.go, go-controller/pkg/ovn/controller/services/service_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/controller/services/utils_test.go, go-controller/pkg/ovn/endpoints.go, go-controller/pkg/ovn/endpoints_test.go, go-controller/pkg/ovn/gateway.go, go-controller/pkg/ovn/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/service.go, go-controller/pkg/ovn/service_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, go-controller/pkg/util/ovn.go, go-controller/pkg/util/ovs.go, test/e2e/unidling.go
This PR replaces the current ACL reject rules for services with no endpoints with the creation of a "idling loadbalancer" where we moves the VIPs when a given service has no endpoints.
=> Replace ACL reject rules with a reject=true loadbalancer for services without endpoints

dist/images/Dockerfile.fedora
Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
As I was poking around with ovn-kubernetes troubleshooting, going through some material from @dcbw , I stumbled upon `ovs-tcpdump`. Although this command was not found on any of the pods. In order to rectify that, it was suggested to me that we could add that to the `Dockerfile`.  Hence this PR. 
Just added `openvswitch-test` package to Dockerfile.
On any of the pods, you can check `rpm -qa | grep openvswitch-test` or just run `ovs-tcpdump -h` and command should output help text, and should not complain `command not found`. 
Adding openvswitch-test package for easy debugging, as it provides …
=> Adding openvswitch-test package so that ovs-tcpdump is available in all pods

contrib/kind.sh, dist/images/daemonset.sh, dist/templates/ovnkube-node.yaml.j2
Newer container runtimes pass to CNI the Pods
network namespace path in /var/run/netns.
If the Pod's network interface plumbing is done
in ovnkube-node and not ovn-k8s-cni-overlay.
it will fail to find the namespace as the Pod's
network namespace path is not available in ovnkube
node container.
This was encountered in:
CRI-O 1.19
Containerd 1.4.4
To solve it, mount host /var/run/netns in ovnkube-node
container.
=> Always mount /var/run/netns for ovnkube node

dist/templates/ovnkube-master.yaml.j2, go-controller/cmd/ovn-kube-util/app/readiness-probe.go
While reading through the readiness probes, I found it odd to call "version" as to check the readiness of nbctl and northd. But checking with @trozet @dcbw helped understand it is still valid and acceptable to check the version to determine readiness of the pods, because `ovn-appctl` still connecting to the app/daemon to determine the version. To remove the confusion, specially for readability to new contributors, it could be useful to have some comments there. 
In addition to that, I found that the `target` parameter was being not used/passed to readiness probe function correctly. Fixing that too. 
This is my 1st PR to this repo. Hoping to get your kind reviews and get it merged. 
I was …
=> Adding docutext and fixing usage of target

go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/service.go
Sometimes the LB Ingress is a hostname, in which case the IP is empty.
@trozet @fedepaol
=> services: don't assume Status.LoadBalancer.Ingress IPs are populated

go-controller/Makefile
Run containers in interactive mode + allocate a TTY.
This allows for them to respond to the CTRL+C signal.
Useful when you are debugging tests that are hanging...
Or have accidentally run the wrong make target
Also add `--rm` to ensure that old containers are deleted
=> Makefile: Allow CTRL+C when running in container

go-controller/pkg/ovn/common.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/ovn/port_group_unit_test.go, go-controller/pkg/testing/mock_ovn.go, go-controller/pkg/testing/mock_portgroup.go, go-controller/pkg/testing/mock_stubs.go
This is part of an effort to use go-ovn bindings instead of RunOVNNbctl commands.
- Modified functions to add/delete port groups, and add/remove ports from port groups to use go-ovn instead of RunOVNNbctl
- Updated existing code to use these functions instead of RunOVNNbctl for port group operations.
- Implemented mocks for new commands.
- Updated integration/unit test cases to work with go-ovn-based code.
- Add new unit tests for port group functions.
This was verified as follows:
- Running e2e policy test cases
- Excuting ginkgo-based integration test cases
- New unit test cases.
=> Use go-ovn bindings for port group commands

go-controller/pkg/ovn/ipallocator/allocator.go, go-controller/pkg/ovn/ipallocator/allocator_test.go
Changed the code to use utilnet and place IPv6 CIDR max limit to avoid overflow
Updated allocator test cases accordingly
```
Note: 
Valid IPv6 IPs ranges from base to base + 65536 where base is the IPv6CIDR + 1
this is a known limitation for the current POD's IP allocation algorithm.
```
Calculating bitmap index used by allocator using IPv6 CIDR can exceed Int64 value which is the max that the allocator alg can manage, switching to utilnet prevent exceeding that limit
**- Unit test**
[mmahmoud@mmahmoud ipallocator]$ go test -v -vet=off
=== RUN   TestAllocate
allocator_test.go:84: base: [255 255 192 168 1 1]
allocator_test.go:84: base: [32 1 13 184 0 1 0 0 0 0 …
=> Bug 1940233: setting max offset for IPv6 CIR to prevent overflow

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go
When we have this configuration enabled, there should be no SNAT entry
for the pod subnet on the GR. Instead there should be per pod SNAT
entries added. On upgrade or enabling this feature we were failing to
remove any previous SNAT entries here.
=> Ensure no SNAT on GR for DisableSNATMultipleGws

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_test.go
we have,
```
external_ids        : {name=kube-system_v4}
external_ids        : {name=default_v4}
external_ids        : {name=default.access-web.egress.3_v4}
external_ids        : {name=kube-public_v4}
external_ids        : {name=ovn-kubernetes_v4}
external_ids        : {name=default.access-web.ingress.0_v4}
external_ids        : {name=kube-node-lease_v4}
external_ids        : {name=default.access-mysql.ingress.0_v4}
external_ids        : {name=default.access-web.egress.0_v4}
```
so, there is only one part of key=value in `external_ids` and this
results in ForEachAddressSet() not calling the iterator function.
@dcbw PTAL
=> fix ForEachAddressSet() as it is not calling the callback functions

go-controller/pkg/ovn/ovn.go
Egress IP initializes a "watcher" which health checks connectivity to egress
nodes every 5 seconds. This is done in its sync function. However, due to a
bug in the state initialization in WatchEgressNodes we don't set the
different egress node fields correctly in our ADD func which screws up the health
check detection mechanism upon a ovnkube-master restart.
Essentially it goes like this:
1) egress setup is made
2) there's a problem with connectivity to the egress node(s)
3) ovnkube-master is restarted
Once step 3) is made: it is expected that ovnkube-master will perform
health checks continously and detect when the connectivity in step 2) is
back up. However because of this problem that is not the case and even
if further connectivity is successful, we never flag the node as such in
our …
=> Fix: egress IP route health check detection state on restart

test/e2e/unidling.go
When the service times out but it should not, 5 seconds are not enough
for the eventually. 3 seconds are consumed by the first timeout, and it
could exceptionally happen that the second attempt lasts longer than 2.
Here we lower the timeout and wait for longer for the right config to
get in place.
=> Unidling: make the wait shorter / check for longer time

go-controller/pkg/node/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/node_annotations.go
Today, when a node is deleted from the cluster, its chassis entry is
deleted from sbdb by ovnkube-master, but it can be soon added back by
ovn-controller. This stale chassis entry prevents new one being added to
sbdb when the node is added back to the cluster with a different
chassis id.
This commit checks node's chassis annotation and delete the stale
chassis from sbdb if the annotation suggests there is a change of
chassis id.
=> delete stale chassis from sbdb when nodes' chassis annotation change

go-controller/pkg/node/gateway_shared_intf.go
OVS HW offload is unable to offload traffic that matches -est CT state.
For most of our ingress traffic, we send it through CT zone 64000 and
then if we get +est or +rel we know it belongs to OVN, but all other
traffic goes to LOCAL host (-est). This LOCAL bound traffic wont be
offloaded, including Geneve traffic.
This commit helps increase offloaded traffic for pod to pod, by making
all incoming Geneve traffic bypass conntrack and go directly to LOCAL.
=> Bypass conntrack for Geneve pod to pod traffic

test/e2e/unidling.go
The way we check if hitting an idling service generates an idling event is
by checking the last event time, hitting the service and checking if an
event is created with a bigger time. If this happens within the second,
the two events will have the same time and the test will flake.
=> Wait one second between checking the last event and generating a new one

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovn-setup.yaml.j2, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go
This commit adds support for enabling network policy on host
network traffic pods such as the router pod in OpenShift.
Currently, if you have a default deny network policy on a namespace,
services within that namespace are not reachable via host network
using external routes. This feature will make that possible by allowing
users to create a separate network policy with a host network namespace selector.
The expectation is that the namespace you want to use to classify host network
traffic to is pre-created with the desired labels. These labels will then
be used as match fields for the network policy object's ingress selector.
It is also necessary that the users pass the host network namespace
as a command line parameter for ovnkube when it starts.
**How to test this feature:**
- Start …
=> netpol: Changes to support network policy for host network traffic

go-controller/pkg/config/config.go
The default value of host network namespace should be an empty string.
This way the feature is disabled unless someone specifically creates
and configures the host network namespace.
=> Set the default value of host network namespace to empty string

go-controller/pkg/factory/factory.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/ovn_test.go
When reviewing the PR https://github.com/ovn-org/ovn-kubernetes/pull/2097 I noticed we still have some left over egress IP clientset referenced on the node side. There is no reason for this as nodes don't perform any setup w.r.t egress IP, it is thus safe to simply remove.
=> Remove node-side egress IP clients

go-controller/pkg/testing/mock_lr.go, go-controller/pkg/testing/mock_lrsr.go, go-controller/pkg/testing/mock_ovn.go
This PR
- moves Logical Router Static Route (lrsr) mock functions into a separate mock_lr.go file
- implements Logical Router Static Route (lrsr) functions for the mocks
Co-author:  Palani Kodeswaran palani.kodeswaran@in.ibm.com
Signed-off-by: Sayandeep <sayandes@in.ibm.com>
=> Implement LRSR functionalities for Mocks Testing

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/namespace.go
In production, it was observed that NetworkPolicies that select all / many Namespaces often cause errors in ovn-controller:
`error parsing match "reg0[7] == 1 && (ip4.dst == { (..snip..): Syntax error at '$a5585560803499416081' expecting address set name.`
This is because we first delete the address set, then delete any network policies that refer to it.
This defers deletion of the address set until 20 seconds have passed.
Fixes a bug where deleting a Namespace referenced as a NetworkPolicy Peer would cause ovn-controller errors, and potentially drop traffic.
=> master: Delay deleting Namespace's address set for 20 seconds

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/testing/mock_lsp.go
To prevent port binding ping-pongs between ovn-controllers, if an
ovnkube-node isn't running or hasn't been able to clear the iface-id
for an old instance of a pod, but the pod has been rescheduled,
request the chassis the pod has been scheduled on.
@trozet @fedepaol
=> pods: bind pod logical switch ports to the node's chassis with requested-chassis

contrib/kind.sh, test/e2e/e2e.go
it has been observed that in the github and local env. pods that are
deployed in a cluster using shared gateway mode cannot resolve dnsNames.
This patch fixes that and exlicitly tests e2e dnsName resolution in pods
=> Should allow shared and local gateway dns resolution

go-controller/pkg/ovn/master.go
We're missing %v
@trozet @abhat 
Signed-off-by: Raul Sevilla <rsevilla@redhat.com>
=> Fix typo in error log message

test/e2e/e2e.go, test/scripts/e2e-cp.sh
this PR continues #1918 .
this PR is adding an e2e test that will check that the database is saved on the node file system (and not on a particular pod file system). The test will delete all the db pods (1 pod when on `non-ha` mode or 3 pods when on `ha` mode) without deleting any database files. After all the db pods will be be ready again we will test that new pod can be created and pass simple connectivity test to the API server.
as said earlier this PR continues #1918 .
the test validate connectivity before and after deleting all the db pods .
(we are  deleting the pods in order to emulate the pod restart.)
in order to try it yourself you can run from the `test` directory:
```
make …
```
=> e2e test to validate persistence of the OVN databases

.github/workflows/generate-report.yml, .github/workflows/test.yml, go-controller/Makefile, go-controller/hack/test-go.sh, go-controller/pkg/informer/informer_test.go
CI: go 1.16, small fixes
- bump to go 1.16
- coverage fixes for go1.16
- run race detector and coverage at the same time - stop testing twice
- run lint in parallel
- don't run tests in a container on CI - save build times
- add junit summarization
- fix handling of PKGS var
- stop forcing a single CPU
Tests are much faster now.
=> Go 1.16 + CI fixes

go-controller/pkg/ovn/gateway_init.go
For each node, we add pbrs for each node subnet. When syncing pbrs, we purge
not expected rules. In case of dual stack, we are mistakenly purging the
rules that were added because of the subnet belonging to the other ip
family.
Here, we compare the family of the nexthop with the family of the new
nexthop and apply the logic only if they match.
=> Purge only the lprs with nexthops of the same family of new nexthop

go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
Service targetPort is a selector for the endpoints/endpointslices
controller to create the endpoints based on that container port name.
It is not meant to be used in the Service implementation.
The relation is ServicePort.Name - EndpointPort.Name, however,
ServicePort.Name is only required for multiple ports and it may be empty.
If the endpoint matches the service and there is no name,
that means that is a single port service and there is only one endpoint.
=> service controller should not use the target-port

go-controller/hack/build-go.sh
On F34 the binary is being built with dynamic linkage. This fixes it to
use static and prints out the value during make so we can ensure from
logs that it is built correctly.
=> Fixes statically linking CNI binary

go-controller/pkg/ovn/pods.go
No functional issue, just an annoying warning message.
=> [wip] pods: make LSPGetOptions error more descriptive

go-controller/hybrid-overlay/pkg/controller/node.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
There was some unsafe access to checking if the node was ready in the
tests.
=> Fixes data race in hybrid overlay tests

go-controller/pkg/cni/bandwidth.go, go-controller/pkg/cni/bandwidth_test.go, go-controller/pkg/cni/cni.go, go-controller/pkg/cni/utils.go
When the cni is not chained with multus, the container runtime invokes
the check command. The check command checks the bandwith requirements
annotated on the pod, vs what's being configured in ovs. Ovs sets
ingress_policing_rate=0 by default, so the check always fails.
Here, when ingress_policing_rate is 0, we treat it as not found.
=> CNI cmdCheck: treat ingress_policing_rate=0 as not found

go-controller/pkg/ovn/pods.go
This was leftover from removing hybrid overlay external gateway.
Basically we dont need to add pod and service network routes when using
the routing external gateway. That traffic will always go to OVN anyway.
Also, we still need a route for hybrid overlay subnets in order to get
traffic to those subnets for HO purposes, regardless of if routing
external gateways are used for default egress traffic.
=> Remove improper checks for pod routes

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/util/kube.go
In the last community meeting it was dicussed to transition egressfirewall to be enabled with a cli flag. this is the PR that does that, and it also removes the code that watches the CRDs because it is no longer required 
=> change egressFirewall to be enabled with a cli flag

go-controller/pkg/ovn/controller/services/utils.go
In LGW mode the special SGW Hairpin Masquerade IP
is being used in the loadbalancer where it should not
be.  This PR ensures we only use the Masquerade IP
In shared GW when adding backends to loadbalancers
that have the same IP as the VIP.
More information can be found in [BZ 1957039](https://bugzilla.redhat.com/show_bug.cgi?id=1957039)
For Example, Before the Fix the GW LB resembled the following 
```
_uuid               : c3617307-f109-4d2e-9c2d-704166ffd970
external_ids        : {TCP_lb_gateway_router=GR_ovn-worker}
health_check        : []
ip_port_mappings    : {}
name                : ""
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"172.18.0.2:30081"="169.254.169.2:8081"}
```
Where it incorrectly DNATS Pod -> Svc traffic to …
=> Fix pod -> svc -> host LGW flow

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
Using ovn-nbctl to delete stale ports causes a discrepancy between the
go client cache and the content of the database. What happens is that
when the pod gets re-added, the go client thinks the port is there while
its not.
=> Stale ports: use ovnNBClient to delete them.

go-controller/pkg/factory/handler.go, go-controller/pkg/metrics/master.go
Previously we only tracked duration for some update handlers (but not
all). This extends the metrics to track all informer events (add,
update, delete).
The metric `ovnkube_master_resource_update_latency_seconds` now tracks Add, Update, and Delete events. It now includes Pod latency as well.
=> pkg/factory: more complete handle metrics

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy_test.go
This is a slight modification for the ACL Audit Logging feature
Currently for every gress rule it is impossible to tell what
NS the rule is in just by the name of the ACL this patch
fixes that by naming the ACL
`<Namespace>_<NetworkPolicy_Name>_<rule#>`
Adding the rule number fixes the case where we have multiple
gress rules defined in a single network policy.
=> Add Namespace and rule Number to gress policy ACL name

dist/images/Dockerfile.fedora
Our f33 OVN packages got GCed as they were never in an official update, so bump to a newer version of OVN.
=> Dockerfile.fedora: bump to ovn-21.03.0-32.fc33

go-controller/pkg/ovn/address_set/address_set.go
newOvnAddressSets returns a concrete type, that gets assigned to an
interface. This makes the interface not being nil (even if the backing
value is).  In particular, having
nsInfo.addressSet, err = oc.createNamespaceAddrSetAllPods(ns)
called twice would result in having the interface not being nil but the
value behind it being nil and it will make sequent use of
nsInfo.addressSet refer to a nil value.
More references in 
https://glucn.medium.com/golang-an-interface-holding-a-nil-value-is-not-nil-bb151f472cc7
=> NewAddressSet: return nil in case of error

dist/images/run-smart-nic-ovn.sh, dist/images/run-smart-nic-ovnkube-node.sh, dist/templates/ovnkube-node.yaml.j2
The `ovnkube.sh` script looks for the `OVN_LOGLEVEL_CONTROLLER environment variable for ovn-controller log level.
=> Fix ovn-controller log level var name

go-controller/pkg/ovn/acl/acl.go, go-controller/pkg/ovn/acl/acl_test.go
We no longer get any ACL by it's name in the OVN-K
Code.  This commit removes some Erronous code where
we used to do just that.
Signed-off-by: astoycos <astoycos@redhat.com>
=> Remove GetAclByName()

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/node.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go, test/e2e/external_gateways.go, test/scripts/e2e-kind.sh
With OVN-kubernetes we set the MTU of the pods to be 100 less than
physical network MTU. This becomes a problem when something outside of
the cluster tries to access a pod (local or shared gw mode) or via
service (shared gateway mode) with a packet larger than the pod MTU.
The packet will be dropped by OVS because OVS will not re-fragment
at the lower pod MTU when trying to send the packet to the pod.
This solves the problem by checking packet size for packets destined
towards OVN. If they are > pod MTU + 12 bytes (eth overhead) they are
forwarded to the kernel. The kernel has a route for pods via mp0
interface, which is a -100 byte MTU interface. This means the kernel
will automatically send ICMP needs frag back to the client.
For services, we add back the PREROUTING iptables rule to …
=> Fixes handling large packets towards OVN

go-controller/pkg/ovn/controller/services/services_controller.go
prevents prints like:
`42 services_controller.go:154] Error repairing services: %!v(MISSING)`
=> Fix error message

go-controller/pkg/node/node_smartnic.go, go-controller/pkg/node/node_smartnic_test.go
ConfigureOVS() method may fail after adding VF representor
Port to br-int, e.g if timeout is reached while waiting for
OVS flows.
If this happens, remove VF representor from br-int to allow retry.
=> Smart-NIC Remove VF Representor port on OVS failure

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
We were deleting pods from the default-deny lsp caches, even if they
still have other policies that may apply to them.
This could leave pods in the default-deny portgroup even if they no
longer have any policies selecting them (due to label changes).
Fixes a bug where pods could still have a default-deny ACL applied to them if their labels were changed. This is very unlikely to be triggered.
=> policy: remove incorrect deletion from lsp cache

go-controller/pkg/ovn/egressfirewall_dns_test.go
it appears that sometimes the test "EgressFirewall DNS Run Runs update
after the ttl returned from the DNS server expires" flakes.
I can't reproduce locally so I think it has to do with the timeouts
being too small
=> Increase timeouts for ttl egressFirewall DNS tests

go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go
The function was assuming dualstack, which was causing "Failed to find
node ips for gateway" error to appear over 14k times in our scale
test runs downstream.
=> Fixes getNodeIPs assuming dualstack

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go
The runtime might call ovnkube to set up the pod sandbox before
the pod informer has received the pod from the apiserver. Currently
the code simply returns an error and expects kubelet to retry.
Instead let's be nicer and wait a short bit of time for the pod
to show up before erroring out.
@trozet 
```
I0608 04:55:31.294649    3386 informer.go:294] Successfully synced 'e2e-test-job-controller-b886m/simplev1-4pwg8'
I0608 04:55:31.763896    3386 cni.go:213] [e2e-configmap-4525/pod-configmaps-59b65ed6-a123-4f8c-ba52-7b6ecc0cda9d 5692e102594ab44ca4a0d2adc866a421e50a9086fbe9e92ca6bf82af07f714ca] ADD starting CNI request [e2e-configmap-4525/pod-configmaps-59b65ed6-a123-4f8c-ba52-7b6ecc0cda9d 5692e102594ab44ca4a0d2adc866a421e50a9086fbe9e92ca6bf82af07f714ca]
I0608 04:55:31.763966    3386 …
```
=> cni: wait up to 1 second for pods to appear in the API

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/port_group_unit_test.go, go-controller/pkg/testing/mock_portgroup.go, go-controller/vendor/github.com/ebay/go-ovn/port_group.go, go-controller/vendor/modules.txt
Bumps go-ovn to pick up https://github.com/eBay/go-ovn/pull/149
This adds a factory sync function for network policy that bulk-sets all pods on policy create. This means that creating a network policy that selects a large number of pods is much more efficient.
Additionally, this means that ovn-kube startup time for large policies should be much faster.
=> NetworkPolicy: bulk-add pods to new policies (or on restart)

go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
It turns out what the system reports for maximum arguments may not be
the real amount of arguments that are usable in a shell. Different
kernels calculate it differently, but the gist is that the only reliable
way to know is to test for it. This patch does an initial search based
on the given max args in the kernel to find the actual usable amount.
The search is only done one time during initialization, so it shouldn't
impact performance.
=> Batching: Fixes finding maximum bash arguments

go-controller/pkg/util/ovs.go
This will reduce the memory footprint and possibly
run a bit faster as current implementation may
reach a depth of 52 calls where in each call it
allocates an array of size `estimatedMax` bytes
=> Avoid recursion when calculating max supported args

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, test/e2e/e2e.go
Egress firewall matching pods can't connect to cluster services because the ACLs on the node switch specify `from-lport`, change that to `to-lport`. This was introduced by PR: https://github.com/ovn-org/ovn-kubernetes/pull/1971
=> Fix connectivity for egress firewall matching pods to cluster services

go-controller/pkg/node/gateway_shared_intf.go
Today, node port traffic is steered directly to OVN
via patch port from phys bridge to br-int
return traffic then goes through conntrack zone 64000
before being sent to the physical port.
This leads for this type of traffic to never establish
on CT zone 64000 which prevents HW offload capable NICs
from offloading this traffic pattern.
For these type of flows we can optimize by not sending
to CT on zone 64000 when egressing patch port by matching
on the src port (nodeport).
Bump the priority of node port Openflow rules to 110
to avoid commiting to CT zone 64000 for traffic egressing
patch port.
=> Shared Gateway Node Port Skip commit to CT-Zone 64000

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/util/ovs.go
In older kernels like RHEL 7, OVS does not support chk pkt length in
kernel datapath. This will cause all packets hitting these flows to go
to userspace, which is the majority of OVN destined ingress traffic into
the node. This will result in severe performance degradation. To avoid
this, detect and disable using these flows if the kernel datapath does
not support the action.
Note this will result in these nodes not being able to handle packets
larger than pod MTU and send ICMP frag needed, but the trade off vs.
performance impact is worth it.
=> Detect if OVS supports check pkt length

go-controller/pkg/util/ovs.go
There are still bash errors for "too many args" which stem not from the
number of arguments but a combination of number of args and total length
of the args. This sets the maximum line length to 100k, which is less
than the default maximum of 130k (to be safe).
Verified in downstream scale this resolves the issue of hitting too many args os/fork errors.
=> Declare a maximum line length for batching

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go
Adds configuration options to disable or set logical flow cache limits. Logical flow cache is enabled by default and no limits are assumed.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1961757
=> Bug 1961757: Add ovn-controller logical flow cache options

test/scripts/e2e-kind.sh
GCE skipped tests have been fixed with this PR, so remove GCE from the skipped tests list.
https://github.com/kubernetes/kubernetes/pull/93119
Signed-off-by: vpickard <vpickard@redhat.com>
=> Remove GCE from skipped tests

docs/kind.md
The example under `Launch the KIND Deployment` did not export the
KUBECONFIG. Run `export KUBECONFIG=${HOME}/admin.conf` instead.
=> docs: Export KUBECONFIG in Run KIND deployment section

go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/gress_policy.go
There is a race between handlers that unit tests found. Remove the offending racy write, and update AddresSets so that operations on a Destroy'd set are a no-op.
```
WARNING: DATA RACE
Write at 0x00c0003c1f28 by goroutine 919:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*gressPolicy).destroy()
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/gress_policy.go:480 +0x115
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).destroyNetworkPolicy()
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/policy.go:1128 +0x59c
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).deleteNetworkPolicy()
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/o …
```
=> policy: fix gressPolicy data race on delete

.github/workflows/test.yml, test/Makefile, test/scripts/upgrade-ovn.sh
Addresses issue #2132
1.  Deploys KIND using current origin/master HEAD
2.  Builds a new docker image for current PR.
3.  Rolls out new image for ovnkube-node daemonset.
4.  Rolls out new image for ovnkube-master daemonset (workers need to upgrade before masters)
5.  Run e2e tests suite
I'd be happy to address any required changes, and reserve any "Nice to Haves" for a follow-up PR, as this is my first time working on GH actions, would like to keep it simple.
As per discussion in the community meeting on 21st Apr, added Upgrade procedure as part of e2e tests, so for every new PR, and every test, we are upgrading from a KIND-OVN cluster built on master branch to the cluster built using the code in the PR. And …
=> Adding upgrade testing as part of e2e tests

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/util/ovs.go
code is incorrectly caching empty openflow patch and phy ports instead of flagging errors
and that will lead to unaccurate health check errors when ports are created.
=> Bug 1965074: return an error for empty openflow patch and/or phy ports.

.github/workflows/test.yml, go-controller/pkg/node/healthcheck.go
it got removed through the go 1.16 changes
Fixes: 676691772ec4 (CI: go 1.16, small fixes)
@squeed FYI
=> add 'make gofmt' back in the CI

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/management-port_linux_test.go
Some namespace created remain after tests.
This PR remove these namespaces.
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>
None
Run ```ip netns``` command after the test.
None
=> Remove namespaces after the tests

go-controller/Makefile
Fix some warnings at ```make clean``` when removes a non-existent file.
```
$ make clean
rm -rf _output
rm -rf /home/honma/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/_artifacts
rm ./pkg/nbdb/ovn-nb.ovsschema
rm: cannot remove './pkg/nbdb/ovn-nb.ovsschema': No such file or directory
make: *** [Makefile:61: clean] Error 1
```
```
$ make clean
rm -rf _output
rm -rf /home/honma/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/_artifacts
rm -f ./pkg/nbdb/ovn-nb.ovsschema
rm ./pkg/sbdb/ovn-sb.ovsschema
rm: cannot remove './pkg/sbdb/ovn-sb.ovsschema': No such file or directory
make: *** [Makefile:62: clean] Error 1
```
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>
None …
=> Fix some warnings at make clean

.github/workflows/test.yml, contrib/kind.sh, contrib/kind.yaml.j2, test/scripts/install-kind.sh
Upgrade to kind 0.11.1 and make use of builtin support to disable kube-proxy and simplify `kind.sh` script. kind 0.11.1 includes dual stack support so we dont need to use @aojea kind fork any longer for dual stack tests.
=> Upgrade to kind 0.11.1

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Fixes several paths where deleting or updating a pod serving as an external gateway may result in stale ECMP routes.
=> Fixes stale routes after external gateway pods delete/update

go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/services_controller.go
The Service controller was adding metrics per sevice, this creates
scalability problems due to the cardinality explosiong.
OVN doesn't need that granularity for the services metrics, so it just
simply removes the service name/namespace label to have only
one global metrics.
xref:
https://blog.freshtracks.io/bomb-squad-automatic-detection-and-suppression-of-prometheus-cardinality-explosions-62ca8e02fa32
=> avoid prometheus cardinality explosion

go-controller/pkg/ovn/egressgw.go
When adding routes to pod, we fail inside the inner loop returning an error. What happens is that if the pod has two ip addresses, and the gw is set only for the second address, the function will mistakenly return an error.
=> Add routes for pod: fail only after checking all the gw addresses / ips

.github/workflows/test.yml, test/scripts/e2e-cp.sh
This PR enables the e2e tests for IPv6 for the control-plane.
Currently not-IPv6-ready tests are excluded/skipped. 
A list of the skipped tests can be found at the end of this PR with failure messages and links to the failed CI jobs. This can be taken as a starting point to make the failed tests IPv6 ready and include them step by step in the test suite. 
The ovn-ci workflows include two new "steps" for control-plane IPv6 e2e tests (gateway-mode: local & shared). 
none
---
The following contains a list of the excluded and failing tests and a short info about the failure:
**Test: Should be allowed by externalip services**
```
• Failure [14.829 seconds] …
```
=> Enable IPv6 e2e tests for control-plane

dist/images/daemonset.sh
"ovn_sflow_targets" is mixed up with "ovn_sflow_targets" in daemonset.sh
Fixes #2316
Signed-off-by: Joel Takvorian <jtakvori@redhat.com>
Note: this bug fix looks trivial but, being new to ovn-k, I haven't been able to test it or even acknowledge the initial problem at the moment. I would appreciate some help to ack the issue / test the fix.
=> Fix bug #2316 mixed up flow targets

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
`ovnkube-trace` should check for a Pod interface index in the `/sys/class/net/eth0/ifindex` file when the `ip` command isn't installed inside of the Pod.
- Deploy a Pod without `ip` command available and attempt to run `ovnkube-trace`. If should process through Pod IP info collection. 
ovnkube-trace now checks for Pod interface index in sysfs in addition to ip command.
=> Check /sys/class/net for ifindex when ip command is not available inside Pod

go-controller/pkg/util/nicstobridge.go
Improve logging message when address move fails
=> nicstobridge.go: Improve logging message when address move fails

go-controller/pkg/kube/kube_suite_test.go, go-controller/pkg/kube/kube_test.go
In #2278 it was not clear if the `Kube.SetAnnotationsOnPod` method adds annotations correctly. This unit test ensures the annotations are set correctly via this method.
Tests are included in the test suite (e.g. [here](https://github.com/creydr/ovn-kubernetes/runs/2914029053?check_suite_focus=true#step:4:3708))
```
none
```
=> Add unit test for Kube.SetAnnotationsOnPod

go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/utils.go
If ovnkube-master is a bit slow and the service is already gone from
the apiserver and informer cache, we still want to clean it up. But
we don't want to pass a nil service to Eventf() which will cause
the following panic:
```
I0708 15:46:33.636318       1 services_controller.go:518] Deleting service cluster-density-503fcc1a-1066-44d9-bef7-43292b046b06-151/deployment-2pod-151-1
E0708 15:46:35.468114       1 utils.go:93] Error deleting VIP [172.30.55.216:80] on OVN LoadBalancer [01801284-6384-498c-8ef8-a08a6e63c77f 072075fd-eb15-47cc-bb17-05c8b4b49634 0a11b3f8-b1ba-4649-815b-8117442236d
5 10c04472-7cc0-4247-aa7b-2f166e8d4ab1 13a0737b-9859-4654-9a45-df034a2d1098 1532a693-b1e7-438e-b125-9e79953baf73 1b860b67-d31d-4633-98ba-5b62d2db1f2e 240b1487-b592-4c5d-a30c-1910c17512a0 …
```
=> services: log errors and don't panic if the service doesn't exist any more

go-controller/pkg/ovn/namespace.go
Due to lock contention, and because our namespace handler is
single-threaded, namespace additions may pile up and take a
while. Log how long they take, and also when namespaces are
added and deleted so we can better debug these issues.
=> namespace: track how long namespace addition takes

go-controller/hybrid-overlay/pkg/controller/master.go
Since we do not have a config parser that checks if
HybridOverlay.ClusterSubnets is set if HybridOverlay.Enabled is true,
before adding the lr-in-policy we should check if there are any
clustersubnets in the config. Since we don't have a default value
for this field it ends up creating policies that have nil dst
fields.
Fixes #2313 
=> Add hbo-lr-policy only if config.HybridOverlay.ClusterSubnets is set

go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/repair_test.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go, go-controller/pkg/testing/exec.go
In some scale scenarios it takes 20s to repair services on startup:
```
2021-07-08T15:46:57.601Z|01774|ovn_dbctl|INFO|Running command run --if-exists -- remove load_balancer 13a0737b-9859-4654-9a45-df034a2d1098 vips "\"172.30.9.247:80\""
I0708 15:46:57.658232       1 repair.go:132] Deleting non-existing Kubernetes vip 172.30.135.31:80 from OVN TCP load balancer 13a0737b-9859-4654-9a45-df034a2d1098
...
I0708 15:47:08.113637       1 repair.go:132] Deleting non-existing Kubernetes vip 10.0.141.143:30666 from OVN TCP load balancer aaa40b67-8c2b-4c29-bdf7-8d0802b89c49
2021-07-08T15:47:08.117Z|02031|ovn_dbctl|INFO|Running command run --if-exists -- remove load_balancer aaa40b67-8c2b-4c29-bdf7-8d0802b89c49 vips "\"10.0.141.143:30666\""
I0708 15:47:08.477075       1 repair.go:47] Finished …
```
=> services: batch LoadBalancer VIP deletions when possible

go-controller/pkg/ovn/master.go
When the master is restarted, all the nodes are fed using
both a fetch of existing nodes and by the add node event.
In case the node already had subnet annotations, we were
updating the subnets allocated metric again. This commit
checks if new subnets were allocated and only then calls
the code to update metrics associated with allocated
subnets.
=> Fix duplicate incrementing of subnet allocation metric

go-controller/pkg/node/gateway_shared_intf.go
Instead of explicitly going to LOCAL port change
OF rule in shared gateway to do NORMAL action.
This is needed to support cases where tunnel IP
is not on the bridge's management port (LOCAL).
In addition this will allow support for usecase
where tunnel traffic is tagged.
=> OVN Tunnel traffic Normal action

go-controller/pkg/factory/factory.go
We have up to 10 goroutines handling pod events, however handling pod
events depends on namespace existing, and the namespace handler is
single threaded. During a scale test where we create many namespaces
with a few pods in them, the pod handler can get bogged down waiting on
namespace handler to serially get each new namespace. It shouldn't
introduce significant performance cost to handle these also in parallel.
=> Multi-threaded namespace informer

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/types/types.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/config/cni.go, go-controller/pkg/node/node_smartnic.go, go-controller/pkg/node/node_smartnic_test.go
If the the pod's UID changes that means the pod was deleted
and re-created. There's no point in continuing this sandbox
request as kubelet will just be tearing it down soon anyway.
If the pod's MAC changes, that means the master was behind and
set the IPAM annotation on a new instance of the pod (since
the master just uses Patch with namespace+name and ignores
UID), and this sandbox will be torn down soon as well so
kubelet can start the newer one.
=> cni: cancel old pod sandbox add requests if the pod's UID or MAC changes

go-controller/pkg/ovn/controller/services/services_controller.go
Right now we add the vipProtocol to the list of vipProtocols to remove
only if the loadbalancer is not the idling one. The problem is, we
update the loadbalancer just before this check, with the effect of not
removing the vip from the existing balancers. This causes the vip to
stay both on the idling and non idling loadbalancers, with non
predictable effects.
=> Idling: check existing loadbalancer before moving the vip to the idling

.github/workflows/test.yml, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, test/scripts/e2e-cp.sh
When a gw pod gets the external gateway annotation, it adds the specific
routes to the external gateway for existing pods, but it does not remove
the SNAT that was added when the pod was created.
=> Delete per pod nat when adding gw routes to namespace

go-controller/pkg/node/gateway_init.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
When node addresses are allocated through DHCPv6 IA_NA, they might get
a /128 prefix address. These node addresses are set on the gateway
router port as well. OVN routers infers on-link routes from subnet
information on the address itself. Since /128 addresses are not on a
subnet, cluster traffic is routed through the node gatway instead of
directly.
Note that OVN does not support learning routes from ICMPv6 route
advertisement and does not support adding on-link static routes.
This patch infers a subnet for the interface looking at the node
routing information and replaces the /128 prefix with the subnet
prefix.
Added unit tests
Infer subnet for /128 IPv6 addresses allocated through …
=> Infer subnet for node /128 IPv6 addresses

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
Make namespace handlers multi-threaded. Stop waiting for namespace where possible:
The pod handlers and egressgw code would wait for the namespace add
event before being able to actually create things. This wait could last
up to 10 seconds before failure, and possibly even longer depending on
how backed up the namespace handler is.
This patch removes waiting where it is unnecessary. Those cases are the
following:
- Pod add only cares about the address sets for the namespace being
available. We already create the address set if we detect it is nil
during pod add so there is nothing we are really waiting for the ns
event.
- Egress GW waits for namespace to see what routes the annotation may
have on the namespace for gateways. There is really no reason to wait
as we can add the routes we …
=> Fix namespace locking and waiting

contrib/kind.sh, dist/images/Makefile, docs/kind.md
- Support in Makefile (e.g. OCI_BIN=podman make fedora)
- Support in kind.sh with flag "-ep podman"
Signed-off-by: Joel Takvorian <jtakvori@redhat.com>
This PR adds podman support for kind. Currently, only docker is supported, and building / deploying with podman fails.
None
- Non-regression with docker must be verified (I only have podman on my machine, didn't test with docker). Basically, need to check that the instructions here are still working: https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/kind.md
- I wrote a gist to give instructions with podman, as they slightly differ: https://gist.github.com/jotak/068cee03ef1ba9fea467d96daf811cbd . Not sure if they have to be …
=> Kind script: add support for podman

go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, test/e2e/e2e.go
Closes #2232 #2235
The Current per node ExternalIP implementation in Local gateway is designed to work this way:
There are three paths OVN-K takes w.r.t external IP type services
1. The external IP is associated with an interface on one of the cluster nodes. In this case we set up iptables rules on that node only to DNAT to the cluster IP
2. The external IP is on the subnet of one of the NICs on node X, in this case we do nothing (since it's already "routable")
3. Else (which means it's not reachable from the node and not associated with any interface), we setup routing rules to forward traffic to the management port (so that traffic intended for the external IP which hits the node, is forwarded into OVN and the OVN external IP LB which will then forward traffic to the endpoint)
There are …
=> Fix lgw external ip

go-controller/pkg/ovn/egressgw.go
This happens when the pod was already created but a new event of the pod
is generated. I managed to see it after a ovnkube-master manual restart.
=> addGWRoutesForPod: don't fail if the routes are already added

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
ovnkube-trace will now look for ovnkube pods in all namespaces and it
will pick the namespace of the first matching pod that it finds.
A manual override with -ovn-config-namespace still takes precedence.
Fixes #2305
=> ovnkube-trace: Autodetermine ovnNamespace

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cniserver_test.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/types/types.go, go-controller/pkg/config/cni.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
Passing the Kube API authentication data via the CNI config file
has two problems:
1) the CA file path might be different to the cniserver (because
it's containerized) than it is to the cnishim running outside
a container
2) it's better not to leak authentication info into the host
filesystem, even though the CNI config file should have restricted
permissions
To solve these two issues, pass the Kube API authentication data
back from the cniserver (running in ovnkube-node) to the cnishim
in the JSON response instead of writing it to a file on-disk.
This commit reverts parts of:
d39716645fe8bc7f021e7ea0b5f61bbcf421fe8a
cni: cancel pod sandbox add requests if the pod's UID or MAC changes
@trozet @astoycos @squeed
=> cni: pass Kube API auth via cnishim response, not CNI config file

docs/kind.md
Hey @trozet @squeed this is a minor change in kind documentation: `$GOPATH` isn't actually necessary here, just `$PATH` is enough.
=> Kind doc: simplify instructions with podman (minor)

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2
When running kind with -eb, we create a second network and add all the
node-containers to it to create a second interface into "nodes".
Then, we use the value of the same parameter to instruct ovnkube that we
intend to use a different nic for external gateway traffic.
This is based to the additional parameters introduced in https://github.com/ovn-org/ovn-kubernetes/pull/2270
=> Kind: add an option to create a second interface in all nodes

go-controller/pkg/kube/kube.go, go-controller/pkg/kube/kube_test.go, go-controller/pkg/kube/mocks/Interface.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go, test/e2e/e2e.go, test/scripts/e2e-cp.sh
This PR taints nodes, if the nodes default interface MTU is not big enough to contain the Geneve header and the configured MTU (`config.Default.MTU`).
The taint has the key `k8s.ovn.org/mtu-too-small` and `NoSchedule` effect.
I cherry-picked @tssurya s commit 28babd42 from #2183, so you might see some changes twice.
For most parts I included unit tests. In addition an e2e test was included to test the whole procedure. 
To verify it locally, the MTU of one nodes default interface can be adjusted and the ovnkube-node pod restarted to trigger the validation (as done in the following with node ovn-worker2).
1. Get all pods in ovn-kubernetes namespace
```
$ k get po -o wide
NAME …
```
=> Taint nodes with a too small MTU

go-controller/pkg/ovn/ovn.go
We see at scale when a lot of pods are in pending state and not
scheduled to a node that we print useless logging that overflows the
ovnkube-master log:
I0720 21:10:45.781776       1 ovn.go:411] [54fbd32c-ea9d-4c8d-8ece-79f38d05024c/cluster-density-40bc6f73-be12-47be-a9ab-35dfe59adbe8-469/cluster-density-2-1-build] retry pod setup
I0720 21:10:45.781796       1 ovn.go:417] [54fbd32c-ea9d-4c8d-8ece-79f38d05024c/cluster-density-40bc6f73-be12-47be-a9ab-35dfe59adbe8-469/cluster-density-2-1-build] setup retry failed; will try again later
I0720 21:10:45.781802       1 ovn.go:411] [fa4d74f7-6504-4c0b-97c6-75ccddcb2bb9/cluster-density-40bc6f73-be12-47be-a9ab-35dfe59adbe8-119/deployment-2pod-1-7c7b46d4f4-kk4dv] retry pod setup
I0720 21:10:45.781806       1 ovn.go:417] …
=> Dont print pod retries if not scheduled

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/types/const.go
Moves Geneve header length constants into `types` package
Only a small cleanup
No functional change so unit tests should pass
none
=> Move Geneve header length constants into types package

go-controller/pkg/ovn/ovn.go
The code from AddNode to ensure pods already on that node were added
back was flawed. The two goroutines could be trying to add the pods at
the same time, which could lead to errors. This fixes it by utilizing
the retryPod goroutine, which is thread safe with the pod handler.
Therfore now the AddNode will simply add the pods to the retry map, and
request retry to run immediately. This isolates the pod add logic back
to the pod handler itself.
Fixes: #2281
=> Fix node handler stepping on pod handler

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/types/const.go
- What this PR does and why is it needed
UseCase: During upgrades, when the ovnkube pod is deleted and
before/while it gets recreated if a new pod request comes, it
will fail.
When node networking is down, we should not allow pods to be created
on that node. This PR fixes this by adding a taint on the node with
the NoScedule effect when the ovnkube pod receives a SIGTERM and then
removes the taint when the ovnkube pod finishes setting up networking
and initializing the CNI config.
- How to verify it
The added taint will be visible on the node for the brief period of time between the deletion of ovnkube-node pod and creation of the new one that takes its place which roughly takes ~60sec.
```
I0718 09:41:21.603487  396533 kube.go:161] Added taint k8s.ovn.org/network-unavailable:NoSchedule …
```
=> Taint node with NoSchedule effect when ovnkube pod is down

go-controller/pkg/ovn/master.go
This commit adds the previously missing v6 management interface
address to the host network policy address set.
=> Add v6 management interface address for host network policy

contrib/kind.sh
On some systems we may reach this point before
k8s gets the chance to actually create the pods
This causes the check for pod readiness in ovn-kubernetes
namespace to fail with "error: no matching resources found"
as no pods will be present.
Add an initial sleep to allow k8s controllers to create
the relevant (sub)resources
=>  kind.sh: Check for pod object creation

go-controller/pkg/ovn/ovn.go
Fixes another case where update pod and adding pods to retry could race. Also a trivial fix to skipping the pod when it is not scheduled.
=> Additional pod handler race

go-controller/pkg/ovn/ovn.go
we have seen instances where the pod delete event gets queued up and the
pod's DeleteFunc() callback is delayed. in the meantime, we are trying
to do pod setup of the failed pod again and again. since the pod is gone
we fail in setting pod annotations in addLogicalPort(). we add the pod
back to the retryLoop and retry again after 1 minute.
we continue this until the pod's DeleteFunc() gets called and it removes
the deleted pod from the retryPod map.
Fixes: #2341
=> quit retrying pod setup if the pod is already gone from informers cache

contrib/kind.sh, docs/kind.md
Since the future is SGW, let's make this the default when creating KIND clusters.
=> Kind: Make SGW as default

docs/design/external_traffic_policy.md, go-controller/pkg/factory/types.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/controller/services/utils_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/types/const.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, test/e2e/e2e.go, test/e2e/util.go, test/scripts/e2e-cp.sh
fixes #1951 
This PR implements the the k8's externalTrafficPolicy  Feature which is further described [here](https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies)
This feature is implemented only for SGW mode
It adds new Gateway Router load-balancers, explicitly formed to ignore the GWR option `options:lb_force_snat_ip=router_ip`  using a new OVN feature `options:lb_skip_snat=true` which is in the [following patch](http://patchwork.ozlabs.org/project/ovn/patch/327cc4c2e4f954a279dca02bad89682cb6eec7c9.1617288043.git.lorenzo.bianconi@redhat.com/)
Also it ensures that when externalTrafficPolicy=`Local` It adds only the node-local endpoints to the new Loadbalancers to ensure that traffic is only forwarded to local endpoints 
It is currently WIP since it requires a …
=> Implement externalTrafficPolicy Feature 

go-controller/pkg/testing/libovsdb/matchers.go
Now libovsdb matcher does not only compare string slices as string sets, it cmpares any slice as a set.
=> libovsdb: matcher compare slices as sets

test/scripts/upgrade-ovn.sh
The script works fine when run from the makefile
for tests, since the cluster name is set in install-kind
script. For running it standalone, let's add "ovn"
as the default cluster-name.
Helps solve:
```
./upgrade-ovn.sh 
+ export KUBECONFIG=/home/<name>/admin.conf
+ KUBECONFIG=/home/<name>/admin.conf
+ export OVN_IMAGE=ovn-daemonset-f:dev
+ OVN_IMAGE=ovn-daemonset-f:dev
+ install_ovn_image
+ kind load docker-image ovn-daemonset-f:dev --name ''
ERROR: no nodes found for cluster ""
```
=> Add the default cluster name to upgrade.sh

go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/controller/overlay_windows.go
Ensure that if a windows overlay network exists on node start that it is
valid for the node.
currently if a windows node is deleted and there is an attempt to recreate the node with the same name the node overlay network will fail to be created. This patch fixes that 
Reported at https://bugzilla.redhat.com/show_bug.cgi?id=1984201
=> hybrid-overlay: ensure that named networks are valid for Windows

go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
In `GetPortAddresses`, we check if we have both PortMAC and IP for
the port. If not we return nil for both values. While this works
for normal ports, for the HBO ports which don't have IPs for
the `int-<node>` interface, we will always hit this condition and
return an empty PortMAC which in turn triggers the lsp-add even
if the portMAC already exists.
When we have an external entity updating the node object, the
watcher triggers `handleOverlayPort` and we keep hitting this
condition.
Let's remove the `len(addresses)<2` check since its not needed
for HBO and in normal pod port case, `pods.getPortAddresses` already
handles the case for empty podMac or podIPs. This way when portMAC
is set but not the IPs, we will still return the portMAC and the …
=> HBO: Make GetPortAddresses return portMAC even if portIP is nil

contrib/kind-dual-stack-conversion.sh
It waits for all pods to be ready, but fails early if the deployment hasn't created any pods yet.
Instead, just wait for the deployment to roll out.
=> Tests: fix ipv6 conversion flake

go-controller/hack/test-go.sh
this typo makes test-go.sh ignore ginkgo focus setting.
=> fix typo in test-go.sh

.github/workflows/test.yml
@andreaskaris I think now that matrix.target no longer has 'shards', the e2e tests weren't running because there wasn't a target in the Makefile to hit :(
=> ci: fix running e2e tests

go-controller/pkg/config/config.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/ovndbmanager/ovndbmanager_test.go
We may want to update the ovn election timers, and in order to do that
we need to act asynchronously because the election must be completed and
the change must be performed on the leader node. So, we add two optional
parameters for the desired election timer and we change that as part of
the db checker timer.
=> DBChecker: reconcile the election timeouts when specified

go-controller/pkg/factory/handler.go, go-controller/pkg/metrics/master.go
`resource_update_latency_seconds` metric creates hundreds of time series. We tested this against 120 worker cluster of OpenShift and in the spirit of trying to reduce cardinality as seen in #2279 from @aojea (and after consulting with him), this is a follow up PR along the similar lines.
@girishmg @trozet  kindly review if this will be acceptable to change. Thank you.
xref:
https://blog.freshtracks.io/bomb-squad-automatic-detection-and-suppression-of-prometheus-cardinality-explosions-62ca8e02fa32
Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
=> attempting to reduce cardinality in the interest of memory performance

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
If a cluster experiences issues over a longer period of time and ovnkube-master does not run while changes have been occurring to pods / namespaces which are matching egress IPs: then we do not sync the stale data on a restart. This patch implements that sync. Moreover it also adds a couple of conditions which were missed for node synchronization.
/assign @trozet  
=> Sync egress IP for pod and namespace changes on restart 

go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/cnismartnic_test.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/cni/utils.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/handler.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go
Includes a handful of fixes from the outcome of downstream scale testing. Basically the tl;dr is:
1. Having many pod handlers doesnt fix our scale issues, because of lock contention with nsInfo, as well as single threaded ovsdb operations.
2. Having many pod handlers can result can cause average latency of a pod to bring up to be worse, because creation order of events coming from kapi can be spread over many handlers (all fighting for locks), and there is no guarantee a pod created at a given time is processed in a timely manner. Decreasing the number of queues helps this somewhat.
This PR includes fixes that:
1. Tune pod handlers to 15. Increasing the pod handlers to 50 or 150, does not give us any lower pod ready latency, even with full queues, because of contention between handlers. …
=> Scale fixes

go-controller/pkg/util/ovs.go
Today RunOVNNbctlUnix() incorrectly runs ovn-nbctl command to access OVN
NBDB through either the ovn-nbctl daemon or network connection, this
commit fixes that.
=> fix RunOVNNbctlUnix() to access OVN NBDB through unix domain socket

go-controller/pkg/factory/factory.go
Found a downstream panic; I can't believe this is the reason but I don't know what else it would be, and it's silly to have two of the same include.
@trozet 
```
E0819 06:47:31.180307       1 handler.go:190] Object has no meta: cannot get ObjectMeta from type *v1.Pod
E0819 06:47:31.180430       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 130 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19457e0, 0x292eef0)
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io …
```
=> factory: remove duplicate include

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go
nsInfo is one of the 2 main sources of contention during heavy pod add
operations. Moving this to an RW Mutex greatly improves performance
because there in most places we are able to only use an RLock for
nsInfo, which allows the multiple parallel pod handlers to be blocked
less often.
=> Scale Improvement: nsinfo RW Mutex

go-controller/pkg/factory/handler.go
EnsureObjectOnDelete checks the expected type of the object, if it
doesn't match it gets the the object from the tombstone and returns the
real object. After this, we were still using the old object to get meta
from during refQueueEntry.
Not 100% sure this fixes the issue, but it seems plausible since EnsureObjectOnDelete can not match the expected type.
=> Fix errors during delete for get object meta

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/monitor.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go, go-controller/vendor/modules.txt
This pulls in https://github.com/ovn-org/libovsdb/pull/218 which fixes a bug that @dcbw noticed with the reconnect logic.
TL;DR libovsdb would immediately try to reconnect and would not get "connection refused" (even though ovsdb-server had shut down). the reconnect logic would get stuck in a half-connected state (established and rpc connection, but can't perform rpcs) and subsequent calls to `connect` would not error out, because we had an rpc connection, even if it wasn't working.... This ensures that state is cleaned up during failure in `connect`. I've tested this and it now works as expected on container restart and forced stop + delay of 2 minutes to reconnect, so I'm confident this should fix any issues seen here in CI.
/cc @dcbw 
**- …
=> bump libovsdb

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go
While providing ipv6 addresses in `nexthop` and `dst-ip` fields into the
nbctl calls, it fails with the error `unexpected ":" parsing string`
during hbo pod deletion. This leads to stale bfd entries that don't
get cleaned up.
Without the PR:
```
I0820 10:59:13.626354      48 pods.go:94] Deleting pod: t1/client-on-ovn-worker
I0820 10:59:13.626393      48 address_set.go:481] (d79acab8-7d39-47cc-8682-ab7bf0d80bb4/t1_v6/a3345265888189311907) deleting IP "fd00:10:244:1::7" from address set
I0820 10:59:13.626492      48 ovs.go:207] exec(188): /usr/bin/ovn-nbctl --timeout=15 remove address_set d79acab8-7d39-47cc-8682-ab7bf0d80bb4 addresses "fd00:10:244:1::7"
I0820 …
```
=> Add quotes around nexthop and dst-ip fields

go-controller/pkg/testing/libovsdb/matchers.go
The previous gomega matching function `ContainsElement` doesn't
assert that objects which are deleted, are also not retrieved in the
final result. Ex: item1, item2 exists, item1 is deleted. With
`ContainsElement(item2)` we cannot fully assert that item1 is gone. With
`ConsistOf(item2)` we can.
/assign @jcaamano 
=> [libovsdb] Update test matcher for libovsdb

go-controller/pkg/ovn/address_set/address_set.go
Function was accidentally using the non-hashed names.
=> Fixes ensure address set

go-controller/pkg/testing/libovsdb/libovsdb.go, go-controller/pkg/testing/libovsdb/matchers.go
When verifying if https://github.com/ovn-org/libovsdb/pull/220 works, I realized our testing framework needs to be modified to be able to handle optional field values (referenced by pointers). Explicitly for optional field values representing UUIDs (see: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/nbdb/logical_router_static_route.go#L18) we need to compare the referenced pointer value and see if they match. 
I always get a bit nervous when using `reflect` and was a bit afraid that my changes in `matchers.go` will panic for non-string pointer values, but according to the doc for `String()`:
> func (reflect.Value).String() string
> (reflect.Value).String on pkg.go.dev
> String returns the string v's underlying value, as a string. String is a special case because …
=> [libovsdb] Modify matchers to take into account optional field values

dist/images/Dockerfile.fedora
This new version includes support for multiple DGPs per router, which is
needed for an upcoming commit.
=> Dockerfile.fedora: Update ovn build to ovn-21.06.0-15.fc33.

dist/images/Dockerfile.fedora, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn.go
This patch sets gateway-chassis to the node itself for each logical
router port that connects node level switch to the cluster router. This
makes use of the OVN optimization [0] that avoids flooding-filling
unrelated datapaths by ovn-controller on each node, which perfectly
fits the ovn-kubernetes deployments where each logical switch is bound
to a chassis, significantly improving scalability of ovn-controller (10
times faster for recompute and 70-80% memory savings for ovn-controller
\+ OVS combined. See more details in [0]).
[0] https://github.com/ovn-org/ovn/commit/22298fd3790825f45680508bde821bb9a2d525d2
=> Use DGP to connect logical switches to the cluster router.

go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/loadbalancer/lb_cache.go, go-controller/pkg/ovn/loadbalancer/lb_cache_test.go, go-controller/pkg/ovn/master.go
When a node gets deleted, the logical switch and
gateway router get removed first. However we do
not update the LBCache and this causes dependency
failures during deletion leaving behind wrong ip->vip
pairing in the lbs.
When the pods on this node go away, ensureLBs
gets triggered and it tries to update endpoints across
load balancers. This `set load_balancer` command is
batched with `ls-lb-del` & `lr-lb-del` commands to remove
association of the lbs from the removed switches and
routers. These commands fail together because the switches
and routers are not present in ovn.
This PR updates the LBcache as soon as we remove the
routers and switches.
Before the PR:
```
I0827 08:52:51.185522      50 ovs.go:209] exec(172): …
```
=> Fix lb delete during node deletion

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go
Fixes #1997438, where any update to an EgressFirewall (including a cluster upgrade) causes an error as soon as more than one ACL UUID are retrieved and parsed, leading to the EgressFirewall eventually not being correctly set. This is easily reproducible in local gateway mode.
This patch proposes the following changes:
- Added "--format=table" to all "ovn-nbctl find" calls in order to have entries separated by a newline character and not by two newline characters, which is the default if "--format" is not specified;
- Replaced calls to "Strings.Split" on "sep=\n" with a safer "Strings.Fields", which splits based on whitespace characters and trims them too.
=> Bug 1997438: egressfirewall not set after upgrade

go-controller/pkg/ovn/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go
After the modifications made to `ensureJoinLRPIPs` by PR: #2434 the
function "lost" thread-safety. This meant that we could have one
go-routine - spawned by the network policy watchers - and another by the
node watcher, race and try to `Allocate` the same IP for the same
logical switch. Causing the second to error with `ErrAllocated`. We can
re-work the existing locks and have `ensureJoinLRPIPs` and
`releaseJoinLRPIPs` locks that span the caching functions, ensuring that
that all cache operations are thread-safe.
This is "soaking" in OpenShift CI, using: https://github.com/openshift/ovn-kubernetes/pull/705 which should give it a stronger CI signal. 
/assign @dcbw 
**- Description for the …
=> Make `ensureJoinLRPIPs` thread-safe

go-controller/pkg/ovn/master.go
Lets us watch leader election events between ovnkube masters
and debug leader election problems.
=> master: give leader election an event recorder

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
`Failed to get IPs for logical router port rtoj-GR_ip-10-0-245-226.us-west-2.compute.internal for logical router port rtoj-GR_ip-10-0-245-226.us-west-2.compute.internal`
to
`Failed to get IPs for logical router port rtoj-GR_ip-10-0-245-226.us-west-2.compute.internal`
=> lsm: remove duplicate wording in error message

go-controller/hack/test-go.sh
Specifying (as an example)
```
PKGS="github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn" GINKGO_FOCUS="creates an address set for existing nodes when the host network traffic
namespace is created" make check
```
currently is broken because the white space characters for the defined
test case are not replaced correctly. We need to do the same thing we do
for that argument in our E2E tests:
https://github.com/ovn-org/ovn-kubernetes/blob/8fc9298e56457f66b39415992d8ec7d838d4217e/test/scripts/e2e-cp.sh#L75
FYI: also doing:
```
PKGS="github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn" hack/test-go.sh focus "creates an address set for existing nodes when the host network traffic namespace is created"
```
will work, and run the tests without a container
/assign @flavio-fernandes 
**- …
=> Fix ginkgo argument for unit test case specification

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/config/config.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_smartnic_test.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/util/util.go
Newly added option [1] allows to distinguish new vs old logical
ports for recreated pod with the same name, thus making "ovn-installed"
option reliable again [2].
1. Add "iface-id-ver" option to logical and OVS ports
[Upgrade][master] add iface-id-ver only for newly created Ports,
no ovn version check, since if iface-id-ver is not enabled in ovn, it will be just ignored
[Upgrade][node] no additional actions are needed, because existing Interfaces don't need
iface-id-set since it won't be set in master. Ovn support for iface-id-ver will be checked
during cni server creation
2. Add OvnKubeNodeConfig option "ovn-iface-id-ver-disabled" to manually
disable this feature for older ovn versions
3. Change test mock that checks ovs add-port command
4. Add common function to compose LogicalPort name …
=> Add "iface-id-ver=${POD_UID}" tuple to the external-ids of logical and OVS ports

go-controller/Makefile, go-controller/hack/lint.sh
This PR has two commits:
- remove install.tools target since it is not being used
```
make lint only works within the container, so there is on point in
installing golangci-lint tools on the build machine.
```
- move golangci-lint to version 1.42.0
```
the 1.33.2 golangci-lint container uses go version 1.15.6 and that causes
following error:
cannot find package \".\" in:\n\t/app/vendor/io/fs
so move to 1.42.0 version of golangci-lint that contains go version 1.16.7
and doesn't have the issue of not finding `io/fs` package.
```
=> fix golangci-lint related issues

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
Currently the LSP that connects the node switch to the cluster router
has its "addresses" column set to LRP's MAC address, which is incomplete
(missing IP) and redundant (MAC is already specified in the peer LRP).
What's worse, it leads to a problem that the ARP responder flows are not
installed for the LRP's IPs on the switch pipeline, which in turn causes
that all ARP requests from VIFs on the LS to the LRP's IP get flooded on
the LS and one of the copies hits the LR pipeline, which in turn leads to
mac-binding learning for the VIFs IP-MAC pair, propagating to SB DB,
and ovn-controllers installs extra OVS flows because of this. All these
are unnecessary because the VIFs' IP-MAC are known beforehand and no
need for the dynamic mac-bindings.
This patch fixes the problem by setting the …
=> Set node switch's router port's addresses to "router".

go-controller/pkg/cni/helper_linux.go
Due to https://bugzilla.redhat.com/show_bug.cgi?id=2003193 where crio is not cleaning up leftover veths/netns...overtime OVS CPU climbs to 100% and performance degrades in the node. This ensures OVN CNI cleans up the ports rather than relying on kublet/crio.
=> Ensure host veths are cleaned up properly

go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go
So if I'm understanding correctly this 
```
keepIPTRules = append(keepIPTRules, getGatewayIPTRules(svc, []string{l.gatewayIPv4, l.gatewayIPv6})...)
```
Is only called in the syncServices function for Local GW and it's broken , It was creating iptables rules like so 
```
for _, gatewayIP := range gatewayIPs {
rules = append(rules, getNodePortIPTRules(svcPort, gatewayIP, svcPort.Port)...)
}
```
So a rule for traffic Destined to the nodeport <svcPort> that DNATed  the traffic to the `<ovn-k8s-gw0 IP>:<servicePort>`, which Isn't a real endpoint. Also no where else in the LGW node code do we add iptables rules like this  
Instead on Service Add in the LGW Node code we use that same IP [here](https://github.com/ovn-org/ovn-kubernetes/blob/fae10ffecb1b79e3db4eec384d45aaaa88d09703/go-controller/pk …
=> Fix LGW Node `SyncServices`

go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, test/e2e/e2e.go, test/e2e/util.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1985838
Specifically when `OVN_NETFLOW_TARGETS` is set and eventually unset it does not clear the existing OVS collector targets. 
This PR also add's more e2e coverage and fixes a flake in the netflow export test which has been laying around.
=> Fix collector

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go
there are two commits:
1. return on error while parsing node's subnet annotation
```
on node addition to a cluster, say we failed in performing gateway setup.
the node is added to gatewayFailed store. on next node update,
syncNodeGateway() is called and it could be that the node still doesn't have
host-subnets node annotation set and we will return nil from that function
and remove the node from the gatewayFailed store without setting up gateway.
```
2. no need to obtain node's host-subnets annotation instead use the passed arg
=> fixes as it relates to node addition/update handling

go-controller/pkg/ovn/ovn.go
The code was using the initially stored pod object to determine if the
pod was scheduled or not, rather than the current state of the pod.
=> Fixes skipping pods accidentally in retry

contrib/kind.sh
(This is my first pull request here, I followed the guidelines, but apologies if I missed something)
When deploying ovn with the kind.sh script on a system without ipv6 support, the deployment fails because sysctl can not find ipv6 key : 
> sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory
Adding the --ignore flag tell sysctl to ignore this error.
This should be safe to ignore it there, since the function wants to disable ipv6 anyway.
Signed-off-by: Olivier Cazade <ocazade@redhat.com>
=> kind.sh: Ignore missing key when disabling ipv6

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_dns.go, test/e2e/e2e.go, test/e2e/unidling.go
This patch fixes bug BZ 2000057, where a panic occurred when, after deleting a EgressFirewall with a DNS entry,  the corresponding DNS A record stored locally expires.
-  Added a new channel named "deleted" to the EgressDNS struct, so tha…t the domain name (if any) of a newly deleted EgressFirewall can be passed over to the Run() loop, which keeps track of DNS records and updates them as soon as they expire. This prevents inconsistencies between current EgressFirewalls and corresponding DNS records, which eventually led to a panic in a customer case.
- The aforementioend panic is now avoided by checking for the presence of the given DNS domain to delete in a map, before proceeding to update its (pointer) value.
-  Fixed type assertion when deleting EgressFirewalls, which resulted in DNS …
=> Bug 2000057: panic after EgressFirewall deletion and DNS record expiration

go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/gress_policy_test.go
with the support for this feature(alpha in 1.21 and beta in 1.22), the
network policies can be authored with port range. OVN already supports
port range, so it is is just a matter of implementing the support for it
in OVN K8s.
we don't need to check for the validity of the endport as it relates to
port (it should be >=, endport can't exist without port, and so on) since
it is already checked for us by the k8s apiserver.
@astoycos @dcbw @trozet PTAL
=> add support for NetworkPolicyEndPort feature

go-controller/pkg/util/libovsdb.go
Previously we only created a client and monitored the cache for the NB
DB, this resulted in an empty cache generation for the SB DB (which we
also need to perform operations against). This fixes that
/assign @flavio-fernandes @jcaamano 
=> Generate client with monitor for SB and NB DB

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
To check if a particular node is reachable ovn-kubernetes is using the node's primary IP to open a TCP connection on port 9.
This is not going to work if the cluster doesn't allow for this type of traffic.
To avoid connecting to the node's primary IP use one of the node's logical switch management port addresses.
PTAL @alexanderConstantinescu @danwinship @flavio-fernandes
=> Bug 2002657: ovn-kube egress IP monitoring is using a random port over the node network

test/e2e/e2e.go, test/scripts/e2e-cp.sh
This commit fixes some previously skipped E2E tests by using an alternative set of addresses and subnets for IPv6 clusters.
It also enables the control-plane IPv6 tests in a separate commit.
=> Fix E2E IPv6 tests: adapt addresses and subnets

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/ovn/controller/services/repair.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/libovsdbops/loadbalancer.go, go-controller/pkg/ovn/libovsdbops/router.go, go-controller/pkg/ovn/libovsdbops/switch.go, go-controller/pkg/ovn/libovsdbops/util.go, go-controller/pkg/ovn/loadbalancer/lb_cache.go, go-controller/pkg/ovn/loadbalancer/lb_cache_test.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/vendor/github.com/ovn-org/libovsdb/mapper/mapper.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/bindings.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/mutate.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/transact.go, go-controller/vendor/modules.txt
Moves all LB operations over to libovsdb. Worth mentioning:
- libovsdb low level operations have been aggregated in ovn/libovsdbops package to avoid cluttering main bussiness logic. Every operation has two versions, one that returns libovsdb operations for batching and another that directly transacts that operation.
- Aggregated all ops in a single transaction where reasonable.
=> libovsdb: Use libovsdb for load balancer operations

.github/workflows/test_periodic.yml
This fixes the ovn-ci-periodic job which used to fail always previously
Closes #2406
=> CI: Fix ovn-ci-periodic job

go-controller/pkg/ovn/libovsdbops/util.go, go-controller/pkg/util/libovsdb.go
Set libovsdb timeout to 10s due to observed delays of up to 5s in
scale testing. Once scale improvements are in this might be lowered.
Add timeout context for Transact.
=> libovsdb: tweak timeout

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Previously nsInfo was holding not only a map of gateways per namespace,
but all of the routes per pod in an external gateway enabled namespace.
This means that during all external gateway route adds/deletes nsInfo
would need to be locked. This creates heavy contention in cluster
specifically using external gateway functionality.
This breaks out the pod routes portion into its own cache, which has
individual locks on a per pod basis. This allows exgw routes to be added
and removed without needing nsInfo lock. Additionally, since locks are
on a per pod basis, it provides less overall contention across the
cache.
=> Reduce nsInfo contention on external gateway ops

go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
Change libovsdb for logical switch port operations specifically for
pod creation.
reorganized some of the testing that depends on the logical switch port
creation.
=> [libovsdb] Use libovsdb for logical switch port operations

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/ovn/master.go
with the effort to remove the go-ovn bindings from ovn-kube there remove
the go-ovn SB client from hybrid overlay. Nothing is using it at this
point.
=> remove go-ovn southbound client from hybrid overlay

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/node_ip_handler_linux.go
Address manager needs to update host-addresses annotation only when there is an actual address change
1. Create `nodeAnnotator` in `newAddressManager` instead of using an existing one, this avoids sending annotations that were added by other components.
2. Modify `addressManager` so it will try to set the annotations only if there was an actual change, not on every netlink notification.
2. Remove redundant `nodeIPManager` creation from `gateway_init.go`, it is always created in `GatewayModeShared`: https://github.com/ovn-org/ovn-kubernetes/blob/12074303166c94bec47c21ffb90f97bd0863b66d/go-controller/pkg/node/gateway_shared_intf.go#L1127
PTAL: @dcbw @astoycos @flavio-fernandes
=> Bug 1998515: ovn-kubernetes repeatedly updates host-addresses annotation on ipv6/dual-stack hosts

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy_test.go
Deleting a pod leaves:
```
E1006 08:16:21.482432      50 pods.go:634] KEYWORD: POD DELETED?
```
if deletion was a success, because a debug statement snuck in.
/assign @JacobTanenbaum
=> Nit-Fix: Remove debug statements from LSPDel

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
Grouping mutex close to data source enhances
code readability and mutex purpose.
I know this doesn't suit the current struct's lock/resource style, but that can be changed bit by bit.
Suggested by @trozet here: https://github.com/ovn-org/ovn-kubernetes/pull/2537/files#r724988531
```None```
=> Embed mutex into allocator struct

go-controller/pkg/factory/handler.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Rather than waiting 10 seconds and blocking the network policy handler,
dont block, and ensureNamespace via the informer/kclient. nsInfo
properties derived from namespace (like exgw, acl logging, multicast)
will be updated now during ensureNamespaceLocked, if the namespace is
obtainable.
Also fixes unsafe access to nsInfo in several places in the network
policy code.
=> Remove waitForNamespaceLocked

go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
For port security and port addresses the value needs to be a space
separated string rather than individual elements in an array.
=> Fixes incorrect syntax for pod addresses

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Currently, anything on the host network trying to access a service which is backed by egress IP matching pods will fail. This is because we end up in the below described traffic flow.
Keep in mind that for egress IP to function currently we have the following routing table:
```
101 ip4.src == 10.128.0.0/14 && ip4.dst == 10.10.92.150/32           allow
101 ip4.src == 10.128.0.0/14 && ip4.dst == 10.10.93.155/32           allow
101 ip4.src == 10.128.0.0/14 && ip4.dst == 10.10.94.22/32           allow
101 ip4.src == 10.128.0.0/14 && ip4.dst == 10.128.0.0/14           allow
100                             ip4.src == 10.128.2.37         reroute
100                            ip4.src == 10.129.2.169         reroute
```
The 101 rules are setup so that packets are not rerouted between nodes for …
=> [EgressIP]: Fix host network to service backed by egress IP pods

go-controller/pkg/ovn/egressgw.go
While creating an exgw pod, we try to unmarshall the `network-status`
annotation that is set by the multus CNI plugin. Since multus only
sets the annotation after it calls the SRIOV plugin this means
ovn-k must return a successful CNI_ADD result.
Currently we return the error to the top and fail to create the pod,
this blocking the pod creation. Let's just log an error instead.
Before the PR:
```
I1007 19:17:30.532046      38 egressgw.go:177] External gateway pod: e2e-gateway-pod, detected for namespace(s) bar
I1007 19:17:30.532099      38 pods.go:262] [default/e2e-gateway-pod] addLogicalPort took 42.449531ms
E1007 19:17:30.532136      38 ovn.go:567] failed to handle external GW check: unable to unmarshall annotation …
```
=> Don't return the error when annotation cannot be unmarshalled

.github/workflows/test.yml
Adjust the timeouts for e2e tests. Cap kind deployment and kubernetes e2e
tests to 30 and 60 minutes respectively. Allow control-plane tests to
run for up to 150 minutes. Add some buffer for all other steps.
Fixes #2607
=> CI/CD: Ajust e2e timeouts in github action workflow

go-controller/pkg/ovn/master.go
Deleting a node currently causes ovnkube-master to panic. The reason is: `OperationModel` requires `Model` to be specified as to automatically generate `ExistingResults` when performing a `Delete`, see: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/libovsdbops/model_client.go#L190-L198
A better solution might be to use `reflect` and infer the type of `ExistingResult` from the function argument specified in `ModelPredicate`. But that might be a task for later, in the mean time this will fix the panic. 
/assign @jcaamano 
=> Fix panic on node object deletion

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/util/mocks/NetLinkOps.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
This PR introduces the following changes:
- Recreate existing service routes on startup to allow for MTU changes
- Fix `util.LinkRoutesDel` to work with links that have a default route defined
=> Recreate existing service routes on startup to allow for MTU changes

go-controller/pkg/ovn/egressgw.go
If a single routeInfo had multiple external routes that matched the
same gateway IP, that routeInfo could be added to the returned list
multiple times. It was only locked once, however.
But deletePodGWRoutesForNamespace() iterates over the list returned
by getRouteInfosForGateway() and calls Unlock() on each element in
the list, which can create an unbalanced locking situation (multiple
Unlocks for a single Lock) in the above situation where a routeInfo
has multiple external routes matching the same gatewayIP.
@trozet @alexanderConstantinescu
=> egressgw: only return unique elements from getRouteInfosForGateway()

go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/master.go
Hey,
This PR adds two things. It adds IPSec metric and also removed the need for go-ovn lib and using libovsdb instead.
The detection if IPSec is enabled or disabled is retrieved from OVN NB NB_Global table.
Apologies for bundling in the removal of go-ovn here but it simplified the PR for me because I needed libovsdb to access the IPSec boolean in OVN NBDB. This is not available with go-ovn API.
No changes to e2etimestamp metric functional output.
This IPSec metric gives us visibility into whether this feature is used.
=> Metric: IPsec

go-controller/cmd/ovndbchecker/ovndbchecker.go
when the ovn-dbchecker was receiving a SIGTERM it would
catch it, but the channel never closed so it never
quits. Fix that.
=> run RunDBChecker as goroutine

go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go, go-controller/pkg/util/subnet_annotations.go, go-controller/pkg/util/subnet_annotations_unit_test.go
Currently any update to any of the node fields triggers an `updateNode` from the `updateFunc` of
node watcher. For each node, every 5mins there is `updateNode` being triggered since something
seems to be updating the node object. In reality `updateNode` only needs to be called if node.Name
or switchName or gwRouterName or hostSubnet annotation or L3Gateway annotation change (which
are rare changes) and it has no effect on other unrelated field changes. Most of the times we
end up parsing annotations and computing ip address from the annotations only to realize the
actual node fields are the same as in the cache and we return without taking any action.
In large prod clusters, even if its event-triggered it will cause a lot of noise/unnecessary …
=> Scale: Don't trigger updateNode unless needed

go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/ovn.go
Even though we can have only one egress firewall per namespace, we would like to know what proportion of namespaces have an egress firewall.
1. Configure a EgressFirewall CR:
```
apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
name: default
spec:
egress:
- to:
cidrSelector: 1.1.1.3
type: Allow
- to:
cidrSelector: 0.0.0.0/2
type: Allow
```
2. Curl the /metrics endpoint (:9409 w/ KinD) and grep for `egress_firewalls`. It should show an integer of one.
3. Delete the CR created in step one.
4. Curl the /metrics endpoint (:9409 w/ KinD) and grep for `egress_firewalls`. It should show an integer of 0. 
=> Metric: Egress firewall count

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go
Currently ovnkube-node & -master pods fail to start, when the config files contain an unknown field or unknown section. This can lead during updates to problems in the following scenario:
1. ConfigMap is updated
2. ovnkube-node rollout starts
3. somehow an ovnkube-master pod needs to be (re-)started (be it through eviction from a node or something else)
4. the newly started ovnkube-master pod isn't aware of the new config structure and fails to parse the config, resulting in a crashloop of the newly ovnkube-master. This can result in a stucking rollout.
Fixes [BZ 1988440](https://bugzilla.redhat.com/show_bug.cgi?id=1988440)
This PR addresses this and makes the config parsing more resilient against unknown fields or sections. 
**- How to verify …
=> Make config parsing more resilient for unknown config fields

.github/workflows/test.yml, .github/workflows/test_periodic.yml
It is currently failing our CI, and I don't think anyone uses it anyway.
=> Remove generating test report

go-controller/pkg/node/gateway_shared_intf.go
In downstream CI there are many occurrences of:
E1109 13:20:02.794662    3252 gateway_shared_intf.go:172] failed to parse Ingress IP. IP is empty.
Ingress can use either IP or hostname, and in the past we skipped trying
to create flows for services where the IP was empty. Somehow during
libovsdb migration we are now producing errors.
Previous code was like this:
https://github.com/openshift/ovn-kubernetes/blob/release-4.8/go-controller/pkg/node/gateway_shared_intf.go#L89
=> Fix logging invalid errors on ingress IP

go-controller/pkg/ovn/master.go
Port groups have been supported for a while in OVN, no reason to check
this anymore.
=> Remove fatal check for port groups

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go
since implementing libovsdb the escape character in the matchStr is extra and goes
into the database as a backslash character instead of escape
=> fix hybrid overlay communication through services

go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/libovsdbops/model.go, go-controller/pkg/ovn/libovsdbops/router.go, go-controller/pkg/ovn/ovn.go
This PR addresses three things that were broken in LGW upgrade path:
1. cleanupDGP: Add sbdb.MACBinding table to `getListfromModel`. If not, we will hit:
```
panic: getModelList: unknown model *sbdb.MACBinding
goroutine 106 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/libovsdbops.getListFromModel(0x1a57c00, 0xc000abecd0, 0x1e05144, 0x0)
/home/surya/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/libovsdbops/model.go:184 +0x5f7
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/libovsdbops.(*ModelClient).buildOps(0xc000b05430, 0xc000b05330, 0x0, 0xc000b05500, 0x1, 0x1, 0xc000abecd0, 0x50, 0x50, 0x1ce6b40, ...)
/home/surya/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/libovsdbops/model_cli …
```
=> Libovsdb fixes for lgw upgrades

go-controller/pkg/ovn/gateway_init.go
Upon upgrade to new SGW, we already call delPbrAndNatRules
which is removing the 1003 & 1005 policies.
We don't need to do it again everytime in addPolicyBasedRoutes.
We are removing 1003 in two places to safe guard upgrades to new SGW mode.
1) https://github.com/ovn-org/ovn-kubernetes/blob/42639ad6e644dad0dd84cc3ba641b480156b4bc9/go-controller/pkg/ovn/gateway_cleanup.go#L116
2) https://github.com/ovn-org/ovn-kubernetes/blob/42639ad6e644dad0dd84cc3ba641b480156b4bc9/go-controller/pkg/ovn/gateway_init.go#L784
Let's just use the proper cleanup path for upgrades where we are removing 1005 & 1003. Anyhow doesn't make sense we are simply removing only 1003 (and not removing 1005) in `addPolicyBasedRoutes` path.
=> Remove redundant LRP removal in upgrade path

go-controller/pkg/ovn/libovsdbops/transact.go
We used to log all nbctl commands via the daemon, and it was incredibly
useful for debugging. We need the same logging at least for the short
term with libovsdb, otherwise we cannot tell what is being
configured...especially in level driven scenarios like services
controller.
=> Log all nbdb txns via libovsdb

go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go
When deciding if a service needs updating, we do a reflect.DeepEqual on
the existing load balancers that are stored in a cache, vs the load
balancers that would be built by the operation. This comparison was
incorrect, because it was comparing the UUID field, which will never be
equal. The end result is potentially a lot more pressure on OVN for
transactions that essentially do nothing.
=> Fixes unnecessary loadbalancer OVN transactions

go-controller/pkg/ovn/libovsdbops/acl.go
Fixes this error:
2021-11-12T01:53:02.766Z|02680|ofctrl|ERR|could not find meter named "outport == @a5785862186530551571_ingressDefaultDeny"
=> Fixes incorrect meter configuration for ACL

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/node_ip_handler_linux.go
Node annotator address changes may fail updates to Kube api.
To handle such cases, make sure they are in sync by comparing the
annotator value against kapi.Node.
Co-Authored-By: Tim Rozet <trozet@redhat.com>
=> Ensure node host address annotations are in sync with api server

go-controller/pkg/ovn/libovsdbops/model.go
In https://github.com/ovn-org/ovn-kubernetes/pull/2631 there was a rebase disaster and this resulted in incorrectly returning the uuid of sbdb.MACBinding instead of the model object list.
=> Fix sbdb.MacBinding model

test/e2e/e2e.go, test/scripts/e2e-cp.sh
- Existing netflow export test is renamed and now supports netflow_v5, ipfix, sflow.
- The original test only validated the export of netflow v5 (legacy netflow) data, which does not support IPv6 by design. In order to validate flow data export in an IPv6 cluster, we can now choose between IPFIX and sflow; also, the test now supports an IPv6 endpoint and is again enabled for IPv6 single-stack clusters;
- For the time being we're only testing netflow v5 in IPv4 (as before) and sflow in IPv6, because:
(1) The test itself is long (~5 minutes);
(2) The current implementation of the flow collector container (cloudfare/goflow) doesn't support IPFIX data generated by OVS (https://github.com/cloudflare/goflow/issues/99)
This patch addresses https://issues.redhat.com/browse/SDN-2059
**- How to …
=> add support for multiple flow monitoring protocols and for IPv6 endpoint in existing netflow test

go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/metrics/ovn_northd.go
Our downstream distribution refers to ovn-kubernetes master
with label app=ovnkube-master intead of name=ovnkube-master.
This PR uses both to search for ovnkube master.
=> Metrics: Add additional label to refer to ovnkube master

go-controller/pkg/node/node_ip_handler_linux.go
Should ErrorCallback from addressManager take place after
stopChan is closed, it is not safe to call sync() because
c.watchFactory is no longer useable (see below).
Fortunately, sync() is already called via subScribeFcn as
well as periodically, so removing it from ErrorCallback
is a simple way of resolving this case.
Also fixing a trivial formatting issue in sync() when doing
isValidNodeIP().
Fixes: #2657
CI job where this error takes place:
https://github.com/ovn-org/ovn-kubernetes/runs/4267007250?check_suite_focus=true
I1119 17:12:47.755099   18058 node_ip_handler_linux.go:213] Skipping invalid IP address found on host: %s::1
I1119 17:12:47.755140   18058 node_ip_handler_linux.go:213] Skipping invalid IP address found on host: %sfe80::20d:3aff:fe8e:860c
panic: runtime error: invalid …
=> addressManager should not call sync() from ErrorCallback

go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/egressfirewall_dns_test.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway/gateway_test.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/libovsdbops/model_client_test.go, go-controller/pkg/ovn/libovsdbops/switch_test.go, go-controller/pkg/ovn/loadbalancer/lb_cache_test.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/testing/libovsdb/libovsdb.go, go-controller/pkg/util/net_unit_test.go, go-controller/pkg/util/util_unit_test.go
Two unrelated things:
1) the libovsdb test server was being shut down concurrently with the client, which could trigger the client's reconnect handling and un-necessarily block tests for a while. Split the shutdown logic for client and server so that callers can shut them down in the right order (client first, then server) and prevent that. As a bonus actually clean things up rather than piling up tons of goroutines that we aren't properly terminating.
2) It turns out most tests don't change the config options and don't need to have the urfave/cli/v2 App object wrapping the testcase since they just use the defaults. But FakeOVN currently needs it... so remove that from FakeOVN and let the few tests that change the config do it directly rather than with CLI options pass to the App object.
=> Two unrelated CI cleanups

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, test/scripts/e2e-cp.sh
Currently we use the disableSNATMultipleGWs option for externalgws feature to ensure we
do not SNAT podIPs to the nodeIP. This means we enable a per pod snat for the pods not
managed by externalgws.
EgressIPs feature can work only if the SNAT for an egressIP managed pod is to the egressIP
and not the nodeIP as is the case when disableSNATMultipleGWs is set.
So far we were declaring these features as mutually exclusive. Let's stop that and instead
add the logic to simply delete SNAT to nodeIP for an egressIP managed pod & add SNAT to nodeIP
for an egressIP un-managed pod.
**- Note to reviewers**
e2e tests already exist for egressIPs, they were skipped when `disable-SNAT` was true, …
=> Make egressIPs compatible with externalgws

go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/libovsdbops/sb_global.go
Some minor fixups, and ensure we return it's error if any
in RegisterMasterMetrics
Ensure we monitor the sbdb's sb_global table since
it is fetched for metrics purposes
fixes 
`2021-11-30T17:02:56.194213143Z E1130 17:02:56.194158       1 master.go:208] Failed to get global options for the SB_Global table err: object not found`
=> Fixup FindSBGlobal and monitor sb_global

go-controller/pkg/ovn/policy.go
when Pod add/update event is handled for selected Pods of a given
policy, the portInfo in the cache may still be that of the staled Pod.
In order not to add the stale port into the portGroup, stop processing
and wait for the next Pod update event.
Signed-off-by: Yun Zhou yunz@nvidia.com
=> port missing in the network policy port_groups

go-controller/pkg/metrics/ovn.go
```
promtool check metrics < ovn.txt 
ovn_controller_integration_bridge_geneve_ports_total non-counter metrics should not have "_total" suffix
ovn_controller_integration_bridge_patch_ports_total non-counter metrics should not have "_total" suffix
```
If a metric is not counter based, it is recommended to not have _total suffix.
=> Metrics: remove "_total" suffix from non-counter metrics

go-controller/pkg/metrics/ovn.go, go-controller/pkg/metrics/ovn_db.go
Prometheus recommends to only use base units (seconds/
bytes) [1].
Also, corrected openflow probe interval that was in
consumed in seconds [2] but the `HELP` field said milliseconds.
[1] https://prometheus.io/docs/practices/naming/#base-units
[2] https://www.ovn.org/support/dist-docs/ovn-controller.8.html
=> Metrics: convert metrics to base prometheus units

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/healthcheck_test.go, go-controller/pkg/node/node_dpu_test.go
This will ensure stale pod OVS interfaces are purged by
the OVS service during a hard reboot for a node
This leaves the mechanism we have in ovnkube node to
periodically search for and remove stale interfaces, but improves 
the function by batching the interface deletion commands
=> Make container OVS interfaces Transient, Batch Periodic interface scrubbing

.github/workflows/test.yml
Run full e2e tests on upgrade jobs instead of only the Networking
Granular Checks.
Fixes #2641
=> CI: Run full e2e tests on upgrade jobs

go-controller/pkg/ovn/master.go
When we lose leadership we exit to trigger a restart of the container
to come back up as a follower. That is not an error condition so
exit(0) makes more sense. When we exit(1) it's noted in some
CI jobs that it was an error condition and indicative of some
problem. This will remove that scary report in our CI.
with exit(1) our monitor logs look like this:
Nov 19 20:25:14.241 E ns/openshift-ovn-kubernetes pod/ovnkube-master-bpq94 node/ip-10-0-165-169.us-east-2.compute.internal container/ovnkube-master reason/ContainerExit code/1 cause/Error -11-19T20:24:43.215Z|02253|reconnect|INFO|ssl:10.0.241.143:9641: connected\n2021-11-19T20:24:43.221Z|02254|fatal_signal|WARN|terminating with signal 15 (Terminated)\n2021-11-19T20:24:43.221Z|00002|daemon_unix(monitor)|INFO|pid 13 died, killed …
=> exit 0 instead of 1

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cni_dpu_test.go, go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/helper_linux_test.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/node/node_dpu.go, go-controller/pkg/node/node_dpu_test.go
PodRequest`IsDPU is currently being used to capture whether ovnkube node
is running in DPUHostMode or not. However, IsDPU could mean two things:
-- DPU Host or DPU itself. Since IsDPU here is meant to track
DPUHostMode lets change the name to mean DPUHost mode.
Also, there is no need for Server`mode field, so remove it as well.
@adrianchiris PTAL
=> PodRequest`IsDPU field is confusing and must reflect a mode type

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/libovsdbops/switch.go
We are adding handling the logic behind local and shared gateway migrations. Specifically we handle two things:
- delete the static route towards management port when moving to shared and delete the static route towards join subnet when moving to local wrt to the hostSubnet source prefix routes on ovn_cluster_router.
- similar to how we were already deleting acls from node switches when moving to shared, we will now start deleting acls from join switches when moving to local.
Apart from these two differences and a few others like 501 hybrid policy (which is already migration ready), we really shouldn't have any differences between the two gateway modes as long as users properly upgraded it using the `topology-version` for older clusters. New …
=> Support migrations between LGW  and SGW

dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/mocks/CNIPluginLibOps.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/utils.go, go-controller/pkg/config/config.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/node.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
routable-mtu setting is introduced to faciliate a procedure allowing to
change the MTU on a running cluster with minimum service disruption.
Given current and target mtu values:
1. Set `mtu` to the higher MTU value and `routable-mtu` to the lower
MTU value.
2. Do a rolling reboot. As a node restarts, `routable-mtu` is set on
all appropriate routes while interfaces have `mtu` configured.
The node will effectively use the lower `routable-mtu` for outgoing
traffic, but be able to handle incoming traffic up to the higher
`mtu`.
3. Change the MTU on all interfaces not handled by ovn-k to the target
MTU value. Since the MTU effectively used in the cluster is the lower
one, this has no impact on traffic.
4. Set `mtu` to the target MTU value and unset `routable-mtu`.
5. Do a rolling reboot. As a …
=> Add routable-mtu config setting

go-controller/pkg/ovn/egressgw.go
```   
1. ensureRouteInfoLocked() locks the cache
2. getRouteInfosForGateway() tries to grab the cache RLock() but is blocked on 1
3. ensureRouteInfoLocked() gets the routeInfo from the cache releases the cache lock
4. getRouteInfosForGateway() acquires the RLock() on the cache and begins iterating routeInfos
5. ensureRouteInfoLocked() locks the routeInfo
6. another call to ensureRouteInfoLocked() tries to acquire the cache lock, this blocks all new acquisitions of the cache RLock() per the RWLock documentation
7. the first ensureRouteInfoLocked() now tries to acquire the cache RLock() to validate that its routeInfo is still in the cache, but is blocked on 6
8. getRouteInfosForGateway() tries to lock the same routeInfo that 5 has already locked; never releases the cache lock
The core …
```
=> egressgw: fix deadlock due to behavior of RWLock

go-controller/pkg/ovn/master.go
when node is deleted, we need to deleted the node's logical switch and
the logical router port connecting the distributed router to the switch.
=> delete port connecting the distributed router to node's logical switch

go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/policy.go, test/e2e/unidling.go, test/scripts/e2e-cp.sh
Fix a race found with network policy and stateful sets,
and issue described in:
https://bugzilla.redhat.com/show_bug.cgi?id=2016446
Specifically when an LSP is recreated for a stateful set, it will have the same name as it's previous version, and the network policy code may grab the old version of the LSP, creating a security venerability. 
This patch ensures the net
=> Fix Netpol with stateful-sets

docs/design/external_traffic_policy.md, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/management-port_linux.go, go-controller/pkg/node/port_claim_test.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/types/const.go, test/scripts/e2e-cp.sh
This PR implements `ExternalTrafficPolicy=Local` type traffic flow on local gateway mode. The path would be `external->host->ovn-k8s-mp0->OVN->node-local-switch->load-balancer-DNATs->endpoint`
Depends on https://github.com/ovn-org/ovn-kubernetes/pull/2663 getting in first.
Tried and tested on KIND cluster. Docs have been written detailing the process: https://github.com/ovn-org/ovn-kubernetes/pull/2651/commits/6272b0c26f70fe8e9db1e77dbd524b7aaf231a2a
`Implement ETP=local for ovn clustered pods in LGW mode`
=> Implement ETP=local on LGW

go-controller/pkg/util/net.go, go-controller/pkg/util/net_unit_test.go
Addresses on LSP are a space separated value of mac and ip addresses.
This was fixed for setting the address on an LSP in:
https://github.com/ovn-org/ovn-kubernetes/commit/c7cad83baf4fd756ee7bb9a018453f8a20ef9295
However, the logic was never fixed in getPortAddresses to split the
string into mac and ip values. This leads to errors like:
failed to parse logical switch port "openshift-multus_network-metrics-daemon-qzmg7"
MAC "0a:58:0a:80:02:04 10.128.2.4": address 0a:58:0a:80:02:04 10.128.2.4: invalid MAC address
=> Fixes getPortAddresses being space separated value

go-controller/pkg/cni/cniserver.go
There's no point in limiting the timeout to something lower than the
CRI timeout; it just causes pods in large-scale clusters to hit the
kubelet retry backoffs and take even longer to bring up. Continued
improvements to OVN will reduce the need for longer timeouts in
the near future.
@trozet @girishmg @flavio-fernandes @jcaamano
=> cni: match default kubelet CRI operation timeout for CNI operations

go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Metrics duration between:
<b style="font-weight:normal;" id="docs-internal-guid-71d39544-7fff-afaa-d278-6a9c4ccb4e47"><div dir="ltr" style="margin-left:0pt;" align="left">
Name | From | To
-- | -- | --
pod_first_seen_lsp_created_duration_seconds | First seen in OVN-K | LSP created
pod_lsp_created_port_binding_duration_seconds | LSP created |  Port binding seen in libovsdb cache
pod_port_binding_port_binding_chassis_duration_seconds | Port binding | Port binding chassis update seen in libovsdb cache
pod_port_binding_chassis_port_binding_up_duration_seconds | Port binding chassis | Port binding up update seen in libovsdb cache
</div></b>
No clue if the bucket size or intervals are right yet. I plan to test that more to get the right intervals / no. buckets if folks think this would be good. …
=> Metrics: Add control plane metrics recorder

go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/libovsdbops/model.go, go-controller/pkg/ovn/libovsdbops/model_client.go, go-controller/pkg/ovn/libovsdbops/model_client_test.go, go-controller/pkg/ovn/libovsdbops/switch.go, go-controller/pkg/ovn/master.go
When matching for rows is done via a predicate function, there is
a flag called BulkOp. When that is `false`, it means that up to one row
should be found. In such cases, the changes proposed here will fill in
the uuid of row.
This saves caller from having to grab the uuid from the results
slice, normally done via the DoAfter attribute, like in the example below:
```
1 loadBalancerGroup := nbdb.LoadBalancerGroup{ Name: types.ClusterLBGroupName, }
2 loadBalancerGroupRes := []nbdb.LoadBalancerGroup{}
3 opModels := []libovsdbops.OperationModel{
4    {
5      Model:          &loadBalancerGroup,
6      ModelPredicate: func(lbg *nbdb.LoadBalancerGroup) bool { return lbg.Name == types.ClusterLBGroupName },
...
7      ExistingResult: &loadBalancerGroupRes,
8      DoAfter:        func() {
9 …
```
=> libovsdb: fill in uuid of matched row

go-controller/pkg/cni/cni.go, go-controller/pkg/cni/cni_dpu.go, go-controller/pkg/cni/cni_dpu_test.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/helper_linux_test.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/node/node_dpu.go, go-controller/pkg/util/dpu_annotations.go
on pod deletion we need to `rename` the VF device assigned to the Pod
to its original name and then move it to the host network namespace. we
were not doing the same and were hitting the following race:
t0: pod is deleted
t1: cmdDel returned immediately without releasing the VF
t2: kubelet released the DEVICE_ID
t3: udev kicks in and renames the VF device from `net1` to its original
name
Now between t2 and t3 a new Pod can come up and consume that DEVICE_ID
and cmdAdd`setupSRIOVInterface() will end up not finding that VF
=> release DPU VF assigned to the Pod back to the host network namespace

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/node_dpu_test.go
Set the ovs port as transient rather than the
interface. This along with configuring
systemd with `DELETE_TRANSIENT_PORTS = yes`
will result in the dedicated systemd service
`Delete Transient Ports` to remove stale
ovs ports and accompanying interfaces following
a hard reboot.
We found that this was done incorrectly in https://github.com/ovn-org/ovn-kubernetes/pull/2665/commits/e04c51346e574e229890071ffe60380e25ff9b59
while debugging SNO + OVNK scale :(
=> Set the OVS port as transient

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/ovn.go
When a pod currently gets deleted we continuously log:
```
E1216 04:58:39.376563       1 ovn.go:1018] Unable to delete egress IP matching pod: win-webserver-ec2amaz-9f873gh-deployment-kgqn7-78cffcfbf9-cn8n9/wmco-test, err: namespace "" not found
```
because the `new` argument passed to `reconcileEgressIPPod` is nil and hence we utilize an empty `newPod` when trying to get the namespace. This leads to spurious error logs. 
Also, most errors returned from `initEgressIPAllocator` are transient and just caused by some other controller not having annotated the node object at that point. Hence don't log it as an error. 
=> [Egress IP]: Fix spurious error logs

go-controller/pkg/ovn/master.go
When a node is deleted, the node logical switch and logical router
port connecting to the cluster router were not cleaned up in Northbound
db.  Fix this issue.
Issue 2711
https://github.com/ovn-org/ovn-kubernetes/issues/2711
Fixes: 79652ddc21c("delete port connecting the distributed router to node's logical switch")
=> Fix the node deletion cleanup.

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/modules.txt
To pick up https://github.com/ovn-org/libovsdb/pull/270
"cache: don't let RowByModel() recursively lock the RowCache"
@trozet @jcaamano
=> vendor/libovsdb: bump to ab69150b65ee937622385e60f360f6f6664de33f

.github/workflows/test.yml, go-controller/pkg/ovn/egressip.go
In order to make egressIPs and externalgws compatible, we re-add the SNAT to nodeIP during pod deletion 
when disableSNATMultipleGWs is true. While doing this, we need to check if the pod exists or not, because
`delLogicalPort` is called first before `deletePodEgressIPAssignment`. This will leave stale SNATs behind.
This bug was introduced in https://github.com/ovn-org/ovn-kubernetes/pull/2686
=> Check if pod exists before re-adding SNAT

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/datapath.go, go-controller/pkg/ovn/master.go, go-controller/pkg/util/ovn.go
https://github.com/ovn-org/ovn-kubernetes/commit/1b94cbb795af5817c7258109642d185bb3c3f07d
Managed to break Hybrid overlay specifically with the creation of the
MAC binding for the HO logical Port since we never actually passed
a valid sbClient to the ho Controller.
Also the unit tests were broken in the sense that we didn't have a test
that ensured we actually created all the needed OVN objects from
scratch, these objects are
The HO Logical Switch Port
The HO Logiacal Router Policy
The HO Mac binding
this commit fixes the above problems and more related to HO
found while fixing the tests
This bug was originally found in this downstream test run -> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1250/pull-ci-openshift-cluster-network-oper …
=> Fix Hybrid Overlay

go-controller/pkg/cni/helper_linux.go
Corrects formatting error in ovsargs.
Fixes: #2726
Signed-off-by: Hareesh Puthalath <hareeshp@nvidia.com>
Fixes a recent regression in the master branch caused by merge of PR #2675 
The issue shows up when creating pods with sriov vfs.
Adds right string formatting for ovsArgs.
=> Fix String Formatting error

test/e2e/util.go
Fix log message for failed commands in pokeEndpointHostname.
=> CI: Fix log message for failed commands in pokeEndpointHostname

go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go
When the traffic directed to a service of type loadbalancer reaches the nodes, it's not redirected to the service's cluster ips. This is
implemented for services of externalip / nodeport, but not for loadbalancer services. All the other logic is in place.
This will enable the integration with metallb when the traffic reaches the node from an interface different from breth0.
=> Create iptables NAT rules also for loadbalancer services

go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/pkg/cni/ovs.go, go-controller/pkg/config/config.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/util/ovs.go
This PR fixes the following issues:
* fix regex that was matching malformatted logs and errors
the current regex wasn't matching `single quote` in the first word. for
example -- can't, couldn't and so on . furthermore, it had issues with Klog.*S() invocations as well. fixed them.
*  avoid duplicate imports of packages
*  avoid possible nil pointer dereference
=> Log message fixes, possible nil dereference, and duplicate import

test/e2e/e2e.go
Delete and wait for namespaces inside Context.AfterEach with
f.DeleteNamespace(f.Namespace.Name). This makes sure that we actually
wait for the Namespaces to be deleted and avoids that host network pods
hog ports for too long.
Close #2728
=> CI: Wait on namespace deletion for host networked test pods

go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/ovndbmanager/ovndbmanager_test.go
Implement unit tests for ensureLocalRaftServerID,
ensureClusterRaftMembership, resetRaftDB and add minor
changes to these functions.
Fixes #2576
=> ovndbmanager: Implement unit tests for missing functions

contrib/kind.sh
Use absolute paths instead of relative paths so that kind.sh can be
run from any directory.
=> kind.sh: Use absolute paths instead of relative paths

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/metrics/ovn_northd.go
The two metrics:
- metricDBE2eTimestamp
- probe_interval
both make nb/sbctl calls to the OVN dbs, and
to ensure we only make ovsdb client connections
in the master process it makes sense to move these
to the master's set of metrics
It also renames the `probe_interval` metric to
`northd_probe_interval` to make things a bit easier
to parse
Follow up from the upstream meeting and the following slack thread 
https://ovn-org.slack.com/archives/C010SQ5FSNL/p1639585451036600
=> Move nb/sbctl metrics to master

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go
Contains fixes which try to detect/validate unique IPs across pods serving as external gateways. Includes a fix where the pod exgw cache was being keyed only on pod name instead of namespaced name.
=> Multiple ExGW cache validation/improvements

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/router_test.go, go-controller/pkg/ovn/egressip.go
When performing delete/mutation in ovn tables using modelClient.Delete(),
any rows returned by predicate will be removed.
Using doAfter is too late to decide the row's fate.
Also fixed issue in FindNatsUsingPredicate so that creating a slice of
NAT pointers uses the right address values.
=> egressip: fix usage of clientModel doAfter

go-controller/pkg/ovn/egressip.go
On CloudPrivateIPConfig deletion there can still be a finalizer left in the CR, instead of checking if there are any finalizers left check if new is nil.
/assign @alexanderConstantinescu 
=> Do not rely on empty finalizers during CloudPrivateIPConfig deletion

go-controller/pkg/metrics/master.go
Increasing log level to decrease log noise.
Pods maybe created and deleted before port binding
events hit the libovsdb cache causing unwanted
log noise. Its fine to discard metrics that do not hit the libovsdb
cache in an order we expect.
=> Metrics: Increase log level for CP recorder

docs/design/external_traffic_policy.md, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go
Host -> svc (ETP=local) backed by ovn pods
does not work in SGW because we add the DNAT
rule that converts the NP to CIP before it
hits the LB on the GR.
Current flow which is wrong:
1) traffic from host gets DNAT-ed to clusterIP svc using iptables
2) traffic sent to br-ex
3) hits the GR load balancer
4) gets DNAT-ed to the backend pods,
5) depending on if this is on the same node or a different one,
we'll have packet delivered to the pod if its on the same node,
or it passes via geneve tunnel to the destination node where the pod lives.
Technically if the backends are not local to the node, the
request should get rejected. This PR removes the iptable DNAT rule
if the traffic is of ETP=local type.
New flow:
1) NP traffic from host is sent to …
=> ETP=local, SGW: Add DNAT rule towards masquerade

go-controller/pkg/node/gateway.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go
The "mode" field in the l3gw annotation
actually denotes if there is a gateway
or not, and it means "have we created
an interface that we share with the node".
The value for this is always "shared" for
both local and shared modes and this is
confusing. Let's just update this with
the right mode.
We are unfortunately stuck with the names "local" and "shared" for historical reasons. Note that LGW no longer contains a "br-local" and "breth0" exists on both LGW & SGW, so LGW also contains the "shared interface with the node". Wish we could expose "egressRoutingViaHost" versus "egressRoutingViaOVN" instead.
Spin up a KIND cluster, …
=> Set l3GWConfig.mode correctly

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/egressfirewall.go
While creating ACLs, we are using the
nodeNames as the switch names on which
the ACLs need to be created on. This
will break on hybrid-overlay mode
since not all nodes have the OVN
switches. Let's use the libovsdb cache.
It is happening on pre-libovsdb times as well:
```
2021-10-26T10:38:38.106Z|02433|nbctl|INFO|Running command run
--id=@acl -- create acl priority=9999 direction=to-lport "match=\"(ip4.dst == $a5773229689678011375)
&& ip4.src == $a5811396932658691220 && ip4.dst != 10.128.0.0/14\"" action=allow external-ids:egressFirewall=test
-- add logical_switch winworker-mff7b acls @acl
E1026 10:38:38.106660       1 ovn.go:893] error executing create ACL command,
stderr: "ovn-nbctl: no row \"winworker-mff7b\" in table …
```
=> Pull up switch names from cache while creating ACLs

go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
using the logical switch manager to keep a cache of logical switch
UUIDs. Use the cache for adding and removing pods, this should increase
the performance since we don't have to figure out the UUID of the
applicable logical switches for every operation
=> Add logical switch UUID to the logical switch manager struct

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/router_test.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go
`deletePerPodGRSNAT` until now used to delete all
the SNAT's matching on the podIP. However this
SNAT could either belong to nodeIP or egressIP.
We really shouldn't be deleting all the SNAT's
of a pod and instead let the corresponding
controllers decide when they want to delete the
specific SNAT.
However if we are doing this, then we need to be careful 
since we rely on the l3gateway annotation to figure
out which externalID is chosen for deletion of the SNAT.
In case the annotation gets updated between an add and
delete, we'd be left with an inconsistent state.
So we add support to update GR SNATs when
l3gateway.IPAddresses change. Currently we update the
GR object when l3gateway annotations change, but we
do not update the SNATs on the router. So we are left with
stale SNATs towards old …
=> deletePerPodGRSNAT should match on externalIP

go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/ovs.go, go-controller/pkg/metrics/ovs_windows.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_go115.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_pre_go115.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector.go, go-controller/vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go, go-controller/vendor/modules.txt
Gather process metrics from the host OVS process using the default
pidfile locations.
=> metrics: enable host OVS process metrics collection

go-controller/pkg/config/utils.go, go-controller/pkg/config/utils_test.go
The ovnkube-node pod will fail if it receives a duplicate host:ip
for the Flow collector addresses. This commit removes the duplicate
flow collectors before forwarding to the ovs-vsctl command.
fixes #2039253
Reported-at: https://bugzilla.redhat.com/show_bug.cgi?id=2039253
=> Bug 2039253: avoid passing duplicate Flow endpoints to ovs-vsctl

go-controller/pkg/node/gateway_shared_intf.go
When switching a service from SingleStack to DualStack, its
ClusterIPs are updated. This change to ClusterIPs will now be detected
and ovnkube will write IPv6 DNAT rules to the host.
Fixes #2700
=> Shared gateway: Modification of ClusterIPs shall trigger svc update

go-controller/pkg/libovsdb/libovsdb.go
At larger scale a reconnect may need to download and parse a bunch of
database data. This (especially the JSON parsing in cenkalti/rpc2) can
take longer than we expect a normal ovsdb transaction to take, because
it's a lot more data.
If the reconnect takes too long our timeout will cancel the Monitor
call and attempt to reconnect, perhaps timing out again, etc.
@jcaamano @tssurya @flavio-fernandes @trozet
=> libovsdb: give reconnects more time to process than normal transactions

go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
This commit fixes addRetryPods to correctly
construct the retryPods cache. Currently
since we assign pointer as value in
retryPods cache in a loop, the values
get overwritten and this causes a nasty
bug in the retry pod logic. Some pods
get retried while others don't.
This PR also fixes addLogicalPort to
fail hard if the node.l3gateway annotation
is not set in disableSNATGWMode.
=> Fix pod-creation-retry

README.md, docs/external-ip-and-loadbalancer-ingress.md
The fact that OVN Kubernetes does not answer to ARP requests if External
IP or LoadBalancer Ingress VIPs are on the machine network can be
confusing. Document the current implementation and the reasoning behind
the current implementation.
=> Documentation: Document OVN ExternalIP and LoadBalancer.Ingress ARP

go-controller/README.md
Some go-controlle submodules make use of the go fs
package that were added to go version 1.16.
Trying to compile go-controlle module using go versions
older than v1.16 will cause some compilation issues.
Signed-off-by: Mohammad Heib <mheib@redhat.com>
=> Docs/go-controller: update minimum go version to v1.16

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/router.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/libovsdbops/transact.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/types/const.go, go-controller/pkg/util/util.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/notation.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/transact.go, go-controller/vendor/modules.txt
According to https://bugzilla.redhat.com/show_bug.cgi?id=2042001#c1
The cause of duplicate entries with the same name may occur in OVSDB due
to a raft issue during leader transition. This can end up entering
duplicate entries in OVSDB with the same name for things like load
balancers, switches, routers, etc. This commit adds a workaround.
=> Adds wait method for ovsdb operations that created named objects

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/address_set/address_set_cleanup.go, go-controller/pkg/ovn/address_set/address_set_test.go, go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go
Upon starting, failures when syncing OVN DB with K8 should
be considered fatal. Still, this change will introduce
retry logic to minimize pod restarts.
=> Make sync failures fatal after retries

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/helper_linux.go
The code for determining the default gateway was not taking into
consideration if the gateway interfaces was provided via config and
would return any default gateway found on the host. This is an issue
when a system has more than 1 default gateway, as well as if a user
provided an interface other than the real default gateway interface.
If the gateway interface is provided via config, the code now scopes
default routes found to only that interface.
=> Fixes finding default gateway for configured GW interface

dist/images/Dockerfile.fedora.dev, dist/images/Makefile
It's useful to be able to test with custom upstream OVS/OVN repos and/or branches but the previously built images were very large.  This PR significantly reduces the size of the built images.
CC: @aojea 
CC: @vishnoianil
=> dist: Update Dockerfile.fedora.dev to obtain smaller images.

go-controller/pkg/metrics/ovn_northd.go
Before registering OVN northd metrics, we check to see if ovnkube
master is co-located on the same node and repeatedly check if it
is present because ovnkube node may start before ovnkube master.
This repeated checking only causes one error mode to occur which
is a timeout error and this is incorrectly logged as an error
confusing the user.
The only failure path to occur within 'checkPodRunsOnGivenNode' can
be seen with increased log level.
=> Metrics: Fix incorrectly logged error when searching for ovnkube master pod

go-controller/pkg/libovsdbops/copp.go, go-controller/pkg/libovsdbops/meter.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/types/const.go
PR adds support for rate-limiting packets by availing the COPP feature provided by OVN. See https://bugzilla.redhat.com/show_bug.cgi?id=2011525 for details.
We have set the rate to random value of 25 packets per second, can be made configurable in the future like we do for acl logging,
Unit tests included. Verified on KIND:
```
sh-5.1# ovn-nbctl list copp
_uuid               : a1199870-9f5b-464b-b29c-52dc4f159244
meters              : {arp=arp-rate-limiter, arp-resolve=arp-resolve-rate-limiter, bfd=bfd-rate-limiter, event-elb=event-elb-rate-limiter, icmp4-error=icmp4-error-rate-limiter, icmp6-error=icmp6-error-rate-limiter, …
```
=> Add COPP to gateway routers for rate limiting pkts

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/util/pod_annotation.go, go-controller/pkg/util/pod_annotation_unit_test.go
When network policy would go to add peer pods via the handler, it would
commonly fail on initial add because it would fail to get pod IPs, due
to racing with the pod handler for the pod add event. This is OK,
because eventually the pod will get an update event once the ovn
annotation is added and the network policy handler will add it. However,
this would cause an error log to be spammed, especially with a lot of
pods and network policies in place.
This commit ignores logging errors on policy add/update events where the
pod has no IP either in the OVN annotation or in the KAPI pod IP fields.
Additionally, changes GetAllPodIPs function to be more readable and
eliminates a check in namespace.go for legacy PodIP field.
=> Fixes handling errors for getting IPs for pods

go-controller/pkg/ovn/egressip.go
When a pod matching an egress ip is scheduled and `ovnkube-master` is not running the following happens once `ovnkube-master` starts again:
1. The new POD gets an IP address assigned
2. Egress IP is configured using the following logic to get the pod IP: https://github.com/ovn-org/ovn-kubernetes/blob/7ba85e84aa489761d4958d953e0a1daeb0c10e8c/go-controller/pkg/ovn/egressip.go#L852-L869
3. Egress IP ovn config is removed  [here](https://github.com/ovn-org/ovn-kubernetes/blob/7ba85e84aa489761d4958d953e0a1daeb0c10e8c/go-controller/pkg/ovn/egressip.go#L1023) because `pod.Status.PodIPs`  is still empty when [generatePodIPCacheForEgressIP](https://github.com/ovn-org/ovn-kubernetes/blob/7ba85e84aa489761d4958d953e0a1daeb0c10e8c/go-controller/pkg/ovn/egressip.go#L1100) is called.
It is a timing …
=> Fix cache building used for removing stale egress IPs

go-controller/pkg/cni/helper_linux.go
ovsExec() doesn't return stderr in 'output', as it instead
returns a custom error with the stderr included in the error
message.
Fixes suppression of messages like:
```
W0205 18:14:55.491330    2131 helper_linux.go:452] Failed to delete OVS port 288c3f1cf2fdea0 for pod kubectl-608/agnhost-primary-kfhfv from br-int: failed to run 'ovs-vsctl --timeout=30 del-port br-int 288c3f1cf2fdea0': exit status 1
"ovs-vsctl: no port named 288c3f1cf2fdea0\n"
""
```
=> cni: fix logspam suppression for non-existing OVS port

go-controller/pkg/libovsdbops/model_client.go
nil string pointer wasn't properly checked while determining whether
it had empty value
=> some OVN NB Table's Name field is a pointer type since its optional

go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/cni/cniserver_linux.go, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/ovndbmanager/ovndbmanager_test.go, go-controller/pkg/util/nicstobridge.go, go-controller/pkg/util/ovs_unit_test.go
Go 1.13 introduced 0o prefixes for octal constants, for consistency
with 0b and 0x prefixes and to improve readability. See
https://go.dev/doc/go1.13#language for details.
This changes all octal constants to use 0o prefixes.
Signed-off-by: Stephen Kitt <skitt@redhat.com>
=> Use 0o prefixes for octal constants

go-controller/pkg/libovsdbops/meter.go, go-controller/pkg/libovsdbops/meter_test.go, go-controller/pkg/ovn/master.go
When ovnkube master is restarted, it will now update the ovn nb db
and it will set the meter_bands' rate according to the value in
acl-logging-rate-limit.
https://bugzilla.redhat.com/show_bug.cgi?id=2051954
Verification:
Spawn kind.sh with defaults in ha:
~~~
./contrib/kind.sh  --ha-enabled
~~~
Get a baseline from the ovndb:
~~~
sh-5.1#  ovn-nbctl list meter_band
_uuid               : 67b3d8b0-362f-4cf8-8b8b-f01662e0ffd0
action              : drop
burst_size          : 0
external_ids        : {}
rate                : 20
_uuid               : 7dca4687-670c-4113-b11d-44d3b42481c9
action              : drop
burst_size          : 0 …
=> ovnkube master: Reflect changes to acl-logging-rate-limit in ovn db 

.github/workflows/test.yml
The Action's matrix key ordering should match JOB_NAME so the CI job's name matches the logfile name.
=> actions: make job name match logfile names

go-controller/pkg/ovn/policy.go
Updating the ACL logging by checking the namespace was added to the
network policy handler as part of:
https://github.com/ovn-org/ovn-kubernetes/pull/2809
However, the policy was not added to the namespace before updating the
logging levels. Therefore the current policy would not be processed
during logging level updates in this path.
Reported-by: Andrew Stoycos <astoycos@redhat.com>
=> Fixes race for namespace logging level update

go-controller/hack/lint.sh, go-controller/pkg/libovsdbops/router.go
Just adds some more explicit error messages about updating/deleting SNATs, and bumps golang linter version.
=> Fix router err msgs + linter update

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_ip_handler_linux.go
While the code would close the stopChan when each test was complete,
nothing waited for the nodeIPManager and OpenFlow managers to
actually break out of their loops and return. This could lead to
spillover into the next test and cause flakes like:
```
I0217 21:55:45.508740   18937 reflector.go:225] Stopping reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
Gateway Operations DPU DPU Host Operations
sets up a shared interface gateway DPU host
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/gateway_init_linux_test.go:1097
I0217 21:55:45.508328   18937 node_ip_handler_linux.go:221] Node address annotation being set to: map[10.1.1.37:{} 172.17.0.1:{}] addrChanged: true
I0217 21:55:45.509576   18937 kube.go:99] Setting annotations …
```
=> node: wait for nodeIP and OpenFlow manager to stop before next test

go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/ovn/policy_retry.go, go-controller/pkg/ovn/policy_test.go
This fixes a case where:
1. A network policy foo/bar is deleted, but fails
2. foo/bar with delete is added to retry cache
3. foo/bar is recreated in kapi
4. foo/bar gets added in network policy handler
In the above scenario we would not clean up the old network policy, and
just add the new one. If that was successful we would miss cleaning up
the old policy.
=> Fixes delete retry on network policy recreation

go-controller/pkg/sbdb/bfd.go, go-controller/pkg/sbdb/dhcp_options.go, go-controller/pkg/sbdb/dhcpv6_options.go, go-controller/pkg/sbdb/load_balancer.go, go-controller/pkg/sbdb/logical_flow.go, go-controller/pkg/sbdb/model.go, go-controller/pkg/sbdb/port_binding.go, go-controller/pkg/sbdb/service_monitor.go
Bring sbdb model and ovn version in sync.
Possible solution for https://bugzilla.redhat.com/show_bug.cgi?id=2052398. 
Downstream, I saw errors like:
~~~
cache "msg"="during libovsdb cache populate2" "error"="unable to apply row modifications: FieldByColumn: column requested_chassis not found in orm info" "database"="OVN_Southbound"
~~~
That column is new in OVN 20.21.0. I looked at upstream latest and downstream 4.10 and our SB schema is still 20.20.0 everywhere  https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/sbdb/model.go#L52 and precisely that column is missing from our schema. I also generated a new model with modelgen and that column sure is now added:
~~~ …
=> sbdb model: Re-run libovsdb modelgen on SB OVN schema

go-controller/pkg/node/gateway_init_linux_test.go
We need to stop the node IP manager before the factory, becuase the node IP
manager uses the factory.
Fixes: eb73081 node: wait for nodeIP and OpenFlow manager to stop before next test
@tssurya
=> gateway: fix test teardown order to really prevent nodeIP manager flake

go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/gateway_init.go
A metric is the first step towards telemetry and we need
to know the count of lgw users. This will be a first step
towards that.
=> Add metric to record gateway modes

.github/workflows/docker.yml, .github/workflows/test.yml
Only retest failed E2E jobs out of the matrix. Do the same for DualStack
and Upgrade tests. Test results will be stored inside github's cache and
if a sub-job was marked as completed, it is skipped and its results from
the run before are going to be displayed instead.
Also cache master and PR builds.
=> CI: Retest only failed E2E jobs

dist/images/ovnkube.sh, go-controller/cmd/ovndbchecker/ovndbchecker.go, go-controller/pkg/ovndbmanager/ovndbmanager.go
In order to avoid any potential bringup race conditions between dbchecker container
and sbdb/nbdb we move the memory trimming check and enable to start of each db.
Note: memory trim config is not persistent and need to be applied everytime sbdb/nbdb restarts.
=> Move memory-trimming-on-compaction out of dbchecker to nbdb/sbdb init

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdbops/meter_test.go, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/api.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/mapper/info.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/condition.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go, go-controller/vendor/modules.txt
```
9598c132c2616 Fixes client error handling
fc5e884e9f41a Moves client error handling from the cache to client
87acccaf29896 client: use LastTransactionID when the only monitor is a CondSince one
5b14611220b61 test: Using wait api with integration
bb1929ac6d2ec Mapper: FieldByColumn error message shall contain table name
ebe15cf84d8c4 Fix libovsdb server close
976fa4167e523 adding Wait to client api
6791b3ba1f1ce api: support pointer to slice of Models for List
```
=> vendor: bump libovsdb to c8b4494412b1a0ba1396dd162a9a2d497c80f2b0

go-controller/pkg/util/kube.go
In some scale tests we get client-side throttling.
Though perhaps we should get @squeed to do another audit of our direct API usage.
@trozet @jcaamano @tssurya
=> kube: bump kube API QPS to 50

go-controller/pkg/metrics/ovn.go, go-controller/pkg/metrics/ovn_db.go
We are using labelled (vector) metrics to export
info and if the label values change, we still
export the old labels values which confuses users
because they have no way of determining which labelled
metric is the latest.
We must reset each vector metric prior to using it to
ensure we are only exporting the current state and not
old states which should have been scraped previously.
This is occurring in the OVN metrics exported by
ovnkube-node.
Follow on work is needed to fix OVS metrics that are
used by ovs-exporter but I do not understand those metrics.
/cc @npinaeva @girishmg
=> Metrics: Remove stale label metric entries

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go
See commits.
Summary:
* Register and run control plane pod watcher metrics when ovnkube-master is leader
* Register and run IPSec / timestamp metrics when ovnkube-master is leader
* Register metrics after becoming leader so there isn't lots of followers posting blank metrics.
This should save us some CPU and help confuse the user a little less.
=> Refactor OVN-Kube master metrics

dist/images/Dockerfile.fedora, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
When we set the nat-addresses=router option on the lsp of external switch;
```
sh-5.1# ovn-nbctl find logical-switch-port name=etor-GR_ovn-worker
_uuid               : 08101a36-07e3-4d69-a95e-2cb9f5ff1398
addresses           : ["02:42:ac:12:00:03"]
dhcpv4_options      : []
dhcpv6_options      : []
dynamic_addresses   : []
enabled             : []
external_ids        : {}
ha_chassis_group    : []
name                : etor-GR_ovn-worker
options             : {nat-addresses=router, router-port=rtoe-GR_ovn-worker}
parent_name         : []
port_security       : []
tag                 : []
tag_request         : []
type                : router
up                  : true
```
We end up …
=> Stop sending GARPs for LB VIPs on GR

go-controller/pkg/ovn/egressgw.go
The map is keyed by namespace_pod, but was accidentally adding the new
pod by pod name only. If this was a retry pod add it could result in the
an error like:
duplicate IP found in ECMP Pod route cache! IP: "192.168.222.33",
first pod: "dep-serving-33-4-serving-job-66f7948f5d-dzx52", second pod:
"serving-ns-33_dep-serving-33-4-serving-job-66f7948f5d-dzx52"
=> Fixes improper validation of gw cache on pod add

go-controller/pkg/ovn/master.go
To sync the logical router port, we used to delete and add it back in
the same trasanction with ovn-nbctl, making sure no existing dirty data
are left. However, now using libovsdb, we are using mutate to set the
gateway_chassis, and if the LRP has an old gateway chassis set already,
this mutation would add an extra gateway chassis instead of replacing
the old one. This can happen when the chassisID annotation changes,
resulting multiple gateway chassis set for the LRP, leading to
unexpected behavior, such as BFD being enabled.
=> Using "update" instead of "mutate" when updating GatewayChassis of LRP.

go-controller/pkg/kube/kube.go, go-controller/pkg/ovn/egressip.go
Successful assignment of egress IP is really useful to log. This change makes it
happen on Info level by default.
=> TRIVIAL: Enable info logging for successful assignment of egress IP

dist/images/daemonset.sh
`make fedora` complains:
```
./daemonset.sh --image=docker.io/ovnkube/ovn-daemonset-f:latest
'j2' not found, installing with 'pip'
./daemonset.sh: line 16: install_j2_renderer: command not found
make: *** [Makefile:40: fedora] Error 127
```
Reuse the `install_j2_renderer` function from `contrib/kind.sh`
Signed-off-by: Alin-Gabriel Serdean <aserdean@ovn.org>
=> daemonset.sh: Add missing install_j2_renderer function

go-controller/pkg/ovn/egressip.go
In cases where OVN database for logical router policies or NATs
used by EgressIPs have stale nexthops or wrong external_ips, the
sync function should remove them, so the proper row/column gets set.
=> EgressIp sync needs to account for stale nexthops

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/factory/factory.go, go-controller/pkg/factory/types.go, go-controller/pkg/node/controllers/upgrade/node_upgrade.go, go-controller/pkg/node/node.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/topology_version.go, go-controller/pkg/types/const.go
We would like to run the OVN-Kubernetes control-plane off-cluster. This means we can no longer use the Node object for coordinating topology version. This change:
- Moves topology-version to a ConfigMap
- Deletes the topology-version annotation from Nodes.
- Other random cleanups.
=> node, master: don't use Node objects for coordinating topology version

test/scripts/e2e-kind.sh
Test "should have ipv4 and ipv6 node podCIDRs" was removed from e2e tests in kubernetes 1.23 (https://github.com/kubernetes/kubernetes/pull/105079), so no need to skip it.
closes #1996128
=> Bug 1996128: Remove test "should have ipv4 and ipv6 node podCIDRs" from disabled tests

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_retry.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/port_cache.go, go-controller/pkg/util/kube.go
This pull request is to delete the logicial ports associated with a pod when a
pods runs to completion. The intent of this change is to reduce the size of OVN
databases by removing entries that are no longer needed.
=> Scalability: Delete logical ports for completed pods

go-controller/pkg/cni/cniserver.go, go-controller/pkg/cni/cnishim.go, go-controller/pkg/cni/types.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/util/kube.go
API token can expire and we should not rely only on the token itself.
If BearerTokenFile is provided it is periodically read and takes precedence over BearerToken.
More info on SA token expiration: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#safe-rollout-of-time-bound-token
=> Add a way to provide API token file

go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/address_set/address_set.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/topology_version.go, go-controller/pkg/util/util.go
The ovn kubernetes directly uses libovsdb.OperationWait operation
to check for a object existence before creating any entity into
nbdb. This commit changes it to use new Wait API which is more
user friendly.
=> Use libovsdb API for Wait operation

docs/design/service_traffic_policy.md, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go
This commit does two things:
1) No need to steer service traffic for LGW via breth0 into OVN.
Let's pass it into the host where user can apply custom routes
and modulate the traffic as needed.
Flow: external->br-ex->host->iptables->br-ex->GR->pod
reply will follow the same path (check docs for details)
2) Cleanup some ETP=local code since this simplifies things on
br-ex for LGW a lot!
=> Fix lgw flows for ingress-svc traffic

dist/images/Dockerfile.fedora, go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/nbdb/acl.go, go-controller/pkg/nbdb/logical_router_static_route.go, go-controller/pkg/nbdb/model.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Currently all network policy ACLs are placed on the OVN ingress pipeline. Since the first ACL of the highest priority is action is followed there is no way to ensure the correct operation of network policies when multiple apply to the same pod.
Splitting the ACLs onto both the ingress and egress pipelines allows all the egress network policies to be evaluated followed by the ingress so correct action is always assured
=> change networkpolicy ACLs to use "apply-after-lb" for egress network policy 

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
since iterators are reused and not redeclared the pointers would be the
same value by the end of the loop
=> Fix bug with pointers

.github/workflows/test.yml, README.md, contrib/kind.sh, dist/images/Makefile, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, docs/kind.md, go-controller/cmd/ovn-kube-util/app/readiness-probe.go, go-controller/pkg/config/config.go, go-controller/pkg/metrics/master.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go, test/scripts/upgrade-ovn.sh
Remove the ability/config to run nbctl in daemon mode
in Ovn-Kubernetes.  This is due to the fact that 90%
of nbctl calls have been converted to using libovsdb clients
in the ovnkube-master process rendering the daemon obsolete.
Would like this to merge after https://github.com/ovn-org/ovn-kubernetes/pull/2697
=> Remove nbctl daemon and fix upgrade tests

go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go
Changes the test to actually trigger an update event by updating the
node annotation with a new nexthop for the node. This revealed a bug in
the gateway update logic where we were using the nexthop as a predicate
for deciding on updating or adding a new route. Really route updates
should be based on IP prefix and not on destination.
=> Fixes node retry test and updating nodes next hop

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/node.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/net_linux.go, go-controller/pkg/util/net_linux_unit_test.go
Currently when we delete a clusterIP service we don't cleanup the conntrack entries on the node. This PR adds the logic to do this + we add the tcp protocol to the conntrack filtering process (not sure if we had any reasons for not including TCP?)
This PR does two things:
1) cleanup conntrack entries irrespective of protocol stack for service deletion
2) cleanup conntrack entries only for UDP during endpoint deletion. See https://github.com/kubernetes/kubernetes/issues/108523#issuecomment-1074044415 for details.
Debug logs capturing conntrack deletes (done for testing purposes):
```
I0223 20:48:13.136499  431210 gateway_shared_intf.go:575] SURYA 172.30.151.15, 30102, SCTP
I0223 20:48:13.136519  431210 …
```
=> Delete stale conntrack entries for services

.github/workflows/generate-report.yml, .github/workflows/test.yml
Don't run ovn-ci on push and thus don't report ovn-ci status on tip of normal branches.
Also adds debug to the junit report job which seems to be crossposting. See https://github.com/ovn-org/ovn-kubernetes/pull/2707#issuecomment-1097873394
=> Don't run CI on push

dist/templates/ovnkube-db-raft.yaml.j2, dist/templates/ovnkube-db.yaml.j2, dist/templates/ovnkube-master.yaml.j2, dist/templates/ovnkube-node.yaml.j2, dist/templates/ovs-node.yaml.j2
This commit changes the spec.dnsPolicy to Default for hostNetwork pods
so they use the hosts DNS. Even this is currently already the case for
pods having hostNetwork:true and spec.dnsPolicy DNSClusterFirst (which
is the default) this makes it more clear (https://github.com/kubernetes/kubernetes/blob/0424c7c74d926b4fe3193059e003e9056b429d28/pkg/kubelet/network/dns/dns.go#L303-L322)
Check that all of the ovn pods which use host network have the dnsPolicy `Default`:
`$ kubectl -n ovn-kubernetes get po -ojsonpath='{.items[?(@.spec.hostNetwork)].spec.dnsPolicy}'`
none
=> templates: switch dnsPolicy to Default for hostNetwork pods

go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressgw_test.go
The gw is deleted from the routes cache outside of the func that calls
the hybrid route policy deletion so we should remove the policy for
the pod before its last gw is deleted.
=> Fix hybrid routes policy not deleted on pod deletion

docs/design/service_traffic_policy.md, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_localnet.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/port_claim_test.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/util/iptables.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/util.go, test/scripts/e2e-kind.sh
Implements InternalTrafficPolicy=Local
Documentation has been added, please check it out for design details.
Tests: Upstream k8s e2e's are pretty good and testing this feature well. Added unit tests to capture our LB filter logic on the switches and iptable rules on the nodes.
```
[surya@hidden-temple yaml_debugging]$ oc get pods -owide
NAME                             READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
hello-world-1-7fd8cdc9df-57p8n   1/1     Running   0          3m52s   10.244.0.4   ovn-worker2   <none>           <none>
hello-world-1-7fd8cdc9df-brg68   1/1     Running   0          3m52s   10.244.1.4   ovn-worker    <none> …
```
=> Implement InternalTrafficPolicy=Local

dist/images/Dockerfile.fedora, go-controller/Makefile, go-controller/hack/update-codegen.sh, go-controller/pkg/libovsdbops/copp.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/nbdb/copp.go, go-controller/pkg/nbdb/model.go, go-controller/pkg/ovn/gateway_copp.go, go-controller/pkg/ovn/gateway_copp_test.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/sbdb/bfd.go, go-controller/pkg/sbdb/dhcp_options.go, go-controller/pkg/sbdb/dhcpv6_options.go, go-controller/pkg/sbdb/load_balancer.go, go-controller/pkg/sbdb/logical_flow.go, go-controller/pkg/sbdb/model.go, go-controller/pkg/sbdb/service_monitor.go
22.03 has some schema changes so we need to bump CI as well.
22.03 added (at our request) a Copp.Name field and indexing on name, which wasn't in 21.12, so we do need to update any COPP item we've already added with a name to make the indexes happy.
=> Bump OVN version to 22.03 in schema and CI

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/pods_test.go
Otherwise, we get "Expected a ModelPredicate with BulkOp==true"
/cc @jcaamano
=> Set bulk ops to false when not using predicate for deleting LSPs

go-controller/cmd/ovn-kube-util/app/ovs-exporter.go, go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/metrics/ovs.go
Instead of through the extra OVS metrics exporter utility. We're already doing node and OVN metrics in ovnkube, might as well do OVS there too.
NOTE: this is based on https://github.com/ovn-org/ovn-kubernetes/pull/2923
=> metrics: add option to expose OVS metrics on the node

go-controller/pkg/metrics/ovn_db.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/ovndbmanager/ovndbmanager_test.go, go-controller/pkg/util/ovs.go
1. Fix cluster/status parsing for single-member db cluster 
2. Use common DbProperties struct for dbmanager and ovn_db metrics.
3. Change command to check if db is clustered to the one that works
even if db file is not mounted.
4. Fix getting ovn{n/s}b_db schema-version for /var/run/ovn mount path
To see the changes, compare the following metrics
ovn_db_cluster_ metrics are not exposed
```
oc -n openshift-ovn-kubernetes exec $POD -c ovnkube-node curl "127.0.0.1:29105/metrics" | grep "# HELP ovn_db_cluster" | wc -l
0
```  
All 15 metrics https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/metrics/ovn_db.go#L386-L400 are exposed 
```
oc -n openshift-ovn-kubernetes exec $POD -c ovnkube-node curl "127.0.0.1:29105/metrics" | grep "# HELP ovn_db_cluster" | wc -l
15
``` …
=> ovn_db_cluster metrics improvements

go-controller/pkg/factory/handler.go
The informer lock is held to add and remove handlers, as well as execute
handlers in the non-federated queue case. However, in federated queue
the handlers were being copied while locked, and then executed. This
allows handlers to execute even after the handler has been removed from
the informer.
=> Fixes handler locking

go-controller/Makefile, go-controller/hack/test-go.sh, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/management-port_linux_test.go, go-controller/pkg/node/management-port_test.go, go-controller/pkg/testing/testing.go
Skips tests that require sudo or special capabilities to execute. To
run, use "make check NOROOT=TRUE"
=> Allow make check without root

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/pkg/ovn/master.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go
In a cluster with hybrid overlay, after the ingress traffic is DNATed
by the ovnkube node's gateway router LB rule, the dst ip of some packets
will be changed to the ip of non-onvkube managed pods. We need to
steer this traffic to the hybrid overlay vxlan tunnel through the
node switch.
With this patch, the packects will be first forwarded from the GR to
cluster router. Then based on the routing policy, the packets will be
forwarded to the hybrid overlay bridge. At the hybrid overlay bridge
stateless SNAT rules will change the src ip to the node's Distributed
Router's.
=> Fix nodePort service backed by pods on hybrid overlay nodes

test/e2e/e2e.go, test/e2e/util.go
Refactor the DualStack service IPFamily upgrade test for node ports.
Tolerate initial failure of the IPv4 endpoints (workaround iss #2868)
=> NodePort services DualStack tests refactor and failure toleration

go-controller/pkg/ovn/master.go
Since we combined add and update node functions
into addUpdateNodeEvent, we end up calling oc.addRetryPods(pods.Items)
and trigger oc.requestRetryPods() for every node update which happens
every 5 mins. This means we are retrying all the existing pods on
a given node every 5mins. Let's call addRetryPods only if syncNode=true
which signifies its a nodeAdd and not nodeUpdate.
Closes: #2942
=> Don't addRetryPods during node updates

go-controller/pkg/ovn/policy.go
This PR fixes ACLs that allow POD ip multicast traffic to pass towards the ovn_cluster_router. IP multicast traffic between pods that are on different nodes was otherwise dropped.
The following e2e test is now passing:
```
Multicast 
should be able to send multicast UDP traffic between nodes
```
There was a typo for multicast ingress allow policies causing their ACLs
to be turned into "from-lport" ACLs that would never be matched.
=> policy: Fix multicast allow policy type.

test/e2e/acl_logging.go, test/e2e/external_gateways.go, test/e2e/multicast.go, test/e2e/service.go, test/e2e/unidling.go, test/e2e/util.go
Now when a test case fails, the DBs will be copied before cleanup to the
/var/logs/e2e-dbs/<test case>_<test namespace>/
This makes it easier to debug OVN failures.
Example output on ovn-control-plane node:
```
root@ovn-control-plane:/var/log/e2e-dbs# ls
should_be_able_to_send_multicast_UDP_traffic_between_nodes-multicast-1847  should_be_able_to_send_multicast_UDP_traffic_between_nodes-multicast-4425
should_be_able_to_send_multicast_UDP_traffic_between_nodes-multicast-2540  should_be_able_to_send_multicast_UDP_traffic_between_nodes-multicast-7887
root@ovn-control-plane:/var/log/e2e-dbs# ls should_be_able_to_send_multicast_UDP_traffic_between_nodes-multicast-1847
ovn-control-plane-conf.db  ovnnb_db.db  ovnsb_db.db
```
=> Dump OVN databases on e2e-control-plane failure

dist/images/ovnkube.sh, go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/metrics/metrics.go
the assumption here is that the key/cert files are pre-generated and
mounted into the ovnkube container (running either as a master or node)
and paths for these files are exposed using OVNKUBE_METRICS_PK and
OVNKUBE_METRICS_CERT environment variables
@zshi-redhat @trozet @dcbw  PTAL
=> add TLS support to metrics endpoint in ovnkube

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/libovsdbops/chassis.go, go-controller/pkg/libovsdbops/chassis_test.go, go-controller/pkg/libovsdbops/model.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/monitor.go, go-controller/vendor/github.com/ovn-org/libovsdb/mapper/mapper.go, go-controller/vendor/modules.txt
When SBDB chassis rows are deleted, remove the associated chassis
private row as well.
Remove stale chassis private rows on initial node synchronization.
=> Bug 2074009: Delete ChassisPrivate along with Chassis

dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-node.yaml.j2, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go
This is avoid data plane down time during ovn-controller upgrade.
See https://github.com/ovn-org/ovn/commit/896adfd2d8b3369110e9618bd190d190105372a9
=> Support option ovn-ofctrl-wait-before-clear of ovn-controller.

go-controller/pkg/ovn/master.go
a correctly configured noHostSubnet node will never become avalible on
GCP because the unavailable condition will never be cleared.
=> call clearInitialNodeNetworkUnavailableCondition for noHostSubnet nodes

go-controller/pkg/libovsdbops/router.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/ipallocator/allocator.go, go-controller/pkg/ovn/ipallocator/allocator/bitmap.go, go-controller/pkg/ovn/ipallocator/allocator/bitmap_test.go, go-controller/pkg/ovn/ipallocator/allocator/interfaces.go, go-controller/pkg/ovn/ipallocator/allocator_test.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
- During pod sync we allocate IPs of all existing pods, but we should
ignore completed pods
- During namespace add we add all of the pod IPs to the ns address set,
but we should ignore completed pods
- During processing of delete event for a completed pod, we were trying
to delete the pod again, which would try to free the IP that was
previously released and could be in use by another pod. We should
ignore delete events for completed resources as they would have been
handled during update.
- On node add, we add all existing pods on that node back to retry as
an "add". We should skip completed pods here.
=> Fixes various issues with completed pods

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods.go
This commit addresses two issues:
When addNode() failed in addNodeAnnotations(), the node's IPAM can be
overwritten by subsequent addNode() retry attempts. As the result, the
same IP can be allocated to multiple pods.
retryPod worker is started too soon, which could start to handle add Pod
request and allocate duplicate Pod IPs before IPs of the existing Pods are
reserved in syncPods().
=> duplicated IPs can be assigned to multiple Pods

go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressqos.go, go-controller/pkg/ovn/egressqos_test.go, test/e2e/egressqos.go, test/e2e/go.mod, test/e2e/go.sum, test/scripts/e2e-cp.sh
When using the namespace's address_set for the
EgressQoS rule we should return an empty map rather
than nil, otherwise when we try to load from it
in the pod sync path we get a nil pointer dereference.
Using an empty map is fine since we don't want to
change anything in the namespace's address_set here.
---
Adding E2E tests that cover EgressQoS functionality for both
IPv4 and IPv6:
* First table verifies that a pod's egress traffic is marked with
the correct DSCP value on EgressQoS resource updates regardless
if it was created before or after the resource.
* Second table verifies that updating a pod's labels results
in the right QoS rules being applied to its egress traffic.
=> Add Egress QoS E2E and fix panic

go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go
If the pod isn't yet scheduled, we should just ignore the event and try again later.
=> Don't warn on failure to create pod when it isn't scheduled

go-controller/pkg/kube/kube.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, test/e2e/e2e.go
We should be deleting the snat towards nodeIP before
adding snat towards egressIP only from the node
where the pod lives if that same node is serving
as the egressIPnode for the pod.
=> delete SNAT2NIP if pod.node == egressNodeServingPod

dist/templates/ovnkube-db-raft.yaml.j2, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go
Both are planned to be removed in 1.25
=> Bump PodDisruptionBudget and EndpointSlice to v1 

go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/helper_linux_test.go, go-controller/pkg/cni/mocks/CNIPluginLibOps.go, go-controller/pkg/cni/ovs.go
During Single-node cluster testing cpu usage spikes were noticed, e.g. when deploying a large daemonset.
ovnkube-master container doesn't affect master pod cpu usage too much (example from the cluster with 3 master nodes, sorted by total cpu usage for master pods containers). Therefore optimizing master code won't make a big difference here.
```
container_cpu_usage_seconds_total    northd                 127.704829389    
container_cpu_usage_seconds_total    sbdb                    70.024377485
container_cpu_usage_seconds_total    nbdb                    42.733104665
container_cpu_usage_seconds_total    sbdb                     35.589553931
container_cpu_usage_seconds_total    nbdb                     34.340587309 …
```
=> cni pod deployment performance imrovements

contrib/kind.sh, dist/images/daemonset.sh, dist/images/ovnkube.sh, dist/templates/ovnkube-master.yaml.j2, docs/metrics.md, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/metrics/master.go, go-controller/pkg/metrics/master_test.go, go-controller/pkg/metrics/metrics_suite_test.go, go-controller/pkg/metrics/mocks/histogram.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/policy.go
Provides a mechanism to record config duration within OVN-K
for kubernete kinds from when event handler fires for a given
resource until processing is complete.
Exposes the duration as a histogram.
Optionally, provides a way to record OVN duration.
Currently added for the following k8 kinds:
* pod
* networkpolicy
* service
=> Metrics: add config duration recorder

go-controller/pkg/node/gateway_shared_intf.go
There was a null pointer dereference crash seen on comparing
InternalTrafficPolicy type on a service spec. This commit
fixes the null pointer.
=> Fix a crash on service update check

.github/workflows/test.yml, go-controller/.golangci.yml, go-controller/hack/lint.sh
Update golangci-lint to v1.46.0 and enable nosprintfhostport linter to prevent URL constructions that are incompatible with IPv6.
None
Run `make lint`, notice nosprintfhostport linter passes.
Update golangci-lint to v1.46.0 and enable nosprintfhostport linter to prevent URL constructions that are incompatible with IPv6.
=> Add nosprintfhostport linter config

go-controller/.golangci.yml, go-controller/cmd/ovnkube-trace/ovnkube-trace.go, go-controller/pkg/ovn/pods.go
`exportloopref` golangci linter finds pointers exported from within
for-range loop, see https://github.com/kyoh86/exportloopref for details.
The linter does expose 2 violations, the one in `pkg/ovn/pods.go` is a
real bug.
Signed-off-by: xqu <xqu@nvidia.com>
=> enable `exportloopref` linter and fix violations

go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/model_client_test.go
Transactions is an all or nothing thing so we just need one wait per transaction to check against duplicate transactions that might happen on transaction retries or other OVN glitches. This prevents massive delays on transactions that bundled several LB inserts, and thus several Wait ops, from the service controller.
However, for genuine reasons to prevent duplicate rows, like inserting the same row from multiple threads, this requires to have them by themselves on their own transaction.
=> libovsdbops: only one wait per txn

go-controller/pkg/libovsdbops/loadbalancer.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go
Running the LB predicate that matches on name takes a long time if the
LB table has many LBs. For example, looking up ~40 LBs in a table with
~200k rows took aproximately 3s.
The service controller has a second level cache and knows which LBs need
to be added and which need to be updated. Avoid this lookup for LBs that
are to be added.
=> Don't lookup LBs that don't exist in cache

test/scripts/install-kind.sh
KIND 0.13.0 or later is required for k8s 1.24.0 bump, as explained in https://github.com/kubernetes-sigs/kind/releases. Taking latest stable KIND release: 0.14.0
=> Bump KIND version to 0.14.0 to prepare for k8s 1.24.0 bump

go-controller/pkg/metrics/ovs.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
Using ovs-dpctl can cause severe issues when there is a version mismatch between ovs-dpctl and ovs-vswitchd.
To address that use ovs-appctl dpctl/* since it provides the same data that is in the same format.
/cc @flavio-fernandes @dcbw 
=> Use ovs-appctl dpctl/* instead of ovs-dpctl

contrib/.gitignore
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
Fix the name for the file in gitignore. Avoid showing it in `git status`
run `contrib/kind.sh` and execute git status, no generated file should show up. 
- contrib: fix gitignore for including the kind-CLUSTERNAME
=> contrib: fix generated yaml file in gitignore

go-controller/pkg/cni/helper_linux.go
Helps debug ovn-installed issues between ovnkube and
ovn-controller, to ensure they both agree on what
iface-id-ver should be.
=> cni: print a bit more pod info in ConfigureOVS()

go-controller/pkg/metrics/ovs.go
This metric produces a time series for each interface and this
becomes problematic when the number of nodes in a cluster scales.
For example, with a 50 node cluster and 200 pods per node, we are
looking at 10000 time series.
In order to protect the prometheus database, I want to remove this.
/cc @girishmg Are you ok with removing this? 
@npinaeva @pperiyasamy
=> Remove metric ovs_vswitchd_dp_if due to high number of time series

go-controller/hybrid-overlay/pkg/controller/master.go, go-controller/hybrid-overlay/pkg/controller/master_test.go, go-controller/hybrid-overlay/pkg/controller/node_linux.go
With this patch, when '--hybrid-overlay-cluster-subnets' is absent, and
the hybrider overlay node annotation exists on non-ovnkube nodes,
ovnkube-master will try to derive the hybrid-overlay-node-subnet for each
non-ovnkube node and setup the static routes and route policies for the
traffic to the hybrid overlay nodes accordingly.
We need this ability for the SDN live migration case, where we use hybrid
overlay to connect the node managed by ovnkube and openshift-sdn. To
reuse the node subnet, we need to skip the ip allocation for hybrid
overlady nodes by setting the node annotation by other tools (e.g
cluster-network-operator). As we don't cannot use the same value for
both '--hybrid-overlay-cluster-subnets' and '--cluster-subnets', I think
we …
=> Auto detect hybrid overlay node subnets

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go
The retry logic should not attempt to add or delete an object indefinitely. Adding an upper bound to the maximum number of times we can attempt to add or delete a given object, as we do already in level-driven controllers.
fixes #2082599
=> Bug 2082599: add upper bound to number of retries

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/gateway_cleanup.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/util/net.go
There are a few instances in egressIP code where we shouldn't
fail hard if objects are not found, example if a node gets
deleted before egressIP watcher takes action. In this case,
we can log a warning saying objects couldn't be deleted and
move on since its technically not an error if the object was
deleted by some other path.
=> Fix egressIP object deletion if the node is deleted first

go-controller/pkg/ovn/policy.go
All the namespace policies ACLs were being updated when adding a single
policy to make sure that the ACL logging levels were current on the
policies in case it changed while the policy was being created. This is
unnecessary and has performance issues.
When creating a policy, only update the ACL logging of that policy, and
only if it changed from the value we created it with. The other
namespace policies will be handled through the namespace update handler.
=> Update logging for specific policy when creating it

go-controller/go.mod, go-controller/go.sum, go-controller/pkg/cni/helper_linux.go, go-controller/pkg/cni/types.go, go-controller/pkg/cni/utils.go, go-controller/pkg/cni/utils_test.go, go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/node/gateway.go, go-controller/vendor/github.com/safchain/ethtool/.travis.yml, go-controller/vendor/github.com/safchain/ethtool/ethtool.go, go-controller/vendor/github.com/safchain/ethtool/ethtool_cmd.go, go-controller/vendor/github.com/safchain/ethtool/ethtool_msglvl.go, go-controller/vendor/modules.txt
With recent kernels it is possible to improve the performance of pods that transmit lots of small UDP packets by allowing multiple packets to traverse the kernel network stack as a single large aggregate packet. For various reasons, this functionality is not enabled by default (in particular, aggregating multiple packets implies _not sending the first packet right away_, so enabling this functionality would be bad on systems that care more about having very low latency than about having good bandwidth.)
More details [in this blog post](https://developers.redhat.com/articles/2021/11/05/improve-udp-performance-rhel-85). The graphs there are for bare metal, and the performance improvements are not as impressive in virtualized/cloud environments (more like 1.3x rather than 2x), but it's still …
=> Add support for enabling UDP packet aggregation on veth interfaces

go-controller/pkg/ovn/master_test.go
This PR introduces a new unit test to check adding a node without a defined host
subnet is possible only when the node is properly annotated.
In order to reduce the number of copied code, a series of refactors were made in the
`master_test.go` file, moving some code into dedicated helper functions.
closes: #2938
Run unit tests. The new added test - `use node retry for a node without a host subnet` - should pass.
Added a unit test to assert adding a properly annotated node without a host subnet is possible.
=> Add no host subnets unit test

go-controller/pkg/config/cni.go, go-controller/pkg/node/node.go
Start the CNI server before we indicate we're ready to process requests by writing the CNI config file out.
Also log when the node is initialized and ready which helps debugging.
=> node: start CNIServer before writing out CNI config and log when initialized

go-controller/pkg/ovn/obj_retry.go
=> Remove redundant log lines in obj_retry.go

go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods_test.go
When an object (like a pod) is updated to indicate it is now terminal, we were passing the old version of the object to the delete handler. Within the pod delete path, we check again to see if this pod is terminal, so that we can do some extra logic. However, since we were passing the old object, this check was bypassed. We used to pass the newer version of the object before the refactor to generic watcher/retry handlers.
Also, the completed pod test cases were not functioning correctly and have been fixed.
=> Fixes handing terminal pods during update event + test case fixes

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
EgressIP node reachability check when it fails it marks the node offline and never retries again.
new configuration knob `egressip-reachability-total-timeout` to allow users to change the default egressip retry total timeout in seconds the default is 1 second.
if users set this config knob to 0 egressip reachability check will be skipped.
=> EgressIP add retry for EgressIP node's mgmtIP reachability check

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Fix panic in NP deletion
NOTE to reviewers: First commit adds a unit test that shows the panic, the second commit adds the fix and updates the test case to pass.
Fixes panic observed during NP deletion:
```
2022-05-27T15:48:27.957882179Z I0527 15:48:27.957839       1
policy.go:1251] Deleting network policy XXXXX in namespace XXXXX
2022-05-27T15:48:27.957950868Z E0527 15:48:27.957928       1
runtime.go:78] Observed a panic: "invalid memory address or nil pointer
dereference" (runtime error: invalid memory address or nil pointer
dereference)
2022-05-27T15:48:27.957950868Z goroutine 132 [running]:
2022-05-27T15:48:27.957950868Z
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1930dc0, 0x2907f50)
2022-05-27T15:48:27.957950868Z
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s …
```
=> Fix Panic in network policy deletion

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/policy.go
during the scale testing we observed that the ovnkube-master
was not annotating the pods fast enough as a result the ovn-k8s-cni
on the scheduled node was timing out while waiting on the pod's
annotation. the pods were getting annotated by ovnkube-master after
several minutes.
this is because the iterateRetryResources() function was walking through
the list of pods that failed setup and was retrying setup on them with
lock held. there were 100s of these pods and each one of the took
several seconds.
The fix here is to retrieve the list of all the pods that needs to be
retried with retryPods map lock held and then call ensurePod() on
each of those pods with the new mutex in retryEntry struct held. This
will ensure that the add/update for Pod doesn't race with delete for
Pod.
Furthermore, …
=> Avoid holding map mutex accross iterateRetryResources()

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/policy.go
before deleting port group
To verify run kind cluster with multicast enabled, then enable and disable multicast for a namespace, check port group and ACLs are deleted from nbdb
=> Fix deleteMulticastAllowPolicy: don't cleanup ACLs for port group

go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/healthcheck_test.go
checkForStaleOVSRepresentorInterfaces was found to run
in non-SRIOV deployment which causes memory spike every
minute with extra 512kB memory allocated in the heap.
This could be a problem when running ovnk in a small
form factor deployment.
The following is observed via pprof:
512.14kB 14.17% 57.50%   512.14kB 14.17%  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.checkForStaleOVSRepresentorInterfaces
this commit filters "ovs-vsctl find" output with "vf-netdev-name"
external-ids so it takes much less memory in non-SRIOV case.
=> Improve memory efficiency when checking stale VF representor

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
Fix egressips for pods recreated with same name
EIP handler uses logicalPortCache for getting pod's
portInfo. Since cache removes entries only 60 seconds
after deletion, its possible that when pod is recreated
with the same name within the 60seconds timer, stale
info gets used to create SNATs and reroutes for the eip pods
Special thanks to @kyrtapz who was my debugging buddy here :) #Peer-Debugging
=> EIP: Fix stateful set pods recreated with same name

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, test/e2e/acl_logging.go
Update and cleanup older stale ACLs upon startup
This PR does two things:
1) Loops through all the ACLs that have `ARPallowPolicy`
in their names and have " && arp" in their match expression
and deletes it. This is because we did
https://github.com/openshift/ovn-kubernetes/pull/1043/files where
we changed the match but didn't remove acls on the older match which
causes problems like:
2022-06-01T08:17:44.635401164Z E0601 08:17:44.634509       1 ovn.go:753]
Failed to create network policy mdh-old/allow-from-other-namespaces,
error: failed to create default port groups and acls for policy:
mdh-old/allow-from-other-namespaces, error: unexpectedly found multiple
equivalent ACLs: [{UUID:3bc36c0e-ee1a-4609-a240-c211f14f379b
Action:allow Direction:to-lport …
=> Cleanup stale acls as part of syncNetworkPolicies on startup

go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller_test.go
services controller: reconcile on node deletion
A node load balancer is a load balancer associated to any of the following
services:
- service with NodePort set
- service with host-network endpoints
- service with ExternalTrafficPolicy=Local
- service with InternalTrafficPolicy=Local
This commit forces the reconciliation of the load balancers upon node
deletion. Since the node was deleted, the newly generated list of load
balancers will *not* feature the deleted node's load balancers, which will
lead to their deletion.
Leaking these load balancers causes an issue when the deleted node is re-added
(as part of a remediation procedure, for instance) since the newly created node
logical switch does not point to these node load balancers, thus …
=> Reconcile node lbs on node deletion

go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/obj_retry.go
Fix flaky test: using EgressNode retry should re-assign EgressIPs andperform proper OVN transactions when pod is created after node egress label switch
In `OVN master EgressIP Operations/using EgressNode retry should re-assign EgressIPs and perform proper OVN transactions when pod is created after node egress label switch` test we are using a sleep to wait for TransactWithRetry timeout.
There is a chance that both egressnode events(node1 removal and node2 update) will end up in the same event queue which means we need to wait double the time.
Addresses: https://github.com/ovn-org/ovn-kubernetes/issues/2988
=> Fix flaky egress IP test

go-controller/cmd/ovnkube-trace/ovnkube-trace.go, test/scripts/test-ovnkube-trace.sh
* ovnkube-trace no longer depends on bash inside the application pod and
instead gets all information that it needs from ovs/ovn commands inside
the ovnkube-node pods.
* Add color coding to ovnkube-trace output for better readability.
* Refactor large parts of main() and remove code duplication.
* Allow tracing to an external IP address.
* Fix issues with host networked pods and shared gateway mode.
* Add script that allows testing of ovnkube-trace.
This fixes: 
* https://bugzilla.redhat.com/show_bug.cgi?id=2066891
*  | SDN-2336 | [Debugging] ovnkube-trace improvements: Implement pod2external traffic in ovnkube-trace
Use the provided script:
~~~
[root@ovnkubernetes ovn-kubernetes]# test/scripts/test-ovnkube-trace.sh --help
usage: test-ovnkube-trace.sh [--kubectl …
=> ovnkube-trace improvements and refactor

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/node_test.go, go-controller/pkg/node/ovn_test.go
In the DPU 2-clusters design, a host with DPU will join the cluster
with ovn-controller running in the host first, then it will be  moved
to the DPU. Therefore, we will have 2 chassis with the same hostname
in the ovn sbdb.
This patch removes the stale chassis from the ovn sbdb if ovnkube-node
is running at the dpu-host mode.
Create a cluster with hosts having BF-2 DPU installed. Check the sbdb of OVN.
=> Remove stale chassis for hosts that run ovnkube-node on DPU

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/ovn.go
eventRecorder creates both incoming and outgoing queues
with same length (1000), this commit saves ovnk memory
by approriately 2000*Event bytes.
=> Share eventRecorder when both master & node specified

go-controller/pkg/ovn/address_set/fake_address_set.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy_test.go
Includes multiple fixes for pod retries:
1. When disable-snat-multiple-gateways is true, we need to get l3 gateway info of a node when we addLogicalPort (to add the SNAT entry). However, we were requesting the pod to be retried during node add, before the l3gateway config had been validated. This would end up requesting a pod to be retried from the node handler, which would end up failing anyway due to lack of l3gateway config.
2. Fixes for various error logs that were wrong.
3. When the node was requesting immediate retry of pods for a node, it was actually signalling to retry all pods on the entire cluster that were in the retry cache. This is now fixed so that only the requested pods are immediately retried, while the backoff is respected for all other pods during the next retry …
=> Fix pod retries

go-controller/pkg/node/management-port_linux.go, go-controller/pkg/util/iptables.go
On startup we are flushing all the rules in ovnk
chains. The MGTM chain particularly gets flushed twice, once from
from `createPlatformManagementPort` which calls
`tearDownManagementPortConfig` before `setupManagementPortConfig`
that readds these rules back. Then again it gets flushed from `SyncServices`
which then gets re-added by the healthcheck gorutine.
This PR doesn't fix the flushing bug, but fixes the ovn-k8s-mp0 SNAT
rule to be always added last in the chain (append)
on startup. The other rules in the chain are inserted
or prepend-ed so we should be good.
/assign @trozet
=> Append the SNAT rule in management chain

go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/util/ovs.go, go-controller/pkg/util/ovs_unit_test.go
Currently the default value for all interfaces is 0 while
rp_filter for "all" is set to 1.
rp_filter - INTEGER
0 - No source validation.
1 - Strict mode as defined in RFC3704 Strict Reverse Path
Each incoming packet is tested against the FIB and if the interface
is not the best reverse path the packet check will fail.
By default failed packets are discarded.
2 - Loose mode as defined in RFC3704 Loose Reverse Path
Each incoming packet's source address is also tested against the FIB
and if the source address is not reachable via any interface
the packet check will fail.
Current recommended practice in RFC3704 is to enable strict mode
to prevent IP spoofing from DDos attacks. If using asymmetric routing
or other complicated routing, then loose mode is recommended.
The max value from …
=> Change rp_filter value for ovn-k8s-mp0

go-controller/hack/build-go.sh
remove runtime dependencies for c libraries
=> Build all ovnk binaries with cgo disabled

go-controller/pkg/ovn/obj_retry.go
We weren't locking individual entries while looping through
them, this was causing races when same entry was changed or
accessed elsewhere in the code.
Closes: #3080
=> iterateRetryResources: Lock the entry in the loop

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go
If EgressIP node create failed while creating default
NoRoute policy then an update event happens before
objRetry period "30sec" there is no logic to retry
recreating this policy.
=> EgressIP node handle create errs followed by update in < 30s

go-controller/pkg/ovn/egressip.go
Even when running on a public cloud, we must make sure that we
unwire EgressIP configuration from OVN *before* we instruct the
CloudNetworkConfigController to remove the CloudPrivateIPConfig
object from the cloud to avoid dropping packets.
Reported-at: https://bugzilla.redhat.com/show_bug.cgi?id=2101992
=> Unwire OVNKubernetes before scheduling CloudPrivateIPConfig deletion

test/e2e/external_gateways.go
The former works regardless of what datapath OVS uses.  The latter only
works with the kernel datapath.
=> e2e: Prefer "ovs-appctl dpctl/dump-conntrack" over ovs-dpctl.

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/policy.go
To make sure we don't forget about that, add port group and switch refs
to DeleteACLs as args. UUIDs don't need to be cleaned up only if
port group or switch is completely deleted.
Update all DeleteACLs calls to cleanup refs.
=> Cleanup ACL UUID references from switch or port group when deleting ACL

go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go
Instead of always listing all pods on a node even when we don't use
the result, just list them if we are going to iterate the pods to
ensure they are set up.
This fixes a performance regression where ovnkube-master puts more
pressure on the apiserver/etcd when node update events occur.
@tssurya @trozet @jtaleric
=> master: don't list node pods on add/update unless necessary

go-controller/pkg/ovn/obj_retry.go
Randomly found this during debugging unit test failures
Introduced here https://github.com/ovn-org/ovn-kubernetes/pull/3081
=> Fix possible retryEntry deadlock in iterateRetryResources

go-controller/hybrid-overlay/pkg/controller/node_windows.go, go-controller/hybrid-overlay/pkg/controller/overlay_windows.go
Before, AWS EC2 initial instance boot used [EC2Launch](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html#ec2launch-tasks) to set `persistent` static routes to reach the [metadata service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html). With [EC2Launch v2](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch-v2.html) the routes to reach the metadata service are set as `non-persistent` static routes, making the [DuplicatePersistentIPRoutes](https://github.com/ovn-org/ovn-kubernetes/blob/fadfcd6112b4207c8fafacf8e719f2806d9bb421/go-controller/hybrid-overlay/pkg/controller/overlay_windows.go#L269) function an instruction that specifies no operation since there are no persistent routes …
=> [hybrid-overlay] Forward routes for link-local addresses to vNIC in Windows

go-controller/pkg/ovn/egressip.go
Up until now, the Cloud Private IP Conf add operation unconditionally
overwrote the current entry in pendingCloudPrivateIPConfigsOps for
the egressIPName. This lead to race conditions when updating an
EgressIP's IP address to a different one. During such a simultaneous
CloudPrivateIP add and remove operation, the add could overwrite the
map entry before the remove had the time to remove its own op.
The delete operation would be rescheduled and log an error until the
reschedule was killed off.
To address this:
* Merge the add op into the existing map, using the
same logic as for remove operations.
Unrelated but found during testing:
* Do not throw an error when the cache contains a delete operation
for an IsNotFound API object. Instead, log an Info and go on with
the business logic. The …
=> Bug 2105706: EgressIP: Merge ops into pendingCloudPrivateIPConfigsOps on add

.github/workflows/docker.yml, .github/workflows/test.yml, .github/workflows/test_periodic.yml, README_MANUAL.md, go-controller/Makefile, go-controller/go.mod, go-controller/go.sum, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/obj_retry_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/syncmap/syncmap.go
Implmenet syncCache for retryObjects with lockable keys.
Isolate cache implementation from the retry logic:
- retryObjEntry doesn't need to have mutex anymore
- retryObjs doesn't work with cache mutexes, only calls methods
SyncCache is a map with lockable keys. It allows to lock the key
regardless of whether the entry for given key exists.
When key is locked other threads can't read/write the entry with
the key.
Split ensureRetryEntryLocked into loadOrStore that will
make sure newEntry is present and locked, and load that was
previously called as ensureRetryEntryLocked with nil newRetryEntry.
Change iterateRetryResources to only lock every entry once and not use
cache mutex. Create a snapshot of keys that will be retried instead
of holding map lock.
Lock retyrObject key until work for …
=> Fix retry_obj retryMutex vs retryEntry.Mutex deadlocks

go-controller/pkg/kube/kube.go, go-controller/pkg/metrics/metrics.go, go-controller/pkg/ovn/master.go
Antonio says that if you don't pass ResourceVersion:"0" the call goes directly
through to etcd, while if you pass "0" it gets pulled from the apiserver's
cache. Pulling from the cache can greatly reduce load on etcd.
@aojea 
See: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L637
```
// GetList implements storage.Interface
func (c *Cacher) GetList(ctx context.Context, key string, opts storage.ListOptions, listObj runtime.Object) error {
recursive := opts.Recursive
resourceVersion := opts.ResourceVersion
pred := opts.Predicate
if shouldDelegateList(opts) {
return c.storage.GetList(ctx, key, opts, listObj)
}
<...>
}
func shouldDelegateList(opts storage.ListOptions) bool {
resourceVersion := opts.ResourceVersion
pred := …
```
=> kube: pass ResourceVersion:"0" for direct List() calls

dist/templates/k8s.ovn.org_egressqoses.yaml.j2, go-controller/pkg/crd/egressqos/v1/types.go, test/e2e/egressqos.go
This denies resources that specify an invalid cidr.
thanks @andreaskaris :)
=> Add EgressQoS DstCIDR kubebuilder validation

.github/workflows/test.yml
Add golang installation step to lint job, since `golangci-lint` might install a later version by design: https://github.com/golangci/golangci-lint-action/issues/75
=> Fix go version in lint job

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
BZ2117310: Fix race when adding and removing pod with same name
Adding and removing a pod on changing nodes back to back can end up in a race where
corresponding logical switch port remains in the wrong logical switch and never gets
properly removed. In order for this to happen, the logical switch port has to have
the same name, which is the `<namespace>_<podName>`.
**NOTE:** This PR is built upon https://github.com/ovn-org/ovn-kubernetes/pull/3071 . Both of them should be
backported to handle the race described here.
=> BZ2117310: Fix race when adding and removing pod with same name

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go, go-controller/vendor/github.com/ovn-org/libovsdb/server/mutate.go, go-controller/vendor/modules.txt
=> Bump libovsdb to include https://github.com/ovn-org/libovsdb/pull/321

docs/metrics.md, go-controller/pkg/metrics/metrics.go
Currently, they are reported in milliseconds.
Prometheus mandates time values are reported in seconds.
/cc @creydr && @npinaeva
=> OVN-K Metrics: Ensure stopwatch metrics are reported in seconds

docs/metrics.md, go-controller/pkg/metrics/ovn.go
Report OVN controller connection status via a metric from each
OVN kube node.
The metric is updated every 2 minutes in-order not to incur
polling overhead which is not insignificant.
Prometheus scrape interval is usually every 30 seconds, and is
this value on OCP.
The reason we report this from every node instead of grabbing it
from SB DB via (nb_cfg trigger), is to save SB DB from each
OVN controller having to write to it.
This maybe an issue when scaling node.
/cc @npinaeva
=> OVN-K metrics: Add OVN controller southbound database connection

go-controller/pkg/config/config.go, go-controller/pkg/config/config_test.go, go-controller/pkg/metrics/master.go, go-controller/pkg/ovn/egressip.go
Add metrics to observe core events related to EgressIP:
- name: egress_ips_assign_latency_seconds -- Histogram **
desc: The latency of egress IP assignment to ovn nb database
- name: egress_ips_unassign_latency_seconds -- Histogram **
desc: The latency of egress IP unassignment from ovn nb database
- name: egress_ips_node_unreachable_total -- Counter
desc: The total number of times assigned egress IP(s) were unreachable
- name: egress_ips_rebalance_total -- Counter
desc: The total number of times assigned egress IP(s) needed to be moved to a different node
Add flags to explicitly enable the histogram metrics, since we only see value
in having them when scale testing egress ips. The flag introduced here is:
`--metrics-enable-eip-scale`
=> egressip: add metrics

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
When the logical port is already deleted, deleteLogicalPort should
not return an error. Otherwise, delete will be retried up for
maxFailedAttempts (currently set to 15).
This issue introduced in commit be8786a89546effe2de121fce9c05907fae4c1ce
https://github.com/ovn-org/ovn-kubernetes/pull/3114/commits/be8786a89546effe2de121fce9c05907fae4c1ce#r945726724
Co-authored-by: Tim Rozet <trozet@redhat.com>
Reported-at: https://issues.redhat.com/browse/OCPBUGS-469
=> pods: deleteLogicalPort should not fail when port is already gone

go-controller/pkg/ovn/egressip.go
This deletes any stale ip from node allocations map before assignment
so that update on same egress ip object would assign new ip address
on a particular assignable node in any timing scenarios.
For Example:
1. Label a node with `k8s.ovn.org/egress-assignable='' `
2. Create egress ip entry like below.
```
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
name: egressips-peri-test
spec:
egressIPs:
- 10.0.128.10
namespaceSelector:
matchLabels:
team: red
```
For this EgressIP object, ovn-k populates egressNode#allocations cache with an entry for labeled node and then invokes 
CreateCloudPrivateIPConfig for given ip address. In some clouds like Azure, this op takes a while and delay in populating 
EgressIP object with status containing node and ip.
3. While cloud op is in progress, Update …
=> Delete stale egress ip before assigning new ip

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
it is no longer required to have the interface address be in each pod.
Since the reroute logical router static policies where added these
routes in the pods are not required
=> Remove hybrid routes in pods for nodes hybrid overlay interface addr

go-controller/pkg/cni/helper_linux.go
If the pod only has IPv4 addresses, we don't need to do any IPv6
stuff because it won't matter anyway. The sysctls take the RTNL
lock which under heavy load contends with other users (metrics,
cadvisor, node exporter), and SettleAddresses() does netlink
operations every 50ms.
Even with all that, this doesn't have a huge affect in heavy
load cases because the OVS operations and waiting for ovn-installed
take way more time, and waiting for addresses to settle actually
runs in parallel with ovn-installed.
But let's not make the netlink problem worse, and let's credit
the time taken for operations to the rigth place instead of
masking it.
Sample of some timings to call SettleAddresses during a scale test:
```
/tmp/logs2/bdd1ffe1-node-density-heavy-20220827-perfapp-1-126-84f65fb45c-nx6hb-2022-0 …
```
=> cni: don't settle addresses or set IPv6 parameters for IPv4

docs/metrics.md, go-controller/go.mod, go-controller/go.sum, go-controller/pkg/libovsdb/libovsdb.go, go-controller/pkg/testing/libovsdb/libovsdb.go, go-controller/vendor/github.com/Microsoft/go-winio/README.md, go-controller/vendor/github.com/Microsoft/go-winio/file.go, go-controller/vendor/github.com/Microsoft/go-winio/hvsock.go, go-controller/vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go, go-controller/vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go, go-controller/vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go, go-controller/vendor/github.com/Microsoft/go-winio/vhd/vhd.go, go-controller/vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go, go-controller/vendor/github.com/cenkalti/backoff/v4/exponential.go, go-controller/vendor/github.com/ovn-org/libovsdb/client/metrics.go, go-controller/vendor/modules.txt
depends on ovn-org/libovsdb/pull/328
See docs/metrics.md for metric names.
I want libovsdb monitor connection metrics to create an alert if we aren't connected to SB and NB DBs.
Also,
Go mod vendor for vishvananda/netlink has custom modifications. When I perform go mod vendor, I need to remove the overwrites of the custom mods. It seems surya made the mods.
~~Also, fedora dockerfile is rejecting updates because of gpg check. Needed to add `--nogpgcheck` to install the packages locally.~~
Resolved - very old f36 image locally.
Testing with CI.
/cc @npinaeva
=> Add libovsdb metrics

test/e2e/e2e.go, test/e2e/external_gateways.go, test/e2e/util.go, test/scripts/e2e-cp.sh
Currently running the external gateways e2e tests is possible
only on kind deployments.
Adding support for using a host-networked container
instead of leveraging the kind network allows running
the tests from a host that can access the cluster.
=> External gateways E2E on host network

go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go
There is a lot of duplicated code in master_test.go that can be removed
by making better use of ginkgo.BeforeEach()
=> take advantage of ginkgo framework to make master_test.go simpler

go-controller/pkg/ovn/healthcheck/egressip_healthcheck.go
grpc-go only supports HTTP proxy: https://github.com/grpc/grpc-go/blob/master/Documentation/proxy.md. Use a custom dialer to enable socks proxy.
=> Use a custom dialer for GRPC to allow connectivity over a socks proxy

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/ovn.go, test/e2e/acl_logging.go, test/e2e/util.go
commit 150d9b71f2bfb6630cbfe4775cd19885755fef95 (HEAD -> 2111362, origin/2111362)
Author: Andreas Karis <ak.karis@gmail.com>
Date:   Mon Aug 1 20:05:42 2022 +0000
ACL logging: rename and rewrite oc.aclLoggingCanEnable
Rename oc.aclLoggingCanEnable to aclLoggingUpdateNsInfo and make some
changes to this method and how it is being called.
When a namespace's ACL logging annotation is updated to either {}
or {"allow": "", "deny": ""}, make sure to disable ACL logging
completely.
When "" or an invalid value is provided for "allow" or "deny", reset
the key's value to "", always.
commit 194963e512bbcdeb8d15f0c22fb7f90c1e2b42cb
Author: Andreas Karis <ak.karis@gmail.com>
Date:   Mon Aug 1 15:00:48 2022 +0200
E2E tests: Improve EgressFW and …
=> BZ2111362: ACL logging: rename and rewrite oc.aclLoggingCanEnable 

go-controller/pkg/metrics/master.go
GetConfigDurationRecorder is called from two paths. 1) nodeTracker detects a switch or GR has been added for the node and does a full RequestFullSync which calls onServiceAdd 2) onServiceAdd is called from the service handler for adds.
If we don't lock the cdr variable we access it from two routines while one routine edits it; the other tries to read it for example. Let's lock this variable to prevent races.
```
2022-09-09T14:33:01.6982688Z WARNING: DATA RACE
2022-09-09T14:33:01.6982976Z Read at 0x000004402a78 by goroutine 1044:
2022-09-09T14:33:01.6983629Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.GetConfigDurationRecorder()
2022-09-09T14:33:01.6984387Z       /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/metrics/master.go:847 +0x29b …
```
=> Lock the cdr global variable

go-controller/pkg/ovn/master.go
Commit 16ea40be changed the logical switch other-config to be overwriten this needs to be changed so that the hostsubnet values are appended.
https://bugzilla.redhat.com/show_bug.cgi?id=2117255
=> BZ2117255 append instead of overwrite logicalSwitch other-config

go-controller/pkg/node/helper_linux.go, go-controller/pkg/node/helper_linux_test.go
Due to the way how IPv6 multipath is implemented, it is not possible to filter by ifindex as the ifindex for multihop routes will always be 0. Instead, implement a custom filter.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1318
Here's a reproducer that helps understand why the original approach does not work.
The reproducer is super simple, using ifindex 2 for my interface eth0:
~~~
[root@ovnkubernetes netlink-test]# ip a ls dev eth0 | head -1
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
~~~
~~~
package main
import (
"fmt"
"github.com/vishvananda/netlink"
)
func main() {
filter := &netlink.Route{Dst: nil}
mask := …
=> getDefaultGatewayInterfaceByFamily: custom filter for MultiHop

docs/kind.md
Hey, I found that `kind.md` has two problems.
We could not execute `go get` to get `src` folder unless executing `go env -w GO111MODULE=auto` first.
Second, we need `go env GOPATH` to get `GOPATH` environment rather than only `GOPATH`.
I fix them, and they run well on my laptop.
=> Modification of kind.md document

go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/healthcheck.go
We were not creating healthchecks for service updates when the etp changed from local to cluster or back. This PR fixes this. It also fixes some endpoint slice code on node side where we seem to assume service:endpointslice is 1:1 ? o_o
No use of adding e2e's here since this only effects cloud load balancer offerings, KIND clusters don't have that luxury, real e2e needs to go into sig-network, will see if I can submit a PR for this there.
=> Fix UpdateService healthport checks

go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
While testing the  removal of a node that has completed pods stuck on finalizers, I ran
into this codepath. It fails removal of logical port (which had already been removed) because
it logical switch is already removed as well.
This PR fixes that, in addition to including a test that exercises the logic mentioned here. 
Closes https://github.com/ovn-org/ovn-kubernetes/issues/3168
=> pods: deleteLogicalPort should not fail when ls is gone

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
PolicyTypes field of a policy should always be set to an appropriate value before it reaches the network plugin. The network plugin should not make any assumptions about what the policy type is outside of what PolicyTypes indicates towards evaluating the isolation status of a selected pod.
Not doing any re-synchronization of possibly affected policies because:
- If the user does not provide PolicyTypes, api server will fill those appropriately.
- It is unlikely that a user provides PolicyTypes that do not include a type for which rules are provided as well. And if it does, it's probably better not to change the behavior of those policies anyway.
**- How to …
=> Don't assume policy type when evaluating isolation

go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
We didn't consider this tiny hack that we do
https://github.com/openshift/ovn-kubernetes/blob/44ad75466e486cce605e39513a3ecd9e0b306e7d/go-controller/pkg/libovsdbops/acl.go#L60 there when we wrote https://github.com/openshift/ovn-kubernetes/pull/1259 and unit tests don't actually scream loudly for longer names.
Without this PR we break users who have namespace names longer than 45 characters.
Co-authored-by: Patryk Diak <pdiak@redhat.com>
=> Trim ACL names according to RFC1123

go-controller/hybrid-overlay/pkg/controller/node_linux.go, go-controller/hybrid-overlay/pkg/controller/node_linux_test.go, go-controller/hybrid-overlay/pkg/types/types.go, go-controller/pkg/node/node.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
Change the hybrid overlay so that it can use any ipv4 address in the nodes subnet to setup. This will remove the requirement that hybrid overlay be on during cluster setup. hybrid overlay does require a restart to enable but not a clean cluster
=> remove the requirement that hybrid overlay needs subnet .3 address

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/syncmap/syncmap.go
No need to save and pass portGroupIngressDenyName,
portGroupEgressDenyName. Some time ago its name was unpredictable, but
now it can be just retrieved with defaultDenyPortGroupName.
Sort ovn.go imports
Move logic to define if policy need egress/ingress isolation from update
counters function to networkPolicy object
Stop counting nsInfo.networkPolicies to decide if defaultDeny port group
should be created/deleted: for shared resources like this counter should
be updated atomically together with db.
An example of race with previous implementation: 2 network policies are
being created, nsInfo.networkPolicies will only be updated at the end.
Both network policies will call createDefaultDenyPGAndACLs, which in
turn creates port group with empty ports list, so one policy can drop
ports added by …
=> Improve default deny port groups logic for network policy

go-controller/pkg/ovn/namespace.go, go-controller/pkg/ovn/obj_retry.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Don't store network policy objects in namespaceInfo, use
oc.networkPolicies. This allows to retry network policy create/delete/ cleanup without namespace dependency. we also don't need to delete network policies on namespace delete, because network policy will receive delete event itself (like pods).
Don't use ensureNamespaceLocked, since we don't want to create deleted namespace, use getNamespaceLocked instead.
Allowed order locking is namespace -> oc.networkPolicies -> networkPolicy.Lock. It allows namespace to trigger network policy acl loglevel update while holding namespace lock.
Namespace is responsible for retrying acl loglevel update if that fails.
Network policy is responsible for retrying create if namespace update can't be applied.
policy_test update: defaultDeny port group …
=> Separate network policies from namespaceInfo

go-controller/pkg/ovn/healthcheck/egressip_healthcheck.go
Connecting logic iterates through all the management addresses that egress IP can use to reach its egress nodes. The log, however, was only providing the last one it tried.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-2004
=> egress IP: fix log when gRPC connection fails

README.md, docs/egress-ip.md
Document egress IP functionality.
Emphasis on this commit was done in documenting the gRPC enhancement that is now implemented as part of the Egress IP reachability logic.
Reported-at: https://issues.redhat.com/browse/SDN-3470
=> Add egress-ip doc

go-controller/pkg/node/gateway_shared_intf.go
Now that the special masquerade IPs are assigned to the interface, they default flows that end up DNAT'ing return traffic from the GR->host from masquerade ip -> host ip were being overridden with secondary ip flows for extra ips. This fixes it by skipping special ips when evaluting the extra ips on a node.
=> Fixes incorrect GR hairpin flows

go-controller/pkg/node/node.go
GetMACAddressFromArp does not support IPv6 addresses as IPv6 does not have ARP.
Silenced the logs by checking if ip that is passed in is v6 and added TODO to add support 
for IPv6 external gateways.
Also adds a warning if an attempt to find the mac address is done with an IPv6 gatewayIP
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> Silence error logs for IPv6

go-controller/pkg/ovn/obj_retry.go
We were passing the newObj into deleteResource
instead of the oldObj and this was creating
unexpected bugs.
This was caught when trying to add unit tests for https://github.com/ovn-org/ovn-kubernetes/pull/3175
Basically if deletion failed for stateful-set and we got a new add event for stateful-set it was deleting the newObj instead of the oldObj in the add event handler. Blocks the other PR. PTAL @ricky-rav @trozet
=> Pass old object when doing deleteRetry

go-controller/pkg/ovn/acl.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
Improve netpol naming: either namespace or port group is used to
generate ACL name, don't pass both.
Add separate functions to get name for different ACLs. Add common ACLType type to use for all ACLs, not only related to network policy.
Unify BuildACL: set direction and options based on ACLType:
- ACLTypeIngress => direction = nbdb.ACLDirectionToLport
- ACLTypeEgress => direction = nbdb.ACLDirectionFromLport, options["apply-after-lb"] = "true"
Pass externalIDs and aclName to BuildACL explicitly.
=> Improve netpol naming, unify BuildACL

go-controller/pkg/libovsdbops/transact.go
When updating a large number of address_set, logs get flooded with "Configuring OVN" which cannot be reduced.
Also klog shows up in the profiling data as a source of CPU consumption of ovnkube-master.
We make it configurable and assign it a verbosity of 4 which is default on OpenShift.
Signed-off-by: François Rigault <frigo@amadeus.com>
=> Add logging verbosity to configuring OVN logs

go-controller/cmd/ovnkube-trace/ovnkube-trace.go, go-controller/hybrid-overlay/pkg/util/util.go, go-controller/pkg/node/gateway_iptables.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/node/gateway_shared_intf_linux.go, go-controller/pkg/node/healthcheck.go, go-controller/pkg/node/node.go, go-controller/pkg/node/port_claim.go, go-controller/pkg/ovn/controller/egress_services/egress_services_service.go, go-controller/pkg/ovn/controller/services/load_balancer.go, go-controller/pkg/ovn/controller/services/load_balancer_test.go, go-controller/pkg/ovn/controller/services/utils.go, go-controller/pkg/ovn/egressgw.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovndbmanager/ovndbmanager.go, go-controller/pkg/util/kube.go, go-controller/pkg/util/kube_test.go, go-controller/pkg/util/pod_annotation.go
Changed all ParseIP and ParseCIDR functions of net package to ParseIPSloppy and ParseCIDRSloppy of k8s.io/utils/net package respectively for k8s API objects. This is done to allow IPs and CIDRs with leading zeros to be parsed without any error.
Additionally have added conversion of any IP in string format to net.IP format and then conversion to string format again to remove any leading zeros.
Following set of IP strings are validated:
- `service.Spec.ClusterIP`
- `service.Spec.ClusterIPs`
- `service.Spec.ExternalIPs`
- `service.Status.LoadBalancer.Ingress[*].IP`
- `node.Status.Addresses[*].Address` (for address types `NodeInternalIP` and `NodeExternalIP`)
- `endpointSlice.Endpoints[*].Addresses`
- `pod.Status.PodIP`
- `pod.Status.PodIPs[*].IP`
Signed-off-by: Arkadeep Sen …
=> Support proper parsing of IPs with leading zeros

go-controller/pkg/libovsdbops/model_client.go, go-controller/pkg/libovsdbops/model_client_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/pods_test.go
to do index-based search.
Update the logic for model lookup to
1. Use index if any provided
2. If no indices provided with the Model, use predicate search.
Update syncPods find logical switch to only set Model.UUID if it is not
empty, otherwise search will only be performed using given UUID, and no
attempt to use predicate will be made.
Update egress_ip test to set empty ls UUID, since we don't know the real
switch UUID in the db to make a search, but it can be done by name.
=> Update libovsdbops to use Where().List() instead of Get()

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go
When handlers share the informer for the same type of objects - example egressIP feature also watches for Pods and creates a handler to receive events for any pod-related activities - it is better to prioritize the order in which a specific event for a pod will be processed. Pod creation should happen first, so addLogicalPort should go first before egressIP Pod handler. Similarly for network policies and other controllers.
Today OVNK already handles the events serially, the only problem is we don't control which handler gets the event first, so this PR adds a priority system for the handlers where by we say all critical handlers get priority 0 - this is the highest priority and it applies to pods/namespaces/nodes and all the CRD objects. Then …
=> Prioritize adding events to handlers for shared resources

go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go
Default gateway requirement was removed in 3eeb93079, but the L3GatewayConfig UnmarshalJSON function still expects non-empty nexthop value in L3GatewayConfig.
=> Allow empty nexthop in L3GatewayConfig annotation

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/util/ovs.go
This is a OVS dependent work around fix. If we detect that OVS HW Offload is enabled, we are aware that the offloading of packet MTU check support in OVS is not supported. This support will not be available until the offload support for sFlow is added.
In order to have the most optimal performance, the packet MTU check support should be disabled when OVS HW Offload is enabled on the node.
I added an extra condition to check for OVS HW Offload is enabled during the code that checks for check pkt length support.
Enable OVS Hardware Offload then check that the warning is printed in the logs when OVN-K is started.
Disable packet MTU check when OVS HW …
=> Disable packet MTU check when OVS HW Offload is enabled

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/retry/obj_retry.go
leverage stop channel on watch factory when periodic retry stopchannel is called
Problem: Hybrid test was creating creating an ovn-controller for some tests.
The tests could not use the waitGroup in the test so the afterEach function
(cleanup function after each test) could execute while leaving controllers up.
In the tests, we were leveraging the code in ovn.go to run the controllers
and creating a watcher pod on them. This issue was just a symptom of the main
issue which was that we were using the incorrect stopChannel in the retry logic.
Solution: The stopChannel that we use in the watchFactory is private, so we
created a function that when called will close the watcher stopChannel,
closing the watcher. We then call this function in the select
(basically a switch statement in go but …
=>  refactor retry to close watchFactory

go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go
The tests were copying the podAssignment cache under the cache's lock, but unfortunately it was just a shallow-copy of element of that cache. Maps within structs are copied by reference, not by value (eg deep-copy), so neither the 'egressStatuses' nor the 'standbyEgressIPNames' members of each podAssignmentState element were deep-copied.
This led to data races in the tests like:
```
2022-10-27T13:00:36.6560710Z WARNING: DATA RACE
2022-10-27T13:00:36.6560988Z Write at 0x00c01c6480c0 by goroutine 1527:
2022-10-27T13:00:36.6561275Z   runtime.mapdelete_faststr()
2022-10-27T13:00:36.6561762Z       /opt/hostedtoolcache/go/1.18.4/x64/src/runtime/map_faststr.go:301 +0x0
2022-10-27T13:00:36.6562144Z   k8s.io/apimachinery/pkg/util/sets.String.Delete()
2022-10-27T13:00:36.6563012Z …
```
=> egressip: fix test data race accessing podAssignment cache

go-controller/go.mod, go-controller/go.sum, go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go, go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/database.go, go-controller/vendor/modules.txt
Pulls in the following commits, for which we really just care about the client logging one for performance.
64a1543b16 client: don't construct transaction log string when it's not needed
https://github.com/ovn-org/libovsdb/pull/342
14b9f5b67b Make table name a const above generated model
https://github.com/ovn-org/libovsdb/pull/337
=> vendor: bump libovsdb to 8f21d188c3a50d0ce378bd66ec68215967aaad77

go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go, go-controller/pkg/ovn/controller/egress_services/egress_services_service.go, go-controller/pkg/ovn/egressservices_test.go, go-controller/pkg/util/service_annotations.go, go-controller/pkg/util/service_annotations_test.go
The egress service nodeSelector parsing did
not take into account wrong values that cause
errors (such as "name part must consist of alphanumeric characters"),
and the controller did not handle them gracefully given a bad input.
This PR adds some sort of validation to the
annotation given and some tests to verify the correct behavior.
The first commit is pretty much cosmetic (the long diff is misleading :slightly_smiling_face:)
=> Egress Services: Fix nodeSelector parsing

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
- to accommodate scenarios where ovnkube-master is not present in the namespace use ovnkube-node pod to detect the db addresses
- use ovn-sbctl instead of ovn-nbctl to enable environments without nbdb connectivity
- run ovn-detrace only if connectivity to nbdb is available
/cc @tssurya @andreaskaris 
This should address https://issues.redhat.com/browse/OCPBUGS-298
=> Adapt ovnkube-trace to work with external controlplane

go-controller/pkg/factory/factory.go, go-controller/pkg/factory/factory_test.go, go-controller/pkg/factory/handler.go, go-controller/pkg/informer/informer.go, go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go, go-controller/pkg/ovn/controller/services/node_tracker.go, go-controller/pkg/ovn/controller/services/services_controller.go, go-controller/pkg/ovn/egressqos.go
Sometimes k8s watcher getting restarted and for this condition update events are sent for all updated resources. If the object was recreated with same namespace and name while the watcher was off, ovnk gets update event where old and new objects have different UIDs.
Hence this commit handles such scenario by comparing object UIDs, deleting resources for old object followed by adding resources for new object.
=> Handle k8s watcher restart scenario

go-controller/pkg/ovn/pods.go
Issue: When a new ovnkube master starts, or gains leadership through leaderelection, addLogicalPort is called for all existing pods to ensure they are set up correctly, which means we recollect the podCreated metrics on pods that may not need it, and we will set an incorrect creation latency for pods.
Solution: Do not record pod creation latency metric for pods with annotations or pods with existing logical switch ports when addLogicalPort is ran
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> Avoid re-metricing pods

go-controller/cmd/ovnkube-trace/ovnkube-trace.go
Instead of exiting with an error, exit gracefully with an info message. Add a flag so that ovnkube-detrace can be skipped altogether.
~~~
[akaris@linux go-controller (ovnkube-trace-2022-11-06)]$ ./_output/go/bin/ovnkube-trace -src-namespace openshift-network-diagnostics -dst-namespace openshift-network-diagnostics -src network-check-target-4dq2b -dst network-check-target-7fbh7 -tcp
I1106 14:32:16.248415 1761302 ovs.go:90] Maximum command line arguments set to: 191102
ovn-trace source pod to destination pod indicates success from network-check-target-4dq2b to network-check-target-7fbh7
ovn-trace destination pod to source pod indicates …
=> ovnkube-trace: Fail gracefully on failed ovn-detrace dependency check

go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
general fixes to the windows node_linux.go testing to make the testing more meaningful. The tests are not ideal because there is no interface into fakeCmd to get the bundled ovs commands but we can compare the cache to what we believe it should be.
I also removed tests that where no longer meaningful
test "removes stale node flows on initial sync" and "removes stale pod flows on initial sync" are no longer needed because we sync to the flowCache on every sync and that stale nodes/pods will be taken care of then.
test "sets up local pod flows" is a duplicate of "sets up local linux pod" so I removed the former
**- Description for the …
=> fixes to windows testing

go-controller/pkg/ovn/hybrid.go, go-controller/pkg/ovn/hybrid_test.go
When changing the hybrid overlay to dynamically allocated IP addresses there where instanses where the .3 address was blindly returned. Correct that mistake
=> correct the hybrid overlay port MAC address

go-controller/pkg/retry/obj_retry.go
Avoid unnecessary log messages like:
> I1103 16:08:37.699509   89653 obj_retry.go:197] Iterate retry objects requested (resource *v1.Pod)
> I1103 16:08:37.699523   89653 master.go:1299] Posting Warning event for Node node1: [cannot allocate hybrid overlay distributed router ip for nodes until all initial pods are processed, k8s.ovn.org/node-chassis-id annotation not found for node node1, macAddress annotation not found for node "node1" , failed to set up hybrid overlay logical switch port for node1: unable to setup Hybrid Subnet Logical Route Policy for node: node1, error: unable to find router port rtoj-GR_node1: object not found, k8s.ovn.org/l3-gateway-config annotation not found for node "node1"]
> I1103 16:09:07.688454   89653 obj_retry.go:346] Going to retry *v1.Namespace resource …
=> Don't log in iterateRetryResources when there are no retry entries

go-controller/pkg/ovn/egressfirewall_dns.go
When nextQueryTime for dns entry is already expired and update goroutine is trying to use negative duration to reset ticker. This causes process crash on the ovnk master. This change avoids proces crash and ensures to trigger ticker in shortest possible time (1 ms) so that update happens immediately on expired dns entry.
=> Handle expired entry while handling dns update

go-controller/pkg/factory/factory.go, go-controller/pkg/ovn/controller/services/services_controller_test.go, go-controller/pkg/ovn/gress_policy.go, go-controller/pkg/ovn/loadbalancer/loadbalancer.go, go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go, go-controller/pkg/types/const.go, test/e2e/e2e.go, test/e2e/egressip.go, test/e2e/service.go, test/e2e/util.go
Currently NP's with service hairpin traffic is broken***. This PR revives the work done in https://github.com/ovn-org/ovn-kubernetes/pull/2332. We add a new masqueradeIP that will be passed as the explicit hairpin_snat_ip into OVN LBs. Based on that masqeuradeIP we update all ingressACLs to be `ip.src == srcAS || ip.src == masqueradeIP && ip.dst == srcAS`. See commit4 for more details. By doing this we can remove the dependency for network policies to watch for services and we can get rid of `peerServiceType`.
*** When I say broken, I mean more broken than it was, since we allow/deny in a random manner in OVNK for hairpin traffic. Example: Let's consider nsA with podA and podB and podC. We have a svc backed by all these pods.
case1: 1) We have …
=> Fix Network Policy Service Hairpin Traffic

go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/node_ip_handler_linux.go, go-controller/pkg/ovn/egressfirewall_dns_test.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/testing/testifymockhelper.go, go-controller/pkg/util/dns_test.go
If real conntrack operations are performed against the CI host we may get operation errors because we're not running a real node in the testcases and we fake out all the iptables stuff too. We shouldn't mix real operations in the CI host's netns with fake operations in the testscases because then we cannot control the test parameters.
Second, don't start the node IP handler's netlink watch or sync host IPs in testcases because it scrapes the CI host's IP addresses which service deletion uses when clearing conntrack, which the testcases know nothing about. Just stick with the fake node IP that the testcases already add.
```
[91m[1m• Failure [0.114 seconds][0m
Node Operations
[90m/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_localnet_linux_test.go:161[0m
on …
```
=> node: mock conntrack delete operations for service and EgressIP testcases

contrib/kind.sh, dist/images/Dockerfile.fedora, dist/images/daemonset.sh, dist/images/ovndb-raft-functions.sh, dist/images/ovnkube.sh, dist/templates/ovn-ipsec.yaml.j2, dist/templates/ovn-setup.yaml.j2, dist/templates/ovnkube-db-raft.yaml.j2, dist/templates/ovnkube-db.yaml.j2
Deploy with:
~~~
contrib/kind.sh -ha --ipsec
~~~
Or without the -ha parameter
Once deployed, check the pods:
~~~
[root@ovnkubernetes ovn-kubernetes]# oc get pods -n ovn-kubernetes | grep ipsec
ovn-ipsec-btm5l                   1/1     Running   0          16m
ovn-ipsec-n252g                   1/1     Running   0          16m
ovn-ipsec-wkxks                   1/1     Running   0          16m
~~~
And run a tcpdump inside one of the docker containers:
~~~
[root@ovnkubernetes ovn-kubernetes]# tcpdump -nne -i eth0 esp
(...)
~~~
While pinging from one pod on the cluster to another:
~~~
[root@ovnkubernetes ~]# oc get pods -o wide
NAME                                   READY   STATUS    RESTARTS …
=> kind.sh: Add IPsec option to kind deployments

go-controller/pkg/ovn/obj_retry_master.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go, go-controller/pkg/util/kube.go
Fixes a scenario where a pod exists but the node does not and upon ovnk master reboot our sync would fail. During sync we should attempt to preallocate all existing pod IPs, which include terminating pods with finalizers.
=> Handle cases where a pod may exist but the node does not

go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/egressip.go, go-controller/pkg/ovn/egressip_test.go, go-controller/pkg/ovn/ovn.go
There are three places where ovnkube marks an egress node as reachable:
- node add event handler
- node update even handler
- periodic connectivity checker
In a scenario where the egressip node becomes reachable at the same time as the node object is updated the node is set as reachable but because there was no label/readiness change it is never added as an egressip node: https://github.com/ovn-org/ovn-kubernetes/blob/17ab3c3de635c33489a64b58c68b2c4b0935dfb7/go-controller/pkg/ovn/obj_retry_master.go#L614-L632 The periodic check will then ignore the node because it considers it as already reachable: 
https://github.com/ovn-org/ovn-kubernetes/blob/17ab3c3de635c33489a64b58c68b2c4b0935dfb7/go-controller/pkg/ovn/egressip.go#L2432-L2438
To address the issue only set the node as reachable if it …
=> egressip node update: set the node as reachable only when it is beingadded as an egressip node

go-controller/pkg/libovsdbops/acl.go, go-controller/pkg/libovsdbops/portgroup.go, go-controller/pkg/ovn/egressfirewall.go, go-controller/pkg/ovn/egressfirewall_test.go, go-controller/pkg/ovn/policy.go, go-controller/pkg/ovn/policy_test.go
since it will fail if equivalent ACL is not deleted from port group/switch. e.g. on netpol sync, users (somehow) ended up with equivalent default deny ACLs with different names, one of them will be updated and one will be sent to DeleteACLsOps. DeleteACLsOps will find both ACLs because of predicate search, and will try to delete both of them, but only one of them is de-referenced from the port group in the beginning, so it will return delete error like `cannot delete ACL row 7b55ba0c-150f-4a63-9601-cfde25f29408 because of 1 remaining reference(s)`
Only delete ACLs when owner port group/switch is not deleted, only allow deletion for ACLs with UUID to make sure it is properly dereferenced. 
Update netpol tests to include not-garbage-collected ACLs for deleted port groups.
Signed-off-by: …
=> Don't delete equivalent ACLs by predicate

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go, go-controller/pkg/ovn/pods.go, go-controller/pkg/ovn/pods_test.go
deleteLogicalPort should not fail when node is already deleted from lsManager's cache.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-3739
=> pods: deleteLogicalPort should not fail when node is gone

go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/gateway_shared_intf.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/gateway_init.go, go-controller/pkg/ovn/gateway_test.go, go-controller/pkg/ovn/hybrid_test.go, go-controller/pkg/ovn/master.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/namespace_test.go, go-controller/pkg/ovn/ovn.go, go-controller/pkg/util/node_annotations.go, go-controller/pkg/util/node_annotations_unit_test.go, test/e2e/service.go
A series of patches around 947e8d450ebaa8ce4ab81cb480a419618f1508c7
in the ovn-org/ovn repository now enable check_pkt_larger for gateway
router ports. Take advantage of this new feature to solve https://issues.redhat.com/browse/OCPBUGS-2827
Also see: http://patchwork.ozlabs.org/project/ovn/cover/cover.1627405420.git.lorenzo.bianconi@redhat.com/
Reported-at: https://issues.redhat.com/browse/OCPBUGS-2827
=> Move check_pkt_larger to gateway router ports

go-controller/cmd/ovnkube/ovnkube.go, go-controller/pkg/factory/factory.go, go-controller/pkg/node/gateway.go, go-controller/pkg/node/gateway_init.go, go-controller/pkg/node/gateway_init_linux_test.go, go-controller/pkg/node/gateway_localnet_linux_test.go, go-controller/pkg/node/node.go, go-controller/pkg/node/obj_retry_gateway.go, go-controller/pkg/node/obj_retry_node.go, go-controller/pkg/node/obj_retry_test_helper.go, go-controller/pkg/node/ovn_test.go, go-controller/pkg/ovn/default_network_controller.go, go-controller/pkg/ovn/master_test.go, go-controller/pkg/ovn/ovn_test.go, go-controller/pkg/retry/obj_retry.go
Instead of having the WatchFactory expose a WaitGroup (which is somewhat of an encapsulation violation), we can pass the top-level WaitGroup from ovnkube.go down to the retry code and use it there. We're already using that WaitGroup many places in the master and node code so we might as well push it down to retry code too. This keeps the factory code somewhat cleaner by not exposing its own internal WaitGroup.
All we really care about is that the goroutine that calls `periodicallyRetryResources()` exits when the OvnController or OvnNode is shut down, and adding it to the top-level WaitGroup accomplishes that.
As a bonus, consolidate FakeOvnNode shutdown code in the node tests into AfterEach().
@trozet @npinaeva @bpickard22 
Reverts part of #3226
=> retry: refactor stop channel/WaitGroup usage to reduce dependency on WatchFactory

go-controller/pkg/libovsdbops/switch.go, go-controller/pkg/ovn/pods_test.go
This may occur when a user exceeds max node subnet allocations.
=> Skip cleaning LSPs when LS doesn't exist

contrib/kind.sh, dist/templates/ovn-ipsec.yaml.j2
* Add help text for ipsec option to kind.sh
* Fix OpenSSL version check
* Run certificate signer in foreground
* In ovn-ipsec.yaml.j2 make the counter increment the same as in downstream cluster-network-operator
Check help text:
~~~
contrib/kind.sh -h
~~~
Launch kind with IPsec:
~~~
contrib/kind.sh --ipsec
~~~
You should see IPsec pods after deployment:
~~~
[root@ovnkubernetes ovn-kubernetes]# export KUBECONFIG=/root/ovn.conf 
[root@ovnkubernetes ovn-kubernetes]# oc get pods -A -o wide | grep ipsec
ovn-kubernetes       ovn-ipsec-97xml                             1/1     Running   0               5m10s   172.18.0.4   ovn-worker …
=> kind: Fix ipsec in kind.sh and fix counter expression

go-controller/pkg/node/management-port-dpu.go, go-controller/pkg/node/management-port.go, go-controller/pkg/node/node.go
There can be multiple management ports. Currently in the case of Full mode with hardware backed mgmt port, the virtual function representor and virtual function netdev exists separately. However the management port config belongs to the virtual function representor in this case. This caused the Egress IP health check to fail to initialize since there won't be an IP address on the virtual function representor interface. Instead the code now iterates through all management port interfaces, skips the virtual function representor and finds the virtual function netdev management port with a valid IP address configuration.
In the case of DPU, there will be a DPU-Host mode node and DPU mode node. Also it will always use hardware backed mgmt ports. The DPU mode node will only have a virtual …
=> egress ip: Skip mgmt ports that cannot have assignable IP addresses

dist/images/Dockerfile.fedora
Mainly to pickup the fix for the session affinity timeout bug.
=> Dockerfile.fedora: bump OVN to 22.09.0-25
