ovn-kubernetes/ovn-kubernetes

.github/workflows/test.yml

CI: Remove redundant booleans and use names for all of the features.

---

.github/workflows/test.yml

The initial fix omitted the periodic job. Remediate this.

ci: Periodic job remove redundant booleans and use names

---

go-controller/cmd/ovnkube-trace/ovnkube-trace.go

Determine SSL status from the deployment automatically instead of
relying on a command line flag.
Fixes #2309

ovnkube-trace: Auto determine SSL status for OVN

---

go-controller/pkg/ovn/address_set/address_set.go
go-controller/pkg/ovn/address_set/address_set_cleanup.go
go-controller/pkg/ovn/address_set/address_set_test.go
go-controller/pkg/ovn/egressfirewall_dns_test.go
go-controller/pkg/ovn/ovn.go

[libovsdb] changing addressset to use libovsdb and testing in CI

---

go-controller/go.mod
go-controller/go.sum
go-controller/vendor/github.com/ebay/go-ovn/client.go
go-controller/vendor/github.com/ebay/go-ovn/logical_switch_port.go
go-controller/vendor/github.com/ebay/go-ovn/ovnimp.go
go-controller/vendor/github.com/ebay/go-ovn/port_group.go
go-controller/vendor/modules.txt

This picks up Tim's change removing the transaction lock.

vendor: bump go-ovn

---

go-controller/pkg/node/gateway_shared_intf.go

Today, openflow rules on the shared gateway bridge
send incoming traffic from uplink to conntrack on zone
64000 to decide if the traffic needs to be steered towards
OVN or the host.
established/related connections are sent to OVN via
the patch port to OVN integration bridge while new
connections are set to the host.
This poses an issue for NICs that are capable of offloading
conneciton tracking rules as only established connections are
offloadable.
This commit modifies the openflow rules on the physical
bridge to allow the use of ct_mark on ct zone 64000 to
classify traffic going to host and OVN
- table 0: set up higher priority rule (200) to steer tunneled traffic
based on udp encap port
- table 0: commit traffic coming out of ovn (patch to br-int) to zone 64000
with ct_mark=0x1
- table …

Shared gateway use ct_mark to classify host/ovn traffic

---

docs/ci.md

Update CI documentation and add further details that will help
first time contributors understand the workflows better.

Documentation: Improve CI documentation

---

docs/ovnkube-trace.md

Update ovnkube-trace documentation

Documentation: Update ovnkube-trace documentation

---

go-controller/pkg/ovn/egressip_test.go

I don't know how CI has managed to pass with this failing across the board (I will create an issue for it), but this test is currently broken and fails on _certain_ PRs (see: https://github.com/ovn-org/ovn-kubernetes/pull/2427/checks?check_run_id=3371570502 / https://github.com/ovn-org/ovn-kubernetes/pull/2331/checks?check_run_id=3373000587)

Egress IP: fix failing test

---

go-controller/cmd/ovn-kube-util/app/readiness-probe.go

Readiness Probe improvements for ovn-northd and ovn-controller containers

---

go-controller/go.mod
go-controller/go.sum
go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/bindings.go
go-controller/vendor/modules.txt

This will bump libovsdb and get https://github.com/ovn-org/libovsdb/pull/220 which is needed for #2426 (maybe other PRs too)
/assign @jcaamano @flavio-fernandes 

[libovsdb] Bump to main: optional field value fix for in-mem DB

---

go-controller/pkg/ovndbmanager/ovndbmanager.go

Fixes backwards values for election timer

---

go-controller/pkg/ovn/logical_switch_manager.go

When populating the cache, if for some reason the node's GW LRP
already has that IP, don't fail.
```
E0826 13:45:04.449574       1 namespace.go:587] Failed to get join switch port IP address for node ip-10-0-152-74.us-west-2.compute.internal: provided IP is already allocated
E0826 13:45:04.620345       1 master.go:1260] Failed to get join switch port IP address for node ip-10-0-152-74.us-west-2.compute.internal: provided IP is already allocated
```

master: don't fail trying to cache same GW LRP IPs as already exist

---

contrib/kind.sh
docs/kind.md

Trivial: This is particularly helpful when working around pull rate limit
issues. Update documentation for kind.sh

kind.sh: Make kind image configurable

---

go-controller/pkg/cni/cni.go

When logging the result of CNI requests, filter out kubeAuth from the response, since it might contain sensitive information.
Today ovnkube-node logs include the entire response from all CNI requests, which includes the KubeAPIToken from the KubeAPIAuth part of the response. For instance:
> I0909 15:57:37.113983    1081 cni.go:246] [kube-system/coredns-74ff55c5b-rpbwj 78bcab6c1889a04f6e14d83d2a5caf6143f82bdaf162bb543f7c36857755051f] ADD finished CNI request [kube-system/coredns-74ff55c5b-rpbwj 78bcab6c1889a04f6e14d83d2a5caf6143f82bdaf162bb543f7c36857755051f], result "{\"Result\":{\"interfaces\":[{\"name\":\"78bcab6c1889a04\",\"mac\":\"b6:a5:6a:b4:2e:10\"},{\"name\":\"eth0\",\"mac\":\"0a:58:0a:f4:02:03\",\"sandbox\":\"/var/run/netns/cni-efc6443c-bc1c-5380-d90d-377a4a029747\"}],\"ips\":[{\"v …

Bug 1999261: filter out KubeAPIAuth when logging CNI requests

---

go-controller/pkg/ovn/ovn.go

In the update pod logic, we pass the current pod event to
addLogicalPort. In addLogicalPort we assume that if the annotations
exist for the pod mac/ifaddr, then we use those and do not update
annotations on the pod. This assumption is invalid, because this event
may not be the current state of the pod. In other words we could have a
situation where:
1. A pod add event comes we annotate with 10.0.0.2, assume OVN execute
failure
2. Before the annotate is done, the pod is modified in some other way
signaling another pod update event
3. A pod update event comes for 2, the pod is annotated with 10.0.0.3
because this was an update to the original pod, before it was
annotated with 10.0.0.2, assume OVN execute failure
4. A pod update event comes for 1, since annotations existed, nothing is …

Fixes misuse of pod annotations during update event

---

go-controller/pkg/ovn/master.go

this enables `fair` metring for OVN ACL logging meter. From `ovn-nb` manpage, we have:
```
fair: optional boolean
This  column is used to further describe the desired behavior of
the meter when there are multiple references to it. If this col‐
umn  is empty or is set to false, the rate will be shared across
all rows that refer to the same  Meter  name.  Conversely,  when
this  column is set to true, each user of the same Meter will be
rate-limited on its own.
```

enable fair metering for acl-logging meter

---

go-controller/pkg/node/gateway_shared_intf.go

current code calls initSharedGatewayIPTables() twice, so this commit
fixes it
@dcbw @trozet @astoycos PTAL

initialzie iptables rules in shared gateway mode only once

---

go-controller/pkg/node/gateway_init_linux_test.go

setup fake iptables helpers to avoid random failures in make check

---

go-controller/pkg/cni/cni.go
go-controller/pkg/cni/types.go

minimize marshalling operations when filtering out KubeAPIAuth in logged CNI requests
Original PR (merged): https://github.com/ovn-org/ovn-kubernetes/pull/2479
This patches addresses the changes requested in: https://github.com/openshift/ovn-kubernetes/pull/731  (... which will be closed)

Bug 1999261: filter out KubeAPIAuth when logging CNI requests (improved)

---

go-controller/pkg/cni/cni.go
go-controller/pkg/cni/cnishim.go

The check isn't really used for anything and causes a performance impact
on CRIO setups due to being called right after CNI ADD for container
creation.

Remove CNI CMD Check

---

test/e2e/e2e.go
test/scripts/e2e-cp.sh

This PR fixes e2e external gateway tests and e2e pod to a non-node host address on same node test.

Fix IPv6 e2e tests

---

go-controller/pkg/node/node.go

Today when ovnkube node is in smart-nic mode
it does not check if OVN supports setting of
OVS.Interface.external-id:ovn-installed and
OVNSB.Port_Binding.up via getOVNIfUpCheckMode()
which is used to check if an ovs port was
successfully programmed.
It instead assumes this is not supported and
falls back to legacy flow check (cni.doPodFlowsExist).
This commit calls getOVNIfUpCheckMode() in both
ovnkube node modes. For the third mode, smart-nic-host,
there is no need to call this method as ovs is not used
on the host.

Node: Set isOvnUpEnabled in full and smart-nic mode

---

dist/images/Dockerfile.fedora

Fixes https://github.com/ovn-org/ovn-kubernetes/issues/2520

Bump ovnver to fix multicast relay issue when DGP are configured

---

dist/images/daemonset.sh
dist/images/ovnkube.sh
dist/templates/ovnkube-node.yaml.j2
go-controller/pkg/cni/cni.go
go-controller/pkg/cni/helper_linux.go
go-controller/pkg/cni/types.go
go-controller/pkg/cni/utils.go
go-controller/pkg/cni/utils_test.go
go-controller/pkg/node/node_smartnic.go
go-controller/pkg/node/node_smartnic_test.go

Upstream unprivileged mode

---

go-controller/pkg/ovn/ovn.go

Instead of always one minute, start with a small backoff and increase
2x each time up to 60 seconds, with some jitter.
@trozet @alexanderConstantinescu

pods: shorten pod retry timer and include backoff

---

dist/images/Dockerfile.fedora

Includes fix for https://github.com/ovn-org/ovn/commit/beed00c9206d439c89da3bcaf924163abf606215

Bump ovn version

---

go-controller/pkg/cni/utils.go

cni: Use POD from cache, if available.

---

go-controller/go.mod
go-controller/go.sum
go-controller/hack/update-codegen.sh
go-controller/pkg/libovsdb/libovsdb.go
go-controller/pkg/nbdb/model.go
go-controller/pkg/ovn/gateway_test.go
go-controller/pkg/sbdb/model.go
go-controller/pkg/testing/libovsdb/libovsdb.go
go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go
go-controller/vendor/github.com/ovn-org/libovsdb/client/api_test_model.go
go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go
go-controller/vendor/github.com/ovn-org/libovsdb/client/condition.go
go-controller/vendor/github.com/ovn-org/libovsdb/client/options.go
go-controller/vendor/github.com/ovn-org/libovsdb/mapper/info.go
go-controller/vendor/github.com/ovn-org/libovsdb/mapper/mapper.go
go-controller/vendor/github.com/ovn-org/libovsdb/model/client.go
go-controller/vendor/github.com/ovn-org/libovsdb/model/database.go
go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/schema.go
go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/model.go
go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/updates2.go
go-controller/vendor/github.com/ovn-org/libovsdb/server/database.go
go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go
go-controller/vendor/github.com/ovn-org/libovsdb/server/transact.go
go-controller/vendor/modules.txt

This brings in some small bugfixes to reconnect handling and the mock
server implementation as well as improving cache memory consumption

vendor: bump libovsdb

---

go-controller/pkg/node/gateway_shared_intf.go

Dont Add NodePort related iptable rules on the DPU 

---

go-controller/pkg/ovn/master.go
go-controller/pkg/ovn/master_test.go

LIBOVSDB CLEANUP: Remaining Logical Router work

[libovsdb] Use libovsdb for lrp-add and gateway_chassis

---

go-controller/pkg/util/ovn.go

Removes unused nbctl find lb function

---

go-controller/pkg/node/node_ip_handler_linux.go

This PR ensures that address callbacks for node IP handler are not
missed by re-subscribing for address updates from netlink in case of
errors and also by explicitly calling sync after an initial timeout.
Co-Authored-By: Andrew Stoycos <astoycos@redhat.com>

Bug 2018276: Avoid stale annotations by re-subscribing to netlink

---

go-controller/pkg/ovn/pods.go

If the pod isn't in our port cache, and it doesn't have a Spec.NodeName
then it wasn't ever scheduled and we almost certainly never added it.
Avoid useless warnings like:
```
I1029 14:32:10.885987       1 pods.go:106] Deleting pod: e2e-apply-9655/deployment-55649fd747-glfcj
E1029 14:32:10.886002       1 pods.go:111] logical port e2e-apply-9655_deployment-55649fd747-glfcj not found in cache
E1029 14:32:10.886876       1 pods.go:116] could not find logicalSwitch  - object not found
```
@trozet

pods: don't try to delete unscheduled pods

---

go-controller/pkg/ovn/controller/services/repair.go

Fix panic on nil NB client deleting legacy LBs

---

go-controller/pkg/libovsdb/libovsdb.go

Add default 10s timeout for monitor command

---

go-controller/pkg/libovsdb/libovsdb.go

Only monitor speicfic tables for sbdb

---

go-controller/pkg/ovn/controller/services/services_controller.go

Just migrates the log to a debug level log. If an endpointSlice is
missing the service label, we will just pick it up when the label gets
added.
Otherwise we see errors in downstream CI like:
E1102 14:20:20.841452       1 services_controller.go:442] couldn't get key for EndpointSlice &EndpointSlice{ObjectMeta:{e2e-example-ingcgwqs e2e-example-ing e2e-endpointslice-4466  f502f416-1595-482d-ab89-a67196ea0734 52504 1 2021-11-02 14:20:20 +0000 UTC <nil> <nil> map[special-label:e2e-endpointslice-4466] map[] [] []  [{openshift-tests Update discovery.k8s.io/v1 2021-11-02 14:20:20 +0000 UTC FieldsV1 {"f:addressType":{},"f:endpoints":{},"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}}} }]},Endpoints:[]Endpoint{Endpoint{Addresses:[1.2.3.4 …

Dont log errors for endpointSlices missing services

---

go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_test.go

remove the last of the code that calls util.RunOVNNbctl() from
egressip.go in favor of libovsdb.

[libovsdb] remove calls to RunOVNbctl from egressip.go

---

go-controller/go.mod
go-controller/go.sum
go-controller/pkg/ovn/libovsdbops/transact.go
go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go
go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go
go-controller/vendor/modules.txt

Bumps libovsdb to include some reconnect fixes, as well as adds retry handling in ovnkube.

Fix libovsdb reconnection logic

---

go-controller/pkg/ovn/controller/services/repair.go
go-controller/pkg/ovn/egressfirewall.go
go-controller/pkg/ovn/libovsdbops/acl.go

* On most ocassions not finding egress firewall ACLs should not be an
error on itself.
* Use UUID when possible.

Improve ACL egress firewall nbdb ops

---

go-controller/pkg/ovn/egressfirewall_dns.go
go-controller/pkg/ovn/libovsdbops/transact.go
go-controller/pkg/util/dns.go

We can't mix v1 and v2 otherwise some log messages just don't show up.
@trozet

logging: make sure we use klog v2

---

go-controller/pkg/ovn/egressfirewall.go
go-controller/pkg/ovn/egressfirewall_test.go
go-controller/pkg/ovn/libovsdbops/acl.go

Fix find ACLs by priority

---

go-controller/pkg/ovn/egressgw.go
go-controller/pkg/ovn/egressgw_test.go

When disableSNATMultipleGWs=true, per pod SNATs are added for normal pods and for the
served pods, these snats are deleted. This SNAT deletion wasn't working because we
were passing the podIP/hostsubnetcidrmask instead of the expected podIP/32 which is
done during the snat addition. Hence the right nats were not getting matched and
thus stale nat entries were left behind in the GWR + external gateway tests were
failing since they expected the traffic from the served pods to not be snated.
We are seeing CI failures where in the external gateway e2e tests, the containers are unable to reach the src pods:
```
[It] TCP ipv4 …
```

NATs not getting deleted on GWR

---

go-controller/pkg/libovsdb/libovsdb.go
go-controller/pkg/ovn/egressfirewall.go
go-controller/pkg/ovn/libovsdbops/acl.go
go-controller/pkg/ovn/libovsdbops/loadbalancer.go
go-controller/pkg/ovn/libovsdbops/portgroup.go
go-controller/pkg/ovn/libovsdbops/switch.go

Minor documentation and spelling cleanup

---

go-controller/go.mod
go-controller/go.sum
go-controller/pkg/ovn/pods.go
go-controller/pkg/util/kube.go
go-controller/pkg/util/kube_test.go
go-controller/pkg/util/pod_annotation.go
go-controller/vendor/github.com/containernetworking/cni/libcni/api.go
go-controller/vendor/github.com/containernetworking/cni/libcni/conf.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/args.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/find.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/os_windows.go
go-controller/vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
go-controller/vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/cniconfig.go
go-controller/vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils/net-attach-def.go
go-controller/vendor/modules.txt

use APIs from k8snetworkplumbingwg's net-attach-def client library to
parse Pod's network annotation.

move to network plumbing wg's net-attach-def client library

---

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
go-controller/pkg/ovn/pods.go

With ovnkube-master start, we start up the node handler and then the pod
handler. When the pod sync is running, it attempts to pre-allocate all
of the already reserved IP addresses for pods. However, the IP
allocation in the sync depends on the logical switch manager being setup
for the node via the node add handler. There is no guarantee that the
node has been added by the time we pod sync, and thus we may up in a
situation where IP reservation for a pod in sync fails, and another pod
ends up getting that IP in a subsequent pod add event.
This commit adds a wait to ensure the node is in the cache before we try
to sync the pod and reserve its IP.

Fixes race between node handler and pod sync

---

dist/images/Dockerfile.fedora

Signed-off-by: Numan Siddique <nusiddiq@redhat.com>

fedora: Bump ovn version to 21.09.0-4.

---

go-controller/pkg/ovndbmanager/ovndbmanager.go

Adds support for upgrading db schema in HA and noHA deployments.

ovn-dbchecker: upgrade DB schema

---

go-controller/pkg/node/gateway_iptables.go

Just irritating wrong words order I found while was testing https://github.com/ovn-org/ovn-kubernetes/issues/2700

Fix iptables log

---

go-controller/pkg/metrics/metrics.go

@girishmg Can you take a look at this since you implemented the initial split between OVN metrics and other metrics? Thanks,

Register OVN components metrics with OVN Prometheus registery

---

go-controller/pkg/ovn/egressgw.go
go-controller/pkg/ovn/egressgw_test.go

Previously during sync we would remove a legacy hybrid policy if we
found a pod ip belonging to a multiple exgw namespace and we would
delete one at a time. It was also confusing because this cleanup action
was done while building the sync caches.
Improve this by just deleting all legacy hybrid route policies
explicitly during sync. This will also cover removing dangling legacy
route policies for ips that no longer map to a pod.

Remove all legacy 501 hybrid route policies in sync

---

go-controller/go.mod
go-controller/go.sum
go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go
go-controller/vendor/github.com/ovn-org/libovsdb/server/database.go
go-controller/vendor/modules.txt

Bump libovsdb version to fix connection leak.

---

go-controller/pkg/metrics/ovn_db.go

Do not register OVN DB size metric if OVN DBs are
not found.
Downstream, we want to enable consumption of OVN Metrics using ovnkube node, but we do not want to mount OVN DBs for now. This PR only enables OVN DB size metric if its accessible and does not attempt to update this metric pointless if OVN DBs aren't available.

Metrics: Enable OVN DB size metric only if OVN DBs found

---

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go

Drop defer statement to make function reserveJoinLRPIPs more readable.

LogicalSwitchManager: Refactor reserveJoinLRPIPs

---

go-controller/Makefile

Fix bad example  for disabling optimizations

Makefile: Fix bad example  for disabling optimizations

---

dist/templates/ovn-setup.yaml.j2
go-controller/pkg/kube/kube.go
go-controller/pkg/kube/mocks/Interface.go
go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_test.go
go-controller/pkg/ovn/ovn.go
go-controller/pkg/util/cloudprivateipconfig_annotations.go

This fixes some problems found for the implementation and refactor made in https://github.com/ovn-org/ovn-kubernetes/pull/2691

EgressIP: miscellaneous fixes

---

README.md

The beginner slides + recording was not
fully public, make it so.

Add Public Links

---

go-controller/pkg/ovn/pods.go

In the normal delete case we have the port's UUID in the cache, so
use it when deleting to save a bit of work.
@jcaamano @trozet @tssurya @JacobTanenbaum

pods: delete ports by UUID if available

---

dist/images/Dockerfile.fedora

fedora: Bump OVN version to 21.12.0 and fedora version to 35.

---

go-controller/pkg/util/node_annotations.go

ParsedNodeEgressIPConfiguration.V[4|6].IP is used to [verify](https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/egressip.go#L1133) if an egress IP matches node IP to disable its [creation](https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/egressip.go#L1217).
It should be set to the node IP address instead of the value assigned from cloud egress CIDR config.
/cc @alexanderConstantinescu

Use node IP in ParsedNodeEgressIPConfiguration

---

go-controller/pkg/ovn/address_set/address_set.go
go-controller/pkg/ovn/address_set/address_set_test.go

Duplicates in addrsets

---

go-controller/pkg/libovsdbops/portgroup.go

@dcbw @trozet FYI simple fix..

fix error check in findPortGroup()

---

go-controller/pkg/ovn/address_set/address_set.go

use the correct ACL name in the ovsdb wait operation

---

go-controller/pkg/libovsdbops/model_client.go

simplify the buildOps() method for the NotFound case

---

go-controller/pkg/config/config.go

Do not print serviceaccount token in any of the ovn-k8s log

---

go-controller/pkg/ovn/gress_policy.go
go-controller/pkg/ovn/policy.go

Fixes dualstack clusterIPs for network policy svc handler

---

go-controller/pkg/node/healthcheck.go
go-controller/pkg/node/healthcheck_test.go

Fix cleaning VF representor ports

---

go-controller/pkg/ovn/pods.go

Add more debug logs to addLogicalPort

---

go-controller/pkg/ovn/policy.go

Missed a place where we should be returning an error so NP create will
be retried.

NP Retry: return error for ensureAddrSet

---

go-controller/pkg/ovn/ovn.go
go-controller/pkg/util/node_annotations.go

fix issues in adding gateway-chassis to router port code

---

go-controller/pkg/node/gateway_localnet_linux_test.go

Fix issue with stack traces for gateway localnet linux

---

.github/workflows/test.yml
test/e2e/e2e.go
test/e2e/util.go

Follow-up to https://github.com/ovn-org/ovn-kubernetes/pull/2702
We decided to break this up into 2 PRs:
The functional changes were implemented with:  https://github.com/ovn-org/ovn-kubernetes/pull/2759
This PR here implements the e2e tests 

Issue2700 e2e

---

go-controller/pkg/ovn/pods.go

When iterating through nodes, it is necessary to account
for clusters where not all nodes are running ovn-kubernetes.

pods: Support hybrid clusters by skipping non-ovnk nodes

---

contrib/kind.yaml.j2
go-controller/pkg/ovn/ovn.go

Fix some rebase glitches

---

.github/actions/retest-action/entrypoint.sh
.github/workflows/test.yml

Github just released the rerun failed jobs feature that we have been waiting for:
* https://github.com/actions/runner/issues/432
* https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs
That makes my recent changes with caching seem a bit of overkill.
Roll back those changes and instead introduce a "retest-failed" command.
Keep the master and PR image cache as both are dependencies for the other jobs (so we can save some time and computing).
Also relay error messages to the end user should they occur - for an example of so far missed error messages, see 
https://github.com/ovn-org/ovn-kubernetes/runs/5542811058?check_suite_focus=true
~~~
+ RERUN_URL=https://api.github.com/repos/ovn-org/ovn-kubernetes/actions/runs/1722835047/rerun
+ curl --request POST …

Retest failed command improvements and /retest-failed action

---

go-controller/pkg/ovn/policy.go

If destroyNetworkPolicy() fails, we'd need to rollback so that the
reference count of lspIngressDenyCache/lspEgressDenyCache won't be
decremented twice when deletion of the policy is retried.

policy deletion retry could results in incorrect default deny portgroups

---

go-controller/hack/lint.sh

update the linter used for local testing so it matches the ci version

---

.github/workflows/test.yml
go-controller/pkg/node/gateway.go
go-controller/pkg/node/gateway_init.go
go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/gateway_localnet.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/ovn/gateway_init.go

Fixes a libovsdb regression where secondary bridges no longer worked, as well as adds back the CI jobs to test it.

Fix secondary bridge

---

go-controller/pkg/ovn/policy.go

deleteNetworkPolicy() can be called when addNetworkPolicy() fails. In
that case, the policy is not yet added into the nsInfo.networkPolicies
map. The current isLastPolicyInNamespace check in deleteNetworkPolicy()
needs to be fixed in order to delete the default deny port group
correctly.

incorrect last-policy check when network policy is deleted

---

go-controller/pkg/ovn/master.go

Thanks to @tssurya for thinking of this!

Fixes adding nohostsubnets nodes (i.e. windows)

---

.github/workflows/test.yml

Use explicit include list for test cases of E2E matrix

---

go-controller/pkg/metrics/master.go
go-controller/pkg/ovn/obj_retry.go

See commits. 
* Fix recent regression introduced - see f8f3661f5b1b742a3d01016f0bccdcef6ef47507
* Improve CPU usage/memory used - see 141da2c28857828f69f25b67b7dd154b7e3a7d94, 6e062f459d6b78ae7036de1f2daac9ad9933dfcf

Fix pod recorder and improve it

---

go-controller/pkg/ovn/egressip.go

This commit ensures invalid or unassigned egress ip entry is also
removed from cloudprivateipconfig when egressip resource is
deleted.

Delete invalid egress ip from cloudprivateipconfig

---

test/e2e/e2e.go

Forgot to add "fetching egressIP action"
within the retry mechanism which was causing
flakes in CI
Co-Authored-By: Patryk Diak <pdiak@redhat.com>

test flake: Fix e2e for egressIPs

---

go-controller/pkg/ovn/egressqos.go

No need to log this, should have been removed in
https://github.com/ovn-org/ovn-kubernetes/pull/2958/commits/523d88c5027cd1acd9820ca17165e53cdf4f0a9a

Reduce EgressQoS logs

---

docs/egress-qos.md

Adding some documentation that covers some examples
for the EgressQoS feature and how it affects
the northbound database.

Add EgressQoS documentation

---

go-controller/pkg/factory/factory.go
go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_test.go
go-controller/pkg/ovn/obj_retry.go
go-controller/pkg/ovn/ovn.go

enable retry to egress ip resources

Add retry logic to EgressIP resources

---

go-controller/pkg/libovsdbops/model.go
go-controller/pkg/ovn/egressgw_test.go

When creating multiple logical_router_policy simultaneously we sometimes see duplicate entries in the db (4 501's instead of 3).
```
ovn-nbctl lr-policy-list ovn_cluster_router
Routing Policies
1004 inport == "rtos-ovn-control-plane" && ip4.dst == 172.18.0.3 /* ovn-control-plane */         reroute                10.244.0.2
1004 inport == "rtos-ovn-worker" && ip4.dst == 172.18.0.5 /* ovn-worker */         reroute                10.244.2.2
1004 inport == "rtos-ovn-worker2" && ip4.dst == 172.18.0.4 /* ovn-worker2 */         reroute                10.244.1.2
501 inport == "rtos-ovn-control-plane" && ip4.src == $a6560308499851631376 && ip4.dst != 10.244.0.0/16         reroute                100.64.0.2
501 inport == "rtos-ovn-control-plane" && …
```

Add wait for logical router policies

---

go-controller/go.mod
go-controller/go.sum
go-controller/pkg/libovsdbops/acl.go
go-controller/pkg/ovn/egressfirewall.go
go-controller/pkg/ovn/egressfirewall_test.go
go-controller/pkg/ovn/namespace.go
go-controller/pkg/ovn/ovn.go
go-controller/pkg/ovn/policy.go
go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go
go-controller/vendor/modules.txt
test/e2e/acl_logging.go
test/e2e/multicast.go
test/e2e/util.go

Extend ACL logging to EgressFirewall objects.

EgressFirewall: Enable OVN-Kubernetes logging for egress firewall

---

go-controller/pkg/ovn/pods_test.go

fix make check error

---

go-controller/pkg/ovn/egressip.go

This is a continuation of PR #2946 which is unfortunately not complete in
fixing removal of invalid egress ip from cloud private ip config.
This PR completes it by ensuring node name is added into EgressIPStatusItem
so that executeCloudPrivateIPConfigOps removes the egress ip from cloud
config store even though assignment didn't actually happen on the node.

Add node name into egress ip status for the removal

---

go-controller/pkg/ovndbmanager/ovndbmanager.go

We've seen instances where the migration initially failed because the db
wasn't ready yet. This change adds some retrying to the migration to
handle that situation more gracefully and efficient, as failing this a
couple of times currently results in getting the pod into crashlooop
backoff.
A sample transient error for initial failures looks like e.G. this:
```
F0511 04:31:57.928725       1 ovndbmanager.go:44] NBDB Upgrade failed: %!w(*fmt.wrapError=&{failed to get schema version for NBDB, stderr: "ovsdb-client: transaction returned error: {\"details\":\"get_schema request specifies database OVN_Northbound which is not yet available because it has not completed joining its cluster\",\"error\":\"database not available\"}\n", error: OVN command '/usr/bin/ovsdb-client -t 10 get-schema-version …
```

OVNDBManager: Retry migrations

---

go-controller/pkg/ovn/policy.go

Direction of the ACLs built for multicast egress policy was always
"from-lport", so we cannot determine if we need to update egress ACL
direction based on the first egress ACL that found.

update all egress ACLs' direction to "from-lport"

---

go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/obj_retry.go

Fixes panic seen during `checkEgressNodesReachability`
```
E0606 11:57:34.063567       1 egressip.go:2096] Node:
huirwang-0606c-m5w24-worker-2-dkjmc reachability changed, but could not
retrieve node from cache, err: node
"huirwang-0606c-m5w24-worker-2-dkjmc" not found
W0606 11:57:34.063658       1 egressip.go:1657] Unable to remove GARP
configuration on external logical switch port for egress node:
huirwang-0606c-m5w24-worker-2-dkjmc, err: object not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x176626d]
goroutine 487 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).checkEgressNodesReachability(0xc000171c00) …
```

egressIP: node retrieval failure is not respected, causes panic

---

docs/metrics.md

This will aid consumers if they want to understand
if a metric is removed/changed or is possibly broken.
/cc @npinaeva

Metrics: init metric change log documentation

---

go-controller/cmd/ovnkube/ovnkube.go
go-controller/pkg/ovn/master.go

When the elected master pod is forced to exit, release
leader election lock so other ovnkube-master can become
the new leader.

Release Leader election lock on errors

---

go-controller/hybrid-overlay/pkg/controller/node_linux.go
go-controller/hybrid-overlay/pkg/controller/node_linux_test.go

correcting two issues introduced in past merges that renders the hybrid overlay not usable. 
A comma was left out of a flow causing the node to fail to add all the flows for hybrid overlay and making sure that an annotation gets read.  

General hybrid overlay fixes

---

test/e2e/external_gateways.go

e2e: Fix checking of mac entries embedded in conntrack labels.

---

dist/images/Dockerfile.fedora

fedora Dockerfile : Update OVN to 22.06.

---

go-controller/pkg/ovn/policy.go
go-controller/pkg/ovn/policy_test.go

We weren't removing reference of ACL from PG before deleting
it. Unfortuntely unit tests don't catch this.

syncNetworkPolicies: Remove ACLs from PGs before deleting

---

go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/gateway_localnet_linux_test.go
go-controller/pkg/node/healthcheck_test.go
go-controller/pkg/node/management-port_dpu_test.go
go-controller/pkg/node/management-port_linux_test.go
go-controller/pkg/node/management-port_test.go
go-controller/pkg/node/node_test.go
go-controller/pkg/node/port_claim_test.go

This PR adds error checking to the unit tests in the node package; currently
plenty of tests had instructions where the returning error was not checked.
Run unit tests.
Added error checking to the the `pkg/node` pkg unit tests when appropriate.

node tests: add missing error checking

---

dist/images/daemonset.sh
go-controller/hack/build-go.sh

Parametrize the golang version used to build the ovn-k code.
Also fix the installation of j2cli for zsh based shells on the e2e tests.

Parametrized golang

---

go-controller/pkg/node/gateway_shared_intf.go

When service is deleted, we were removing the conntrack
entries before removing the flows/iptable rules. It's
safer to do the reverse so that in the nano second interim
the conntrack entries don't get recreated before the rules/flows
get deleted.

Remove conntrack entries after rules

---

go-controller/pkg/ovn/egressip_test.go

... because of unexpected startup failure.
Add some error checks.
If you run this test without adding cluster router `WatchEgressNodes` will complain about that.

Fix egressip test that skips populating egress node data

---

go-controller/pkg/util/ovn.go

Enable CNCC in OVNK

---

go-controller/pkg/ovn/master.go

trivial: add missing argument to klog.Errorf

---

go-controller/pkg/ovn/obj_retry.go

When object is in a terminal state we want to remove it, it is most likely to happen with an update event.
If we get the object from cache during this scenario the object might no longer exist causing us to exit without performing the removal.
This was seen during verification of a bug, the pod logical port did not get removed during update because the cache entry no longer exists and delete was ignored:
```
2022-07-11T06:08:19.254219737Z I0711 06:08:19.254168       1 obj_retry.go:1276] Detected object test/hello-pod of type *factory.egressIPPod in terminal state (e.g. completed) during update event: will remove it
2022-07-11T06:08:19.266628736Z W0711 06:08:19.266585       1 obj_retry.go:1401] Unable to get *v1.Pod test/hello-pod from informer cache (perhaps it was already deleted?), …
```

On update,  delete objects in terminal state that no longer exist in the informer cache

---

go-controller/pkg/factory/factory.go
go-controller/pkg/factory/factory_test.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/healthcheck.go
go-controller/pkg/node/node.go

@Pardhakeswar , @girishmg  PTAL
When reviewing https://github.com/ovn-org/ovn-kubernetes/pull/3056, I made a silly mistake and actually left all comments in "pending" state. This is a followup with the changes I had in mind. 
Thanks!

Followup to EndpointSlices PR for ovn-k node

---

go-controller/pkg/ovn/master.go
go-controller/pkg/ovn/master_test.go

As the community decided to not add any DB client to the node, this patch uses 'ovn-sbctl' to do the same job.
In the DPU 2-clusters design, a host with DPU will join the cluster
with ovn-controller running in the host first, then it will be moved
to the DPU. Therefore, we will have 2 chassis with the same hostname
in the ovn sbdb.
With this patch, the master will try to remove the stale chassis when
the Chassis ID is inconsistent with the value of  node annotation
'k8s.ovn.org/node-chassis-id'.
This is to fix #3026.

Remove stale chassis for hosts that run ovnkube-node on DPU

---

dist/images/Dockerfile.fedora
dist/images/Dockerfile.fedora.dev

fedora Dockerfile : Switch to f36 and OVN 22.06.

---

go-controller/pkg/ovn/policy.go

policy: fix log message and clarify comment

---

test/e2e/e2e.go

These tests run checkContinuousConnectivity in a goroutine and wait on the podChan to continue. The problem is that if the goroutine fails to create a pod it sends a msg to the errChan and exits, making the test hang indefinitely until the global timeout kicks in (3hrs).
Fixing checkContinuousConnectivity to send a nil to the errChan if the pod was created successfully, and the callers to wait for that nil before trying to get the pod.
https://github.com/ovn-org/ovn-kubernetes/runs/8228933899?check_suite_focus=true

E2E: fix tests stuck waiting on a channel

---

test/e2e/service.go

The `err` variable was not being set to the result of the endpoint generation, 
which meant that if - for whatever reason - creating those endpoints failed, 
the test would continue and fail further down the execution.

e2e tests, services: assert endpoints were created

---

go-controller/pkg/factory/factory.go
go-controller/pkg/ovn/namespace.go
go-controller/pkg/ovn/obj_retry.go
go-controller/pkg/ovn/ovn.go

Add retry logic to Namespace resources

---

go-controller/pkg/ovn/address_set/address_set.go

EnsureAddressSet may be called by multiple go threads around the same time.
While transactions are serialized, the operations that populate the transactions
are not and that is where the determination on whether a row in ovsdb is to
be created or updated via libovsdbops. The result of that is that the creation
fails due to the constraints on the table index.
This change is a placebo. It just adds a comment since a higher level retry
logic is expected to succeed on the following invocation.
Co-authored-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
Reported-at: https://bugzilla.redhat.com/show_bug.cgi?id=2108026

newOvnAddressSet: log mid-air collisions

---

go-controller/pkg/ovn/policy.go

NetworkPolicyNotCreated error only returned from
updateACLLoggingForPolicy when network policy that is passed as an argument have np.created = false.
updateACLLoggingForPolicy called from 2 places:
func (oc *Controller) setNetworkPolicyACLLoggingForNamespace(ns string, 
nsInfo *namespaceInfo) error {
...
for name, policy := range nsInfo.networkPolicies { }
...
}
func (oc *Controller) addNetworkPolicy(policy *knet.NetworkPolicy) error {
...
if err := oc.createNetworkPolicy(np, policy, aclLogDeny,
aclLogAllow,portGroupIngressDenyName, portGroupEgressDenyName);
...
nsInfo.networkPolicies[policy.Name] = np
if err := oc.updateACLLoggingForPolicy(np, nsInfo.aclLogging.Allow);
err != nil {
...
}
np.created is set to true in createNetworkPolicy,
and createNetworkPolicy is only called from …

remove networkPolicy.created field

---

test/e2e/external_gateways.go

In environments where PodSecurity is enforced we can't use the default ns unless certain labels are set. Namespaces we create with the framework have these labels which let us create pods on them without restrictions. Since we're using disposable namespaces that are deleted in AfterEach there is no longer need to delete the gw pods.

E2E (exgw): create ns for the serving gw pods instead of using default

---

test/e2e/external_gateways.go

The `checkPingOnContainer` function is duplicated in the tests. 
It also returns a redundant error, since it is both:
- already asserted within the function
- not checked by the caller. 
Thus, we can safely update the function's signature, removing its return
parameters.

e2e, external gw test: remove duplicate funcs

---

docs/design/dpu_support.md
docs/ovs_offload.md

- Add design doc which depicts the current implementation
in OVN-Kubernetes
- Add DPU section in ovs_offload docs
Note:
Currently only a general overview is provided
in the in-project documents plus links to google doc.
This is a first stage to have some initial documentation
in the project. Later on these docs should be converted
to Markdown and be part of the project.

Add DPU support documentation

---

go-controller/pkg/ovn/obj_retry.go

fix duplicate case value

---

go-controller/pkg/ovn/egressfirewall_dns_test.go

Fix flakiness in DNS tests

---

go-controller/pkg/factory/factory.go

Add endpointSlice informer in master process

---

go-controller/pkg/ovn/egressgw_test.go

Ensure error checking on the egress GW unit tests.
Ensure all calls that throw errors succeed.

Check errors egressgw tests

---

go-controller/pkg/ovn/policy.go
go-controller/pkg/ovn/policy_test.go

Initially when the commit to cleanup ACLs was done in https://github.com/ovn-org/ovn-kubernetes/pull/3038 I had assumed that ACL names weren't truncated to fit the 63 char length and thought they were like other fields. Based on that assumption there were two places in code where I used a predicate match based on acl names which was plain stupidity. This PR fixes that:
1) When the arp && arp || nd bug was being cleaned up, I was trying to be extra careful in matching on old exp: "arp" and the acl name. I deleted the second part of that logic since there can be cases where the entire suffix is missing like when the namespace is 63 chars. So let us stick to matching on acl.Match alone
2) When the deny default ACL duplicates per namespace were being updated - again I was matching on ACL …

Don't use ACL names ever!

---

dist/templates/ovnkube-master.yaml.j2
test/e2e/e2e.go
test/e2e/util.go
test/scripts/e2e-cp.sh

Legacy health check test is skipped for now as it takes ~10mins to do two sequenced rollouts of both ovnkube-node and ovnkube-master which is high price to pay for a non-default unlikely used option.
@flavio-fernandes @kyrtapz WDYT?

Add e2e tests for egressIP health check

---

dist/images/Dockerfile.fedora

fedora Dockerfile:  Use OVN 22.09.

---

go-controller/hybrid-overlay/pkg/controller/overlay_windows.go
go-controller/pkg/config/config.go
go-controller/pkg/crd/egressfirewall/v1/apis/clientset/versioned/fake/register.go
go-controller/pkg/crd/egressfirewall/v1/apis/clientset/versioned/scheme/register.go
go-controller/pkg/crd/egressip/v1/apis/clientset/versioned/fake/register.go
go-controller/pkg/crd/egressip/v1/apis/clientset/versioned/scheme/register.go
go-controller/pkg/crd/egressqos/v1/apis/clientset/versioned/fake/register.go
go-controller/pkg/crd/egressqos/v1/apis/clientset/versioned/scheme/register.go
go-controller/pkg/libovsdbops/model_client.go
go-controller/pkg/metrics/master.go
go-controller/pkg/metrics/ovn.go
go-controller/pkg/metrics/ovs.go
go-controller/pkg/node/gateway_iptables.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/helper_linux.go
go-controller/pkg/node/management-port_linux.go
go-controller/pkg/node/node_dpu.go
go-controller/pkg/node/port_claim.go
go-controller/pkg/ovn/controller/services/repair.go
go-controller/pkg/ovn/egressfirewall_dns.go
go-controller/pkg/ovn/egressfirewall_test.go
go-controller/pkg/ovn/ipallocator/allocator.go
go-controller/pkg/ovn/loadbalancer/loadbalancer.go
go-controller/pkg/ovn/ovn.go
go-controller/pkg/ovn/policy.go
go-controller/pkg/testing/libovsdb/matchers.go

No code change, only comment indentations and fixes.

Update comment formatting for Go 1.19

---

README.md
docs/egress-service.md

* Adding egress service docs that explain how they work + usage example
* Adding missing EgressQoS entry to the features list in the README

DOCS: Add Egress Service docs

---

go-controller/cmd/ovnkube-trace/ovnkube-trace.go

Reported-at: https://issues.redhat.com/browse/SDN-3573

ovnkube-trace: Fix ofproto/trace for IPv6

---

go-controller/pkg/factory/factory_test.go

This commit fixes the async random updates that
were been sent and instead does the updates
in a more ordered fashion that mimics the
k8s event driven env.

Fix priority handler factory unit test

---

go-controller/cmd/ovnkube-trace/ovnkube-trace.go

Fix issues raised by golint -min_confidence 0.8 for ovnkube-trace.

ovnkube-trace: Fix some linter issues

---

go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/healthcheck.go
go-controller/pkg/node/node.go

Ignore non-ready endpoints when processing endpointslices
In ovn-k node we introduced a regression when replacing endpoints with endpointslices, causing 10x higher disruption times in ingress-to-console/oauth/image-registry new connections in CI upgrade jobs, as reported in #OCPBUGS-1427
Previously we were processing Endpoints from `k8s.io/api/core/v1`, where we get the current list of _ready_ endpoint addresses from  `EndpointSubset.Addresses` and the list of non-ready addresses from `EndpointSubset.NotReadyAddresses`:  https://github.com/openshift/ovn-kubernetes/blob/da6ac5b78ff34d10201edbadb37e7b658b3ea991/go-controller/vendor/k8s.io/api/core/v1/types.go#L4711-L4724
However, endpointslices are defined differently and offer a more fine-grained view of each endpoint, reporting its status …

OCPBUGS-1427: Ignore non-ready endpoints when processing endpointslices

---

go-controller/pkg/ovn/namespace_test.go

- use new function to generate test objects
- init expectedNodeSwitch with node1.logicalSwitch() call, that will contain OtherConfig and LoadBalancerGroup fields that were added later in the previous version
- start ovn with node1 k8s object, since ls for this node is already in the db, no need to call Create for that node later
- remove additional second wait for expectedDatabaseState, since it was added to fix the ips mismatch problem, that can't be fixed by waiting longer
This *should* fix https://github.com/ovn-org/ovn-kubernetes/issues/3233. The issue is difficult to reproduce and catch, but it has similar setup as some  `master_test` tests, and those tests don't fail to get node annotations.
The main difference is starting ovn with …

Update namespace_test to match master_test changes

---

test/e2e/e2e.go

These tests simply kills the control plane pods to simulate the
reboot scenario.
This test does not really simulate the reboot, because:
1) Kind cluster's etcd stores data in-memory and it looses that data
after the reboot, so we skip deleting this pod.
2) Deleting the ovs-node pod will tear down the pod networking and
and the restart does not build it back, so we skip deleting this
pod as well.
this is work picked up from an old PR by Anil:
https://github.com/ovn-org/ovn-kubernetes/pull/1891

Add e2e test to simulate control plane node reboot

---

go-controller/pkg/retry/obj_retry.go

Hold lock when deleting completed pod during update event

---

go-controller/pkg/ovn/default_network_controller.go

close default controller stopchan first to stop all the goroutines

---

go-controller/pkg/metrics/master.go

Fix pod creation and OVN cli metric variable doc comments

---

go-controller/pkg/ovn/pods.go

Remove extra log format verb for add logical port latency

---

dist/images/Dockerfile.fedora

To get https://bugzilla.redhat.com/show_bug.cgi?id=2126083#c13

Bump OVN to 22.12

---

contrib/kind.sh

Restarting kind environment to reflect ovn kubernetes changes does not
take that much but sometimes apart from ovn-kubernetes something else is
deployed on top of it for testing so restarting means redeploying those
artifacts.
This change add "--deploy" option to kind script to prevent kind from
re-run and just deploy ovn-kubernetes. To ensure the images are reloaded
the ovn-kubernetes pods are deleted after manifests are deployed.
Alternative solutions does not work well:
- Use image digest at manifest does not work for "localhost" images
since it tries to contact the unexistent remote repository
- Updating the image with different tag does not work well with
ovnkube-db, the old pod does not get terminated when image is updated.
NOTE: …

kind: Add --deploy option to just install ovn-k

---

go-controller/pkg/ovn/egressip.go

Do not throw an error if the owner annotation if missing. Instead log it and return nil. Otherwise there's a big risk that the controller loops on the error for a very long time.
It makes no sense to throw an error upon deletion if the annotation is missing: the deleted object will not get the annotation any more. It makes no sense to throw an error upon add if the annotation is missing: if this is a new object then the there will be an update action when the object is updated so we should retrieve the annotation on update.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-4500

CloudPrivateIPConfig reconcile: don't throw err on missing annotation

---

go-controller/pkg/cni/helper_linux.go
go-controller/pkg/node/node_dpu_test.go

fix error adding external_ids:vf-netdev-name

---

go-controller/pkg/ovn/pods.go

we need to ensure that we only call allocateHybridOverlayDRIP() in syncPods() when there is an existing hybrid overlay distributed router ip address on the node.
the initial allocation of the hybrid overlay distributed router ip should be made during the call to allocateHybridOverlayDRIP() during the addUpdateNodeEvent(). The call to allocateHybridOverlayDRIP() is in syncPods() to ensure that on restart the annotated hybrid overlay distributed router ip is allocated before processing pod events so it is reserved. without the check for the presence of the annotation there is a good chance that the syncPods() will call allocateHybridOverlayDRIP() with a stale node object and cause a reallocation of the hybrid overlay distributed router ip without changing associated the MAC address or …

fix race condition in hybrid overlay DRIP alloc

---

go-controller/hybrid-overlay/pkg/controller/node.go
go-controller/hybrid-overlay/pkg/controller/node_linux.go
go-controller/hybrid-overlay/pkg/controller/node_linux_test.go

built on top of PR https://github.com/ovn-org/ovn-kubernetes/pull/3293
this PR makes the hybrid overlay node code responsive to changes to the DRMAC and DRIP annotations. Thsese changes are built on the mocking of the hybrid overlay test code to correctly test that the changes take place.

make hybrid overlay node code responsive to change 

---

contrib/kind.sh

This is mainly useful for testing out clusters with no default gateway. In this case the behavior of host->services changes and previously there was no easy way to launch a cluster like this and test it.
When deploying with --isolated:
1. default gw routes are removed on every node when kind is deployed
2. static DNS hostname entries are added to every node
3. ovnkube-node is started with the gateway-interface specified

Enable isolated clusters with KIND

---

.github/workflows/test.yml
contrib/kind.sh
test/e2e/go.mod
test/e2e/go.sum
test/e2e/multihoming.go
test/scripts/e2e-cp.sh

This PR adds e2e tests for the multi-homing routed topology feature; it asserts a pod can have multiple OVN-K networks.
It adds the following tests:
- assert a pod w/ a routed secondary network can reach the `Ready` phase. 
- asserts 2 pods can communicate over a routed topology secondary network.
These tests run in a separate lane, since it does require multus deployed. 
So far, we are only adding IPv4 tests; a follow up PR should expand this coverage by adding an IPv6 lane.
Follow-up PRs will add more e2e tests. Given the current code coverage of OVN-K multi-homing, we should also better unit test the secondary controllers, etc.
A new lane is introduced, where everything related to …

E2e multi homing l3 topology

---

go-controller/pkg/cni/types/types.go
go-controller/pkg/libovsdbops/switch.go
go-controller/pkg/network-controller-manager/network_controller_manager.go
go-controller/pkg/ovn/base_network_controller.go
go-controller/pkg/ovn/base_network_controller_pods.go
go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
go-controller/pkg/ovn/master.go
go-controller/pkg/ovn/secondary_layer2_network_controller.go
go-controller/pkg/ovn/topology_version.go
go-controller/pkg/types/const.go
go-controller/pkg/util/multi_network.go
go-controller/pkg/util/net.go
go-controller/pkg/util/net_unit_test.go

Add secondaryLayer2NetworkController to support secondary layer2 topology network.

support secondary network of layer2 topology

---

go-controller/pkg/util/multi_network.go
go-controller/pkg/util/multi_network_test.go

excludeSubnets in layer2 topology type NAD is optional

---

test/e2e/multihoming.go

This PR adds e2e tests for the multi-homing switched (layer2) topology feature; it asserts a pod can have multiple OVN-K networks of this particular topology.
It adds the following tests:
- assert a pod w/ a switched secondary network can reach the Ready phase.
- asserts 2 pods can communicate over a switched topology secondary network.
These tests run in a separate lane, since it does require multus deployed.
So far, we are only adding IPv4 tests; a follow up PR should expand this coverage by adding an IPv6 lane.
Follow-up PRs will add more e2e tests. Given the current code coverage of OVN-K multi-homing, we should also better unit test the secondary controllers, etc.
**- Description for …

E2e multi homing l2 topology

---

go-controller/pkg/metrics/metrics.go

Bundled with the pprof endpoint since enabling pprof (a) enables /debug and (b) indicates that you're OK with things that can reach ovnkube changing runtime settings (pprof and logging).
To change logging do something like:
`curl -X PUT --data="5" http://localhost:<metrics port>/debug/flags/v`

logging: allow changing log-level at runtime via the pprof /debug endpoint

---

.github/workflows/test.yml
docs/ci.md
go-controller/pkg/node/gateway.go
go-controller/pkg/node/gateway_init.go
go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/gateway_localnet.go
go-controller/pkg/node/gateway_localnet_linux_test.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/healthcheck.go
go-controller/pkg/node/node_ip_handler_linux.go
go-controller/pkg/node/node_ip_handler_linux_test.go
go-controller/pkg/ovn/default_network_controller.go
go-controller/pkg/util/node_annotations.go
test/e2e/node_ip_migration.go
test/e2e/util.go
test/scripts/e2e-cp.sh

Adjust ovnk configurations based on primary IP change:
- OVNK related node annotation
- OVN encap IP
- Egress IP
Co-authored-by: Andreas Karis <ak.karis@gmail.com>

Support dynamic node IP changes

---

go-controller/hybrid-overlay/pkg/controller/node_linux.go
go-controller/pkg/node/healthcheck.go
go-controller/pkg/node/node_dpu.go
go-controller/pkg/ovn/base_network_controller_pods.go
go-controller/pkg/ovn/base_network_controller_secondary.go
go-controller/pkg/ovn/egressgw.go
go-controller/pkg/ovn/egressqos.go
go-controller/pkg/ovn/namespace.go
go-controller/pkg/ovn/ovn.go
go-controller/pkg/ovn/pods.go
go-controller/pkg/util/kube.go
go-controller/pkg/util/multi_network.go
go-controller/pkg/util/pod_annotation.go

allow multiple NADs of the same network on a Pod

---

test/e2e/multihoming.go

This PR updates a traffic test in the multi-homing suite to ensure the workloads are deployed in different nodes.
This is paramount to ensure the cluster-wide logical switch via which we model the flat L2 topology works as expected when the OVN interconnect feature is introduced.
I've refactored the test suite a little bit, allowing for the network / pod configurations to be more easily extended in the future.
Run the suite.
Ensure a flat L2 traffic test deploys workloads in different nodes

Ensure a flat L2 traffic test deploys workloads in different nodes

---

test/e2e/multihoming.go

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
This PR adds a new e2e test asserting a pod can have multiple attachments to the same network.
The test shows the pod enters the ready state, and is able to get 2 IPs from the same subnet.
Test multiple attachments to the same secondary network.

multi-homing, e2e: multiple attachments to the same network

---

go-controller/pkg/ovn/gress_policy.go

Simple fix to not do 15 retries on something that is not going to succeed anyway
/cc @flavio-fernandes

Don't retry fetching pod ips on delete if it failed once.

---

dist/images/Dockerfile.fedora
dist/images/Dockerfile.fedora.dev

Mainly to pickup the latest fixes and the commit
7053ae6("lb: northd: Properly format IPv6 SB load balancer VIPs.")

Dockerfile.fedora: bump OVN to 22.12.0-25 and to fedora 37.

---

go-controller/pkg/ovn/hybrid_test.go
go-controller/pkg/ovn/master.go

with the ability to turn on and off hybrid overlay if the annotations for Hybrid overlay distributed router ip and mac addresses are left on the node if hybrid overlay is ever reenabled there is a possibility that those addresses where allocated to pods
tested with a unit test

correct cleanup of hybrid overlay annotations

---

go-controller/pkg/ovn/egressip.go

Anticipating openshift/cloud-network-config-controller#95 this allows support for operations when CloudPrivateIPConfig is moved from one node to another skipping the usual release-assign dance.
Without this commit new IP is only added to the EgressIP CRD status without deleting the old one, resulting in controller deleting the CloudPrivateIPConfig completely in the next iteration of reconclieEgressIP.
I extended the cases where CloudPrivateIP controller selects IPs to delete to include a case when `Status.Node` is different on old and new resource.
I verified it with OpenShift env running openshift/cloud-network-config-controller#95
Support …

EgressIPs: Allow moving IP

---

docs/multi-homing.md
go-controller/cmd/ovnkube/ovnkube.go
go-controller/pkg/cni/types/types.go
go-controller/pkg/network-controller-manager/network_controller_manager.go
go-controller/pkg/network-controller-manager/network_controller_manager_suite_test.go
go-controller/pkg/network-controller-manager/node_network_controller_manager.go
go-controller/pkg/network-controller-manager/node_network_controller_manager_test.go
go-controller/pkg/node/base_node_network_controller_dpu.go
go-controller/pkg/node/base_node_network_controller_dpu_test.go
go-controller/pkg/node/default_node_network_controller.go
go-controller/pkg/node/default_node_network_controller_test.go
go-controller/pkg/node/gateway_init.go
go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/healthcheck.go
go-controller/pkg/node/obj_retry_node.go
go-controller/pkg/node/ovn_test.go
go-controller/pkg/node/secondary_node_network_controller.go
go-controller/pkg/ovn/base_network_controller.go
go-controller/pkg/ovn/base_network_controller_pods.go
go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
go-controller/pkg/ovn/default_network_controller.go
go-controller/pkg/ovn/secondary_layer2_network_controller.go
go-controller/pkg/ovn/secondary_layer3_network_controller.go
go-controller/pkg/ovn/secondary_localnet_network_controller.go
go-controller/pkg/types/const.go
go-controller/pkg/util/multi_network.go
go-controller/pkg/util/ovn.go

support secondary network of localnet topology

---

docs/multi-homing.md

This PR provides a detailed explanation of each available attribute for layer2/layer3 topologies.
It also clarifies that the secondary networks constructs are **not** namespaced.

Improve multi homing  user documentation

---

test/e2e/multihoming.go

Add tests ensuring a pod comes up when it is attaching to an IPv6 subnet, and that pods can communicate over an IPv6 subnet.
Run the e2e tests.

Multi homing e2e tests ipv6

---

test/e2e/multihoming.go

The e2e test didn't actually check the pod assigned IPs were not within
the excluded range: this commit adds this check.
Run the e2e tests.

e2e, multi-homing: ensure assigned IPs are not within the excluded range

---

go-controller/pkg/ovn/base_network_controller.go
test/e2e/multihoming.go

add e2e multihoming tests for localnet network

---

go-controller/pkg/cni/cni.go
go-controller/pkg/cni/helper_linux.go
go-controller/pkg/cni/utils.go
go-controller/pkg/cni/utils_test.go
go-controller/pkg/node/base_node_network_controller_dpu_test.go
test/e2e/static_pods.go

fixes https://issues.redhat.com/browse/OCPBUGS-5042

Static pod creation

---

dist/images/Dockerfile.fedora

fedora: Update OVN to latest release - 23.03.0.

---

go-controller/pkg/metrics/metrics.go

Emit logs when metrics servers start and stop.

---

go-controller/pkg/factory/handler.go

When a handler is added to an informer we must deliver to it
all existing objects of its type to match the Shared Informer
behavior.
For queued informers we spread the adds out over an array of
initial-add-specific queues, so that we don't dump a whole set
of objects into the queues that other informers are also
receiving events from; only the handler being added should
get this set of initial objects.
Unfortunately the initial add logic to spread objects across
the initial-add-specific queues took its data from the regular
queues, which caused initial add queues to become unbalanced
when the regular queues were processing lots of objects.
To fix that, abstract queue management out into a queueMap
struct and use that same struct for both regular event
delivery and the initial add event …

factory: use same queue balancing logic for initial adds

---

go-controller/cmd/ovnkube/ovnkube.go

~~/hold
testing~~
Test complete

Start master metrics server for all master instances

---

go-controller/cmd/ovnkube/ovnkube.go

On goroutine panic, defers are executed. If we wait there for something
that will never happen, we prevent the process to fully crash. Make sure
we cancel the context before waiting.

Defer wait on startOvnKube might prevent panic crash

---

go-controller/pkg/node/node_ip_handler_linux.go

In the case of the DPU, only the local IPs on the infra cluster will be added to the IP manager, while `util.GetNodePrimaryIP(node)` returns the IP of the host on the tenant cluster. To avoid changing the remote IPs for geneve tunnels,only allow to update the OVN encap IP when the IP that has just been detected is contained in the addresses that were already added to the IP manager. This fixes a bug described by https://issues.redhat.com/browse/NHE-519 where all the flows that are between different nodes in a cluster are broken due to the dynamic handling of IPs.
While tackling that, also remove some duplicate code from node ip handler.

Only update IP addresses if they are locally available

---

go-controller/pkg/node/gateway_iptables.go

The rules that are created on init should be appended instead of inserted as they are "lowest priority".
More specifically, if they are inserted before EGRESS-SVC it breaks because its rules are never evaluated - this may happen if the init rules do not exist but the jump to EGRESS-SVC does (e.g when moving from shared to local mode).

lgw: append init rules instead insert

---

go-controller/pkg/libovsdb/libovsdb.go

When the cert/key files got removed during cert/key update,
With current code, libovsdb will only works for once with first remove event.
To fix this issue, watcher need remove the old file and add new file
back to watcher.

ovnkube-master pod failed to reconnect to ovn db due to ssl expire

---

go-controller/pkg/cryptorand/cryptorand.go
go-controller/pkg/factory/handler.go
go-controller/pkg/libovsdbops/named_uuid.go
go-controller/pkg/ovn/ipallocator/allocator/bitmap.go
go-controller/pkg/testing/libovsdb/libovsdb.go

Move from math/rand to crypto/rand package for random numbers generation

---

go-controller/pkg/libovsdb/libovsdb.go
go-controller/pkg/libovsdbops/loadbalancer.go
go-controller/pkg/libovsdbops/model.go
go-controller/pkg/ovn/controller/services/loadbalancer.go

Revert predicate search optimization
3369d387417ede05033c002b782b0279b201ea76 as predicate search should not bee needed anymore

Use loadbalancer.Name as client index

---

go-controller/pkg/cni/cni.go
go-controller/pkg/cni/cni_dpu.go
go-controller/pkg/cni/helper_linux.go
go-controller/pkg/node/base_node_network_controller_dpu.go
go-controller/pkg/node/base_node_network_controller_dpu_test.go
go-controller/pkg/node/default_node_network_controller.go
go-controller/pkg/node/secondary_node_network_controller.go
go-controller/pkg/util/dpu_annotations.go
go-controller/pkg/util/ovs.go
go-controller/pkg/util/util.go

fix OVS configuration issues in the DPU mode 

---

go-controller/pkg/util/dns.go

If the DNS resolution is too big for the buffer (512) the message and returned addresses are truncated.
Change the EgressFirewall DNS to fall back onto TCP if the message is truncated. if for some reason the TCP fails continue using the truncated list of IPs

if egressfirewall DNS result is truncated fall back to TCP

---

go-controller/pkg/ovn/gateway_init.go

If a pod is in completed state or it is not scheduled we should not try to get its ip

Check if the status of a pod before trying to get its ip

---

CODEOWNERS

Will allow us to require 1 approval from committers before merge.

Adds code owners

---

docs/multi-homing.md

This PR introduces minimal user documentation for multi-network policies.

docs, multi-net policy: provide user documentation

---

docs/multi-homing.md

Document IPAM-less multi-net policy restrictions (it can only employ `ipBlock` peers).

docs, multi-homing, policy: document IPAM-less policies restrictions

---

go-controller/pkg/ovn/base_network_controller_namespace.go
go-controller/pkg/ovn/base_network_controller_secondary.go
go-controller/pkg/ovn/namespace.go

Trying to improve cpu consumption

Extract all namespace pod ips only when creating nsInfo

---

go-controller/pkg/ovn/gateway_init.go

In CI we are observing:
```
E0531 19:52:52.309098       1 obj_retry.go:627] Failed to update *v1.Node, old=ip-10-0-133-36.ec2.internal, new=ip-10-0-133-36.ec2.internal, error: error creating gateway for node ip-10-0-133-36.ec2.internal: failed to init shared interface gateway: failed to sync stale SNATs on node ip-10-0-133-36.ec2.internal: unable to fetch podIPs for pod openshift-multus/network-metrics-daemon-cr75v: pod openshift-multus/network-metrics-daemon-cr75v: no pod IPs found
I0531 19:52:52.309185       1 event.go:285] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"ip-10-0-133-36.ec2.internal", UID:"65797716-b2a8-43fc-a216-8154fecee781", APIVersion:"v1", ResourceVersion:"203498", FieldPath:""}): type: 'Warning' reason: 'ErrorUpdatingResource' error creating gateway for …
```

Fix cleanupStalePodSNATs if no podIPs are found

---

docs/metrics.md
go-controller/pkg/metrics/cluster_manager.go
go-controller/pkg/metrics/master.go

This is the metrics refactor for interconnect for the egressIP feature
following the work done in https://github.com/ovn-org/ovn-kubernetes/pull/3386.

EIP: Move relevant metrics to CM

---

dist/images/Dockerfile.fedora

OVN 23.06.0 was released on 2023-06-02.

fedora: Update OVN to 23.06.0-0.

---

go-controller/pkg/ovn/controller/apbroute/master_controller.go

Do the same work, but in loops rather than duplicating code.

apbroute: consolidate some startup code

---

go-controller/pkg/node/default_node_network_controller.go

2023-06-21T01:32:41.27224837Z stderr F E0621 01:32:41.272153    1616 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
2023-06-21T01:32:41.27226207Z stderr F goroutine 447 [running]:
2023-06-21T01:32:41.27226607Z stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d7d920?, 0x23d56b0})
2023-06-21T01:32:41.27226907Z stderr F 	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
2023-06-21T01:32:41.27228377Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000260000?})
2023-06-21T01:32:41.27228707Z stderr F 	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75 …

Fixes panic with APB sync conntrack

---

go-controller/pkg/ovn/egressip_test.go

Failure seen in https://github.com/ovn-org/ovn-kubernetes/actions/runs/5391698838/jobs/9788946404?pr=3673

Fix bad expected NAT on egressip unit test flake

---

go-controller/pkg/network-controller-manager/network_controller_manager.go

Ovnkube-controller would exit if it did not see the zone configured in NBDB on the first try because the wait loop was returning error when it did not find the zone, rather than continuing to poll. This fixes it and adds some more clear logging on how long it is taking for this wait to finish.

Fixes ovnkube-controller not waiting for zone

---

go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go

Simple PR, removes the debug log line that accidentally creeped in cc @trozet

Remove Debug Logline

---

go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
go-controller/pkg/ovn/controller/apbroute/external_controller_namespace.go
go-controller/pkg/ovn/controller/apbroute/external_controller_pod.go
go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
go-controller/pkg/ovn/controller/apbroute/master_controller.go
go-controller/pkg/ovn/controller/apbroute/network_client.go
go-controller/pkg/ovn/controller/apbroute/node_controller.go
go-controller/pkg/ovn/controller/apbroute/repair.go
go-controller/pkg/ovn/default_network_controller.go
go-controller/pkg/ovn/egressgw.go

There are specific reasons for when we want
to use the structured logs a.k.a InfoS versus
when we want to use the formatted logs a.k.a Infof.
Most of these logs are using the Infof format while using the InfoS function unfortunately. This causes logs like:
I0629 20:41:28.798703  114685 master_controller.go:200] "Repairing Admin Policy Based External Route Services" I0629 20:41:28.798985  114685 repair.go:30] "Syncing exgw routes took %v" 265.415µs="(MISSING)" I0629 20:41:28.799084  114685 external_controller_pod.go:42] "Processing gateway pod %s/%s with matching policies %+v" openshift-dns="node-resolver-cmhvr" []="(MISSING)" I0629 20:41:28.799116  114685 external_controller_pod.go:42] "Processing gateway pod %s/%s with matching policies %+v" …

APB: Fix wrong structured logs

---

go-controller/pkg/ovn/egressfirewall.go

If the egress fw was modified while trying to update status, it will just repeatedly fail:
ovn-worker2/ovn-kubernetes/ovnkube-network-controller-manager.log:E0621 04:03:47.983023   11526 default_network_controller.go:761] Failed to update egress firewall status egressip-3696/default, error: error in updating status on EgressFirewall egressip-3696/default: Operation cannot be fulfilled on egressfirewalls.k8s.ovn.org "default": the object has been modified; please apply your changes to the latest version and try again
Fetch the latest version and update the status.

Fix updating egress firewall status

---

go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync.go

`ExternalIDs[defaultDenyPolicyTypeACLExtIdKey]` is also used by multicast acls (despite the name), but multicast acl have different priorities.
It was not a bug, because multicast acls are updated before default deny, therefore only default deny acls will match the criteria. This commit just makes the filtering more specific.

Fix acl sync to properly filter default deny acls.

---

docs/INSTALL.OPENSHIFT.md

fixes some typos in docs/INSTALL.OPENSHIFT.md

---

go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go

Node add can fail because we try to set port binding in IC on the SBDB, and it depends on the SBDB chassis being present. This is configured by ovnk in NBDB, but it can take some time for northd to propagate this to SBDB. OVNK trying to set the port binding before the chassis has appeared in SBDB will cause a failure, and node retry will take up to 30 seconds. Avoid this delay by waiting a bit for the chassis to show up in SBDB.

Adds a wait for SB chassis for port binding

---

go-controller/pkg/node/default_node_network_controller.go

Leverage the poll loop correctly so that
we don't crash and restart frequently.

Fix startup of ovnkube-node

---

go-controller/pkg/informer/informer_test.go

getting 1 add event instead of 2.

An attempt to fix "adds existing pod and processes an update event"

---

go-controller/pkg/ovn/pod_selector_address_set.go

- On pod add/update the IP not might be available yet, since another node might be allocating its IP. Suppress the error.
- Warning was printing a wrapped error object
- On completed pods check, if the pod had no IP, it would cause an error and be retried. If the pod is completed and has no IP, we should not retry or log error.

Handle pod IPs correctly for address set selector

---

go-controller/pkg/factory/factory.go

this was caught in review for the PR to rebase to k8s 1.27 [0] but the PR was approved and merged before it could be updated.
[0] https://github.com/ovn-org/ovn-kubernetes/pull/3593/files/2c4701d8e2ac5326affe0fc39f97f8fefb71e437..3ce2d31065684edc4607be3b51b1754867c71ebf#top

use false in OnAdd in WithUpdateHandlingForObjReplace

---

contrib/kind.sh

Add mlb entry to kind.sh --help

---

go-controller/hybrid-overlay/pkg/controller/node_linux.go

RouteDel's log should be corrected.

fixes logs for Route delete

---

go-controller/pkg/clustermanager/egressip_controller.go
go-controller/pkg/clustermanager/egressip_controller_test.go

This would remove node name comparison between cloud private ip config and egress ip status as this is not valid in the case of egress ip failover to another node during upgrade or reboot scenario.

Remove node check for syncing cloud private ip config

---

go-controller/pkg/ovn/controller/services/node_tracker.go
go-controller/pkg/ovn/egressgw.go
go-controller/pkg/util/node_annotations.go

Ensure load-balancers are not deleted till node migrates to remote

---

test/scripts/install-kind.sh

See https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0 and https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0 for details of the changes.

Bump to kind 0.20.0

---

go-controller/pkg/ovn/zone_interconnect/chassis_handler.go
go-controller/pkg/ovn/zone_interconnect/chassis_handler_test.go

When processing a node deletion, we're getting the node kube resource directly from the API server along with the delete event. 
In the code that deletes a remote node, we look for the chassis id in the node annotation and based on that we proceed to delete the corresponding chassis in sbdb. If ever the chassis id wasn't found in the node annotation, we wouldn't be able to find it by retrying the same operation later on, since the kube resource we're inspecting will be exactly the same. So we'd better continue with the chassis deletion, even though we only have the node name for it, and go on with the rest of the node removal code.

Run remote node deletion by hostname if chassis id wasn't found

---

go-controller/pkg/node/default_node_network_controller.go
go-controller/pkg/node/default_node_network_controller_test.go

If geneve encap port is different from the default, then we configure the SBDB chassis with the new port. After this we proceed to annotate the zone-name in ovnkube-node.
However in IC deployments, ovnkube-controller does not come up until the zone-name annotation is tagged on the nodes: https://github.com/ovn-org/ovn-kubernetes/blob/4bfacf905e84e9e1e37e3a9dda5b5321df22bc4f/go-controller/pkg/network-controller-manager/network_controller_manager.go#L337 This means ovnkube-controller is waiting on ovnkube-node to annotate stuff before starting to configure NBDB stuff and SBDB chassis creation won't happen because of that.
On the other hand, ovnkube-node is timing out trying to find the sbdb chassis to set the encap port since chassis is not existing in sbdb yet.
We end up in a deadlock …

Fix encap port deadlock

---

go-controller/pkg/node/management-port_linux_test.go

Fix data race seen in mgnt port DPU test

---

go-controller/pkg/clustermanager/network_cluster_controller.go
go-controller/pkg/ovn/master.go

clearInitialNodeNetworkUnavailableCondition needs to be run on every node for GCP. Since we have some nodes that are not running ovn-kubernetes, notably windows, it should be run in the clustermanager

move clearInitialNodeNetworkUnavailableCondition to clustermanager

---

docs/ovnkube-trace.md

This updates ovnkube-trace readme file according to latest changes for adapting interconnect feature and support for tracing dual stack cluster.

Update ovnkube-trace readme file

---

contrib/kind.sh

Allows to run cluster manager in HA mode when IC is enabled.

kind: enable control plane/cluster manager HA with IC

---

go-controller/pkg/clustermanager/egressip_controller.go

See commit message for more details.

EIP multi NIC: fix possible exception when finding a network for EIP

---

go-controller/pkg/ovn/gateway_init.go

See https://issues.redhat.com/browse/FDP-38 for details

Do not set vlanID when its zero

---

go-controller/cmd/ovnkube-trace/ovnkube-trace.go

The ovnkube-node container is merged into ovnkube-controller container in an interconnect environment with this PR https://github.com/ovn-org/ovn-kubernetes/pull/3807, it creates regression in ovnkube-trace command. Hence this commit provides relevant fixes for the command so that it works seamlessly on this environment.

Make ovnkube-trace to work for ovnkube-controller

---

dist/images/Dockerfile.fedora
dist/images/Dockerfile.fedora.dev

OVN 23.09.0 was released on 2023-09-15. Also update the fedora image to f38.

fedora: Update OVN to 23.09.0-0.

---

test/e2e/kubevirt.go

Looks like virtual machine creation sometimes fail at kubevirt virt-api services not ready yet. This change retries the creation in case of failure.
Closes https://github.com/ovn-org/ovn-kubernetes/issues/3902
CI error logs 
```
Sep 13 10:56:49.180: Unexpected error:
<*errors.StatusError | 0xc00078a1e0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Internal error occurred: failed calling webhook \"virtualmachines-mutator.kubevirt.io\": failed to call webhook: Post \"[https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s\](https://virt-api.kubevirt.svc/virtualmachines-mutate?timeout=10s\)": context deadline …
```

kubevirt, e2e: Retry vm creation

---

go-controller/cmd/ovnkube-identity/ovnkubeidentity.go

Fixed two isses that prevented the process to exit on error.
- We were waiting for `idleWebhookConnectionsClosed` even if `l.Listen` failed
- We would not exit if either `runWebhook` or `runCSRApproverManager` failed, only when both of them failed
Observed when the webhook cannot bind because the port was already in use, which may happen if an old instance of the webhook is running under a different user id.

Fix webhook error & exit handling

---

dist/images/Dockerfile.fedora

Update OVN 23.09 to latest version - ovn-23.09.0-37.

---

test/e2e/kubevirt.go

Same as VM creation the virt-api webhook is stuck sometimes, this change add a retry to the test.
closes #3902
kubevirt, e2e: Retrie VMIM creation

kubevirt, e2e: Retrie VMIM creation

---

go-controller/Makefile

Bump golang docker version for make check

---

go-controller/pkg/util/sriovnet_linux.go

Fixes https://issues.redhat.com/browse/OCPBUGS-22691

Fix pod creation with sriov interfaces

---

test/e2e/e2e.go

Wait for egress firewall applied status before running connectivity check
should fix https://github.com/ovn-org/ovn-kubernetes/issues/3970

EgressFIrewall e2e fix

---

go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_test.go

Resolved an issue where the Egress IP deletion handler misidentified affected pods, leading to unintended leaks of OVN logical router policies and SNATs. This occurred in scenarios with matchExpressions that only excluded keys and values.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-24055

Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

---

dist/images/Dockerfile.fedora

fedora: Update Dockerfile for latest OVN ovn-23.09.0-91.

---

CODEOWNERS
OWNERS

Add Surya Seetharaman as committer

---

test/e2e/service.go

1. Clarify PMTUD test's topology using diagram as comment
2. Revert MTU to old value so that when the subsequent test runs large packets can still reach correctly.
/cc @trozet

Clarify PMTUD e2e test topology

---

contrib/kind.sh
go-controller/pkg/node/gateway_init_linux_test.go

This is to merge the easier fixes from PR4046 which do not need to be discussed.
That should make review easier as none of these fixes is crucial, they don't risk breaking anything and there's no risk associated merging them. All the commits should just improve testing tools (mainly kind.sh) and are very small.

Fixes mainly to kind.sh

---

.github/workflows/test.yml
dist/images/daemonset.sh
dist/templates/ovnkube-single-node-zone.yaml.j2
test/e2e/egressip.go

PR to demo drop forwarding Egress Services issues
Upstream bug: https://github.com/ovn-org/ovn-kubernetes/issues/4042
Downstream bug: https://issues.redhat.com/browse/OCPBUGS-25637
Resolution: https://github.com/ovn-org/ovn-kubernetes/pull/4056/

Demo drop forwarding Egress Services issues

---

README.md

Ensuring correct case for the project name for consistency.

---

go-controller/pkg/ovn/hybrid.go

We are using a generic predicate to remove HO routes from ovn cluster router that also matches HO routes on the gateway router, which will fail because the gateway router will be left referencing nonexistent rows. Inverting the order fixes this for now.

Don't remove HO static routes from incorrect routers

---

README.md

Trying to bringup a k8s cluster with kubeadm
with ovn-kubernetes repo needs the following
minimum changes to README.md.

README.md: Make it easier to get started.

---

contrib/kind.sh

The latest [metallb](https://github.com/metallb/metallb/pull/2073) skips nodes having the label `"node.kubernetes.io/exclude-from-external-load-balancers": ""` (particularly set on the control plane nodes) from advertising bgp routes for external service. But this breaks ovnk service related tests. Hence this PR removes the label from those nodes after metallb deployment on kind cluster, so that these nodes can also act as bgp speaker for external services.
Fixes https://github.com/ovn-org/ovn-kubernetes/issues/4104

Remove exclude external lb label from control-plane nodes

---

go-controller/pkg/metrics/ovs.go

When OVN-Kubernetes lists all datapaths with `ovs-appctl dpctl/dump-dps`, it stores both a datapath's name and type. But it then continues to use only each datapath's name when querying `ovs-appctl dpctl/show`.
For system datapaths this works because `ovs-appctl dpctl/show` will assume the `system` type if no type has been set. However, this breaks when using other datapath types such as `netdev`, causing `ovs-appctl` to fail with:
```
ovs-vswitchd: opening datapath ovs-netdev failed (No such device)
```
This change keeps using a datapath's name as an identifier for metrics but includes the type when querying ovs-appctl.
Whether a datapath's name without a type is sufficient for identifying datapaths uniquely in OpenShift and Open vSwitch is left for future work.

Use full datapath name when querying datapaths with ovs-appctl

---

go-controller/pkg/ovn/hybrid.go
go-controller/pkg/ovn/hybrid_test.go
go-controller/pkg/ovn/master.go

currently if hybrid overlay is being disabled only the nodes annotations get cleaned up. This will lead to erroneous entries in the ovn database that will lead to potentially one pod on every node (the one allocated the reroute address for hybrid overlay) to not being able to send/receive network traffic.
Correctly clean up hybrid overlay ports and logical router policies on node add. A unit test was amended to include this cleanup.
will fix https://issues.redhat.com/browse/OCPBUGS-22221
Also removed references to a function that no longer exists watchNodes()

correctly clean up hybrid-overlay on during node add

---

go-controller/pkg/ovn/base_network_controller.go

In general, a node might be set as Ready and have things scheduled on it
before we have had the chance to process the corresponding AddNode.

Ignore missing live migratable pod annotation on AddNode

---

go-controller/pkg/util/kube.go

Once the initial certificate is retrieved, run a periodic check to ensure it is not expired.
The certificate can become invalid when the time changes unexpectedly(e.g. cluster was suspended).
This cannot happen in normal circumstances as the cert manager keeps track of when to rotate the certificate.
Additionally, when waiting for the initial certificate use the one from cert manager to avoid a scenario in which an expired certificate is accepted as valid.
Verified by setting up a kind cluster and then moving the time forward by 10min:
```
I0201 14:02:39.987769    2532 certificate_manager.go:356] kubernetes.io/kube-apiserver-client: Current certificate is expired
E0201 14:02:39.987797    2532 kube.go:335] The current certificate is invalid, exiting.
...
POD RESTARTS
...
I0201 …
```

Periodically check whether the ovnkube-node certificate is not expired

---

go-controller/pkg/node/node_ip_handler_linux_test.go

Node IP handler: allow skipping tcs that require root

---

test/e2e/kubevirt.go

Using depending on external domain to check n/s traffic and name resolution introduce some flakiness since the domain can be down or reject CI.
This change replace the external domain with the kube api service fqdn so everything is setup by the cluster.
Also to make this work the guest VM is configured to use NetworkManager for name resolution instead of systemd resolved.
kubevirt, e2e: Use kube api service to test n/s

kubevirt, e2e: Use kube api service to test n/s

---

go-controller/pkg/util/kube.go

If the node name changes recreate the certificate using kubelets kubeconfig by removing the stale cert.
Otherwise the certificate request would be created by using the current cert(with the old node name) which the cert approver denies. 
Verified in kind with the following steps:
1. Rename a node:
```
docker exec ovn-worker sh -c 'echo " --hostname-override=ovn-worker-pro" >> /etc/default/kubelet'
docker exec ovn-worker systemctl restart kubelet
```
3. Accept the new node to the family:
```
kubectl get csr | awk '/Pending/ {print $1}' | xargs kubectl certificate approve
kubectl label node ovn-worker-pro k8s.ovn.org/zone-name=ovn-worker-pro --overwrite 
```
5. Verify that the ovnkube-node cert got recreated:
```
kubectl get csr --sort-by=.metadata.creationTimestamp …
```

Recreate the ovnkube-node certificate if the node name changed

---

dist/images/daemonset.sh
dist/images/ovnkube.sh
dist/templates/ovnkube-db-raft.yaml.j2
dist/templates/ovnkube-db.yaml.j2
dist/templates/ovnkube-single-node-zone.yaml.j2
dist/templates/ovnkube-zone-controller.yaml.j2

ovnkube.sh: make northd backoff interval configurable

---

test/e2e/service.go
test/scripts/e2e-cp.sh

based on https://github.com/ovn-org/ovn-kubernetes/pull/4201
/cc @kyrtapz @tssurya

Fix and enable MetalLB service tests for Shared mode with IPv6

---

test/e2e/multihoming.go

Extract code segments into functions.
This will allow also extending the tests and reusing code.
For example can be used by the new tests we are adding at
https://github.com/ovn-org/ovn-kubernetes/pull/4153

e2e tests: Refactor multihoming tests

---

docs/egress-ip.md

Depends on https://github.com/ovn-org/ovn-kubernetes/pull/4040

Update EIP docs for EIP multi NIC

---

test/scripts/e2e-cp.sh

this test is flaking and needs to be fixed

skip ipv6 'should listen on each host address test'

---

go-controller/pkg/node/gateway_localnet_linux_test.go
go-controller/pkg/node/gateway_shared_intf.go

Due to a regression caused by d8f728844 service flows were being added to the wrong key in the flow cache, and upon removal not all flows were being removed. This fixes that it and adds unit test coverage.

Fixes regression to service openflow rules

---

go-controller/pkg/clustermanager/status_manager/status_manager.go
go-controller/pkg/clustermanager/status_manager/zone_tracker/zone_tracker.go
go-controller/pkg/controller/controller.go
go-controller/pkg/controller/controller_test.go

Change Config to be reusable by simple Controller and SubController.

pkg/controller: add MultiController to allow common initial sync for multiple informers.

---

test/e2e/egressip.go

A test could fail when allocating pods to a node that has the not-reachable taint. That could happen if the previous test last step was to set that node back to Ready. This waits for the node condition to be set back to ready as well but does not explcitily wait for the taint to be removed which seems to happen asynchronously, potentially a change of behavior from the last kube rebase.

e2e: wait for taints to be removed when setting node back to ready

---

docs/_config.yml

Add github pages conf

---

go-controller/pkg/clustermanager/node/subnet_allocator.go
go-controller/pkg/clustermanager/node/subnet_allocator_test.go

This PR is to return an already allocated subnet instead of creating a new one if a combination of subnet and node name already exists in the cache[1].
- May cause multiple subnet allocation per node as we currently allow same owner name for multiple subnets.
This PR is to stop multiple allocation of node-subnet from ClusterNetwork CIDR for any node. This may occur if addition[2] of 'k8s.ovn.org/node-subnets' annotation gets delayed and meanwhile UpdateResource[3] gets executed multiple times after executing initial AddResource[3] for a node. 
Below log indicates execution of AddResource/UpdateResource(network_cluster_controller) in quick succession:
~~~
I1227 13:40:52.026089 1 node_allocator.go:371] Expected 1 …

Reuse node-subnet from cache if exists

---

go-controller/pkg/metrics/ovs.go

the ovnkube-node daemon that runs on the node doesn't share the process namespace with the host and therefore will not be able to collect any ovs-vswitchd or ovsdb-server related processes.
@trozet @tssurya @jcaamano another issue in the metrics module

OVS Process metrics cannot be collected through the PID file location

---

docs/developer-guide/web-design.md
mkdocs.yml

This particular PR captures how one can contribute to ovn-kubernetes.io.
It captures tools used and how to test their changes locally before submitting
the PR.

document on how we do web designing for ovn-kubernetes project

---

dist/templates/ovnkube-alerts.yaml.j2
go-controller/pkg/clustermanager/node/node_allocator.go
go-controller/pkg/metrics/cluster_manager.go
helm/ovn-kubernetes/templates/ovnkube-alerts.yaml

This PR also adds a new alert OVNKubeAllocatedSubnetsDoNotMatch

Update ovnkube_clustermanager_allocated_v4_host_subnets metric during add/delete node event

---

.github/actions/diagnostics/action.yml
.github/workflows/test.yml

ISSUE: https://github.com/ovn-org/ovn-kubernetes/issues/4287
JIRA: https://issues.redhat.com/browse/SDN-4786

check disk usage before and after 'Run Tests' step

---

test/e2e/util.go

During wrappedTestFramework, avoid the following failure when running e2e, by accounting for situations where
/etc/origin/openvswitch is not present. The proposed change will not alter existing behavior, just make it  more resilient.
```
INFO: Unexpected error:
<*errors.errorString | 0xc000488220>:
failed to run "docker exec ovn-control-plane cp -f /etc/origin/openvswitch/conf.db /var/log/.../ovn-control-plane-conf.db": exit status 1 (cp: cannot stat '/etc/origin/openvswitch/conf.db': No such file or directory)
```

e2e util: do not assume /etc/origin/openvswitch exists

---

contrib/kind.sh

kind: Add parameter to configure overlay MTU
kind: Add parameter to configure overlay MTU

kind: Add parameter to configure overlay MTU

---

go-controller/pkg/node/base_node_network_controller_dpu.go

allow multiple interface of different NADs of the same network in a Pod

---

dist/images/daemonset.sh
dist/images/ovnkube.sh
dist/templates/ovnkube-master.yaml.j2
dist/templates/ovnkube-single-node-zone.yaml.j2
dist/templates/ovnkube-zone-controller.yaml.j2
go-controller/pkg/config/config.go
go-controller/pkg/network-controller-manager/network_controller_manager.go
helm/ovn-kubernetes/README.md
helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
helm/ovn-kubernetes/values.yaml

make svc_template_support configurable, default is enabled

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/e2e-testing.yaml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/ISSUE_TEMPLATE/flaking-test.yaml
.github/ISSUE_TEMPLATE/generic-issue.yaml
.github/ISSUE_TEMPLATE/support.yaml
.github/ISSUE_TEMPLATE/unit-testing.yaml
.github/PULL_REQUEST_TEMPLATE.md

This PR introduces new templates for issues, updates
the PR template a bit (taken with love from k8s community))
This makes our issues look better and adds
automatic labels depending on which
area the issue falls under
Open an issue/PR with this change
`Cleanup issues/PRs template`

Fix templates for issues/prs in OVN Kubernetes

---

.github/ISSUE_TEMPLATE/bug-report.yaml

This PR fixes some nits in the bug report template rendering
Fixes #
```release-note
```

Fix id to not have spaces

---

docs/okeps/okep-4368-template.md
mkdocs.yml

Adds template to write OKEPs
Fixes #4368 
Will be added to a new tab in ovn-kubernetes.io website

Add OKEP Template

---

go-controller/pkg/node/base_node_network_controller_dpu.go

If ovnkube-node-dpu restarts, we need to handle already running pods as well as the later update/delete pod event handler relies on the podNADToDPUCDMap cache.
Fixes #
```release-note
```

node-dpu needs to handle POD add events for running pods

---

go-controller/pkg/metrics/ovn_northd.go

We would like to know the status of OVN DB connection from ovn-northd to both NB and SB.
Once we have the metric, then we can set alert on the same.
@trozet @tssurya PTAL

Add nb-connection-status & sb-connection-status metrics for ovn-northd

---

go-controller/pkg/ovn/dns_name_resolver/dns.go

That bug is obvious, but the side effects are worse than you can think:
since egress firewall node selector uses the same queued informer as regular node event handler, the deadlock of an egress firewall handler means no events for a given node are handled at all.
This will be followed-up by a re-design PR to make these handlers independent

dns: fix deadlock in case of error

---

.github/pr-labeler.yml

I am manually having to label the PRs; none of the
authors do this and neither can we expect them to
start doing this since everyone loves writing code
but rarely like project management duties that
come with it.
This attempts to automate this process.
This is just a part1 of this process and in case
it turns out to work well we can fill in the same
for the remaining area labels.
Fixes #
Uses https://github.com/marketplace/actions/labeler
See that for more information on fine tuning
I guess we just need to merge this and then test it out?
```release-note
NONE
```

Add labeler workflow for PRs

---

helm/ovn-kubernetes/templates/ovnkube-monitor.yaml
helm/ovn-kubernetes/values.yaml

This PR adds custom labels on ovn-kubernetes service monitor objects in the helm chart so that the service monitors are discovered from which the prometheus exporters scrape metrics off of.
None
None
Adds labels to service monitor ovn-kubernetes objects off of which prometheus metrics are scraped.
```release-note
```

Add labels for ServiceMonitor K8S objects

---

docs/governance/CONTRIBUTING.md
docs/index.md
docs/installation/launching-ovn-kubernetes-on-kind.md
mkdocs.yml

Starting to refactor developer documentation

---

docs/features/hardware-offload/ovs-doca.md
docs/features/hardware-offload/ovs_acceleration.md
mkdocs.yml

Update hardware offloads to hardware acceleration

---

README.md
docs/index.md

some nit fixes for docs before releasing

docs-nit-fix

---

dist/images/Dockerfile.fedora.dev

This PR fixes the dev Dockerfile.  It's needed in order to be able to easily test custom OVN changes.
Fix OVS/OVN build steps in Dockerfile.fedora.dev.
```release-note
NONE
```

Fix the Fedora dev Dockerfile.

---

docs/features/multiple-networks/multi-homing.md

This PR addresses a gap in the OVN-Kubernetes user documentation, by explaining the persistent IPs for virtualization workloads feature. 
This feature is described in detail in the following [KubeVirt enhancement](https://github.com/kubevirt/community/pull/279).
Fixes #
```release-note
```

docs, multi-homing, virt: persistent IPs for virt workloads

---

docs/features/hardware-offload/ovs-doca.md
docs/features/hardware-offload/ovs-kernel.md
mkdocs.yml

Keep section references in documentation consistent

Fix hardware acceleration documentation.

---

contrib/kind-common
contrib/kind.sh

Since ipam component was renamed to `kubevirt-ipam-controller`, 
and also the repo URL was changed (to https://github.com/kubevirt/ipam-extensions) 
we need to adapt to those changes.
Fixes #
```release-note
```

ipam: Adapt to ipam-controller renaming and repo transfer

---

go-controller/pkg/ovn/pod_selector_address_set_test.go
go-controller/pkg/ovn/policy_test.go

in an effort to remove the FakeAddressSet code from testing this commit remove FakeAddressSet from network policy testing
Fixes #
```release-note
```

Remove FakeAddressSet from network policy testing

---

test/e2e/acl_logging.go

Fixes waiting for ACL logging in a test where the namespace's ACL logging level is updated.
To reproduce, use these steps:
cd test/e2e && \
while : ; do \
go test -v . -ginkgo.v \
-ginkgo.focus 'the\sACL\slogs\sare\supdated\saccordingly' \
-ginkgo.flake-attempts 1 -provider skeleton \
-kubeconfig ${KUBECONFIG} --num-nodes=2 || break ; \
echo --- ; done
Fixes: #4392
Fixes #
```release-note
```

e2e flake fix: Fixes race in e2e ACL logging

---

test/e2e/network_segmentation.go

Will be used in the future e2es :)

segmentation e2e: add runUDNPod function to simplify tests.

---

go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go
go-controller/pkg/ovn/secondary_layer2_network_controller.go
test/e2e/network_segmentation.go

This commit auto-excludes the gateway and management port IP addresses from the subnet range for user defined primary networks of `layer2` topology.
We are [already getting this behavior](https://github.com/ovn-org/ovn-kubernetes/blob/e3ad29066d00085d9a18b49751288d2fe5f3d10a/go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go#L24) on all L3 secondary networks + the default cluster network; thus we do not have to do anything user-defined primary networks.
This PR  auto-excludes the gateway and management port IP addresses from the
subnet range for user defined primary networks.
Fixes #
Covered by unit tests (introduced in this PR).
Auto-exclude GW and mp0 IPs from the subnets of user defined primary networks.
```release-note
NONE
```

udn: auto-exclude GW and mp0 IPs from the subnet

---

go-controller/pkg/util/kube.go

In the unlikely event that the certificate file becomes corrupted, recover by removing the certificate so the CSR will be created using the bootstrap kubeconfig.
`certificate.NoCertKeyError` is an expected error that is handled by the certManager so there is no need to do anything there.
Additionally avoid trying to remove the file if the error is a os.PathError.
Repro:
1. Start a kind cluster with node identity enabled (default)
2. Corrupt the certificate file, for example:
```
docker exec ovn-worker bash -c 'echo "" > /var/run/ovn-kubernetes/certs/ovnkube-client-current.pem' 
```
3. Restart ovnkube-node and check the logs:
```
I0705 12:59:29.422234   10322 certificate_store.go:130] Loading cert/key pair from "/var/run/ovn-kubernetes/certs/ovnkube-client-current.pem".
E0705 …
```

NodeIdentity: Recover from a corrupted certificate file

---

.github/workflows/test.yml

Add CI lane for network segmentation and local gateway.
-->
```release-note
NONE
```

ci: Add network segmentation lgw lane

---

helm/ovn-kubernetes/Chart.yaml
helm/ovn-kubernetes/README.md
helm/ovn-kubernetes/charts/ovn-ipsec/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-control-plane/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-db-raft/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-db/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-identity/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-master/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-node-dpu-host/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-node-dpu/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-node/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-single-node-zone/Chart.yaml
helm/ovn-kubernetes/charts/ovnkube-zone-controller/Chart.yaml
helm/ovn-kubernetes/charts/ovs-node/Chart.yaml

Helm release appVersion should be 1.0.0 (not 1.16.0)

helm: fix appVersion to be 1.0.0

---

go-controller/pkg/clustermanager/clustermanager_test.go
go-controller/pkg/config/config.go
go-controller/pkg/config/config_test.go
go-controller/pkg/config/utils.go

This PR is to emit error and terminate ovnkube startup if transit switch subnet is being used as either join switch or masquerade subnet.
Fixes #4502 
Fixes #
```release-note
```

Add subnet overlap check for transit switch subnet

---

go-controller/hybrid-overlay/pkg/controller/ovn_node_linux.go
go-controller/hybrid-overlay/pkg/controller/ovn_node_linux_test.go
go-controller/pkg/util/node_annotations.go

258c5cd16dfea428a53ac5e313b352899170a55c forgot to update the hybrid overlay case of using the annotation.

Fixes hybrid overlay from deprecated annotation

---

go-controller/pkg/node/node_ip_handler_linux_test.go

UT flake: fix panic in node IP handler tests

---

go-controller/pkg/ovn/hybrid_test.go

The issue was a race where the hybrid overlay node was being updated to remove the windows label for testing. However, the update action itself was with a blank original copy of the node which would overwrite l3 gateway config and other OVNK annotations with empty values, causing a bunch of errors.
This changes the code to just patch and remove the labels, in order to not corrupt any of the other aspects of the node object itself.
Fixes: #4387

Fixes HO test when HO node switched to OVN node

---

go-controller/Makefile

When I updated golang to 1.22.0 in (9be60edf4) I left out updating the go version in the makefile
Fixes #
```release-note
```

Missed updating go version in makefile to 1.22.0

---

test/e2e/e2e.go
test/e2e/egressip.go
test/e2e/external_gateways.go
test/e2e/multicast.go
test/e2e/multihoming.go
test/e2e/node_ip_mac_migration.go
test/e2e/ovspinning.go
test/e2e/pod.go
test/e2e/service.go
test/e2e/static_pods.go
test/e2e/util.go

Various minor fixes to test/e2e pulled out of @martinkennelly 's branch to start adding support for running ovn-k e2e downstream in OCP.
```release-note
NONE
```

Dead code, gofmt, typos, and other trivial test/e2e fixes

---

go-controller/pkg/node/controllers/egressservice/egressservice_node.go
go-controller/pkg/node/egress_service_test.go
test/e2e/egress_services.go

Ingress reply traffic for ETP=Local EgressServices with Network did not use the network on LGW. Here we fix it by programming another ip rule for the ETP=Local MASQUERADE + Nodeport, so that the reply also gets steered properly.
**NOTE:** while working on this I saw that ETP=Local does not behave well on SGW (even without Network) + with Network both Cluster and Local do not seem to work. This needs to be tracked in a different issue.

EgressService: Fix ETP=Local ingress reply for LGW

---

go-controller/pkg/ovn/secondary_layer3_network_controller_test.go

This PR adds unit tests to assert the proper cleanup of layer3 UDN networks.
Fixes #
Run the unit tests added in this PR.
Add unit tests for layer3 primary UDNs.
```release-note
NONE
```

Udn layer3 add cleanup unit tests

---

go-controller/pkg/network-attach-def-controller/network_manager.go

NAD controller adds keys to Network Manager to process. Upon Network Manager start up, it does not add any handler for Kubernetes and therefore does not block until it processes all current objects. For certain controllers that integrate with UDN, they contain caches, which depend on being initialized by networks having been created at start up. If those controllers were to start without a fully initialized cache, they may end up temporarily deleting configuration that could cause disruption.
An example of this is the ip rule manager. If the ip rule manager reconciliation loop runs, it will try to remove any stale network rules. If the cache is not fully updated by the time the loop runs, it would accidentally remove previously configured rules, causing disruption until the network add is …

Serializes Network Manager Start up

---

go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/gateway_iptables.go

Depends-On: https://github.com/ovn-org/ovn-kubernetes/pull/4550 and https://github.com/ovn-org/ovn-kubernetes/pull/4496
Adds iptables SNAT rules for UDN networks
so that pod2Egress can work properly
Given ip table rules are not really per network no use of adding a ipt rules manager just for that.
Instead used feature gate and added a one time CIDR masquerade rule.
Day2 change for masquerade CIDR range is not supported here for UDNs yet.
```
-A POSTROUTING -j OVN-KUBE-EGRESS-IP-MULTI-NIC
-A POSTROUTING -j OVN-KUBE-EGRESS-SVC
-A POSTROUTING -o ovn-k8s-mp0 -j OVN-KUBE-SNAT-MGMTPORT
-A POSTROUTING -d 172.18.0.1/32 -j DOCKER_POSTROUTING
-A POSTROUTING -s 169.254.0.1/32 -j MASQUERADE
-A POSTROUTING -s 10.244.2.0/24 -j MASQUERADE
-A POSTROUTING -s 169.254.0.0/29 -j RETURN ---> UDN
-A …
```

UDN: Add `MASQUERADE` IPTable Rules

---

dist/images/Dockerfile.fedora

Depends on https://github.com/openshift/ovn-kubernetes/pull/2269 to be merged

Update Dockerfile.fedora to use pre-released 24.09 ovn rpm.

---

go-controller/pkg/node/gateway.go
go-controller/pkg/node/gateway_init.go
go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/gateway_localnet_linux_test.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/gateway_udn.go
go-controller/pkg/node/gateway_udn_test.go
go-controller/pkg/node/openflow_manager.go
go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
test/e2e/network_segmentation_services.go

Adds support for accessing services (nodePort/LB) from outside (or other nodes).
Fixes #
Unit tests have been adapted where needed.
E2e tests for UDN + nodePort have been enabled for shared gateway.
```release-note
NONE
```

UDN: SGW: L2/L3 Add support for external -> service traffic.

---

docs/api-reference/introduction.md
docs/api-reference/userdefinednetwork-api-spec.md
mkdocs.yml

This PR Adds UserDefinedNetwork CRD API reference
The doc generated using the following command 
```
crd-ref-docs --source-path ./go-controller/pkg/crd/userdefinednetwork --config=crd-docs-config.yaml --renderer=markdown --output-path=./docs/api-reference/userdefinednetwork-api-spec.md
```
Fixes #
```release-note
NONE
```

docs, api-reference: Add doc for UDN API

---

go-controller/pkg/clustermanager/endpointslicemirror/endpointslice_mirror_controller_test.go
go-controller/pkg/config/config.go
go-controller/pkg/config/utils.go
go-controller/pkg/config/utils_test.go
go-controller/pkg/util/multi_network.go
go-controller/pkg/util/multi_network_test.go

This is to validate whether POD and join subnet mentioned in a
net-attach-def with topology "layer2" and "layer3" does not overlap
with ClusterSubnets, ServiceCIDRs, join subnet and masquerade subnet.
It also considers excluded subnets mentioned in a net-attach-def.
Fixes #
```release-note
```

Add subnet overlap check for POD and join subnets in net-attach-def

---

go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
go-controller/pkg/network-attach-def-controller/network_attach_def_controller_test.go
go-controller/pkg/network-controller-manager/network_controller_manager.go
go-controller/pkg/network-controller-manager/node_network_controller_manager.go

Emit a K8 event within the namespace of the NAD if the NAD cannot be parsed.

Emit Event if NAD cannot be parsed

---

go-controller/pkg/clustermanager/pod/allocator_test.go
go-controller/pkg/clustermanager/secondary_network_unit_test.go
go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template_test.go
go-controller/pkg/cni/udn/primary_network_test.go
go-controller/pkg/node/gateway_udn_test.go
go-controller/pkg/ovn/controller/services/lb_config_test.go
go-controller/pkg/ovn/controller/services/services_controller_test.go
go-controller/pkg/ovn/controller/services/utils_test.go
go-controller/pkg/ovn/topology/topologyfactory_test.go
go-controller/pkg/util/multi_network.go
go-controller/pkg/util/multi_network_test.go
test/e2e/multihoming.go
test/e2e/multihoming_utils.go
test/e2e/network_segmentation.go
test/e2e/network_segmentation_endpointslices_mirror.go

[WIP] checking testing without overlapping CIDR

---

go-controller/pkg/ovn/multihoming_test.go
go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
go-controller/pkg/ovn/secondary_layer3_network_controller_test.go

This commit is to add some unit tests to make sure proper NAT entries are being created i NBDB while DisableSNATMultipleGWs is set to true.
Fixes #4684 
```release-note
```

Add unit tests for UDN while DS is true

---

test/e2e/egress_firewall.go

In our e2e tests, a strange behaviour for ipv6 was seen: newly created pod can't reach ipv6 destination.
But if the same pod is re-created, everything works. We don't know what causes that behaviour, so given function is a workaround for this issue.
It also only historically fails for the first ef test "Should validate the egress firewall policy functionality for allowed IP", so only used there for now.
Based on testing done here https://github.com/ovn-org/ovn-kubernetes/actions/runs/10355680804/job/28665008105?pr=4513 in PR https://github.com/ovn-org/ovn-kubernetes/pull/4513
(hopefully) fixes https://github.com/ovn-org/ovn-kubernetes/issues/4480
Finally got the test run that is fixed by this change
https://github.com/ovn-org/ovn-kubernetes/actions/runs/10594137549/job/29358314564?pr=4650 …

Add a source pod create retry function for egress firewall e2e.

---

dist/images/Dockerfile.ubuntu.arm64
dist/images/daemonset.sh
dist/images/ovnkube.sh
dist/templates/ovnkube-master.yaml.j2
dist/templates/ovnkube-node.yaml.j2
go-controller/cmd/ovnkube/ovnkube.go
go-controller/pkg/config/config.go
go-controller/pkg/config/config_test.go
go-controller/pkg/node/default_node_network_controller.go
go-controller/pkg/node/default_node_network_controller_test.go
go-controller/pkg/node/gateway_init.go
go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/node_ip_handler_linux.go
go-controller/pkg/ovn/base_network_controller_pods.go
go-controller/pkg/ovn/master.go
helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
helm/ovn-kubernetes/charts/ovnkube-node-dpu/templates/ovnkube-node-dpu.yaml
helm/ovn-kubernetes/charts/ovnkube-node-dpu/values.yaml
helm/ovn-kubernetes/templates/_helpers.tpl
helm/ovn-kubernetes/values-no-ic.yaml

Fix several issues for supporting DPUs

---

go-controller/pkg/ovn/ovn.go
go-controller/pkg/ovn/pods.go
go-controller/pkg/ovn/udn_isolation.go
go-controller/pkg/util/pod_annotation.go
go-controller/pkg/util/pod_annotation_unit_test.go
test/e2e/network_segmentation.go

An example annotation is
```
k8s.ovn.org/open-default-ports: |
- protocol: tcp
port: 80
- protocol: udp
port: 53
```

Add UDN pod annotation to open default network ports.

---

go-controller/pkg/node/secondary_node_network_controller_test.go

This was introduced in https://github.com/ovn-org/ovn-kubernetes/pull/4713 but seriously I don't know why UT CI did not fail in that PR?
Fixes: #4765

Fix panic in UT

---

test/e2e/multicast.go

The past-me thought this was a good idea?? :) not really looks like I sneaked in a 5hour sleep at some point and never removed it...

Remove 5hours of sleeping time from e2e

---

go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go

When we go to add a remote node, its likely it is missing one or more anotations on the first couple events. Suppress these errors as we do for other remote node cases.

Suppress remote node annotation missing

---

test/e2e/kubevirt.go

This PR addresses a flake in KubeVirt E2E tests, improving
the connectivity tests.
It also introduces the use of an environment check for
KUBEVIRT_SKIP_MIGRATE_POST_COPY to avoid failing the
kubevirtv1.MigrationPostCopy mode, which is currently
used in the GitHub workflow.
~~Lastly, it makes it possible to skip tests in deployments
where OVS is installed on the node instead of running as
a pod.~~
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/4709

e2e flake fix: kubevirt

---

.github/PULL_REQUEST_TEMPLATE.md

Current template has too many questions which are hard to write, checklist is better to ask for tests and docs

change PR template to be checklist

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docker.yml
.github/workflows/test.yml

Repo migration fixes

---

go-controller/pkg/node/management-port_linux.go
go-controller/pkg/util/net_linux.go
go-controller/pkg/util/net_linux_unit_test.go

Routes via mp0 were being deleted on every ovnkube-node restart: [root@ovn-worker ~]# ip monitor route
Deleted 192.72.3.0/24 dev ovn-k8s-mp0 proto kernel scope link src 192.72.3.2 Deleted broadcast 192.72.3.255 dev ovn-k8s-mp0 table local proto kernel scope link src 192.72.3.2 Deleted local 192.72.3.2 dev ovn-k8s-mp0 table local proto kernel scope host src 192.72.3.2 local 192.72.3.2 dev ovn-k8s-mp0 table local proto kernel scope host src 192.72.3.2 broadcast 192.72.3.255 dev ovn-k8s-mp0 table local proto kernel scope link src 192.72.3.2
This causes traffic outage during upgrade, as well as other unwanted side effects when pod-destined traffic is routed via default gateway route in the host. This is especially disruptive in local gateway mode.
This patch removes the teardown, and then …

Fixes unexpected mp0 route removal during start up

---

go-controller/pkg/clustermanager/secondary_network_unit_test.go
go-controller/pkg/network-attach-def-controller/network_attach_def_controller_test.go

Add unit tests to document the behavior for localnet networks (with or without subnets defined) on IC/non-IC deployments.
Also add unit tests to ensure that the cluster manager tolerates the topology not managed errors which are raised for localnet without subnets.
This is a follow-up to #4813
Fixes #
```release-note
```

cluster manager, tests: ignore topology not managed errors

---

go-controller/pkg/clustermanager/userdefinednetwork/controller_test.go

Following the refactoring of UDN unit tests in #4612, flaky unit tests surfaced.
The test "when UDN is being deleted, NAD exist, 2 pods using UDN, should delete NAD once no pod uses the network" is flaky due to some pods not exist in the expected time.
This PR change the test setup so the clientset and informers are populated with the tested objects, as in other tests.
Fixes #4839

udn controller, tests: Fix flake where pods not exist yet

---

dist/images/Dockerfile.ubuntu

This PR updates Ubuntu version from 24.04 to 24.10 to get the in box OVN version 24.09 as required by ovnkube
Fixes #

Update ubuntu version to 24.10

---

docs/api-reference/userdefinednetwork-api-spec.md

- Localnet support removed, as it's not supported at the moment.
- Introduce ClusterUserDefinedNetwork CRD and types
Fixes #
This PR changes are result of the following command:
```
crd-ref-docs --source-path ./go-controller/pkg/crd/userdefinednetwork --config=crd-docs-config.yaml --renderer=markdown --output-path=./docs/api-reference/userdefinednetwork-api-spec.md
```

docs, api-reference: Update UDN content

---

test/e2e/e2e.go

Deleting the ovnkube-identity pod can result in webhook calls failing, leaving the pod in a terminated state. This prevents pods from being scheduled or updated.
In kind clusters, the API server runs on a single node, making this issue worse. The ovnkube-identity webhook listens on localhost, and when deleted, it breaks the API server's ability to update pod status or cleanly remove pods.
This fix accounts for these limitations, ensuring proper behavior.
Fixes: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4779
Fixes: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4838

Fix issues with ovnkube-identity pod deletion in kind clusters

---

contrib/kind.sh

By using `maxUnavailable`, we can make the redeploy faster.
Fixes #

kind, ic, single node zone: Improve redeploy speed

---

test/e2e/multicast.go

Fix a flake where IGMP queries do not occur while iperf runs bound to a multicast address. Instead, use smaller intervals, allowing the test to complete in less than the fixed 30 seconds.

e2e: Improve IGMP validation test with retries

---

go-controller/pkg/cni/udn/primary_network.go

primary_network: Properly log NAD name on error.

---

.github/workflows/test.yml
go-controller/Makefile
go-controller/hack/verify-go-mod-vendor.sh

Add script to test for go mod / vendor inconsistencies and add it to CI.
* add new dependency but do not run go mod / go vendor
* execute `make verify-go-mod-vendor`

Test for go mod or go vendor inconsistencies

---

go-controller/pkg/node/udn_isolation.go
go-controller/pkg/node/udn_isolation_test.go

Handle host-network pods as default network.
Don't return per-pod errors on startup.

udn host isolation: fix initialSync.

---

go-controller/pkg/controllermanager/controller_manager.go
go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go
go-controller/pkg/ovn/controller/egressservice/egressservice_zone_node.go
go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_udn_l2_test.go
go-controller/pkg/ovn/ovn.go
go-controller/pkg/ovn/ovn_test.go
go-controller/pkg/ovn/secondary_layer2_network_controller.go
go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
go-controller/pkg/ovn/secondary_layer3_network_controller.go
go-controller/pkg/util/node_annotations.go
test/e2e/egressip.go

Please read enhancement before review: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4438
Depends on https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4530

L2 UDN: EgressIP hosted by primary interface (`breth0`)

---

dist/images/Dockerfile.ubuntu.arm64

This PR adds nftables binaries to ubuntu arm image
Fixes #

Add nftables binaries to ubuntu arm image

---

dist/templates/k8s.ovn.org_routeadvertisements.yaml.j2
go-controller/pkg/crd/routeadvertisements/v1/types.go

Add missing enum validation for RouteAdvertisements

---

helm/basic-deploy.sh

Enhance the script to use the updated OVN Kubernetes organization.
Add options to easily toggle building the Docker image and 
deploying with or without OVN Interconnect when setting up 
the kind cluster.

Helm fix basic deploy.sh

---

test/scripts/traffic-flow-tests.sh

Also, use commit https://github.com/ovn-kubernetes/kubernetes-traffic-flow-tests/commit/3e092f2c448bdffcddd5d025b97df53145ccea62

Use kubernetes-traffic-flow-tests new repo

---

go-controller/pkg/node/gateway_shared_intf.go

can not update gateway IP if nodePort is disabled

---

test/e2e/network_segmentation.go

The test "Network Segmentation when primary network exist, UserDefinedNetwork status should report not-ready" may flake in case the tested UserDefinedNetwork instance conditions are not populated on the expected time.
This PR stabilize the test by wrapping the failing assertion with Eventually, so that the test wait for conditions to populate.
Fixes #

e2e,net-seg,udn: Wait for condition to populate

---

dist/images/ovnkube.sh
go-controller/pkg/node/gateway_shared_intf.go

This PR adds OVS bridge flows to handle VLAN tagged traffic to/from external interface
Fixes #
```release-note
```

Update OVS bridge flows for supporting gateway VLANs

---

test/e2e/network_segmentation.go

netConfig pointer was being modified in a loop so pods were removed from only one namespace.

Fix pods cleanup in ClusterUserDefinedNetwork test

---

test/e2e/network_segmentation.go

Instead of deleting the pods from one network to check isolation on the other towards those IPs, use different http port per network to check isolation

e2e, pudn: Use port to check overlapping isolation

---

go-controller/pkg/clustermanager/userdefinednetwork/controller.go

When a namespace is removed it shouldn't be considered as an error during reconciliation.
cc: @ormergi

Ignore removed namespaces in clustermanager

---

docs/api-reference/userdefinednetwork-api-spec.md

This commit changes are result of the following command:
crd-ref-docs --source-path ./go-controller/pkg/crd/userdefinednetwork --config=crd-docs-config.yaml --renderer=markdown --output-path=./docs/api-reference/userdefinednetwork-api-spec.md
This is a cleanup after https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4933

docs: update (C)UDN CRD reference.

---

go-controller/pkg/clustermanager/pod/allocator.go
go-controller/pkg/ovn/base_network_controller.go

There is a chance that the pod deletion will come after the primary network is already removed so we cannot rely on `getActiveNetworkForPod` returning no error during pod deletion.

Accept no active network during pod deletion in the IP allocator

---

go-controller/pkg/factory/factory.go

Clone raFactory in ShallowClone

---

go-controller/pkg/node/udn_isolation.go
go-controller/pkg/node/udn_isolation_test.go

Avoid spamming errors for pods that just don't have IPs assigned yet.
Fixes #

[UDN: host isolation] don't return error for pods with no IPs assigned.

---

contrib/kind.sh

Currently, IPV6 deployment of Kind with RUN_IN_CONTAINER flag [1] fails, the root cause seems to be setting of IPV4 address of master node in the server field in Kubeconfig [2] instead of the IPV6 address.
This PR sets the server IP address in Kubeconfig considering IP family type.
[1] KIND_IPV4_SUPPORT=false KIND_IPV6_SUPPORT=true RUN_IN_CONTAINER=true ./contrib/kind.sh 
[2]
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/contrib/kind.sh#L1078
Fixes #

Fix Kind IPV6 deplyoment with RUN_IN_CONTAINER

---

go-controller/pkg/clustermanager/egressip_controller_test.go

During UDN we added syncEgressIPMarkAllocator
which is called when WatchEIP is started as a global syncFunc
that causes an extra patch operation that
causes an extra event. So update the test to
reflect that.
Fixes #4968 
@martinkennelly PTAL

Fix CM-EIP controller UT flake

---

go-controller/pkg/clustermanager/network_cluster_controller.go

So we can actually see what happens when cluster manager starts a new network controller

Add better logging for cluster manager network controller

---

go-controller/pkg/clustermanager/network_cluster_controller.go

When a node would no longer have an error, the code would search for the next node that has an error and report that. However, it would not update the error message and report the error message for the old node. It was also not detecting the next error node properly, by not checking if its error message was empty or not.

Fix updateNetworkStatus

---

helm/ovn-kubernetes/values-single-node-zone.yaml

NIT: remove duplicate line in helm value file.

helm: remove duplicate key in values-single-node-zone.yaml: enablePersistentIPs

---

go-controller/pkg/ovn/egressip.go
go-controller/pkg/ovn/egressip_test.go

Today we have an event driven strategy for egress IP where any of these events can force egress IP reconcilation:
1. egressIP object change
2. namespace change
3. pod change
All 3 of these are called from different threads. These threads all block each other by using a single global mutex called podAssignmentMutex. The problem here is that pod and namespace handlers find what egressIP affects their objects, and then waits for the mutex, to then program egressIP state. They essentially can operate on old data, which causes configuration issues between the three threads. Take this example:
1. Egress IP exists, with status node 1
2. Simultaneously pod is x is created in y namespace, selected by egress IP
3. Pod and namespace handlers fire, get current Egress IP on node1, wait for …

Serialize egress IP handling

---

go-controller/pkg/util/kube.go

this commit change the recorder name to better represent that is related to ovn-k
Fixes #

change recorder name to better representation

---

go-controller/pkg/clustermanager/userdefinednetwork/controller_helper.go
go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template.go
go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template_test.go
go-controller/pkg/node/default_node_network_controller.go
go-controller/pkg/node/gateway.go
go-controller/pkg/node/gateway_init.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/gateway_udn.go
go-controller/pkg/node/gateway_udn_test.go
go-controller/pkg/node/management-port.go
go-controller/pkg/node/openflow_manager.go
go-controller/pkg/node/secondary_node_network_controller.go
go-controller/pkg/ovn/base_network_controller.go
go-controller/pkg/ovn/default_network_controller.go
go-controller/pkg/ovn/gateway.go
go-controller/pkg/ovn/secondary_layer2_network_controller.go
go-controller/pkg/ovn/secondary_layer3_network_controller.go
go-controller/pkg/ovn/secondary_localnet_network_controller.go

This commit adds capability to advertise an user defined L3
primary network over providers network. This commit takes care
of implementation required while using either shared gateway
mode or local gateway mode.
This commit introduces various Reconcile function for different
controllers so that node and ovn resources gets reconciled upon
advertising an user defined network.
As part of those Reconcile functions, following resources gets
added or removed to allow traffic from outside network when the
network is advertised:
- OpenFlow flows. For shared gateway mode, one priority 16 flow
gets added to forward traffic to patch port. For local gateway mode,
one priority 15 flow gets added to forward traffic to LOCAL port.
- SNAT rule from ovn_cluster_router specific to and UDN gets removed
when …

Add BGP support for UDN

---

go-controller/pkg/clustermanager/routeadvertisements/controller.go
go-controller/pkg/clustermanager/routeadvertisements/controller_test.go

If MultiProtocol is enabled (default) then a BGP session carries prefixes of both IPv4 and IPv6 families. Our problem is that with an IPv4 session, FRR can incorrectly pick the masquerade IPv6 address (instead of the real address) as next hop for IPv6 prefixes and that won't work. Note that with a dedicated IPv6 session that can't happen since FRR will use the same address that was used to stablish the session. Let's enforce the use of DisableMP for now.

RouteAdvertisements: fail if DisableMP is unset

---

MEETINGS.md
mkdocs.yml
requirements.txt

MKDocs deploy is broken, we need a CI lane to pre-catch things like this but for now this fix should do it.
I'll try to add a CI lane for deploy test for website but as of now changes to docs is not rendering on website so let's fix that
Fixes: #5108

awesome-pages became awesome-nav

---

test/e2e/multihoming_utils.go

cc @tssurya 
Blocking downstream testing as pod sec context isnt defined.

E2Es: drop container rights for unpriv pods

---

contrib/kind-common
contrib/kind.sh

We are in the process of removing passt from ipam controller we should remove it from kind.sh

kind: Remove passt

---

docs/okeps/okep-5085-localnet-api.md
mkdocs.yml

Introduce API for Localnet topology networks.
This proposal outlines the Localnet API utilizing OVN-Kubernetes ClusterUserDefinedNetwork (CUDN) CRD.
And extending the CUDN CRD to allow creating localnet topology networks.
Tracking issue https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5085 
Fixes #

docs,okeps: Localnet API proposal

---

go-controller/pkg/clustermanager/endpointslicemirror/endpointslice_mirror_controller.go
go-controller/pkg/clustermanager/routeadvertisements/controller.go
go-controller/pkg/clustermanager/routeadvertisements/controller_test.go
go-controller/pkg/controllermanager/controller_manager.go
go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
go-controller/pkg/ovn/ovn_test.go
go-controller/pkg/ovn/routeimport/route_import.go
go-controller/pkg/ovn/secondary_layer2_network_controller.go
go-controller/pkg/ovn/secondary_layer3_network_controller.go
test/e2e/route_advertisements.go

Add BGP support for Layer2 primary UDN in shared gateway mode.
Local gateway mode support will be added separately.

SGW Support for BGP support for L2 UDN

---

.github/workflows/docs.yml
docs/ci/ci.md

add job to test github pages deployment

---

mkdocs.yml

Relates to https://github.com/cncf/sandbox/issues/302#issuecomment-2746388067

chore: update footer with trademark disclaimer

---

.github/workflows/docs.yml
docs/developer-guide/documentation.md
mkdocs.yml
requirements.txt

Fixes https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5108 again, now using Jamo's change in https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5178 .
Partially revert https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5110 .
Fixes: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5177

Fix: Website navigation is broken

---

go-controller/pkg/node/gateway.go

Today, we require that VF accelerated gateway interface must be explicitly configured. This change allows VF based accelerated gateway interface without explict configuration.
Fixes #

detect VF accelerated gateway interface without explicit configuration

---

MAINTAINERS.md

Thanks @dcbw for all your contributions! Whenever you choose to come back the process to get you back to maintainer should be fast as per our governance.
Welcome @npinaeva to maintainer role. It's more than just PR merges LOL, Happy to have you share that burden :)
cc @trozet @girishmg @jcaamano

Add Nadia Pinaeva to maintainer's list

---

go-controller/pkg/ovn/base_network_controller.go

gateway_mtu should be set on router ports only if node supports it

---

test/e2e/service.go

The test "Load Balancer Service Tests with MetalLB Should ensure connectivity works on an external service when mtu changes in intermediate node" relied on forwarding traffic through localhost into the cluster docker kind network. I was able to reproduce it locally and looking into filter rules, that traffic is dropped and requires an additional rule to allow it.
I do not know what change triggered the failure. It looks like it might have been a docker update in the github runner image [1].
[1] https://github.com/actions/runner-images/commit/ce61c11aaca04737a02288ec2ad5cc0c3b2d74c3
Fixes https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5234

Fix LB service e2e test

---

go-controller/pkg/node/node_ip_handler_linux.go

This PR fixes the issue of node-encap-ips not getting updated when the node's primary IP changes. This breaks geneve traffic in IC as the nodes rely on this annotation to update their records of remote nodes. 
Fixes #

Update node-encap-ips annotation when primary ip changes

---

go-controller/pkg/node/gateway_nftables.go
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/gateway_udn_test.go
go-controller/pkg/testing/networkmanager/fake.go

Node port watcher sync: ignore ns with no valid network

---

go-controller/pkg/node/default_node_network_controller_test.go
go-controller/pkg/node/gateway_init_linux_test.go
go-controller/pkg/node/managementport/port_linux.go
go-controller/pkg/node/managementport/port_linux_test.go
go-controller/pkg/node/obj_retry_node.go
go-controller/pkg/ovnwebhook/nodeadmission.go
go-controller/pkg/types/const.go
go-controller/pkg/util/node_annotations.go
go-controller/pkg/util/node_annotations_unit_test.go

This PR enables adding subnets to the don't SNAT list via node annotations, allowing applications to designate traffic that should bypass SNAT.
Fixes # https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5082
Currently traffic gets SNATed at ovn-k8s-mp0 within the mgmtport-snat chain. Since OVNK has transitioned to nftables, this behavior can no longer be overridden.
Previously, with iptables, SNAT could be avoided by adding a higher-priority rule in the POSTROUTING chain. However, with nftables, all rules are evaluated before making a final decision, making it impossible to skip SNAT.
Some applications, like Submariner, need to preserve the source IP when traffic reaches the destination pod, as certain use cases depend on it.
This PR allows users to add subnets to don't SNAT list …

Enable SNAT bypass in mgmtport-snat chain for specified subnets

---

test/e2e/kubevirt.go

When collecting the logs after a failed test run, test name is used as a part of the file path, and double quotes are not allowed:
```
The following characters are not allowed in files that are uploaded due
to limitations with certain file systems such as NTFS. To maintain file
system agnostic behavior, these characters are intentionally not
allowed to prevent potential problems with downloads on different file
systems.
```
ref: https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/15607653555/job/43962954391?pr=5202
Fixes #

[e2e] kubevirt: generate test name that is compatible with file path.

---

test/e2e/acl_logging.go
test/e2e/e2e_suite_test.go
test/e2e/egress_firewall.go
test/e2e/egress_services.go
test/e2e/egressip.go
test/e2e/egressqos.go
test/e2e/external_gateways.go
test/e2e/feature/features.go
test/e2e/gateway_mtu.go
test/e2e/kubevirt.go
test/e2e/label/component.go
test/e2e/label/label.go
test/e2e/label/override.go
test/e2e/multi_node_zones_interconnect.go
test/e2e/multicast.go
test/e2e/multihoming.go
test/e2e/network_segmentation.go
test/e2e/network_segmentation_endpointslices_mirror.go
test/e2e/network_segmentation_policy.go
test/e2e/network_segmentation_services.go
test/e2e/node_ip_mac_migration.go
test/e2e/ovspinning.go
test/e2e/service.go
test/e2e/status_manager.go
test/e2e/testcontext.go
test/e2e/unidling.go

This will allow us to filter tests based on features.
cc @trozet

SDN-5676: Add component + feature name to e2e tests

---

dist/images/Dockerfile.fedora

Thus, we make sure to use the compatible ovs version by default, otherwise OVN may not be built correctly.
When I tried to build ovn using current version, I have got a failure https://productionresultssa8.blob.core.windows.net/actions-results/f1d79533-2387-49f1-a0e0-f3d41be2feba/workflow-job-run-ea8873ba-a1db-5e2f-87e3-50ec1407f82f/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-07-14T07%3A55%3A10Z&sig=L14t06WvfeqZabFlC1NrWKqM1ha2LU7d81QAS2f%2B7c8%3D&ske=2025-07-14T19%3A23%3A50Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-07-14T07%3A23%3A50Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-07-14T07%3A45%3A05Z&sv=2025-05-05
Fixes #

[OVN build] Fetch ovs package from the ovn submodule.

---

dist/images/Dockerfile.fedora

Docker.io has rate limits, hence use Quay instead.
Fixes #

images: Use Quay instead docker.io

---

dist/images/Dockerfile.fedora

Before cutting 1.1, let's bump to using latest OVN

Bump OVN to 25.03
