- go-controller/pkg/libovsdbops/loadbalancer.go
- go-controller/pkg/ovn/controller/services/load_balancer.go
- go-controller/pkg/ovn/loadbalancer/loadbalancer.go
- go-controller/pkg/ovn/loadbalancer/types.go
- test/scripts/e2e-kind.sh
Implements Load Balancer Session Affinity TimeOut. Most of the work is in OVN. This PR just sets the needed option on the load balancer to get it to work correctly. We also remove the older method of using selectionFields in OVN.
Based on KIND testing:
```
Name:              hello-world-2
Namespace:         surya
Labels:            <none>
Annotations:       service.kubernetes.io/topology-aware-hints: auto
Selector:          run=load-balancer-example-2
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.169.9
IPs:               10.96.169.9
Port:              <unset>  80/TCP
TargetPort:        8080/TCP
Endpoints: …
```
> Support LB Session Affinity TimeOut

- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/topology_version.go
- go-controller/pkg/util/node_annotations.go
Existing OVN code can be shared by the default network controller and the upcoming secondary layer 3 network controller. Update it to get ready for the seconary layer 3 network support.
> make code shareable for secondary network controller

- go-controller/pkg/libovsdbops/portgroup.go
- go-controller/pkg/ovn/address_set/address_set.go
- go-controller/pkg/ovn/policy.go
With network policy we add handlers that fire on pod events. They typically either add a pod ip to an address set or add the pod port to a port group. This is done via a mutate-insert operation into either the address set or port group. The issue is on pod updates we also do these operations (because sometimes the pod IP/port is not available until after an update event). Functionally this isn't an issue, because mutate will not add duplicate values into the address set or port group. However from a scale/perf perspective this hurts. If we take a pod that has 730 network policies applied to it, we would expect 730 transactions to add it to each policy address set/port group. However, it will actually have 730 x n updates to the pod. That means in a scenario where we have 7 pod updates, …
> Eliminates duplicate transactions for adding to address sets and port groups

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/node.go
- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/net_linux_unit_test.go
Previously, when `LinkRoutesAddOrUpdateSourceOrMTU` found a route with a gateway different from `gwIP` parameter it never updated it.
In the proposed change we update the route if any of the parameters(`gwIP`,`mtu`,`src`) changed.
/cc @tssurya @jcaamano
> LinkRoutesAddOrUpdateSourceOrMTU/LinkRoutesApply: update route GW if it was changed 

- go-controller/pkg/ovn/address_set/address_set.go
- go-controller/pkg/ovn/address_set/address_set_cleanup.go
- go-controller/pkg/ovn/address_set/address_set_test.go
- go-controller/pkg/ovn/address_set/fake_address_set.go
- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
Fix FakeAddressSetFactory.ProcessEachAddressSet locking to allow calling other FakeAddressSetFactory in iteratorFn.
Address set may be owned by one of 5 object types: namespace, network policy, egress firewall dns, egress qos, and hybrid node. Only namespace and network policy are trying to delete stale address sets on initial sync.
Previously namespace considered address sets that don't have dots in its name to be owned by namespace and network policy considered everything with the dot to be owned by network policy. This logic was based on network policy address set naming: it has a format of `fmt.Sprintf("%s.%s.%s.%d", policyNamespace, policyName, direction, gp.idx)`. Besides the fact that this logic ignores 3 other owners of address sets, it also ignores the fact that network policy …
> Fix address set cleanup: only delete address sets owned by given object.

- go-controller/pkg/ovn/policy.go
selector to reduce the number of per-namespace pod handlers. We don't need per-namespace handlers in case of empty namespace selector, just use pod selector with empty namespace.
> Use PeerPodHandler if namespaceAndPod selector has empty namespace

- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
- go-controller/pkg/ovn/pods.go
currently there is a race condition when allocating the hybridOverlayDRIP on master startup. 
There is a period of time between when `syncPods()` is finished and the addNode event is retried where a valid addPod event can be processed and allocated an address previously assigned as the nodes hybrid overlay distributed router IP. 
In order to fix this we can allocate the ip address in the nodes `k8s.io/api/core/v1/distributed-router-gateway-ip` annotation during `syncPods()` this will ensure that no future event will allocate the already assigned ip address 
furthermore we can ignore the already allocated error from the ipallocator for the hybridOverlay because we do not support setting the annotations manually and that *should* be the only way there would be a collision. 
Signed-off-by: …
> fix hybrid overlay allocation on the master

- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
Commit 09af6537 moved the LRP creation from ensureNodeLogicalNetwork to syncNodeClusterRouterPort, so that when creating LRP the gateway-chassis can be set, to pin LS to a chassis. However, Commit c58554adfc accidently reverted the change when converting nbctl to libovsdb (it is likely a rebase problem). It creates LRP in ensureNodeLogicalNetwork without setting gateway-chassis, which end up with all existing ovn-controllers change monitor condition to monitor the new LS datapath. And later, when ovnkube-node annotates the chassis-id, ovnkube-master calls syncNodeClusterRouterPort, which updates the LRP and sets the gateway-chassis, so all the ovn-controllers (except the new node) change monitor condition again to remove the LS.
Such monitor condition changes come from every existing …
> Set gateway-chassis when LRP is being created, to avoid scaling problems

- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
- go-controller/pkg/ovn/pods.go
This reverts commit dabaf9fb8e024d8a52fbb1dc470fdce596caf505.
Original PR never passed control plane tests.
> Revert "fix hybridOverlay DRIP address allocation"

- go-controller/pkg/retry/obj_retry.go
For completed resources (pods) we were not processing them if completed
because they should have been handled already during update. However we
may miss an update event where the pod was completed, and only get a
delete event with the pod completed. In this case we were ignoring
deleting the pod and the IP and port would not be cleaned up.
Ideally we would want the delete to be idempotent no matter how many
times it is called. This is true for the deleteLogicalPort path, but not
true for other pod types (peer address set, local pod, egress ip pod
type, etc). Therefore it is currently unsafe to attempt to delete more
than one time. This should be resolved once we have level driven
controllers, but for now we can at least try to do something in the pod
delete event if we know we have never …
> Process completed deleted resources conditionally

- go-controller/pkg/ovn/master_test.go
Data race seen at: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1449/pull-ci-openshift-ovn-kubernetes-master-unit/1603150200489119744/artifacts/test/build-log.txt
> Fix unit tests not shutting down watch factory

- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
- go-controller/pkg/ovn/pods.go
revert https://github.com/ovn-org/ovn-kubernetes/commit/c1ad7d7a02ac510f164aaf09150cae63ad964023 (the reversion of my previous PR)
in order to clean up my previous PR the flag for all initial pods processed has to be moved to before attempting to allocate hybrid overlay addresses in syncPods().
> hybrid overlay DRIP allocation fixup 

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/factory/handler.go
If the priorities of the handlers represent interdependencies between them, it makes sense to process deletes in reverse order of adds to minimize potential problems were a high priority handler deltes something a lower priority handler depends on.
> Process delete handlers in reverse order of priority

- go-controller/pkg/ovn/master.go
Currently when deleting a noHostSubnet node the operation always fails because we are trying to delete ovn constructs that only get created for typical nodes.
Change the deletion of noHostSubnet nodes to only delete the logical switch and in the case of hybrid overlay the allocated subnet. 
> Correct the deletion of noHostSubnet nodes

- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
There is no need to access the leader.
Additionally SBDB is exposed as a single openshift route in HyperShift, even if running in clustered mode.
This change depends on https://bugzilla.redhat.com/show_bug.cgi?id=2152151 
> ovnkube-trace: run ovn-sbctl and ovn-trace with --no-leader-only

- go-controller/pkg/ovn/default_network_controller.go
`setNodeEgressAssignable` sets an egress node as assignable when it exists in the allocator cache, otherwise it does nothing.
Currently the egress node update handler only calls `setNodeEgressAssignable` when it detects that the `nodeEgressLabel` was added/removed.
In cloud environment a node is added to the allocator cache after it gets annotatated with `cloud.network.openshift.io/egress-ipconfig` by CNCC.
In a scenario where a node is labeled for egress IP assignment before it is annotated by CNCC, it never gets set as assignable(`isEgressAssignable`). 
To address that call `setNodeEgressAssignable` on every node update.
It was found in https://issues.redhat.com/browse/OCPBUGS-4969.
> Update egress node assignability on every egress node update

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/node.go
- go-controller/pkg/node/node_test.go
Single node indicates a one node cluster and allows to
simplify ovn-kubernetes feature logic to reduce overall
cpu and memory footprints which are required in small
form factor deployment.
This change enable future work to have optimized logic
for single node ovnk deployment.
> Add single-node gateway config option

- .github/workflows/test.yml
- contrib/kind.sh
- docs/design/service_traffic_policy.md
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_shared_intf_linux.go
- go-controller/pkg/util/kube.go
- test/e2e/e2e.go
- test/e2e/egress_services.go
- test/e2e/service.go
- test/e2e/util.go
- test/scripts/e2e-cp.sh
Curently in LGW mode, when using ETP=local, we use the masqueradeIP .3 and nodePort to DNAT LB VIPs and externalIPs and lure them into mp0. However there can be cases where nodeports don't exist on load balancer services. This PR takes care of this scenario by directly dnat-ing to pod backend in such situations using the IPT random probability algorithm.
Unit test is added to catch the iptable rule changes, e2e's already exist for AllocateLoadBalancerNodePorts https://github.com/kubernetes/kubernetes/blob/00c0c9d880c1448f778bf892c43664081c80d11e/test/e2e/network/loadbalancer.go#L926 but not in combination with ETP=local. So a new one has been added downstream only using metalLB.  …
> Support AllocateLoadBalancerNodePorts=False with ETP=local, LGW mode

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/util/net.go
There might be circumstances where the node status internal IPs
are not current (in our case, a dual-stack conversion procedure in
which kubelet is not configured with the newly acquired IPv6 address
and restarted, which in itself is a problem that would need to be
fixed).
While node status IPs are preferred to avoid issues with IPs that the
user or other components might arbitrarily add to the gateway interface,
fallback to an interface IP if we are missing it from the node status.
Also fix DPU. Masquerading should not be needed in the DPU (when
newSharedGateway is called with mode NodeModeDPU), only in the
host (where initGatewayDPUHost is use instead for NodeModeDPUHost).
Ref: https://github.com/openshift/ovn-kubernetes/blob/master/docs/design/dpu_support.md
Signed-off-by: Jaime …
> addMasqueradeRoute: fallback to gateway interface IPs

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_dns.go
- go-controller/pkg/ovn/egressfirewall_dns_test.go
- go-controller/pkg/ovn/egressfirewall_test.go
- test/e2e/e2e.go
- test/e2e/service.go
Unify egress firewall implementation for both gateway modes,
move all acls to the ClusterPortGroup.
Unify unit tests for both gateway modes.
Make sure egress firewall allows inbound connections.
Don't apply "&& dst != clusterSubnet" to every acl, since that will
generate inefficient conjunctive flows in ovs. Every egress firewall
ACL has "dst = <CIDR selector or dns name address set>", for CIDR
selector only add clusterSubnet exclusion if CIDR selector has
intersection with clusterSubnet. For dns address sets (since they are
only used by egress firewall), don't add ips from clusterSubnet to
dns address set, since we know these ips should be excluded.
> Fix egress firewall to allow inbound connections in both gw modes

- go-controller/pkg/node/gateway_shared_intf.go
This PR fixes two traffic flows:
1) podCIDR to svcCIDR:unexposedPort. This flow currently sends the packets towards br-ex in both gateway modes since OVN LB's won't DNAT and OVN doesn't know what to do then other than to send these packets out. However the argument here is svcCIDR is a private range, these packets shouldn't be sent outside. Hence like SDN let's drop them.
2) nodeCIDR to svcCIDR:unexposedPort. Same as above.
Fix: Add a new flow at 105 priority right above the default 100 priority flow (that sends the pkt out to primary interface if coming from OVN) which will drop it instead of sending it out the primary interface.
```
cookie=0xdeff105, duration=7804.947s, table=0, n_packets=18, n_bytes=1332, idle_age=6984, priority=105,ip,in_port=2,nw_dst=10.96.0.0/16 actions=drop …
```
> Drop in-cluster traffic towards svcCIDR arriving at wrong port

- go-controller/pkg/node/management-port-dpu.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_dpu_test.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/util/mocks/NetLinkOps.go
- go-controller/pkg/util/net_linux.go
When ovnkube-node configures management port interface it may fail if host already have it configured but it is different interface. To handle that do the following:
- verify that port exists on the integrational bridge and it represents provided management port netdevice or OVS internal port, if no netdevice were provided;
- verify that no interface exists with the name of the management port;
If any of the checks had failed then need to remove port from the bridge and if it wasn't OVS internal port - flush IP addresses, routes, tables and rename the interface.
Because ovnkube doesn't have unload sequence, port check done during new management port creation.
Signed-off-by: Dmytro Linkin <dlinkin@nvidia.com>
> ovnkube-node: Existing management port check

- .github/workflows/cleanup.yml
- .github/workflows/commands.yml
- .github/workflows/docker.yml
- .github/workflows/test.yml
- .github/workflows/test_periodic.yml
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/cache@v2, actions/setup-go@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> actions: bump standard GH actions to @v3

- go-controller/pkg/config/utils.go
- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/hybrid.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
There can be a case where multiple routes exist on ovn_cluster_router matching on the same IP prefix. For example:
10.130.0.0/23                100.64.0.4 src-ip ecmp
10.130.0.0/23                100.64.0.6 src-ip ecmp
10.130.0.0/23                100.64.0.9 src-ip ecmp
In this case stale routes exist for old join subnet nexthops matching on
the same host subnet. OVN allows for these extra routes to be added and
considers them ecmp.
This commit modifies our behavior to ensure only a single route exists.
If more than one route for a predicate are found, the additional routes
are removed and then the leftover route is updated with the correct
fields.
A route is considered unique when it has the same prefix and policy type
(dst-ip vs src-ip) on the same router. The only case in OVNK where we …
> Ensure routes are not duplicated

- go-controller/pkg/node/node_ip_handler_linux.go
- go-controller/pkg/node/node_ip_handler_linux_test.go
- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/net_linux_unit_test.go
`I0123 00:45:01.424261 946716 node_ip_handler_linux.go:268] Node address annotation being set to: map[192.168.18.12:{} 2600:52:7:18::12:{} fd69::2:{}] addrChanged: true`
ovn-kube shouldn't be considering the fd69::2 internal masquerade address (or its IPv4 equiavlent) as a node IP address. It gets set by setNodeMasqueradeIPOnExtBridge().
> node: don't consider internal masquerade addresses as node IP addresses

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
Previous to this change, OVN was always evaluating our cluster exclusion ACL match expression to false if we had a match expression that directly compared IP V4 and IP V6 operands. 
Example:
```
(ip4.dst == 0.0.0.0/0) && (ip4.src == $a5154718082306775057 || ip6.src == $a5154715883283518635) && ip4.dst != 10.244.0.0/16 && ip6.dst != fd00:10:244::/48" 
```
Notice at the end of that expression, we have operand "ip6.dst" AND'd with everything previous to it, therefore we always compare to this operand even if the packet is IP V4. OVN doesnt like this and will always evaluate this expression to false for IP V4.
~~This code will need a refactor in the future to consider if an exclusion for IP V6 and/or IP V4 is needed.
For example, if the match expression only contains IP V4 operands, then …
> Fix cluster exclusion for egress firewall in dualstack mode

- go-controller/pkg/libovsdbops/lbgroup.go
- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/libovsdbops/switch.go
- go-controller/pkg/ovn/loadbalancer/loadbalancer_test.go
use ErrNotFound=false for operations that delete loadbalancer from swtich, router, and port group. If a given object is not found, it's noop and not error. Delete LBCache methods RemoveSwitch and RemoveRouter, since they were only used to avoid deletion error, which won't happen anymore.
> Ensure loadbalancer cleanup doesn't fail

- go-controller/pkg/cni/ovs.go
- go-controller/pkg/node/node.go
The pkg/cni OVS exec operations don't lock the runner variable, partly for performance reasons (since multiple podRequests could be in-flight at the same time). This causes a race where one pod operation found 'runner == nil', calls SetExec() which sets 'runner = r', but before the first operation can find the OVS binaries a second pod operation finds 'runner = [something]' and proceeds to call os/exec functions with an empty path.
```
W1212 22:57:22.431136    5515 helper_linux.go:588] Failed to delete pod "openshift-kube-scheduler/revision-pruner-7-ip-10-0-181-91.us-west-2.compute.internal" OVS port 14b76a3e6667536: failed to run 'ovs-vsctl --timeout=30 del-port br-int 14b76a3e6667536': exec: no command
""
""
```
This sometimes happens on ovnkube-node startup when kubelet already has …
> node/cni: initialize OVS exec runner early to prevent races

- docs/design/host_to_services_OpenFlow.md
- go-controller/pkg/ovn/gateway/gateway.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/hybrid_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace_test.go
There remained a dependency for return service traffic from OVN->Host where OVN would need to think it was routing towards the default gw. Once this traffic made it into the shared gw bridge, it would be hijacked and redirected back to the Host. This only applied to clusters where a default gateway exists. In a cluster with no default gateway, the default route for OVN pointed to a fake gw (169.254.169.4) with a static MAC binding for this address.
However, in a cluster where there is a default gateway, but we are unable to ARP and create a MAC binding, return service traffic will fail to be routed. This commit changes the behavior so that:
1. Dummy GW MAC bindings are always created
2. Always add a route destined to the dummy masquerade subnet via dummy GW. Like "169.254.169.0/29 via …
> Fully remove dependency on default gateway for services

- go-controller/pkg/network-controller-manager/network_controller_manager.go
When multi network feature is not enabled,
the nadController will be nil. So while stopping
the controllers, we need to check if nadController is nil or not, else we'll panic.
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x193c7ee]
```
goroutine 1 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*netAttachDefinitionController).GetAllNetworkControllers(0x0)
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/network-controller-manager/network_attach_def_controller.go:307 +0x2e
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*networkControllerManager).Stop(0xc000540210) …
```
> Fix panic if nadController is nil

- go-controller/pkg/ovn/controller/egress_services/egress_services_node.go
It can happen that node got deleted, but then
we have already deleted nodeState from the cache
because node was not ready or not reachable?
In those cases do nothing and return from syncNode since we can neither remove the address-set nodeIPs from the route nor add the node.
```
E0201 17:09:28.513834       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 568 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1b67100?, 0x3059000})
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000d3cbf0?}) …
```
> Fix panic when node is deleted and state is also not present

- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
There is an unknown scenario where stale pod snat entries are found for egress ip which refers to an unassigned node. This pr ensures those stale entries are deleted in sync stale logic and also making sure that egress ip reconcile does not break because of this entry, otherwise it may lead to "unexpectedly found multiple results for provided predicate" error in DeleteNATsWithPredicateOps.
> Delete stale egress ip snat entries by node

- go-controller/pkg/ovn/controller/services/services_controller_test.go
- go-controller/pkg/ovn/loadbalancer/loadbalancer.go
NB.Load_Balancer.options:neighbor_responder controls generation of logical flows for routers in order to reply to ARP/ND request for a VIP.
Default value is 'reachable' that means that routers on which the load balancer is applied should reply to ARP/ND requests only for VIPs that are part of a router's subnet.
However, there seems to be no such VIPs in ovn-k setups.  And the function that is looking for them is one of the heaviest functions in ovn-northd that can take up to 30% of the northd processing.
Switching this option to 'none' should noticeably reduce load on northd in LB-heavy scenarios.
The 'none' option is available since OVN 22.12, older OVN versions will just ignore it using a default 'reachable' value.
Signed-off-by: Ilya Maximets \<i.maximets@ovn.org\>
I observed the …
> loadbalancer: Disable generation of neighbor responder flows for VIPs on LRs

- go-controller/go.mod
- go-controller/go.sum
- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/libovsdbops/chassis.go
- go-controller/pkg/libovsdbops/chassis_test.go
- go-controller/pkg/libovsdbops/model.go
- go-controller/pkg/testing/libovsdb/libovsdb.go
- go-controller/vendor/github.com/ovn-org/libovsdb/cache/cache.go
- go-controller/vendor/github.com/ovn-org/libovsdb/cache/uuidset.go
- go-controller/vendor/github.com/ovn-org/libovsdb/client/client.go
- go-controller/vendor/github.com/ovn-org/libovsdb/client/monitor.go
- go-controller/vendor/github.com/ovn-org/libovsdb/database/database.go
- go-controller/vendor/github.com/ovn-org/libovsdb/database/errors.go
- go-controller/vendor/github.com/ovn-org/libovsdb/database/mutate.go
- go-controller/vendor/github.com/ovn-org/libovsdb/database/transaction.go
- go-controller/vendor/github.com/ovn-org/libovsdb/mapper/mapper.go
- go-controller/vendor/github.com/ovn-org/libovsdb/ovsdb/serverdb/database.go
- go-controller/vendor/github.com/ovn-org/libovsdb/server/server.go
- go-controller/vendor/modules.txt
IGMPGroup has a weak link to chassis, deleting multiple chassis may result in IGMP_Groups with identical values on columns "address", "datapath", and "chassis", when "chassis" goes empty
Error message example:
```
error:constraint violation Details:Transaction causes multiple rows in "IGMP_Group" table to have identical values 
(mrouters, 038b16fa-6aba-4244-9d4f-00a1e2cbf9a2, and []) for index on columns "address", "datapath", and "chassis".  
First row, with UUID 7e9a18fa-e58c-4547-a7cb-afa934b6cdc9, had the following index values before the transaction: 
mrouters, 038b16fa-6aba-4244-9d4f-00a1e2cbf9a2, and d9755997-e909-4d0c-8770-82a902d69a90.  Second row, with 
UUID 84da3622-3ac7-41f0-a6b5-536a2d5f9137, had the following index values …
```
> Delete IGMP Groups when deleting stale chassis.

- docs/multi-homing.md
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
This PR provides end user documentation on how to use the multi-homing feature.
End user documentation for the multi-homing feature.
> multi-homing, docs: provide multi-homing user documentation

- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/hybrid.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/net.go
- go-controller/pkg/util/net_unit_test.go
- go-controller/pkg/util/node_annotations.go
Refactor egress IP assignment so that all operations are done as a single libovsdb transaction.
Commit egress IP pod assignment as one transaction with the following ops:
1. Add SNAT towards egress IP on egress gw router
2. Add a router policy to forward pod traffic to the egress node
3. Delete SNAT towards nodeIP(only if the egress node is the same as the pod host)
Commit egress IP pod assignment removal as one transaction with the following ops:
1. Add SNAT towards nodeIP(only if the egress node is the same as the pod host)
2. Remove router policy that forwards pod traffic to the egress node
3. Remove SNAT towards egress IP from the egress node
NOTE: Unfortunately there is still a chance that the flow won't be configured when the packet arrives at the egress node but it is less likely …
>  Refactor egress IP assignment so that all operations are done as a single libovsdb transaction

- go-controller/Makefile
- go-controller/hack/build-go.sh
LDFLAGS="-w -s" reduces ~10M size for each ovnk binary
w/ LDFLAGS="-w -s":
-rwxrwxr-x. 1 root root  37M Feb  7 10:20 hybrid-overlay-node 
-rwxrwxr-x. 1 root root  35M Feb  7 10:20 ovndbchecker 
-rwxrwxr-x. 1 root root  35M Feb  7 10:20 ovn-k8s-cni-overlay 
-rwxrwxr-x. 1 root root  45M Feb  7 10:20 ovnkube
-rwxrwxr-x. 1 root root  30M Feb  7 10:21 ovnkube-trace 
-rwxrwxr-x. 1 root root  31M Feb  7 10:20 ovn-kube-util
w/o LDFLAGS="-w -s":
-rwxrwxr-x. 1 root root  52M Feb  7 10:28 hybrid-overlay-node 
-rwxrwxr-x. 1 root root  49M Feb  7 10:28 ovndbchecker 
-rwxrwxr-x. 1 root root  50M Feb  7 10:28 ovn-k8s-cni-overlay 
-rwxrwxr-x. 1 root root  64M Feb  7 10:28 ovnkube
-rwxrwxr-x. 1 root root  42M Feb  7 10:28 ovnkube-trace 
-rwxrwxr-x. 1 root root  44M Feb  7 10:28 ovn-kube-util …
> Enable LDFLAGS when building ovnk binaries

- .github/workflows/test.yml
- contrib/kind-dual-stack-conversion.sh
- test/Makefile
- test/scripts/e2e-kind.sh
The dualstack jobs are flaky, and keep causing red CI. These jobs are not really valuable as we do not find many bugs from them. We have tried multiple times to root cause why the flakes happen, but to no success.
- Remove running local gateway mode conversion. There should not be any real difference anymore between the two modes that affect dualstack.
- Add a sleep after conversion. This may help with letting the system settle after conversion before tests are executed.
- Stop running CI tests before and after conversion. We already have a dualstack and single IP family jobs that will run conformance tests. We only need to run after conversion.
- Skip test that always flakes for dualstack conversion: should function for service endpoints using hostNetwork
Signed-off-by: …
> Consolidate dualstack conversion jobs

- docs/metrics.md
- go-controller/pkg/metrics/master.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/retry/obj_retry.go
The resource event handling has 15 max retries upon failures. once it reaches the limit, it won't be tried agin and logged with an warning message.
Now this exposes it as resource_max_retry_failed prometheus counter metric for both master and node when retries failed.
> Expose resource max retry failed metric

- go-controller/pkg/node/gateway_init.go
- test/e2e/service.go
Until we fix bug https://bugzilla.redhat.com/show_bug.cgi?id=2169839 we cannot remove the MTU from the service route.
We also have https://issues.redhat.com/browse/OCPBUGS-7609 that is plugin agnostic but a potential issue that is hard to solve. In the interim since the host->other NodePort flow is a rare use case, let's flush the routes from cache in our e2e tests for now. This will also be the recommended workaround for users who want to use UDP+frag in our setups within 5 mins after a node->otherNodePort traffic flow.
> Flush route cache from all nodes

- go-controller/pkg/node/gateway_shared_intf.go
Now that OVN is capable of sending ICMP needs frag for PMTU discovery,we
no longer need to proxy that capability in the host.
However, there seems to be a bug with this feature when trying to send
OVN a packet that is too large:
https://bugzilla.redhat.com/show_bug.cgi?id=2169839
This commit only changes to remove the MTU specified on the
169.254.169.1 route. This is the OVNMasquerade IP and is only used when
hairpinning traffic back to the node which will end up at a host network
pod. Therefore there is no reason to restrict its MTU as we are never
forwarding to an OVN networked pod in this case.
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/3419
> Remove MTU on service routes

- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/node/node_dpu_test.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_unit_test.go
- test/e2e/multihoming.go
This PR allows users to create flat L2 secondary networks without IPAM to be used by multi-homed pods.
This is useful especially for virtualization scenarios, where users manage IP addresses on their own - and thus enables KubeVirt to lift and shift existing VMs from traditional virtualization / cloud technologies.
These are the relevant contents of the NB database:
```
_uuid               : aecf79fd-efd1-48f8-980c-456b06d9efbb
acls                : []
copp                : []
dns_records         : []
external_ids        : {k8s-ovn-topo-version="5", "k8s.ovn.org/network"=l2-network, "k8s.ovn.org/topology"=layer2}
forwarding_groups   : []
load_balancer       : []
load_balancer_group : []
name                : …
```
> Multi homing l2 topology optional ipam

- go-controller/cmd/ovnkube/ovnkube.go
When running ovnkube master and node in a single process,
ovnkube node fails silently (doesn't exit) if there is error starting
node since the ovnkube master keeps running and prevents
the process from exiting. This commit adds a log message for
easy debugging when ovnkube node fails but ovnkube master
doesn't fail.
> Print ovnkube node exit error

- docs/metrics.md
- go-controller/pkg/cni/ovs.go
- go-controller/pkg/metrics/ovs.go
This adds two metrics to track total number of OF ports and checks how many times ovnk attempted to validate whether port is up or not (ovs_interfaces_total and ovs_interface_up_wait_total). These metrics is useful to trace down issues known to be problematic.
> Add metrics pod ovs ports

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/healthcheck.go
- go-controller/pkg/ovn/controller/services/lb_config.go
- go-controller/pkg/ovn/multicast.go
- go-controller/pkg/util/kube.go
- go-controller/pkg/util/kube_test.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/util.go
Master, node and healthcheck code looked up the Ready field in endpoints inside endpointslices, in line with the previous implementation that dealt with the older and less fine-grained Endpoints resource, that only distinguished between ready and not ready. Healthchecks should indeed rely on the Ready field, while node and master could look up the "Serving" field, so that we won't prematurely refuse incoming connections to an endpoint that is scheduled to be terminating but is still up and running.
Making a special case for services with PublishNotReadyAddresses set, as their endpoints should always be considered ready, even if terminating. A couple of upstream kubernetes tests use this feature in 1.26.
More context in this comment from the jira bug: …
> OCPBUGS-6947: Check the "Serving" field for endpoints

- contrib/kind.sh
if that repo exists when re-running kind it will throw and error during the install_metallb() step when it tries to clone it. the repo is removed later in the install_metallb() step, but if something breaks or exits before that happens it could be leftover making the clone step on the next install fail. You could check if the repo folder exists before hand, but then you would not be using the latest version of the repo... or would have to add steps to pull the latest which could get more complicated if files are potentially modified. this is simple enough.
> rm metallb repo in destroy_metallb() function

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/healthcheck_node.go
- go-controller/pkg/node/healthcheck_node_test.go
- go-controller/pkg/node/healthcheck_service.go
- go-controller/pkg/node/openflow_manager.go
For Cluster traffic policy services every node should accept
traffic and balance to a node with an endpoint for that service.
The cloud LB periodically health checks each node to know what
nodes it can send traffic to.
For Local traffic policy the cloud LB health-checks the specific
service's port on every node to determine whether that node has
any endpoints for the service, so no node-level health checks
are needed.
GCE's legacy cloud provider hardcodes port 10256 (the default
kube-proxy port) for its node-level health checks.
kube-proxy starts a healthz server on port 10256 on every node
for Cluster traffic policy services. ovnkube didn't do that,
so in some cases the cloud LB wouldn't consider nodes healthy.
While we're here split the node healthcheck into "node" and "service"
files …
> node: add node healthz server for cloud load balancers

- test/e2e/multihoming.go
This PR ensures the pods and network-attachment-definitions on the test namespace are deleted
between test executions.
This is required to prevent the tests on this particular test suite (multi-homing) from flaking.
IMO, we should still investigate the underlying issue, to make sure we're not masking any real issues.
Run the e2e tests.
Clean up the namespace entities between test executions for the multi-homing test suite.
> e2e, multi-homing: randomize the network names used in tests

- go-controller/pkg/clustermanager/clustermanager.go
Currently, we have two LEs  in main,
however, LE framework only allows setting
a provider once for these LE metrics, and since
CM is set first, its LE metrics are used and
master (NCM) are ignored.
Lets depend on master (NCM) LE metrics for now as
downstream, we depend on this for alerts.
```
func (f *leaderMetricsFactory) setProvider(mp MetricsProvider) {
f.onlyOnce.Do(func() {
f.metricsProvider = mp
})
}
```
> Depend only on ovnkube master LE metrics

- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
Completed pods IP addresses can collide with running pods and they can be deleted after a period of time by the kube-controller-manager garbage collector [1].
Add an OVN controller test to avoid regressions on this scenario.
[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
> netpol: Ensure Completed pods deletion works

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/policy.go
Add MetricMasterSyncDuration metric to track how much it takes for
ovn-k master to start watching every resource.
Add scale metrics for network policies, rename existing
enable-eip-scale-metrics flag to more general enable-scale-metrics, and
use it for network policy metric too.
Add an option to enable scale metrics in kind 
For anyone who would like to test this, `ovnkube_master_sync_duration_seconds` is enabled by default. To check scale metrics use newly added `kind.sh` flag `--scale-metrics`
To fetch master metrics `curl <ovn-k master leader ip>:9409/metrics`
> Add performance metrics for initial sync and netpol

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
even when the acl name is cropped. That happens when namespace name is longer than 43 symbols.
> Add egress firewall external id to make name+externalIDs unique

- go-controller/pkg/libovsdbops/acl.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/master.go
This commit ensures we truncate names as a precaution
also in CreateOrUpdateACLsOps so that our bases are
covered since not all code snippets call BuildACL
directly
NOTE: The first commit adds a test to showcase that we actually weren't truncating. Test server is not smart enough to scream like real ovsdb server so it won't complain :/ See https://github.com/ovn-org/libovsdb/issues/338.
Second commit does the fix and changes the test case
> Fix syncEgressFirewall (truncate ACL names) and SetupMaster (stop recreating cluster-wide PGs)

- docs/multi-homing.md
This commit adds a section to the user documentation explaining how to configure the following data for a pod's attachment:
- IP address
- MAC address
- pod interface name
> docs, multi-homing: secondary attachment config via net-selection-elements

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/util/batching/batch.go
- go-controller/pkg/util/batching/batch_test.go
The default transaction timeout is 10 seconds, it can be reached when we delete all egress firewall acls during migration to port groups from switches.
I reproduced the bug trying to delete 3M acls with random-generated UUIDs from 1 worker switch, and measured the time it takes to transact the changes on a kind cluster, here are the results:
2M(no batching) = 9.08 s
100000/batch = 7.66 s
10000/batch = 6.6 s
1000/batch = 6.97 s
Say we have 1000 nodes * 1000 ACLs ~= 1M ACLs * 1 switch = 4.38 s
That is a rough explanation for `defaultBatchSize = 1000`
I also updated `RemoveACLsFromLogicalSwitchesWithPredicateOps` to only delete acls that are present on the switch, since this op will be generated unconditionally on every sync
> Batch potentially big transaction on egress firewall ACLs migration.

- go-controller/go.mod
- go-controller/go.sum
- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/vendor/golang.org/x/sync/LICENSE
- go-controller/vendor/golang.org/x/sync/PATENTS
- go-controller/vendor/golang.org/x/sync/errgroup/errgroup.go
- go-controller/vendor/modules.txt
NAD controller would wait for the workers to be terminated before shutting down the worker queue. In turn the workers could be endlessly waiting for the queue to be shut down. This results in the NAD controller never actually stopping.
Improved also how the network controllers are stopped for which we wait until the NAD controller workers have effectively terminated.
> Fix NAD controller Stop

- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
Egress firewall creation error was overridden by the status update
error and never returned. That would prevent retry on failure.
It worked before because the error was reassigned locally https://github.com/openshift/ovn-kubernetes/blob/release-4.11/go-controller/pkg/ovn/obj_retry.go#L681.
Fix egress firewall unit tests gatewayMode setup
update "egress firewall with node selector updates during node update"
to work for both gateway modes.
> Egress firewall fix retry

- contrib/kind.sh
- contrib/kind.yaml.j2
- dist/images/daemonset.sh
- docs/kind.md
This allow to use kind.sh and `--deploy` with kind local registry.
kind: Support local registry at "--deploy"
> kind: Support local registry at "--deploy"

- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/util/pod_annotation.go
when addLogicalPortToNetwork() fails after it successfully allocated pod IPs and updated the pod annotation, there is a case new pod IPs can be allocated to the pod during retry if the informer cache does not cache up with the latest pod annotation update. This would cause leak of the old IPs allocated to the pod.
> fix potential pod IP leak in case that addLogicalPortToNetwork() fails

- test/e2e/e2e.go
- test/e2e/egressip.go
- test/e2e/service.go
In the hairpin SNAT e2e test case I was pinning
the nodePort of the service created when that was not really necessary.
So when in times of flake, CI re-runs this test we run into
```
2023-03-07T09:33:02.1112035Z [1mSTEP[0m: creating a TCP service service-for-pods with type=NodePort in namespace service-hairpin-test-2286 2023-03-07T09:33:02.1162862Z Mar  7 09:33:02.116: FAIL: unable to create service: service-for-pods, err: Failed to create service service-for-pods service-hairpin-test-2286: Service "service-for-pods" is invalid: spec.ports[0].nodePort: Invalid value: 32766: provided port is already allocated 2023-03-07T09:33:02.1163500Z Unexpected error:
2023-03-07T09:33:02.1163792Z     <*errors.withStack | 0xc000f8d188>: {
2023-03-07T09:33:02.1164046Z         error: { …
```
> e2e: Don't pin nodePort

- go-controller/pkg/ovn/controller/services/lb_config.go
- go-controller/pkg/ovn/controller/services/lb_config_test.go
- test/e2e/unidling.go
Ensure pods can connect to an idled ClusterIP
service at the first attempt without getting
any TCP Reject or connection timeout.
The test currently fails, as the TCP connection from the execpod to the service gets conntracked when there is no endpoint available:
```
[root@ovn-control-plane ~]# ovs-dpctl -t 1618  dump-conntrack  | grep 10.244
// what is happening ()
tcp,orig=(src=10.244.2.8,dst=10.96.207.68,sport=41338,dport=80),reply=(src=10.96.207.68,dst=10.244.2.8,sport=80,dport=41338),zone=9,mark=2,protoinfo=(state=SYN_SENT)
tcp,orig=(src=10.244.2.8,dst=10.96.207.68,sport=41338,dport=80),reply=(src=10.96.207.68,dst=10.244.2.8,sport=80,dport=41338),zone=7,mark=6,protoinfo=(state=SYN_SENT)
// how it should be …
```
> unidling: Workaround for OVN LB `reject=false` `event=false`

- dist/templates/ovnkube-node.yaml.j2
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/healthcheck_node.go
- go-controller/pkg/node/healthcheck_node_test.go
In the node healthz server, leveraged by cloud load balancers to check the node health for services with ExternalTrafficPolicy=Cluster, respond negatively to health checks as soon as the ovnk node pod is to be deleted, by inspecting the pod DeletionTimestamp.  This is what the endpointslice controller in KCM looks up when deciding whether an endpoint is terminating: https://github.com/kubernetes/kubernetes/blob/e706788455e99c77627c4ec88e1ec95e4fece54c/pkg/controller/endpointslice/utils.go#L43
The purpose is to allow cloud load balancers to have a little more time to update their list of healthy nodes before the node actually stops forwarding traffic altogether.
These changes complement https://issues.redhat.com/browse/OCPBUGS-7158,  should help …
> Node healthz server: return unhealthy when ovnk node pod is to be deleted

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/clustermanager/clustermanager_test.go
- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/metrics/cluster_manager.go
- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/hybrid_test.go
While adding support for cluster-manager, a second leader election was
introduced in ovnkube-master.
This leads to a change of paradigm we don't want, where one
ovnkube-master is leading for some components while a different
ovnkube-master is leading for other components. Additionally, each of
them runs a full fledged informer causing more strain to the api server.
There is also a problem in that cluster-manager will not be able to
regain leadership, as its leader election does not cause the process to
exit when leadership is lost but does not resume trying to acquiere
leadership.
> Single leader election

- docs/multi-homing.md
The configuration reference for localnet topology mistakenly stated `layer2`. It should feature `localnet` instead.
> docs, multi-homing: fix localnet topology typo

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- go-controller/pkg/cni/cni.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/util/sriovnet_linux.go
A new argument ovnkube-node-mgmt-port-dp-resource-name is added in this commit to pass the device plugin resource name that would be used for the mgmt port. The resource will override the existing parameter ovnkube-node-mgmt-port-netdev, if provided. 
A new DPResourceDeviceIdsMap is added in this commit to the OvnKubeNodeConfig structure to track the resources and allocated device ID that would be used for mgmt port and other future features such as bypass port.
This is needed to support k8s device plugin resources to be used instead of passing in interface names.
OvnKubeNode modified in this change.
Extended some of the config tests.
Support Device …
> Support Device Plugin Resources For Mgmt Port

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/libovsdbops/acl.go
- go-controller/pkg/libovsdbops/db_object_types.go
- go-controller/pkg/metrics/master.go
- go-controller/pkg/ovn/address_set/address_set.go
- go-controller/pkg/ovn/address_set/fake_address_set.go
- go-controller/pkg/ovn/base_event_handler.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pod_selector_address_set.go
- go-controller/pkg/ovn/pod_selector_address_set_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
Add PodSelectorAddressSet object, that should be used to manage network
policy peers with pod selector (network policy object is only
responsible for local pods and peer namespace-only handlers).
This should improve performance, since every peer selector will have only
1 address set to update (and 1 handler), instead of 1 address set per 
NetworkPolicy[In/E]gressRule, and 1 handler per every pod selector.
Update syncNetworkPolicies to cleanup policies based on acls, and not
address sets, since address sets are not created for policies without
peers with selectors, and it doesn't cleanup default deny port groups.
New sync is based on acls, it will only skip empty policies without
any gress rules. This should be fixed later with proper ownership
indexing for port groups.
Note: default deny …
> Network policy: use shared pod selector address sets

- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/node_ip_handler_linux_test.go
- go-controller/pkg/ovn/namespace_test.go
Fixes warnings related to `struct literal uses unkeyed fields` in the tests.
@tssurya PTAL.
> Cleaned a few warnings in the tests

- contrib/kind.sh
The creation of two kind clusters using scripts failed since the connect_local_registry is called before
fixup_kubeconfig_names. The kubectl apply was failing with unable to connect error. Now it will be called after fixup_kubeconfig_names.
Also fixed a wrong substitution in create_local_registry
The kind scripts to spawn cluster is modified
Run `kind -cn cluster1 -lr`
> Fix scripts for spawning multiple kind clusters

- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
Default node network controller initialization could fail which would result
in a BaseNodeNetworkController interface initialized with a nil 
implementation which is not the same as a nil interface{}.
> Fix default node network controller initialization

- go-controller/pkg/libovsdbops/db_object_types.go
- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/pod_selector_address_set_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
- test/e2e/e2e.go
Always allow hairpinned traffic, since it should be the same as pod
connecting to its own ip. That allows to remove hairpinned match
condition for ingress network policies and reduce the number of ovs
flows (significantly)
Steps to reproduce here https://issues.redhat.com/browse/OCPBUGS-10839
> Update hairpinning ACLs for network policy

- go-controller/pkg/ovndbmanager/ovndbmanager.go
Convert the db schema when there is a difference not just when there is a difference in version.
This should support upgrade and downgrade and also if we consume a schema where the author doesn't
change the schema version when making changes to a schema.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-4557
@kyrtapz I see you did something very similar in https://github.com/ovn-org/ovn-kubernetes/pull/3246
I think this is better as it doesnt rely on the schema version only.
> Use ovsdb client to detect if schema needs changing

- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- go-controller/pkg/config/config.go
- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/gress_policy_test.go
- go-controller/pkg/ovn/policy.go
- go-controller/pkg/ovn/policy_test.go
All K8s Network Policies are implemented as OVN ACLs and they are stateful by default. With stateful ACLs, the reply packets for an outbound connection are automatically matched and those packets are let in since the connection was started from within the Pod. There is no need to author additional network policy to match the reply packets.
This means that the Kernel needs to track connection state and match the incoming packets with that state to ascertain whether they are ‘reply’ packets or ‘new’ packets. This can be used to overwhelm the DPU by creating millions of connections and making the kernel track the state for each one of them and forcing the incoming packets to match those states thereby overwhelming the DPU CPU.
To mitigate this, the K8s Network Policies can be created as …
> Add support for creating stateless OVN ACLs for K8s Network Policies

- go-controller/pkg/cni/cnishim.go
Exec runner set during CmdAdd CNI request is not seen by CmdDel, hence should be set inplace.
Fixes: db56394dbda5 ("node/cni: initialize OVS exec runner early to prevent races")
Fixes: 39d1dc85a710 ("initialize OVS exec runner when ovnkube-node is in unprivileged mode")
> cni: Initialize OVS exec runner on CmdDel CNI request

- contrib/kind.sh
- test/scripts/install-kind.sh
Developer can deploy kind cluster with OVN-K on ARM machine for development and testing.
Run the following command on An ARM machine
```
make -C test install-kind
make -C test shard-network
```
> Enable kind scripts on ARM machine

- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/util/multi_network.go
- test/e2e/multihoming.go
today, ovnkube-master incorrectly assumes IPv6 is not enabled if no IPv6 is configured for default network, and fails to allocate IPv6 host subnets for secondary layer 3 networks with IPv6 subnets.
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/3168
> Cannot create routed secondary network with an IPv6 subnet

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- docs/kind.md
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- test/scripts/upgrade-ovn.sh
This PR does two things:
1) We add the following rules to our setup: 
```
"-d 172.16.1.0/24 -j ACCEPT",
"-s 172.16.1.0/24 -j ACCEPT",
"-o breth0 -j DROP",
"-i breth0 -j DROP",
```
(for primary and secondary bridges) if the DisableForwardingOnInterfaces=true
Problem: When packets are destined towards externalIPs/loadbalancerVIPs against unexposed ports, the packets follow this path: external->br-ex->host->br-ex->external and this causes a loop with the user's gw router. As per CNI plugin requirements, we shouldn't be interfering with this undefined traffic and sending it out if we don't know where to route this since its afterall service traffic. Just like we drop serviceCIDR traffic against unexposed ports, let's add drop rules for this kind of traffic coming from breth0 and getting …
> Control forwarding on OVNK managed interfaces

- go-controller/pkg/ovn/pod_selector_address_set.go
- go-controller/pkg/ovn/policy.go
Optimize deleteStaleNetpolPeerAddrSets to iterate over all acls only once.
On a random setup with 187 address sets and 6270 ACLs
initial version runs 573.911701ms
updated version runs 60.471213ms
"Processing NetworkPolicy %s/%s to have %d local pods" log is not really useful and eats ~40% of `handleLocalPodSelectorAddFunc` cpu usage
> Minor performance fixes

- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/libovsdbops/acl.go
- go-controller/pkg/libovsdbops/db_object_ids.go
- go-controller/pkg/libovsdbops/model.go
- go-controller/pkg/types/const.go
Based on the data from https://github.com/ovn-org/ovn-kubernetes/issues/3431 
netpol create is ~3 times faster, and restart is ~6 times faster on a test kind setup
> Use PrimaryID as a client index for ACL.

- go-controller/pkg/node/gateway_shared_intf.go
- test/e2e/service.go
This PR attempts to fix the flakes we are seeing in CI around:
```
[Fail] Load Balancer Service Tests with MetalLB [It] Should ensure load balancer service works with 0 node ports when ETP=local 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/service.go:831
[Fail] Load Balancer Service Tests with MetalLB [It] Should ensure load balancer service works with 0 node ports when ETP=local 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/service.go:831
```
Closes #3490 
For unknown reasons, during the kube rebase, we just decided to flip from sorting the list of endpoints to not sorting it? : https://github.com/ovn-org/ovn-kubernetes/pull/3401/commits/3850450829db65ef15fe308896036897339757a7#diff-d3a …
> Fix e2e etp=local flake happening in LGW mode lanes

- docs/developer.md
- go-controller/Makefile
- go-controller/hack/update-codegen.sh
- go-controller/hack/update-modelgen.sh
Running `make codegen` was using an older version of libovsdb modelgen and this was causing issues while regenerating `nbdb` and `sbdb` packages.
This PR updates the version in the make files to use a later version that includes: https://github.com/ovn-org/libovsdb/commit/a4f2602f585a3c2995a0abea7010b333631341d9
Funny enough the code however seems to be in sync so seems like whenever the last time packages were updated the version in the update-codegen file was not updated.
PR also splits modelgen from codegen so that users have the ability to run make on them separately.
Run `make modelgen`, everything should be clean.
`Updates modelgen version`
> Update modelgen version

- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/network_cluster_controller_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
Remove the no-longer-used node host subnet annotation to allow the default network controller's node code to proceed.
Also redo how the default network controller counts host subnets to make sure we actually have the right number of each IP family, rather than just counting numbers. Because the allocation handling was split out into the ClusterManager, the network controller's addNode() no longer has the guarantees of a correct set of annotations before it runs, as it and the cluster manager run in parallel.
> clustermanager: update node annotations on dual->single stack conversion

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/helper_linux.go
Users can specify IPV4 and IPv6 gateway nexthop for dual-stack cluster with '--gateway-nexthop=<ipv4_addr>,<ipv6_addr>'
> Make --gateway-nexthop support dual-stack

- go-controller/pkg/node/node_ip_handler_linux.go
- go-controller/pkg/ovn/address_set/address_set.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/util/node_annotations.go
During the kube 1.26 bump the sets[type].List() call was deprecated and replaced with unsortedList(). This could cause some flakes as we depend on the order of the set in some cases. This fix updates the unsortedList calls to use the sets List function
use sets.List instead of unsortedList
> Convert unsortedList() to sets.List()

- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/egressgw_test.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/egressqos_test.go
- go-controller/pkg/ovn/egressservices_test.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/multicast_test.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pod_selector_address_set_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_test.go
The FakeAddressSetFactory and by extension FakeAddressSet where created back when we where testing using ovn commands as a way to see the addresssets and how they change over time. Since the introduction of libovsdb and the ovn database used for testing we no longer need FakeAddressSetFactory to see how the addressSets change. we can query the database itself. 
Since addressSets are used in wide areas of the code I made this PR so that we can remove the useage of FakeAddressSetFactory over time and not require one large PR that removes the whole thing. 
This PR just removes the FakeAddressSet from egressfirewall_test.go
> Start to remove the fakeAddressSet

- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/ovn/controller/services/lb_config.go
- go-controller/pkg/ovn/controller/services/lb_config_test.go
- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/ovn/controller/services/services_controller_test.go
- go-controller/pkg/util/node_annotations.go
- test/e2e/e2e.go
- test/e2e/util.go
This PR makes NodePort services reachable on every IP address of a node.
They cannot be set only during `ovnkube-node` startup because other addresses can arrive later. The typical scenario is when a virtual IP address moves from a dead node the another.
PR adds End2End tests to the `control-plane` suite to cover the main scenario.
> Serve NodePort services on secondary IP addresses

- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
closes #3534
If the interface specified with '--gateway-interface' is already
a bridge port, use the bridge name as the gateway interface.
> Detect bridge name when 'gateway-interface' is specified

- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/libovsdbops/model.go
- go-controller/pkg/libovsdbops/model_client_test.go
- go-controller/pkg/libovsdbops/qos.go
- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/libovsdbops/router_test.go
- go-controller/pkg/libovsdbops/switch.go
- go-controller/pkg/libovsdbops/switch_test.go
For performance. Avoids running predicates to search for rows on this table where we already consider the name an index, or the alternative of having second level caches storing UUIDs.
> Add logical switch and router name as client index

- go-controller/pkg/node/helper_linux.go
Error if we found a default gateway interface for v4, but not for v6.
/cc @kyrtapz
> Return error msg if no ipv6 found

- go-controller/pkg/ovn/multipolicy_test.go
- go-controller/pkg/ovn/policy_test.go
Before acl indexes refactoring creating such objects was failing.
To test manually you can create netpols from the test, or based on this bug https://issues.redhat.com/browse/OCPBUGS-5835 2 policies with the following spec
```
spec:
egress:
- to:
- ipBlock:
cidr: 1.1.1.1/32
ingress:
- {}
podSelector: {}
policyTypes:
- Ingress
- Egress
```
The initial problem happened, because 1 network policy can create 2 equivalent acls (by match, not by name+externalIDs), since these acls will be created in 1 transaction, predicate search for both of them will be empty, so db doesn't mind adding them. It becomes a problem when there is another predicate-search-based operation with equivalent acl. That happens if one more policy with equivalent acl will be created, or on restart, when every policy will …
> Add netpol unit test for network policies with equivalent CIDR-based rules

- test/e2e/e2e.go
When asserting external connectivity, it happens to consistently receive a 429 (Too Many Requests) status code from the sample website. As the test only verifies the presence of an external connection, even an error status code is a good condition to continue testing.
This should avoid flakes like 
```
2023-04-28T14:19:03.3241874Z [0me2e control plane[0m [90mtest node readiness according to its defaults interface MTU size[0m 
2023-04-28T14:19:03.3242338Z   [1mshould get node ready with a big enough MTU[0m
2023-04-28T14:19:03.3242833Z   [37m/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:753[0m
2023-04-28T14:19:03.3243151Z [BeforeEach] e2e control plane …
```
> Avoid external connectivity flakes in E2E

- go-controller/hybrid-overlay/pkg/controller/node_windows.go
- go-controller/hybrid-overlay/pkg/controller/overlay_windows.go
fixes #3119
During the network creation a vnic is created however the routes from the parent vnic are not moved over to the associated vnic resulting in a network outage. This PR fixes this by caching the routes prior the creation so they can be restored after the network creation and associated to the new vnic. Netsh was also replaced with a more appropriate Powershell Cmdlet. One spelling mistake was resolved. 
@aravindhp can you provide the details on how this was tested?
Caches routes prior to network creation and applies them to the newly created vnic
> Ensure Routes are Restored to new vNIC fixes #3119

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/node_ip_handler_linux.go
The DPU needs to use the DPU host's IP address (the tenant cluster's host internal IP address) instead of the DPU's external bridge ip address for the node primary address annotations and the L3 gateway configuration.
An incorrect node primary address annotation and L3 gateway configuration results in broken flows when using NodePort or ClusterIP service.
Signed-off-by: William Zhao <wizhao@redhat.com>
> Fix handling of DPU on node primary IP change

- .github/workflows/test.yml
This will help resolve the issue of merging a PR then requiring another PR to be rebased to ensure we test against new HEAD. PRs will be sent to a merge queue and then executed against HEAD before they are merged.
Once this commit is merged we can go enable requiring merge queue in the repo. For more info:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> Enable github actions merge group

- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/util/kube.go
In case of completed pod case, egress ip module is handling pod add, egressip events as usual and when logical port is found, it proceeds with programming SNAT and LRP for pod ip address which is not required. Also when pod is done or completed, then it's not required to recreate SNAT entry referring to node ip address. Hence this commit addresses these two issues so that no stale or duplicate SNAT entries present for a pod.
> Fix stale SNAT entries for completed pods

- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
This makes the test code more explicit than it was before, and addresses the comment + promise for a short refactor done in pr [#3531 comment](https://github.com/ovn-org/ovn-kubernetes/pull/3531#discussion_r1177642261).
> multi-homing, policy, e2e: add requiresExtraNamespace attribute to pod config

- go-controller/pkg/util/net_linux.go
When we set `k8s.ovn.org/node-primary-ifaddr annotation` on the node, we simply take the first valid IP address we find on the node gateway. We already exclude link-local addresses and those in internally reserved subnets. Let's also filter out addresses added by keepalived, which are now labeled with $iface:vip.
This will make the choice of node primary IP deterministic in the case, like the following, where we have a keepalived address on `br-ex` but don't know how to distinguish it from the rest: 
```
sh-4.4# ip a show br-ex
7: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
link/ether 00:52:12:af:f3:53 brd ff:ff:ff:ff:ff:ff
inet6 fd69::2/125 scope global dadfailed tentative <---- masquerade IP, excluded
valid_lft forever …
```
> OCPBUGS-4370: Filter out IP addresses added by keepalived

- go-controller/pkg/node/healthcheck_service.go
There is a race condition observed when the
endpointslice is added before the service.
We will not pass https://github.com/ovn-org/ovn-kubernetes/blob/e7a92dbdab7d2f0c056ae2c6e549140c1809c7c0/go-controller/pkg/node/healthcheck_service.go#L131 this check and hence will not call `syncEndPointSlices` since service doesn't exist yet. Later when we do
AddService, we were not calling syncEndpoints and so we end up in a situation where the localEndpoints count is not updated.
This PR fixes that by moving the logic to call syncEndpoints to AddService. In the reverse case of endpointslice being added after the service, its possible we call the syncEndpoints from two places - both AddService and AddEndpointSlice, but better to be functionally correct and …
> Call SyncEndpoints from AddService

- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/retry/obj_retry.go
Nodes obj is configured via distributed software
components and previous to this patch, we are
sending numerous kubernetes events of error level warning when infact everything is proceeding normally..
Only emit warning events when we fail to configure a node. This is after 15 retry attempts - ~7m currently.
We continue logging every node add/update/delete failure to logs.
> Emit node events only when retry failure

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/management-port-dpu.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_dpu_test.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/management-port_test.go
- go-controller/pkg/util/node_annotations.go
Currently, the vf rep needs to be specified manually on the DPU side, but given a configuration on the host side, there is only one correct configuration on the DPU side. Instead of relying on the user to provide the right config on both sides, expose the config on the host side through an annotation and read that annotation from the DPU side.
> Expose PfID and VfID in DPU host mode and read that in DPU mode

- go-controller/pkg/ovn/controller/egress_services/egress_services_controller.go
- go-controller/pkg/ovn/controller/egress_services/egress_services_node.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/egressservices_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/util.go
- test/e2e/egress_services.go
- test/e2e/egressip.go
Match on all node's IP addresses on the no re-route policies so that intra cluster traffic is not routed through the egress or service IP even when the destination IP address is a secondary node IP.
Secondary node IPs might be VIPs that move across nodes.
> Egress IP, Services: use all node IP addresses

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/management-port-dpu.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_dpu_test.go
After introducing representor discovery for DPU mode MgmtPortRepresentor variable is not populated which cause ovnkube to mistakenly unconfigure management port netdevice or representor in the Full mode because it uses incorrect management interface name.
Drop this variable as obsolete and use other existing config variables to determine when management interface name should have a post-fix. Fix affected unit-tests.
Fixes: #3598
> Drop MgmtPortRepresentor config variable

- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/ovn_test.go
MeterBand and Meters have been supported for ACLs for a long time; any ovnkube user should be running an OVN that supports them.
> ovn: assume ACL logging is always supported

- go-controller/pkg/network-controller-manager/network_controller_manager.go
DP Groups have existed since 2020, defaulted to enabled in OVN 21.09, and the option to disable them was removed in OVN 22.09.
> ovn: assume Logical Datapath Groups are always supported

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cniserver_test.go
- go-controller/pkg/cni/ovs.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/cni/utils.go
- go-controller/pkg/cni/utils_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/pkg/node/base_node_network_controller_dpu.go
- go-controller/pkg/node/base_node_network_controller_dpu_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/ovn_test.go
- go-controller/pkg/util/ovn.go
iface-id-ver was added in OVN 21.09; all ovn-kubernetes users should *definitely* be using a much newer OVN. So we can remove all the complicated logic around detecting if OVN supports it, and just assume we can always use it unless we're in DPUHost mode.
@bn222 @trozet
> Always use OVN's iface-id-ver option in non-DPUHost mode

- dist/templates/ovnkube-node.yaml.j2
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/ovspinning/ovspinning_linux.go
- go-controller/pkg/node/ovspinning/ovspinning_linux_test.go
- go-controller/pkg/node/ovspinning/ovspinning_noop.go
- go-controller/pkg/util/ovs.go
- test/e2e/e2e.go
- test/e2e/ovspinning.go
Make ovnkube-node manage the CPU affinity of ovs-vswitchd and ovsdb-server processes, aligning them to its affinity.
The feature is enabled when the file `/etc/openvswitch/enable_dynamic_cpu_affinity` is present and not empty on the filesystem.
This feature is useful when the kubelet is configured with `static` cpuManager policy [1] and the OVS daemon needs
more cycles to cope with a network load rise.
This PR is a WIP as it needs further activation semaphore, besides the argument parameter, to activate the feature.
Allow ovnkube daemonset to control OVS CPU affinity in case of static cpuManager policy.
[1] …
> OVS Dynamic CPU Affinity

- dist/images/ovnkube.sh
- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
- go-controller/pkg/clustermanager/egressip_event_handler.go
- go-controller/pkg/clustermanager/fake_cluster_manager_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/ovn/base_event_handler.go
- go-controller/pkg/ovn/controller/egress_services/egress_services_node.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/syncmap/syncmap.go
- go-controller/pkg/util/kube.go
- test/e2e/egressip.go
- test/e2e/util.go
This PR tracks the work required to support EIP on IC environments. Here are the following pieces that need to go in:
When IC is enabled:
This PR does not run a multi-zone lane, so if someone wants to see a CI signal see <https://github.com/ovn-org/ovn-kubernetes/pull/3561>. Please pay extra attention to cloud private IP parts since there is no CI signal here for that. I could be easily breaking things. We at least need to add unit tests for that beast somewhere...
`Support egressIPs in Interconnect mode`
> Support Egress IP on OVN-IC

- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/fake_cluster_manager_test.go
Without initializing the stopChan `stopChan` will always fail with `close of nil channel`. 
Additionally removed unused fields from FakeClusterManager.
/cc @tssurya
> Initialize EgressIP stopChan in cluster-manager

- go-controller/pkg/ovn/base_network_controller_multipolicy.go
- go-controller/pkg/ovn/base_network_controller_multipolicy_test.go
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
This PR adds support for multi-network policies for secondary networks whose peers are of IPBlock type.
Run the multi-net tests.
Add support for multi-network policies for secondary networks whose peers are of IPBlock type.
> Multi policies ipamless ipblock

- .github/workflows/test.yml
- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/helper_linux.go
Users can create the external gateway bridge without attaching a
host physical interface as the uplink port in local gateway mode.
The gateway router will use 169.254.169.4 as the default gateway.
Add a new gateway config flag 'allow-no-uplink' to controll if this
setup is allowed or not. It's disabled by default.
With this setup, egressIP and egressGW can not work.
1. Create an ovs bridge (e.g. br-ex)without binding any host physical interface.
2. Assign an IP address to the br-ex interface
3. Run ovnkube-node with the flag `--gateway-interface=br-ex`.
> Allow external gateway bridge without uplink port In local gateway mode

- contrib/kind.sh
- test/e2e/localnet-underlay.go
- test/e2e/multihoming.go
This PR adds localnet multi-network underlay configuration to the e2e tests. Up to now, those executed the pods in the same node, and thus the test didn't check anything other than it is possible to schedule pods attaching to those networks.
This PR ensures the pods are scheduled on different nodes, which means the traffic between the workloads will use the physical underlay between them.
> Configure underlay secondary net localnet

- go-controller/hack/test-go.sh
On a normal, green, unit test run ovn package is already close to the limit of 10m timeout to run the unit tests with the eventual timeout actually happening sometimes:
ok github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn  593.856s
> Increase unit test timeout to 20m for ovn pkg

- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
This PR is includes two items of cleanup to the hybrid overlay.
First, in https://github.com/ovn-org/ovn-kubernetes/pull/3595 I mentioned that I would be cleaning up the podLister naming to be more explicit in this comment https://github.com/ovn-org/ovn-kubernetes/pull/3595#discussion_r1195574769. The first commit makes that naming explicit changing the names in the hybrid overlay from podInformer  to localPodInformer and podLister to localPodLister. 
Second, there is initialization code in AddPod() that is not required. PR https://github.com/ovn-org/ovn-kubernetes/pull/3595 added the localPodLister so as soon as the drIP and drMAC are set on the node there is a node update event that will use the new localPodLister in the hybrid overlay node controller to get all nodes and wire them for …
> hybrid overlay cleanup 

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/route_manager.go
- go-controller/pkg/node/route_manager_test.go
Route manager stop was failing since it was not incrementing the waitgroup:
```
panic: sync: negative WaitGroup counter
goroutine 139 [running]:
sync.(*WaitGroup).Add(0xc0007f7130, 0xffffffffffffffff)
/usr/local/go/src/sync/waitgroup.go:83 +0x1ab
sync.(*WaitGroup).Done(0xc0007f7130)
/usr/local/go/src/sync/waitgroup.go:108 +0x25
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*routeManager).run(0xc0010038c0, 0xc00003c000)
/home/pdiak/dev/ovn-kubernetes/go-controller/pkg/node/route_manager.go:56 +0xb98
created by github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*DefaultNodeNetworkController).Start
/home/pdiak/dev/ovn-kubernetes/go-controller/pkg/node/default_node_network_controller.go:634 +0x306
```
Since it doesn't really need the waitgroup it should be fine to remove it …
> Stop using a waitgroup in route manager

- test/e2e/external_gateways.go
Removes a BeforeEach check that ensured no namespaces contained the egress gw annotations before running the Admin Policy Based External Route tests.
This check is not necessary since each run creates its own namespace and the Admin Policy Based External Route tests are namespaced.
> Remove check for removal of egress GW annotation in namespace during tests

- go-controller/pkg/metrics/master_test.go
- go-controller/pkg/ovn/address_set/address_set_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/services/services_controller_test.go
- go-controller/pkg/ovn/controller/unidling/unidle_test.go
- go-controller/pkg/ovn/hybrid_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/ovn/zone_interconnect/chassis_handler_test.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler_test.go
- go-controller/pkg/testing/libovsdb/libovsdb.go
Let testcases use a globally created libovsdb test harness from BeforeEach() and update the database with test-specific data in the test, rather than each testcase creating its own harness.
> testing: add CreateTestData() method for libovsdb test server

- .github/workflows/test.yml
- contrib/kind-dual-stack-conversion.sh
- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-control-plane.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- go-controller/cmd/ovn-kube-util/app/readiness-probe.go
- test/e2e/e2e.go
- test/e2e/egressip.go
- test/e2e/multi_node_zones_interconnect.go
- test/e2e/multihoming.go
- test/e2e/util.go
- test/scripts/e2e-cp.sh
This PR enables multiple zone support testing using kind.
Zone support feature is already merged and we were missing the support to deploy a multi zone environment and interconnect them in a kind environment.
This PR adds this support.  It does the following
- Allows the option to  deploy a kind cluster with multi zone interconnect enabled with each node as a zone.
- Allows the option to  deploy a kind cluster with multi zone interconnect enabled with multiple nodes in a zone. 
- Adds CI testing with interconnect enabled for different scenarios.   Existing CI jobs are reused to test both interconnect enabled and interconnect disabled.
- There are a few features missing for the multizone support.  They are : 
-  egress service support
- …
> Multiple zone support for kind/CI

- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
OVN-Kubernetes on secondary networks only supports internal IPAM (i.e. implemented by OVN-K)
or no IPAM at all.
The [CNI IPAM key](https://github.com/containernetworking/cni/blob/main/SPEC.md#configuration-format) (tip: search  for ipam ..) is an optional, well-known key providing:
> Dictionary with IPAM (IP Address Management) specific values:
type (string): Refers to the filename of the IPAM plugin executable. Must not contain characters disallowed in file paths for the system (e.g. / or \).
Thus, it is pretty common for a user to attempt to define it; it currently wouldn't work - silently - which would confuse the users. 
This PR disallows the usage of this key providing an error message if it is used.
**- …
> Disallow ipam key on multi net cni config

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
testing
make the timeout for the periodic syncing of the ovs flows so high during testing that there will be no impact and this should eliminate testing flakes
Reported as: https://issues.redhat.com/browse/OCPBUGS-13979
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/3506
> fix hybrid overlay test flakes by removing periodic syncflows from

- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/controller/apbroute/node_controller.go
- go-controller/pkg/ovn/controller/apbroute/repair.go
- test/e2e/external_gateways.go
* Fixes a flaky test in the Admin Policy Based External Route unit test by adding logic to wait for the CR to be reconciled before comparing slices and also aligning the test with the expected behavior based on the test description (currently it not only removed a duplicated IP but also changed one, this is not aligned with the test description as it does not expect changes in the IP slice).
~~* Added Equal() functions to gatewayInfoList, gatewayInfo and namespaceInfo to support test scenarios~~
* Removed sorting functions in gatewayInfoList as they were not clear how they would sort the struct and were only used in test scenarios. They have been replaced by the Equal() functions.
* Added tests for `Insert` `Delete`  for `gatewayInfoList`
* Changed to use `cmpOpts` to validate comparing …
> Fix APB External Route flaky unit test

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pod_selector_address_set.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_unit_test.go
- go-controller/pkg/util/util.go
We were treating a failure to get IPs on a pod (because it had no IPs at the time) as an error in certain non-pod handlers. This would cause entire syncs or adding handlers to fail, when it shouldn't because once the handler/sync has been done the pod watcher will see the update event when the pod finally gets its IP address.
Also, its possible to get a delete event for a pod that never had an IP address but was scheduled.
> Fixes usages of get pod IPs

- dist/images/daemonset.sh
Running "./kind.sh -ic -cn foo" is broken.  This patch fixes it.
Fixes: 3f96b2fa9294("kind: Add support for interconnect and multiple zones support.")
Fixes: 0742ee4347e7("kind: Enhance interconnect support to deploy multiple nodes in a zone.")
Reported-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>
> kind ic: Fix kind deployment failure if cluster name is specified.

- go-controller/cmd/ovnkube/ovnkube.go
- test/e2e/e2e.go
Otherwise on upgrade there will be two leaders done the same things, the
old ovn-kubernetes-master leader and the new
ovn-kubernetes-master-global leader.
> Use the old leadership lock name for global zone

- go-controller/pkg/ovn/address_set/fake_address_set.go
Real address sets don't have any concurrency check but specifically deleting an address set twice from different threads at the same time should not be a problem.
We are seeing unit test failing on the fake address set destroy:
```
2023-06-13T22:39:00.4651626Z Your test failed.
2023-06-13T22:39:00.4651925Z Ginkgo panics to prevent subsequent assertions from running.
2023-06-13T22:39:00.4652392Z Normally Ginkgo rescues this panic so you shouldn't see it.
2023-06-13T22:39:00.4652576Z 
2023-06-13T22:39:00.4652842Z But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
2023-06-13T22:39:00.4653164Z To circumvent this, you should call
2023-06-13T22:39:00.4653319Z 
2023-06-13T22:39:00.4653431Z 	defer GinkgoRecover()
2023-06-13T22:39:00.4653572Z …
```
> fake address set: don't check for concurrency on destroy

- go-controller/pkg/clustermanager/egressip_controller.go
When an EgressIP gets created with an IP address that is already used by a different object ovn-kubernetes should emit a warning event.
> Emit a warning event for duplicated egress IPs

- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/external_gateway_test.go
We were not actually waiting for the informer cache to sync before starting workers.
> Fix apb informer sync wait

- go-controller/pkg/ovn/external_gateway_test.go
This test adds 2 legacy hybrid routes in the old format and then 1 new one and runs the stale cleanup code to verify that legacy ones get removed. By starting APB controller it will also try to run repair and potentially remove the new one becuase it does not match a real pod in the cluster. There is no real value in having APB in this test.
> Fixes race in delete legacy hybrid route policies

- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/node_controller.go
Adds a cast check when retrieving the objects from the event queues to avoid cases where the object retrieved in the delete use case is of type `cache.DeletedFinalStateUnknown`. 
It also adds checks for nil to avoid queuing nil objects.
> Adds cast check when getting object from queue in APB logic

- test/scripts/e2e-cp.sh
The jobs were not actually executing any tests becuase of a bad regexp introduced in:
de40f0ffeb17e4991005677aa6684eaf30cee4b6
@oribon fyi
> Fixes control plane shared gateway jobs

- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/default_network_controller.go
Fixes an issue found when testing the APB external route unit tests where the libovsdbops panicked due to empty value in the `controllerName` variable. The fix includes defining a unique value for the `controllerName` variable in the APB controller package and using that value in both controllers and tests.
@npinaeva @trozet PTAL @flavio-fernandes PTAL.
> Fix libovsdbops panic when testing apb external controller due to empty controllerName value

- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/repair.go
Remove the policy cache initialization in the repair.go. The reason is because the repair only takes care of removing inconsistencies, but does not tackle adding the differences. And when policy is again processed right after the repair is completed, the logic will not find any difference between the one cached and the one coming from the informer and will do nothing to reconcile the potentially missing additions that were not tackled in the repair.
The cache was mean to avoid hitting the informer every time it was required to recalculate all the gateway IPs of a given namespace so that the legacy/annotated logic could identify overlapping IPs.
@trozet PTAL.
> APB: remove init policy cache in repair.go

- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/egressgw_test.go
- go-controller/pkg/ovn/external_gateway_test.go
- go-controller/pkg/ovn/pods_test.go
When the ovn-kube default network is not the only network attached to the pod, the default route may point to a different interface. But we still need to send ovnk-specific traffic to the ovnk interface otherwise things just won't work.
https://issues.redhat.com/browse/RFE-3899
> pods: always add join subnet route to pod network namespace

- go-controller/pkg/libovsdbops/router.go
- go-controller/pkg/libovsdbops/switch.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/gateway_cleanup.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/net.go
Partial removal of nodes can leave OVN database with the gateway logical router and external logical switch of the removed node. This commit improves syncNode functionality, so these cases are taken into consideration.
When deleting a port from a logical switch or router, it is possible that the logical switch or router themselves have been deleted. This commit changes the behavior of delete so it is not an error when if that happens.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-13744
> Improve syncNodes to remove stale data

- go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go
When an EgressService is deleted the POD IPs added to the global EgressService address set should be removed.
I still need to add unit-tests and some additional cleanup  of the address set in `repair()`
> Delete pod IPs from the global EgressService address set

- .github/workflows/test.yml
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/egressgw_test.go
- go-controller/pkg/ovn/external_gateway_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/pods.go
- test/e2e/external_gateways.go
- test/scripts/e2e-cp.sh
* Added changes in the master APB External Controller to be IC aware and avoid hitting the NB when adding pods that are not in the same zone as the controller.
* It reverts the commit to disable interconnect in the e2e tests for APB use cases.
@trozet PTAL. I'm missing adding unit tests, hence a WIP for now, but I'd be grateful if you could take a look at what it's done and give me the thumbs up in the meanwhile.
> Add Interconnect support in APB External Route controller

- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
It's enabled by default when snooping is enabled but it's not really needed and we don't configure a source IP for it anyway.  This was causing ovn-controller to continuously log the mis-configuration and effectively disable the querier, e.g.:
pinctrl|WARN|IGMP Querier enabled without a valid IPv4 or IPv6 address
> Don't enable multicast querier on transit switches.

- go-controller/pkg/node/controllers/egressservice/egressservice_node.go
The repair function of the EgressService node controller was trying to remove the chain creating rule resulting in the following error:
```
Failed to repair Egress Services entries: running [/usr/sbin/iptables -t nat -D OVN-KUBE-EGRESS-SVC -N OVN-KUBE-EGRESS-SVC --wait]: exit status 2: iptables v1.8.7 (nf_tables): Cannot use -N with -D
```
To address the issue skip that particular rule.
/cc @trozet @oribon
> EgressService: Do not try to remove the chain creation rule on startup

- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
Cleanup on failed Add. Return nil instead of error when egressFirewall is not found on delete.
> Fix egressFirewall create error handling

- go-controller/pkg/node/gateway_shared_intf.go
If ovnkube runs in LGW mode with no uplink gateway bridge, ingress traffic enters the host from node's physical interface instead of the breth0. It makes no sense to configure the servcie flows in the gateway bridge.
As the no uplink gateway bridge is only used by microshift, the `externalTrafficPolicy` is useless when only one node is in the cluster.
> Skip adding service flows to gateway bridge when no uplink in the bridge

- go-controller/pkg/libovsdbops/router.go
Regression introduced by:
25d892cc9e318d19738d9519e0e20fbab28f7eae
Would end up appending a nil NAT and causing an NPE when trying to execute EquivalentNAT:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x178ea7b]
goroutine 140 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdbops.isEquivalentNAT(0x0, 0xc002e6cea0)
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/libovsdbops/router.go:935 +0x9b
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdbops.DeleteNATsOps({0x24aa068, 0xc0008c0fc0}, {0x0, 0x0, 0x0}, 0xc002e1a4e0, {0xc000130c48, 0x1, 0xc00106f6f8?})
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/libovsdbops/router.go:1087 +0x728
Seen …
> Fixes panic with delete NAT operations

- .github/workflows/commands.yml
So we don't consume a runner for every comment.
> Don't run commands workflow if not a command

- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/controller/apbroute/node_controller.go
- go-controller/pkg/ovn/controller/apbroute/repair.go
- go-controller/pkg/ovn/external_gateway_test.go
This PR aims to solve a design flaw in the APB External Route controllers where there were potential situations for race conditions due to all 3 controllers making changes to the impacted resources in parallel and out of sync. 
The new implementation relies only on the route policy controller to handle any updates due to changes to namespaces, pods or policies.
> APB External Route: refactored controllers to use a single workqueue to handle policy updates

- go-controller/pkg/node/ovspinning/ovspinning_linux.go
OCPBUGS-15523
grep to scan for incorrect usage
```
grep --line-number -E 'klog[^"]*[^f]\(".*%'
```
> ovspinning: use klog.Infof() instead of klog.Info()

- FAQ.md
- README.md
- dist/images/ovnkube.sh
- dist/templates/ovnkube-monitor.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- docs/ha.md
- go-controller/README.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/network-controller-manager/network_controller_manager_suite_test.go
- go-controller/pkg/util/kube.go
```
User Facing change: Rename ncm to ovnkube-controller
Recently we added the network-controller-manager flag
mode for supporting deployments where master will run
separately from cluster-manager. From https://github.com/ovn-org/ovn-kubernetes/pull/3366
we have renamed the container to be more generic: `ovnkube-controller`.
Since we are still early and only merged this flag a few weeks ago,
let's make sure we stay consistent moving forward and rename
this flag to ovnkube-controller before bringing this flag downstream
into CNO.
NOTE: All exisiting internal code can call this
NetworkControllerManager.
On a user facing level, I'd like to keep this simple and say
anything programming ovnkube and OVN DB is the ovnkube-controller
similar to …
```
> Rename ovnkube-network-controller-manager to ovnkube-controller

- go-controller/pkg/ovn/base_network_controller_policy.go
- go-controller/pkg/ovn/policy_test.go
The previous version used shared address sets for empty namespace
selector to reuse the address set, but it didn't include a special
config.Kubernetes.HostNetworkNamespace that only has an address set,
but no pods. This difference may break existing network policies for
hostNetwork pods, therefore we explicitly add this address sets for an
empty namespace selector.
> Allow hostNetwork ingress for network policies with empty namespace selector

- test/e2e/unidling.go
Test was done and the framework was being de-allocated while still in createBackend
Fixes
```
2023-06-28T13:58:03.0137137Z   [91m[1mTest Panicked[0m
2023-06-28T13:58:03.0138811Z   [91mruntime error: invalid memory address or nil pointer dereference[0m
2023-06-28T13:58:03.0141144Z   /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884
2023-06-28T13:58:03.0143776Z 
2023-06-28T13:58:03.0144764Z   [91mFull Stack Trace[0m
2023-06-28T13:58:03.0145429Z   panic({0x1a54e20, 0x2e71ba0})
2023-06-28T13:58:03.0146179Z   	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x212
2023-06-28T13:58:03.0147433Z   github.com/ovn-org/ovn-kubernetes/test/e2e.createBackend(0xc000477080, {0xc0009e33e0, 0x10}, {0xc0009e2aa0, 0xc}, {0xc000b41db8, 0x11}, 0xc000f3d260, 0x50) …
```
> Fix unidling test panic after not waiting to be done

- test/e2e/util.go
We had a flake here: https://github.com/ovn-org/ovn-kubernetes/actions/runs/5408009751?pr=3724 for this test and from the logs everything looks good. Unless we print the iptable rules at the given instance its hard to debug this test specially since we don't gather the iptable rules from nodes at a given point.
This PR tries to debug the flake seen in https://github.com/ovn-org/ovn-kubernetes/pull/3724
We could revert this when we think we have the test stable. From just looking at the logs in the failed run things look good!
The curl was successful and so my doubt is that the counter in iptables [1:60] was perhaps not right and maybe we matched on more packets? We need to check this and the only way to run …
> Add debug statements to figure out ETP=local flake

- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/repair.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/external_gateway_test.go
Add logic to wait for APB controller's clean external gateway ECMP routes to be finished in the default network controller before resuming the execution of the `Run()` method.
Also moved the initialization of the APB controller to be the first thing to do to ensure the north bound information is updated before all other controllers kickoff.
@jcaamano PTAL.
> Wait for APB controller's clean external gateway ECMP routes before resuming default net controller startup

- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/ovn/egressqos_test.go
This commit adds the notion of zone to the
EgressQoS controller so that it stops processing
remote nodes and pods.
Fixes these errors in the CI:
```
2023-06-10T05:45:37.811658735Z stderr F E0610 05:45:37.811590   94286 egressqos.go:890] ovn-worker2 failed with : object not found
2023-06-10T05:45:37.809790419Z stderr F E0610 05:45:37.809759   94286 egressqos.go:890] ovn-worker failed with : object not found
```
We will also only add local podIPs to the address-sets references by QoS objects.
We have tests in e2e and unit frameworks for this feature
`Add notion of IC to EgressQoS`
> EQoS: Consider only local nodes and pods

- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/egressgw_test.go
- go-controller/pkg/ovn/external_gateway_test.go
Adds logic in the legacy external gateways (egress.go) to check for overlapping gateway IPs coming from existing APB external route CRs to ensure that they are not deleted from the north bound.
Adds unit tests to cover for static (namespace annotations) and dynamic IPs (pod gateway annotations).
@trozet PTAL.
> Add check for overlapping external gateway IPs in egressgw when deleting a pod

- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/external_gateway_apb_test.go
* Rename `external_gateway_test.go` to `external_gateway_apb_test.go` to reflect that the tests are specific to the APB logic.
* Replace calls to the legacy external gateway functions for hybrid route and SNAT in the APB external route tests to use the counterpart functions found in the APB's north bound client. 
* Expose the following methods in the north bound client inside the apb master controller so that it can be used by the unit tests to validate its logic:
* addHybridRoutePolicyForPod
* delHybridRoutePolicyForPod
* delAllHybridRoutePolicies
* delAllLegacyHybridRoutePolicies
* deletePodSNAT 
@trozet PTAL.
> APB: Change hybrid route and SNAT calls in unit tests to call the APB functions instead of the ones exposed for the legacy egressgw

- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go
Fixes this scenario:
```
2023-06-29T12:37:36.2845679Z     github.com/onsi/gomega/internal.(*AsyncAssertion).buildActualPoller.func3.1()
2023-06-29T12:37:36.2846810Z     	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/github.com/onsi/gomega/internal/async_assertion.go:321 +0x397
2023-06-29T12:37:36.2847525Z     panic({0x285b340, 0x3f2c890})
2023-06-29T12:37:36.2848328Z     	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:890 +0x262
2023-06-29T12:37:36.2849115Z     github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/apbroute.glob..func1.4.4.4()
2023-06-29T12:37:36.2850141Z     	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go:337 +0x55
``` …
> APB: Add check for nil when retrieving number of dynamic hops in tests

- go-controller/pkg/ovn/external_gateway_apb_test.go
Disable UTs for APB Temporarily till the feature
is stabilized.
Reason: UTs are very flaky. Each PR is needed a
minimum of 3 close/open combinations and luck for CI
to pass to even run e2e's. At this stage where other features
are trying to get in before the deadline this process is painful.
At least if the retest flag was present it would be nice, closing/opening
PRs on github  frequently - we don't know what the consequences of that
for bigger feature PRs are.. too muc of time consumption trying to get CI
to pass
cc @jordigilh : WDYT? I think you and @npinaeva are working to get it all fixed
but that may take 2 more weeks for merge, meanwhile I'd like to unblock CI.
cc @jcaamano
> Disable UTs for APB Temporarily.

- go-controller/pkg/network-controller-manager/network_controller_manager.go
At ovnkube-controller start up, it may attempt to start adding resources for a node that does not yet have its annotation, but should be considered local. This is especially the case in OpenShift when going from phase1 -> phase 2 upgrade and ovnkube-node on the node will annotate its zone id. In this case ovnkube-controller will start too early and program NBDB resources as remote for the node. Then when the node is annotated, it will program NBDB resources as local.
Since we cannot be sure that all remote feature configuration in NBDB is removed when going from remote -> local we need to avoid this case. It also makes no sense to program NBDB when there are no nodes in the zone.
This commit adds a wait to make sure at least one node in the cluster is in the ovnkube-controller's managed …
> Ensure ovnkube-controller does not go remote->local

- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler_test.go
When node from a remote zone is updated, we only perform the actual update when necessary. This commit improved the logic for doing the remote update in cases where the subnets of the remote node change. That is particularly needed when node changes from ipv4 to dual stack (ipv4 + ipv6)
Reported-at: https://issues.redhat.com/browse/SDN-3993
> ovn-ic: node update missing static routes

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-control-plane.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
Add config flag 'enable-multi-external-gateway'. It allows users to enable/disable the feature.
> Add config flag 'enable-multi-external-gateway'

- go-controller/pkg/ovn/egressip.go
When a namespace with pods gets removed and the pod removal event is handled after the namespace is already gone, we should ignore the NotFound error in reconcileEgressIPPod. Any potential configuration will get removed in reconcileEgressIPNamespace.
Found in downstream CI, tracked in https://issues.redhat.com/browse/OCPBUGS-15804
Example error:
```
I0707 01:15:21.862524       1 namespace.go:260] [e2e-netpol-z-1913] deleting namespace
...
E0707 01:15:21.894356       1 obj_retry.go:680] Failed to delete *factory.egressIPPod e2e-netpol-z-1913/b, error: namespace "e2e-netpol-z-1913" not found
I0707 01:15:21.894452       1 pods.go:100] Deleting pod: e2e-netpol-z-1913/b
E0707 01:15:21.904170       1 obj_retry.go:680] Failed to delete *factory.egressIPPod e2e-netpol-z-1913/c, error: namespace …
```
> Do not reconcile egressIPPod objects that are being deleted when the namespace no longer exists

- go-controller/pkg/ovn/default_network_controller.go
These logs are already moved to cluster-manager
> NIT: EIP: Healthchecks have moved to ovnkube-controller

- contrib/kind.sh
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
- go-controller/pkg/types/const.go
- test/e2e/localnet-underlay.go
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
This change attempts to simplify how the network admin configures the underlay of the network to which the secondary network overlays connect to; the user must configure the OVN bridge mappings by associating the name of the physical network to the name of the desired OVS bridge.
Currently that is done via the following pattern:
`<name of phys network>_br-localnet:<name of ovs bridge>`
An example would be:
`tenantblue_br-localnet:ovsbr1`
This commit simplifies that by removing the suffix; the bridge mappings would be:
`<name of phys network>:<name of ovs bridge>`
And an example would be:
`tenantblue:ovsbr1`
Run the e2e tests.
Remove the localnet port …
> multi-homing, localnet: update localnet port network name

- test/e2e/localnet-underlay.go
- test/e2e/multihoming.go
Enable e2e tests for localnet but there was another issue that needed
a fix.
PR#3609 removed the suffix `_br-localnet` from the localnet network
name used in the bridge mappings, but also inadvertedly removed the
replacement of `-` and `/` characters form the controller code but not
from the tests.
Let's remove them from tests as well as they don't look troublesome
neither as network name in the logical switch port options nor in the
OVS bridge mappings.
> Enable multi-homing e2e tests for localnet with IC

- go-controller/pkg/clustermanager/subnetallocator/allocator.go
- go-controller/pkg/clustermanager/subnetallocator/allocator_test.go
- go-controller/pkg/clustermanager/subnetallocator/host_subnet_allocator.go
- go-controller/pkg/clustermanager/subnetallocator/host_subnet_allocator_test.go
The original Usage() returned both used and available subnets for the allocator, which is confusing and error prone. The fixed commit used the "count" (eg used+unused) for both count and usage, leading to OpenShift alerts about subnets exceeded because (usage / count) = 1.
Instead, break the API into two separate calls with clear meaning. Usage() returns how many subnets are allocated, and Count() returns how many are possible/available.
```
{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:587]: Unexpected error:
<errors.aggregate | len:1, cap:1>:
promQL query returned unexpected results:
ALERTS{alertname!~"Watchdog|AlertmanagerReceiversNotConfigured|PrometheusRemoteWriteDesiredShards|KubeJobFailed|Watchdog|KubePodNotReady|etcdMembersDown|etcdMembersDown|etcdGRPC …
```
> subnetallocator: fix and clean up used vs. count confusion

- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressservices_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/ovn.go
Update service controller to use sharedInformerFactory from the default controller. It decreases kube-apiserver load and memory footprint, because service controller used to create its own SharedInformerFactory for Nodes, Services and EndpointSlices.
> service controller: use shared InformerFactory

- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler_test.go
Previously the behavior was for every remote add across 15 threads to
try to create or update the transit switch. The transit switch is a
singleton which does not need to be updated on every remote node add.
Consequently by doing this it could cause high delays in nodes getting
added for IC. This is because one or more threads could read the
libovsdb cache at the same time and determine the switch does not exist,
then make insert operations. These insert operations are guarded by a
libovsdb wait, and the timeout on retries per transaction is 10 seconds.
Compounded into this delay is the retry framework timer which is 30
seconds. This could result in nodes delaying to be added by up to 40
seconds.
This patch changes the behavior so that the transit switch is configured
during …
> Fixes race across node workers to create transit switch

- go-controller/Makefile
- go-controller/pkg/libovsdbops/acl.go
- go-controller/pkg/libovsdbops/acl_test.go
- go-controller/pkg/nbdb/acl.go
- go-controller/pkg/nbdb/mirror.go
- go-controller/pkg/nbdb/model.go
- go-controller/pkg/ovn/acl.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync.go
- go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync_test.go
- go-controller/pkg/ovn/external_ids_syncer/address_set/address_set_sync_test.go
- go-controller/pkg/ovn/multicast_test.go
- go-controller/pkg/ovn/pod_selector_address_set_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/sbdb/mirror.go
- go-controller/pkg/sbdb/model.go
- go-controller/pkg/types/const.go
Change all existing ACLs to tier2
We have a new feature called Hierarchical
ACLs that is introduced in OVN to enable
support for tiered ACLs. This commit
ensures all existing ACLs for all features
are migrated towards tier2. By default all
new ACLs must be added to tier2.
Tiered ACLs will be used for ANP & BANP in https://github.com/ovn-org/ovn-kubernetes/pull/3659. This PR splits the initial framework addition so that its easier to review this.
`Move all existing ACLs to tier2 which will be the default`
> Add Support for Hierarchical ACLs

- go-controller/pkg/libovsdbops/portbinding.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
- go-controller/pkg/util/ovn.go
There are other objects that we update in SBDB that depend on an object being created by northd and may race. Failures here can further delay node add by 30 seconds.
Ideally we should lower the retry mechanism interval from 30 seconds to something much smaller (now that we use a per key locked syncmap), however that could have even greater implications. So for now, just add in path delays for SBDB objects.
> Wait for other SBDB objects

- go-controller/pkg/ovn/egressfirewall_dns.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/pod_selector_address_set_test.go
- go-controller/pkg/ovn/policy_test.go
1.  Fix counting goroutines test: let the system settle down before
counting goroutines.
It used to flake ~ every 1000 iterations.
Verified this fix with 7500 runs.
2.  Fix egressDNS test flake when EgressDNS hasn't started its goroutine
listening to the added channel. If `Add` is called before that,
message won't be sent because the channel didn't have a buffer.
> Stabilize 2 unit tests

- go-controller/pkg/ovn/base_network_controller_policy.go
to avoid ovn-controller syntax errors.
For some stupid reason I changed the cleanup order when implemented `PodSelectorAddressSet`, fix it
> Delete address sets after acls that reference them 

- go-controller/pkg/clustermanager/egressservice/egressservice_cluster.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/informer/informer.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/node/controllers/egressservice/egressservice_node.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/egress_service_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/node_controller.go
- go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go
- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/ovn/egressqos_test.go
- go-controller/pkg/ovn/egressservices_test.go
- go-controller/pkg/ovn/external_gateway_apb_test.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/sync.go
WaitForCacheSync function takes stopChannel as an argument, and it will
retry syncing cache until it is closed. If we just use ovn-kube stop
channel, it will never return an error (it will never return until
either the cache is synced, or stopChannel is closed).
To fix it, GetChildStopChanWithTimeout and some wrappers functions
passing this channel with timeout were added. The default cache sync
timeout is 20 seconds (with reflector exponential backoff it means 4
list() retries).
If any informer failed to list its resource withing a given time period,
return error to make the problem visible.
To test this change, comment out list permission for any object in
dist/templates/ovn-setup.yaml.j2, run kind cluster and check the
corresponding container fails with message like
"failed to start …
> Sync cache with timeout, fix apbroute start

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/zone_interconnect/chassis_handler.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
- go-controller/pkg/retry/obj_retry.go
- go-controller/pkg/types/errors.go
This PR adds a new type of SuppressedError which can be used by different components to indicate errors that should only be logged as error on their final failure (since we implement retry framework). This is needed because with IC, we rely on the remote node to update some information on the pod/node/resource before we can process it. Currently we spam errors everytime we get an event and do not see that information. The error is necessary so that our retry framework will know to retry, but we do not need to log these as errors.
The PR focuses on pod ips set by remote nodes, as well as chassis information for nodes set by remote nodes or OVN.
When I launch a cluster with this PR most of the log spam is gone. There is still spam from egress qos:
E0628 10:28:09.135010    4186 …
> Fix log spam caused by IC

- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
- go-controller/pkg/clustermanager/egressip_event_handler.go
- go-controller/pkg/clustermanager/fake_cluster_manager_test.go
- go-controller/pkg/kube/kube.go
This commit ensures egress IP status is in sync with cloud private IP config on a restarted ovnk master because stale entry is noticed in the egress IP status though cloud private IP config entry is not present for the given egress IP.  This might have happened while processing cloud private IP config delete event, an error is thrown because of bug fixed in PR: https://github.com/ovn-org/ovn-kubernetes/pull/3371.
> Remove stale egressip status entry

- go-controller/pkg/ovn/kubevirt_test.go
After live migrating a VM the original node can be shutdown and a new one can appear taking over the node subnet. There were some unit tets for that but they exercise this part for non live migration scenarios creating a race condition between cleanup and addLogicalPort.
This change run that part of the tests only for live-migration scenarios.
This is the race condition log 
```
2023-07-20T19:21:44.7804051Z ^[[1mSTEP^[[0m: Replace vm node with newNode at the logical switch manager
2023-07-20T19:21:44.7804518Z I0720 19:21:44.780096   23041 master.go:789] Adding or Updating Node "newNode1"
2023-07-20T19:21:44.7811187Z I0720 19:21:44.780889   23041 pods.go:181] [namespace1/virt-launcher-1] addLogicalPort took 20.236766ms, libovsdb time 6.815389ms …
```
> kubevirtl: Replace node only at migration tests

- .github/workflows/test.yml
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
This is a continuation of https://github.com/ovn-org/ovn-kubernetes/issues/3770
More details on the reproducing of the flake was added [here](https://github.com/ovn-org/ovn-kubernetes/issues/3770#issuecomment-1637204333).
This PR also includes a commit for github workflow that saves the ovn dbs as an artifact when the test fails. Having this was extremely useful for narrowing down on the flake. So I would like to merge that too.
Note: Unit tests for exercising the individual functions were already added via [this commit](https://github.com/ovn-org/ovn-kubernetes/pull/3724/commits/980abd3d7f6f67714d8a7437e4d0b9917c9ed2f9). What we lacked was the logic in `func (h *defaultNetworkControllerEventHandler) UpdateResource(oldObj, newObj interface{}, inRetryCache bool) error` which is hard to …
> IC Dualstack jobs are flaking (try 2)

- go-controller/pkg/node/node_ip_handler_linux.go
When running a 2-cluster design in DPU mode, currently host-addresses is set to the IP address of the Infrastructure node (i.e. Bluefield node) running of behalf of the tenant cluster. This will cause all NodePort service to fail in DPU mode.
Instead, we should calculate the host-addresses using the NodePrimaryIP which will set the host-address to the Node IP of the tenant node.
> Use NodePrimaryIp to set host-addresses in DPU mode

- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
Some were `Localnet` and some were `localnet`, align all to `localnet`.
This allows running all of them using:
`ENABLE_MULTI_NET=true make -C test control-plane WHAT=".*localnet.*"`
Before this change, 2 out of 5 were not selected.
Additional small change:
Rearrange imports
> e2e, localnet: Align case of all localnet tests

- dist/images/Dockerfile.fedora
- dist/images/Dockerfile.fedora.dev
- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
This PR enhances ovnkube-trace module to make it work seamlessly when ovn interconnect is enabled per node or subset of nodes, It also collects ovn trace from both source and destination node when both nodes are in different interconnect zones. 
The following scenarios are tested for the change:
- Pod to Pod Traffic (Local and Remote)
- Pod to Service Traffic (Endpoint Local and Remote)
- Pod to External IP
- Dual Stack cluster
- Running `bash -x ./test/scripts/test-ovnkube-trace.sh` script.
> Enhance ovnkube-trace for ovn interconnect

- docs/kind.md
The kubectl installation instructions define a variable, but it isn't used when renaming and linking the kubectl binary. This fixes the instructions to use the variable, producing a consistent result instead of a hard-coded 1.18.0 binary name.
> Use variable for kubectl version

- test/e2e/e2e.go
in the only test that was using it. Downloading an extra image for one test doesn't make a lot of sense, and can cause test failures like
"docker: failed to register layer: ApplyLayer exit status 1 stdout: stderr: write /usr/lib64/dyninst/libparseAPI.so.9.3.1: no space left on device."
Failure example https://github.com/ovn-org/ovn-kubernetes/actions/runs/5665620434/job/15351462559?pr=3582
> Replace centos/tools image with agnhostImage

- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/ovn/controller/services/services_controller_test.go
When service controller starts up along side node tracker, it is possible that it attempts to sync a service without having all of the nodes in the cluster. In new installations this is fine, but in a steady state cluster where a new ovnkube-controller takes over, or is restarted it can cause service outage.
This happens because there may already be a load balancer configured for a specific node in OVN, then when the ovnk pod is restarted, it may sync the service before it has rebuilt its node cache. The consequence is the LB will be removed from OVN for a period of time, causing traffic disruption. This was noticed in a downstream OCP CI run.
This commit fixes the problem by ensuring that the node tracker has synced its initial objects first, before allowing services and endpoint …
> Fixes service controller + node tracker start up race

- go-controller/pkg/network-controller-manager/network_controller_manager.go
This is a continuation of commit 5e6787d187a77d837b7bddade57e93c6fb199116 . While waiting for a node in the default zone, introduced logic must factor in cases when there are no nodes in the cluster at the time controller starts.
Related PR: https://github.com/ovn-org/ovn-kubernetes/pull/3735
Reported-at: https://issues.redhat.com/browse/OCPBUGS-16767
> Ensure ovnkube-controller does not go remote->local (cont.)

- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/util/kube.go
While running on scaling cluster, we have identified some chatty logs that we can do without. This PR addresses that.
Extracted from a 330 Mb log file:
```
kube.go:484                130 Mb (39.39%)
services_controller.go:416  37 Mb (11.21%)
kube.go:501                 33 Mb (10%) <-- also among longest lines
services_controller.go:537  26 Mb (7.88%)
services_controller.go:326  26 Mb (7.88%)
services_controller.go:433  24 Mb (7.27%)
services_controller.go:322  23 Mb (6.97%)
kube.go:462                 22 Mb (6.67%)
```
> Put chatty logs on a diet

- go-controller/pkg/factory/factory.go
the log files were filled with very very very long lines enumerating 100s of objects that were being processed. it is not of much help in logging them anyways.
> do not print all the items being processed in processExisting() on error

- go-controller/pkg/libovsdb/ops/chassis.go
By updating the chassis with incomplete information, it was causing ovn-controler to rewrite the values in the DB, and furthermore causing northd to rewrite logical flows during ovnkube-master restart. The notable consequence of this would be that access to a service via loadbalancer type (using LB templates) would be momentarily disrupted. This is the root cause for the outage we see in Azure upgrades.
@dceara @numansiddique @tssurya 
Manual way to test/reproduce:
1. launch kind: kind.sh -wk 2 -ic -npz 3 (3 nodes in 1 zone, similar to phase 1)
2. create a loadbalancer service:
```
[trozet@fedora ~]$ cat ~/loadBalancersvc.yml 
apiVersion: v1
kind: Service
metadata:
name: web-service
spec:
selector:
role: webserver
ports:
- protocol: TCP
port: 80
targetPort: 80
type: LoadBalancer
```
3. …
> Changes IC chassis update to be a mutate operation

- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
When using localnet topology, we need to test pod to underlay
service connectivity.
Steps: (the ones with * are new)
1. Setup the underlay (create OVS bridge, and bridge mapping).
2. Create NAD with localnet toplogy.
Exclude from the CIDR an IP reserved for the underlay bridge (*).
3. Add the mentioned IP to the underlay bridge (*).
4. Run a web server connected to that bridge (*).
5. Start a pod connected to our secondary network.
6. Run curl command from the pod, connecting to the web server (*).
A follow [PR](https://github.com/ovn-org/ovn-kubernetes/pull/3810) can reuse some of the new functions (i.e `createNad`, `setupLocalnetUnderlay`)
and `kickstartPod` in more places that they suit.
**- How to verify …
> e2e, multihoming: Add underlay service connectivity test

- go-controller/pkg/libovsdb/libovsdb.go
In certain scaling situations, it may take longer than types.OVSDBTimeout for the monitoring of OVSDB tables to be set up. This change is a follow-up to commit da9408d3b1d1c1fd376e365f9cb2836444e2523b, accounting for cases where ovnkube-master has a lot of startup data. The timeout for monitoring introduced in commit 6ae4edb8d8575e86c4e4519ee45e11ffecc5d239 did not account for that.
Reported-at: [OCPBUGS-17147](https://issues.redhat.com/browse/OCPBUGS-17147)
> libovsdb: give monitor setup time to process than normal transactions

- dist/templates/k8s.ovn.org_adminpolicybasedexternalroutes.yaml.j2
- go-controller/pkg/crd/adminpolicybasedroute/v1/types.go
- go-controller/pkg/crd/adminpolicybasedroute/v1/zz_generated.deepcopy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/external_gateway_apb_test.go
Implements changes to the APB External Route [PR](https://github.com/openshift/enhancements/pull/1377) that makes the namespace selector in the dynamic hop as mandatory. The motivation is that it did not make sense to have a dynamic hop that scoped all the pods in the cluster (if namespace selector is empty, then fetch all pods in all namespaces). 
@trozet @npinaeva @tssurya @jcaamano PTAL.
> APB: make namespaceSelector in dynamic hops mandatory

- go-controller/pkg/libovsdb/ops/db_object_types.go
- go-controller/pkg/ovn/base_network_controller_policy.go
- go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync.go
- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/gress_policy_test.go
- go-controller/pkg/ovn/policy_test.go
If an ingress rule has 5 TCP port specified along with a namespace selector, then we end up creating 5 OVN ACLs. Instead, we could create just one ACL by consoldiating the individual ports and/or ranges. For example:
With this Network Policy,
spec:
ingress:
- from: - nameSelector: matchLabels: name: web ports: - protocol: TCP port: 3306 - protocol: TCP port: 80 - protocol: TCP port: 9000 endPort: 9100
we end up creating following 3 matches
(ip4.src == {$as1} && tcp && tcp.dst==3306 && outport == @pg1) (ip4.src == {$as1} && tcp && tcp.dst==80 && outport == @pg1) (ip4.src == {$as1} && tcp && 9000<=tcp.dst<=9100 && outport == @pg1)
With the fix in this commit, we will have only one match (ip4.src == {$as1} && tcp && (tcp.dst=={3306,80} || \
9000<=tcp.dst<=9100 && outport == @pg1)
With …
> Consolidate several L4 OVN ACLs into smaller number of OVN ACLs

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- go-controller/go.mod
- go-controller/pkg/config/config.go
- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/node/route_manager.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/retry/obj_retry.go
This PR enables the libovsdb client to use a separate log file to prevent ovn transactions
from filling up ovnkube controller logs. By default, this feature is disabled, and the logs will
only be separated when the new flag is provided:
--libovsdblogfile /path/to/log.log
When this flag is used, the log's verbosity and rotation will follow the existing flags for such
purposes. See  https://github.com/ovn-org/ovn-kubernetes/pull/1458
> Support for separate libovsdb logs via lumberjack

- dist/images/ovnkube.sh
- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/ovn/default_network_controller.go
UnidledAtController sets informational annotations on idled/unidled services.
Without the proposed changes every node will try to set/remove the `UnidledAtAnnotation` on a service that changed the idle state.
Additionally, this is the only place where ovnkube-node requires `services/status` permissions so it would be good if we could get rid of it.
Before:
```
oc logs -lapp=ovnkube-node -c ovnkube-controller --tail -1 | grep -i "setting.*unidled"                                                                                                                                                                                                                                                                                                           
I0807 12:33:43.879576    4125 kube.go:173] …
```
> Move the UnidledAt controller to cluster-manager

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/metrics/cluster_manager.go
There is no point in unregistering metrics from Prometheus when cluster manager is stopped. Hence removing associated methods handling unregister metrics.
> Remove unregister metrics from cluster manager

- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/util/net.go
On syncPods there is an hybryd overlay route sync to clear out an outdated route. The logic is not matching on IP family so it ends up duplicating routes in dual stack configurations.
> Fix duplicate routes after HO route sync

- go-controller/pkg/ovn/baseline_admin_network_policy_test.go
The test is expecting on DB data before actually updating what it is supposed to expect on and expecting again after.
> Fix BANP unit test flake

- go-controller/pkg/metrics/cluster_manager.go
This fixes a regression associated with IC changes because resource_retry_failures_total metric is not registered for cluster manager module, hence it doesn't collect object max retry failures metric associated with control plane pod. So this makes resource_retry_failures_total  metric is registered for cluster manger as well.
> Register resource max retry failed metric for cluster manager

- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
The test uses IPBlock to block egress traffic from matching pods.
Verify that without the policy we can reach a service running
on the underlay, and that once we create the blocking
policy, we can't anymore.
> e2e, multihoming: Add localnet MultiNetworkPolicy test

- go-controller/pkg/ovn/address_set/address_set.go
- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_dns_test.go
- go-controller/pkg/ovn/egressfirewall_test.go
This should improve the time it takes to create an egressfirewall.
Transaction size is limited to 8000 acls, which should be fine based on https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync.go#L58-L60
but should be verified for older version is case of backporting
To test, use 8000-rule egressfirewall https://gist.github.com/npinaeva/7af14f6aa3234694c6d0e082e6c58d14 and find ovnkube-master or ovnkube-control-plane log `Creating *v1.EgressFirewall <namespace>/default took: <n>s`
in local testing, before change the result is `31.372159307s`, after change `2.599303302s` (with db logging enabled, which takes extra time)
> Create egress firewall with one db transaction

- contrib/kind.sh
The fedora coreos quay.io image tag "stable" is a moving tag so quay.io remove the old image after the tag is moving. This change pre-load that image at kind so it's present after quay.io has remove it.
closes https://github.com/ovn-org/ovn-kubernetes/issues/3855
Pre pull fedora coreos image
> kubevirt: pre pull fedora coreos image

- contrib/kind.sh
Reverts ovn-org/ovn-kubernetes#3857
The kubevirt jobs were skipped on that PR and are otherwise failing
> Revert "kubevirt: pre pull fedora coreos image"

- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/gateway_info/gateway_info.go
- go-controller/pkg/ovn/controller/apbroute/gateway_info/gateway_info_test.go
This PR changes the way the APB external route unit tests were run so that the pods don't rely on the `hostNetwork` to avoid skipping running the northBoundDB code stored in network_client.go, and instead they use the multus annotation to retrieve the pod IP.
@npinaeva @trozet @jcaamano PTAL.
> Change APB unit test to use multus annotation instead of hostnetwork

- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/node/default_node_network_controller.go
Nodes running hybrid overlay only care about routing traffic from pods local to the node into the hybrid overlay's vxlan tunnel. Commit 91046e... changed how the LocalPodLister worked and it grabs all pods in the cluster. Change the filtering of the handler for hybrid overlay to only select pods local to the node so the right ovs flows are created. 
This will correct the operation for hybrid overlay while working to correct the WatchFactory
> Correct the operation of the hybrid overlay

- go-controller/pkg/clustermanager/egressip_controller_test.go
The EIP test case `should not update valid assignments` is flaking. It seems it was always broken because with the current EIP implementation we need the EIP specified in spec to equal whats specified in status and be lexicographical the same.
Opened issue [1] to track and fix it later but for now, this should stop the flakes and it stops the EIP controller from patching the status.
[1] https://github.com/ovn-org/ovn-kubernetes/issues/3853
> EIP TC: stop flake by ensuring EIP spec and status are equal

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
at the beginning of AddNode() we checked if the hybrid annotation had been set on the node being added as a quick way to determine if we should continue. It turns out we also set the nodes drIP to whatever the annotation of the added node is.
Turns out this does not effect the operation too much because we never change the flows associated with the drIP except when nodeName being added is equal to the nodeName of the controller but the internal representation is wrong without this patch.
> fix race condition in hybrid overlay.

- .github/workflows/docker.yml
Fixes this error on the ovn-docker-images workflow which has been preventing us to upload new images from quite some time
```
buildx failed with: ERROR: failed to solve: failed to push ghcr.io/ovn-org/ovn-kubernetes/ovn-kube-f:master: unexpected status from POST request to https://ghcr.io/v2/ovn-org/ovn-kubernetes/ovn-kube-f/blobs/uploads/: 403 Forbidden
```
Fixes: https://github.com/ovn-org/ovn-kubernetes/pull/3607
> Fix push image permissions

- dist/images/ovnkube.sh
- dist/templates/ovnkube-single-node-zone.yaml.j2
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pod_selector_address_set.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/pod_annotation.go
- Enables scale metrics correctly in KIND with single zone per node
- Enables pprof when enabling metrics with KIND
- Prefers to use IPs provided in pod status IPs, and falls back to annotation when needed
- For searching for colliding pods, restrict the search to only pods on the node where the original pod lived, as long as the topology is layer 3, and the pods are not affected by live migration.
> Fix pod delete perf

- test/e2e/unidling.go
If the test fails an assertion, the `createBackend(...)` gorotine is still running after the test end, as the reading from `done` channel is skipped.
Moving that wait to a `defer ...` routine avoids spanning test execution across multiple cases, that can cause panics.
fixes #3882 
cc @martinkennelly , @oribon , @jcaamano 
> e2e: Avoid test panic if unidling test fails

- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/slice.go
- go-controller/pkg/util/slice_test.go
I am not sure how this happened during #3749 but it somehow got excluded..
When cluster manager is attempting to find out if an EIP IP can be hosted by a non-OVN managed network, we dont exclude OVN managed networks.
> EIP multi NIC: ensure we exclude ovn managed networks when CM is assigning EIP

- go-controller/hack/build-go.sh
Fixes a small issue in the `build-go.sh` where the script failed to extract the `k8s.io/client-go` version from the `go.sum` due to 2 factors:
* Wrong path: The file `go.sum` is located inside the `go-controller` directory from the main project, the current variable prefix used to point the path `$OVN_KUBE_GO_PACKAGE` won't find the file because the script runs already in `$OVN_KUBE_ROOT`. So in essence it's trying to run this command:
```
grep 'k8s.io/client-go' github.com/ovn-org/ovn-kubernetes/go-controller/go.sum
```
Inside `$OVN_KUBE_ROOT`, which is the full path to the `go-controller` directory. In my case:
```bash
$> echo $OVN_KUBE_ROOT 
/home/jgil/go/src/github.com/ovn-org/ovn-kubernetes/go-controller
```
* Possibly the wrong file to check to extract this value: Checking the …
> fix: build-go.sh capture k8s.io/client-go version to use in build tag

- go-controller/pkg/ovn/address_set/address_set.go
- go-controller/pkg/ovn/address_set/address_set_test.go
- go-controller/pkg/ovn/admin_network_policy_test.go
- go-controller/pkg/ovn/baseline_admin_network_policy_test.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/egressqos_test.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pod_selector_address_set_test.go
as it should be used only for
testing. This is a follow-up to the 2c252f11344c80718fc1b291d0e0921e2afb4e41 where I added UUID generation for address sets, which can only be used for testing.
Thanks to @jcaamano for pointing this out
> Rename GetDbObjsForAS to GetTestDbAddrSets 

- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- test/e2e/service.go
This adds flow rule into external ovs bridge so that Destination unreachable (Fragmentation needed) packet can be put onto OVN pipeline for a given loadbalancer or ingress type of service ip address and forwards those packets into appropriate target endpoint pods. This eventually makes Path MTU Discovery (PMTUD) works end to end.
This is just an extension of [freedge](https://github.com/freedge)'s effort (PR https://github.com/ovn-org/ovn-kubernetes/pull/3696) and makes that work for every external service scenarios.
> Forward ICMP packets to OVN loadbalancer

- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- test/e2e/pod.go
- test/e2e/service.go
1. pod sends request to server outside the cluster
2. server responds back with a large pkt
3. GR sends frag needed when pkt hits rtoj since gateway_mtu is set
4. pkt going out is not SNAT-ed by OVN so it goes out with podIP
5. pkt is dropped by server since it doesn't know what to do
6. server continues to hammer large pkts
7. OVN team doesn't have a nice way to fix this on their side
8. Compromise: On the CMS we configure gateway_mtu on both rtoe and rtoj ports such that needs frag is sent at rtoe itself and this time it will be SNATed to nodeIP
Also fixes the MTU test flake on IC lanes:
Sep  5 14:00:02.820: INFO: Flushing the ip route cache on ovnkube-node-sc4v8
Sep  5 14:00:02.820: INFO: Running …
> Enable gateway_mtu on rtoe port of GR

- go-controller/pkg/node/node_ip_handler_linux.go
When the addressManager detects changes in the node's address, it will update the node address annotations, but it was not reflecting the address changes in the OpenFlow rules within the node via openflowManager.updateBridgeFlowCache(). This could result in nodes having stale rules that affect functionalities such as hairpin.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-18353
> Update bridge flow cache when the host address changes

- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/util/node_annotations.go
Ready for review. See commits for details. 
Essentially this is a revert to previous behaviour that was introduced by EIP multi NIC PR.
In the original EIP multi NIC PR, I erroneously thought we get the IP + subnet for the primary OVN managed node network from annotation `k8s.ovn.org/node-primary-ifaddr` in both cloud and non cloud env.
I missed the distinction that in the cloud we get the IP from that annotation but we get the subnet from CNCCs annotation `cloud.network.openshift.io/egress-ipconfig`. This PR reverts to this behaviour.
On GCP cloud, the subnet seen on the `node-primary-ifaddr` is different to what is seen in the CNCC subnet and this error was found there.
> EIP: fix how we detect primary interface EIP configuration

- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
LSPs for remote pods were being needlessly configured on localnet
secondary networks. To avoid this, watch for nodes on these networks as
well just as with the layer2 networks which results in a bunch of code
moved from a layer2 specific event handler to the common one.
Additionally, remove secondary network ports for remote pods on 
node local to remote events.
> Watch nodes for localnet secondary networks

- go-controller/pkg/clustermanager/network_cluster_controller.go
when this used to be called from a master pod
clearInitialNodeNetworkUnavailableCondtion() was called during both add and update. It seems as though there are some instances where there is a delay between when the node is created and when gcp adds the taint, clearing on unpdate will ensure that the taint is removed.
this was seen in a bug https://issues.redhat.com/browse/OCPBUGS-18572?filter=-1
> [OCPBUGS-18572] clearInitialNodeNetworkUnavailableCondition() called on node update

- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
This error was introduced in eip multi nic feature.
Revert to how it was previously.
For IPv6, this may cause reassignment of 'compressed' IPv6s.
> EIP: fix entry of EIP into validated EIP set

- go-controller/cmd/ovnkube-identity/ovnkubeidentity.go
- go-controller/pkg/csrapprover/approver.go
- go-controller/pkg/csrapprover/approver_test.go
- go-controller/pkg/ovnwebhook/nodeadmission_test.go
- go-controller/pkg/ovnwebhook/podadmission.go
- go-controller/pkg/ovnwebhook/podadmission_test.go
- go-controller/pkg/ovnwebhook/user.go
This change introduces additional certificate acceptance condition so that other components reuse ovnkube-identity.
This change introduces add command line options in ovnkube-identity to support to reuse this feature (csrapprove and pod webhook) to other components.
> Add additonal certificate acceptance condition feature in ovnkube-identity

- go-controller/pkg/clustermanager/egressip_controller.go
If the cloud provider is still working on de-associating an egress IP from a node, it is possible that a following association will be stopped. This commit implements a better log explaining this scenario.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-18647
> Trivial: Improve CloudPrivateIPConfig logs when it cannot be assigned.

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/master.go
having a hybrid overlay node in the cluster will cause upgrading to interconnect to fail currently.
We need to skip hybrid overlay ndoes when checking for node-subnet annotations as they do not have one.
would fix: https://issues.redhat.com/browse/OCPBUGS-18352
> skip hybrid overlay nodes when upgrading to interconnect

- dist/templates/k8s.ovn.org_egressfirewalls.yaml.j2
- dist/templates/k8s.ovn.org_egressips.yaml.j2
- dist/templates/k8s.ovn.org_egressqoses.yaml.j2
- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
- go-controller/pkg/crd/egressip/v1/types.go
- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/ovn_test.go
Reasons for adding this network status field in the first place was to allow users to quickly establish which network an EgressIP IP is assigned to. 
This is a good idea for users.
The original goal can be accomplished without the burden of introducing a new field within EIP IPs status and managing this field during upgrade and for existing assigned EIP IPs isnt trivial. 
Simplify things and reduce the possibility of bugs introduced by this new field.
OVN kube node doesnt depend on this field so its removal is trivial.
Add extra logging to accomplish the original goal.
@trozet
> Remove Network field from EIP status

- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
Previous to this change, when we were processing Pod IPs, we didnt check if the pod IP is the same IP family as the EIP.
> EIP multi NIC: only match EIP IP family with pod IP family

- .github/workflows/test.yml
- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/libovsdb/ops/model.go
- go-controller/pkg/libovsdb/ops/model_client.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/ovn.go
Fixes node ip migration with IC. Now on primary IP change, IC will call add local/remote zone node, which will properly update the encap for the chassis. Also re-enables node ip migration CI with IC. 1 additional commit to fix some things found along the way.
Closes #3636
> Fix node ip migration encap

- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
There is a duplicated call to addOrUpdateSubnet at switch manager. This change remove that.
switch-manager: Remove ippool duplicate call
> switch-manager: Remove ippool duplicate call

- go-controller/pkg/ovnwebhook/nodeadmission.go
- go-controller/pkg/ovnwebhook/nodeadmission_test.go
- go-controller/pkg/util/node_annotations.go
Allow ovnkube-node to set util.OvnNodeManagementPort.
Based on https://github.com/ovn-org/ovn-kubernetes/pull/3927.
/cc @wizhaoredhat @tssurya @jcaamano
> Allow ovnkube-node to set util.OvnNodeManagementPort

- go-controller/pkg/node/linkmanager/link_network_manager.go
Wasnt caught earlier because:
- No unit tests for link manager
- E2Es didnt catch it because no coverage for multiple non-OVN managed EIPs on a single node
> Fix removal of address from link manager

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
- go-controller/pkg/ovn/controller/apbroute/node_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/syncmap/syncmap.go
Fixes an issue in APB External Route where deleting a pod and recreating it failed due to the Deleted state in the routeInfo. The solution involves getting the status before obtaining the routeInfo lock and comparing it after obtaining lock: if the values differ, return with error. If the values match, there has been no changes and it is safe to reuse the routeInfo in case it was deleted.
@npinaeva @trozet @jcaamano PTAL
> [OCPBUGS-17692] Failed to apply APB External Route to a recreated pod

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/obj_retry_node.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressgw.go
- go-controller/pkg/ovn/namespace.go
- test/e2e/external_gateways.go
Currently in legacy ICNI, we use the `k8s.ovn.org/external-gw-pod-ips` as a way for communicating the change in an ICNI gateway pod's status (add/delete/update) from the ovnkube-controller (ovnkube-master in nonIC) to ovnkube-node. In IC multi-zone since the ovnkube-controller and ovnkube-node run as the same process, this is not needed. We can remove dependeny on the extra annotation update we do for IC multizone deployments. We flush the conntrack on ovnkube-controller directly.
On nonIC and IC with single zone we still use the annotation approach for flushing.
Review the namespace update bits carefully.
E2Es present for signalling issues. Ran v6 ones locally since CI does not run it. …
> IC/ICNI: Remove the need for k8s.ovn.org/external-gw-pod-ips annotation in

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/hybrid-overlay/cmd/hybrid-overlay-node/hybrid-overlay-node.go
- go-controller/pkg/util/kube.go
`hybrid-overlay-node` runs on windows nodes and should be able to set the same annotations as ovnkube-node.
This means that it requires also requires a per-node certificate.
/cc @jcaamano @JacobTanenbaum
> Run node certificate manager in hybrid overlay

- go-controller/pkg/node/gateway_shared_intf.go
`SyncServices` in gateway code would try and add iptable rules for
headless services resulting in ovnkube-node crashing
```
I0929 16:34:08.992237   17788 iptables.go:35] Chain: "OVN-KUBE-ITP" in table: "mangle" already exists, skipping creation: running [/usr/sbin/iptables -t mangle -N OVN-KUBE-ITP --wait]: exit status 1: iptables: Chain already exists.
I0929 16:34:08.997235   17788 iptables.go:27] Adding rule in table: mangle, chain: OVN-KUBE-ITP with args: "-p TCP -d <nil> --dport 80 -j MARK --set-xmark 0x1745ec" for protocol: 0 
I0929 16:34:08.998672   17788 iptables.go:35] Chain: "OVN-KUBE-ITP" in table: "mangle" already exists, skipping creation: running [/usr/sbin/iptables -t mangle -N OVN-KUBE-ITP --wait]: exit status 1: iptables: Chain …
```
> GW: Ignore headless services in syncServices

- go-controller/pkg/node/default_node_network_controller.go
in some cases, multiple nodes will have to sync and we may not have enough subnets available for all of them. In that case we don't want to quit the sync on other nodes if one is found to not have the subnet annotation as the others may still have it.
JIRA: https://issues.redhat.com/browse/OCPBUGS-18598
> dont quit if node does not have subnet annotation

- go-controller/pkg/ovn/controller/apbroute/external_controller_namespace_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_pod_test.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go
- go-controller/pkg/ovn/controller/apbroute/gateway_info/gateway_info.go
- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- go-controller/pkg/ovn/controller/apbroute/network_client.go
Currently, when adding a new pod to a cluster with an APB CR, the controller will process the pod before it reaches the `Running` phase, which is before the target pod has an [IP allocated](https://github.com/ovn-org/ovn-kubernetes/blob/91046e8892e603822cbae2c5ff1351b703664da8/go-controller/pkg/ovn/controller/apbroute/network_client.go#L168-L170). This leads to the situation where the pod information cache is [initialized](https://github.com/ovn-org/ovn-kubernetes/blob/91046e8892e603822cbae2c5ff1351b703664da8/go-controller/pkg/ovn/controller/apbroute/network_client.go#L168-L170) with the GW IPs presumably added in the nbDB, when in truth nothing happened because the pod didn't have an IP to link to. When the event where the pod reaches the `Running` phase is generated, the logic checks …
> APB: return error if the target pod is in Pending phase when adding the GW IPs

- dist/images/ovnkube.sh
23.09 northd has a new option that lets the CMS (ovnkube) set a maximum processing loop time. When this option is enabled, northd will batch updates (but do no processing of them) for the duration of the last processing loop, saving significant CPU.
When the processing loop time exceeds the CMS-configured backoff interval, northd will no longer sleep, trading off CPU usage for responsiveness to changes.
During scale tests we observed that when northd was fed a continous stream of changes from kube-burner -> ovnkube -> NB it was never able to complete work quickly enough to sleep before the next change came in. Until more portions of northd are moved to Incremental Processing (IP) most of the processing time is taken by recomputes of unchanged data. Doing this continuously is pretty …
> ovnkube.sh: set northd backoff interval to save CPU

- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
The EIP controller being event driven means we don't
have control over the order of events that we get.
There is a bug around the ordering of event processing currently:
- When a node goes offline, 
- cluster-manager calls deleteEgressNode based on healthchecks and then patches the EIP to reflect that on the status by deleting the node immediately from the status
- this causes zone-controller to take action and do tear down of OVN setup for this EIP in the respective zone
- the CPIP also reacts and starts deleting the CPIP for this EIP (On clouds like azure this is very slow)
- node now comes back online - no control on the amount of time its down
- cluster-manager is super fast in IC as its asynchronous and tries to re-add this egressNode
- CM …
> EIP: Fix CPIP updates on cloud environments

- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
This change is to prevent Type Assertion panic in case the object has already been removed but was put into tombstone of type cache.DeletedFinalStateUnknown which contains the deleted key and object.
JIRA: https://issues.redhat.com/browse/OCPBUGS-19961
It is hard to reproduce .
- Raise error and return if the object is neither of type NetworkAttachmentDefinition nor of type cache.DeletedFinalStateUnknown.
- Raise error and return if the object in tombstone is not of type NetworkAttachmentDefinition.
- Continue normally if none of the above condition matches.
> Handle tombstone of type cache.DeletedFinalStateUnknown while deleting net-attach-def

- dist/images/ovnkube.sh
- dist/templates/ovs-node.yaml.j2
Function[1] sets n_handler to maximum number of CPUs available on the node and in turn overrides n-handler-threads while setting[2] up threads. So, right now there is no point in setting n-handler-threads to 10 when number of CPUs are more than 12. Limiting n-revalidator-threads to 4 also not at per with the best practices in per-cpu mode.
[1] - https://github.com/openvswitch/ovs/blob/master/lib/dpif-netlink.c#L2570-L2591
[2] - https://github.com/openvswitch/ovs/blob/master/ofproto/ofproto-dpif-upcall.c#L650
Currently n-revalidator-threads can be limited by setting n-revalidator-threads other_config but that is not suitable in per-cpu mode and its best to create default(n-handler-threads/4+1) number of threads …
> Setting custom n-handler-threads is not supported in per-cpu mode

- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
Current node gateway init logic set other_config:hwaddr on the bridge twice when bridge is created:
bridgeForInterface(...)
`-- util.NicToBridge(bridgeName)
`-- RunOVSVsctl(...) <-- set bridge other_config:hwaddr #1
...
`-- bridgedGatewayNodeSetup(...) <-- set bridge other_config:hwaddr #2
2nd set completely redundant, hence, remove it.
Move call to get MAC address up into bridgeForInterface() to simplify bridgedGatewayNodeSetup().
Signed-off-by: Dmytro Linkin <dlinkin@nvidia.com>
> ovnkube-node: Remove redundant set of other_config:hwaddr

- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_linux_test.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
This is a fix for issue [#3867](https://github.com/ovn-org/ovn-kubernetes/issues/3867).  This happens mainly for SR-IOV/vDPA interfaces when enabling the ovn-k secondary interface, sometimes the netdev can't be moved from the host to the pod namespace.
This is the faulty scenario:
- netdev in the host to be moved to pod namespace is called eth0
- the pod has already an interface called eth0 (primary interface)
- when the user creates a new pod (planning to use the interface above), the pod creation fails with the message "file exists"
> netdev can't be moved to pod namespace

- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/ovn_node_linux.go
- Fixes data race where properties of the hybrid controller are read during node add, but may also be being written to at the same time (like n.drIP). Now there is a mutex on the controller, which is write locked when the local node add happens and the controller properties may be updated. On remote node or pod add, the controller is read locked.
- During *every* node add, the code would attempt to add *every* pod in the cluster to this node's hybrid overlay. Modified this behavior so that this only happens when the state of our node is not PodsInitialized, as well as filtered out only pods local to our node.
- During node add, if setting up hybrid overlay failed, we would still try to add pods. Additionally if adding a pod failed, we would not return error and then set …
> Various fixes to hybrid overlay

- go-controller/pkg/allocator/ip/subnet/allocator.go
- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/kubevirt/router.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/kubevirt_test.go
- go-controller/pkg/ovn/master.go
closes https://issues.redhat.com/browse/OCPBUGS-19445
When the migrated IPs node has being removed and a new node owning the
subnet is added a new pod can be created before the migrated IPs are
stored at ip pool at sync so a duplicate IP can happend. This change
reserve the migrated IPs atomically during subnet registration at ip
pool so new pods will be assigned with different IPs.
Unit test included.
Reserver migrated atomically IPs at add node to prevent IP duplication
> kubevirt: Reserve migrated IPs at add node

- contrib/kind.sh
This fixes `multi-network-enable` redeploy flow on existing kind cluster. 
Use `./kind.sh -mne` to create the cluster
and then `./kind.sh -mne --deploy` to redeploy OVN-K, reusing the same cluster.
> kind: Allow redeploy multi-network-enable OVN-K

- go-controller/pkg/config/config.go
Prior to this, we dont consume config file options for CM HA, specifically to configure LE.
Also, in our current code when you run ovnkubecontroller & cluster manager together, we use cluster managers HAs options to set the HA defaults but they arent being consumed from the `kube-config.conf` override file:
```go
var haConfig *config.HAConfig
var name string
switch {
case runMode.ovnkubeController && runMode.clusterManager:
metrics.RegisterClusterManagerBase()
fallthrough <==== fall through here
case runMode.ovnkubeController:
metrics.RegisterOVNKubeControllerBase()
haConfig = &config.MasterHA
name = networkControllerManagerLockName()
case runMode.clusterManager:
metrics.RegisterClusterManagerBase()
haConfig = &config.ClusterMgrHA  <=== cluster manager ends up setting the haConfig …
```
> Cluster manager: fix consumption of CM HA config file overrides

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_pods_test.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/util/subnet_annotations.go
There is a race condition on startup when a scheduled pod is allocated
an IP that is also annotated on a completed pod by which the delete flow
of the completed pod will check if any other pods are using that IP just
before the scheduled pod is annotated, missing that and thus
de-allocating the IP, leading to the possibility of a third pod being
allocated that same IP and ending up with duplicate IPs for two different
pods.
By allocating the IPs of completed pods on startup, we prevent other
scheduled pods from being allocated the same IPs.
However, on startup, multiple pods might be annotated with the same IP as long as
just one of them is running. Thus, we cannot release the IPs for the
completed ones as that would de-allocate the IP which the running pod is
using.
To avoid that, track …
> Allocate completed pods on startup

- go-controller/go.mod
- go-controller/go.sum
- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cniserver_test.go
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/util/sriovnet_linux.go
- go-controller/vendor/github.com/k8snetworkplumbingwg/govdpa/pkg/kvdpa/device.go
- go-controller/vendor/github.com/k8snetworkplumbingwg/govdpa/pkg/kvdpa/util.go
- go-controller/vendor/modules.txt
The current PR introduces support for vhost-vDPA devices.
There are 2 main changes:
1)  DeviceInfo support on ovn-k
See deviceInfo spec at https://github.com/k8snetworkplumbingwg/device-info-spec
This commit is required for introducing vhost-vdpa
2) vhost-vDPA device support
Please make sure to merge this PR first: https://github.com/ovn-org/ovn-kubernetes/pull/3868
> vhost-vDPA support

- go-controller/hybrid-overlay/pkg/controller/ovn_node_linux.go
- go-controller/hybrid-overlay/pkg/util/util.go
- go-controller/pkg/clustermanager/node/node_allocator.go
- go-controller/pkg/config/config.go
- go-controller/pkg/node/controllers/egressip/namespace.go
- go-controller/pkg/node/controllers/egressip/pod.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/base_network_controller_policy.go
- go-controller/pkg/ovn/controller/apbroute/external_controller.go
- go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/util/kube.go
Instead of ignoring the error returned from `LabelSelectorAsSelector` handle it to avoid using nil values.
Note: NetworkPolicy shouldn't ever have invalid labelselectors since this is verified in the API already, I don't think it hurts to have the error checks though. 
I wasn't able to find out how we could add labelSelector validation to the CRD but if it is possible it doesn't conflict with the proposed changes.
Found in https://issues.redhat.com/browse/OCPBUGS-20210
/cc @tssurya
> Always handle invalid label selectors

- go-controller/pkg/ovn/egressip_test.go
ed8842c065860b93c82101fb5980585b055304b2 removed a part of the fix introduced in c089c2ead7302c7fb5d69e641c4d267bd31312d8:
```
- fakeOvn.patchEgressIPObj(node2Name, updatedEgressIP.String())
- expectedNAT.ExternalIP = updatedEgressIP.String()
+ fakeOvn.patchEgressIPObj(node2Name, egressIPName, updatedEgressIP.String(), "::/64")
```
This commit adds it back.
Saw it here: https://github.com/ovn-org/ovn-kubernetes/actions/runs/6626475165/job/17999485415?pr=3972
/cc @martinkennelly @jcaamano @tssurya
> Fix bad expected NAT on egressip unit test flake

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/kubevirt/router.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods_test.go
This was recently changed incorrectly. A pod can be deleted with no IPs annotated so don't assume that is an error.
Incidentally fix the case for a live migratable pod as well which would have failed in the same way before.
Fixes: #3919
> Fix remove remote pod when no IPs annotated

- go-controller/pkg/config/cni.go
- go-controller/pkg/util/multi_network_test.go
Starting from CNI 1.0.0, the only accepted configuration format possible features a config list of plugins: https://github.com/containernetworking/cni/blob/main/SPEC.md#configuration-format
Support plugin list, in addition to single plugin configuration.
> multi network: Support NAD plugin list in addition to single plugin configuration

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
for an overloaded cluster. With the previous params we only allowed 1 retry in case tryAcquireOrRenew failed within 10 seconds, and no retry otherwise. When etcd is overloaded, lease requests may timeout in 10 seconds, and that will result in giving up the leadership without retry.
For big clusters leadership change may be a problem, because initial sync of ovnk-master may take hours and during that time no new requests are handled, so we better be a bit more conservative on giving up the leadership
> Update leaderelection config to allow retries 

- go-controller/pkg/libovsdb/ops/chassis.go
- go-controller/pkg/libovsdb/ops/model_client.go
- go-controller/pkg/libovsdb/ops/model_client_test.go
For each chassis, there should only be only 1 encap-ip. However the OVN database allows for multiple encap-ips per chassis. In order to recover from a situation where the database already has an existing encap-ip for a chassis and there is a different encap-ip being added to the chassis; we introduce this fix to use "OnModelUpdates" to override the chassis encaps instead of previously appending to it.
Note: This can happen in the case of the DPU because the DPU can have the incorrect encap-ip stored in the SBDB because converting the cluster to DPU-aware may not be a Day0/1 operation but rather a Day2 operation.
> Prevent multiple encap-ips per single chassis

- go-controller/pkg/libovsdb/ops/portgroup.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_multicast.go
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/multicast_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/util/batching/batch.go
- go-controller/pkg/util/batching/batch_test.go
We already have namespace port groups that are created by multicast and updated by pod handlers. That implementation has some races because port group is created conditionally. First commit changes that to create namespace port groups similar to namespace address sets on namespace initialization and update multicast handler to use that.
Second commit updates egress firewall to use namespaced port group instead of cluster port group + address set match to reduce the number of OVS flows.
Namespace port groups can be created conditionally, but that would require namespace locking for every port group-related operation, and may be worse for performance than 1 extra port group per namespace
> Egressfirewall use port groups

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/ovn/kubevirt_test.go
When a live migration fails at completed virt-launcher pod with newer
creation timestamp is lingering in the system so the virt-launcher that
is really running the VM is hidden by it and routes are wrongly
reconstructed. This change take into account if the pod is completed to
ignore it marking it as stale.
Closes https://issues.redhat.com/browse/OCPBUGS-22767
It includes a unit test that emulate the result of failing migration, completed virt-launcher pod with newer creation timestamp.
kubevirt: Ignore completed virt-launcher pods
> kubevirt: Ignore completed virt-launcher pods

- dist/images/Dockerfile.ubuntu
This PR contains fixes for the dist/image/Dockerfile.ubuntu.
One includes the newly created binary `ovnkube-identity` and another bumps image version to install a newer version of OVN packages
Based on commits:
https://github.com/ovn-org/ovn-kubernetes/commit/50a5c60140956e0c4444500f3304784bb1263757
https://github.com/ovn-org/ovn-kubernetes/commit/7dc48048a346f175772fe5c2839b083f7a20c597
Build and run a docker image based on the Dockefile: dist/image/Dockerfile.ubuntu
Dockerfile.ubuntu: include ovnkube-identity binary and bump the image version which contain newer OVN packages
> Dockerfile.ubuntu fixes

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/node_ip_handler_linux.go
There was additional code to handle the OVN-IC zones from the SBDB to support OVN-IC. Since the DPU-Host mode assumes that OVN does not run alongside it, the code needed to be modified to prevent accesses to the OVN DBs.
We need to use the correct CIDR address for the DPU. The "GetNodePrimaryIP" does not return a CIDR address. We should pass the ifaddr from the gateway bridge.
> Dpu OVN-IC enablement

- go-controller/Makefile
Running make check as root on Ubuntu 22.04, make complains with the following:
/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node/gateway_init_linux_test.go:1387                                                        [42/9265]    sets up a shared interface gateway DPU host
/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/testing/testing.go:18
Unexpected error:
<*errors.errorString | 0xc000c0be50>:
mount --make-rshared /var/run/netns failed: "permission denied"
{
s: "mount --make-rshared /var/run/netns failed: \"permission denied\"",
}
occurred
This patch runs container in privileged mode to overcome all permissions.
> go-controller/Makefile: Fix make check on Ubuntu

- go-controller/pkg/util/sriovnet_linux.go
If `GetVdpaDeviceByPci` returns an error we should log the result and allow `GetSriovnetOps` to run instead of bailing out.
This patch makes `GetVdpaDeviceByPci()` errors non fatal.
Found while testing on a ConnectX environment.
> sriovnet_linux: Make GetVdpaDeviceByPci errors non fatal

- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
During start up when existing pods run through the sync function, their IPs will attempt to be pre-allocated. This fails if the node does not exist, which can happen in kapi. Ignore those errors rather than causing ovnkube start up to fail.
> Ignore pod allocation errors during sync if no node exists

- go-controller/pkg/ovn/controller/apbroute/master_controller.go
- test/e2e/external_gateways.go
When an APB fails to apply, the status fails to update because the `LastTransitionTime` is nil. The logs show the following:
```
Failed to update AdminPolicyBasedExternalRoutes duplicated-first-policy status: failed to update AdminPolicyBasedExternalRoutes duplicated-first-policy status: AdminPolicyBasedExternalRoute.k8s.ovn.org "duplicated-first-policy" is invalid: [status.lastTransitionTime: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```
I added a new e2e test case to cover this scenario because in the unit tests, the field `LastTransitionTime` comes populated when the object is retrieved by the controller, so it's not possible to reproduce it there.
@npinaeva …
> APB: Ensure last transition time is always updated in status regardless of success or failure

- dist/images/iptables-scripts/iptables
- dist/images/iptables-scripts/iptables-restore
- dist/images/iptables-scripts/iptables-save
/usr/sbin/iptables is the de facto path for iptables in most distributions. Notably, since kind switched to Debian 11-based images, ovn-kubernetes fails to deploy there because Debian 11 provides iptables *only* in /usr/sbin.
On Ubuntu and Fedora, /sbin and /usr/sbin are the same directory, so iptables is available in both location and nothing changes there. Debian 12 and later also have the same setup.
Deploy clusters with kind 0.20 with ovn-kubernetes; `ovn-kube-pod` fails to start with
```
failed to start node network manager: failed to start default node network controller: failed to create IPTablesHelper for proto 0: could not get iptables version: exit status 127
```
Applying this …
> Use /usr/sbin/iptables instead of /sbin/iptables

- dist/images/iptables-scripts/ip6tables
- dist/images/iptables-scripts/ip6tables-restore
- dist/images/iptables-scripts/ip6tables-save
Same as https://github.com/ovn-org/ovn-kubernetes/pull/4015
This is needed to use KIND 1.20.0 which is needed for the kube 1.28 rebase: https://github.com/ovn-org/ovn-kubernetes/pull/3978
> Use /usr/sbin/iptables6 instead of /sbin/iptables6

- contrib/kind.sh
- dist/images/daemonset.sh
Signed-off-by: josecastillolema josecastillolema@gmail.com
j2 dependency uses the [imp module](https://docs.python.org/3/library/imp.html) which has been deprecated since Python 3.4 and removed in 3.12 (see https://github.com/kolypto/j2cli/issues/80).
j2 authors have published  [Jinjanator](https://pypi.org/project/jinjanator/) as the new alternative, which resolves this issue by adding a much more flexible and less invasive plugin mechanism.
Closes https://github.com/ovn-org/ovn-kubernetes/issues/4011
Manually verified on Python 3.12.0.
Should be tested in previous Python versions (guess the CI will already do that?)
Python 3.12 support by replacing j2 for jinjanate
> Replace j2 for jinjanate

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/default_node_network_controller_test.go
This PR makes default network controller to wait for Encap entry to be created because in some cases local node add event is received a bit later than network controller and it looks up for encap entry and giving up on starting ovnkube controller.
> Fix race condition between encap row update and retrieval

- dist/images/daemonset.sh
- dist/templates/ovnkube-node.yaml.j2
- dist/templates/rbac-ovnkube-node.yaml.j2
This PR fixes templating around the `ovnkube-node-dpu-host`.
One fix is to address the RBAC issues and the second is to allow to switch `OVN_ENABLE_OVNKUBE_IDENTITY` for that specific mode.
These issues were found while testing the master branch on a new environment.
Deploy ovn-kubernetes on a Kubernetes cluster with a node that has a DPU.
> Fix templating around ovnkube-node-dpu-host

- go-controller/pkg/util/net_linux.go
The previous `${interface}:vip` label on keepalived addresses yielded an error whenever the total label length exceeded the allowed limit of 15 characters. As a result, we simplified the label to be just `vip`, which is sufficient for our purposes: https://github.com/openshift/machine-config-operator/pull/4040 Let's keep the call to `HasSuffix` to be compatible with both implementations.
> Account for the new VIP address label

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/vendor/k8s.io/client-go/informers/factory.go
Kubernetes client-go v0.29 (not yet released) adds a WithTransform() option to shared informer factories that lets callers modify objects before they are added to the cache. Since we cache lots of objects (every pod, service, endpoint, node, etc) we can nil out a bunch of fields we don't care about, and save a lot of memory. This reduces ovn-kube memory usage by about 30% at high scale (250 nodes, 60,000 pods, 30,000 services)
The only catch is we need to carry a client-go patch until we can bump to v0.29 next year. But it's really small.
> Significantly reduce shared informer memory usage

- go-controller/hybrid-overlay/pkg/controller/node.go
- go-controller/hybrid-overlay/pkg/controller/node_linux.go
- go-controller/hybrid-overlay/pkg/controller/ovn_node_linux.go
- go-controller/hybrid-overlay/pkg/controller/ovn_node_linux_test.go
- go-controller/pkg/clustermanager/node/node_allocator.go
- go-controller/pkg/clustermanager/zone_cluster_controller.go
- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/gateway_cleanup.go
- go-controller/pkg/ovn/hybrid.go
- go-controller/pkg/ovn/hybrid_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/types/const.go
With this patch, when hybrid overlay is enabled, a node can dynamically be switched from a OVN node to a hybrid overlay node or versa vice.
When the node is switched to a ovn node, OVN-K will treat it as adding a new OVN node, and try to remove the HO static routes and policies like a HO node is removed.
When the node is switched to a HO node, OVN-K will treat it as deleting a existing OVN node, and adding a HO node.
This patch is primary for the SDN live migration use case of OpenShift
> Allow a node switching between OVN node and hybrid overlay node

- go-controller/pkg/clustermanager/zone_cluster_controller.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/util/node_annotations.go
- test/e2e/service.go
- test/e2e/util.go
https://github.com/ovn-org/ovn-kubernetes/pull/3886 introduced a regression. By setting the MTU of the pod network on the external facing interface of the gateway router, now any large host->service->host UDP traffic will cause ICMP needs frag and install an MTU route cache entry between nodes.
This PR reverts the commit to configure MTU on the GR RTOE interface, adds testing to ensure it doesn't happen again, and the original issue that #3886 was added for is addressed by an OVN fix that we already have:
https://github.com/ovn-org/ovn/commit/0e49f49c73d67ba4869d658a5b9dfd8114513e7c
> Reverts setting MTU on GR external port

- go-controller/hybrid-overlay/pkg/controller/ho_node_windows.go
- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/kube/kube.go
- go-controller/pkg/kube/mocks/Interface.go
- go-controller/pkg/kube/mocks/InterfaceOVN.go
- go-controller/pkg/metrics/ovnkube_controller.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync.go
- go-controller/pkg/ovn/external_ids_syncer/acl/acl_sync_test.go
- go-controller/pkg/ovn/gateway_cleanup.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/hybrid.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovndbmanager/ovndbmanager.go
Listing when there's a bunch of API objects puts lots of load on the apiserver. Be nice and use paging.
Thankfully most of our accesses are from the informer.
> kube: use paging when List-ing API objects directly

- test/e2e/kubevirt.go
This PR ensures a KubeVirt VM tolerates a failed migration - meaning the VM stays in the original pod, but is for all effects available.
> kubevirt, live migration: ensure VM tolerates migration failure

- contrib/kind.sh
- dist/images/.gitignore
- go-controller/pkg/node/egress_service_test.go
- go-controller/pkg/util/iptables.go
- test/e2e/external_gateways.go
- test/e2e/service.go
a) Add ovnkube-ipsec to .gitignore
b) Fixes implementation of mock function `func (f *FakeIPTables) List(...)` in `pkg/util/iptables.go` is not correct.  See: https://github.com/ovn-org/ovn-kubernetes/issues/4026
c) Fixes style of klog.Infof in `test/e2e/external_gateway.go` (the linter flagged that for me for some reason whereas it seems to have gone unnoticed)
d) Fixes `sudo rm -rf metallb` in `kind.sh` and instead replaces it with a `chmod` to make directories `u+rwx`
e) Fixes issues with netmask for `client_network` network for `ip route add` (hardcoded `/16` even though the netmask can be different). See https://github.com/ovn-org/ovn-kubernetes/issues/4028
f) Fixes broken cleanup logic of test `of type NodePort should listen on each host …
> Various upstream fixes

- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_shared_intf.go
- test/e2e/egressip.go
- test/scripts/e2e-cp.sh
In SGW mode we don't support doing IP fragmentation when routing for most
of the flows because they don't go through the host kernel and OVN/OVS
does not support fragmentation. This is can be considered as by design.
In LGW mode we support doing IP fragmentation when routing for the
opposite reason. However, some egress traffic is an exception 
since it doesn't go through the host network stack even in LGW mode. 
To support fragmentation for this type of flow we need to explicitly send replies
to egress traffic that requires fragmentation to the host kernel
> Fragment oversized reply packets in LGW mode

- go-controller/pkg/metrics/ovn.go
This is the shortest PR I have ever made.
While reading through the metrics I noticed that there was a missing space in the help text, this is fixed with this PR.
> go-controller: added missing space to description of metric

- dist/images/daemonset.sh
- dist/templates/ovnkube-node.yaml.j2
This PR introduces a new `ovnkube_app_name`: `ovnkube-node-dpu` together with its corresponding yaml.
This helps deployment on DPU nodes, allowing custom variables to be defined only for that specific mode.
Deploy ovn-kubernetes over a Kubernetes cluster that has a DPU node.
> Add ovnkube_app_name ovnkube node in dpu mode[.yaml]

- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
While https://github.com/ovn-org/ovn-kubernetes/pull/4025 reverted setting the MTU on the rtoe GR port, it did not address upgrades and clearing the value. This commit fixes it and adds a test case.
> Clear RTOE GR MTU on upgrade

- dist/images/ovnkube.sh
- go-controller/pkg/metrics/ovs.go
They may be used to create alerts to signal when OVS is having performance issues.
Based on input from OVN team:
```
ovs-appctl coverage/read-counter upcall_flow_limit_kill
If the value on this one changes, that may be a trigger to fire an alert.  Coverage is increased every time the condition gets hit, the log appears only once.
The coverage counter:
ovs-appctl coverage/read-counter upcall_flow_limit_hit
Indicates that the upcall is not installing a flow into a datapath.  Potentially deserve to be an alert as well.
```
> Add 2 OVS metrics upcall_flow_limit_kill and upcall_flow_limit_hit.

- contrib/kind.sh
Go on Linux dynamically links C libraries to have faster and smaller builds.
This was causing GLIBC mismatches with the [plugins](https://github.com/containernetworking/plugins.git).
This PR exports CGO_ENABLED=0 to disable CGo and get rid of the dependencies.
> Fixed CNI plugins compilation issue in kind.sh

- go-controller/pkg/libovsdb/ops/portgroup.go
- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pods_test.go
to only create port group if it doesn't exist and don't update ports or acls, since they should be updated by other handlers (pod/multicast/ egressfirewall/etc).
Add namespace and pod unit tests to cover new port group functionality.
The problem was that namespace handler on initial sync would delete all ports (because logical port cache where it got lsp UUIDs wasn't populated) and all acls (they were just set to nil). Even though both ports and acls will be re-added by the corresponding handlers, it may cause disruption.
It was missed, because multicast handler that was used before, had to create port groups when the corresponding namespace requested multicast (so after lsps were already added to the namespace), but the new implementation creates this port group on namespace creation, so …
> Update namespace-owned port group (that used to be managed by multicast)

- .github/workflows/test.yml
- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/egress_service_test.go
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/linkmanager/link_network_manager.go
- go-controller/pkg/node/linkmanager/link_network_manager_test.go
- go-controller/pkg/node/openflow_manager.go
- go-controller/pkg/util/ovs.go
- test/e2e/node_ip_mac_migration.go
- test/e2e/node_ip_migration.go
- test/scripts/e2e-cp.sh
If the MAC changes on the interface used in OVS and the OVS bridge, OVN may still retain the old MAC on its GR. This can cause OVN and the host to both respond with different MACs for the same IP address, leading to network disruption. A common scenario for this is a server with a bond. When the node is rebooted, the bond MAC may change depending on which slave comes up first. When this happens, ovnkube-node starts up and is unable to sync its informers and proceed to full start up, due to disruption with kapi.
Note, this can be avoided by setting the MAC specifically for the bond to always be the mac of the first slave.
This PR adds port security in a sense to the breth0/br-ex bridge. It drops any traffic sent from the OVN patch port that has a MAC other than the one we expect by …
> Adds port security for external OVS bridge for OVN MAC address

- go-controller/pkg/informer/informer_test.go
When starting the informer factory and the worker thread, a delay may occur between the informer being deemed synced and the worker completely starting. Due to this, the test could fail as add and update pod events might coalesce into a single event for the worker. This change proposes a fix that ensures the worker is fully initialized before updating the pod.
PR also related to this issue:  https://github.com/ovn-org/ovn-kubernetes/pull/3772
This PR also addresses replacing deprecated wait.PollImmediate with wait.PollUntilContextTimeout
When flake did not happen, you would see:
```
Informer Event Handler Tests
adds existing pod and processes an update event
/home/vagrant/dev/ovn-kubernetes.git/go-controller/pkg/informer/informer_test.go:209
I0102 22:04:39.868546  349898 informer.go:207] …
```
> flakey test: Informer Event Handler Tests adds existing pod and processes an update event

- go-controller/pkg/ovn/controller/services/lb_config.go
The service's node_switch LB was using the wrong address, breaking IPv6 ETP=Local services.
I guess this wasn't caught by CI because control-plane e2es aren't enabled on IPv6?
ETP=Local LB Service (using MetalLB only to assign the IP), setting static routes for the vips on an external client to a node hosting a pod:
curl to both the IPv4 and the IPv6 VIP works (without the fix IPv6 doesn't work)
Fix LGW ETP=Local on IPv6
> Fix LGW ETP=Local on IPv6

- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/ovn/egressqos_test.go
QOS rows are strongly referenced from switches so they should not be deleted without deleting also the references which we are already doing just a few lines below. Garbage collection takes care of removing the QOS rows.
> Don't delete QOS rows that might be referenced

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/util/kube.go
- go-controller/pkg/util/kube_test.go
The previous implementation was an approximation of KEP-1669 ProxyTerminatingEndpoints: we simply included terminating serving endpoints (ready=false, serving=true, terminating=true) along with ready ones in the endpoint selection logic. Let's fully implement KEP-1669 and only include terminating endpoints if none are ready. The selection follows two simple steps: 
1) Take all ready endpoints
2) If no ready endpoints were found, take all serving terminating endpoints.
This is done for all traffic policies (https://github.com/kubernetes/kubernetes/pull/108691).
This should also help with an issue found in a production cluster (https://issues.redhat.com/browse/OCPBUGS-24363) where, due to infrequent readiness probes, terminating endpoints were declared as non-serving (that is, their …
> OCPBUGS-24363: Full implementation of KEP-1669 ProxyTerminatingEndpoints

- dist/images/Dockerfile.fedora
- test/e2e/service.go
Add e2e test for session affinity after the chosen backend pod is deleted.
Inspired by (and a bit copied from) https://github.com/kubernetes/kubernetes/blob/83e6636096548f4b49a94ece6bc4a26fd67e4449/test/e2e/network/service.go#L2218-L2222
[DONE] Waiting for https://patchwork.ozlabs.org/project/ovn/list/?series=390173&state=* to be merged to make this test pass
> Ensure session affinity cleanup on backend removal

- go-controller/pkg/clustermanager/egressip_controller.go
- go-controller/pkg/clustermanager/egressip_controller_test.go
- go-controller/pkg/clustermanager/egressip_event_handler.go
EgressIP is not supported on hybrid-overlay nodes. 
Exclude hybrid-overlay nodes from EgressIP controller to avoid issues related to missing annotations.
/cc @martinkennelly
> Ignore hybrid-overlay nodes from EgressIP controller

- docs/multi-homing.md
This PR removes sentences from the docs stating the `layer2` and `localnet` topologies are not
supported when interconnect is used. 
This is no longer true.
Remove documentation indicating layer2/localnet topologies are not supported in interconnect mode
> docs, multi-homing: layer2/localnet topologies are supported in IC

- go-controller/pkg/ovn/base_network_controller_policy.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/multipolicy_test.go
- go-controller/pkg/ovn/policy_stale_test.go
- go-controller/pkg/ovn/policy_test.go
Namespace address sets don't have hostNetwork pod ips, while Network
Policies do add hostNetwork pods to their own address sets. An attempt
to unify this behaviour ended up breaking customers relying on the
previous logic, so we have to keep it.
The logic on when to use namespace address sets was restored. It is
applied when podSelector is nil. That means that peer
```
to:
- namespaceSelector: <ns selector>
```
won't include hostNetwork pods, while peer
```
to:
- namespaceSelector: <ns selector>
podSelector: {}
```
will.
the source of the previous behaviour is here https://github.com/openshift/ovn-kubernetes/blob/release-4.12/go-controller/pkg/ovn/policy.go#L1222-L1240, you can see that nil and empty podselectors are handled differently.
You can find 2 new unit tests verifying this …
> Update netpol namespace address sets usage to the old ways

- .github/workflows/commands.yml
- .github/workflows/docker.yml
- .github/workflows/test.yml
- .github/workflows/test_periodic.yml
Most of the GitHub actions that ovn-kubernetes is using are deprecated, since they are using outdated versions of Node.js: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Also, `set-output` feature is deprecated for a long time: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
These generate a lot of warnings on every build and may actually stop working eventually:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20:
actions/setup-go@v3, actions/checkout@v3, docker/login-action@v1.12.0, docker/metadata-action@v3.6.2,
docker/build-push-action@v2.9.0.
The `set-output` command is deprecated and will be …
```
> github: Update all the deprecated actions and features.

- .github/workflows/test.yml
- go-controller/pkg/kubevirt/router.go
- go-controller/pkg/ovn/kubevirt_test.go
- test/e2e/kubevirt.go
Kubevirt live migration between nodes that do not own the VM subnet are
creating wrongly at ECMP route since is not replacing the point to point
routes, this breaks traffic.
This change use just just IPPrefix and Policy at the point to
point routes predicate to prevent ECMP.
closes [#OCPBUGS-27215](https://issues.redhat.com/browse/OCPBUGS-27215)
This is tested at unit and e2e tests, for unit a new test is added that sets the virt-launcher at a third node that do not own the subnet and create a target virt-launcher at different one not owning the subnet either.
For e2e instead of doing two migrations, where we migrate back to the node owning the subnet, a extra migration is added to migrate between two nodes not …
> OCPBUGS-27215: Replace routes from kubevirt live migration to prevent ECMP

- go-controller/pkg/ovn/hybrid_test.go
The node ID 1 and in correspondence, the first ip of the join subnet, is reserved for the OVN cluster router. This HO unit test was trying to use that ID for a node and the test would flake depending on whether cluster manager was able to fix the situation before the test ran or not.
Fixes #4031
> Fix HO unit test flake

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/factory/handler.go
Otherwise, on node start failure, ovnkube controller may not be started yet, and ovnkubeControllerStartErr will be nil just because it is unassigned yet.
Besides not cleaning up, there is a possible deadlock on `masterWatchFactory.Shutdown()`. WatchFactory closes the channel https://github.com/ovn-org/ovn-kubernetes/blob/12681a716a4c98d8337c7815f15966cc5bba3502/go-controller/pkg/factory/factory.go#L663 and locks every informer before deletion. https://github.com/ovn-org/ovn-kubernetes/blob/12681a716a4c98d8337c7815f15966cc5bba3502/go-controller/pkg/factory/handler.go#L476 On handler add every informer is also locked https://github.com/ovn-org/ovn-kubernetes/blob/12681a716a4c98d8337c7815f15966cc5bba3502/go-controller/pkg/factory/factory.go#L861 If the informer is queued, it will use initial …
> Wait for ovnkube controller to start before checking result error.

- go-controller/pkg/clustermanager/egressservice/egressservice_cluster.go
- go-controller/pkg/controller/controller.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/node/controllers/egressservice/egressservice_node.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go
- go-controller/pkg/ovn/controller/egressservice/egressservice_zone.go
- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/sync.go
[edited]
- separate the handler sync from the informer sync 
-  remove the full service resync during the node tracker startup since it's redundant: all service keys are added at each node tracker add, but no service controller workers are consuming those keys yet; the services keys are added already in the service controller startup. This is discussed in: https://issues.redhat.com/browse/OCPBUGS-20336?focusedId=23916634&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23916634 and previous comments
> Separate timeout for handler sync from informer sync and do not resync services during node tracker startup

- .github/workflows/test.yml
There were some storage issues at github actions, looks like android-sdk is using 8gb, this change remove that to prevent those issues.
> actions: Remove android sdk

- go-controller/pkg/ovn/egressgw.go
We cannot always depend on there being an external IP family that matches the pod IP family.
For example, if we are converting from dualstack to single stack. In that scenario, a panic may occur because we depend on non-nil entries within the nat slices.
> Build Pod SNAT: remove risk of adding nil pointer and later panicking

- test/e2e/egress_services.go
- test/e2e/egressip.go
Two e2es shared the node IP 172.18.1.1 and assigned them to different nodes. This caused some e2es to timeout due to stale mac binding entry.
See the issue below for full details.
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/4127
> ESVC/EIP E2Es: stop sharing node IP address across multiple nodes

- .github/workflows/test.yml
- dist/images/Dockerfile.fedora
- test/e2e/external_gateways.go
- test/e2e/pod.go
- test/e2e/service.go
- test/e2e/util.go
This includes the following relevant changes:
- actions: Use random port selection for SNAT with external_port_range.
[https://github.com/ovn-org/ovn/commit/7ee483a45df1]
[https://issues.redhat.com/browse/FDP-301]
[https://issues.redhat.com/browse/RFE-4980]
- northd: Make sure that affinity flows match on VIP.
[https://github.com/ovn-org/ovn/commit/859e8d917408]
[https://issues.redhat.com/browse/FDP-290]
- ovn: Add tunnel PMTUD support.
[https://github.com/ovn-org/ovn/commit/6d2f9d60760a]
[https://bugzilla.redhat.com/show_bug.cgi?id=2241711]
- northd: Use proper field for lookup_nd
[https://github.com/ovn-org/ovn/commit/8e25c1c37aa3]
[https://issues.redhat.com/browse/FDP-283]
[https://issues.redhat.com/browse/OCPBUGS-27093]
- northd: Remove the protocol match from ECMP symmetric reply …
> fedora: Update OVN to latest version ovn-23.09.0-112.

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/ovs.go
There are some "unexpected \":\" parsing set of strings\n" errors in the ovnkube-node log, because ovs-vsctl takes two condition strings as a single string argument.
> ovnkube-node: eliminate `ovs-vsctl find Interface` failure log

- go-controller/pkg/ovn/base_event_handler.go
- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/hybrid_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/util/node_annotations.go
- test/e2e/egress_firewall.go
This commit changes efw.to.nodeSelector
to apply on all the nodeIPs present in the
host-cidrs annotation and not just primary
nodeIPs.
filed during https://github.com/openshift/enhancements/pull/1388#discussion_r1194068950
e2e's and ut's added
`ensure all nodeIPs are considered for nodeselector when using egress firewall`
> EFW: Add support for secondary nodeIPs

- go-controller/pkg/node/default_node_network_controller.go
That prevented it from closing up properly.
As a side note, oh how would I like if we didn't pass wait groups around.
@martinkennelly PTAL
cc @npinaeva 
> Fix unneeded wait group add on node network controller

- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
First 2 commits based on https://github.com/ovn-org/ovn-kubernetes/pull/4071
It Adds an e2e test that proves an ingress deny-all policy will have no impact on egress traffic
(see please link for more info)
In addition, add egress allow all / deny all tests.
> e2e, multi-net policies: ensure ingress denyall has no impact on egress, and add egress allow/deny all tests

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/net_linux_unit_test.go
- test/e2e/service.go
Currently, the host masq IP is selected as src IP when a workload residing in the host net ns attempts to connect to a svc IP.
But users may not config any routes that match a particular destination. This may happen if a user configures addresses on a link with noprefixroute or if the destination is not covered by any route.
For IPv6, there is an increased chance of the host masq IP being selected as src IP for destinations that do not fall within the svc CIDR if a user does not have appropriate routes configured to ensure the host masq IP is not selected and we have to use the following algorithm for V6 addrs: (rfc-3484)
1. Prefer same address.
2. Prefer appropriate scope.
3. Avoid deprecated addresses.
4. Prefer home addresses.
5. Prefer outgoing interface
6. Prefer matching label.
7. …
> Deprecate IPv6 host masq IP in-order to use it for svc only

- contrib/kind.sh
There is a bug [1] at kubevirt where source and target pods are not ready after successful live migration, this make endpoints slices move not ready and ovn-k do some ovs/ovn cleanup that breaks connections.
This change reduce the chance to have a not ready source pod by disabling one of the optional containers that is more eager to fail.
[1] https://issues.redhat.com/browse/CNV-38604
This improve the situation for https://github.com/ovn-org/ovn-kubernetes/issues/3986, but proper fix need to land at kubevirt.
Disable kubevirt guest-console-logs at "kind" installation
> kubevirt: Disable guest console log container

- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
Functionally this makes 0 difference, honestly I just want to start a unit test with 0 nodes without getting stuck on syncNodes with the error:
```
E0214 15:34:52.882353  704419 factory.go:876] Failed (will retry) while processing existing *v1.Node items: zoneICHandler failed to sync nodes: error: failed to find network ID: could not find network ID: %!w(<nil>)
```
Is that too much to ask :) => I guess with IC it is, because technically speaking you can't really have IC with 0 nodes.
In `syncNodes` we except to find networkID from the nodes and then use that to create transit switch.
Don't add too much logic to this, this is something needed only for testing purposes. Came while doing UTs for …
> Fix ensureTransitSwitch from failing if there are no nodes

- .github/workflows/test.yml
- test/e2e/acl_logging.go
- test/e2e/e2e.go
- test/e2e/egress_firewall.go
- test/e2e/egressip.go
- test/e2e/multicast.go
- test/e2e/service.go
- test/e2e/util.go
- test/scripts/e2e-cp.sh
This commit fixes things here and there
in e2e's to make control planes run on
v6 as well. Note that some tests are
skipped since they cannot be run on
github runners with v6 enabled.
NOTE: One of the multicast test is moved
from e2e.go to multicast.go where it belongs.
We must re-enable all the skipped tests: https://github.com/ovn-org/ovn-kubernetes/labels/ci-ipv6 
Supercedes https://github.com/ovn-org/ovn-kubernetes/pull/3512
- What this PR does and why is it needed
I was trying to review https://github.com/ovn-org/ovn-kubernetes/pull/3503 (that got merged already so too late) but then was thinking why this wasn't caught in CI and @trozet pointed out that we are indeed not running v6 in control plane? LOL. I …
> Run ipv6 lane in control plane jobs

- go-controller/pkg/node/node_ip_handler_linux.go
- go-controller/pkg/node/node_ip_handler_linux_test.go
#4040 introduced a constraint to filter VIPs. Remove that.
Also remove the external call to get these addresses. 
Previously, we needed to use an external pkg func call because we wanted to filter EIPs but that is no longer needed so get the IP addrs locally and filter the addresses locally, and dont do it in two places which is confusing.
> Node IP handler: Fix (include) keepalived VIPs

- go-controller/pkg/node/egress_service_test.go
Call AddFakeCmd before deleting the EgressService object to avoid a scenario in which the fakeExec detects the iptables commands as unexpected.
Found in a downstream UT run:
```
I0228 13:45:27.898828   22142 egressservice_node.go:635] Processing sync for EgressService namespace1/service1
I0228 13:45:27.899037   22142 ovs.go:164] Exec(86): /fake-bin/ip -4 rule add prio 5000 from 10.129.0.2 table mynetwork
I0228 13:45:27.899076   22142 ovs.go:167] Exec(86): stdout: ""
I0228 13:45:27.899107   22142 ovs.go:168] Exec(86): stderr: ""
I0228 13:45:27.899174   22142 ovs.go:164] Exec(87): /fake-bin/ip -4 rule add prio 5000 from 10.128.0.3 table mynetwork
I0228 13:45:27.899207   22142 ovs.go:167] Exec(87): stdout: ""
I0228 13:45:27.899232   22142 ovs.go:168] Exec(87): stderr: ""
I0228 …
```
> Fix EgressService test race

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-control-plane.yaml.j2
- docs/ovnkube.1
- go-controller/pkg/clustermanager/clustermanager_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
v4 and v6 transit switch subnets were made configurable via commit[1]. However some configurations were still missing to allow setting custom subnets while creating a kind cluster.
This PR is to allow configuring v4 and v6 transit switch subnet while creating a kind cluster.
This PR also adds/modifies couple of unit tests to take care of following scenarios:
- Wrong v4 & v6 transit switch subnets are not allowed.
- v4 and v6 transit switch subnets mentioned in config file takes precedence over default value.
- v4 and v6 transit switch subnet mentioned with cli options takes precedence over both default value & the value mentioned in config file.
- v4 and v6 transit switch subnet mentioned with cli options takes	precedence over default value.
[1] - …
> Allow configuring custom v4 and v6 transit switch subnets while creating kind cluster

- go-controller/pkg/ovn/egressqos.go
- go-controller/pkg/ovn/egressqos_test.go
This fixes pod update event to be ignored appropriately as it belongs to different zone, otherwise QoS rules are unnecessarily programmed in local zone's nbdb in which pod is not actually present.
> EgressQoS: Ignore remote pod update event

- test/e2e/egress_firewall.go
rules to be applied before running connectivity checks
[hopefully] fixes https://github.com/ovn-org/ovn-kubernetes/issues/3970
> Update egress firewall e2e tests to always wait for egress firewall

- README.md
Link to network-policy.md residing in the subdir ./doc/networkpolicies to fix current 404. 
(./doc/networkpolicies/admin-network-policy.md might still miss linkage from the current documentation)
Signed-off-by: Benjamin Redling <github@benjaminrampe.de>
> README: trivial fix to link NetworkPolicy

- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/iptables/iptables_manager.go
> EIP multi NIC: During Repair(), ignore IPv6 NAT table error

- test/e2e/kubevirt.go
- test/e2e/kubevirt/echoserver/main.go
Using the "Reuse" golang http client connection attribute to check that the connection is not broken is a little hard to debug, this change replace the http client and http agnhost server with a simple golang TCP server injected using fedora coreos ignition, its simpler and test is faster.
kubevirt, e2e: Use simple tcp server
> kubevirt, e2e: Use simple tcp server

- dist/images/ovnkube.sh
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/util/kube.go
Ovnkube allows the service conntrack zone to be configurable.
This PR exposes that flag via ovnkube.sh
This PR is needed to allow two instances of `ovnkube-node`  to run on the same node.
Setup a Kubernetes cluster with ovn-kubernetes and set `OVN_KUBERNETES_CONNTRACK_ZONE` in ovnkube-node yaml to a different value than `64000`
> ovnkube-node: Make service conntrack zone configurable

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
When no default gateway is found, OVNK will still come up. This behavior was intentional: 3eeb930791e04824b76b03172f64a1db21d9c377
The goal was that with design changes, host->service traffic would work without the need for a default gateway to be detected. This works, in most cases, but there is a case we did not consider. If a user has deployed a cluster with local gateway mode, and is using a different interface/network for kapi traffic (not the gateway bridge interface), then endpoints to the kubernetes service will reside on this other network. In this case when a host tries to talk to kube API service, the traffic would go to the GR, it would be DNAT'ed to an IP address not on any known network, and be dropped by OVN routing when there is no default gateway route.
When the …
> Use masquerade default gateway when no default gw is found

- go-controller/pkg/config/config.go
- go-controller/pkg/node/gateway_shared_intf.go
This is a followup to 8bb2db42326ef2fe918644263d555dc3f39743a0 which missed setting the conntrack zone values in gateway modes other than shared.
Considering that the default conntrack zone is now configurable this PR makes all of the other values as unexposed config fields that are set when the config is parsed. 
/cc @tssurya @naserdean
> Move custom conntrack zones to the config package

- go-controller/pkg/ovn/baseline_admin_network_policy_test.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy.go
- go-controller/pkg/ovn/controller/admin_network_policy/baseline_admin_network_policy.go
This commit creates updateExistingANP function
which can then be called from both ANP and BANP
ensure it functions similar to createNewANP.
Functionally no changes, internal cleanup which addresses review comment: https://github.com/ovn-org/ovn-kubernetes/pull/3659#discussion_r1289862089
We will be adding new peers in future PRs which will build on top of this
> Share common code between ANP/BANP

- docs/multi-homing.md
This PR corrects the multi-homing user documentation:
- removes a leftover claiming interconnect is not supported for layer2 / localnet topologies
- ensures the layer2 `subnets` parameter is rendered as a member of the attribute list
> Fix multihoming docs

- go-controller/pkg/util/kube.go
in the case that no Token && CertDir are "" (or empty CAData) we can still be ok if we have a TokenFile [0][1]
[0] https://github.com/ovn-org/ovn-kubernetes/blob/95c7a5eed5b6a3388b9d832dfdc9391d589b02b4/go-controller/vendor/k8s.io/client-go/rest/config.go#L74-L77
[1] https://github.com/ovn-org/ovn-kubernetes/blob/de6c98316ab8922b7940430239c3a849667b8064/go-controller/vendor/k8s.io/client-go/transport/round_trippers.go#L287
> TokenFile also has to be "" to fail new RestConfig

- contrib/kind.sh
- test/e2e/service.go
- test/e2e/util.go
- test/scripts/e2e-cp.sh
The PR doesn't fix the `Should ensure connectivity works on an external service when mtu changes in intermediate node` but it makes it retrieve the svc load balancer IP instead using the hardcoded value. 
Special thanks to @msherif1234 for the helping hand with metalb config!
> Fix and enable MetalLB service tests for LGW mode with IPv6 

- go-controller/pkg/node/controllers/egressip/egressip.go
- test/scripts/e2e-cp.sh
ovnkube-node fails here in ipv6 lgw clusters: https://github.com/ovn-org/ovn-kubernetes/blob/e5965ded4af0f0f6eb14cb7c2ada0713137ba4d5/go-controller/pkg/node/controllers/egressip/egressip.go#L287-L296
```
ovnkube.go:136] failed to run ovnkube: failed to start node network controller: failed to start default node network controller: failed to run egress IP controller: failed to create IP rule for node IPs: file exists 
```
This fails because in the current code the IP rule being added is always for ipv4.
Fix this by adding the rule with the appropriate family :family:
> Fix EgressIP initialization on IPv6 LGW clusters

- go-controller/pkg/ovn/admin_network_policy_test.go
- go-controller/pkg/ovn/controller/admin_network_policy/types.go
There was a typo when I did https://github.com/ovn-org/ovn-kubernetes/pull/4162 during the updates. 
s/portnumber/portrange
Added test to capture this
> ANP: Fix PortRange typo

- test/e2e/kubevirt.go
At kubevirt e2e tests the pods create at each nodes where not being added to the pods slice, this means that they were not created and the test for east/west communication was not run.
This change fill in again that slice so the test is run again.
> kubevirt, e2e: Fill in the http server pods slice

- go-controller/pkg/libovsdb/util/acl.go
- go-controller/pkg/ovn/admin_network_policy_test.go
- go-controller/pkg/ovn/baseline_admin_network_policy_test.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go
- go-controller/pkg/ovn/controller/admin_network_policy/types.go
- go-controller/pkg/ovn/controller/admin_network_policy/utils.go
- go-controller/pkg/ovn/controller/admin_network_policy/utils_test.go
- test/e2e/acl_logging.go
~HOLD, Need to add tests~ DONE! Open for reviews!
This PR adds support for ACL Logging for ANP&BANP features.
This adopts the existing ACL Logging framework used by NetworkPolicies
and EgressFirewalls. No surprises.
Only difference is that an anp annotation will look like:
```
Annotations:  k8s.ovn.org/acl-logging: { "deny": "alert", "allow": "alert", "pass": "warning" }
```
to include pass
while BANP will look like:
```
Annotations:  k8s.ovn.org/acl-logging: { "deny": "alert", "allow": "alert" }
```
Added unit tests and e2e's and found an OVN bug https://issues.redhat.com/browse/FDP-442 due to which some aspects of the e2e's are disabled ATM.
`Add …
> ANP: Support ACL logging

- test/scripts/e2e-cp.sh
The failure might have been caused by the EIP issue, from the logs in the failed job:
```
F0221 10:40:35.977662   11123 ovnkube.go:136] failed to start node network manager: failed to start default node network controller: failed to run egress IP controller: failed to create IP rule for node IPs: file exists
F0221 10:40:35.977662   11123 ovnkube.go:136] failed to start node network manager: failed to start default node network controller: failed to run egress IP controller: failed to create IP rule for node IPs: file exists
F0221 10:40:35.977662   11123 ovnkube.go:136] failed to start node network manager: failed to start default node network controller: failed to run egress IP controller: failed to create IP rule for node IPs: file exists
F0221 10:40:35.977662   11123 ovnkube.go:136] …
```
> Enable status manager tests in lgw v6

- test/e2e/acl_logging.go
- test/e2e/util.go
There are two parts to the flake, this is only fixing one part, I am still trying to figure out why the pod2pod communication though logged in ovn-controller as "allowed" doesn't end up working in v6 env in CI. I have also added some extra debug logs to see what happens when it fails
See https://github.com/ovn-org/ovn-kubernetes/issues/4242
> Fix-flake: ACLlogging ANP/BANP test

- go-controller/go.mod
- go-controller/go.sum
- go-controller/vendor/github.com/safchain/ethtool/.yamllint
- go-controller/vendor/github.com/safchain/ethtool/ethtool.go
- go-controller/vendor/github.com/safchain/ethtool/ethtool_cmd.go
- go-controller/vendor/modules.txt
Update the version to include big-endianness fix to safchain/ethtools (https://github.com/safchain/ethtool/pull/69).
Steps done for this commit:
* replace: `github.com/safchain/ethtool v0.3.0` with `github.com/safchain/ethtool v0.3.1-0.20231027162144-83e5e0097c91` in go.mod, vendor/modules.txt
* `go mod tidy`
* `go mod vendor`
This is needed to allow changing interface options on s390x architecture.
> vendor: bump safchain/ethtool to v0.3.1-0.20231027162144-83e5e0097c91

- go-controller/pkg/ovn/admin_network_policy_test.go
- go-controller/pkg/ovn/baseline_admin_network_policy_test.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_namespace.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_node.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_pod.go
- go-controller/pkg/ovn/controller/admin_network_policy/baseline_admin_network_policy.go
- go-controller/pkg/ovn/controller/admin_network_policy/repair.go
- go-controller/pkg/ovn/controller/admin_network_policy/status.go
- go-controller/pkg/ovn/controller/admin_network_policy/status_test.go
- go-controller/pkg/ovn/controller/admin_network_policy/types.go
- go-controller/pkg/ovn/ovn.go
This PR adds support for `node` Egress peer in ANP and BANP.
API changes added as part of: https://github.com/kubernetes-sigs/network-policy-api/commit/23d3882d5c8bc280c2f1c7b590c11e1d3509a6b0
unit tests and e2e's have been added (e2e's will run and merge as part of https://github.com/ovn-org/ovn-kubernetes/pull/4235)
`allow support for selecting nodes as egress peers`
> ANP: Add Support for Nodes as Egress Peers

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- MAINTAINERS.md
- MEETINGS.md
- OWNERS
- REVIEWING.md
- SECURITY.md
- community-meeting-info.md
Strictly follows the guidelines mentioned in https://contribute.cncf.io/maintainers/templates/ and all templates are copied from there.
Must get approval from all maintainers: @girishmg @trozet @jcaamano @dcbw 
`SECURITY.md` file is not complete ATM, will get back to this round2.
N/A
N/A
> Add Project Governance for ovn-kubernetes project

- docs/metrics.md
- go-controller/pkg/metrics/ovnkube_controller.go
- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy.go
- go-controller/pkg/ovn/controller/admin_network_policy/baseline_admin_network_policy.go
This commits adds two metrics to:
1. count number of admin network policies and (between 0 and 100)
2. number of baseline admin network policies in a cluster (0 or 1)
My goal with these two metrics are:
1. understand how the user is using this feature
2. how many admin network policies have they created (I plan to do future PRs for more fine-grained information)
3. is the user using baseline admin network policy in their cluster?
So its also for the user but more so for us.
I am starting out with the metrics stuff for ANP/BANP
PTAL @martinkennelly at this one for starters. I think this is simple enough to not need the monitoring team's purview but future PRs will need their help. WDYT?
> (B)ANP: Add num_anp && num_banp metrics

- test/e2e/diagnostics/conntrack.go
- test/e2e/diagnostics/context.go
- test/e2e/diagnostics/daemonset.go
- test/e2e/diagnostics/diagnostics.go
- test/e2e/diagnostics/doc.go
- test/e2e/diagnostics/iptables.go
- test/e2e/diagnostics/ovsflows.go
- test/e2e/diagnostics/tcpdump.go
- test/e2e/e2e_suite_test.go
- test/e2e/kubevirt.go
This change add some daemonset to gather the following info from nodes
- conntrack
- tcpdump
- iptables
- ovsflows
> kubevirt, e2e: Add diagnostics tools

- test/e2e/e2e.go
- test/scripts/e2e-cp.sh
To fix https://github.com/ovn-org/ovn-kubernetes/issues/4180.
/cc @tssurya
> Enable EgressQoS tests for IPv6 and LGW mode

- test/e2e/node_ip_mac_migration.go
Adds a restart to kubelet to make sure the host networked "backend" pod IP is updated to the new IP so that the proper flows are programmed.
Fixes #4073
> Fixes flaking node ip migration ETP local check

- test/e2e/pod.go
- test/e2e/util.go
The test previously used a host network pod to act as the external server and test ingress PMTUD with OVN. This changes it to be an external server as a docker container, which sets us up for the future where  pod -> host goes via overlay and wouldn't test PMTUD in the same way.
> Changes PMTUD tests to use an external docker container

- test/scripts/e2e-kind.sh
- test/scripts/install-kind.sh
Attempting to fix issue found in e2e tests in PR: https://github.com/ovn-org/ovn-kubernetes/pull/4253
Following tests were failing but should now be resolved:
](https://github.com/ovn-org/ovn-kubernetes/actions/runs/8551587549/job/23431934438?pr=4253)
More details in https://github.com/ovn-org/ovn-kubernetes/pull/4253 regarding the first commit.
> Remove extra || in SKIP formatting && bump k8 test binary to fix e2e issues found

- dist/templates/ovnkube-alerts.yaml.j2
- docs/metrics.md
- go-controller/pkg/metrics/ovnkube_controller.go
- go-controller/pkg/util/ovs.go
we have moved away from invoking the CLI to leveraging libovsdb go-module for OVN DB operations, so this metric and its associated alerts are of no use.
@trozet @cathy-zhou @tssurya PTAL
> remove ovn-{nb|sb}ctl CLI latency metrics and alerts

- go-controller/pkg/metrics/ovn_db.go
- go-controller/pkg/metrics/ovs.go
ovnkube-node pod could be running different container image from OVN DB pod, so we will need to use:
`ovs-appctl -t /path/to/ovnnb_db.ctl version`
Authored-By: Zhen Wang <zhewang@nvidia.com>
> incorrect OVN DB version is being scrapped

- test/e2e/service.go
- test/scripts/e2e-cp.sh
This PR fixes some of the ipv6 e2e tests and unskips them from CI 
"Services when a nodePort service targeting a pod with hostNetwork:true is created when tests are run towards the agnhost echo service [It] queries to the nodePort service shall work for UDP on IPV6 Shared gateway"
"Services when a nodePort service targeting a pod with hostNetwork:true is created when tests are run towards the agnhost echo service [It] queries to the nodePort service shall work for UDP on IPV6 Shared gateway"
and the ginkgo step "Services of type NodePort: should listen on each host addresses"
"e2e ingress to host-networked pods traffic validation: Should be allowed to node local host-networked endpoints by nodeport services" in local gateway mode 
the testing …
> Restore some skipped IPv6 testing

- dist/images/Dockerfile.ubuntu
This change stops using the Xenial repo, as it is no longer available.
The failure would look like this:
```
$ cd $(git rev-parse --show-toplevel)/dist/images && make ubuntu
docker build -t ovn-kube-u-amd64 -f Dockerfile.ubuntu . DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
Install the buildx component to build images with BuildKit:
https://docs.docker.com/go/buildx/
Sending build context to Docker daemon    428MB
Step 1/23 : FROM ubuntu:23.10
---> 0adee8f4dd22
Step 2/23 : USER root
---> Using cache
---> a517bccf401f
Step 3/23 : RUN apt-get update && apt-get install -y iproute2 curl software-properties-common util-linux
---> Using cache
---> 6994116cf2ef
Step 4/23 : RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a …
```
> Dockerfile.ubuntu : fix build issue

- dist/images/Dockerfile.fedora
- test/e2e/service.go
Supersedes https://github.com/ovn-org/ovn-kubernetes/pull/4199
OVN bump - see https://github.com/ovn-org/ovn/tree/v23.09.3 for list of changes.
E2E test to validate fix for downstream issue: https://issues.redhat.com/browse/OCPBUGS-25889
This issue is seen in some deployments where if a pod container uses a source port that is equal to a node port, then packets are dropped.
Tested against main (passed) and downstream OpenShift 4.12 (failed) where the issue resides.
> OVN bump to 23.09.0-139

- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/ovs_unit_test.go
control file is used to communicate with the running daemon to modify its properties, whereas sock file is AF_UNIX transport to run OVSDB protocol over
@trozet should be an easy one
> control file is not same as sock file

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/ovn/controller/services/lb_config.go
- go-controller/pkg/ovn/controller/services/lb_config_test.go
- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/controller/services/services_controller.go
- go-controller/pkg/ovn/controller/services/services_controller_test.go
- go-controller/pkg/testing/kube.go
- go-controller/pkg/util/kube.go
- go-controller/pkg/util/kube_test.go
In https://github.com/ovn-org/ovn-kubernetes/pull/4072 the following edge case was not handled correctly in ovnkube-controller code. 
Fix the case for `all endpoints terminating on a node when traffic policy is local`:
> "When the traffic policy is "Local" and all endpoints are terminating within a single node, then traffic should be routed to any terminating endpoint that is ready on that node."
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/1669-proxy-terminating-endpoints/README.md#example-all-endpoints-terminating-on-a-node-when-traffic-policy-is-local
The endpoint selection logic in the services controller is now entirely implemented in `getEndpointsForService`, which computes for a given service and each service port all its cluster-wide endpoints and …
> Fix endpoint selection for externalTrafficPolicy=local

- go-controller/go.mod
- go-controller/go.sum
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/iptables/iptables.go
- go-controller/pkg/util/iptables.go
- go-controller/vendor/github.com/coreos/go-iptables/iptables/iptables.go
- go-controller/vendor/modules.txt
When ovnk node gateway starts up, it will attempt to:
- flush iptables chains
- recreate all chains
- add iptables rules back for all services
We were inefficiently:
- Always trying to recreate the chain on every rule insertion
- Recreating all rules over and over again as we iterate over different chains.
This would result in the same iptables rule attempting to be inserted 7 times:
trozet@fedora:~$ kubectl logs -n ovn-kubernetes ovnkube-node-ckkxd -c ovnkube-controller | grep "Adding rule" | grep 1.1.4.100
I0326 13:37:17.637007    8984 iptables.go:27] Adding rule in table: nat, chain: OVN-KUBE-EXTERNALIP with args: "-p TCP -d 1.1.4.100 --dport 80 -j DNAT --to-destination 10.96.204.38:80" for protocol: 0
I0326 13:37:22.597245    8984 iptables.go:27] Adding rule in table: nat, chain: …
> Improves service iptables efficiency on start up

- docs/metrics.md
- go-controller/pkg/libovsdb/util/metric.go
- go-controller/pkg/metrics/ovnkube_controller.go
- go-controller/pkg/ovn/default_network_controller.go
See https://github.com/ovn-org/ovn-kubernetes/pull/4248 and https://docs.google.com/document/d/1LQ1IENCehjtiYTvBL8uORXU8GZwFbpNXMnAhVNfqnIM/edit for more information
We are adding two metrics:
1. ANP(Table_Name) DB Object counter metric
2. BANP(Table_Name) DB Object counter metric
3. We can easily do EFW if we decide this approach is ok. (NetPol needs a sum of many type of ACL IDs so not exploring that in this PR)
4. A poller routine that runs every 30seconds scrapes for the nbdb object counts owned by each configured feature
The ACL/AS count for ANP/BANP is pretty useful for users, scale, devs to assess how this feature is being used.
We plan to expose this via telemetry.
**- Description …
> Add (B)ANP ACL/AddressSet count metrics

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/default_node_network_controller_test.go
- test/scripts/e2e-cp.sh
When we do not set external_ids:ovn-set-local-ip="true" on OVS we doe not set local_ip parameter when creating tunnel ports and ipv6 does not work with multiple addresses on the same interface 
> set external_ids:ovn-set-local-ip="true" on nodes 

- .github/workflows/test.yml
- test/e2e/diagnostics/daemonset.go
- test/e2e/diagnostics/tcpdump.go
- Fix e2e diagnostics tcpdump daemonset name to avoid invalid character `_`.
- Define OVN_IMAGE for e2e job task. Change pull policy as there is no
image repository backing the test cluster.
> e2e diagnostic fixes

- dist/templates/ovnkube-alerts.yaml.j2
- docs/metrics.md
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/node.go
- go-controller/pkg/metrics/ovnkube_controller.go
- go-controller/pkg/network-controller-manager/network_controller_manager.go
We have found several instances where the size of the log file increased very rapidly and consumed good amount of disk space. With the addition of this metric and alert, it will provide deployers with an ability to know if an ovnkube-node or ovnkube-controller daemon is misbehaving.
> Introduce metrics and alerts to track the logfile size

- go-controller/pkg/metrics/metrics.go
- go-controller/pkg/metrics/ovs.go
we already retrieve ovs-vswitchd metrics from coverage/show output via coverageShowMetricsUpdater(), so just leverage the same mechanism to pull the following upcall related metrics
-- upcall_flow_limit_kill
-- upcall_flow_limit_hit
@npinaeva FYI
> move retrieving upcall related metrics to coverage/show command

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-control-plane.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/pod/allocator.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/factory_test.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
- helm/ovn-kubernetes/values.yaml
Only start the IPAMClaim factory watchers if the persistent IPs feature gate is enabled.
Currently, anytime multi-network is enabled in IC scenarios we assume the IPAMClaims CRD is installed. This might not be always the case - let's add a feature gate then.
> virt, persistent ips: make the feature configurable

- REVIEWING.md
- contrib/CODEOWNERS
Turns out we need CODEOWNERS to assign to the general team first, then auto assign will pick someone.
> Add back CODEOWNERS

- go-controller/pkg/ovn/egressqos.go
Force: true was not set on EQoS status updates in ovnkube-controller
causes conflicts when trying to patch
`Use force:true when doing server side apply`
> EQoS: Set force:true for server-side-apply

- test/scripts/e2e-kind.sh
UPDATE:
Original fix here went into https://github.com/ovn-org/ovn-kubernetes/pull/4256
I am converting this PR to fix: https://github.com/ovn-org/ovn-kubernetes/pull/4253#discussion_r1551952094
OUTDATED INFO ON OLD PR:
I think we should definitely spend some time fixing https://github.com/ovn-org/ovn-kubernetes/issues/4229
cc @jluhrsen this might be why you saw some lanes not running tests and finishing in 5mins?
Accidental addition of `|` pipe during skipping makes it `||` which matches empty string which skips all tests :/
Not on all lanes I think shard, local, v6 ones only:
- ovn-ci / e2e (shard-conformance, HA, local, ipv6, snatGW, 1br, ic-disabled) (pull_request)
- ovn-ci / e2e (shard-conformance, noHA, local, dualstack, snatGW, 1br, …
> Unskip ETP=local+terminating endpoints

- test/e2e/multihoming.go
Add multi network policy ingress allow all and deny all e2e tests.
Add a test that shows a bug: egress deny-all affects ingress
(reverse case of #4156), and a test that shows the workaround for it:
add ingress wildcard.
> e2e, multi-net policies: Add ingress allow all and deny all tests

- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/nicstobridge.go
This change is aimed at making the ANY network check backward compatible with the old netlink library and simplifying the process by utilizing the library function IP.IsUnspecified().
This is a follow up change for https://github.com/ovn-org/ovn-kubernetes/commit/14f5f1841114740307511e586e18079b5368fe47
> Follow up fix how detect any network following lib change

- crd-docs-config.yaml
- docs/developer-guide/admin-epbr-api-spec.md
- docs/developer-guide/egress-firewall-api-spec.md
- docs/developer-guide/egress-ip-api-spec.md
- docs/developer-guide/egress-qos-api-spec.md
- docs/developer-guide/egress-service-api-spec.md
- mkdocs.yml
the API reference documentation was generated by using this project
https://github.com/elastic/crd-ref-docs/. The config that was used to
generate the API is
$ go install github.com/elastic/crd-ref-docs@latest
$ ~/gowork/bin/crd-ref-docs \
--source-path=~/gowork/src/githubcom/ovn-org/ovn-kubernetes/\
go-controller/pkg/crd/egressfirewall/ \
--config=crd-docs-config.yaml --renderer=markdown \
--output-path=./docs/developer-guide/egress-firewall-api-spec.md
Please check my github landing page:
https://girishmg.github.io/ovn-kubernetes/developer-guide/egress-firewall-api-spec/
https://girishmg.github.io/ovn-kubernetes/developer-guide/egress-qos-api-spec/
https://girishmg.github.io/ovn-kubernetes/developer-guide/egress-service-api-spec/ …
> Generate API reference documentation for all of our CRDs

- go-controller/pkg/ovn/master.go
- go-controller/pkg/types/errors.go
errors.As() is not supported[1] with Aggregate type error. This PR is to unfurl Aggregate type error into a slice of builtin error by using Aggregate.Errors() function. errors.As() can then be used with each element of the slice.
This PR also wraps 'annotation not found' errors for remote zone nodes with SuppressedError type to suppress expected logs for remote zone nodes going forward.
Upstream Issue: https://github.com/ovn-org/ovn-kubernetes/issues/4332
[1] - https://pkg.go.dev/k8s.io/apimachinery/pkg/util/errors#Aggregate
closes #4332 
> Add logic to unfurl Aggregate type error in IsSuppressedError function

- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/gateway_init.go
- go-controller/pkg/ovn/gateway_test.go
A node update may overwrite the GARP options from the external switch router port.
Handle these options directly from the gateway reconciliation logic and avoid writing to the same DB row from two concurrent threads which might also be racey.
As a curiosity, on my local environment where I reproduced this, ~~I had sysctl rp_filter=2. With that in place, and~~ with no GARP, the external server was sending replies to the old egress node and the old egress node was able to forward them to the new egress node, so no connectivity hiccup but a permanent undesired path. On an OCP environment however, ~~with rp_filter=1,~~ the old egress node can't forward to the new egress node. The connectivity hiccup is there, and without GARP it takes longer for the external server to become aware of the mac …
> Fix EIP GARP config overwritten by gateway update

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
Node delete is failing and retrying until retry limit when it can never succeed when particular annotations arent added in time before the node is deleted.
~/hold~
~Need to add unit test.~
All thanks to @trozet  for his KinD scaler PR to reproduce #4331 !
> Node delete should not fail when it can never succeed when `node-subnet` annot isnt assigned

- dist/templates/k8s.ovn.org_adminpolicybasedexternalroutes.yaml.j2
- dist/templates/k8s.ovn.org_egressfirewalls.yaml.j2
- dist/templates/k8s.ovn.org_egressips.yaml.j2
- dist/templates/k8s.ovn.org_egressqoses.yaml.j2
- dist/templates/k8s.ovn.org_egressservices.yaml.j2
- go-controller/hack/update-codegen.sh
for predictable output folder that doesn't depend on GOPATH.
Clean up generated folder after copying apis.
Specify code-generator version, as release-1.30 changes scripts parameters.
> Update codegen to explicitly set output-base 

- contrib/kind.sh
New argument "--add-nodes" allows a user to scale up the number of worker
nodes in their current cluster to the desired amount. The current -wk,
--num-workers argument is used to determine how many workers to add.
Additionally it is important to indicate if the cluster is interconnect
or not. Example usage:
./kind.sh --scale -wk 1 -ic
Props to @lobuhi for coming up with the KIND scaling script!
> Enables scaling worker nodes in KIND cluster

- test/e2e/e2e_suite_test.go
- test/scripts/conformance.sh
- test/scripts/e2e-cp.sh
- test/scripts/upgrade-ovn.sh
This PR replaces remaining usage of deprecated ginkgo v2.4.0 APIs in the e2e test modules.
> Remove ginkgo deprecated APIs from e2e test

- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy_controller.go
- go-controller/pkg/ovn/controller/admin_network_policy/metrics.go
This PR is adding rule count metrics for ANP/BANP
Goal is to be able to count number of rules across all ANP CRDs and BANP CRDs in the cluster.
The approach taken here is to add 2 metrics one for ANP and another for BANP.
Each metric has two labels (direction of the rule with max 2 cardinality and action of the rule with max 3 cardinality)
Each metric is tailored to gather data from a single ANP/BANP, hope is on prometheus we can query the total across all ANP/BANP?
=============================OUTDATED INFO BELOW TO BE IGNORED============================
EDIT: I met with @martinkennelly and @npinaeva and we have a path forward here:
1. Do feature wise generic DB counter metric which is extensible; this will be FeatureObjectsMetric …
> Add Rule count metrics for (B)ANP feature

- .github/workflows/test.yml
- contrib/kind-common
- contrib/kind-helm.sh
- contrib/kind.sh
- helm/ovn-kubernetes/values.yaml
- test/scripts/e2e-cp.sh
- Move common functions into a single file that both kind.sh and kind-helm.sh can use
- Install metal-lb in when deploying via kind-helm, so e2e egress tests are exercised
Partially fixes https://github.com/ovn-org/ovn-kubernetes/issues/4257 
Will address ovn-ic deployment under helm in a separate PR.
> Move parts of kind.sh into kind-common

- go-controller/pkg/ovn/controller/services/lb_config.go
- go-controller/pkg/ovn/controller/services/node_tracker.go
- go-controller/pkg/ovn/gateway_init.go
node's nodePort is disabled
Also, if a node's nodePort is disabled, all the nodePort services' load balancers should not be added to the node's gateway router. If service template is enabled, the loadBalancerGroup that contains all the nodePort services' loadBalancers should not be added to the node's gateway router either.
> host-networked pod backed cluster service not accesible on same node if

- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/node/node_allocator.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/node/secondary_node_network_controller.go
- go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
Cleanup method doesn't need netName, as it should be already known to the NetworkController.
Was promised as a part of https://github.com/ovn-org/ovn-kubernetes/pull/3579 review
> Refactor NetworkController.Cleanup

- README.md
Looks like the meetings.md link in the readme is broken
> Fix meetings relative link in readme

- dist/images/Dockerfile.ubuntu
This change updates the OVN DB schema to be compatible with Object type nbdb.LogicalRouterPolicy field BFDSessions.
```
Database OVN_Northbound validation error (2): Mapper Error. Object type nbdb.DNS contains field Options (map[string]string). OVS tag options: Column does not exist in schema. Mapper Error. Object type nbdb.LogicalRouterPolicy contains field BFDSessions ([]string). OVS tag bfd_sessions: Column does not exist in schema.
```
> Dockerfile.ubuntu: Use ubuntu:24.04

- go-controller/Makefile
This is not used in CI but we need it for running the tests locally.
> Bump the go version for the container running the unit tests

- .github/workflows/test.yml
- contrib/kind-common
- contrib/kind.sh
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/kubevirt.go
- test/e2e/multihoming_utils.go
kubevirt, e2e: Add persistent ips tests
To verify the ovn-kubernetes integration with IPAMClaim this change
add kubevirt VirtualMachines live migration and restart with
multi-homing and persistent ips tests.
> Kubevirt e2e ipamclaim

- test/e2e/gateway_mtu.go
- test/e2e/util.go
This e2e test verifies whether 'k8s.ovn.org/gateway-mtu-support' annotation is being added to all nodes and being set to 'false' when `disable-pkt-mtu-check` is set to 'true'. This annotation should be absent from node objects when either `disable-pkt-mtu-check` is unset or set to 'false'.
closes #3928 
Run control-plane CI test in local kind environment. Make sure to set `OVN_DISABLE_PKT_MTU_CHECK` environment variable to either 'true'  or 'false' while running this test.  
- Added gateway_mtu.go containg main test cases
- Added couple of functions in util.go
> Add e2e test for DisablePacketMTUCheck

- go-controller/pkg/factory/factory.go
We were not waiting on for informers to fully shutdown for level-driven controllers. As a consequence, goroutines would still be running handling events while the next unit test case ran. In this case, a handler with no workqueue (like node_tracker) would attempt to read global config, while the next test case was modifying the global config, leading to a data race.
Fixes: #4381
Thanks to @npinaeva for helping me debug this one!
> Fixes waiting for level-driven informers to stop

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/ovn/kubevirt_test.go
After merging https://github.com/ovn-org/ovn-kubernetes/commit/469c4e8202166b9b334c8785fc14e0f3193597e7 the live migration leftovers were not removed since all the VM's pods are at completed state so the cleanup was skip.
This change simplify that logic by removing left overs if all the VM's pods are completed.
```release-note
kubevirt: Propertly remove migration leftovers
```
> kubevirt: Propertly remove migration leftovers

- .github/workflows/stale-action.yml
For maintainers it is hard to keep the repo clean manually.
There are 270+ issues on this project and its not possible
for any human to go through them and clean them
This list will only keep growing if we don't have a
system in place to close stale issues.
Fixes #
PR uses https://github.com/marketplace/actions/close-stale-issues#usage so more details
and further fine tuning can be found there.
NO IDEA :)
But its a cron job that runs every 1.5 hours so we'll know soon? :D
Yea I will perhaps add a section later on to the docs.
`Add cronjob to cleanup stale issues and PRs but we NEVER CLOSE PRs`
```release-note
NONE
```
> Add github actions for stale issues

- test/e2e/external_gateways.go
This modifies the sender address for ingress ping test to use a common
IP address that is emulated on a loopback acting as though it lives
behind the gateways. This ensures that packets sent from either gateway
will have the same hash. The point of this is to exercise test coverage
that auto last hop is working correctly. If it is not working, then the
ping reply will only go back to one of the gateways instead of both.
Also, vendor the test directory like I think we agreed on a while ago and never did it.
> Fix ICMP MEG Ingress e2es

- .github/ISSUE_TEMPLATE/e2e-testing.yaml
- .github/ISSUE_TEMPLATE/unit-testing.yaml
I am sorting labels based on types "Area", "Kind", "Feature", "Lifecycle" etc. This is part of that.
Would be nice to get these in so that new issues don't start getting opened against the wrong labels.
> Change area labels on issues

- docs/getting-started/configuration.md
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- mkdocs.yml
This PR is to remove any iptables rules which were created based on config.Gateway.DisableForwarding set to true and later it was changed to false.
This PR also ensures forwarding sysctl parameters are set for all IPv4 and IPv6 interfaces by either enabling or disabling it based on config.Gateway.DisableForwarding
> Implementation required to enable Forwarding if it is already disabled

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cni_dpu_test.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_linux_test.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/util/mocks/NetLinkOps.go
- go-controller/pkg/util/mocks/SriovnetOps.go
- go-controller/pkg/util/net_linux.go
- go-controller/pkg/util/sriovnet_linux.go
This commit introduces VFIO (Virtual Function I/O) support for Virtual Functions (VFs) on systems with SR-IOV capabilities. KubeVirt virtual machines can now use VFs that are bound to the vfio_pci driver as pass-through PCIe devices.
This PR add support for VFIO support  which can use
be used by kubevirt VM which support VFIO pass though
Fixes #
Use kubevirt VM with secondary NAD with VFIO as resources.
Tested in my 3 nodes cluster,  one kvm node for control plane
two BM nodes with CX6 with switchdev offloading enabled.
```release-note
```
> CNI: Add VFIO support for SR-IOV enabled systems

- contrib/ingress/mandatory.yaml
Before this change, the image used was quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0, which has not been updated for ~4 years:
[https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller?tab=tags](https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller?tab=tags)
Stop using v1beta1.Ingress to avoid the following issue when starting the ingress controller:
```
I0605 20:53:28.807814      13 nginx.go:263] Starting NGINX Ingress controller
I0605 20:53:28.810783      13 event.go:281] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-nginx", Name:"nginx-configuration", UID:"90cd2ad0-5769-47a1-a4a5-90b84e9ba609", APIVersion:"v1", ResourceVersion:"649", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap …
```
> ingress: update image to registry.k8s.io/ingress-nginx/controller:v1.10.1

- go-controller/pkg/ovn/egressip_test.go
in an effort to remove the FakeAddressSet code from testing this commit removes FakeAddressSet from EgressIPTesting
> Remove FakeAddressSet from EgressIP testing

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_linux_test.go
- go-controller/pkg/cni/ovs.go
- go-controller/pkg/node/base_node_network_controller_dpu_test.go
- go-controller/pkg/node/management-port-dpu.go
- go-controller/pkg/node/management-port_dpu_test.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/mocks/SriovnetOps.go
- go-controller/pkg/util/ovs.go
- go-controller/pkg/util/sriovnet_linux.go
Offer the possibility to use ovs-doca based userland datapath in OVS with OVN-kubernetes.
ovs-doca uses DOCA Flow library which enables use of the embedded eswitch and other hardware based offload mechanisms in capable hardware.
The ovn bridge will be created with the 'netdev' datapath type. ovnkube will query the datapath type of this bridge and modify OVS requests as necessary. In particular, CNI requests resulting in ovs configuration will add ports of type dpdk if on a 'netdev' bridge. Same with management port as well.
For using ovs-doca with ovn-kubernetes, in addition to initializing ovs-doca correctly, the following ovs configuration needs to be set
`ovs-vsctl set open . external-ids:ovn-bridge-datapath-type=netdev`
Documentation PR: #4408 
PR #4408 
```release-note
Allows using …
```
> Support OVS-DOCA

- go-controller/pkg/ovn/base_network_controller.go
Fix race condition:
1. deleteNamespaceLocked, after the 20s delay, checks that the current nsInfo for the namespace is nil
2. ensureNamespaceLockedCommon adds a new nsInfo referencing the existing address set
3. deleteNamespaceLocked destroys the existing address set
Fixes: https://issues.redhat.com/browse/OCPBUGS-33005
> Fix race condition when creating/deleting namespace address set

- go-controller/pkg/ovn/controller/admin_network_policy/admin_network_policy.go
In the event we had "This ANP mc-ta-2 has a conflicting priority with ANP mc-ta-1: %!s(MISSING);Please verify your rules are non-lapping between all policies at same priority to avoid undefined behavior"
an extra %s :/
> nit-fix: log statement had extra %s

- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-control-plane.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- docs/getting-started/configuration.md
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
This will be leveraged in future commits
UTs are added
New config flag docs done!
`Add feature gate for user-defined-networks-feature`
```release-note
Allows users to enable user-defined-networks via feature gate
```
> User Defined Network Segmentation Feature Gate

- test/e2e/egressip.go
The previous mask was invalid and docker was failing with: invalid subnet `2001:db8:abcd:1234:c000::/64`: it should be `2001:db8:abcd:1234::/64`
/cc @tssurya
> e2e: Fix secondaryIPV6Subnet mask

- .github/workflows/test.yml
- docs/ci/ci.md
this is to help track down and find the most common flakes we need to fix. It removes the condition on the e2e job to not run on a schedule so the cron will pick it up (twice daily). the e2e job should still run pull_requests for [ master ] branch.
this also adds the "workflow_dispatch" trigger so we can manually trigger the workflow from the github UI.
> SDN-4909: rm e2e-periodic and run e2e in full twice daily

- .github/workflows/test.yml
- contrib/kind-helm.sh
- contrib/kind.sh
- dist/images/Dockerfile.ubuntu
- dist/images/Makefile
- dist/images/push_manifest.sh
- docs/developer-guide/image-build.md
- docs/developer-guide/release.md
- docs/installation/INSTALL.KUBEADM.md
- docs/installation/launching-ovn-kubernetes-with-helm.md
- helm/basic-deploy.sh
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/README.md.gotmpl
- helm/ovn-kubernetes/values.yaml
- test/e2e/diagnostics/daemonset.go
- test/scripts/test-ovnkube-trace.sh
- test/scripts/upgrade-ovn.sh
In commit
https://github.com/ovn-org/ovn-kubernetes/commit/fabb87bbc7f5a2036c55736b2dc025b0c60053c9, we renamed the packages, but missed a few important scripts and documentation.
Fixes: #4451
> Add missing places when renaming ovn-kubernetes packages

- dist/templates/ovnkube-db.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- go-controller/pkg/metrics/ovn_northd.go
- helm/ovn-kubernetes/charts/ovnkube-db-raft/templates/statefulset.yaml
- helm/ovn-kubernetes/charts/ovnkube-db/templates/deployment.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
With IC, we are not registering northd metrics since there is no ovnkube-master pod. To fix, use `ovn-db-pod=true` label instead since in all our deployment models northd has been collocated with the DBs.
> Fix registering northd metrics on appropriate nodes

- dist/images/Dockerfile.fedora
- test/e2e/kubevirt.go
- test/e2e/multicast.go
Bumps OVN to 24.03.2-19, which reverts multicast-related commits that introduced a regression.
Extends the unit test to cover the scenario that was broken: add an additional receiver to the same node where the sender is.
https://issues.redhat.com/browse/OCPBUGS-34778
https://issues.redhat.com/browse/FDP-656
> Bump OVN to ovn-24.03.2-19 to fix multicast bug

- go-controller/pkg/factory/factory.go
- go-controller/pkg/ovn/base_event_handler.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressfirewall.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/ovn.go
Beginning of the story is in https://github.com/ovn-org/ovn-kubernetes/pull/4386
Switch to level-driven controller to avoid
dependency between node handler and ef node handler.
If EF handler is ever deadlocked (and it can be as node handler iterates
all egress firewalls, which in turn, depend on dns resolvers), node
handler should not be affected.
See a new test for more idea.
> Make egress firewall node controller level-driven

- test/e2e/network_segmentation.go
Exclude the .1 from ipv6 subnet at udn e2e tests, so it do not collide with default gw configuration at pod.
-->
```release-note
NONE
```
> e2e, udn: Exclude ipv6 gateway address

- docs/troubleshooting/ovnkube-trace.md
- docs/troubleshooting/udn.md
- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
- go-controller/cmd/ovnkube-trace/udn.go
- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/util/net.go
A new vrf table id is needed by UDN, this change move the egress ip table ID generator to util so it can be used by UDN feature.
Also a new command to `ovnkube-trace --dump-udn-vrf-table-ids` to dump VRF table IDs per node, the output is a json in the form 
```json
{
"ovn-control-plane": {
"net-blue": 1,
"net-red": 2
},
"ovn-worker": {
"net-blue": 3,
"net-red": 4
}
}
```
The egress ip feature already verify the util
util: Move route table calculator from egressip
This change introduces a new flag at `ovnkube-trace --dump-udn-vrf-table-ids` 
```release-note
NONE
```
> util: Move route table calculator from egressip

- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller_test.go
Default network does add NADs.
This is a follow up from PR https://github.com/ovn-org/ovn-kubernetes/pull/4461.
This change addresses the following panic:
```
Image built from ovn-kubernetes ref: refs/heads/master  commit: 0a6853062c6f3da40d07b3bc51bfbc61b058f84d
I0703 14:17:52.721946      52 shared_informer.go:311] Waiting for caches to sync for [cluster-manager NAD controller]
I0703 14:17:52.721970      52 shared_informer.go:318] Caches are synced for [cluster-manager NAD controller]
panic: unexpected call for default network
goroutine 89 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/util.(*DefaultNetInfo).AddNADs(0x205a120?, {0xc0005d6d50?, 0x23f9ce2?, 0x7?})
/builds/nithyar/ovn_upstream_validation/ovn-kubernetes/go-controller/pkg/util/multi_network.go:148 +0x25 …
```
> Refactor NAD controller: Do not attach to default network

- go-controller/pkg/generator/udn/masquerade_ips.go
- go-controller/pkg/generator/udn/masquerade_ips_test.go
Add a function to calculate the
masquerade IPs for shared and local gw for user defined networks.
Depends-on:
- https://github.com/ovn-org/ovn-kubernetes/pull/4503
There are some unit test tesing masquerade IPs generation
NONE
Add user defined network masquerade IPs generator
NONE
```release-note
Add user defined network masquerade IPs generator
```
> udn, allocator: Add masquerade IPs

- .github/workflows/test.yml
- go-controller/cmd/ovnkube-trace/udn.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
- test/Makefile
- test/scripts/test-ovnkube-trace.sh
The project contains an script to exercise ovnkube-trace but that script is not run by any CI lane, this change add a lane named "tools" to run that script.
Add "tools" ci lane
-->
```release-note
NONE
```
> ci: Add lane to test ovnkube-trace

- test/e2e/egress_firewall.go
before starting the test.
An attempt to fix https://github.com/ovn-org/ovn-kubernetes/issues/4480
Based on the reported failures, it seems like a problem with the external container connectivity, as some failures happen even before the egress firewall is created.
Can't guarantee that it will fix it though, couldn't reproduce the problem locally.
WIP: trying to get a couple of successful e2e runs (no egress firewall failures), will update when this is done.
1st green run: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9744630959/job/26893660029?pr=4484
2nd green run: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9747524153/job/26901588241?pr=4484
3rd: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9749486954/job/26907766095?pr=4484
4th: …
> ef e2e: make sure external containers are running and ready to serve

- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_policy.go
- go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
This creates the OVN management port for user defined networks.
Fixes #
This refactors the magament port creation code and moves it to the base network controller.  It also makes it receive the host subnets as argument.  In L2 networks there's a single large subnet pods get their IPs from.
There's one TODO left here and that is that the management port should be added to the per-network "cluster port group".  However, today, that doesn't exist so we keep adding it to the single, large, cluster-wide port group.  This should be addressed when network policy support is added to user defined networks.
Existing UTs and e2es must pass.
NONE
Adds the OVN management port to L2 and L3 user defined networks.
```release-note
NONE
```
> UDN: L2/L3 - add OVN management port

- helm/ovn-kubernetes/charts/ovn-ipsec/templates/daemonset.yaml
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/ovnkube-control-plane.yaml
- helm/ovn-kubernetes/charts/ovnkube-db/templates/deployment.yaml
- helm/ovn-kubernetes/charts/ovnkube-identity/templates/ovnkube-identity.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu-host/templates/ovnkube-node-dpu-host.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu/templates/ovnkube-node-dpu.yaml
- helm/ovn-kubernetes/charts/ovnkube-node/templates/ovnkube-node.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
- helm/ovn-kubernetes/charts/ovs-node/templates/ovs-node.yaml
This patch introduces a conditional inclusion of image pull secrets across various daemonsets and deployments within our Helm charts. Users can now specify the
'imagePullSecretName' in the 'global' values to include this secret. This flexibility allows for secure pulling of images from private repositories when required.
Example usage in values.yaml:
```yaml
global:
imagePullSecretName: my-registry-secret
```
Documentation reference on using `imagePullSecrets`: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
> helm: Add conditional image pull secrets to Helm charts

- docs/getting-started/configuration.md
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/egress_service_test.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/util/iptables.go
Global forwarding works differently for IPv6:
```
conf/all/forwarding - BOOLEAN
Enable global IPv6 forwarding between all interfaces.
IPv4 and IPv6 work differently here; e.g. netfilter must be used
to control which interfaces may forward packets and which not.
```
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt
It is not possible to configure the IPv6 forwarding per interface by setting the net.ipv6.conf.IFNAME.forwarding sysctl (it just configures the interface-specific Host/Router behaviour). Instead, the opposite approach is required where the global forwarding is enabled and traffic is restricted through iptables.
**To ensure consistent behavior between IPv4/IPv6 and to limit the forwarding scope for IPv4 networks this PR configures the default DROP policy for both …
> Enable global IPv6 forwarding

- contrib/kind-common
- contrib/kind-helm.sh
- contrib/kind.sh
This includes enhancements to kind and kind-helm:
- kind-common: Add kind_get_nodes function
- kind-helm: Add Enable Multi-Network Support (as in non-helm script)
- kind-helm.sh: Add --config-file Flag (as in non-helm script)
The kind_get_nodes function in kind-common is necessary to exclude the external load balancer node that is automatically added by kind when multiple controller nodes are created.
> Kind Script Fixes: kind_get_nodes and kind-helm Support for Multi-Net and Kind-Config

- go-controller/pkg/testing/util.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
When looking for the active network ovn-k should skip the non OVN nads instead of failing with the well known error.
It has a unit test
For more information on release notes see: TBD
-->
```release-note
NONE
```
> udn: Skip non ovn nads

- go-controller/pkg/clustermanager/pod/allocator.go
- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_linux_test.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/cni/udn/primary_network.go
- go-controller/pkg/cni/udn/primary_network_test.go
- go-controller/pkg/cni/utils.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/testing/util.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
- test/e2e/multihoming_utils.go
- test/e2e/network_segmentation.go
Add logic at secondary network controller to trigger the creation of network selection element (but not annotate the pod) with the found active network, it also plumbs the primary network at the pod network namespace
It also introduce "Pending" egress test to activate it when topology for egress is in place.
Superceeds:
- https://github.com/ovn-org/ovn-kubernetes/pull/4459
It contains some unit test and the already present east/west traffic e2e
NONE
NONE
-->
```release-note
Wired up primary network lsp and network namespace config by creating a network selection element.
```
> UDN: Use synthetic network selection element

- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- test/e2e/network_segmentation.go
This PR is the non-IC deployment counter-part of #4514 ; it auto-excludes the GW and mgmt port IPs for layer2 primary networks when IP addresses are assigned on the ovnkube-controller (by the logical switch manager).
Fixes #
This code only makes sense **if** we want to support non-IC for user defined networks. 
Run the associated unit tests.
Auto exclude gw mgmtport ips layer2 udn for non-IC deployments
```release-note
NONE
```
> Auto exclude gw mgmtport ips layer2 udn for non-IC deployments

- .github/workflows/test.yml
- dist/templates/rbac-ovnkube-node.yaml.j2
- go-controller/pkg/factory/factory.go
- test/e2e/network_segmentation.go
We had to update the job names so the user segmentation lanes do not clash (the only difference between them is the IC configuration).
This PR introduces an e2e test lane for user defined primary networks on **non interconnect deployments**.
Fixes #
This PR must go after the PR that fixes the e2e tests for L2 on non-IC deployments: #4517 
```release-note
```
> udn, ci, e2e: add a non-IC lane

- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller_test.go
- go-controller/pkg/network-attach-def-controller/network_manager.go
- go-controller/pkg/network-controller-manager/network_controller_manager.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
The NAD controller was attempting to clean up stale networks from references to network controllers that had not been created yet as the controller itself had not been started. Use the BasicNetInfo of networks that are about to be created instead.
> Fix stale network cleanup

- go-controller/pkg/clustermanager/clustermanager_test.go
- go-controller/pkg/clustermanager/network_cluster_controller_test.go
- go-controller/pkg/clustermanager/node/node_allocator.go
- go-controller/pkg/clustermanager/zone_cluster_controller.go
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/hybrid_test.go
- go-controller/pkg/ovn/kubevirt_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler_test.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/node_annotations_unit_test.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/util_unit_test.go
JoinSubnets are allocated only for default networks as of today.
We never needed them on UDNs since we never supported
pod2Egress there and never had a join or GR in the topologies.
Given this is changing moving forward, this PR aims to ensure
joinSubnet is configurable via NAD configs. If not provided
assumes the default values. We also change code to ensure
join subnet is calculated also for UDNs (primary only) moving
forward.
NOTE: Validation of joinSubnet for UDN against default network's
joinSubnet will be done in another PR. I don't think there is any
validation for pod subnet cidr range as well, so might as well get
both done together in the future (Being tracked separately)
> Add `joinSubnets` config for UDNs

- go-controller/pkg/util/multi_network_test.go
This PR adds unit test coverage to the `GetPodNADToNetworkMapping` function.
It asserts the function works as expected in the following scenarios:
- the intended network is **not** found in the attachment list: returns false, not an error
- the intended network **is** found in the attachment list: returns true, not an error
- there are more than 1 attachment to the same network with the same NAD name: returns an error
- a user defined primary network is configured on a namespace, and specified as a secondary network in a pod: returns an error
Fixes #
Run the provided unit tests.
```release-note
NONE
```
> Prevent user defined network from being attached as secondary net

- helm/ovn-kubernetes/Chart.yaml
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/charts/ovn-ipsec/templates/daemonset.yaml
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/ovnkube-control-plane.yaml
- helm/ovn-kubernetes/charts/ovnkube-db/templates/deployment.yaml
- helm/ovn-kubernetes/charts/ovnkube-identity/templates/ovnkube-identity.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu-host/templates/ovnkube-node-dpu-host.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu/templates/ovnkube-node-dpu.yaml
- helm/ovn-kubernetes/charts/ovnkube-node/templates/ovnkube-node.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
- helm/ovn-kubernetes/charts/ovs-node/templates/ovs-node.yaml
- helm/ovn-kubernetes/templates/_helpers.tpl
- helm/ovn-kubernetes/templates/ovn-setup.yaml
- helm/ovn-kubernetes/values.yaml
**Note**: This is a continuation of https://github.com/ovn-org/ovn-kubernetes/pull/4494 
It is needed to account for cases where image pull secret itself may need to be created.
This PR allows for secure pulling of images from private repositories when required.
Example usage in values.yaml:
```
global:
imagePullSecretName: my-registry-secret
dockerConfigSecret:
registry: ghcr.io
auth: blah_blah_blah
create: true
```
Documentation reference on using imagePullSecrets: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
> Helm image secrets (continuation)

- .github/workflows/test.yml
- helm/ovn-kubernetes/templates/rbac-ovnkube-node.yaml
HELM: udn, non-IC: allow node to read NADs on non-IC
This is needed when there are user defined primary networks configured
in a namespace, and so the CNI side knows it needs to wait for the
annotations to appear on the pod.
This is a complement for commit 9e2aa33cf0bce0994ae96a1be982528ee16471a2
so it also applies to helm.
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/4534
> fix multi-net when deploying via helm

- go-controller/pkg/node/secondary_node_network_controller.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_network_controller_secondary_test.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/node_annotations_unit_test.go
Find and store the networkID at different at the following UDN controllers:
- layer3
- layer2
- udn node
The `EnsureNetworkID` helper is not created under `pkg/util` to be able to use use factory.NodeWatchFactory, not doing so creates a dependencies cycle since "factory" is already using "pkg/util".
Future primary UDN egress e2e tests will use this.
Store networkID at udn controllers
NONE
```release-note
Store networkID at udn controllers
```
> udn, controllers: Add getNetworkID helper

- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/secondary_node_network_controller.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
Depends-On: https://github.com/ovn-org/ovn-kubernetes/pull/4529
- We have intentionally kept it separate from default network's syncManagementPort which is way more static
- We also don't have periodic reconcile loops etc at the moment, these can be future enhancements when we have a basic functionally done.
```
k8s.ovn.org/network-ids: {"default":"0","l2-network":"5","l3-network":"4"}                                                                               
k8s.ovn.org/node-chassis-id: fe7f50c6-7321-43c3-9329-0435ea0bc33c                                                                                        
k8s.ovn.org/node-gateway-router-lrp-ifaddr: {"ipv4":"100.64.0.3/16","ipv6":"fd98::3/64"}                                                                 
k8s.ovn.org/node-id: 3 …
```
> UDN: Create/Delete management port interface on the host side

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cni_test.go
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/types.go
Don't look for primry UDN networks at CNI if the network segmentation feature gate is not activated.
Upgrade issues from pre primary UDN networks pods with network segmentation not enabled.
Upgrade with pod's from pre primary UDN changes and network segmentation gate not enabled.
udn, cni: Gate primary role networks
For more information on release notes see: TBD
-->
```release-note
udn, cni: Gate primary role networks
```
> udn, cni: Gate primary role networks

- go-controller/pkg/cni/udn/primary_network.go
- go-controller/pkg/cni/udn/primary_network_test.go
- go-controller/pkg/ovn/network_segmentation_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/pods_test.go
After upgrade from non network segmentation enabled version the default
network at pods will not have the role field at the ovn annotation. This
change add that field and hardcode it to "primary" since configuring a
primary UDN at a namespace with pods is not supported.
Testing it here:
- https://github.com/openshift/ovn-kubernetes/pull/2230
Fixes #TODO
udn, pods: Add default net 'role=primary' when missing
-->
```release-note
udn, pods: Add default net 'role=primary' when missing
```
> udn, pods, cni: Add default net 'role=primary'

- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
Throw an error if the subnets attribute is not defined for primary user defined networks of `layer2` topology.
The controllers require the subnet attribute to properly configure the GW for egressing the workload traffic.
Fixes #
```release-note
Primary user defined networks of layer2 topology must have the subnets attribute defined.
```
> udn, config: a layer2 primary UDN requires subnets

- go-controller/pkg/node/node_ip_handler_linux_test.go
- go-controller/pkg/ovn/pods.go
Otherwise there is a performance/start up hit in large clusters where we potentially try to annotate all pods in a cluster on each node.
Credit to @tssurya for identifying this issue
> Make annotation in pod sync only happen for local pods

- go-controller/pkg/config/config.go
- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/libovsdb/ops/acl.go
- go-controller/pkg/libovsdb/ops/address_set.go
- go-controller/pkg/libovsdb/ops/chassis.go
- go-controller/pkg/libovsdb/ops/lbgroup.go
- go-controller/pkg/libovsdb/ops/loadbalancer.go
- go-controller/pkg/libovsdb/ops/model_client.go
- go-controller/pkg/libovsdb/ops/portgroup.go
- go-controller/pkg/libovsdb/ops/qos.go
- go-controller/pkg/libovsdb/ops/router.go
- go-controller/pkg/libovsdb/ops/switch.go
- go-controller/pkg/libovsdb/ops/template_var.go
- go-controller/pkg/libovsdb/ops/transact.go
- go-controller/pkg/ovn/controller/unidling/unidle.go
- go-controller/pkg/ovn/controller/unidling/unidle_test.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_test.go
Make OVSDBTimeout for transactions a part of config.Global instead of const. A reasonable value for this timeout depends on the size of the cluster and making it configurable may help solve crashloop problems. It also speeds up testing as timeout may be set to lower value for unit tests.
`types.OVSDBTimeout` is still used in `libovsdb.newClient` for inactivity and reconnectTimeouts.
How much time a transaction takes depends on the size of this transaction, one of the most complicated examples is address set dbIDs sync, which needs to update address set name and all its references (i.e. acls, lrps, qoses matches). I have set batch size for transaction to 50 https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/external_ids_syncer/address_set/address_set_sync.go#L76 …
> Bump OVSDBTimeout and make it configurable.

- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/network_cluster_controller_test.go
- go-controller/pkg/clustermanager/pod/allocator.go
- go-controller/pkg/clustermanager/pod/allocator_test.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/cni/udn/primary_network.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/util/util.go
We should show proper error events on defects related to UDN so users can react properly:
The events that got recorded at the PR will look like the following
Unknown active network
```
ormal   Scheduled               16m                default-scheduler  Successfully assigned default/client-pod to ovn-worker
Warning  ErrorUpdatingResource   16m (x3 over 16m)  controlplane       addLogicalPort failed for default/client-pod: unable to determine what is the primary role network for namespace 'default'; please remove multiple primary role networkNADs from it
Warning  ErrorAllocatingPod      16m (x2 over 16m)  controlplane       unable to determine what is the primary role network for namespace 'default'; please remove multiple primary role networkNADs from it
Warning  ErrorReconcilingPod  69s …
```
> udn: Add events to primary role network related problems

- .github/workflows/test.yml
- contrib/kind-common
- contrib/kind-helm.sh
- contrib/kind.sh
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-control-plane.yaml.j2
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-single-node-zone.yaml.j2
- dist/templates/ovnkube-zone-controller.yaml.j2
- dist/templates/rbac-ovnkube-cluster-manager.yaml.j2
- dist/templates/rbac-ovnkube-master.yaml.j2
- dist/templates/rbac-ovnkube-node.yaml.j2
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/ovnkube-control-plane.yaml
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/rbac-ovnkube-cluster-manager.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/rbac-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
- helm/ovn-kubernetes/templates/rbac-ovnkube-node.yaml
- helm/ovn-kubernetes/values.yaml
This PR adds support for DNSNameResolver in KIND cluster.
A new flag, `[-dns | --enable-dnsnameresolver]`, is now supported by `contrib/kind.sh`. When a KIND cluster is installed using this flag, the cluster will be using DNSNameResolver for resolving DNS names used in EgressFirewall rules. Wildcard DNS names will also supported in EgressFirewall DNS rules.
> Add support for DNSNameResolver in KIND cluster

- contrib/README.md
The README.md under `contrib/` referred to a `kind.md` file which did not appear to exist. I've added a hyperlink to the `./docs/installation/launching-ovn-kubernetes-on-kind.md` file which appears to be the appropriate documentation.
> fix: link to kind usage docs in contrib README.md

- go-controller/hack/lint.sh
Currently, `make lint` runs golangci-linter in a container but wont mount golangci-lint local cache.
linter time can be optimized by using the local cache, in tested env lint time droped from 1:11 minutes to 45 seconds.
This PR changes hack/lint.sh to mount golangci-lint local cache to the subject container.
Fixes #
```release-note
NONE
```
> hack/lint.sh: Mount local golangci-lint cache

- .github/workflows/test.yml
- docs/features/cluster-egress-controls/egress-ip.md
- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/node/linkmanager/link_network_manager.go
- go-controller/pkg/node/linkmanager/link_network_manager_test.go
- go-controller/pkg/node/routemanager/route_manager.go
- go-controller/pkg/node/routemanager/route_manager_test.go
- test/e2e/egressip.go
If EIP assigned to secondary interface thats enslaved by a VRF device, use the associated VRF devices routing table instead of main. Added unit tests + e2e.
> Add VRF support for EIP assigned to secondary interface

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/openflow_manager.go
- go-controller/pkg/node/openflow_manager_test.go
This commit changes the openflow manager to ignore localnet patch ports when bootstrapping the default cluster network - these have a different format (they feature the physical network name for which the port was created instead of a physical bridge), which leads to the following error:
```
failed to start node network controller: failed to start default node network
controller: failed to bootstrap OVS flows: failed to get flows on bridge
"vlan2002_ovn_localnet":, stderr: "ovs-ofctl: vlan2002_ovn_localnet is not a
bridge or a socket\n", error: exit status 1
```
Fixes https://issues.redhat.com/browse/OCPBUGS-37433
```release-note
```
> OCPBUGS-37433: ignore localnet patch ports while bootstrapping the cluster default network

- go-controller/pkg/ovn/hybrid.go
- go-controller/pkg/ovn/hybrid_test.go
- go-controller/pkg/ovn/master.go
It can help to avoid the unintended match when the '-gr' substring exists in a node name.
Fixes https://issues.redhat.com/browse/OCPBUGS-37855
```release-note
```
> Use more exact name match when deleting static routes to HO nodes

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cni_test.go
- go-controller/pkg/cni/cnishim.go
- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/udn/primary_network.go
When a pod with a primary UDN is deleted it has to call the unconfigure interface to delete ovs resources.
It will have unit test
```release-note
NONE
```
> udn, cni: Unconfigure interface

- go-controller/pkg/libovsdb/ops/router.go
- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
The EgressIP assigned node is accidently deleted from cluster which causes EIP is moved to another node, but while updating nexthops EgressIP zone controller is not able to find node object to remove nexthop from Logical Route Policy for the old node and this becomes a stale entry on the LRP. This commit ensures nexthop is updated even when node is not found from the watch factory.
> Delete EgressIP LRP stale nexthops when node is not found

- go-controller/pkg/clustermanager/endpointslicemirror/endpointslice_mirror_controller.go
There is a small chance that objects from the informer are not of type v1.EndpointSlice, add a check to handle this scenario. Example error seen:
```
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2205280, 0xc0001861b0})
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0006b1a40?})
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x2205280?, 0xc0001861b0?})
/usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/clustermanager/endpointslicemirror.(*Controller).enqueueEndpointSlice(0xc0004fd080?, {0x22dd7e0?, 0xc0001214e0?}) …
```
> EndpointSlice mirror controller: ensure enqueued objects are endpoint slice

- go-controller/pkg/network-attach-def-controller/network_manager.go
Synchronizes access to `nm.networks` map to avoid race condition while running the tests.
Fixes https://github.com/ovn-org/ovn-kubernetes/issues/4602.
> UT flake: fix race condition for nad controller tests

- go-controller/pkg/clustermanager/network_cluster_controller.go
When a pod is created, and the IP pool is empty,
the pod will stuck forever in creation state, even if IPs are released.
To simulate the bug:
1. Create a NAD with a pool with just 1 available IP (others excluded; first and last reserved).
2. Create 2 pods that use this NAD:
a. One pod will take the IP.
b. The second pod will remain in "creation" state.
3. Wait around 1 minute and then delete the Running pod.
The bug: The pending pod stays pending forever, even though an IP is available.
Without the fix, update / add Pod retry mechanism isn't triggered at all, because it will be triggered
only if a non nil error is returned.
Note: 
Even with the fix, the retry mechanism is capped in 15 retries [1], which total for around 15m.
After 15m the pod will be pending forever, even if IPs are …
> Fix retry handling in case IP pool is empty

- go-controller/pkg/ovn/egressfirewall_test.go
an attempt to fix data race https://github.com/ovn-org/ovn-kubernetes/actions/runs/10300314435/job/28509457479?pr=4590
We start nodeController here in the test https://github.com/ovn-org/ovn-kubernetes/blob/1e4527557ec1f14c1a9534387ee1288872d9f6bf/go-controller/pkg/ovn/egressfirewall_test.go#L233-L234
but it is never stopped
> UT egress firewall: stop node controller in AfterEach.

- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
```
sh-5.2# ovn-nbctl list logical-router GR_l3.network_ovn-control-plane
_uuid               : b2a4db8a-54b2-44c9-89f5-dacf381dca17
copp                : d51232db-7768-4d6c-aab0-9303a7856e8c
enabled             : []
external_ids        : {"k8s.ovn.org/network"=l3-network, "k8s.ovn.org/topology"=layer3, physical_ip="172.18.0.4", physical_ips="172.18.0.4,fc00:f853:ccd:e793::4,169.254.0.11,fd69::b"}
load_balancer       : []
load_balancer_group : []
name                : GR_l3.network_ovn-control-plane
nat                 : []
options             : {always_learn_from_arp_request="false", chassis="53db7ce4-f836-41ca-a176-8e237073f602", dynamic_neigh_routers="true", lb_force_snat_ip=router_ip, mac_binding_age_threshold="300", snat-ct-zone="0"}
policies            : []
ports               : …
```
> Don't use zone 0 for UDN Networks

- go-controller/pkg/ovn/master.go
In large scale zone around 800 nodes,  this check consume more than 60% of the cpu time. we only need check when old and new node object has chassis id annotation change.
Fixes #
```release-note
```
> Avoid calling oc.deleteStaleNodeChassis for every node update event

- dist/images/Makefile
The default OVS branch has been renamed from "master" to "main" a while ago.
This fixes the `make -C dist/images fedora-dev` target which was incorrectly trying to clone OVS "master" branch.
Fixes #
Build the dev ovn-kubernetes image:
```
make -C dist/images fedora-dev
```
```release-note
```
> dist/images: Use OVS main branch.

- go-controller/pkg/cni/bandwidth.go
- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/helper_linux.go
The previous implementation had several issues:
- If a NAD was removed while pods were active, CNI DEL would fail.
- If a pod was force removed, CNI DEL would fail.
The above issues were due to:
- Searching for the NAD to be able to do the CNI DEL
- Searching for the pod in the informer cache for CNI DEL
This PR simplifies deletion by not relying on the pod object or the NAD
object. When primary CNI deletion happens with this patch, we simply
find any interfaces that belong to this pod's sandbox ID. There is no
performance impact, because clearPodBandwidth was already finding all of
these ports anyway.
CNI deletion happens in reverse order, so we can be sure that secondary
interfaces have already been deleted by the time we search and delete
interfaces for the primary CNI.
Signed-off-by: …
> Fixes deleting CNI DEL with UDN

- test/e2e/network_segmentation.go
Use the current UDN pod state to avoid a race in which the condition is not yet set during pod creation.
Additionally print the pod object in case of failure for easier debugging in the future. 
Seen flaking in CI, example run:
```
2024-08-17T05:12:27.5807666Z   [1mSTEP:[0m asserting healthcheck works (kubelet can access the UDN pod) [38;5;243m@ 08/17/24 05:12:27.58[0m
2024-08-17T05:12:27.5853305Z   [38;5;9m[FAILED][0m in [It] - /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/network_segmentation.go:264 [38;5;243m@ 08/17/24 05:12:27.584[0m
...
2024-08-17T05:13:08.7407141Z [38;5;243m/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/network_segmentation.go:347[0m
2024-08-17T05:13:08.7408176Z 
2024-08-17T05:13:08.7408593Z   [38;5;9m[FAILED] Expected …
```
> Network Segmentation E2E: Use current pod state when checking readiness 

- test/e2e/egressip.go
- test/e2e/util.go
Folks not using our GH CI may not be able to execute the EIP E2E test if they do not have a test dependent kernel module loaded. Skip test if not loaded.
> EIP e2e: skip test if VRF kernel module isn't loaded on target node

- .github/workflows/test.yml
- contrib/kind-helm.sh
- dist/images/ovnkube.sh
- docs/installation/launching-ovn-kubernetes-with-helm.md
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/README.md.gotmpl
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/ovnkube-control-plane.yaml
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/rbac-ovnkube-cluster-manager.yaml
- helm/ovn-kubernetes/charts/ovnkube-identity/values.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/values.yaml
- helm/ovn-kubernetes/templates/rbac-ovnkube-node.yaml
- helm/ovn-kubernetes/values-multi-node-zone.yaml
- helm/ovn-kubernetes/values-no-ic.yaml
- helm/ovn-kubernetes/values-single-node-zone.yaml
add `-ic` option to `kind-helm.sh` to enable interconnect
- if npz is not specified, create single-node zone interconnect
- if npz is greater than 1, create multi-node zone interconnect
support interconnect in Helm chart
#4371
N/A
contrib/kind-helm.sh -ic, should create ovn-k8s with single-node zone interconnect
contrib/kind-helm.sh -ic -wk3 -npz 2, should create ovn-k8s with multi-node zone interconnect
`contrib/kind-helm.sh` only, i.e. without `-ic` option, should create ovn-k8s with interconnect disabled.
N/A
N/A
N/A
> enable interconnect in helm chart

- test/e2e/acl_logging.go
- test/e2e/e2e.go
- test/e2e/e2e_suite_test.go
- test/e2e/egress_firewall.go
- test/e2e/egress_services.go
- test/e2e/egressqos.go
- test/e2e/endpointslices_mirror.go
- test/e2e/external_gateways.go
- test/e2e/gateway_mtu.go
- test/e2e/multi_node_zones_interconnect.go
- test/e2e/multicast.go
- test/e2e/node_ip_mac_migration.go
- test/e2e/pod.go
- test/e2e/reporter.go
- test/e2e/service.go
- test/e2e/static_pods.go
- test/e2e/unidling.go
- test/e2e/util.go
Just a cleanup to `test/e2e`; the `import` ordering was kind of a mess, and very inconsistent.
(`gofmt` requires that the imports section consists of 1 or more newline-separated groups, where each group is individually alphabetized, but it doesn't do any enforcement of what should and shouldn't be in the same group.)
The main codebase is pretty consistent about at least not mixing up stdlib imports and third-party imports, though not totally consistent beyond that. This makes the e2e files use the order (1) stdlib, (2) ginkgo/gomega, (3) ovn-k-internal, (4) everything else; which is sort of the overall consensus ordering.
```release-note
NONE
```
cc @martinkennelly
> Consistently reorder test/e2e imports

- test/e2e/status_manager.go
Fixes [e2e (control-plane, HA, shared, ipv4, snatGW, 1br, ic-disabled)](https://github.com/ovn-org/ovn-kubernetes/actions/runs/10290466858/job/28482170103?pr=4596#logs)
Default are set to `5min, 2s` by k8s https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/test/e2e/framework/timeouts.go#L22-L23
with this comment https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L503-L506. So when you set timeout to `1s`, poll interval is still `2s`, which gives 1 retry.
There is a chance other tests also don't expect that.
> Set gomega poll interval on retry to allow ~5 retries instead of just 1.

- go-controller/pkg/node/secondary_node_network_controller.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
- test/e2e/network_segmentation.go
This PR reacts to the creation of layer2 primary used defined networks by establishing the OVN logical infrastructure (GW routers and external switches in each node) to allow pods connected to that primary user defined network to egress the cluster.
Fixes #
Run the unit tests - this PR introduces unit tests to ensure the ovn topology created is the expected.
Create logical infrastructure to allow egress for primary layer2 user defined networks
```release-note
Create logical infrastructure to allow egress for primary layer2 user defined networks
```
> UDN egress integration: create logical infra for primary UDNs to egress for layer2 networks 

- go-controller/pkg/node/controllers/egressip/egressip_test.go
IPTables doesn't exist inside the containers.. other modules and EIP tests skip running in that case but this one seems to fail?
```
------------------------------
VRF 
copies routes from the VRF routing table for a link enslaved by VRF device
/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node/controllers/egressip/egressip_test.go:1097
STEP: setup link
I0822 13:32:00.166208   17044 iptables.go:224] "Error checking iptables version, assuming version at least" version="1.4.11" err="executable file not found in $PATH"
I0822 13:32:00.166899   17044 iptables.go:224] "Error checking iptables version, assuming version at least" version="1.4.11" err="executable file not found in $PATH"
STEP: create VRF and add link
STEP: add route to routing table associated with VRF
STEP: start …
```
> UT: Skip eip test when iptables doesn't exist

- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
For IPv6, if you enslave a link to a VRF device, then any non-Link Local addresses maybe removed.
This commit adds the link addresses only after the link is enslaved.
cc @tssurya
> Fix IPv6 network mgnt port IP address assignment

- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/node_ip_handler_linux.go
- go-controller/pkg/node/node_ip_handler_linux_test.go
Looking for better ideas to filter UDN mgnt port IPs but this is the simplest I can think of right now.
> Node IP hander: ignore mgnt port IPs

- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/iprulemanager/ip_rule_manager.go
- go-controller/pkg/node/secondary_node_network_controller.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
Depends-On: https://github.com/ovn-org/ovn-kubernetes/pull/4549
```
2000:   from all to 169.254.0.12 lookup 1007
2000:   from all to 169.254.0.14 lookup 1009
```
adds iprules for reply traffic to go back into OVN
> UDN: Add IPRules Manager

- go-controller/pkg/node/management-port_dpu_test.go
- go-controller/pkg/util/node_annotations.go
The tests were missing kubeclient and node informer setup. Additionally another test was missing expected OVS commands.
Fixes: #4656
> Fixes panic in DPU mgmt port tests

- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
Depends-On: https://github.com/ovn-org/ovn-kubernetes/pull/4552
Same as default mp0; needed for traffic coming from OVN
with masqueradeIP to go out.
```
0xffff9a698897b000      9 [<empty>(2468110)] kfree_skb_reason(SKB_DROP_REASON_IP_RPFILTER) 169.254.169.12:0->8.8.8.8:0(icmp)
```
```
net.ipv4.conf.ovn-k8s-mp1.rp_filter = 2
net.ipv4.conf.ovn-k8s-mp2.rp_filter = 2
```
> UDN: Add RPFilter Loose Mode for management port

- go-controller/pkg/node/gateway_udn_test.go
Otherwise the tests fail when run on the testing container.
Fixes: #4657
> Use faked iptables in UDN gateway tests

- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/util/node_annotations.go
Everytime a UDN was created, we were adding the all remote nodes for every network all over again, including the default network. This makes the checks on the annotations network aware.
> Fixes remote node checks to be network aware

- .github/workflows/test.yml
- go-controller/pkg/generator/udn/masquerade_ips.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
```
sh-5.2# ovn-nbctl lr-nat-list GR_l3.network_ovn-worker2
TYPE             GATEWAY_PORT          EXTERNAL_IP        EXTERNAL_PORT    LOGICAL_IP          EXTERNAL_MAC         LOGICAL_PORT
snat                                   169.254.0.11                        10.128.2.5
sh-5.2# ovn-nbctl lr-nat-list GR_l3.network_ovn-worker2
sh-5.2# ovn-nbctl lr-nat-list GR_l3.network_ovn-worker2
sh-5.2#
```
let's see how this looks in CI...
TODO:
> UDN: Fix per pod SNATing

- test/e2e/egressip.go
- test/e2e/util.go
- test/scripts/e2e-cp.sh
Issue was healthcheck test didnt consider IPv6 when adding iptable rule to drop packets therefore test would fail because failover didnt occur.
Fixes: #4130
> (Re)Enable EIP IPv6 E2Es and fix issue with test

- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet.go
cc @tssurya 
Fixes https://github.com/ovn-org/ovn-kubernetes/issues/4695
> UDN LGW: ensure masq chain exists before adding rules

- go-controller/pkg/clustermanager/pod/allocator_test.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template_test.go
- go-controller/pkg/cni/udn/primary_network_test.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/ovn/controller/services/lb_config_test.go
- go-controller/pkg/ovn/controller/services/services_controller_test.go
- go-controller/pkg/ovn/controller/services/utils_test.go
- go-controller/pkg/ovn/topology/topologyfactory_test.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
- test/e2e/network_segmentation.go
- test/e2e/network_segmentation_endpointslices_mirror.go
- test/e2e/util.go
this PR does three things 
1. ensure that user defined primary networks only use ip families the cluster supports
2. ensure that e2e tests select the correct families for primary networks under test
3. increase the testing of NAD and UDN CRDS to CIDR overlap and pod2Egress e2e tests 
Fixes #
```release-note
```
> corrections to user defined networking 

- go-controller/pkg/allocator/pod/pod_annotation_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/util/pod_annotation.go
When users attach pod to a secondary network and override the default route pod. It will cause the assymetric routing for service haripin traffic.
We add static routes to ensure the traffic to the hairpin masquerade IP always goes to OVN.
https://issues.redhat.com/browse/OCPBUGS-39009
With this patch, in the pod routing table a static route to hairpin masquerade IPs will be added.
```
root@ovn-control-plane:/# nsenter --net=/proc/3607/ns/net ip route
default via 10.244.2.1 dev eth0 
10.96.0.0/16 via 10.244.2.1 dev eth0 
10.244.0.0/16 via 10.244.2.1 dev eth0 
10.244.2.0/24 dev eth0 proto kernel scope link src 10.244.2.5 
100.64.0.0/16 via 10.244.2.1 dev eth0 
169.254.0.5 via 10.244.2.1 dev eth0 
#IPv6
root@ovn-control-plane:/# nsenter --net=/proc/3607/ns/net ip -6 route
fd00:10:96::/112 …
```
> Add static route to the hairpin masquerade IPs to pod

- contrib/kind-common
There are some expectation at the dev-env interface at metallb that can change and break ovn-k CI, let's pin it so we can propertly consume those changes at a PR later on.
This need to be cherry-pick to proper branches:
- release-1.0
NONE
```release-note
Pin kind metallb to v0.4.18
```
> kind: Pin metallb to v0.14.8

- contrib/kind-common
- contrib/kind.sh
(cherry picked from commit 2b64f10ff8afa271b66368a1e0a91d0e8f502fcb)
> [release-1.0]: Adapt to ipam-controller renaming

- dist/images/Dockerfile.fedora
- test/e2e/e2e.go
- test/e2e/util.go
Test opens a TCP connection that simulates a GCP LB environment where the packet is redirected via iptables to a local server on a node. Note, in GCP the LB does not DNAT the VIP, so the packet arrives to the node with the GCP VIP on it. In OCP, we then redirect that packet to the local kapi server running on the node.
Once the test opens the TCP connection, it leaves it open for 2 minutes while ovnkube-node is then deleted. Post ovn-controller starting it should not flush the conntrack in zone 0, and the test ensures that the conntrack entry still exists.
Recent OVN regression that prompted this E2E: https://issues.redhat.com/browse/FDP-773
I tested this with OVN 24.03 and it passed. Testing with 24.09 will fail due to the above regression. We should wait until an OVN version is ready …
> Adds e2e test: conntrack flush after ovnkube delete + bumps OVN with fix

- .github/workflows/test.yml
- contrib/kind-common
- contrib/kind.sh
- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
- go-controller/pkg/util/pod_annotation.go
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/kubevirt.go
- test/e2e/kubevirt/console.go
This PR looks for a special annotation on pods, where KubeVirt (or an agent on behalf of KubeVirt) will indicate what is the name of the `IPAMClaim` used for the primary UDN interface.
An alternative would be to use an hard-coded value, but then we wouldn't be able to distinguish between a pod and a VM, and we do not want to abuse reading the KubeVirt label.
Fixes #
Pending adding the CI requirements, ensuring kubevirt e2e tests are run.
Configure persistent IPs on UDN networks when requested
```release-note
Configure persistent IPs on UDN networks when requested
```
> udn: set persistentIPs for UDN ifaces

- contrib/kind-common
There are some expectation at the dev-env interface at metallb that can change and break ovn-k CI, let's pin it so we can propertly consume those changes at a PR later on.
(cherry picked from commit b3ba566d043011be863a5cffce47918002fb3d72)
```release-note
[release-1.0], kind: Pin metallb to v0.14.8
```
> [release-1.0], kind: Pin metallb to v0.14.8

- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
For UDN L3, it seems the local LRSR and LRPs are not getting created correctly.
SGW:
See a snippet of default network routes:
```
sh-5.2# ovn-nbctl lr-route-list ovn_cluster_router                                                                                                                          
IPv4 Routes
Route Table <main>:
100.64.0.2                100.88.0.2 dst-ip
100.64.0.3                100.64.0.3 dst-ip
100.64.0.4                100.88.0.4 dst-ip
10.244.0.0/24                100.88.0.2 dst-ip --> remote pod subnet re-route to other node's transit port
10.244.2.0/24                100.88.0.4 dst-ip --> remote pod subnet re-route to other node's transit port
10.244.1.0/24                100.64.0.3 src-ip --> local pod subnet re-route to GR of this node
10.244.0.0/16 …
```
> UDN: L3: Use nodesubnet annotations for L3; not clustersubnet from NAD

- contrib/kind-common
- go-controller/pkg/config/utils.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
Fixes a number of related things about gateway configuration and its tests for UDNs:
* gateway manager not accounting for different join subnets of UDNs
* tests not expecting the join subnet SNAT when pods snats were disabled
* tests misleadingly naming join ip to the ovn masquerade ip
* L3 tests with duplicated names
* L2 duplicated tests of which some were intended to test something else
* L2 secondary tests annotating the wrong IP under the assumption that mgmt and gw IPs would be allocated
> UDN gateway & test fixes

- go-controller/Makefile
- go-controller/pkg/libovsdb/ops/router.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_network_controller_secondary_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
- test/e2e/network_segmentation.go
- test/e2e/network_segmentation_services.go
Depends-On: https://github.com/ovn-org/ovn-kubernetes/pull/4553
Depends-On: https://github.com/ovn-org/ovn-kubernetes/pull/4718
v4:
```
_uuid               : 084ad16e-7d46-495e-87d7-15ff11028d47
allowed_ext_ips     : []
exempted_ext_ips    : []
external_ids        : {}
external_ip         : "169.254.0.12"
external_mac        : []
external_port_range : ""
gateway_port        : []
logical_ip          : "10.128.0.0/24"
logical_port        : rtos-l3.network_ovn-control-plane
match               : "eth.dst == 76:23:f2:3b:a8:df"
options             : {stateless="false"}
priority            : 0
type                : snat
```
v6:
```
_uuid               : 40a02f3e-e24b-4f5e-a1a7-a7db84834628 …
```
> UDN L3/L2 Add Masquerade SNAT

- dist/images/Dockerfile.fedora
We are running into issues with our CI:
```
13.52 >>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xFailed to download metadata (metalink: "https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64") for repository "rawhide"
13.52  Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
------
```
@dceara helped us get unblocked by doing a build: https://koji.fedoraproject.org/koji/taskinfo?taskID=123480682 on fedora41 to make this rpm available, let's use that meanwhile waiting for https://bodhi.fedoraproject.org/updates/FEDORA-2024-91bf950011 to get karmas
> Use fedora 41 instead of rawhide

- contrib/kind-common
- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cni_test.go
- test/e2e/network_segmentation.go
This PR (based on https://github.com/ovn-org/ovn-kubernetes/pull/4671) is updating the network-status annotation to report UDN iface info.
Before this commit, this was the network status we reported for a UDN pod:
```
kubectl get pods pod -ojsonpath="{@.metadata.annotations.k8s\.v1\.cni\.cncf\.io\/network-status}" | jq
[
{
"name": "ovn-kubernetes",
"interface": "eth0",
"ips": [
"10.244.1.9",
"fd00:10:244:2::9"
],
"mac": "0a:58:0a:f4:01:09",
"default": true,
"dns": {}
}
]
```
With it, we now report:
```
[
{
"name": "ovn-kubernetes",
"interface": "ovn-udn1",
"ips": [
"10.128.0.4"
],
"mac": "0a:58:0a:80:00:04",
"default": true,
"dns": {}
},
{
"name": "ovn-kubernetes",
"interface": "eth0",
"ips": [
"10.244.0.4"
],
"mac": "0a:58:0a:f4:00:04",
"dns": {}
}
]
```
This way, applications complying …
> udn, cni: report UDN iface info on network-status

- dist/images/Dockerfile.fedora
> fedora: Update Dockerfile to OVN release ovn-24.09.0-33.

- go-controller/pkg/libovsdb/ops/router.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/gatewayrouter/policybasedroutes.go
- go-controller/pkg/ovn/gatewayrouter/policybasedroutes_test.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/node_annotations.go
- test/e2e/network_segmentation.go
Depends on https://github.com/ovn-org/ovn-kubernetes/pull/4554
Fixes: #4686
Fixes: #4682
Design:
What are the routes we need on L2 GR? It needs to be a combo of routes on L3's GR and ovn_cluster_router
Today this is what we have:
```
sh-5.2# ovn-nbctl lr-route-list GR_l2.network_ovn-worker                                                                                                                     
IPv4 Routes                                                                                                                                                                  
Route Table <main>:                                                                                                                                                          
169.254.0.0/17               169.254.0.4 …
```
> UDN: Design routes and policies on L2's GR correctly.

- test/e2e/service.go
Reset shared variables before each test to avoid cleanup issues.
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/4733.
> Services NodePort E2Es: Reset shared variables before each test

- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
On GRs we have an SNAT from the join port IP address to the external IP address for ICMP needs frag sent by OVN to the external network.
In L2 UDNs, even though there is no join network, the internal port has two IPs, one for the pod subnet and another for the join subnet. The ICMP source address will be the first one in lexicographical order which might be the pod subnet one.
The proper SNAT for the GR pod subnet address gets created in the gateway initialization. But:
1 when DisableSNATMultipleGWs=false, it is redundant because there is
already a SNAT for the whole pod subnet
2 when DisableSNATMultipleGWs=true we end up with no SNAT because
cleanupStalePodSNATs cleans it up becaause it never expected that
SNAT
This commit fixes (2)
> Fix missing ICMP SNAT for L2 UDNs GR

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/openflow_manager.go
- test/e2e/network_segmentation_services.go
Ensures isolation between UDN pods and services from the default network.
Fixes #4687
E2E tests covering this use case have been updated.
Unit tests added to check the correct openflows are added to br-ex.
N/A
```release-note
NONE
```
> UDN: Ensure pod2service isolation in local gw mode.

- go-controller/pkg/ovn/ovn.go
- test/e2e/external_gateways.go
- test/scripts/e2e-cp.sh
Cleanup gateway pod for remote zone.
For local zone pods, deleteLogicalPort cleans this up, but before IC
this function was called for all non-host-network pods, hence this
logic. After IC, deleteLogicalPort won't be called for all remote zone
pods, so condition is not needed.
See test result without the fix here https://github.com/ovn-org/ovn-kubernetes/pull/4743
> Fix egress gateway pod cleanup for remote zone pods.

- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
Presently for each remote node, ovnkube after creating the remote port in the OVN Northbound db transit switch, binds the port to the remote chassis in the Southbound database.  In order to do this, we have to wait for the remote logical ports (for each of the remote zone nodes) to appear in the OVN Southbound database. This can lead to race conditions.  Instead ask ovn-northd to bind to the remote chassis.  OVN after this commit [1] already supports this.  We just need to set the requested-chassis option in the logical port.
[1] - https://github.com/ovn-org/ovn/commit/170d3e5f19f0fcd760db068cda29fc1b7f1d7ef5
Jira: https://issues.redhat.com/browse/OCPBUGS-42616
Fixes #
```release-note
```
> interconenct: Ask ovn-northd to bind the remote ports.

- go-controller/pkg/network-controller-manager/node_network_controller_manager_test.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
`
mount --make-rshared /run/user/1000/netns failed: "operation not permitted"
`
Fixes #
Rather than making all the tests there go into sudo mode I moved out the test that requires the testNS framework into its own package so that we can run the other tests properly downstream.
```release-note
```
> Fix sudo perms when running tests

- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/multihoming_test.go
We kept trying to add the management port
for secondary networks into the cluster
port group of secondary networks.
But that port group doesn't exist yet.
It will exist once we get https://github.com/ovn-org/ovn-kubernetes/pull/4547 merged but until then this is causing
infinite retries from syncMgmtPort
erroring out. So let's skip this for now
PS: Not really infinite, only 15 times..
> Skip cluster port group operations for UDN

- go-controller/pkg/node/vrfmanager/vrf_manager.go
Sample of logs from an active node:
```
2024-09-18T15:31:11.170275900Z I0918 15:31:11.170246    6743 vrf_manager.go:99] VRF Manager: link update received for interface 5ebc7f96ab4dfdd
2024-09-18T15:31:11.170952573Z I0918 15:31:11.170929    6743 vrf_manager.go:99] VRF Manager: link update received for interface 5ebc7f96ab4dfdd
2024-09-18T15:31:11.171235113Z I0918 15:31:11.171216    6743 vrf_manager.go:99] VRF Manager: link update received for interface 5ebc7f96ab4dfdd
2024-09-18T15:31:11.171632264Z I0918 15:31:11.171613    6743 vrf_manager.go:99] VRF Manager: link update received for interface 5ebc7f96ab4dfdd
2024-09-18T15:31:11.180630043Z I0918 15:31:11.180572    6743 helper_linux.go:442] ConfigureOVS: namespace: openshift-must-gather-m2dq9, podName: perf-node-gather-daemonset-pq5l4, …
```
> VRF manager: reduce log chat for link updates

- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/util/util.go
Ensure that the values specified in `udn-allowed-default-services` are valid namespaced service names.
Stop using `cli.StringSlice` to allow for setting the field through a config file.
> Verify udn-allowed-default-services config field

- contrib/kind-common
Allow to install custom Kubevirt releases.
Also allows to freeze specific version upon needs, for example if newest breaks stuff,
or if a feature is required before a stable release exists.
Default stays deploy last stable as it was.
Since nightly doesn't release virtctl binary, keep using the latest stable released virtctl.
Use by exporting optional env var `KUBEVIRT_VERSION` with the requested value.
Possible values of `KUBEVIRT_VERSION`:
```
stable - install newest stable (default)
vX.Y.Z - install specific stable (i.e v1.3.1)
nightly - install newest nightly
nightly tag - install specific nightly (i.e 20240910)
```
Fixes #
`quay.io/kubevirt/network-passt-binding` does have nightly,
in order to determine the tag, some more logic need to be added,
so for now only support stable
Note …
> kind: Allow to install custom kubevirt versions

- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/clustermanager/userdefinednetwork/controller.go
- go-controller/pkg/clustermanager/userdefinednetwork/controller_test.go
- go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template.go
- go-controller/pkg/util/node_annotations.go
- go-controller/pkg/util/status.go
- test/e2e/network_segmentation.go
- test/scripts/e2e-cp.sh
Cluster manager controllers may have errors related to the UDN network. For example, if Network's cluster subnet doesn't have enough node subnets for all existing nodes. This will cause pod creation error for the nodes, that were not allocated a subnet for a given UDN, and finding the real cause may be cumbersome.
I propose the following framework to report errors that are related to other objects (e.g. nodes in this case).
We use one Success condition, which is true when all related objects were handled fine (all nodes in this case), and is false if at least one error was. The error message in this case should report one failed node to simplify debugging in case events will disappear, but the condition will not be updated until reported node is fixed changed to limit the amount of api …
> Improve error reporting for UDN

- go-controller/pkg/controller/controller.go
- go-controller/pkg/controller/controller_test.go
Usually controller should only be stopped once, but when it is a part of another controller that tries to cleanup, that may be complicated.
Currently `nodeNetworkControllerManager` on `Start` failure will call its own `Stop` method.
https://github.com/ovn-org/ovn-kubernetes/blob/715d5252f6c8ea62885d7da2c5c67970dedd65c3/go-controller/pkg/network-controller-manager/node_network_controller_manager.go#L173-L177
If it was `nadController` that failed to start https://github.com/ovn-org/ovn-kubernetes/blob/715d5252f6c8ea62885d7da2c5c67970dedd65c3/go-controller/pkg/network-controller-manager/node_network_controller_manager.go#L195 it doesn't not expect to be stopped (it actually already cleaned up its resources on failed start), but ncm `Stop` funciton doesn't track which part failed to start, …
> controller: make stop idempotent.

- go-controller/pkg/util/node_annotations.go
The host address annotations were parsed as a set of strings and sets are unordered.  In consequence GetNodeHostAddrs() might return differently ordered host addresses when invoked on the same annotation.
In some cases this can cause DeepEqual() comparisons of objects that contain the parsed annotation results to fail even though the annotation itself didn't change.
One such example is with NodeTracker.updateNodeInfo() which compares two nodeInfo structures that contain parsed lists of host addresses.  The unstable parsing was causing unexpected full service resyncs when nothing relevant had actually changed on the node annotation.
This becomes more visible when testing with a larger number of UDNs because the NodeTracker objects are created per UDN.
Without this fix, on a 20 node kind …
> node_annotations: Make GetNodeHostAddrs() return stable results.

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/openflow_manager.go
The UDN deletion process is asynchronous between ovn-kubernetes and ovn-controller.
Considering the following sequence of events:
1. UDN created
2. ovnkube's network controller creates the OVN external switch for the UDN (with a localnet port)
3. ovn-controller creates the patch port for the UDN localnet port
4. ovnkube's node controller updates netConfigs include the UDN network
5. ovnkube's node controller determines the ofPort of the newly created patch port
6. UDN deleted
7. ovnkube's network controller deletes the OVN external switch
8. ovn-controller removes the patch port
9. ovnkube's node controller finally gets the update about UDN being deleted and removes the corresponding netConfig.
Steps "8" and "9" are asynchronous and can happen in any order.  If "8" happens before "9" and …
> node: Relax check_ports() for UDN patch ports.

- go-controller/hack/lint.sh
When using podman, `make lint` fails due to the following error:
```
Error: short-name resolution enforced but cannot prompt without a TTY
make: *** [Makefile:93: lint] Error 125
```
Root cause is podman wont add `docker.io` registry name to container image tag if not specified like docker does.
Use full image name including the registry to avid failures on envs that use podman.
Fixes #
```release-note
NONE
```
> hack/lint.sh: Use full image tag

- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller_test.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager.go
- go-controller/pkg/node/secondary_node_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
- go-controller/pkg/testing/nad/netattach.go
As it is unused in any network controller except the node default network controller.
The future plan is to strip PreStart from the node default network controller as well and move that somewhere else.
The ultimate reason is we want to configure the management ports (SNAT) correctly depending on whether the network is advertised or not:
https://github.com/ovn-org/ovn-kubernetes/pull/4572
On that PR, commit `Don't SNAT to mgmt port if pod network advertised`:
https://github.com/ovn-org/ovn-kubernetes/pull/4572/commits/ec47746eac307caebd0172b02835f2cec610107c
For this we will depend on the NAD controller, even for the default network:
https://github.com/ovn-org/ovn-kubernetes/pull/4533
On that PR, commit `Provide NAD controller access to the default network controller`: …
> Remove PreStart from NetworkController interface

- test/scripts/e2e-kind.sh
Otherwise github terminates the job on timeout, doesn't give a chance to ginkgo to print status and we don't know why the timeout happened.
> Set shard-conformance timeout lower tham github timeout

- docs/features/multiple-networks/multi-homing.md
- go-controller/pkg/cni/types/types.go
- go-controller/pkg/ovn/secondary_localnet_network_controller.go
- go-controller/pkg/util/multi_network.go
- test/e2e/localnet-underlay.go
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
This PR introduces a network name alias to use when configuring the localnet networks.
By using this alias, the user can create multiple networks - on different vlans - without having to reconfigure the node's OVN bridge mappings. Essentially, the use can provide a **single** mapping and piggy-back multiple physical configurations in it.
Users in OpenShift use kubernetes-nmstate to configure these mappings; this way, they get to skip provisioning multiple policies. 
In this PR we are adding an alias to the network name attribute in the localnet logical switch port mandatory options.
By doing that, we can create multiple networks pointing at the same OVS bridge without having to provision additional bridge …
> OCPBUGS-31679: localnet, multi-homing: introduce localnet alias

- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods_test.go
The IPs of the pods that are on hybrid overlay nodes shall also be added to the namespace address_set.
Fixes https://issues.redhat.com//browse/OCPBUGS-42244, https://issues.redhat.com/browse/OCPBUGS-42605
1. Create a hybrid overlay enabled cluster.
2. Create pods on hybrid overlay nodes.
3. check if the pod IPs are added to the namespace address_set.
```release-note
```
> Add hybird overlay pod IPs to the namespace address_set

- go-controller/hack/test-go.sh
- go-controller/pkg/node/vrfmanager/vrf_manager.go
- go-controller/pkg/node/vrfmanager/vrf_manager_test.go
This PR fixes repair method of VRF manager which is buggy and it incorrectly removes valid VRF device associated with a user defined network while running reconcile loop.
> Fix incorrect removal of VRF device

- .github/workflows/test.yml
- test/e2e/network_segmentation.go
- test/e2e/network_segmentation_services.go
Previous PR https://github.com/ovn-org/ovn-kubernetes/pull/4625 did not include network isolation testing to select the correct CIDR IP family(s) based on the deployed cluster. this corrects that. Additionally add CIDR family selection to the network isolation services test and add a single stack ipv4 CI lane 
Fixes #
```release-note
```
> add single-stack ipv4 lane and correctCIDR family selection for udn network isolation testing 

- test/e2e/network_segmentation.go
It was seen in downstream that this container can take longer than a second for its http server to start sometimes:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2314/pull-ci-openshift-ovn-kubernetes-master-e2e-gcp-ovn-techpreview/1849904878739001344
Therefore add a startup probe to give it a few seconds to fully start, then run liveness probe. The test doesn't check for at least 8 seconds (claimed in the comments) that the container never restarted, so this should be fine to finish start up probe and get a few iterations of liveness probe in.
> Adds startup probe to UDN e2e

- .github/workflows/test.yml
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
Enable IP forwarding on the UDN management interface for IPv4 enabled networks. IPv6 forwarding is
globally enabled.
Disable IP forwarding in the SGW UDN lane to catch any potential issues caused by the restricted forwarding.
> Enable IP forwarding on the UDN management interface

- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
Without this fix, ovn-controller would spam:
2024-10-28T16:58:44.283Z|04438|pinctrl|WARN|Invalid IPv6 prefixes:
> Only configure IPv6 RAs when ipv6 mode enabled

- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/network-attach-def-controller/network_manager.go
This PR ignores `topology net managed` errors on the initial all networks sync of the cluster manager controllers.
Only the `secondaryNetworkClusterManager` - which is created by the cluster controller manager, and executed in the control plane pods - actually returns this type of error.
Fixes #
1. Configure the bridge mappings for the localnet network
2. Create a localnet network without subnets.
3. Attach a pod to the localnet network.
4. Restart the ovnkube-control-plane pods
To configure the mappings for the localnet network you can (upstream):
```sh
for pod in $(kubectl get pods -novn-kubernetes -l "app=ovs-node" --no-headers -ocustom-columns=":metadata.name"); do 
kubectl -n ovn-kubernetes exec $pod -- ovs-vsctl set open . external-ids:ovn-bridge-mappings="physnet:breth0,tenantblue:b …
```
> OCPBUGS-43454: Ignore cluster manager `topology not managed` errors for localnet  with no subnets

- CODEOWNERS
> Fixes auto-assignment of reviewers after repo migration

- go-controller/pkg/clustermanager/node/node_allocator.go
TunnelID Allocator is only present for L2 UDNs. It is nil otherwise, while releasing we forgot to check for the L2 Primary UDN condition and this leads to panic:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1e54748]
goroutine 77 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x2cbd3d8, 0x441f7e0}, {0x2458780, 0x42641b0}, {0x441f7e0, 0x0, 0x10000c0017b41c0?})
/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:89 +0xee
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x5?}) …
```
> Fix Panic in ClusterManager: Release IDs only for Primary L2 UDNs

- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- test/e2e/network_segmentation_services.go
Since in L2 UDNs, multiple networks
are set on the rtos-/stor- ports
when lb_force_snat_ip is set to router-ip
it picks the lexicographically sorted
subnet IP to perform the SNAT which
breaks services on L2.
In this fix we will start using the
joinIP to explicitly SNAT traffic to.
Pinning to joinIP is what we used to do before
except we had to use router-ip to
deal with the following case:
ext->ovn-workerIP:NodePort backed by
ovn-worker2 host networked pod:
ext->ovn-worker->br-ex->GR(DNAT to ovn-worker2)->
GR(SNAT to joinIP)->send it back to br-ex->underlay
->ovn-worker2
..
here traffic goes out with joinIP which will
break this flow.
But in UDNs we don't support host-networked
pods yet, much less host-networked-pod backends
to services. So when that support gets added
we must ensure to …
> UDN: L2: Fix router ip on multiple networks set on LRP case

- go-controller/pkg/allocator/ip/subnet/allocator_test.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/persistentips/allocator.go
- go-controller/pkg/persistentips/allocator_test.go
In case the `ovnkube-control-plane` pod is restarted,
(for example, node restart, upgrade, or any pod restart reason),
the ipam claim Sync function creates an array of all the ipams
belonging to a specific network, and used named allocator `AllocateIPs`
method to allocate them, so the allocator will reflect the current
cluster state.
The problem is `AllocateIPs` allows to allocate only one IP per given subnet,
so once it is used for all the IPs in the network at once, it will fail,
causing the control plane to have a crash loop.
Fix it by calling `AllocateIPs` per each claim on its own.
The claims were already created correctly, so each claim on its
own is safe to call `AllocateIPs`.
Add unit test to show the relevant assertion.
Fixes #
Seen by deleting the pod while there were 2 ipam …
> ipam: Fix init flow in case there are sticky ips in the system

- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
Following https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4604, fix typo in NAD validation error message.
Fixes #
> NAD validations: Fix typo in error message

- go-controller/pkg/libovsdb/util/router.go
- go-controller/pkg/libovsdb/util/router_test.go
- go-controller/pkg/util/kube.go
(Continuing from https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4390, which I can't seem to reopen)
`CreateOrReplaceLogicalRouterStaticRouteWithPredicate` already does duplicate detection on static routes based on the predicate it gets as input, but the code in `CreateDefaultRouteToExternal` calls it with a predicate that is too restrictive: it checks against next hop, IP prefix and policy (src/dst). In corner cases where the gateway IP has changed (https://issues.redhat.com/browse/OCPBUGS-32754, for unknown reason), `CreateDefaultRouteToExternal` will add its static route to the gateway IP; the existing route, pointing to the incorrect gateway router IP, will stay in nbdb.
Simply removing the check against the next hop in the predicate is not enough, since we would wipe out the …
> Fix predicate for cluster subnet route to gateway router

- .github/workflows/test.yml
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_multicast.go
- go-controller/pkg/ovn/base_network_controller_policy.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/master_test.go
- go-controller/pkg/ovn/multicast_test.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/namespace.go
- go-controller/pkg/ovn/namespace_test.go
- go-controller/pkg/ovn/pods_test.go
- go-controller/pkg/ovn/policy_stale_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
- test/e2e/multicast.go
- test/e2e/network_segmentation.go
- test/scripts/e2e-cp.sh
This adds:
- cluster and router port groups to user defined L2/L3 primary networks
- multicast support to user defined L2/L3 primary networks
- hairpin ACLs allowing hairpin service traffic for user defined L2/L3 primary networks too
Cluster-wide port group management routines have been moved to the base network controller and now are used by secondary network controllers too.
Multicast ACL management routines have been moved to the base network controller and now are used by secondary network controllers too.
E2e and unit tests have been adapted to run for both default and primary UDN networks for the features mentioned above.
Unit and end to end tests have been adapted/created.
```release-note
None
```
> Add support for multicast in user defined networks.

- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/policy_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
The namespace is currently not getting configured in ovnk and ovn for user defined network when multi network policy is disabled for the cluster. But multinet policy is not a requirement for UDN network policies, hence fixing it so that namespaces get configured for those namespaces on secondary controller and network policies can be created for the same.
> Ensure UDN namespace is configured when MultiNetPolicy is disabled

- go-controller/pkg/node/gateway_udn.go
From the documentation of the PollUntilContextTimeout (used by startupWaiter):
// ConditionWithContextFunc returns true if the condition is satisfied, or an error
// if the loop should be aborted.
In the readyFunc callback we were incorrectly returning an error if the flows couldn't be found in the current try, causing the waiter to bail early, essentially never retrying.
Change this to log the error inside the callback instead of returning it.
Fixes #
> gateway_udn: Don't bail out early when waiting for UDN patch ports.

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/openflow_manager.go
The netConfig map is accessed from multiple threads (e.g., for UDNs).
Fixes #
> gateway: Access default net config under bridge lock.

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_nftables.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/openflow_manager.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
- go-controller/pkg/node/vrfmanager/vrf_manager.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/gateway/gateway.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
- go-controller/pkg/util/util.go
- test/e2e/network_segmentation_services.go
This PR adds support for external to NodePort/ExternalIP/LoadBalancer service traffic.
It marks packets destined to externally exposed services with a network's specific value.
Traffic is then routed to the appropriate UDN using ip rules and openflows on breth0. 
This PR doesn't add support for ITP=Local.
It depends on:
- the OVN conditional SNAT fix in OVN for ETP=Local services: https://issues.redhat.com/browse/FDP-787
56d95bbfeeff378c801aada363175625d11ac867 is not strictly related to the changes in this PR, it fixes a bug for default service access flow cleanup.
> UDN: Support external to service in LGW

- go-controller/pkg/ovn/base_network_controller_secondary.go
The previous condition was incorrect and was ignoring host-networked pods only when `addPort` was false, additionally it didn't ignore cluster-networked pods that do not want a port configured(`addPort==false`). 
This means that the controller tried to configure the logical port for new host-networked pods and on updates for cluster-networked pods. 
Fix the condition by exiting when the pod is host networked **or** `addPort` is false.
This is likely a mistake from reversing the default network condition:
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/d20b22110a912a244f4cd42f0969df60eaf434fc/go-controller/pkg/ovn/ovn.go#L166
The issue can be reproduced by creating a host networked pod in a UDN namespace:
```
E1125 13:40:08.269965   17921 obj_retry.go:671] Failed to update *v1.Pod, …
```
> Do not configure ports for host-networked pods in secondary networks

- go-controller/pkg/factory/mocks/NodeWatchFactory.go
- go-controller/pkg/factory/types.go
- go-controller/pkg/network-attach-def-controller/network_attach_def_controller.go
- go-controller/pkg/network-controller-manager/node_network_controller_manager_test.go
Following #4612 this PR add support for the NAD controller to take in account CUDN objects when looking for active namespace in a namespace, similar to the UDN case introduced by  https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4662.
Fixes #
> node network controller: Add CUDN check to GetActiveNetworkForNamespace

- dist/templates/k8s.ovn.org_clusteruserdefinednetworks.yaml.j2
- dist/templates/k8s.ovn.org_userdefinednetworks.yaml.j2
- go-controller/pkg/crd/userdefinednetwork/v1/shared.go
This PR changes the UserDefinedNetwork & ClusterUserDefinedNetwork CRDs validations, 
making them fit IPv4 and IPv6* minimum MTU according to RFC [1] [2].
[1] https://datatracker.ietf.org/doc/html/rfc791
[2] https://datatracker.ietf.org/doc/html/rfc2460
Fixes #
The IPv6 validation require some CEL verbs that will be avaiable once the project transition to use kubernetes 1.31, tracking issue [1].
[1] https://github.com/ovn-org/ovn-kubernetes/issues/4607
```release-note
NONE
```
> crd, udn: Improve minimum MTU validations

- go-controller/pkg/node/controllers/egressservice/egressservice_node.go
- go-controller/pkg/node/egress_service_test.go
- go-controller/pkg/util/iptables.go
Discovered while porting to nftables; there was a bug in the `FakeIPTables` implementation used for unit tests (when you called `List()` it would mutate its own internal state rather than only mutating its return value), and the EgressService controller startup cleanup code only worked correctly in the presence of that bug. (It passed the entire rule returned from `List()`, including the "`-A OVN-KUBE-EGRESS-SVC`", as the argument to `Delete()`, which ended up working with `FakeIPTables` because it had accidentally modified its internal state to include that string as part of the rule, but with real iptables it would have ended up trying to do `iptables -D OVN-KUBE-EGRESS-SVC -A OVN-KUBE-EGRESS-SVC -s 10.128.0.3 ...`.)
But this code only runs when ovnkube-node starts up on a node that …
> correctly remove stale EgressService rules at startup

- go-controller/pkg/allocator/ip/subnet/allocator.go
- go-controller/pkg/allocator/ip/subnet/allocator_test.go
- go-controller/pkg/clustermanager/pod/allocator_test.go
- go-controller/pkg/clustermanager/secondary_network_unit_test.go
- go-controller/pkg/ovn/logical_switch_manager/logical_switch_manager.go
- go-controller/pkg/persistentips/allocator_test.go
The `AllocateIPs` method name is misleading; it receives a slice of IPs as parameter, which leads the user to think that it can allocate the IPs in the slice in a single subnet - i.e. for subnet 10.0.0.0/24, it could allocate IPs 10.0.0.2 and 10.0.0.3.
That is not the case: that function allocates a **single** IP address in each of the subnets the IP allocator for said network manages. For instance, on a dual-stack network, it could handle the following subnets: 10.0.0.0/24 and fd10::/64. The function could then the invoked with ips=10.0.0.2,fd10::2 to allocate **one** IP in each of the two subnets managed by the IP allocator.
Fixes #
I've renamed the method, and corrected its docstring, in hope of making its intended usage clearer for future users.
> ip allocator: rename AllocateIPs method

- go-controller/pkg/ovn/egressip.go
- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/pods_test.go
currently when creating egressIP in a dualstack cluster regardless of if the egressip is ipv4 or ipv6 when disable-snat-multiple-gws is set the code removes both ipv4 and ipv6 snats from the database. This means that the pod will not be able to communicate with the cluster correctly becuase the Gateway Router is missing an SNAT and the traffic will be dropped.
Additionally the testing looks a little different from the others because we do not correctly setup dualstack clusters when running unit tests
fixes: https://issues.redhat.com/browse/OCPBUGS-37193
Fixes #
```release-note
```
> fixes overzealous deletion of SNAT in egressIP

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/kubevirt/pod_test.go
- go-controller/pkg/libovsdb/ops/model.go
- go-controller/pkg/libovsdb/ops/switch.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
Currently all pods have the LSP.Enabled option set to nil (which later 
translates to &true) by default.
During live-migrationof kubevirt pods, in order to prevent unneeded 
packet loss the lsp.Enabled of the migration pods (source and target) 
need to be as follows:
1. until target pod is domain ready: source pod lsp is enabled, target
pod lsp is disabled.
2. when target pod is domain-ready: source pod lsp is disabled, target
pod lsp is enabled.
This switch significantly reduces the migration downtime to <0.5s (see details below).
This PR also handles the scenario of a failed migration, where the lsp 
of the source pod needs to be re-enabled.
Note: 
Currently this change is restricted to VM with secondary/primary UDNs, and
layer2 topology.
Fixes #
e2e will be introduced in a follow-up PR …
> VM migration: Reduce downtime using LSP Enabled

- go-controller/pkg/factory/factory.go
Introducing small delay before waiting for cache sync prevents 100ms wait on each
informer creation. There are up to 12 informers in factory that adds up to 1s wait on
each factory creation. 
On my machine introducing small delay reduces tests time from 15m44.683s to 13m56.218s.
Fixes #
> unit tests: speed up by small sleep before cache sync wait

- go-controller/cmd/ovnkube-trace/ovnkube-trace.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/management-port-dpu.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/egressfirewall_test.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
Today ovnkube-controller relies on ovnkube-node to annotate the mac address so that it can properly program the OVN mgmt port. In practice with UDN, this means cluster manager creates the node and allocates some subnet info to the node, both the node and the ovnkube-controller side get updates, but ovnkube-controller fails to program the first time because it is waiting for the node side to configure the mac address.
This patch changes the behavior of ovn-kubernetes to calculate the MAC address for the management port from the mgmt port IP address of the first subnet for the network. For backwards compatibility (on default network), it will first attempt to read the node annotation, and if it no mgmt MAC exists, it will derive it from the mgmt IP of the subnet.
Note the DPU code already …
> Calculates mgmt port MAC rather than storing

- go-controller/pkg/ovn/base_network_controller_secondary.go
Delete path was printing removing the pod for every network controller like:
I1009 23:16:54.375327    8134 base_network_controller_secondary.go:287] [e2e-test-endpointslices-mirror-e2e-hg7st/backend-0] addLogicalPort for NAD e2e-test-endpointslices-mirror-e2e-hg7st/gryffindor took 3.202984ms, libovsdb time 2.456846ms
I1009 23:16:54.377764    8134 base_network_controller_secondary.go:416] Deleting pod: e2e-test-endpointslices-mirror-e2e-hg7st/backend-0 for network e2e-test-network-segmentation-e2e-b66l5.gryffindor
I1009 23:16:54.378006    8134 base_network_controller_secondary.go:416] Deleting pod: e2e-test-endpointslices-mirror-e2e-hg7st/backend-0 for network e2e-test-endpointslices-mirror-e2e-89gg6.gryffindor
I1009 23:16:54.378095    8134 base_network_controller_secondary.go:416] …
> Improves pod deletion with user defined networks

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
Instead of failing ignore EndpointSlices without a service label set.
These custom, user created slices should be ignored.
> UDN Gateway: Ignore EndpointSlices without a service label

- .github/workflows/test.yml
- test/Makefile
- test/scripts/traffic-flow-tests.sh
This pull request integrates ocp-traffic-flow-tests into the existing GitHub E2E workflows. The control tests can now be executed as a standalone lane or added to existing targets via the "traffic-flow-tests" matrix parameter. This allows flexibility in running the tests either independently or in conjunction with other pipelines.
External tests and secondary network support are not yet implemented and will be considered in a future pull request.
Currently, the traffic flow tests use a specific commit from the repository https://github.com/wizhaoredhat/ocp-traffic-flow-tests.git. 
Next steps to look into, after this pull-request:
- External and secondary network tests
- Add bandwidth thresholds that would be reasonable for Github
- Move repo to ovn-kubernetes org
Fixes: …
> Add support for ocp-traffic-flow-tests in GitHub workflows

- test/e2e/kubevirt.go
Some time echoserver in VM could take more than 20s to start up, so increase timeout to 60 seconds to avoid flakiness.
> fix flaky VM live migration e2e case

- .github/workflows/test.yml
'ubuntu-latest' now references ubuntu 24.04.
Previously, it referenced 22.04.
Potential short term measure to unblock GH CI.
Failures for ubuntu 24.04 can be seen here: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4914
> Statically set GH runner image to ubuntu 22.04 for tests

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/ovn/egressip.go
- test/e2e/egressip.go
Fixes #
Previous to this change, UDN EIP tests were not running in network segmentation lanes.
> Add EgressIP E2Es to Net Seg lanes

- go-controller/pkg/cni/helper_linux.go
ovs-doca requires mtu_request to be set on ports metadata for fragmented packets
Fixes #
> helper_linux: Set mtu_request for ovs-doca ports

- .github/workflows/test.yml
Reverts ovn-kubernetes/ovn-kubernetes#4920
the node-ip-migration lane seems to be permafailing after the new ubuntu update happened.
Credit to @kyrtapz I simply only clicked the revert button here, he did the debugging.
> Revert "Fix for unexistent package msbuild in latest ubuntu images"

- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/management-port-dpu.go
- go-controller/pkg/node/management-port.go
- go-controller/pkg/node/management-port_dpu_test.go
- go-controller/pkg/node/management-port_linux.go
- go-controller/pkg/node/management-port_linux_test.go
- go-controller/pkg/node/node_ip_handler_linux_test.go
If the default network is advertised, inhibit:
- pod IP to node IP SNAT on egress in LGW mode
- source IP to managament port IP SNAT on ingress (through secondary nic)
Currently based on top of https://github.com/ovn-org/ovn-kubernetes/pull/4472 and https://github.com/ovn-org/ovn-kubernetes/pull/4533
> SDN-5139: Direct ingress for default network in LGW mode with route advertisements 

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/ovn/controller/services/services_controller.go
A service is added to the cache in `AddEndpointSlice` before the rules are added.
If `addServiceRules` fails the newly added cache entry should be removed to allow for a proper retry.
> Remove service from cache on add failure

- go-controller/pkg/config/config.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/default_node_network_controller_test.go
- go-controller/pkg/node/node_ip_handler_linux.go
If EncapIP is configurated, it means it is different from the node's primary address. Do not update EncapIP when node's primary address changes.
Fixes #
```release-note
```
> Do not update EncapIP if it is configured

- go-controller/pkg/node/default_node_network_controller.go
This PR addresses 2 issues in DPU host initialization. 
- new gatewaysetup structure is missing nodeAddress field initialization that is breaking gateway initialization &
- SBDB connection call is inadvertently made for this mode
Fixes #
> Fix issues in DPU host initialization

- test/e2e/network_segmentation.go
This PR improve stability of CUDN e2e tests with the following changes:
- On CUDN deletion, wait for the object to be gone, and avoid pollution the next test with CUDN object.
- In the CUDN primary network already exist test, when CUDN is created wait for status to populate.
- Use random names for CUDN objects to enable running related tests in parallel.
Fixes #
> e2e, CUDN: Improve stability

- .github/workflows/test.yml
- test/e2e/network_segmentation.go
- test/e2e/network_segmentation_policy.go
The NetPol test checks assigned pod IP only against IPv4 subnet which would fail on IPv6 only cluster. This PR fixes it by checking on all valid CIDRs.
> Fix subnet check for assigned pod IPs

- contrib/kind.sh
- dist/templates/rbac-ovnkube-cluster-manager.yaml.j2
- dist/templates/rbac-ovnkube-master.yaml.j2
- go-controller/pkg/controllermanager/controller_manager.go
- go-controller/pkg/libovsdb/ops/router.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/routeimport/route_import.go
- go-controller/pkg/ovn/routeimport/route_import_test.go
- go-controller/pkg/testing/libovsdb/matchers.go
- go-controller/pkg/util/mocks/NetLinkOps.go
- go-controller/pkg/util/net_linux.go
- go-controller/vendor/github.com/go-logr/logr/testr/testr.go
- go-controller/vendor/modules.txt
This commit adds a new controller to import BGP learnt routes into OVN.
The controller runs in ovnkube-controller so it only supports IC
architecture where ovnkube-controller has kernel access on each node.
Networks should register to this controller to have routes imported for
them. Routes are imported into the network's gateway router. Multipath
routes are supported.
The controller subscribes for netlink route events. When a route is
updated, the corresponding network is queued to be sync'ed. A network is
also sync'ed when registered to the controller.
Synchronizations are delayed by a small amount of time to prevent a
series of consecutive route updates so synchornize the same network
twice. Synchronizations apply the difference between current and desired
state.
The controller …
> Import learnt BGP routes into OVN

- go-controller/pkg/clustermanager/userdefinednetwork/controller.go
- go-controller/pkg/clustermanager/userdefinednetwork/controller_test.go
- test/e2e/network_segmentation.go
As of today the `NetworkReady` condition indicated a NAD has been created.
And not necessarily that the underlying network is ready to work with,
because it require other internal components to act (e.g.: set ovs ports,
ovn flows, etc..).
Rename the `NetworkReady` condition type to `NetworkCreated` so it describe
better what it indicates.
This change enable introducing alternative `NetworkReady` condition that
provider actual indication a UDN network is ready, and that other
internal component acted successfully.
Fixes #
> UDN: Rename NetworkReady condition to NetworkCreated

- go-controller/pkg/ovn/base_network_controller_namespace.go
- go-controller/pkg/ovn/base_network_controller_namespace_test.go
When multinetwork policies support is disabled WatchNamespaces should run to completion for primary UDNs.
This was not happening because a primary UDN is also a secondary network.
cc: @dceara
> Fix WatchNamespaces for UDNs

- go-controller/pkg/node/controllers/egressservice/egressservice_node.go
- go-controller/pkg/node/egress_service_test.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/gateway_shared_intf.go
Switch Egress Services over to nftables. This code is mostly separate from all the other iptables code. (Actually... I'm pretty sure the existing reference to `egresservice.Chain` in `gateway_shared_intf.go:SyncServices` was incorrect, and would just cause it to flush all rules in `egressservice.Chain`. That only runs at startup, and I guess the ordering must have been such that it ran before the egressservice startup repair code, which I guess explains why #4868 wasn't a problem...)
(includes one commit from #4890, which can merge either here or there...)
> Migrate EgressService rules from iptables to nftables

- helm/ovn-kubernetes/Chart.yaml
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/charts/ovn-ipsec/templates/daemonset.yaml
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/ovnkube-control-plane.yaml
- helm/ovn-kubernetes/charts/ovnkube-db/templates/deployment.yaml
- helm/ovn-kubernetes/charts/ovnkube-identity/templates/ovnkube-identity.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu-host/templates/ovnkube-node-dpu-host.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu/templates/ovnkube-node-dpu.yaml
- helm/ovn-kubernetes/charts/ovnkube-node/templates/ovnkube-node.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
- helm/ovn-kubernetes/charts/ovs-node/templates/ovs-node.yaml
- helm/ovn-kubernetes/templates/_helpers.tpl
- helm/ovn-kubernetes/templates/ovn-setup.yaml
This is a backport of https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4521 to the release-1.0 branch.
It also includes https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4494.
@EvenChang  @crnithya : Can this PR be folded into https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4761/ since it needs it ?
This patch introduces a conditional inclusion of image pull secrets across various daemonsets and deployments within our Helm charts. Users can now specify the
'imagePullSecretName' in the 'global' values to include this secret. This flexibility allows for secure pulling of images from private repositories when required.
Example usage in values.yaml:
```yaml
global:
imagePullSecretName: my-registry-secret
```
Documentation reference on using `imagePullSecrets`: …
> Helm image secrets -- backport to release-1.0

- contrib/kind-common
- test/e2e/kubevirt.go
ManagedTap binding name was decided to be `l2bridge`,  use it accordingly.
Fixes #
> managedTap: Use the new bridge type name

- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/zone_interconnect/zone_ic_handler.go
- test/e2e/network_segmentation.go
When default network controller (DNC) restarts and a sync is invoked, it may not exclude transit switches that support different L3 networks when attempting to cleanup stale Node switches.
Therefore, connectivity between Nodes will be impacted for Pods attached to L3 networks because its transit switch maybe removed during DNC sync.
Fixes # https://issues.redhat.com/browse/OCPBUGS-44487
> OVN DNC: ignore all transit switches when cleaning up stale Nodes OVN switch

- test/e2e/network_segmentation.go
This PR fixes the test "when primary network exist, UserDefinedNetwork status should report not-ready" to use the right IP family according to env.
Fixes #
> e2e,udn crd: Use the right IP family according to env

- go-controller/pkg/node/node_ip_handler_linux.go
This PR fixes the issue of host-cidrs annotation missing from DPU Hosts. This is set during ovnkube-node-dpu initialization
Fixes #
> Add missing host-cidrs annotation for DPU Host

- go-controller/pkg/ovn/base_network_controller_pods.go
For layer 2 UDNs it is expected that ovnkube-controller will process the pod with the annotation missing while waiting for cluster manager to allocate it. Suppress the error in that case.
> Suppress layer 2 missing pod anno errors

- go-controller/pkg/ovn/secondary_layer3_network_controller.go
Without this the error for missing annotations will not be suppressed and then false positive errors will be reported.
> Fix missing error wrap on IC remote node add

- go-controller/pkg/node/gateway_egressip.go
When making a call to netlink to retrieve a links
addresses, netlink will return the addresses
and group them by at least the addresses scope.
It will return addresses grouped by scope - host, link and global scope.
Therefore if the EIP address assigned to the ext bridge to support EIP for UDN is scope host, and OVN Kube restarts, it may select the EIP address as the primary IP address.
Fixes #
> UDN EIP IP: change scope from link to global

- dist/images/Dockerfile.fedora
- test/e2e/external_gateways.go
This picks up the following relevant bug fixes:
https://issues.redhat.com/browse/FDP-906
"ovn-controller: lib/ovsdb-idl.c:3596: assertion row->new_datum != NULL failed in ovsdb_idl_txn_write__()"
6448f5e364 pinctrl: Skip non-local mac bindings in run_buffered_binding().
ea35347320 pinctrl: Skip deleted mac bindings in run_buffered_binding().
33a6ae53f4 pinctrl: Use correct map size in pinctrl_handle_put_fdb().
8eaa7d5991 controller: Fix "use after free" issue in statctrl_run().
8579859f51 mac-cache: Properly handle deletion of SB mac_bindings.
https://issues.redhat.com/browse/FDP-752
"ovn-northd IPAM incorrectly reports duplicate IP when part of excluded_ips"
2a24b03f7f ipam: Do not report error for static assigned IPs.
https://issues.redhat.com/browse/FDP-786
"When an ECMP symmetric …
> Dockerfile.fedora: Bump OVN to ovn24.09-24.09.1-10.fc41

- test/e2e/network_segmentation.go
- test/e2e/network_segmentation_endpointslices_mirror.go
This should fix a flake where the cluster UDN status was expected to be updated straight after creating a namespace:
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/acc803c79e4517975f70f7e315a3f09002c739b2/test/e2e/network_segmentation.go#L1138-L1151
The PR includes an alternative solution to: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4967.
Refactored the code to use a dynamic client instead of parsing raw kubectl output. I opted not to use udn/cudn client as this makes the tests more generic and portable.
> Refactor and fix UDN/CUDN readiness checks

- go-controller/pkg/config/config.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
disable-SNAT-Multiple-GWs means we use per pod SNATs
instead of subnet SNAT at the GR. This option is only
relevant to default network as of this PR. We are removing
the support for per pod SNAT due to two reasons:
1) VM Live migration on L2 UDNs needs the older SNAT for the
pod to the present on the older node which is hard to keep
around else some traffic will leave with podIP from the old
node immediately after live migration has finished
2) lots of SNATs cannot be good for scale, a SNAT per network
subnect sounds better.
3) ICNI is the only feature that uses per pod SNAT which is not
supported on UDNs so we don't need that anyways
> Remove per-pod-SNAT support for UDNs

- docs/features/multiple-networks/mirrored-endpointslices.md
- go-controller/pkg/clustermanager/endpointslicemirror/endpointslice_mirror_controller.go
- go-controller/pkg/clustermanager/endpointslicemirror/endpointslice_mirror_controller_test.go
- go-controller/pkg/testing/kube.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
Label values have a length limit of 63 characters.
Use annotations for 'k8s.ovn.org/source-endpointslice' and 'k8s.ovn.org/endpointslice-network'.
Keep using labels where possible to enable labelselector logic.
> Use annotations in mirrored EndpointSlices for potentially long values

- go-controller/pkg/config/config.go
We use PrepareTestConfig to set the logging level to 5, however that was not taking effect for klog all the time. This results in some unit tests only printing libovsdb logs, and regular klog level lines. We miss a ton of debug logs required to investigate unit tests failures.
> Unit tests: set klog level explicitly

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/util/util.go
- go-controller/pkg/util/util_unit_test.go
Do not rely on the active network while removing the EndpointSlice from the nodeport watcher as there is no guarantee that the network is still there.
> Do not rely on the active network while removing the EndpointSlice

- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/util/util.go
It's noticed NAD is deleted even before handling NetPol delete event which causes NetPol deletion never happened and error is always thrown upon retries. This skips such primary network error and proceeds with deleting netpol object.
> Fix race between NAD and NetPol deletions

- go-controller/pkg/ovn/egressip.go
When a single ovnkube-controller manages the NBDB for multiple nodes, such as without IC or IC with multiple nodes per zone, the predicate search for NATs to remove would accidentally remove egress IP SNATs that were not part of the status being removed. For example in the test:
EgressIP UPDATE should update OVN on EgressIP .spec.egressips change interconnect disabled; non-ic - single zone setup
The test will:
1. create node 1 and 2, with egress ip .101 and .102, respectively
2. change the egress ip on node 1 to be .103
The test would flake because the SNAT for .102 would be missing for node 2. The reason this happens is because when the egress IP status is updated for .103 to be added on node1:
1. the code will call e.deletePreviousNetworkPodEgressIPAssignments
2. the code will then call …
> Fixes SNAT removal with egress IP

- dist/images/Dockerfile.ubuntu.arm64
- dist/images/daemonset.sh
- dist/images/ovnkube.sh
- dist/templates/ovnkube-master.yaml.j2
- dist/templates/ovnkube-node.yaml.j2
- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/config/config.go
- go-controller/pkg/config/config_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/default_node_network_controller_test.go
- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/node_ip_handler_linux.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/master.go
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu/templates/ovnkube-node-dpu.yaml
- helm/ovn-kubernetes/charts/ovnkube-node-dpu/values.yaml
- helm/ovn-kubernetes/templates/_helpers.tpl
- helm/ovn-kubernetes/templates/rbac-ovnkube-node.yaml
- helm/ovn-kubernetes/values.yaml
**What this PR does and why is it needed**
(cherry picked from PR https://github.com/ovn-org/ovn-kubernetes/pull/4634)
> [release-1.0]: Fix several issues for supporting DPUs

- go-controller/pkg/node/udn_isolation.go
- go-controller/pkg/node/udn_isolation_test.go
> UDN isolation: trigger update on open-default-ports annotation change.

- go-controller/pkg/clustermanager/clustermanager.go
- go-controller/pkg/clustermanager/node/subnet_allocator.go
- go-controller/pkg/clustermanager/secondary_network_cluster_manager.go
- go-controller/pkg/controllermanager/controller_manager.go
- go-controller/pkg/controllermanager/node_controller_manager.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/handler.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
- go-controller/pkg/node/node_ip_handler_linux_test.go
- go-controller/pkg/node/openflow_manager.go
- go-controller/pkg/node/ovn_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/testing/exec.go
Instead of using a single (federated) event handler for the shared kubernetes index informer create a pool of handlers.  Ensures that all secondary network controllers register their object event handlers with the same entry in the pool.  This allows load sharing between secondary network controllers.
The change is mostly limited to the `factory` package but requires shallow cloning of the watch factory when secondary network controllers are created.
All existing tests must pass.  The change should be transparent from a functionality point of view.
> Increase scalability of secondary network controllers by multiplexing informers.

- go-controller/pkg/networkmanager/nad_controller.go
- go-controller/pkg/networkmanager/nad_controller_test.go
- go-controller/pkg/networkmanager/network_controller_test.go
- go-controller/pkg/util/multi_network.go
On cluster manager restart, there wouldn't be a need to update the network ID annotation of existing networks but we were not setting the annotated ID on NetInfo. This failed to ensure the network and in turn made the controller believe the network was stale, cleaning up the annotated ID on the nodes causing the network to definitely not start and a crash-loop.
> Set network ID on netInfo even when already annotated

- go-controller/pkg/factory/factory.go
:disappointed: 
This is the last factory variable in the `WatchFactory` struct.
> Clone frrFactory in ShallowClone

- go-controller/pkg/factory/factory.go
Commit 6dda0b511d26 ("factory: Bump the event queue size to 1K.") increased the event queue size to 1K events.  However, in combination with fe17136cfd3a ("factory: Reduce contention on informer locks.") which configures 201 internal informers this might end up using too much memory in cases when controllers cannot consume events as fast as they're queued by the kube API.
For each kubernetes API object type we consume:
N_internal_informers x N_queues x N_events x sizeof(event)
memory.
That currently translates to:
N_internal_informers = 201
N_queues = 15
N_events = 1000
sizeof(event) = 32B
=> ~92MB of memory per object type
Given that ovn-kubernetes processes need to be informed about multiple object types this can grow to a significantly large number when controllers that are supposed to …
> factory: Set default event queue size to 100.

- contrib/kind-helm.sh
- docs/developer-guide/image-build.md
- docs/installation/launching-ovn-kubernetes-with-helm.md
- helm/ovn-kubernetes/Chart.yaml
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/README.md.gotmpl
- helm/ovn-kubernetes/values-multi-node-zone.yaml
- helm/ovn-kubernetes/values-no-ic.yaml
- helm/ovn-kubernetes/values-single-node-zone.yaml
Update documentation to replace a bunch of ovn-org to ovn-kubernetes.
> Fix doc: Replace ovn-org with ovn-kubernetes to reflect repo move

- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/retry/obj_retry.go
- go-controller/pkg/util/multi_network.go
- test/e2e/multihoming.go
Previously, if a new NAD was added to an existing network after a pod referencing it, the pod would never start. This is fixed by reconciling pending pods when the secondary network controller reconciles a new NAD.
The e2e test is failing without the controller change, the pod never becomes ready.
cc: @trozet @jcaamano
> Reconcile pending pods when a NAD is added to an existing network

- go-controller/pkg/clustermanager/pod/allocator.go
- go-controller/pkg/clustermanager/userdefinednetwork/controller_test.go
- go-controller/pkg/ovn/base_network_controller.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_secondary_layer2_network_controller.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/pods.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/types/const.go
- go-controller/pkg/util/multi_network.go
Fixes issues where we are calling getActiveNetworkForNamespace on secondary UDN controllers. There is no point in doing this and can cause errors for resources like pods if we are handling pods slowly and the namespace has already been deleted. Remember secondary UDN/NAD can use other namespaces, so NAD/network controller may still be functional trying to add pods for another namespace and that namespace may no longer exist.
Fixes issues where we are starting services and multinetworkpolicy controllers when we shouldn't be.
There were duplicate functions for GetNetworkRole, with ambiguous logic that needed a note to caution developers against when to use it. Consolidated the function into a single util, and made the logic more explicit. Now if a GetNetworkRole is called on a pod that the …
> Fix getting active network secondary udn

- .github/workflows/chart-release.yaml
- .github/workflows/docker.yml
- contrib/kind-helm.sh
- docs/developer-guide/image-build.md
- docs/installation/launching-ovn-kubernetes-with-helm.md
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/README.md.gotmpl
This change takes advantage of the "Helm Chart Releaser" in GitHub. Information about this feature is located at: https://github.com/marketplace/actions/helm-chart-releaser
This is a backport of https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4971 to release-1.0 branch.
> [release-1.0] Add manual chart-releaser workflow

- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/base_network_controller_secondary_test.go
In our add handler code we process existing items. A long time ago a retry loop was added to retry processing failed existing items. 
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/go-controller/pkg/factory/factory.go#L1308
However, during the retry we never re-list and get the existing items in the cluster. This retry will last up to a minute. This becomes a problem when for UDN, because now with UDN we spin up these controllers dynamically at runtime, not just at OVNK start up.
Therefore, failures in the sync can cause a potential delay of a minute to start a controller, potentially backing up other controllers waiting their turn to start.
As a more general fix, we should examine eliminating this retry loop. However, due to the risk of regression and uncovering some issue …
> Fixes 1 minute delay for primary UDN controllers to start

- dist/templates/k8s.ovn.org_clusteruserdefinednetworks.yaml.j2
- dist/templates/k8s.ovn.org_userdefinednetworks.yaml.j2
- go-controller/pkg/crd/userdefinednetwork/v1/shared.go
Fix UDN and CUDN subnet validation
In the previous validation rule, IPv6 subnets would mistakenly invalidate the CR.
I couldn't find any tests for this in the PR that introduced the changes (https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4933), I'm not sure if that was intended.
> OCPBUGS-49621: Fix UDN and CUDN subnet validation

- dist/templates/k8s.ovn.org_clusteruserdefinednetworks.yaml.j2
- go-controller/pkg/crd/userdefinednetwork/v1/cudn.go
Add missing API validations to ensure the topology and the topology configuration are matching.
Similar to the validation rules on UserDefiendNetwork CRD [[1]](https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/go-controller/pkg/crd/userdefinednetwork/v1/udn.go#L18-L19).
For example: the following spec is invalid and should be blocked by the cluster API:
```
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
...
spec
network:
topology: Layer2
layer3:
...
```
[1] https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/go-controller/pkg/crd/userdefinednetwork/v1/udn.go#L18-L19
Fixes #
> crd, cudn: Ensure matching topology and topology-configuration

- go-controller/pkg/factory/handler.go
Calling unlock in defer will only be executed before return, thus holding all informer locks at the same time.
e.g. if you try to execute Shutdown from 2 threads in parallel, and informers are not iterated in the same order, you get a deadlock.
```
thread1
for inf := [inf1, inf2]
inf.Lock() // locks inf1
```
```
thread2
for inf := [inf2, inf1]
inf.Lock() //locks inf2
```
> factory/handler: avoid deadlock on shutdown.

- CONTRIBUTING.md
- README.md
- REVIEWING.md
- docs/governance/CONTRIBUTING.md
- docs/governance/REVIEWING.md
Currently all our documentation is pointing to an archived slack workspace and channel. We need to move it to the new slack_url: https://cloud-native.slack.com/archives/C08452HR8V6
> change slack url to point to the cloud-native workspace

- .github/workflows/test.yml
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/images/crictl.go
- test/e2e/kubevirt.go
- test/e2e/kubevirt/ip.go
- test/e2e/kubevirt/pod.go
- test/e2e/kubevirt/types.go
- test/e2e/multihoming_utils.go
This PR add e2e test to check tcp connection are not broken during live migration for UDN and north/south traffic for primary UDN.
TODO:
- Localnet + IPAM live migration is broken until we don't fix LSP enabled for localnet, let's mark the test.
- We should skip. 
- Fixed with https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4774  
Depends-on:
- https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4773
- https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4774
> kubevirt, e2e, udn: Add north south traffic and tcp connection checks for e/w and n/s.

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/node/linkmanager/link_network_manager.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/util/arp.go
- test/e2e/kubevirt.go
- test/e2e/kubevirt/net.go
After a L2 primary UDN virtual machine is live migrated its ipv4 gateway mac cache is still pointing to the previous node gateway mac from the gateway router LRP.
This PR send a GARP after live migration to update the VM's gateway mac to the new node GR LRP mac address.
This created some utils under pkg/kubevirt to send the GARP and reconcile the gateway and wired up at the layer2 controller so only this controller has code for it.
Closes https://issues.redhat.com/browse/OCPBUGS-48337
It includes tests.
> kubevirt, l2, pudn: reconcile ipv4 gateway mac after live migration

- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/multihoming_test.go
- go-controller/pkg/ovn/ovn_test.go
- go-controller/pkg/ovn/secondary_layer2_network_controller_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
- test/e2e/kubevirt.go
This is the follow up for localnet of layer2 live migration downtime reduction here:
- https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4774
Apart from playing with lsp `Enabled` field for localnet is also needed to remove `Addresses` field to be sure that OVN is removing the L2 lookup table so traffic is steering to the localnet LSP instead of the soon-to-be-removed live migration souirce pod LSP.
Depends on:
- https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4834
TODO:
The test has unit test fixed and also the kubevirt e2e live migration downtime check is reduce to 2 seconds.
> kubevirt, localnet: Reduce live migration downtime.

- go-controller/pkg/factory/factory.go
- go-controller/pkg/factory/handler.go
Using cryptorand ends up making a syscall to udev/random and takes too much CPU since this is called on every enqueue event. We don't need cryptographic random numbers as we are not generating tokens or certificates.
In the future, we should look at implementing a heap and storing queues by size on the heap. That would make it faster than the current method, but for now this is the least risky option.
Reverts PR:  https://github.com/ovn-kubernetes/ovn-kubernetes/pull/3322
@girishmg @Pardhakeswar fyi
Additionally includes a performance fix to limit how many events we need to process on the 201 internal informers we create.
> Improve multiplexed internal informer performance

- go-controller/go.mod
- go-controller/go.sum
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/udn_isolation.go
- go-controller/pkg/node/udn_isolation_test.go
- go-controller/vendor/github.com/moby/sys/userns/LICENSE
- go-controller/vendor/github.com/moby/sys/userns/userns.go
- go-controller/vendor/github.com/moby/sys/userns/userns_linux.go
- go-controller/vendor/github.com/moby/sys/userns/userns_linux_fuzzer.go
- go-controller/vendor/github.com/moby/sys/userns/userns_unsupported.go
- go-controller/vendor/modules.txt
Cgroupv1 nodes won't be able to match on kubelet cgroup path, therefore kubelet checks won't work on such nodes
cgroup check is copied from https://github.com/kubernetes/kubernetes/blob/bfde2edba75c8c00370d0b1a7a82c0988d13f0c6/pkg/kubelet/cm/cgroup_manager_linux.go#L157
It brings quite a lot of dependencies for just 1 cgroup check function, but I am not sure if I want to copy its code and make sure it keeps working
> [UDN: host isolation] check that node uses cgroup v2.

- go-controller/pkg/ovn/gress_policy.go
- go-controller/pkg/ovn/policy_test.go
Fixes a null pointer exception when network policy port has no protocol. If the protocol is missing in the network policy port definition, it should be assumed to be TCP.
Hit the crash downstream in:
https://issues.redhat.com/browse/OCPBUGS-49393
> Handles unspecified protocol in network policy port

- go-controller/pkg/node/udn_isolation.go
We want to use "k8s.io/api/core/v1.ObjectReference" for event reporting. At the same time "k8s.io/kubernetes/pkg/apis/core.ObjectReference" exists.
The fun part is that in default_node_network_controller.go we import
```  
kapi "k8s.io/api/core/v1"
```
and in udn_isolation.go
```
v1 "k8s.io/api/core/v1"
kapi "k8s.io/kubernetes/pkg/apis/core"
```
so when the tested code was moved to another file, it started using the wrong type.
Currently we get an error
"Could not construct reference, will not report event" err="object does not implement the common interface for accessing the SelfLink"
> [UDN: host isolation] Fix node event reporting.

- go-controller/pkg/node/udn_isolation_test.go
Fix issue introduced in 3275d498b4026609effbaaf88a88ff6e43819ad5
```
$ make lint
...
level=info msg="[linters_context/goanalysis] analyzers took 4m3.270244378s with top 10 stages: buildir: 2m29.130860339s, nilness: 5.955006101s, printf: 3.859331341s, fact_deprecated: 3.799388364s, ctrlflow: 3.482855272s, inspect: 3.316943625s, fact_purity: 2.391957936s, S1038: 2.121120295s, gofmt: 2.089813745s, unused: 2.075213702s" pkg/node/base_node_network_controller_dpu.go:1: : # github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node [github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.test] pkg/node/udn_isolation_test.go:364:52: not enough arguments in call to NewUDNHostIsolationManager
have (bool, bool, "k8s.io/client-go/informers/core/v1".PodInformer)
want (bool, bool, …
```
> [UDN: host isolation]: fix lint

- go-controller/pkg/cni/cni.go
I am trying to debug an issue where this error occurs and I dont easily know what pod UIDs that were compared.
Downstream issue; https://issues.redhat.com/browse/OCPBUGS-48760
> Enrich CNI request pod UID error with the mismatched UIDs

- test/e2e/egress_firewall.go
This PR adds e2e test to validate that egressfirewall supports DNS name in caps.
> Add e2e test to validate that egressfirewall supports DNS name in caps

- go-controller/pkg/ovn/egressip_test.go
- go-controller/pkg/ovn/gateway.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/secondary_layer3_network_controller_test.go
In OVN Interconnect topology having dynamic_neigh_routers option on the gateway router will cause mac bindings to expire toward the join switch port. This change disables that option for IC.
> Change dynamic_neigh_routers to false for the Interconnect topology.

- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_iptables.go
- go-controller/pkg/node/gateway_localnet_linux_test.go
Three fixes:
- ~`Improve egress service repair unit test`: adds a third Service to the test and adjusts the initial incorrect state to make use of it, because there wouldn't be any way to make the initial state have multiple incorrect rules _for the same endpoint_ in the upcoming nftables version.~ (EDIT: This got merged as part of #4893)
- `Fix some nftables checking in the unit tests`: in half of the tests we were doing `err = nodenft.MatchNFTRules(...)` but then not checking `err` afterward. (This fix didn't turn up any new bugs; presumably if the generated rules were wrong before, the e2es would have failed and we would have noticed that way.) (EDIT: most of this got fixed as part of #4939.)
- `Slightly fix UDN local gateway masquerade rules (and unit tests)`: don't depend on …
> Small iptables/nftables fixes

- test/e2e/e2e.go
- test/e2e/egress_firewall.go
- test/e2e/external_gateways.go
- test/e2e/multi_node_zones_interconnect.go
- test/e2e/node_ip_mac_migration.go
- test/e2e/util.go
More fixes pulled out of @martinkennelly 's branch to start adding support for running ovn-k e2e downstream in OCP. This just takes a bunch of places where the test cases were doing something and ignoring possible errors, and changes them to assert that an error didn't occur instead.
(In theory, this should not result in us discovering any new bugs in the _existing_ code, since if something actually went wrong, the test would presumably fail later on anyway. It just means that in case of _future_ bugs, the tests should fail closer to the point where something actually went wrong, rather than failing more mysteriously later.)
```release-note
NONE
```
> Add some more ExpectNoError checks to the e2e tests

- docs/okeps/okep-4380-network-qos.md
The current EgressQoS is tied to pod's egress traffic and may be used only for DSCP marking. so this enhances the CR to be more generic enough so that it can be easily extended for applying QoS for both east west and north south traffic and supporting traffic policing and shaping.
> Enhance EgressQoS CR as a generic QoS feature

- contrib/kind.sh
PR [0] broke podman users, with the following error:
```
find ../../go-controller/_output/go/bin/ -maxdepth 1 -type f -exec cp -f {} . \;
echo "ref: refs/heads/master  commit: dd2a70c928d362a8d471352e7ec6e07164064e9f" > git_info
docker build \
--build-arg OVN_FROM=koji \
--build-arg OVN_REPO= \
--build-arg OVN_GITREF= \
-t localhost/ovn-daemonset-fedora:dev \
-f Dockerfile.fedora .
make: docker: No such file or directory
```
By passing along the `OCI_BIN` variable, we make podman users happy again.
[0] - https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4899
Fixes #
Using podman runtime, deploy a kind cluster. It should work with this PR, but fail without it.
> build, images: pass the OCI_BIN variable to the img building scripts

- go-controller/pkg/networkmanager/network_controller.go
Currently network controllers give up at 15 tries on an object. Since zone/node controllers wait on cluster manager to populate node information, and cluster manager may lag behind other controllers, it can result in some UDNs never getting rendered if a controller gives up. This leads to a state where the UDN never came up, and pods are infinitely retrying and failing to start.
> Make network controllers have infinite attempts

- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/udn/primary_network.go
- go-controller/pkg/cni/udn/primary_network_test.go
The log message looked like this:
2025-02-14T00:49:29.504280050Z E0214 00:49:29.504252 2349982 primary_network.go:77] Failed ensuring user defined primary network for nad 'default': failed looking for primary network annotation for nad 'default': missing network annotation with primary role 'map[k8s.ovn.org/pod-networks:{"default":{"ip_addresses":["10.131.6.22/23"],"mac_address":"0a:58:0a:83:06:16","routes":[{"dest":"10.128.0.0/14","nextHop":"10.131.6.1"},{"dest":"100.64.0.0/16","nextHop":"10.131.6.1"}],"ip_address":"10.131.6.22/23","role":"infrastructure-locked"}} openshift.io/scc:restricted-v2 seccomp.security.alpha.kubernetes.io/pod:runtime/default]'
The primary network is always going to be nad "default", so there is no point in printing that a bunch of times. Also the log was missing …
> Fixes CNI primary udn log message

- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/master.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
These things were constantly being executed on every node update. Bring them inline with what we do for other node syncs, keep a cache of what needs to be sync'ed. The impact of this was especially bad for UDN.
> Perf improvement: egress ip/qos reroute rules

- go-controller/pkg/ovn/base_network_controller_secondary.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/ovn.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/ovn/secondary_layer3_network_controller.go
- go-controller/pkg/util/node_annotations.go
We were seeing this error in downstream a lot:
2025-02-14T00:49:29.505243189Z E0214 00:49:29.505221 2349982 ovn.go:423] Failed to unmarshal old node ip-10-0-50-90.us-west-2.compute.internal annotation: unexpected end of JSON input
This was coming from the macAddressChanged function. I realized there is no point in checking if the mac address changed, as we do not store it anymore on the node annotation. The only use for it is for reading it on the default network controller if it existed for legacy reasons.
Also, some minor fixes to nodeSubnetChanged.
> Removes checking for mac address changes, minor fixes to nodeSubnetChanged

- dist/images/ovnkube.sh
This PR fixes the issue of user provided OVN_V4_MASQUERADE_SUBNET and OVN_V6_MASQUERADE_SUBNET options not getting set during ovn-node initialization. 
Fixes #
> Parse masquerade_subnet option during ovn-node initialization

- helm/ovn-kubernetes/charts/ovnkube-identity/values.yaml
This PR adds the podAntiAffinity rule for ensuring that only one instance of ovnkube-identity pod is scheduled per node
Fixes #
> Add podAntiAffinity rule to ovnkube-identity deployment

- docs/features/multiple-networks/multi-homing.md
This PR is adding a missing reference to the physicalNetworkName when configuring localnet topology.
Fixes #
> docs/multi-homing: Add missing physicalNetworkName reference

- go-controller/pkg/node/ovspinning/ovspinning_linux.go
- go-controller/pkg/node/ovspinning/ovspinning_linux_test.go
A configuration manager like the `machine-config-operator` is often used to enable the OVS CPU pinning feature. During reconciliation loop, the configurator might remove and recreate a file for a very short time. When it comes to the `/etc/openvswitch/enable_dynamic_cpu_affinity` file, it might disable the CPU pinning permanently and an ovnkube-controller restart is needed.
Make the OVS CPU pinning be enabled without restarting `ovnkube-controller` pod. Watch the parent folder instead of the enabler file because if the file gets deleted, the file watch will not emit any further fsevent.
Fixes #
> ovspinning: Enable the feature at runtime

- dist/templates/k8s.ovn.org_egressservices.yaml.j2
- go-controller/pkg/crd/egressservice/v1/types.go
We add the current host as a printerColumn to have a nicer way to understand which node is hosting the service:
```
$ kubectl get egressservice
NAME              ASSIGNED HOST
example-service   ovn-worker
```
> EgressService: add additionalPrinterColumn for .status.host

- go-controller/pkg/clustermanager/routeadvertisements/controller.go
- go-controller/pkg/clustermanager/routeadvertisements/controller_test.go
- go-controller/pkg/factory/factory.go
- go-controller/pkg/networkmanager/api.go
- go-controller/pkg/networkmanager/nad_controller.go
- go-controller/pkg/testing/networkmanager/fake.go
Add support to advertise EIPs for UDNs in cluster manager
RouteAdvertisements controller. 
Selected Egress IPs are those that 
- are served on the same namespaces as where the selected
networks are serving, and
- are assigned to a selected node
- ~~are on the default network subnet for that node~~
Egress IPs, just as with Pod IPs, will be advertised on routers
on the target VRF on the selected nodes.
`auto` is not supported as target VRF for Egress IPs.
**Better** support for Egress IPs on subnets other that the default network
node subnet, **including support** VRF-Lite interface subnets, is left for a future
exercise. We would need cluster manager to be able to:
- map non VRF-Lite interface subnets to the proper BGP sessions
- tell apart VRF-Lite interface subnets from other secondary …
> Add support to advertise EIPs for UDNs

- test/e2e/localnet-underlay.go
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
This PR adds e2e tests asserting that after a consistent network config change, and subsequent workload "restart", the restarted workload is configured w/ the updated configuration.
updated fields checked:
- MTU
- VLAN-ID
- excluded IPs
Fixes #
> multihoming: Add NAD reconciliation e2e tests

- contrib/kind-common
The KubeVirt version v1.5.0 is breaking tcp connections at live migration during our e2e tests, this change ping kubevirt to last known good version v1.4.0
https://github.com/kubevirt/kubevirt/releases/tag/v1.5.0
Closes https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5116
NONE
> kind: Pin kubevirt to v1.4.0

- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
Marking `physicalNetworkName` changes as not reconcilable will lead the network controller to dispose of the old network controller, and instantiate a new one, thus reacting to the configuration update - [0].
[0] - https://github.com/ovn-kubernetes/ovn-kubernetes/blob/562f752b01c5d4a1d8ee4b5b3cfebb047f4cad7a/go-controller/pkg/networkmanager/network_controller.go#L281
Fixes #
> net controller: reconcile on physical net name updates

- go-controller/pkg/allocator/ip/allocator.go
- go-controller/pkg/allocator/ip/subnet/allocator.go
- go-controller/pkg/clustermanager/pod/allocator.go
- go-controller/pkg/clustermanager/pod/allocator_test.go
- go-controller/pkg/ovn/base_network_controller_pods.go
When there are no available IP addresses in the IP pool, there is no
indication sent to the pod, and it ends up hanging with the generic
warning event: failed to get pod annotation.
Adding an event indicating the lack of available IP in the pool as the
cause for the failure.
Fixes #
https://issues.redhat.com/browse/CNV-45757
The changes are made to the cluster-manager (for l2 ip allocation) and node-controller (for l3 ip allocation)
1. Create a namespace
```
kubectl create ns localnet-ipam
```
2. Create a NAD with a small IP range. example:
```
cat << EOF | oc create -f - 
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
name: ipam-localnet-nad
namespace: localnet-ipam
spec:
config: |
{
"cniVersion": "0.4.0",
"name": "tenantblue-network",
"type": …
```
> udn: Add event when ip range full

- dist/images/ovnkube.sh
ovs-appctl is used to exit northd when SIGTERM is notified, but northd can be stopped by ov"n"-appctl not ov"s"-appctl.
With the existing code, northd is not stopped gracefully when SIGTERM is notified, and may be killed after graceful period.
Fixes #
> dist/images: fix cleanup command for northd

- contrib/kind-common
- test/e2e/e2e.go
- test/e2e/network_segmentation.go
- test/e2e/route_advertisements.go
Adds e2e test for layer3UDN advertised using BGP. Currently this test is skipped on SGW mode because of a known bug: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5095
> Add BGP Tests: Phase2

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/node_ip_handler_linux.go
- go-controller/pkg/node/openflow_manager.go
- go-controller/pkg/types/const.go
- test/e2e/kubevirt.go
- test/e2e/localnet-underlay.go
- test/e2e/multihoming.go
- test/e2e/multihoming_utils.go
- test/e2e/network_segmentation.go
- test/e2e/network_segmentation_policy.go
Add flows at prio=102 to allow traffic from the OVN network to the host network to be handled normally by the bridge instead of forwarding it directly to the NIC (which would be done by the flow at prio=100). This allows pods in the default network to reach localnet pods on the same node.
Add e2e tests to check connections from default network to localnet on different nodes and on the same node.
Testing downstream here: https://github.com/openshift/ovn-kubernetes/pull/2467
Follow-up PR for localnet->host: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5093 
Fixes #OCPBUGS-43004
> Allow default network pods to reach localnet on the same node

- test/e2e/kubevirt.go
- test/e2e/multihoming_utils.go
The current localnet kubevirt live migration tests are implemented using persistent IPs, this change add similar version of those tests but for ipamless localnet where VMI and pod IPs are statically assigned.
> kubevirt, e2e: Add localnet ipamless live migration

- dist/images/Dockerfile.fedora
Use the OVS RPMs built from source.
cc @dceara
> Copy OVS RPMs to be installed when building from source

- go-controller/pkg/allocator/pod/pod_annotation.go
- go-controller/pkg/allocator/pod/pod_annotation_test.go
- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/pod/allocator.go
- go-controller/pkg/clustermanager/pod/allocator_test.go
- go-controller/pkg/ovn/base_network_controller_pods.go
- go-controller/pkg/util/pod_annotation.go
- go-controller/pkg/util/pod_annotation_unit_test.go
For primary UDN layer2 the proper IPv6 gateway that should be configured
with received router advertisements is the one from the local GR IPv6
LLA, this change add field to the ovn pod annotations with that
information so it can be consumed by follow up PRs that will ensure
remove GRs are ignore as layer2 ipv6 gateways.
This is related to the following PRs that remove multipath ipv6 gateway for l2 primary UDNs:
https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4852
https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4847
Based on https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4866, just finalizing it.
Thanks @qinqon
Fixes #
> l2, udpn: Add ipv6 lla gateway field to the ovn pod annotation

- test/e2e/route_advertisements.go
Currently handles only L3 networks.
There will be a followup change adding an entry for L2 networks.
> Add E2Es for testing isolation around BGP advertised networks

- .github/workflows/test.yml
- contrib/kind-common
- contrib/kind-helm.sh
- contrib/kind.sh
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/ovnkube-control-plane.yaml
- helm/ovn-kubernetes/charts/ovnkube-control-plane/templates/rbac-ovnkube-cluster-manager.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/deployment-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-master/templates/rbac-ovnkube-master.yaml
- helm/ovn-kubernetes/charts/ovnkube-node/templates/ovnkube-node.yaml
- helm/ovn-kubernetes/charts/ovnkube-single-node-zone/templates/ovnkube-single-node-zone.yaml
- helm/ovn-kubernetes/charts/ovnkube-zone-controller/templates/ovnkube-zone-controller.yaml
- helm/ovn-kubernetes/crds/k8s.ovn.org_clusteruserdefinednetworks.yaml
- helm/ovn-kubernetes/crds/k8s.ovn.org_routeadvertisements.yaml
- helm/ovn-kubernetes/crds/k8s.ovn.org_userdefinednetworks.yaml
- helm/ovn-kubernetes/templates/rbac-ovnkube-node.yaml
- helm/ovn-kubernetes/values-multi-node-zone.yaml
- helm/ovn-kubernetes/values-no-ic.yaml
- helm/ovn-kubernetes/values-single-node-zone.yaml
- test/scripts/install-kind.sh
This PR includes changes needed in order to support deploying ovn-kubernetes via helm with UDN feature.
Fixes https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5147
```
❯ cd contrib && ./kind-helm.sh --help | grep -C2 -i segm
[ -ikv | --install-kubevirt ]
[ -mne | --multi-network-enable ]
[ -nse | --network-segmentation-enable ]    <---- new 
[ -wk  | --num-workers <num> ]
[ -ic  | --enable-interconnect]
--
-ikv | --install-kubevirt            Install kubevirt
-mne | --multi-network-enable        Enable multi networks. DEFAULT: Disabled
-nse | --network-segmentation-enable Enable network segmentation. DEFAULT: Disabled
-ha  | --ha-enabled                  Enable high availability. DEFAULT: HA Disabled
-wk  | --num-workers                 Number of worker nodes. DEFAULT: 2 workers 
❯ …
```
> Support network segmentation via helm

- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- go-controller/pkg/node/routemanager/route_manager.go
- go-controller/pkg/node/routemanager/route_manager_test.go
- go-controller/pkg/node/secondary_node_network_controller_test.go
- go-controller/pkg/node/vrfmanager/vrf_manager.go
- go-controller/pkg/types/const.go
Add or remove default route from a vrf device based on the network is advertised on its own network or default network.
Default route from a VRF corresponding to a UDN does not get removed if the network is advertised on default VRF.
default via 172.18.0.1 dev breth0 mtu 1400
Fixes #
> Remove default route if UDN network is advertised on its own VRF

- go-controller/pkg/ovn/routeimport/route_import.go
- go-controller/pkg/ovn/routeimport/route_import_test.go
Route import for CUDNs with names <= 15 characters would fail when the route import controller becomes aware of the network before the VRF exists. 
The VRF name is the same as the CUDN name but the logic did not account for the "cluster_udn_" prefix that is added to the network name.
> routeimport: account for CUDN network name prefix

- dist/templates/ovnkube-identity.yaml.j2
- helm/ovn-kubernetes/charts/ovnkube-identity/templates/ovnkube-identity.yaml
- helm/ovn-kubernetes/charts/ovnkube-identity/values.yaml
Ovnkube-identity pods should run on all control-plane nodes and require that a newly created pod is fully functional before the old one can be terminated and hence require additional pods during upgrades
Fixes #
> Convert to DaemonSet and fix update strategy of ovnkube-identity pods

- go-controller/go.mod
- go-controller/pkg/kubevirt/pod.go
- go-controller/pkg/ovn/secondary_layer2_network_controller.go
- go-controller/pkg/util/ndp/ra.go
- test/e2e/kubevirt.go
- test/e2e/kubevirt/net.go
- test/e2e/kubevirt/types.go
At current layer2 topology each node has gateway router ipv6 link local ip and mac addresses, this end up with a multipath ipv6 defaujl gateways at VMs.
This change send a router advertisment with lifetime 0 to remove the ipv6 default gw path using the node where the VM was running before migration and send another one with lifetime max with the gw path where the VM is currently running after migration (after live migration the VM is not going to send a router solicitation so the router advertisment should be generated from ovn-k).
Fixes https://issues.redhat.com/browse/SDN-5424
Note that another [PR](https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4852) that uses nftables to block RAs from external nodes is in progress, this PR should work in conjuntion with that.
Also note that …
> kubevirt, l2, udpn: send unsolicited router advertisement after live migration to reconcile ipv6 default gw

- go-controller/pkg/clustermanager/routeadvertisements/controller.go
- go-controller/pkg/clustermanager/routeadvertisements/controller_test.go
BGP routes will be imported to the UDN VRF and GR, when EgressIP for the UDN is advertised to the default VRF. This ensures that the egress traffic can find the right egress route.
Fixes #
1. Create a CUDN
2. Create a namespace that uses the CUDN as the primary network.
3. Create an EIP that selects the pods in the namespace
4. Create an RA that selects the CUDN and only advertises the EIP to the default VRF
5. Create a FRRConfiguration that can connect to an external BGP router. The BGP router is different from the default route of the node.
6. Create a test pod in the namespace. And try to curl an external host that is only reachable via the BGP router.
> Import BGP routes to UDN when EgressIP is advertised

- go-controller/pkg/cni/helper_linux.go
- go-controller/pkg/cni/helper_linux_test.go
- test/e2e/kubevirt.go
IPv6 Router Advertisements from non-local sources can interfere with primary UDN interfaces
in multi-gateway setups, resulting in multiple default gateways.
To resolve this, ingress filtering was added using nftables to block unwanted RAs,
allowing only RAs from the node's local gateway and RAs with Lifetime 0,
which are needed to invalidate entries during migration.
The PR include tests
> UDN: Filter RA according local GW Router LLA only to avoid multi path

- contrib/kind-helm.sh
- docs/features/infrastructure-security-controls/node-identity.md
- docs/installation/launching-ovn-kubernetes-with-helm.md
- helm/ovn-kubernetes/README.md.gotmpl
- helm/ovn-kubernetes/values-multi-node-zone.yaml
- helm/ovn-kubernetes/values-no-ic.yaml
- helm/ovn-kubernetes/values-single-node-zone.yaml
- test/scripts/upgrade-ovn.sh
Starting from:
https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5146 ovnkube-identity pods are now created via a DaemonSet.
The test in upgrade-ovn.sh needed to be updated accordingly.
Fixes: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5183
> upgrade-ovn.sh: ovnkube-identity is now a DaemonSet

- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- test/e2e/route_advertisements.go
The PR is based on https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5167. 
An important caveat is that these rules will also block the VRF from accessing the UDN subnets.
> Block local processes from accessing advertised UDNs

- dist/READMEcontainer.md
- docs/developer-guide/image-build.md
- docs/installation/launching-ovn-kubernetes-on-kind.md
- docs/installation/launching-ovn-kubernetes-with-helm.md
- docs/observability/ovn-observability.md
- helm/basic-deploy.sh
- helm/ovn-kubernetes/README.md
- helm/ovn-kubernetes/README.md.gotmpl
Fixes #
It seems that the build commands for container images of ubuntu and fedora were changed in the https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4899, but this did not seem to be reflected in the docs and script, so fix it.
> Fix the commands for image build in the docs and script.

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cni/cni.go
- go-controller/pkg/cni/cni_test.go
- go-controller/pkg/cni/cniserver.go
- go-controller/pkg/cni/cniserver_test.go
- go-controller/pkg/cni/types.go
- go-controller/pkg/controllermanager/node_controller_manager.go
- go-controller/pkg/controllermanager/node_controller_manager_test.go
- go-controller/pkg/node/base_node_network_controller_dpu_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/ovn_test.go
- test/e2e/multihoming.go
For localnet, the ovs `external_ids:ovn-bridge-mappings` should have entry for the network 
(either name, or physicalNetworkName if used). 
Validate it.
Fixes #
> localnet: Make sure bridge mapping is valid

- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
This change fixes a case where we add a network that is already advertised. We should configure the missing bits on startup too, not only during reconciliation.
I was wondering about extracting and reusing the code already present in `doReconcile` but it is going to require some refactor around `udng.gateway.Reconcile` that also calls `openflowManager.updateBridgeFlowCache` so I want to defer that for the future. 
cc: @tssurya @arghosh93 @jcaamano
> Configure isolation and routes during network addition

- go-controller/pkg/node/gateway.go
- go-controller/pkg/node/gateway_shared_intf.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
- test/e2e/route_advertisements.go
Currently the behaviour of an advertised UDN is that
UDN pods are able to talk any service in the default
network in local gateway mode.
Expected behaviour is that advertised UDN pods should
only be able to reach kapi and dns services in the
default network and rest of them should not be
reachable.
Solution adopted is to change all the relevant flows
that were using masIP subnet for services isolation
on br-ex to use the podsubnets.
Caveat is: if user advertises overlapping podSubnets
then things will fall apart and assumption is users
can't do that.
Flow details (post fix I don't want to call out the
current behaviour to avoid confusions -> current behaviour
was using the default network flows for UDN pods which was
wrong):
Onward packet
1) cookie=0xdeff105, duration=1472.742s, table=0, …
> Isolate default network services from UDN pods

- go-controller/cmd/ovnkube/ovnkube.go
- go-controller/pkg/cni/cni.go
This PR fixes the issue of ovs client being incorrectly initialized for dpuhosts introduced by https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5145
Fixes #
> ovs client shouldn't be initialized on DPU Hosts

- go-controller/pkg/libovsdb/libovsdb.go
- go-controller/pkg/libovsdb/ops/chassis.go
- go-controller/pkg/libovsdb/ops/chassis_test.go
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/ovn/default_network_controller.go
- go-controller/pkg/ovn/zone_interconnect/chassis_handler.go
- go-controller/pkg/ovn/zone_interconnect/chassis_handler_test.go
- go-controller/pkg/ovnwebhook/nodeadmission.go
- go-controller/pkg/util/node_annotations.go
This PR adds support for handling user provided encap IPs in remote nodes during OVN IC mode operation
Fixes #
>  OVN IC mode should handle user provided encapIPs

- go-controller/pkg/node/controllers/egressip/egressip.go
- go-controller/pkg/node/controllers/egressip/egressip_test.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/routemanager/route_manager.go
- go-controller/pkg/node/routemanager/route_manager_test.go
- go-controller/pkg/util/net.go
For a number of reasons:
1. Performance
With BGP the number of routes that can be installed on the system scales
up. Tests with > 1500 routes cause trouble. The current sync
implementation has exponential loops. On each iteration,
RouteListFiltered is called which dumps all the routes on the system and
then filters client side. netlink API is by value, and this causes high
GC crunch.
Changed sync implementation to have sequential loops and a single list
call to netlink. Changed to avoid listing routes in any other case.
sync is still a heavy operation that keeps a lock and migh require
further optimizations. This is a first take.
2. Consistency
The used RoutePartiallyEqual had a different criteria than what was used
to actually delete a route from netlink, leaving the door open for …
> Refactor routemanager

- mkdocs.yml
This is a follow up change for https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4508
In that PR, I failed to include the okep under https://ovn-kubernetes.io/okeps/
> docs,okeps: Network QoS

- go-controller/pkg/clustermanager/routeadvertisements/controller.go
- go-controller/pkg/clustermanager/routeadvertisements/controller_test.go
Show a warning message in the status of the RouteAdvertisements CR when a RouteAdvertisements advertise EIP for L2 UDNs.
Fixes #
Create a RouteAdvertisements that selects L2 UDNs and advertises egress IP.
> Show warning message when a RouteAdvertisements advertise EIP for L2 UDNs

- go-controller/pkg/ovn/controller/network_qos/network_qos_controller.go
shut down `nqosNodeQueue` when network qos controller stops, otherwise nad controller may leave stale data in northbound db.
> shut down nqosNodeQueue when nqos controller stops

- docs/installation/launching-ovn-kubernetes-on-kind.md
fixing spaces not tolerable by markdown parsers
specially last bullet under Prerequisites here [link ](https://ovn-kubernetes.io/installation/launching-ovn-kubernetes-on-kind/)
- kubectl - Python and pip - jq - openssl - openvswitch
should be
- kubectl 
- Python and pip 
- jq 
- openssl 
- openvswitch
Signed-off-by: Anurag Saxena [anusaxen@redhat.com](mailto:anusaxen@redhat.com)
> formatting fix for "launching-ovn-kubernetes-on-kind"

- go-controller/pkg/retry/obj_retry.go
In our pod handlers we have code that checks if a pod is scheduled. If the pod is not scheduled, then we do not add the pod to our retry framework. However, there are times where we automatically enqueue all pods on a node or across the cluster. This can be from when a new node comes up (pre-IC) and need to add all pods on that node. Another use case is when a new UDN/NAD is created and the controller spins up...we add all pods then.
We shouldn't be queuing pods to the retry framework that are not scheduled. It's a waste of operations. However, even if we do enqueue them, we definitely should not be treating a non-scheduled resource as an error and retrying it again later.
This commit changes the retry framework to detect the above case, and log an error. It does not trigger retrying of …
> Do not retry pods that are not scheduled

- go-controller/pkg/clustermanager/network_cluster_controller.go
- go-controller/pkg/clustermanager/node/node_allocator.go
Introduced in 836ec3680aa33300d631b3e7f3bd3069bbfed2b9
This would just cause node updates to fire HandleAddUpdateNodeEvent everytime as the code prior to the aforementioned commit would have.
> Fix node update check for network cluster controller

- go-controller/pkg/config/config.go
- go-controller/pkg/config/utils.go
- go-controller/pkg/libovsdb/ops/router.go
- go-controller/pkg/ovn/gateway_test.go
- go-controller/pkg/ovn/namespace_test.go
There was a previous bug where when an egress packet would be SNAT'ed to the node IP, using a nodeport source port, it would cause reply traffic to get DNAT'ed to the nodeport load balancer. This happened because the egress connections were not conntracked correctly.
This was fixed via:
https://issues.redhat.com/browse/OCPBUGS-25889
https://issues.redhat.com/browse/FDP-291
However, that fix was not hardware offloadable. The ideal fix here would be to always commit to conntrack and have it be HW offloadable. Until we have a better solution, we can configure the port range for OVN to use on its SNAT. This applies to all SNATs for traffic that enters the local host or leaves the host.
The new config option --ephemeral-port-range "<minPort>-<maxPort>" can be used to specify the port range to …
> Configures ephemeral port range for OVN SNAT'ing

- go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template.go
- go-controller/pkg/clustermanager/userdefinednetwork/template/net-attach-def-template_test.go
When a CUDN/UDN is create with joinSubnets field configured it should generate the net-attach-def with `joinSubnet` field, the code was using `joinSubnets` wich is not undertood by ovn-kubernetes.
Fixes #https://issues.redhat.com/browse/OCPBUGS-56418
Run UDN with joinSubnets configured it should have that subnet at the ovn topology.
> udn: Fix NAD template for join subnets field

- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
When an UDN is advertised to a non default VRF, we shall not add the ip rule to the default VRF. Otherwise if another UDN is advertised to the default VRF with the same subnet. The ingress traffic intended for the second UDN cannot be correctly routed to its respective VRF.
1. Create UDN-A. Configure VRF-lite for a UDN-A
2. Create UDN-B with the same subnet as UDN-A. Make sure the node-subets from both UDNs are the same for a node.
3. Advertise UDN-B to the default VRF.
4. Create pod-a and pod-b connect to UDN-A and UDN-B respectively. Make sure pod-a and pod-b are scheduled to the same node.
5. Try to access an external host from pod-b in UDN-B.
> Add the IP rule for a UDN only when it is advertised to the default VRF

- go-controller/pkg/config/cni.go
- go-controller/pkg/networkmanager/nad_controller.go
- go-controller/pkg/networkmanager/nad_controller_test.go
- go-controller/pkg/util/multi_network.go
- go-controller/pkg/util/multi_network_test.go
If NADs like bridge,macvlan or others exist we should not record an error event for it
Also in case the NAD is not ovn-k for example multus we support chain plugins.
> stop adding events to NAD if the network type is not ovn-k

- go-controller/pkg/node/gateway_shared_intf.go
- test/e2e/route_advertisements.go
When we did the NFT rules to block traffic
going from host to advertised UDN pod
subnets, we did not mean to also block
replies from host to advertised UDN pod
subnets for traffic initiated by UDN pods.
Given the rules lie in OUTPUT table this would
match on replies as well, so traffic like
pod to kube-apiserver host-networked pod backend
is broken because of this.
Let's change the rule to only match on NEW state
which is what we wanted to do in the original
change.
The current rules unintentionally block traffic
in reverse direction.
First step towards getting https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5140
Fixes #
Note that the L2 Advertised UDNs behave differently and this traffic (UDN advertised pod to other node) doesn't work because of assymmetry reasons. However the …
> [UDN,BGP] Fix the host drop rules to match on new state

- go-controller/pkg/node/gateway_init.go
- go-controller/pkg/node/gateway_init_linux_test.go
- go-controller/pkg/node/gateway_udn.go
- go-controller/pkg/node/gateway_udn_test.go
Convert `.` path separators to `/` when enabling forwarding for bridgeName, interfaceName and mgmtPortName to avoid errors when those names contain `.` characters, e.g. `foo.200`
Fixes: #5283
> Use forward slash as path separator for some sysctl commands

- contrib/kind-helm.sh
Modified line 277 to let kind-helm.sh run also behind a proxy
Added the following piece of code in the kind-helm.sh script to run the build of the Dockerfile.fedora also behind a proxy:
``` bash
$OCI_BIN build \
--build-arg http_proxy="$http_proxy" \
--build-arg https_proxy="$https_proxy" \
--network=host \
-t "${OVN_IMAGE}" \
-f Dockerfile.fedora .
```
> Modified line 277 to let kind-helm.sh run also behind a proxy

- docs/features/hardware-offload/derive-from-mgmt-port.md
- docs/features/hardware-offload/dpu-gateway-interface.md
- docs/features/hardware-offload/dpu-support.md
- docs/installation/ovn_k8s.conf.5
- go-controller/pkg/node/default_node_network_controller.go
- go-controller/pkg/node/default_node_network_controller_test.go
- go-controller/pkg/types/const.go
This patch introduces a new way to detect the gateway interface in the case ovnkube is running in DPU-HOST mode.
Introduce the argument `derive-from-mgmt-port`, if this is specified as the gateway interface, we will identify the physical function of the device used as an management port accelerated interface.
Signed-off-by: Alin Gabriel Serdean <aserdean@nvidia.com>
Fixes: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5239
> ovnkube in dpu host mode: advanced gateway detection

- dist/images/Dockerfile.ubuntu
- dist/images/Dockerfile.ubuntu.arm64
This PR updates Ubuntu image version to 25.04 to get in box OVN version 25.03
Fixes #
> Bump ubuntu version to 25.04
